DROP TABLE TBEP_HTO_TITULACIONESPREFERENTESAREA;
--/////////////////////
DROP TABLE TBEP_TITULACIONESPREFERENTESAREA;
--/////////////////////
DROP SEQUENCE QBEP_TPA;
--/////////////////////
DROP SEQUENCE QBEP_HTO_TPA;