DROP TABLE TBEP_HTO_TITULACIONES_PREFERENTES_AREA;
--/////////////////////
DROP TABLE TBEP_TITULACIONES_PREFERENTES_AREA;
--/////////////////////
DROP SEQUENCE QBEP_TPA;
--/////////////////////
DROP SEQUENCE QBEP_HTO_TPA;