DROP TABLE TBEP_HTO_TIT_PREFERENTES_AREA;
--/////////////////////
DROP TABLE TBEP_TIT_PREFERENTES_AREA;
--/////////////////////
DROP SEQUENCE QBEP_TPA;
--/////////////////////
DROP SEQUENCE QBEP_HTO_TPA;