DROP TABLE TBEP_HTO_CATEGORIABAREMACION;
--/////////////////////
DROP TABLE TBEP_CATEGORIABAREMACION;
--/////////////////////
DROP SEQUENCE QBEP_CAT;
--/////////////////////
DROP SEQUENCE QBEP_HTO_CAT;
