DELETE FROM ARCOS.V_PERSONA_INTRANET WHERE CODINT = 3;
DELETE FROM ARCOS.V_CUENTAS_INTRANET WHERE IDCUENTA = 3;
DELETE FROM ARCOS.V_PERSONA_INTRANET WHERE CODINT = 4;
DELETE FROM ARCOS.V_CUENTAS_INTRANET WHERE IDCUENTA = 4;
DELETE FROM ARCOS.V_PERSONA_INTRANET WHERE CODINT = 5;
DELETE FROM ARCOS.V_CUENTAS_INTRANET WHERE IDCUENTA = 5;