DROP TABLE TBEP_HTO_USUARIOS_EXCLUIDOS_AREA;
--/////////////////////
DROP TABLE TBEP_USUARIOS_EXCLUIDOS_AREA;
--/////////////////////
DROP SEQUENCE QBEP_HTO_USU_EXC_ARE;
--/////////////////////
DROP SEQUENCE QBEP_USU_EXC_ARE;