DROP TABLE TBEP_HTO_TITULACIONES_USUARIO;
--/////////////////////
DROP TABLE TBEP_TITULACIONES_USUARIO;
--/////////////////////
DROP SEQUENCE QBEP_TIT_USU;
--/////////////////////
DROP SEQUENCE QBEP_HTO_TIT_USU;