DROP TABLE TBEP_HTO_MERITOS_PREFERENTES_OPCIONES;
--/////////////////////
DROP TABLE TBEP_MERITOS_PREFERENTES_OPCIONES;
--/////////////////////
DROP TABLE TBEP_HTO_MER_PRE_OPCIONES;
--/////////////////////
DROP TABLE TBEP_MER_PRE_OPCIONES;
--/////////////////////
DROP SEQUENCE QBEP_MPO;
--/////////////////////
DROP SEQUENCE QBEP_HTO_MPO;