DROP TABLE TBEP_HTO_SOLICITUD_BOLSAS_MERITOS_VALORACION;
--/////////////////////
DROP TABLE TBEP_SOLICITUD_BOLSAS_MERITOS_VALORACION;
--/////////////////////
DROP SEQUENCE QBEP_SBV;
--/////////////////////
DROP SEQUENCE QBEP_HTO_SBV;