DROP TABLE TBEP_HTO_SOLICITUD_BOLSAS_MERITOS;
--/////////////////////
DROP TABLE TBEP_SOLICITUD_BOLSAS_MERITOS;
--/////////////////////
DROP TABLE TBEP_HTO_SOL_BOL_MERITOS;
--/////////////////////
DROP TABLE TBEP_SOL_BOL_MERITOS;
--/////////////////////
DROP SEQUENCE QBEP_SBM;
--/////////////////////
DROP SEQUENCE QBEP_HTO_SBM;