DROP TABLE TBEP_HTO_PARAMETROS_CONFIGURACION;
--/////////////////////
DROP TABLE TBEP_PARAMETROS_CONFIGURACION;
--/////////////////////
DROP SEQUENCE QBEP_PAC;
--/////////////////////
DROP SEQUENCE QBEP_HTO_PAC;