DROP TABLE TBEP_HTO_MERITOS_PREFERENTES_USUARIO;
--/////////////////////
DROP TABLE TBEP_MERITOS_PREFERENTES_USUARIO;
--/////////////////////
DROP SEQUENCE QBEP_MPU;
--/////////////////////
DROP SEQUENCE QBEP_HTO_MPU;