#!groovy

pipeline {
    agent any

    environment {
        APP_LISTENING_PORT = "8080"
        TEST_CONTAINER_NAME = "ci-${APP_NAME}-${BUILD_NUMBER}"
    }

    stages {
		stage('Compile') {
			steps {
	        	mail bcc: '', 
	            	 body: "Subida nueva version de uv-externo \n Construccion en: ${BUILD_URL}",
	             	 cc: '', from: '', replyTo: '', 
	             	 subject: "Iniciando jenkins pipeline ${JOB_NAME} (${BUILD_NUMBER}) ",
	             	 to: 'jmoral@ujaen.es'
	        	echo 'Inicio compile'
	        	git credentialsId: 'gitlab-jenkins', url: 'https://gitujap.ujaen.es/isoin/uv-externo.git'
	        	withAnt(installation: 'LocalAnt') {
		            sh "ant compile"
	        	}
        	}
    	}
    	stage('Unit tests') {
			steps {
				echo 'Inicio unittest'
	        	//withAnt(installation: 'LocalAnt') {
	        	//    sh "ant test"
	        	//}
	        }
	    }
	    stage('Package') {
	    	steps {
	        	echo 'Inicio package'
	        }
	    }
	    stage('Build docker') {
	    	steps {
	        	echo 'Inicio build docker'
	        }
	    }
	    stage('Test usuario') {
	    	steps {
	        	echo 'Inicio test usuario'
	        }
	    }
	    stage('sonar') {
	    	steps {
		        echo 'Inicio sonar'
		        withSonarQubeEnv('sonar docker') { 
		            withAnt(installation: 'LocalAnt') {
		               sh "ant sonar -Dsonar.projectName=${JOB_BASE_NAME}"
		            }
		        }
	        }        
	    }
	    stage('push docker') {
	    	steps {
	        	echo 'Inicio push docker'
	       	}
    	}        
    }

    post {
        always {
            echo "-=- fin -=-"
        }
    }
}