--/////////////////////
create sequence sec_dct_convocatorias start with 1;
--/////////////////////
create sequence sec_dct_convocatorias_hto start with 1;
--/////////////////////
CREATE TRIGGER TRG_DCT_CONVOCATORIAS_BRI
BEFORE INSERT
ON DCT_CONVOCATORIAS 
FOR EACH ROW
DECLARE
BEGIN
	select sec_dct_convocatorias.nextval
  	into :new.idconvocatoria
 	from dual;	
   	INSERT INTO DCT_CONVOCATORIAS_HTO
     (IDCONVOCATORIA, NOMBRECONVOCATORIA,ESTADO,OBSERVACIONES,FECHALIMITE,FECHACOMISION,LOG, CODCAMBIO)
   	VALUES
     (:new.idconvocatoria, :New.NOMBRECONVOCATORIA, :New.ESTADO, :New.OBSERVACIONES, 
      :New.FECHALIMITE,:New.FECHACOMISION,'AFTER_INSERT', sec_dct_convocatorias_hto.NEXTVAL);
END TRG_DCT_CONVOCATORIAS_BRI;
--/////////////////////
CREATE TRIGGER TRG_DCT_CONVOCATORIAS_BRU
BEFORE UPDATE
ON DCT_CONVOCATORIAS 
FOR EACH ROW
DECLARE
BEGIN
	INSERT INTO DCT_CONVOCATORIAS_HTO
     (IDCONVOCATORIA, NOMBRECONVOCATORIA,ESTADO,OBSERVACIONES,FECHALIMITE,FECHACOMISION,
     LOG, CODCAMBIO)
   	VALUES
     (:Old.IDCONVOCATORIA, :Old.NOMBRECONVOCATORIA, :Old.ESTADO, :Old.OBSERVACIONES, 
      :Old.FECHALIMITE,:Old.FECHACOMISION,'BEFORE_UPDATE', sec_dct_convocatorias_hto.NEXTVAL);   
   	INSERT INTO DCT_CONVOCATORIAS_HTO
     (IDCONVOCATORIA, NOMBRECONVOCATORIA,ESTADO,OBSERVACIONES,FECHALIMITE,FECHACOMISION,
     LOG, CODCAMBIO)
   	VALUES
     (:New.IDCONVOCATORIA, :New.NOMBRECONVOCATORIA, :New.ESTADO, :New.OBSERVACIONES, 
      :New.FECHALIMITE,:New.FECHACOMISION,'AFTER_UPDATE', sec_dct_convocatorias_hto.NEXTVAL);   

END TRG_DCT_CONVOCATORIAS_BRU;
--/////////////////////

CREATE TRIGGER TRG_DCT_CONVOCATORIAS_BRD
BEFORE DELETE
ON DCT_CONVOCATORIAS 
FOR EACH ROW
DECLARE
BEGIN
   	INSERT INTO DCT_CONVOCATORIAS_HTO
     (IDCONVOCATORIA, NOMBRECONVOCATORIA,ESTADO,OBSERVACIONES,FECHALIMITE,FECHACOMISION,LOG, CODCAMBIO)
   	VALUES
     (:Old.IDCONVOCATORIA, :Old.NOMBRECONVOCATORIA, :Old.ESTADO, :Old.OBSERVACIONES, 
      :Old.FECHALIMITE,:Old.FECHACOMISION,'BEFORE_DELETE', sec_dct_convocatorias_hto.NEXTVAL);   

END TRG_DCT_CONVOCATORIAS_BRD;