CREATE TABLE UVIRTUAL.DCT_CONVOCATORIAS(	
	IDCONVOCATORIA NUMBER(11,0) NOT NULL, 
	NOMBRECONVOCATORIA VARCHAR2(255 BYTE) DEFAULT NULL, 
	ESTADO VARCHAR2(15 BYTE), 
	OBSERVACIONES VARCHAR2(1000 BYTE) DEFAULT NULL,  
	FECHALIMITE TIMESTAMP NOT NULL ENABLE,
	FECHACOMISION TIMESTAMP,
	CHECK (estado in('ABIERTA','CREADA','CERRADA')), 
	CONSTRAINT pk_dct_convocatorias PRIMARY KEY (IDCONVOCATORIA)
);
--/////////////////////
CREATE TABLE UVIRTUAL.DCT_CONVOCATORIAS_HTO(
 	CODCAMBIO NUMBER(11) NOT NULL,
 	LOG VARCHAR(50) NOT NULL,
 	FECHALOG TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
	IDCONVOCATORIA NUMBER(11,0) NOT NULL, 
	NOMBRECONVOCATORIA VARCHAR2(255 BYTE) DEFAULT NULL, 
	ESTADO VARCHAR2(15 BYTE), 
	OBSERVACIONES VARCHAR2(1000 BYTE) DEFAULT NULL,  
	FECHALIMITE TIMESTAMP NOT NULL ENABLE,
	FECHACOMISION TIMESTAMP,
	CHECK (estado in('ABIERTA','CREADA','CERRADA')), 
	CONSTRAINT pk_dct_convocatorias_hto PRIMARY KEY (CODCAMBIO)
);
