INSERT INTO adm_parametros (config_codalf, param_codalf, desid, valor) VALUES ( DEFAULT, 'bolsaempleo.urlAyuda', 'url que enlace a la ayuda ', 'https://www.ujaen.es/gobierno/secord/bolsaempleo-academia'); 
INSERT INTO ADM_ROL (rol_codnum, descripcion, valor) VALUES(1050, 'Integrantes del Servicio de Personal', 'bolemppersonal');
INSERT INTO ADM_ROL (rol_codnum, descripcion, valor) VALUES(1051, 'Candidatos', 'bolempcandidato');
INSERT INTO ADM_ROL (rol_codnum, descripcion, valor) VALUES(1052, 'Miembro de la Comision', 'bolempcomision');
INSERT INTO ADM_USUARIO_ROL (USERUID, ROL_CODNUM, FLG_ADMIN) VALUES ('usig', 1050, 'N');
INSERT INTO ADM_USUARIO_ROL (USERUID, ROL_CODNUM, FLG_ADMIN) VALUES ('estudiante1', 1050, 'N');
INSERT INTO ADM_USUARIO_ROL (USERUID, ROL_CODNUM, FLG_ADMIN) VALUES ('personal1', 1050, 'N');
INSERT INTO ADM_USUARIO_ROL (USERUID, ROL_CODNUM, FLG_ADMIN) VALUES ('personal2', 1050, 'N');
INSERT INTO ADM_USUARIO_ROL (USERUID, ROL_CODNUM, FLG_ADMIN) VALUES ('personal3', 1050, 'N');
INSERT INTO ADM_USUARIO_ROL (USERUID, ROL_CODNUM, FLG_ADMIN) VALUES ('personal4', 1050, 'N');
INSERT INTO ADM_USUARIO_ROL (USERUID, ROL_CODNUM, FLG_ADMIN) VALUES ('personal5', 1050, 'N');

INSERT INTO ADM_USUARIO_ROL (USERUID, ROL_CODNUM, FLG_ADMIN) VALUES ('candidato1', 1051, 'N');
INSERT INTO ADM_USUARIO_ROL (USERUID, ROL_CODNUM, FLG_ADMIN) VALUES ('candidato2', 1051, 'N');
INSERT INTO ADM_USUARIO_ROL (USERUID, ROL_CODNUM, FLG_ADMIN) VALUES ('candidato3', 1051, 'N');
INSERT INTO ADM_USUARIO_ROL (USERUID, ROL_CODNUM, FLG_ADMIN) VALUES ('candidato4', 1051, 'N');
INSERT INTO ADM_USUARIO_ROL (USERUID, ROL_CODNUM, FLG_ADMIN) VALUES ('candidato5', 1051, 'N');
INSERT INTO ADM_USUARIO_ROL (USERUID, ROL_CODNUM, FLG_ADMIN) VALUES ('candidato6', 1051, 'N');
INSERT INTO ADM_USUARIO_ROL (USERUID, ROL_CODNUM, FLG_ADMIN) VALUES ('candidato7', 1051, 'N');
INSERT INTO ADM_USUARIO_ROL (USERUID, ROL_CODNUM, FLG_ADMIN) VALUES ('candidato8', 1051, 'N');
INSERT INTO ADM_USUARIO_ROL (USERUID, ROL_CODNUM, FLG_ADMIN) VALUES ('candidato9', 1051, 'N');
INSERT INTO ADM_USUARIO_ROL (USERUID, ROL_CODNUM, FLG_ADMIN) VALUES ('candidato10', 1051, 'N');

INSERT INTO ADM_USUARIO_ROL (USERUID, ROL_CODNUM, FLG_ADMIN) VALUES ('comision1', 1052, 'N');
INSERT INTO ADM_USUARIO_ROL (USERUID, ROL_CODNUM, FLG_ADMIN) VALUES ('comision2', 1052, 'N');
INSERT INTO ADM_USUARIO_ROL (USERUID, ROL_CODNUM, FLG_ADMIN) VALUES ('comision3', 1052, 'N');
INSERT INTO ADM_USUARIO_ROL (USERUID, ROL_CODNUM, FLG_ADMIN) VALUES ('comision4', 1052, 'N');
INSERT INTO ADM_USUARIO_ROL (USERUID, ROL_CODNUM, FLG_ADMIN) VALUES ('comision5', 1052, 'N');