CREATE TABLE UVIRTUAL.TBEP_DEPARTAMENTOS (	
	CODNUM             NUMBER(11,0) NOT NULL, 
	ID_DEPARTAMENTO	   VARCHAR2(8 BYTE) NOT NULL,
	DES_DEPARTAMENTO   VARCHAR2(40 BYTE),
	CONSTRAINT IBEP_PDEP PRIMARY KEY (CODNUM),
	CONSTRAINT IBEP_UDEP_ID_DEPARTAMENTO UNIQUE (ID_DEPARTAMENTO)
);
--/////////////////////
COMMENT ON COLUMN TBEP_DEPARTAMENTOS.ID_DEPARTAMENTO IS 'Id interno del departamento';
--/////////////////////
COMMENT ON COLUMN TBEP_DEPARTAMENTOS.DES_DEPARTAMENTO IS 'Departamento';
--/////////////////////
COMMENT ON TABLE TBEP_DEPARTAMENTOS IS 'Departamentos. ALIAS: [bepdep] ACRONIMO: [DEP]';
--/////////////////////
CREATE TABLE UVIRTUAL.TBEP_HTO_DEPARTAMENTOS (
 	CODCAMBIO          NUMBER(11,0) NOT NULL,
 	LOG 			   VARCHAR(50) NOT NULL,
 	FECHALOG 		   TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
	ID_DEPARTAMENTO    VARCHAR2(8 BYTE) NOT NULL,
	DES_DEPARTAMENTO   VARCHAR2(40 BYTE),
	CONSTRAINT IBEP_PDEP_HISTORICO PRIMARY KEY (CODCAMBIO)
);
--/////////////////////
CREATE SEQUENCE QBEP_DEP START WITH 1;
--/////////////////////
CREATE SEQUENCE QBEP_HTO_DEP START WITH 1;
--/////////////////////
CREATE TRIGGER DBEP_DEP_BRI
BEFORE INSERT
ON TBEP_DEPARTAMENTOS 
FOR EACH ROW
DECLARE
BEGIN
    SELECT QBEP_DEP.nextval into :new.CODNUM FROM dual;	 	  
    INSERT INTO TBEP_HTO_DEPARTAMENTOS (CODCAMBIO,LOG,ID_DEPARTAMENTO,DES_DEPARTAMENTO)
    VALUES (QBEP_HTO_DEP.NEXTVAL,'AFTER_INSERT',:New.ID_DEPARTAMENTO,:New.DES_DEPARTAMENTO);
END DBEP_DEP_BRI;
--/////////////////////
CREATE TRIGGER DBEP_DEP_BRU
BEFORE UPDATE
ON TBEP_DEPARTAMENTOS
FOR EACH ROW
DECLARE
BEGIN
    INSERT INTO TBEP_HTO_DEPARTAMENTOS (CODCAMBIO,LOG,ID_DEPARTAMENTO,DES_DEPARTAMENTO)
    VALUES (QBEP_HTO_DEP.NEXTVAL,'BEFORE_UPDATE',:Old.ID_DEPARTAMENTO,:Old.DES_DEPARTAMENTO);
      	  
    INSERT INTO TBEP_HTO_DEPARTAMENTOS (CODCAMBIO,LOG,ID_DEPARTAMENTO,DES_DEPARTAMENTO)
    VALUES (QBEP_HTO_DEP.NEXTVAL,'AFTER_UPDATE',:New.ID_DEPARTAMENTO,:New.DES_DEPARTAMENTO);
END DBEP_DEP_BRU;
--/////////////////////
CREATE TRIGGER DBEP_DEP_BRD
BEFORE DELETE
ON TBEP_DEPARTAMENTOS
FOR EACH ROW
DECLARE
BEGIN
    INSERT INTO TBEP_HTO_DEPARTAMENTOS (CODCAMBIO,LOG,ID_DEPARTAMENTO,DES_DEPARTAMENTO)
    VALUES (QBEP_HTO_DEP.NEXTVAL,'BEFORE_DELETE',:Old.ID_DEPARTAMENTO,:Old.DES_DEPARTAMENTO);
END DBEP_DEP_BRD;