CREATE TABLE UVIRTUAL.TBEP_AREAS (	
	CODNUM NUMBER(11,0) NOT NULL, 
	NOMBRE VARCHAR2(255 BYTE) NOT NULL,
	CODIGO VARCHAR2(10 BYTE) NOT NULL, 
	CONSTRAINT IBEP_PARE PRIMARY KEY (CODNUM),
	CONSTRAINT IBEP_UARE_CODIGO UNIQUE (CODIGO)
);
--/////////////////////
COMMENT ON COLUMN TBEP_AREAS.NOMBRE IS 'Nombre del area';
--/////////////////////
COMMENT ON COLUMN TBEP_AREAS.CODIGO IS 'Código único del area';
--/////////////////////
COMMENT ON TABLE TBEP_AREAS IS 'Areas del sistema que se asocian a bolsas de trabajo. ALIAS: [bepare] ACRONIMO: [ARE]';
--/////////////////////
CREATE TABLE UVIRTUAL.TBEP_HTO_AREAS (
 	CODCAMBIO NUMBER(11,0) NOT NULL,
 	LOG VARCHAR(50) NOT NULL,
 	FECHALOG TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
	CODNUM NUMBER(11,0) NOT NULL, 
	NOMBRE VARCHAR2(255 BYTE) NOT NULL,
	CODIGO VARCHAR2(10 BYTE) NOT NULL, 
	CONSTRAINT IBEP_PARE_HISTORICO PRIMARY KEY (CODCAMBIO)
);
--/////////////////////
CREATE SEQUENCE QBEP_ARE START WITH 1;
--/////////////////////
CREATE SEQUENCE QBEP_HTO_ARE START WITH 1;
--/////////////////////
CREATE TRIGGER DBEP_ARE_BRI
BEFORE INSERT
ON TBEP_AREAS 
FOR EACH ROW
DECLARE
BEGIN
	SELECT QBEP_ARE.nextval into :new.CODNUM FROM dual;	 	
  
  INSERT INTO TBEP_HTO_AREAS (CODNUM,NOMBRE,CODIGO,LOG,CODCAMBIO)
  VALUES (:New.CODNUM,:New.NOMBRE,:New.CODIGO,'AFTER_INSERT',QBEP_HTO_ARE.NEXTVAL);
END DBEP_ARE_BRI;
--/////////////////////
CREATE TRIGGER DBEP_ARE_BRU
BEFORE UPDATE
ON TBEP_AREAS 
FOR EACH ROW
DECLARE
BEGIN
	INSERT INTO TBEP_HTO_AREAS (CODNUM,NOMBRE,CODIGO,LOG,CODCAMBIO)
 	VALUES (:Old.CODNUM,:Old.NOMBRE,:Old.CODIGO,'BEFORE_UPDATE',QBEP_HTO_ARE.NEXTVAL);    
      	  
  INSERT INTO TBEP_HTO_AREAS (CODNUM,NOMBRE,CODIGO,LOG,CODCAMBIO)
  VALUES (:New.CODNUM,:New.NOMBRE,:New.CODIGO,'AFTER_UPDATE',QBEP_HTO_ARE.NEXTVAL);   
END DBEP_ARE_BRU;
--/////////////////////
CREATE TRIGGER DBEP_ARE_BRD
BEFORE DELETE
ON TBEP_AREAS 
FOR EACH ROW
DECLARE
BEGIN
  INSERT INTO TBEP_HTO_AREAS (CODNUM,NOMBRE,CODIGO,LOG,CODCAMBIO)
  VALUES (:Old.CODNUM,:Old.NOMBRE,:Old.CODIGO,'BEFORE_DELETE',QBEP_HTO_ARE.NEXTVAL);    
END TRG_DCT_CONVOCATORIAS_BRD;