CREATE TABLE UVIRTUAL.TBEP_AREAS (	
	CODNUM                  NUMBER(11,0) NOT NULL, 
    BEPDEP_CODNUM           NUMBER(11,0) NOT NULL,  
    ID_AREA_CONOCIMIENTO   	VARCHAR2(8 BYTE) NOT NULL,
	DES_AREA_CONOCIMIENTO  	VARCHAR2(50 BYTE), 
	CONSTRAINT IBEP_PARE PRIMARY KEY (CODNUM),
    CONSTRAINT IBEP_UARE_ID_AREA_CONOCIMIENTO UNIQUE (ID_AREA_CONOCIMIENTO)
);
--/////////////////////
COMMENT ON COLUMN TBEP_AREAS.ID_AREA_CONOCIMIENTO IS 'Id interno de la área de conocimiento';
--/////////////////////
COMMENT ON COLUMN TBEP_AREAS.DES_AREA_CONOCIMIENTO IS 'Descripción area de conocimiento';
--/////////////////////
COMMENT ON TABLE TBEP_AREAS IS 'Areas del sistema que se asocian a bolsas de trabajo. ALIAS: [bepare] ACRONIMO: [ARE]';
--/////////////////////
CREATE TABLE UVIRTUAL.TBEP_HTO_AREAS (
 	CODCAMBIO NUMBER(11,0) NOT NULL,
 	LOG VARCHAR(50) NOT NULL,
 	FECHALOG TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
	BEPDEP_CODNUM           NUMBER(11,0) NOT NULL,  
    ID_AREA_CONOCIMIENTO    VARCHAR2(8 BYTE) NOT NULL,
    DES_AREA_CONOCIMIENTO   VARCHAR2(50 BYTE), 
	CONSTRAINT IBEP_PARE_HISTORICO PRIMARY KEY (CODCAMBIO)
);
--/////////////////////
CREATE SEQUENCE QBEP_ARE START WITH 1;
--/////////////////////
CREATE SEQUENCE QBEP_HTO_ARE START WITH 1;
--/////////////////////
CREATE TRIGGER DBEP_ARE_BRI
BEFORE INSERT
ON TBEP_AREAS 
FOR EACH ROW
DECLARE
BEGIN
    SELECT QBEP_ARE.nextval into :new.CODNUM FROM dual;
    INSERT INTO TBEP_HTO_AREAS (CODCAMBIO,LOG,BEPDEP_CODNUM,ID_AREA_CONOCIMIENTO,DES_AREA_CONOCIMIENTO)
    VALUES (QBEP_HTO_ARE.NEXTVAL,'AFTER_INSERT',:New.BEPDEP_CODNUM,:New.ID_AREA_CONOCIMIENTO,:New.DES_AREA_CONOCIMIENTO);
END DBEP_ARE_BRI;
--/////////////////////
CREATE TRIGGER DBEP_ARE_BRU
BEFORE UPDATE
ON TBEP_AREAS 
FOR EACH ROW
DECLARE
BEGIN
    INSERT INTO TBEP_HTO_AREAS (CODCAMBIO,LOG,BEPDEP_CODNUM,ID_AREA_CONOCIMIENTO,DES_AREA_CONOCIMIENTO)
    VALUES (QBEP_HTO_ARE.NEXTVAL,'BEFORE_UPDATE',:Old.BEPDEP_CODNUM,:Old.ID_AREA_CONOCIMIENTO,:Old.DES_AREA_CONOCIMIENTO);
    INSERT INTO TBEP_HTO_AREAS (CODCAMBIO,LOG,BEPDEP_CODNUM,ID_AREA_CONOCIMIENTO,DES_AREA_CONOCIMIENTO)
    VALUES (QBEP_HTO_ARE.NEXTVAL,'AFTER_UPDATE',:New.BEPDEP_CODNUM,:New.ID_AREA_CONOCIMIENTO,:New.DES_AREA_CONOCIMIENTO);
END DBEP_ARE_BRU;
--/////////////////////
CREATE TRIGGER DBEP_ARE_BRD
BEFORE DELETE
ON TBEP_AREAS 
FOR EACH ROW
DECLARE
BEGIN
    INSERT INTO TBEP_HTO_AREAS (CODCAMBIO,LOG,BEPDEP_CODNUM,ID_AREA_CONOCIMIENTO,DES_AREA_CONOCIMIENTO)
    VALUES (QBEP_HTO_ARE.NEXTVAL,'BEFORE_DELETE',:Old.BEPDEP_CODNUM,:Old.ID_AREA_CONOCIMIENTO,:Old.DES_AREA_CONOCIMIENTO);
END DBEP_ARE_BRD;