CREATE TABLE UVIRTUAL.TBEP_AREAS (	
	CODNUM                  NUMBER(11,0) CONSTRAINT RBEP_NARE_COD_NUM NOT NULL,
    BEPDEP_CODNUM           NUMBER(11,0) CONSTRAINT RBEP_NARE_BEPDEP_CODNUM NOT NULL,    	
    ID_SECCION              VARCHAR2(8 BYTE) CONSTRAINT RBEP_NARE_ID_SECCION NOT NULL,
	ID_AREA_CONOCIMIENTO   	VARCHAR2(8 BYTE) CONSTRAINT RBEP_NARE_ID_AREA_CONOCIMIENTO NOT NULL,
    DES_AREA_CONOCIMIENTO   VARCHAR2(50 BYTE) CONSTRAINT RBEP_NARE_DES_AREA_CONOCIMIENTO NOT NULL,
	CONSTRAINT IBEP_PARE PRIMARY KEY (CODNUM),
    CONSTRAINT IBEP_FARE_DEP FOREIGN KEY (BEPDEP_CODNUM) REFERENCES TBEP_DEPARTAMENTOS (CODNUM),   
    CONSTRAINT IBEP_UARE_ID_AREA_CONOCIMIENTO UNIQUE (ID_AREA_CONOCIMIENTO)
);
--/////////////////////
COMMENT ON COLUMN TBEP_AREAS.BEPDEP_CODNUM IS 'Fk a departamento';
--/////////////////////
COMMENT ON COLUMN TBEP_AREAS.ID_SECCION IS 'Id interno de la sección del area del conocimiento';
--/////////////////////
COMMENT ON COLUMN TBEP_AREAS.ID_AREA_CONOCIMIENTO IS 'Id interno de la área de conocimiento';
--/////////////////////
COMMENT ON COLUMN TBEP_AREAS.DES_AREA_CONOCIMIENTO IS 'Descripción area de conocimiento';
--/////////////////////
COMMENT ON TABLE TBEP_AREAS IS 'Areas del sistema que se asocian a bolsas de trabajo. ALIAS: [bepare] ACRONIMO: [ARE]';
--/////////////////////
CREATE TABLE UVIRTUAL.TBEP_HTO_AREAS (
 	CODCAMBIO NUMBER(11,0) CONSTRAINT RBEP_NARE_HTO_CODCAMBIO NOT NULL,
 	LOG VARCHAR(50) CONSTRAINT RBEP_NARE_HTO_LOG NOT NULL,
 	FECHALOG TIMESTAMP DEFAULT CURRENT_TIMESTAMP CONSTRAINT RBEP_NARE_HTO_FECHALOG NOT NULL,
	BEPDEP_CODNUM           NUMBER(11,0) CONSTRAINT RBEP_NARE_HTO_BEPDEP_CODNUM NOT NULL,  
    ID_SECCION              VARCHAR2(8 BYTE) CONSTRAINT RBEP_NARE_HTO_ID_SECCION NOT NULL,
    ID_AREA_CONOCIMIENTO    VARCHAR2(8 BYTE) CONSTRAINT RBEP_NARE_HTO_ID_AREA_CONOCIMIENTO NOT NULL,
    DES_AREA_CONOCIMIENTO   VARCHAR2(50 BYTE) CONSTRAINT RBEP_NARE_HTO_DES_AREA_CONOCIMIENTO NOT NULL,
	CONSTRAINT IBEP_PARE_HISTORICO PRIMARY KEY (CODCAMBIO)
);
--/////////////////////
CREATE SEQUENCE QBEP_ARE START WITH 1;
--/////////////////////
CREATE SEQUENCE QBEP_HTO_ARE START WITH 1;
--/////////////////////
CREATE TRIGGER DBEP_ARE_BRI
BEFORE INSERT
ON TBEP_AREAS 
FOR EACH ROW
DECLARE
BEGIN
    SELECT QBEP_ARE.nextval into :new.CODNUM FROM dual;
    INSERT INTO TBEP_HTO_AREAS (CODCAMBIO,LOG,BEPDEP_CODNUM,ID_SECCION,ID_AREA_CONOCIMIENTO,DES_AREA_CONOCIMIENTO)
    VALUES (QBEP_HTO_ARE.NEXTVAL,'AFTER_INSERT',:New.BEPDEP_CODNUM,:New.ID_SECCION,:New.ID_AREA_CONOCIMIENTO,:New.DES_AREA_CONOCIMIENTO);
END DBEP_ARE_BRI;
--/////////////////////
CREATE TRIGGER DBEP_ARE_BRU
BEFORE UPDATE
ON TBEP_AREAS 
FOR EACH ROW
DECLARE
BEGIN
    INSERT INTO TBEP_HTO_AREAS (CODCAMBIO,LOG,BEPDEP_CODNUM,ID_SECCION,ID_AREA_CONOCIMIENTO,DES_AREA_CONOCIMIENTO)
    VALUES (QBEP_HTO_ARE.NEXTVAL,'BEFORE_UPDATE',:Old.BEPDEP_CODNUM,:Old.ID_SECCION,:Old.ID_AREA_CONOCIMIENTO,:Old.DES_AREA_CONOCIMIENTO);
    INSERT INTO TBEP_HTO_AREAS (CODCAMBIO,LOG,BEPDEP_CODNUM,ID_SECCION,ID_AREA_CONOCIMIENTO,DES_AREA_CONOCIMIENTO)
    VALUES (QBEP_HTO_ARE.NEXTVAL,'AFTER_UPDATE',:New.BEPDEP_CODNUM,:New.ID_SECCION,:New.ID_AREA_CONOCIMIENTO,:New.DES_AREA_CONOCIMIENTO);
END DBEP_ARE_BRU;
--/////////////////////
CREATE TRIGGER DBEP_ARE_BRD
BEFORE DELETE
ON TBEP_AREAS 
FOR EACH ROW
DECLARE
BEGIN
    INSERT INTO TBEP_HTO_AREAS (CODCAMBIO,LOG,BEPDEP_CODNUM,ID_SECCION,ID_AREA_CONOCIMIENTO,DES_AREA_CONOCIMIENTO)
    VALUES (QBEP_HTO_ARE.NEXTVAL,'BEFORE_DELETE',:Old.BEPDEP_CODNUM,:Old.ID_SECCION,:Old.ID_AREA_CONOCIMIENTO,:Old.DES_AREA_CONOCIMIENTO);
END DBEP_ARE_BRD;
