CREATE TABLE UVIRTUAL.TBEP_BOLSAS (	
	CODNUM NUMBER(11,0) NOT NULL, 
    BEPARE_CODNUM NUMBER(11,0) NOT NULL,  
    ESTADO VARCHAR2(15 BYTE), 
    FLGBAREMABLE CHAR(1) DEFAULT 'N',
    FECHAACTUALIZACION TIMESTAMP DEFAULT NULL NULL,
    FECHABLOQUEO TIMESTAMP DEFAULT NULL NULL,
    FECHADEBLOQUEO TIMESTAMP DEFAULT NULL NULL,
	CONSTRAINT IBEP_PBOL PRIMARY KEY (CODNUM),
    CONSTRAINT IBEP_FBOL_ARE FOREIGN KEY (BEPARE_CODNUM) REFERENCES TBEP_AREAS (CODNUM),	
    CHECK (ESTADO IN ('BLOQUEADA','REVISION','BAREMACION','ALEGACIONES','DESBLOQUEADA')), 
    CHECK (FLGBAREMABLE IN ('N','S'))
);
--/////////////////////
COMMENT ON COLUMN TBEP_BOLSAS.BEPARE_CODNUM IS 'Llave externa a la area de trabajo asociada';
--/////////////////////
COMMENT ON COLUMN TBEP_BOLSAS.ESTADO IS 'En que estado está la bolsa de empleo';
--/////////////////////
COMMENT ON COLUMN TBEP_BOLSAS.FLGBAREMABLE IS 'Indica si la bolsa es bareblame o no. Para que una area se pueda baremar el estado de esta debe ser bloqueada y tener el campo bariblema a S';
--/////////////////////
COMMENT ON COLUMN TBEP_BOLSAS.FECHAACTUALIZACION IS 'La última fecha de actualaización de la bolsa';
--/////////////////////
COMMENT ON COLUMN TBEP_BOLSAS.FECHABLOQUEO IS 'La última fecha de bloqueo de la bolsa';
--/////////////////////
COMMENT ON COLUMN TBEP_BOLSAS.FECHADEBLOQUEO IS 'La última fecha de desbloqueo de la bolsa';
--/////////////////////
COMMENT ON TABLE TBEP_BOLSAS IS 'Bolsa de empleo asociada a una area de conocimiento. ALIAS: [bepbol] ACRONIMO: [BOL]';
--/////////////////////
CREATE TABLE UVIRTUAL.TBEP_HTO_BOLSAS (
 	CODCAMBIO NUMBER(11,0) NOT NULL,
 	LOG VARCHAR(50) NOT NULL,
 	FECHALOG TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
	CODNUM NUMBER(11,0) NOT NULL, 
	BEPARE_CODNUM NUMBER(11,0) NOT NULL,  
    ESTADO VARCHAR2(15 BYTE), 
    FLGBAREMABLE CHAR(1) DEFAULT 'N',
    FECHAACTUALIZACION TIMESTAMP DEFAULT NULL NULL,
    FECHABLOQUEO TIMESTAMP DEFAULT NULL NULL,
    FECHADEBLOQUEO TIMESTAMP DEFAULT NULL NULL,
	CONSTRAINT IBEP_PBOL_HISTORICO PRIMARY KEY (CODCAMBIO)
);
--/////////////////////
CREATE SEQUENCE QBEP_BOL START WITH 1;
--/////////////////////
CREATE SEQUENCE QBEP_HTO_BOL START WITH 1;
--/////////////////////
CREATE TRIGGER DBEP_BOL_BRI
BEFORE INSERT
ON TBEP_BOLSAS 
FOR EACH ROW
DECLARE
BEGIN
    SELECT QBEP_BOL.nextval into :new.CODNUM FROM dual;	 	
  
    INSERT INTO TBEP_HTO_BOLSAS (CODNUM,BEPARE_CODNUM,ESTADO,FLGBAREMABLE,FECHAACTUALIZACION,FECHABLOQUEO,FECHADEBLOQUEO)
    VALUES (:New.CODNUM,:New.NOMBRE,:New.CODIGO,'AFTER_INSERT',QBEP_HTO_ARE.NEXTVAL);
END DBEP_BOL_BRI;
--/////////////////////
CREATE TRIGGER DBEP_BOL_BRU
BEFORE UPDATE
ON TBEP_BOLSAS 
FOR EACH ROW
DECLARE
BEGIN
	INSERT INTO TBEP_HTO_BOLSAS (CODNUM,BEPARE_CODNUM,ESTADO,FLGBAREMABLE,FECHAACTUALIZACION,FECHABLOQUEO,FECHADEBLOQUEO)
 	VALUES (:Old.CODNUM,:Old.NOMBRE,:Old.CODIGO,'BEFORE_UPDATE',QBEP_HTO_ARE.NEXTVAL);    
      	  
    INSERT INTO TBEP_HTO_BOLSAS (CODNUM,BEPARE_CODNUM,ESTADO,FLGBAREMABLE,FECHAACTUALIZACION,FECHABLOQUEO,FECHADEBLOQUEO)
    VALUES (:New.CODNUM,:New.NOMBRE,:New.CODIGO,'AFTER_UPDATE',QBEP_HTO_ARE.NEXTVAL);   
END DBEP_BOL_BRU;
--/////////////////////
CREATE TRIGGER DBEP_BOL_BRD
BEFORE DELETE
ON TBEP_BOLSAS 
FOR EACH ROW
DECLARE
BEGIN
    INSERT INTO TBEP_HTO_BOLSAS (CODNUM,BEPARE_CODNUM,ESTADO,FLGBAREMABLE,FECHAACTUALIZACION,FECHABLOQUEO,FECHADEBLOQUEO)
    VALUES (:Old.CODNUM,:Old.NOMBRE,:Old.CODIGO,'BEFORE_DELETE',QBEP_HTO_ARE.NEXTVAL);    
END DBEP_BOL_BRD;
