CREATE TABLE UVIRTUAL.TBEP_BOLSAS (	
	CODNUM NUMBER(11,0) NOT NULL, 
    BEPARE_CODNUM NUMBER(11,0) NOT NULL,  
    ESTADO VARCHAR2(15 BYTE) DEFAULT 'BLOQUEADA', 
    FLGBAREMABLE CHAR(1) DEFAULT 'N',
    FECHAACTUALIZACION TIMESTAMP DEFAULT NULL NULL,
    FECHABLOQUEO TIMESTAMP DEFAULT NULL NULL,
    FECHADEBLOQUEO TIMESTAMP DEFAULT NULL NULL,
    CONSTRAINT IBEP_PBOL PRIMARY KEY (CODNUM),
    CONSTRAINT IBEP_FBOL_ARE FOREIGN KEY (BEPARE_CODNUM) REFERENCES TBEP_AREAS (CODNUM),	
    CHECK (ESTADO IN ('BLOQUEADA','REVISION','BAREMACION','ALEGACIONES','DESBLOQUEADA')), 
    CHECK (FLGBAREMABLE IN ('N','S'))
);
--/////////////////////
COMMENT ON COLUMN TBEP_BOLSAS.BEPARE_CODNUM IS 'Llave externa a la area de trabajo asociada';
--/////////////////////
COMMENT ON COLUMN TBEP_BOLSAS.ESTADO IS 'En que estado está la bolsa de empleo';
--/////////////////////
COMMENT ON COLUMN TBEP_BOLSAS.FLGBAREMABLE IS 'Indica si la bolsa es bareblame o no. Para que una area se pueda baremar el estado de esta debe ser bloqueada y tener el campo baremable a S';
--/////////////////////
COMMENT ON COLUMN TBEP_BOLSAS.FECHAACTUALIZACION IS 'La última fecha de actualaización de la bolsa';
--/////////////////////
COMMENT ON COLUMN TBEP_BOLSAS.FECHABLOQUEO IS 'La última fecha de bloqueo de la bolsa';
--/////////////////////
COMMENT ON COLUMN TBEP_BOLSAS.FECHADEBLOQUEO IS 'La última fecha de desbloqueo de la bolsa';
--/////////////////////
COMMENT ON TABLE TBEP_BOLSAS IS 'Bolsa de empleo asociada a una area de conocimiento. ALIAS: [bepbol] ACRONIMO: [BOL]';
--/////////////////////
CREATE TABLE UVIRTUAL.TBEP_HTO_BOLSAS (
 	CODCAMBIO NUMBER(11,0) NOT NULL,
 	LOG VARCHAR(50) NOT NULL,
 	FECHALOG TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
	CODNUM NUMBER(11,0) NOT NULL, 
	BEPARE_CODNUM NUMBER(11,0) NOT NULL,  
    ESTADO VARCHAR2(15 BYTE), 
    FLGBAREMABLE CHAR(1) DEFAULT 'N',
    FECHAACTUALIZACION TIMESTAMP DEFAULT NULL NULL,
    FECHABLOQUEO TIMESTAMP DEFAULT NULL NULL,
    FECHADEBLOQUEO TIMESTAMP DEFAULT NULL NULL,
	CONSTRAINT IBEP_PBOL_HISTORICO PRIMARY KEY (CODCAMBIO)
);
--/////////////////////
CREATE SEQUENCE QBEP_BOL START WITH 1;
--/////////////////////
CREATE SEQUENCE QBEP_HTO_BOL START WITH 1;
--/////////////////////
CREATE TRIGGER DBEP_BOL_BRI
BEFORE INSERT
ON TBEP_BOLSAS 
FOR EACH ROW
DECLARE
BEGIN
    SELECT QBEP_BOL.nextval into :new.CODNUM FROM dual;	 	
  
    INSERT INTO TBEP_HTO_BOLSAS (CODCAMBIO,LOG,CODNUM,BEPARE_CODNUM,ESTADO,FLGBAREMABLE,FECHAACTUALIZACION,FECHABLOQUEO,FECHADEBLOQUEO)
    VALUES (QBEP_HTO_ARE.NEXTVAL,'AFTER_INSERT',:New.CODNUM,:New.BEPARE_CODNUM,:New.ESTADO,:New.FLGBAREMABLE,:New.FECHAACTUALIZACION,:New.FECHABLOQUEO,:New.FECHADEBLOQUEO);
END DBEP_BOL_BRI;
--/////////////////////
CREATE TRIGGER DBEP_BOL_BRU
BEFORE UPDATE
ON TBEP_BOLSAS 
FOR EACH ROW
DECLARE
BEGIN
	INSERT INTO TBEP_HTO_BOLSAS (CODCAMBIO,LOG,CODNUM,BEPARE_CODNUM,ESTADO,FLGBAREMABLE,FECHAACTUALIZACION,FECHABLOQUEO,FECHADEBLOQUEO)
    VALUES (QBEP_HTO_ARE.NEXTVAL,'BEFORE_UPDATE',:Old.CODNUM,:Old.BEPARE_CODNUM,:Old.ESTADO,:Old.FLGBAREMABLE,:Old.FECHAACTUALIZACION,:Old.FECHABLOQUEO,:Old.FECHADEBLOQUEO);    
      	  
    INSERT INTO TBEP_HTO_BOLSAS (CODCAMBIO,LOG,CODNUM,BEPARE_CODNUM,ESTADO,FLGBAREMABLE,FECHAACTUALIZACION,FECHABLOQUEO,FECHADEBLOQUEO)
    VALUES (QBEP_HTO_ARE.NEXTVAL,'AFTER_UPDATE',:New.CODNUM,:New.BEPARE_CODNUM,:New.ESTADO,:New.FLGBAREMABLE,:New.FECHAACTUALIZACION,:New.FECHABLOQUEO,:New.FECHADEBLOQUEO);
END DBEP_BOL_BRU;
--/////////////////////
CREATE TRIGGER DBEP_BOL_BRD
BEFORE DELETE
ON TBEP_BOLSAS 
FOR EACH ROW
DECLARE
BEGIN
	INSERT INTO TBEP_HTO_BOLSAS (CODCAMBIO,LOG,CODNUM,BEPARE_CODNUM,ESTADO,FLGBAREMABLE,FECHAACTUALIZACION,FECHABLOQUEO,FECHADEBLOQUEO)
    VALUES (QBEP_HTO_ARE.NEXTVAL,'BEFORE_DELETE',:Old.CODNUM,:Old.BEPARE_CODNUM,:Old.ESTADO,:Old.FLGBAREMABLE,:Old.FECHAACTUALIZACION,:Old.FECHABLOQUEO,:Old.FECHADEBLOQUEO);  
END DBEP_BOL_BRD;
--/////////////////////
CREATE TRIGGER DBEP_AREBOL_BAI
AFTER INSERT
ON TBEP_AREAS 
FOR EACH ROW
DECLARE
BEGIN
    INSERT INTO TBEP_BOLSAS (BEPARE_CODNUM,ESTADO,FLGBAREMABLE,FECHAACTUALIZACION,FECHABLOQUEO,FECHADEBLOQUEO)
    VALUES (:New.CODNUM,'BLOQUEADA','N',NULL,NULL,NULL);
END DBEP_AREBOL_BAI;
