CREATE TABLE TBEP_AREAS_DEPARTAMENTOS (	
	CODNUM NUMBER(11,0) CONSTRAINT RBEP_NADE_COD_NUM NOT NULL,
    BEPARE_CODNUM NUMBER(11,0) CONSTRAINT RBEP_NADE_BEPARE_CODNUM NOT NULL,
    BEPDEP_CODNUM NUMBER(11,0) CONSTRAINT RBEP_NADE_BEPDEP_CODNUM NOT NULL,
    ID_SECCION VARCHAR2(8 BYTE) CONSTRAINT RBEP_NADE_ID_SECCION NOT NULL,
    DES_SECCION VARCHAR2(50 BYTE) CONSTRAINT RBEP_NADE_DES_SECCION NOT NULL,
	CONSTRAINT IBEP_PADE PRIMARY KEY (CODNUM),
    CONSTRAINT IBEP_FADE_ARE FOREIGN KEY (BEPARE_CODNUM) REFERENCES TBEP_AREAS (CODNUM),    
    CONSTRAINT IBEP_FADE_DEP FOREIGN KEY (BEPDEP_CODNUM) REFERENCES TBEP_DEPARTAMENTOS (CODNUM)
);
--/////////////////////
COMMENT ON COLUMN TBEP_AREAS_DEPARTAMENTOS.BEPARE_CODNUM IS 'Fk a areas';
--/////////////////////
COMMENT ON COLUMN TBEP_AREAS_DEPARTAMENTOS.BEPDEP_CODNUM IS 'Fk a departamentos';
--/////////////////////
COMMENT ON COLUMN TBEP_AREAS_DEPARTAMENTOS.ID_SECCION IS 'Id sección';
--/////////////////////
COMMENT ON COLUMN TBEP_AREAS_DEPARTAMENTOS.DES_SECCION IS 'Descripción sección';
--/////////////////////
COMMENT ON TABLE TBEP_AREAS_DEPARTAMENTOS IS 'Un área puede estar en varios departamentos. ALIAS: [bepade] ACRONIMO: [ADE]';
--/////////////////////
CREATE TABLE TBEP_HTO_AREAS_DEPARTAMENTOS (
 	CODCAMBIO NUMBER(11,0) CONSTRAINT RBEP_NADE_HTO_CODCAMBIO NOT NULL,
 	LOG VARCHAR(50) CONSTRAINT RBEP_NADE_HTO_LOG NOT NULL,
 	FECHALOG TIMESTAMP DEFAULT CURRENT_TIMESTAMP CONSTRAINT RBEP_NADE_HTO_FECHALOG NOT NULL,
	CODNUM NUMBER(11,0) CONSTRAINT RBEP_NADE_HTO_COD_NUM NOT NULL,
    BEPARE_CODNUM NUMBER(11,0) CONSTRAINT RBEP_NADE_HTO_BEPARE_CODNUM NOT NULL,
    BEPDEP_CODNUM NUMBER(11,0) CONSTRAINT RBEP_NADE_HTO_BEPDEP_CODNUM NOT NULL,
    ID_SECCION VARCHAR2(8 BYTE) CONSTRAINT RBEP_NADE_HTO_ID_SECCION NOT NULL,
    DES_SECCION VARCHAR2(50 BYTE) CONSTRAINT RBEP_NADE_HTO_DES_SECCION NOT NULL,
	CONSTRAINT IBEP_PADE_HISTORICO PRIMARY KEY (CODCAMBIO)
);
--/////////////////////
CREATE SEQUENCE QBEP_ADE START WITH 1;
--/////////////////////
CREATE SEQUENCE QBEP_HTO_ADE START WITH 1;
--/////////////////////
CREATE TRIGGER DBEP_ADE_BRI
BEFORE INSERT
ON TBEP_AREAS_DEPARTAMENTOS 
FOR EACH ROW
DECLARE
BEGIN
    SELECT QBEP_ADE.nextval into :new.CODNUM FROM dual;
    INSERT INTO TBEP_HTO_AREAS_DEPARTAMENTOS (CODCAMBIO,LOG,CODNUM,BEPARE_CODNUM,BEPDEP_CODNUM,ID_SECCION,DES_SECCION)
    VALUES (QBEP_HTO_ADE.NEXTVAL,'AFTER_INSERT',:New.CODNUM,:New.BEPARE_CODNUM,:New.BEPDEP_CODNUM,:New.ID_SECCION,:New.DES_SECCION);
END DBEP_ADE_BRI;
--/////////////////////
CREATE TRIGGER DBEP_ADE_BRU
BEFORE UPDATE
ON TBEP_AREAS_DEPARTAMENTOS 
FOR EACH ROW
DECLARE
BEGIN
    INSERT INTO TBEP_HTO_AREAS_DEPARTAMENTOS (CODCAMBIO,LOG,CODNUM,BEPARE_CODNUM,BEPDEP_CODNUM,ID_SECCION,DES_SECCION)
    VALUES (QBEP_HTO_ADE.NEXTVAL,'BEFORE_UPDATE',:Old.CODNUM,:Old.BEPARE_CODNUM,:Old.BEPDEP_CODNUM,:Old.ID_SECCION,:Old.DES_SECCION);
    INSERT INTO TBEP_HTO_AREAS_DEPARTAMENTOS (CODCAMBIO,LOG,CODNUM,BEPARE_CODNUM,BEPDEP_CODNUM,ID_SECCION,DES_SECCION)
    VALUES (QBEP_HTO_ADE.NEXTVAL,'AFTER_UPDATE',:New.CODNUM,:New.BEPARE_CODNUM,:New.BEPDEP_CODNUM,:New.ID_SECCION,:New.DES_SECCION);
END DBEP_ADE_BRU;
--/////////////////////
CREATE TRIGGER DBEP_ADE_BRD
BEFORE DELETE
ON TBEP_AREAS_DEPARTAMENTOS 
FOR EACH ROW
DECLARE
BEGIN
    INSERT INTO TBEP_HTO_AREAS_DEPARTAMENTOS (CODCAMBIO,LOG,CODNUM,BEPARE_CODNUM,BEPDEP_CODNUM,ID_SECCION,DES_SECCION)
    VALUES (QBEP_HTO_ADE.NEXTVAL,'BEFORE_DELETE',:Old.CODNUM,:Old.BEPARE_CODNUM,:Old.BEPDEP_CODNUM,:Old.ID_SECCION,:Old.DES_SECCION);
END DBEP_ADE_BRD;
