CREATE TABLE UVIRTUAL.TBEP_NOTICIAS (	
	CODNUM NUMBER(11,0) NOT NULL, 
    ENLACE VARCHAR2(50 BYTE), 
    TEXTO VARCHAR2(50 BYTE), 
    FECHA TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
	CONSTRAINT IBEP_PNOT PRIMARY KEY (CODNUM)
);
--/////////////////////
COMMENT ON COLUMN TBEP_NOTICIAS.ENLACE IS 'Enlace de la noticia';
--/////////////////////
COMMENT ON COLUMN TBEP_NOTICIAS.TEXTO IS 'Contenido o titular de la noticia';
--/////////////////////
COMMENT ON COLUMN TBEP_NOTICIAS.FECHA IS 'Fecha de creación de la noticia';
--/////////////////////
COMMENT ON TABLE TBEP_NOTICIAS IS 'Noticias del tablón de anuncios. ALIAS: [bepnot] ACRONIMO: [NOT]';
--/////////////////////
CREATE TABLE UVIRTUAL.TBEP_HTO_NOTICIAS (
 	CODCAMBIO NUMBER(11,0) NOT NULL,
 	LOG VARCHAR(50) NOT NULL,
 	FECHALOG TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
	CODNUM NUMBER(11,0) NOT NULL, 
	ENLACE VARCHAR2(50 BYTE), 
    TEXTO VARCHAR2(50 BYTE), 
    FECHA TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
	CONSTRAINT IBEP_PNOT_HISTORICO PRIMARY KEY (CODCAMBIO)
);
--/////////////////////
CREATE SEQUENCE QBEP_NOT START WITH 1;
--/////////////////////
CREATE SEQUENCE QBEP_HTO_NOT START WITH 1;
--/////////////////////
CREATE TRIGGER DBEP_NOT_BRI
BEFORE INSERT
ON TBEP_NOTICIAS
FOR EACH ROW
DECLARE
BEGIN
    SELECT QBEP_NOT.nextval into :new.CODNUM FROM dual;	 	
  	
    INSERT INTO TBEP_HTO_NOTICIAS (CODCAMBIO,LOG,CODNUM,ENLACE,TEXTO,FECHA)
    VALUES (QBEP_HTO_NOT.NEXTVAL,'AFTER_INSERT',:New.CODNUM,:New.ENLACE,:New.TEXTO,:New.FECHA);
END DBEP_NOT_BRI;
--/////////////////////
CREATE TRIGGER DBEP_NOT_BRU
BEFORE UPDATE
ON TBEP_NOTICIAS 
FOR EACH ROW
DECLARE
BEGIN
	INSERT INTO TBEP_HTO_NOTICIAS (CODCAMBIO,LOG,CODNUM,ENLACE,TEXTO,FECHA)
    VALUES (QBEP_HTO_NOT.NEXTVAL,'BEFORE_UPDATE',:Old.CODNUM,:Old.ENLACE,:Old.TEXTO,:Old.FECHA);   
    
 	INSERT INTO TBEP_HTO_NOTICIAS (CODCAMBIO,LOG,CODNUM,ENLACE,TEXTO,FECHA)
    VALUES (QBEP_HTO_NOT.NEXTVAL,'AFTER_UPDATE',:New.CODNUM,:New.ENLACE,:New.TEXTO,:New.FECHA);
END DBEP_NOT_BRU;
--/////////////////////
CREATE TRIGGER DBEP_NOT_BRD
BEFORE DELETE
ON TBEP_NOTICIAS 
FOR EACH ROW
DECLARE
BEGIN
	INSERT INTO TBEP_HTO_NOTICIAS (CODCAMBIO,LOG,CODNUM,ENLACE,TEXTO,FECHA)
    VALUES (QBEP_HTO_NOT.NEXTVAL,'BEFORE_DELETE',:Old.CODNUM,:Old.ENLACE,:Old.TEXTO,:Old.FECHA);
END DBEP_NOT_BRD;