CREATE TABLE UVIRTUAL.TBEP_FICHEROS (	
	CODNUM NUMBER(11,0) NOT NULL,
	NOMBRE VARCHAR2(100 BYTE) NOT NULL,
	TITULO VARCHAR2(300 BYTE),
    ARCHIVO BLOB NOT NULL,
	CONSTRAINT IBEP_PFICH PRIMARY KEY (CODNUM)
);
--/////////////////////
COMMENT ON COLUMN TBEP_FICHEROS.NOMBRE IS 'nombre del fichero';
--/////////////////////
COMMENT ON COLUMN TBEP_FICHEROS.TITULO IS 'titulo del fichero que aparecerá en inicio';
--/////////////////////
COMMENT ON COLUMN TBEP_FICHEROS.ARCHIVO IS 'archivo blob que se almacena en la bd';
--/////////////////////
COMMENT ON TABLE TBEP_FICHEROS IS 'Ficheros. ALIAS: [bepfic] ACRONIMO: [FIC]';
--/////////////////////
CREATE TABLE UVIRTUAL.TBEP_HTO_FICHEROS (
 	CODCAMBIO NUMBER(11,0) NOT NULL,
 	LOG VARCHAR(50) NOT NULL,
 	FECHALOG TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
	CODNUM NUMBER(11,0) NOT NULL,
	NOMBRE VARCHAR2(100 BYTE) NOT NULL,
	TITULO VARCHAR2(300 BYTE),
	ARCHIVO BLOB NOT NULL, 
	CONSTRAINT IBEP_PFICH_HISTORICO PRIMARY KEY (CODCAMBIO)
);
--/////////////////////
CREATE SEQUENCE QBEP_FICH START WITH 1;
--/////////////////////
CREATE SEQUENCE QBEP_HTO_FICH START WITH 1;
--/////////////////////
CREATE TRIGGER DBEP_FICH_BRI
BEFORE INSERT
ON TBEP_FICHEROS
FOR EACH ROW
DECLARE
BEGIN
    SELECT QBEP_FICH.nextval into :new.CODNUM FROM dual;	 	
  	
    INSERT INTO TBEP_HTO_FICHEROS (CODCAMBIO,LOG,CODNUM,NOMBRE,TITULO,ARCHIVO)
    VALUES (QBEP_HTO_FICH.NEXTVAL,'AFTER_INSERT',:New.CODNUM,:New.NOMBRE,:New.TITULO,:New.ARCHIVO);
END DBEP_FICH_BRI;
--/////////////////////
CREATE TRIGGER DBEP_FICH_BRU
BEFORE UPDATE
ON TBEP_FICHEROS
FOR EACH ROW
DECLARE
BEGIN
	INSERT INTO TBEP_HTO_FICHEROS (CODCAMBIO,LOG,CODNUM,NOMBRE,TITULO,ARCHIVO)
    VALUES (QBEP_HTO_FICH.NEXTVAL,'BEFORE_UPDATE',:Old.CODNUM,:Old.NOMBRE,:Old.TITULO,:Old.ARCHIVO);
    
 	INSERT INTO TBEP_HTO_FICHEROS (CODCAMBIO,LOG,CODNUM,NOMBRE,TITULO,ARCHIVO)
    VALUES (QBEP_HTO_FICH.NEXTVAL,'AFTER_INSERT',:New.CODNUM,:New.NOMBRE,:New.TITULO,:New.ARCHIVO);
END DBEP_FICH_BRU;
--/////////////////////
CREATE TRIGGER DBEP_FICH_BRD
BEFORE DELETE
ON TBEP_FICHEROS
FOR EACH ROW
DECLARE
BEGIN
	INSERT INTO TBEP_HTO_FICHEROS (CODCAMBIO,LOG,CODNUM,NOMBRE,TITULO,ARCHIVO)
    VALUES (QBEP_HTO_FICH.NEXTVAL,'BEFORE_UPDATE',:Old.CODNUM,:Old.NOMBRE,:Old.TITULO,:Old.ARCHIVO);
END DBEP_FICH_BRD;
