CREATE TABLE UVIRTUAL.TBEP_USUARIOS (	
	CODNUM NUMBER(11,0) CONSTRAINT RBEP_NUSU_CODNUM NOT NULL,
	CODPERSONA NUMBER(11,0) CONSTRAINT RBEP_NUSU_CODPERSONA NOT NULL,
	CODCUENTA VARCHAR2(100 BYTE) CONSTRAINT RBEP_NUSU_CODCUENTA NOT NULL,
    ROL NUMBER(11,0) CONSTRAINT RBEP_NUSU_ROL NOT NULL,
    EMAIL VARCHAR2(50 CHAR) DEFAULT NULL,
    DIRECCION VARCHAR2(50 CHAR) DEFAULT NULL,
    CODIGOPOSTAL VARCHAR2(5 CHAR) DEFAULT NULL,
    LOCALIDAD VARCHAR2(50 CHAR) DEFAULT NULL,
    PROVINCIA VARCHAR2(20 CHAR) DEFAULT NULL,
    MOVIL VARCHAR2(9 CHAR) DEFAULT NULL,
    TELEFONO VARCHAR2(9 CHAR) DEFAULT NULL,
    NACIONALIDAD VARCHAR2(20 CHAR) DEFAULT NULL,
    SEXO VARCHAR2(1 CHAR) DEFAULT NULL,
    FLGLISTADISTRIBUCION CHAR(1) DEFAULT 'N',
    FLGEXCLUIDO CHAR(1) DEFAULT 'N',
    RAZON_EXCLUSION VARCHAR2(500) NULL,
    FECHA_EXCLUSION TIMESTAMP NULL,
    FLGBORRADO CHAR(1) DEFAULT 'N',
    FECHA_BORRADO TIMESTAMP NULL,
    CONSTRAINT IBEP_PUSU PRIMARY KEY (CODNUM),
    CONSTRAINT IBEP_FUSU_ROL FOREIGN KEY (ROL) REFERENCES UVIRTUAL.ADM_ROL (ROL_CODNUM),
    CONSTRAINT IBEP_FUSU_CODPERSONA FOREIGN KEY (CODPERSONA) REFERENCES UVIRTUAL.VUJA_NET_BEP_AR_PERSONA (CODINT),
    CONSTRAINT IBEP_UUSU_CODPERSONA UNIQUE (CODPERSONA),
    CONSTRAINT IBEP_UUSU_CODCUENTA UNIQUE (CODCUENTA),
    CONSTRAINT RBEP_CUSU_FLGLISTADISTRIBUCION CHECK(FLGLISTADISTRIBUCION IN ('N','S')),
    CONSTRAINT RBEP_CUSU_FLGEXCLUIDO CHECK(FLGEXCLUIDO IN ('N','S')),
    CONSTRAINT RBEP_CUSU_FLGBORRADO CHECK(FLGBORRADO IN ('N','S'))
);
--/////////////////////
COMMENT ON COLUMN TBEP_USUARIOS.EMAIL IS 'Email del usuario';
--/////////////////////
COMMENT ON COLUMN TBEP_USUARIOS.ROL IS 'Rol del usuario en la apliación del usuario';
--/////////////////////
COMMENT ON COLUMN TBEP_USUARIOS.FLGLISTADISTRIBUCION IS 'Indica si el usuario está suscrito a la lista de distribución de mails';
--/////////////////////
COMMENT ON COLUMN TBEP_USUARIOS.FLGEXCLUIDO IS 'Indica si el usuario está excluido del sistema';
--/////////////////////
COMMENT ON COLUMN TBEP_USUARIOS.RAZON_EXCLUSION IS 'Razón de exlusión del usuario';
--/////////////////////
COMMENT ON COLUMN TBEP_USUARIOS.FECHA_EXCLUSION IS 'Fecha de exlusión del usuario';
--/////////////////////
COMMENT ON COLUMN TBEP_USUARIOS.FLGBORRADO IS 'Indica si el usuario ha sido borrado del sistema';
--/////////////////////
COMMENT ON COLUMN TBEP_USUARIOS.FECHA_BORRADO IS 'Fecha de borrado del usuario';
--/////////////////////
COMMENT ON TABLE TBEP_USUARIOS IS 'USUARIOS del tablón de anuncios. ALIAS: [bepusu] ACRONIMO: [USU]';
--/////////////////////
CREATE TABLE UVIRTUAL.TBEP_HTO_USUARIOS (
 	CODCAMBIO NUMBER(11,0) CONSTRAINT RBEP_NUSU_HTO_CODCAMBIO NOT NULL,
 	LOG VARCHAR(50) CONSTRAINT RBEP_NUSU_HTO_LOG NOT NULL,
 	FECHALOG TIMESTAMP DEFAULT CURRENT_TIMESTAMP CONSTRAINT RBEP_NUSU_HTO_FECHALOG NOT NULL,
	CODNUM NUMBER(11,0) CONSTRAINT RBEP_NUSU_HTO_CODNUM NOT NULL,
	CODPERSONA NUMBER(11,0) CONSTRAINT RBEP_NUSU_HTO_CODPERSONA NOT NULL,
	CODCUENTA VARCHAR2(100 BYTE) CONSTRAINT RBEP_NUSU_HTO_CODCUENTA NOT NULL,
	EMAIL VARCHAR2(50 CHAR) DEFAULT NULL,
	DIRECCION VARCHAR2(50 CHAR) DEFAULT NULL,
    CODIGOPOSTAL VARCHAR2(5 CHAR) DEFAULT NULL,
    LOCALIDAD VARCHAR2(50 CHAR) DEFAULT NULL,
    PROVINCIA VARCHAR2(20 CHAR) DEFAULT NULL,
   	MOVIL VARCHAR2(9 CHAR) DEFAULT NULL,
    TELEFONO VARCHAR2(9 CHAR) DEFAULT NULL,
    NACIONALIDAD VARCHAR2(20 CHAR) DEFAULT NULL,
   	SEXO VARCHAR2(1 CHAR) DEFAULT NULL,
    ROL NUMBER(11,0) CONSTRAINT RBEP_NUSU_HTO_ROL NOT NULL,
    FLGLISTADISTRIBUCION CHAR(1) DEFAULT 'N',
    FLGEXCLUIDO CHAR(1) DEFAULT 'N',
    RAZON_EXCLUSION VARCHAR2(500) NULL,
    FECHA_EXCLUSION TIMESTAMP NULL,
    FLGBORRADO CHAR(1) DEFAULT 'N',
    FECHA_BORRADO TIMESTAMP NULL,
	CONSTRAINT IBEP_PUSU_HISTORICO PRIMARY KEY (CODCAMBIO)
);
--/////////////////////
CREATE SEQUENCE QBEP_USU START WITH 1;
--/////////////////////
CREATE SEQUENCE QBEP_HTO_USU START WITH 1;
--/////////////////////
CREATE TRIGGER DBEP_USU_BRI
BEFORE INSERT
ON TBEP_USUARIOS
FOR EACH ROW
DECLARE
BEGIN
    SELECT QBEP_USU.nextval into :new.CODNUM FROM dual;	 	
  	
    INSERT INTO TBEP_HTO_USUARIOS (CODCAMBIO,LOG,CODNUM,CODPERSONA,CODCUENTA,EMAIL,DIRECCION,CODIGOPOSTAL,LOCALIDAD,PROVINCIA,MOVIL,TELEFONO,NACIONALIDAD,SEXO,ROL,FLGLISTADISTRIBUCION,FLGEXCLUIDO,RAZON_EXCLUSION,FECHA_EXCLUSION,FLGBORRADO,FECHA_BORRADO)
    VALUES (QBEP_HTO_USU.NEXTVAL,'AFTER_INSERT',:New.CODNUM,:New.CODPERSONA,:New.CODCUENTA,:New.EMAIL,:New.DIRECCION,:New.CODIGOPOSTAL,:New.LOCALIDAD,:New.PROVINCIA,:New.MOVIL,:New.TELEFONO,:New.NACIONALIDAD,:New.SEXO,:New.ROL,:New.FLGLISTADISTRIBUCION,:New.FLGEXCLUIDO,:New.RAZON_EXCLUSION,:New.FECHA_EXCLUSION,:New.FLGBORRADO,:New.FECHA_BORRADO);
END DBEP_USU_EXC_ARE_BRI;
--/////////////////////
CREATE TRIGGER DBEP_USU_BRU
BEFORE UPDATE
ON TBEP_USUARIOS 
FOR EACH ROW
DECLARE
BEGIN
	INSERT INTO TBEP_HTO_USUARIOS (CODCAMBIO,LOG,CODNUM,CODPERSONA,CODCUENTA,EMAIL,DIRECCION,CODIGOPOSTAL,LOCALIDAD,PROVINCIA,MOVIL,TELEFONO,NACIONALIDAD,SEXO,ROL,FLGLISTADISTRIBUCION,FLGEXCLUIDO,RAZON_EXCLUSION,FECHA_EXCLUSION,FLGBORRADO,FECHA_BORRADO)
    VALUES (QBEP_HTO_USU.NEXTVAL,'BEFORE_UPDATE',:Old.CODNUM,:Old.CODPERSONA,:Old.CODCUENTA,:Old.EMAIL,:Old.DIRECCION,:Old.CODIGOPOSTAL,:Old.LOCALIDAD,:Old.PROVINCIA,:Old.MOVIL,:Old.TELEFONO,:Old.NACIONALIDAD,:Old.SEXO,:Old.ROL,:Old.FLGLISTADISTRIBUCION,:Old.FLGEXCLUIDO,:Old.RAZON_EXCLUSION,:Old.FECHA_EXCLUSION,:Old.FLGBORRADO,:Old.FECHA_BORRADO);
    
 	INSERT INTO TBEP_HTO_USUARIOS (CODCAMBIO,LOG,CODNUM,CODPERSONA,CODCUENTA,EMAIL,DIRECCION,CODIGOPOSTAL,LOCALIDAD,PROVINCIA,MOVIL,TELEFONO,NACIONALIDAD,SEXO,ROL,FLGLISTADISTRIBUCION,FLGEXCLUIDO,RAZON_EXCLUSION,FECHA_EXCLUSION,FLGBORRADO,FECHA_BORRADO)
    VALUES (QBEP_HTO_USU.NEXTVAL,'AFTER_UPDATE',:New.CODNUM,:New.CODPERSONA,:New.CODCUENTA,:New.EMAIL,:New.DIRECCION,:New.CODIGOPOSTAL,:New.LOCALIDAD,:New.PROVINCIA,:New.MOVIL,:New.TELEFONO,:New.NACIONALIDAD,:New.SEXO,:New.ROL,:New.FLGLISTADISTRIBUCION,:New.FLGEXCLUIDO,:New.RAZON_EXCLUSION,:New.FECHA_EXCLUSION,:New.FLGBORRADO,:New.FECHA_BORRADO);
END DBEP_USU_BRU;
--/////////////////////
CREATE TRIGGER DBEP_USU_BRD
BEFORE DELETE
ON TBEP_USUARIOS 
FOR EACH ROW
DECLARE
BEGIN
	INSERT INTO TBEP_HTO_USUARIOS (CODCAMBIO,LOG,CODNUM,CODPERSONA,CODCUENTA,EMAIL,DIRECCION,CODIGOPOSTAL,LOCALIDAD,PROVINCIA,MOVIL,TELEFONO,NACIONALIDAD,SEXO,ROL,FLGLISTADISTRIBUCION,FLGEXCLUIDO,RAZON_EXCLUSION,FECHA_EXCLUSION,FLGBORRADO,FECHA_BORRADO)
    VALUES (QBEP_HTO_USU.NEXTVAL,'BEFORE_DELETE',:Old.CODNUM,:Old.CODPERSONA,:Old.CODCUENTA,:Old.EMAIL,:Old.DIRECCION,:Old.CODIGOPOSTAL,:Old.LOCALIDAD,:Old.PROVINCIA,:Old.MOVIL,:Old.TELEFONO,:Old.NACIONALIDAD,:Old.SEXO,:Old.ROL,:Old.FLGLISTADISTRIBUCION,:Old.FLGEXCLUIDO,:Old.RAZON_EXCLUSION,:Old.FECHA_EXCLUSION,:Old.FLGBORRADO,:Old.FECHA_BORRADO);
END DBEP_USU_BRD;