CREATE TABLE TBEP_FICHEROS (
	CODNUM NUMBER(11,0) CONSTRAINT RBEP_NFIC_CODNUM NOT NULL,
	NOMBRE VARCHAR2(100 CHAR) CONSTRAINT RBEP_NFIC_NOMBRE NOT NULL,
	TITULO VARCHAR2(300 CHAR),
    ARCHIVO BLOB CONSTRAINT RBEP_NFIC_ARCHIVO NOT NULL,
    FLGPUBLICO CHAR(1) DEFAULT 'N',
    UID_USUARIO VARCHAR2(100) CONSTRAINT RBEP_NFIC_UIDUSUARIO NOT NULL,
	CONSTRAINT IBEP_PFIC PRIMARY KEY (CODNUM)
);
--/////////////////////
COMMENT ON COLUMN TBEP_FICHEROS.NOMBRE IS 'nombre del fichero';
--/////////////////////
COMMENT ON COLUMN TBEP_FICHEROS.TITULO IS 'titulo del fichero que aparecerá en inicio';
--/////////////////////
COMMENT ON COLUMN TBEP_FICHEROS.ARCHIVO IS 'archivo blob que se almacena en la bd';
--/////////////////////
COMMENT ON COLUMN TBEP_FICHEROS.FLGPUBLICO IS 'Indica si el fichero es visible para anónimos en la página inicial de la bolsa de empleo';
--/////////////////////
COMMENT ON COLUMN TBEP_FICHEROS.UID_USUARIO IS 'Ultimo usuario que hace cambios en la tabla';
--/////////////////////
COMMENT ON TABLE TBEP_FICHEROS IS 'Ficheros. ALIAS: [bepfic] ACRONIMO: [FIC]';
--/////////////////////
CREATE TABLE TBEP_HTO_FICHEROS (
 	CODCAMBIO NUMBER(11,0) CONSTRAINT RBEP_NFIC_HTO_CODCAMBIO NOT NULL,
 	LOG VARCHAR(50) CONSTRAINT RBEP_NFIC_HTO_LOG NOT NULL,
 	FECHALOG TIMESTAMP DEFAULT CURRENT_TIMESTAMP CONSTRAINT RBEP_NFIC_HTO_FECHALOG NOT NULL,
	CODNUM NUMBER(11,0) CONSTRAINT RBEP_NFIC_HTO_CODNUM NOT NULL,
	NOMBRE VARCHAR2(100 CHAR) CONSTRAINT RBEP_NFIC_HTO_NOMBRE NOT NULL,
	TITULO VARCHAR2(300 CHAR),
	ARCHIVO BLOB CONSTRAINT RBEP_NFIC_HTO_ARCHIVO NOT NULL,
	FLGPUBLICO CHAR(1) DEFAULT 'N',
	UID_USUARIO VARCHAR2(100) CONSTRAINT RBEP_NFIC_HTO_UIDUSUARIO NOT NULL,
	CONSTRAINT IBEP_PFIC_HISTORICO PRIMARY KEY (CODCAMBIO)
);
--/////////////////////
CREATE SEQUENCE QBEP_FIC START WITH 1;
--/////////////////////
CREATE SEQUENCE QBEP_HTO_FIC START WITH 1;
--/////////////////////
CREATE TRIGGER DBEP_FIC_BRI
BEFORE INSERT
ON TBEP_FICHEROS
FOR EACH ROW
DECLARE
BEGIN
    SELECT QBEP_FIC.nextval into :new.CODNUM FROM dual;	 	
  	
    INSERT INTO TBEP_HTO_FICHEROS (CODCAMBIO,LOG,CODNUM,NOMBRE,TITULO,ARCHIVO,FLGPUBLICO,UID_USUARIO)
    VALUES (QBEP_HTO_FIC.NEXTVAL,'AFTER_INSERT',:New.CODNUM,:New.NOMBRE,:New.TITULO,:New.ARCHIVO,:New.FLGPUBLICO,:New.UID_USUARIO);
END DBEP_FIC_BRI;
--/////////////////////
CREATE TRIGGER DBEP_FIC_BRU
BEFORE UPDATE
ON TBEP_FICHEROS
FOR EACH ROW
DECLARE
BEGIN
	INSERT INTO TBEP_HTO_FICHEROS (CODCAMBIO,LOG,CODNUM,NOMBRE,TITULO,ARCHIVO,FLGPUBLICO,UID_USUARIO)
    VALUES (QBEP_HTO_FIC.NEXTVAL,'BEFORE_UPDATE',:Old.CODNUM,:Old.NOMBRE,:Old.TITULO,:Old.ARCHIVO,:Old.FLGPUBLICO,:Old.UID_USUARIO);
    
 	INSERT INTO TBEP_HTO_FICHEROS (CODCAMBIO,LOG,CODNUM,NOMBRE,TITULO,ARCHIVO,FLGPUBLICO,UID_USUARIO)
    VALUES (QBEP_HTO_FIC.NEXTVAL,'AFTER_INSERT',:New.CODNUM,:New.NOMBRE,:New.TITULO,:New.ARCHIVO,:New.FLGPUBLICO,:New.UID_USUARIO);
END DBEP_FIC_BRU;
--/////////////////////
CREATE TRIGGER DBEP_FIC_BRD
BEFORE DELETE
ON TBEP_FICHEROS
FOR EACH ROW
DECLARE
BEGIN
	INSERT INTO TBEP_HTO_FICHEROS (CODCAMBIO,LOG,CODNUM,NOMBRE,TITULO,ARCHIVO,FLGPUBLICO,UID_USUARIO)
    VALUES (QBEP_HTO_FIC.NEXTVAL,'BEFORE_UPDATE',:Old.CODNUM,:Old.NOMBRE,:Old.TITULO,:Old.ARCHIVO,:Old.FLGPUBLICO,:Old.UID_USUARIO);
END DBEP_FIC_BRD;
