CREATE TABLE UVIRTUAL.TBEP_USUARIOS (	
	CODNUM NUMBER(11,0) CONSTRAINT RBEP_NUSU_CODNUM NOT NULL,
    DNI VARCHAR2(12 BYTE) CONSTRAINT RBEP_NUSU_DNI NOT NULL,
    NOMBRE VARCHAR2(100 BYTE) CONSTRAINT RBEP_NUSU_NOMBRE NOT NULL,
    TELEFONO VARCHAR2(15 BYTE) NULL, 
    MOVIL VARCHAR2(15 BYTE) NULL, 
    EMAIL VARCHAR2(100 BYTE) NULL,     
    ROL VARCHAR2(15 BYTE) DEFAULT 'PERSONAL',
    FLGLISTADISTRIBUCION CHAR(1) DEFAULT 'N',
    FLGEXCLUIDO CHAR(1) DEFAULT 'N',
    RAZON_EXCLUSION VARCHAR2(500) NULL,
    FECHA_EXCLUSION TIMESTAMP NULL,
    FLGBORRADO CHAR(1) DEFAULT 'N',
    FECHA_BORRADO TIMESTAMP NULL,
    CONSTRAINT IBEP_PUSU PRIMARY KEY (CODNUM),
    CONSTRAINT IBEP_UUSU_DNI UNIQUE (DNI),
    CONSTRAINT IBEP_UUSU_EMAIL UNIQUE (EMAIL),
    CONSTRAINT RBEP_CUSU_ROL CHECK(ROL IN ('PERSONAL','COMISION','CANDIDATO')),
    CONSTRAINT RBEP_CUSU_FLGLISTADISTRIBUCION CHECK(FLGLISTADISTRIBUCION IN ('N','S')),
    CONSTRAINT RBEP_CUSU_FLGEXCLUIDO CHECK(FLGEXCLUIDO IN ('N','S')),
    CONSTRAINT RBEP_CUSU_FLGBORRADO CHECK(FLGBORRADO IN ('N','S'))
);
--/////////////////////
COMMENT ON COLUMN TBEP_USUARIOS.DNI IS 'Dni del usuario';
--/////////////////////
COMMENT ON COLUMN TBEP_USUARIOS.NOMBRE IS 'Nombre del usuario';
--/////////////////////
COMMENT ON COLUMN TBEP_USUARIOS.TELEFONO IS 'Teléfono fijo del usuario';
--/////////////////////
COMMENT ON COLUMN TBEP_USUARIOS.MOVIL IS 'Teléfono movil del usuario';
--/////////////////////
COMMENT ON COLUMN TBEP_USUARIOS.EMAIL IS 'Email del usuario';
--/////////////////////
COMMENT ON COLUMN TBEP_USUARIOS.ROL IS 'Rol del usuario en la apliación del usuario';
--/////////////////////
COMMENT ON COLUMN TBEP_USUARIOS.FLGLISTADISTRIBUCION IS 'Indica si el usuario está suscrito a la lista de distribución de mails';
--/////////////////////
COMMENT ON COLUMN TBEP_USUARIOS.FLGEXCLUIDO IS 'Indica si el usuario está excluido del sistema';
--/////////////////////
COMMENT ON COLUMN TBEP_USUARIOS.RAZON_EXCLUSION IS 'Razón de exlusión del usuario';
--/////////////////////
COMMENT ON COLUMN TBEP_USUARIOS.FECHA_EXCLUSION IS 'Fecha de exlusión del usuario';
--/////////////////////
COMMENT ON COLUMN TBEP_USUARIOS.FLGBORRADO IS 'Indica si el usuario ha sido borrado del sistema';
--/////////////////////
COMMENT ON COLUMN TBEP_USUARIOS.FECHA_BORRADO IS 'Fecha de borrado del usuario';
--/////////////////////
COMMENT ON TABLE TBEP_USUARIOS IS 'USUARIOS del tablón de anuncios. ALIAS: [bepusu] ACRONIMO: [USU]';
--/////////////////////
CREATE TABLE UVIRTUAL.TBEP_HTO_USUARIOS (
 	CODCAMBIO NUMBER(11,0) CONSTRAINT RBEP_NUSU_HTO_CODCAMBIO NOT NULL,
 	LOG VARCHAR(50) CONSTRAINT RBEP_NUSU_HTO_LOG NOT NULL,
 	FECHALOG TIMESTAMP DEFAULT CURRENT_TIMESTAMP CONSTRAINT RBEP_NUSU_HTO_FECHALOG NOT NULL,
	CODNUM NUMBER(11,0) CONSTRAINT RBEP_NUSU_HTO_CODNUM NOT NULL,
    DNI VARCHAR2(12 BYTE) CONSTRAINT RBEP_NUSU_HTO_DNI NOT NULL,
    NOMBRE VARCHAR2(100 BYTE) CONSTRAINT RBEP_NUSU_HTO_NOMBRE NOT NULL,
    TELEFONO VARCHAR2(15 BYTE) NULL, 
    MOVIL VARCHAR2(15 BYTE) NULL, 
    EMAIL VARCHAR2(100 BYTE) NULL, 
    ROL VARCHAR2(15 BYTE) DEFAULT 'PERSONAL',
    FLGLISTADISTRIBUCION CHAR(1) DEFAULT 'N',
    FLGEXCLUIDO CHAR(1) DEFAULT 'N',
    RAZON_EXCLUSION VARCHAR2(500) NULL,
    FECHA_EXCLUSION TIMESTAMP NULL,
    FLGBORRADO CHAR(1) DEFAULT 'N',
    FECHA_BORRADO TIMESTAMP NULL,
	CONSTRAINT IBEP_PUSU_HISTORICO PRIMARY KEY (CODCAMBIO)
);
--/////////////////////
CREATE SEQUENCE QBEP_USU START WITH 1;
--/////////////////////
CREATE SEQUENCE QBEP_HTO_USU START WITH 1;
