CREATE TABLE TBEP_USUARIOS (	
	CODNUM NUMBER(11,0) CONSTRAINT RBEP_NUSU_CODNUM NOT NULL,
	PRSNIF VARCHAR2(100 BYTE) CONSTRAINT RBEP_NUSU_PRSNIF NOT NULL,
	CODCUENTA VARCHAR2(100 BYTE) CONSTRAINT RBEP_NUSU_CODCUENTA NOT NULL,
    ROL NUMBER(11,0) CONSTRAINT RBEP_NUSU_ROL NOT NULL,
    DIRECCION VARCHAR2(50 CHAR) DEFAULT NULL,
    CODIGOPOSTAL VARCHAR2(5 CHAR) DEFAULT NULL,
    LOCALIDAD VARCHAR2(50 CHAR) DEFAULT NULL,
    PROVINCIA VARCHAR2(20 CHAR) DEFAULT NULL,
    NACIONALIDAD VARCHAR2(20 CHAR) DEFAULT NULL,
    TELEFONO VARCHAR2(20 CHAR) DEFAULT NULL,
    FLGLISTADISTRIBUCION CHAR(1) DEFAULT 'N',
    FLGEXCLUIDO CHAR(1) DEFAULT 'N',
    FLGEXCLUIDOTIPO CHAR(1) DEFAULT NULL,
    FECHA_EXCLUSION_INICIO TIMESTAMP NULL,
    FECHA_EXCLUSION_FIN TIMESTAMP NULL,
    RAZON_EXCLUSION VARCHAR2(500) NULL,
    FECHA_EXCLUSION TIMESTAMP NULL,
    FLGBORRADO CHAR(1) DEFAULT 'N',
   	RAZON_BORRADO VARCHAR2(500) NULL,
    FECHA_BORRADO TIMESTAMP NULL,
    CONSTRAINT IBEP_PUSU PRIMARY KEY (CODNUM),
    CONSTRAINT IBEP_FUSU_ROL FOREIGN KEY (ROL) REFERENCES ADM_ROL (ROL_CODNUM),
    CONSTRAINT IBEP_UUSU_CODCUENTA UNIQUE (CODCUENTA),
    CONSTRAINT RBEP_CUSU_FLGLISTADISTRIBU CHECK (FLGLISTADISTRIBUCION IN ('N','S')),
    CONSTRAINT RBEP_CUSU_FLGEXCLUIDO CHECK (FLGEXCLUIDO IN ('N','S')),
    CONSTRAINT RBEP_CUSU_FLGEXCLUIDO_TIPO CHECK (FLGEXCLUIDOTIPO IN ('T','I')),
    CONSTRAINT RBEP_CUSU_FLGBORRADO CHECK (FLGBORRADO IN ('N','S'))
);
--/////////////////////
COMMENT ON COLUMN TBEP_USUARIOS.ROL IS 'Rol del usuario en la apliación del usuario';
--/////////////////////
COMMENT ON COLUMN TBEP_USUARIOS.FLGLISTADISTRIBUCION IS 'Indica si el usuario está suscrito a la lista de distribución de mails';
--/////////////////////
COMMENT ON COLUMN TBEP_USUARIOS.FLGEXCLUIDO IS 'Indica si el usuario está excluido del sistema';
--/////////////////////
COMMENT ON COLUMN TBEP_USUARIOS.FLGEXCLUIDOTIPO IS 'Indica el tipo de exclusión del usuario si es que lo esta';
--/////////////////////
COMMENT ON COLUMN TBEP_USUARIOS.FECHA_EXCLUSION_INICIO IS 'Fecha de exlusión inicio del usuario de manera temporal';
--/////////////////////
COMMENT ON COLUMN TBEP_USUARIOS.FECHA_EXCLUSION_FIN IS 'Fecha de exlusión finalización del usuario de manera temporal';
--/////////////////////
COMMENT ON COLUMN TBEP_USUARIOS.RAZON_EXCLUSION IS 'Razón de exlusión del usuario';
--/////////////////////
COMMENT ON COLUMN TBEP_USUARIOS.FECHA_EXCLUSION IS 'Fecha de exlusión del usuario';
--/////////////////////
COMMENT ON COLUMN TBEP_USUARIOS.FLGBORRADO IS 'Indica si el usuario ha sido borrado del sistema';
--/////////////////////
COMMENT ON COLUMN TBEP_USUARIOS.RAZON_BORRADO IS 'Razón de borrado del usuario';
--/////////////////////
COMMENT ON COLUMN TBEP_USUARIOS.FECHA_BORRADO IS 'Fecha de borrado del usuario';
--/////////////////////
COMMENT ON COLUMN TBEP_USUARIOS.TELEFONO IS 'Telefono del usuario';
--/////////////////////
COMMENT ON TABLE TBEP_USUARIOS IS 'USUARIOS DE LA BOLSA DE EMPLEO. ALIAS: [bepusu] ACRONIMO: [USU]';
--/////////////////////
CREATE TABLE TBEP_HTO_USUARIOS (
 	CODCAMBIO NUMBER(11,0) CONSTRAINT RBEP_NUSU_HTO_CODCAMBIO NOT NULL,
 	LOG VARCHAR(50) CONSTRAINT RBEP_NUSU_HTO_LOG NOT NULL,
 	FECHALOG TIMESTAMP DEFAULT CURRENT_TIMESTAMP CONSTRAINT RBEP_NUSU_HTO_FECHALOG NOT NULL,
	CODNUM NUMBER(11,0) CONSTRAINT RBEP_NUSU_HTO_CODNUM NOT NULL,
	PRSNIF VARCHAR2(100 BYTE) CONSTRAINT RBEP_NUSU_HTO_PRSNIF NOT NULL,
	CODCUENTA VARCHAR2(100 BYTE) CONSTRAINT RBEP_NUSU_HTO_CODCUENTA NOT NULL,
	DIRECCION VARCHAR2(50 CHAR) DEFAULT NULL,
    CODIGOPOSTAL VARCHAR2(5 CHAR) DEFAULT NULL,
    LOCALIDAD VARCHAR2(50 CHAR) DEFAULT NULL,
    PROVINCIA VARCHAR2(20 CHAR) DEFAULT NULL,
    NACIONALIDAD VARCHAR2(20 CHAR) DEFAULT NULL,
    TELEFONO VARCHAR2(20 CHAR) DEFAULT NULL,
    ROL NUMBER(11,0) CONSTRAINT RBEP_NUSU_HTO_ROL NOT NULL,
    FLGLISTADISTRIBUCION CHAR(1) DEFAULT 'N',
    FLGEXCLUIDO CHAR(1) DEFAULT 'N',
    FLGEXCLUIDOTIPO CHAR(1) DEFAULT NULL,
    FECHA_EXCLUSION_INICIO TIMESTAMP NULL,
    FECHA_EXCLUSION_FIN TIMESTAMP NULL,
    RAZON_EXCLUSION VARCHAR2(500) NULL,
    FECHA_EXCLUSION TIMESTAMP NULL,
    FLGBORRADO CHAR(1) DEFAULT 'N',
    RAZON_BORRADO VARCHAR2(500) NULL,
    FECHA_BORRADO TIMESTAMP NULL,
	CONSTRAINT IBEP_PUSU_HISTORICO PRIMARY KEY (CODCAMBIO)
);
--/////////////////////
CREATE SEQUENCE QBEP_USU START WITH 1;
--/////////////////////
CREATE SEQUENCE QBEP_HTO_USU START WITH 1;
--/////////////////////
CREATE TRIGGER DBEP_USU_BRI
BEFORE INSERT
ON TBEP_USUARIOS
FOR EACH ROW
DECLARE
BEGIN
    SELECT QBEP_USU.nextval into :new.CODNUM FROM dual;	 	
  	
    INSERT INTO TBEP_HTO_USUARIOS (CODCAMBIO,LOG,CODNUM,PRSNIF,CODCUENTA,DIRECCION,CODIGOPOSTAL,LOCALIDAD,PROVINCIA,NACIONALIDAD,TELEFONO,ROL,FLGLISTADISTRIBUCION,FLGEXCLUIDO,FLGEXCLUIDOTIPO,FECHA_EXCLUSION_INICIO,FECHA_EXCLUSION_FIN,RAZON_EXCLUSION,FECHA_EXCLUSION,FLGBORRADO,RAZON_BORRADO,FECHA_BORRADO)
    VALUES (QBEP_HTO_USU.NEXTVAL,'AFTER_INSERT',:New.CODNUM,:New.PRSNIF,:New.CODCUENTA,:New.DIRECCION,:New.CODIGOPOSTAL,:New.LOCALIDAD,:New.PROVINCIA,:New.NACIONALIDAD,:Old.TELEFONO,:New.ROL,:New.FLGLISTADISTRIBUCION,:New.FLGEXCLUIDO,:Old.FLGEXCLUIDOTIPO,:New.FECHA_EXCLUSION_INICIO,:New.FECHA_EXCLUSION_FIN,:New.RAZON_EXCLUSION,:New.FECHA_EXCLUSION,:New.FLGBORRADO,:New.RAZON_BORRADO,:New.FECHA_BORRADO);
END DBEP_USU_BRI;
--/////////////////////
CREATE TRIGGER DBEP_USU_BRU
BEFORE UPDATE
ON TBEP_USUARIOS 
FOR EACH ROW
DECLARE
BEGIN
	INSERT INTO TBEP_HTO_USUARIOS (CODCAMBIO,LOG,CODNUM,PRSNIF,CODCUENTA,DIRECCION,CODIGOPOSTAL,LOCALIDAD,PROVINCIA,NACIONALIDAD,TELEFONO,ROL,FLGLISTADISTRIBUCION,FLGEXCLUIDO,FLGEXCLUIDOTIPO,FECHA_EXCLUSION_INICIO,FECHA_EXCLUSION_FIN,RAZON_EXCLUSION,FECHA_EXCLUSION,FLGBORRADO,RAZON_BORRADO,FECHA_BORRADO)
    VALUES (QBEP_HTO_USU.NEXTVAL,'BEFORE_UPDATE',:Old.CODNUM,:Old.PRSNIF,:Old.CODCUENTA,:Old.DIRECCION,:Old.CODIGOPOSTAL,:Old.LOCALIDAD,:Old.PROVINCIA,:Old.NACIONALIDAD,:Old.TELEFONO,:Old.ROL,:Old.FLGLISTADISTRIBUCION,:Old.FLGEXCLUIDO,:Old.FLGEXCLUIDOTIPO,:Old.FECHA_EXCLUSION_INICIO,:Old.FECHA_EXCLUSION_FIN,:Old.RAZON_EXCLUSION,:Old.FECHA_EXCLUSION,:Old.FLGBORRADO,:Old.RAZON_BORRADO,:Old.FECHA_BORRADO);
    
 	INSERT INTO TBEP_HTO_USUARIOS (CODCAMBIO,LOG,CODNUM,PRSNIF,CODCUENTA,DIRECCION,CODIGOPOSTAL,LOCALIDAD,PROVINCIA,NACIONALIDAD,TELEFONO,ROL,FLGLISTADISTRIBUCION,FLGEXCLUIDO,FLGEXCLUIDOTIPO,FECHA_EXCLUSION_INICIO,FECHA_EXCLUSION_FIN,RAZON_EXCLUSION,FECHA_EXCLUSION,FLGBORRADO,RAZON_BORRADO,FECHA_BORRADO)
    VALUES (QBEP_HTO_USU.NEXTVAL,'AFTER_UPDATE',:New.CODNUM,:New.PRSNIF,:New.CODCUENTA,:New.DIRECCION,:New.CODIGOPOSTAL,:New.LOCALIDAD,:New.PROVINCIA,:New.NACIONALIDAD,:Old.TELEFONO,:New.ROL,:New.FLGLISTADISTRIBUCION,:New.FLGEXCLUIDO,:New.FLGEXCLUIDOTIPO,:New.FECHA_EXCLUSION_INICIO,:New.FECHA_EXCLUSION_FIN,:New.RAZON_EXCLUSION,:New.FECHA_EXCLUSION,:New.FLGBORRADO,:New.RAZON_BORRADO,:New.FECHA_BORRADO);
END DBEP_USU_BRU;
--/////////////////////
CREATE TRIGGER DBEP_USU_BRD
BEFORE DELETE
ON TBEP_USUARIOS 
FOR EACH ROW
DECLARE
BEGIN
	INSERT INTO TBEP_HTO_USUARIOS (CODCAMBIO,LOG,CODNUM,PRSNIF,CODCUENTA,DIRECCION,CODIGOPOSTAL,LOCALIDAD,PROVINCIA,NACIONALIDAD,TELEFONO,ROL,FLGLISTADISTRIBUCION,FLGEXCLUIDO,FLGEXCLUIDOTIPO,FECHA_EXCLUSION_INICIO,FECHA_EXCLUSION_FIN,RAZON_EXCLUSION,FECHA_EXCLUSION,FLGBORRADO,RAZON_BORRADO,FECHA_BORRADO)
    VALUES (QBEP_HTO_USU.NEXTVAL,'BEFORE_DELETE',:Old.CODNUM,:Old.PRSNIF,:Old.CODCUENTA,:Old.DIRECCION,:Old.CODIGOPOSTAL,:Old.LOCALIDAD,:Old.PROVINCIA,:Old.NACIONALIDAD,:Old.TELEFONO,:Old.ROL,:Old.FLGLISTADISTRIBUCION,:Old.FLGEXCLUIDO,:Old.FLGEXCLUIDOTIPO,:Old.FECHA_EXCLUSION_INICIO,:Old.FECHA_EXCLUSION_FIN,:Old.RAZON_EXCLUSION,:Old.FECHA_EXCLUSION,:Old.FLGBORRADO,:Old.RAZON_BORRADO,:Old.FECHA_BORRADO);
END DBEP_USU_BRD;
