CREATE TABLE UVIRTUAL.TBEP_TITULACIONES (	
	CODNUM NUMBER(11,0) NOT NULL, 
    NOMBRE VARCHAR2(200 CHAR) NOT NULL, 
	CONSTRAINT IBEP_PTIT PRIMARY KEY (CODNUM)
);
--/////////////////////
COMMENT ON COLUMN TBEP_TITULACIONES.NOMBRE IS 'nombre de la titulación';
--/////////////////////
COMMENT ON TABLE TBEP_TITULACIONES IS 'Titulaciones de los candidatos. ALIAS: [beptit] ACRONIMO: [TIT]';
--/////////////////////
CREATE TABLE UVIRTUAL.TBEP_HTO_TITULACIONES (
 	CODCAMBIO NUMBER(11,0) NOT NULL,
 	LOG VARCHAR(50) NOT NULL,
 	FECHALOG TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
	CODNUM NUMBER(11,0) NOT NULL,
	NOMBRE VARCHAR2(100 CHAR) NOT NULL,
	CONSTRAINT IBEP_PTIT_HISTORICO PRIMARY KEY (CODCAMBIO)
);
--/////////////////////
CREATE SEQUENCE QBEP_TIT START WITH 1;
--/////////////////////
CREATE SEQUENCE QBEP_HTO_TIT START WITH 1;
--/////////////////////
CREATE TRIGGER DBEP_TIT_BRI
BEFORE INSERT
ON TBEP_TITULACIONES
FOR EACH ROW
DECLARE
BEGIN
    SELECT QBEP_TIT.nextval into :new.CODNUM FROM dual;	 	
  	
    INSERT INTO TBEP_HTO_TITULACIONES (CODCAMBIO,LOG,CODNUM,NOMBRE)
    VALUES (QBEP_HTO_TIT.NEXTVAL,'AFTER_INSERT',:New.CODNUM,:New.NOMBRE);
END DBEP_TIT_BRI;
--/////////////////////
CREATE TRIGGER DBEP_TIT_BRU
BEFORE UPDATE
ON TBEP_TITULACIONES 
FOR EACH ROW
DECLARE
BEGIN
	INSERT INTO TBEP_HTO_TITULACIONES (CODCAMBIO,LOG,CODNUM,NOMBRE)
    VALUES (QBEP_HTO_TIT.NEXTVAL,'BEFORE_UPDATE',:Old.CODNUM,:Old.NOMBRE);
    
 	INSERT INTO TBEP_HTO_TITULACIONES (CODCAMBIO,LOG,CODNUM,NOMBRE)
    VALUES (QBEP_HTO_TIT.NEXTVAL,'AFTER_UPDATE',:New.CODNUM,:New.NOMBRE);
END DBEP_TIT_BRU;
--/////////////////////
CREATE TRIGGER DBEP_TIT_BRD
BEFORE DELETE
ON TBEP_TITULACIONES 
FOR EACH ROW
DECLARE
BEGIN
	INSERT INTO TBEP_HTO_TITULACIONES (CODCAMBIO,LOG,CODNUM,NOMBRE)
    VALUES (QBEP_HTO_TIT.NEXTVAL,'BEFORE_DELETE',:Old.CODNUM,:Old.NOMBRE);
END DBEP_TIT_BRD;