CREATE TABLE UVIRTUAL.TBEP_TITULACIONESPREFERENTESAREA (	
	BEPARE_CODNUM NUMBER(11,0) NOT NULL,
	BEPTIT_CODNUM NUMBER(11,0) NOT NULL,
	CONSTRAINT IBEP_FTPA_ARE FOREIGN KEY (BEPARE_CODNUM) REFERENCES TBEP_AREAS (CODNUM),
	CONSTRAINT IBEP_FTPA_TIT FOREIGN KEY (BEPTIT_CODNUM) REFERENCES TBEP_TITULACIONES (CODNUM),
	CONSTRAINT IBEP_PTPA PRIMARY KEY (BEPARE_CODNUM, BEPTIT_CODNUM)
);
--/////////////////////
COMMENT ON COLUMN TBEP_TITULACIONESPREFERENTESAREA.BEPARE_CODNUM IS 'Clave foránea a tabla área';
--/////////////////////
COMMENT ON COLUMN TBEP_TITULACIONESPREFERENTESAREA.BEPTIT_CODNUM IS 'Clave foránea a tabla titulaciones';
--/////////////////////
COMMENT ON TABLE TBEP_TITULACIONESPREFERENTESAREA IS 'Tabla que relaciona las titulaciones preferentes con un área. ALIAS: [beptpa] ACRONIMO: [TPA]';
--/////////////////////
CREATE TABLE UVIRTUAL.TBEP_HTO_TITULACIONESPREFERENTESAREA (
 	CODCAMBIO NUMBER(11,0) NOT NULL,
 	LOG VARCHAR(50) NOT NULL,
 	FECHALOG TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
	BEPARE_CODNUM NUMBER(11,0) NOT NULL,
	BEPTIT_CODNUM NUMBER(11,0) NOT NULL,
	CONSTRAINT IBEP_PTPA_HISTORICO PRIMARY KEY (CODCAMBIO)
);
--/////////////////////
CREATE SEQUENCE QBEP_TPA START WITH 1;
--/////////////////////
CREATE SEQUENCE QBEP_HTO_TPA START WITH 1;
--/////////////////////
CREATE TRIGGER DBEP_TPA_BRI
BEFORE INSERT
ON TBEP_TITULACIONESPREFERENTESAREA
FOR EACH ROW
DECLARE
BEGIN
    INSERT INTO TBEP_HTO_TITULACIONESPREFERENTESAREA (CODCAMBIO,LOG,BEPARE_CODNUM,BEPTIT_CODNUM)
    VALUES (QBEP_HTO_TPA.NEXTVAL,'AFTER_INSERT',:New.BEPARE_CODNUM,:New.BEPTIT_CODNUM);
END DBEP_TPA_BRI;
--/////////////////////
CREATE TRIGGER DBEP_TPA_BRU
BEFORE UPDATE
ON TBEP_TITULACIONESPREFERENTESAREA
FOR EACH ROW
DECLARE
BEGIN
	INSERT INTO TBEP_HTO_TITULACIONESPREFERENTESAREA (CODCAMBIO,LOG,BEPARE_CODNUM,BEPTIT_CODNUM)
    VALUES (QBEP_HTO_TPA.NEXTVAL,'BEFORE_UPDATE',:Old.BEPARE_CODNUM,:Old.BEPTIT_CODNUM);
    
 	INSERT INTO TBEP_HTO_TITULACIONESPREFERENTESAREA (CODCAMBIO,LOG,BEPARE_CODNUM,BEPTIT_CODNUM)
    VALUES (QBEP_HTO_TPA.NEXTVAL,'AFTER_UPDATE',:New.BEPARE_CODNUM,:New.BEPTIT_CODNUM);
END DBEP_TPA_BRU;
--/////////////////////
CREATE TRIGGER DBEP_TPA_BRD
BEFORE DELETE
ON TBEP_TITULACIONESPREFERENTESAREA
FOR EACH ROW
DECLARE
BEGIN
	INSERT INTO TBEP_HTO_TITULACIONESPREFERENTESAREA (CODCAMBIO,LOG,BEPARE_CODNUM,BEPTIT_CODNUM)
    VALUES (QBEP_HTO_TPA.NEXTVAL,'BEFORE_DELETE',:Old.BEPARE_CODNUM,:Old.BEPTIT_CODNUM);
END DBEP_TPA_BRD;