CREATE TABLE UVIRTUAL.TBEP_TITULACIONESAREA (	
	BEPARE_CODNUM NUMBER(11,0) NOT NULL,
	BEPTIT_CODNUM NUMBER(11,0) NOT NULL,
	FLGREQUERIDA CHAR(1) DEFAULT 'N',
	CONSTRAINT IBEP_FTIAR_TIT FOREIGN KEY (BEPARE_CODNUM) REFERENCES TBEP_AREAS (CODNUM),
	CONSTRAINT IBEP_FTIAR_ARE FOREIGN KEY (BEPTIT_CODNUM) REFERENCES TBEP_TITULACIONES (CODNUM),
	CONSTRAINT IBEP_PTIAR PRIMARY KEY (BEPARE_CODNUM, BEPTIT_CODNUM)
);
--/////////////////////
COMMENT ON COLUMN TBEP_TITULACIONESAREA.BEPARE_CODNUM IS 'Clave foránea a tabla área';
--/////////////////////
COMMENT ON COLUMN TBEP_TITULACIONESAREA.BEPTIT_CODNUM IS 'Clave foránea a tabla titulaciones';
--/////////////////////
COMMENT ON COLUMN TBEP_TITULACIONESAREA.FLGREQUERIDA IS 'Clave foránea a tabla titulaciones';
--/////////////////////
CREATE TABLE UVIRTUAL.TBEP_HTO_TITULACIONESAREA (
 	CODCAMBIO NUMBER(11,0) NOT NULL,
 	LOG VARCHAR(50) NOT NULL,
 	FECHALOG TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
	BEPARE_CODNUM NUMBER(11,0) NOT NULL,
	BEPTIT_CODNUM NUMBER(11,0) NOT NULL,
	FLGREQUERIDA CHAR(1) DEFAULT 'N',
	CONSTRAINT IBEP_PTIAR_HISTORICO PRIMARY KEY (CODCAMBIO)
);
--/////////////////////
CREATE SEQUENCE QBEP_TIAR START WITH 1;
--/////////////////////
CREATE SEQUENCE QBEP_HTO_TIAR START WITH 1;
--/////////////////////
CREATE TRIGGER DBEP_TIAR_BRI
BEFORE INSERT
ON TBEP_TITULACIONESAREA
FOR EACH ROW
DECLARE
BEGIN
    INSERT INTO TBEP_HTO_TITULACIONESAREA (CODCAMBIO,LOG,BEPARE_CODNUM,BEPTIT_CODNUM,FLGREQUERIDA)
    VALUES (QBEP_HTO_TIAR.NEXTVAL,'AFTER_INSERT',:New.BEPARE_CODNUM,:New.BEPTIT_CODNUM,:New.FLGREQUERIDA);
END DBEP_TIAR_BRI;
--/////////////////////
CREATE TRIGGER DBEP_TIAR_BRU
BEFORE UPDATE
ON TBEP_TITULACIONESAREA
FOR EACH ROW
DECLARE
BEGIN
	INSERT INTO TBEP_HTO_TITULACIONESAREA (CODCAMBIO,LOG,BEPARE_CODNUM,BEPTIT_CODNUM,FLGREQUERIDA)
    VALUES (QBEP_HTO_TIAR.NEXTVAL,'BEFORE_UPDATE',:Old.BEPARE_CODNUM,:Old.BEPTIT_CODNUM,:Old.FLGREQUERIDA);
    
 	INSERT INTO TBEP_HTO_TITULACIONESAREA (CODCAMBIO,LOG,BEPARE_CODNUM,BEPTIT_CODNUM,FLGREQUERIDA)
    VALUES (QBEP_HTO_TIAR.NEXTVAL,'AFTER_UPDATE',:New.CODNUM,:New.NOMBRE,:New.FLGREQUERIDA);
END DBEP_TIAR_BRU;
--/////////////////////
CREATE TRIGGER DBEP_TIAR_BRD
BEFORE DELETE
ON TBEP_TITULACIONESAREA 
FOR EACH ROW
DECLARE
BEGIN
	INSERT INTO TBEP_HTO_TITULACIONESAREA (CODCAMBIO,LOG,BEPARE_CODNUM,BEPTIT_CODNUM,FLGREQUERIDA)
    VALUES (QBEP_HTO_TIAR.NEXTVAL,'BEFORE_DELETE',:Old.BEPARE_CODNUM,:Old.BEPTIT_CODNUM,:Old.FLGREQUERIDA);
END DBEP_TIAR_BRD;