CREATE TABLE TBEP_TITULACIONES (	
	CODNUM NUMBER(11,0) CONSTRAINT RBEP_NTIT_CODNUM NOT NULL,
    NOMBRE VARCHAR2(1000 CHAR) CONSTRAINT RBEP_NTIT_NOMBRE NOT NULL,
    FLGBORRADO CHAR(1) DEFAULT 'N',
    FECHA_BORRADO TIMESTAMP NULL,
    UID_USUARIO VARCHAR2(100) CONSTRAINT RBEP_NTIT_UIDUSUARIO NOT NULL,
	CONSTRAINT IBEP_PTIT PRIMARY KEY (CODNUM)
);
--/////////////////////
COMMENT ON COLUMN TBEP_TITULACIONES.NOMBRE IS 'nombre de la titulación';
--/////////////////////
COMMENT ON COLUMN TBEP_TITULACIONES.UID_USUARIO IS 'Ultimo usuario que hace cambios en la tabla';
--/////////////////////
COMMENT ON TABLE TBEP_TITULACIONES IS 'Titulaciones de los candidatos. ALIAS: [beptit] ACRONIMO: [TIT]';
--/////////////////////
CREATE TABLE TBEP_HTO_TITULACIONES (
 	CODCAMBIO NUMBER(11,0) CONSTRAINT RBEP_NTIT_HTO_CODCAMBIO NOT NULL,
 	LOG VARCHAR(50) CONSTRAINT RBEP_NTIT_HTO_LOG NOT NULL,
 	FECHALOG TIMESTAMP DEFAULT CURRENT_TIMESTAMP CONSTRAINT RBEP_NTIT_HTO_FECHALOG NOT NULL,
	CODNUM NUMBER(11,0) CONSTRAINT RBEP_NTIT_HTO_CODNUM NOT NULL,
	NOMBRE VARCHAR2(1000 CHAR) CONSTRAINT RBEP_NTIT_HTO_NOMBRE NOT NULL,
	FLGBORRADO CHAR(1) DEFAULT 'N',
    FECHA_BORRADO TIMESTAMP NULL,
    UID_USUARIO VARCHAR2(100) CONSTRAINT RBEP_NTIT_HTO_UIDUSUARIO NOT NULL,
	CONSTRAINT IBEP_PTIT_HISTORICO PRIMARY KEY (CODCAMBIO)
);
--/////////////////////
CREATE SEQUENCE QBEP_TIT START WITH 1;
--/////////////////////
CREATE SEQUENCE QBEP_HTO_TIT START WITH 1;
--/////////////////////
CREATE TRIGGER DBEP_TIT_BRI
BEFORE INSERT
ON TBEP_TITULACIONES
FOR EACH ROW
DECLARE
BEGIN
    SELECT QBEP_TIT.nextval into :new.CODNUM FROM dual;	 	
  	
    INSERT INTO TBEP_HTO_TITULACIONES (CODCAMBIO,LOG,CODNUM,NOMBRE,FLGBORRADO,FECHA_BORRADO,UID_USUARIO)
    VALUES (QBEP_HTO_TIT.NEXTVAL,'AFTER_INSERT',:New.CODNUM,:New.NOMBRE,:New.FLGBORRADO,:New.FECHA_BORRADO,:New.UID_USUARIO);
END DBEP_TIT_BRI;
--/////////////////////
CREATE TRIGGER DBEP_TIT_BRU
BEFORE UPDATE
ON TBEP_TITULACIONES 
FOR EACH ROW
DECLARE
BEGIN
	INSERT INTO TBEP_HTO_TITULACIONES (CODCAMBIO,LOG,CODNUM,NOMBRE,FLGBORRADO,FECHA_BORRADO,UID_USUARIO)
    VALUES (QBEP_HTO_TIT.NEXTVAL,'BEFORE_UPDATE',:Old.CODNUM,:Old.NOMBRE,:Old.FLGBORRADO,:Old.FECHA_BORRADO,:Old.UID_USUARIO);
    
 	INSERT INTO TBEP_HTO_TITULACIONES (CODCAMBIO,LOG,CODNUM,NOMBRE,FLGBORRADO,FECHA_BORRADO,UID_USUARIO)
    VALUES (QBEP_HTO_TIT.NEXTVAL,'AFTER_UPDATE',:New.CODNUM,:New.NOMBRE,:New.FLGBORRADO,:New.FECHA_BORRADO,:New.UID_USUARIO);
END DBEP_TIT_BRU;
--/////////////////////
CREATE TRIGGER DBEP_TIT_BRD
BEFORE DELETE
ON TBEP_TITULACIONES 
FOR EACH ROW
DECLARE
BEGIN
	INSERT INTO TBEP_HTO_TITULACIONES (CODCAMBIO,LOG,CODNUM,NOMBRE,FLGBORRADO,FECHA_BORRADO,UID_USUARIO)
    VALUES (QBEP_HTO_TIT.NEXTVAL,'BEFORE_DELETE',:Old.CODNUM,:Old.NOMBRE,:Old.FLGBORRADO,:Old.FECHA_BORRADO,:Old.UID_USUARIO);
END DBEP_TIT_BRD;
