CREATE TABLE UVIRTUAL.TBEP_TITULACIONES_PREFERENTES_AREA (	
	BEPARE_CODNUM NUMBER(11,0) CONSTRAINT RBEP_NTPA_BEPARE_CODNUM NOT NULL,
	BEPTIT_CODNUM NUMBER(11,0) CONSTRAINT RBEP_NTPA_BEPTIT_CODNUM NOT NULL,
	FLGBORRADO CHAR(1) DEFAULT 'N',
    FECHA_BORRADO TIMESTAMP NULL,
	CONSTRAINT IBEP_FTPA_ARE FOREIGN KEY (BEPARE_CODNUM) REFERENCES TBEP_AREAS (CODNUM),
	CONSTRAINT IBEP_FTPA_TIT FOREIGN KEY (BEPTIT_CODNUM) REFERENCES TBEP_TITULACIONES (CODNUM),
	CONSTRAINT IBEP_PTPA PRIMARY KEY (BEPARE_CODNUM, BEPTIT_CODNUM)
);
--/////////////////////
COMMENT ON COLUMN TBEP_TITULACIONES_PREFERENTES_AREA.BEPARE_CODNUM IS 'Clave foránea a tabla área';
--/////////////////////
COMMENT ON COLUMN TBEP_TITULACIONES_PREFERENTES_AREA.BEPTIT_CODNUM IS 'Clave foránea a tabla titulaciones';
--/////////////////////
COMMENT ON TABLE TBEP_TITULACIONES_PREFERENTES_AREA IS 'Tabla que relaciona las titulaciones preferentes con un área. ALIAS: [beptpa] ACRONIMO: [TPA]';
--/////////////////////
CREATE TABLE UVIRTUAL.TBEP_HTO_TITULACIONES_PREFERENTES_AREA (
 	CODCAMBIO NUMBER(11,0) CONSTRAINT RBEP_NTPA_HTO_CODCAMBIO NOT NULL,
 	LOG VARCHAR(50) CONSTRAINT RBEP_NTPA_HTO_LOG NOT NULL,
 	FECHALOG TIMESTAMP DEFAULT CURRENT_TIMESTAMP CONSTRAINT RBEP_NTPA_HTO_FECHALOG NOT NULL,
	BEPARE_CODNUM NUMBER(11,0) CONSTRAINT RBEP_NTPA_HTO_BEPARE_CODNUM NOT NULL,
	BEPTIT_CODNUM NUMBER(11,0) CONSTRAINT RBEP_NTPA_HTO_BEPTIT_CODNUM NOT NULL,
	FLGBORRADO CHAR(1) DEFAULT 'N',
    FECHA_BORRADO TIMESTAMP NULL,
	CONSTRAINT IBEP_PTPA_HISTORICO PRIMARY KEY (CODCAMBIO)
);
--/////////////////////
CREATE SEQUENCE QBEP_TPA START WITH 1;
--/////////////////////
CREATE SEQUENCE QBEP_HTO_TPA START WITH 1;
--/////////////////////
CREATE TRIGGER DBEP_TPA_BRI
BEFORE INSERT
ON TBEP_TITULACIONES_PREFERENTES_AREA
FOR EACH ROW
DECLARE
BEGIN
    INSERT INTO TBEP_HTO_TITULACIONES_PREFERENTES_AREA (CODCAMBIO,LOG,BEPARE_CODNUM,BEPTIT_CODNUM,FLGBORRADO,FECHA_BORRADO)
    VALUES (QBEP_HTO_TPA.NEXTVAL,'AFTER_INSERT',:New.BEPARE_CODNUM,:New.BEPTIT_CODNUM,:New.FLGBORRADO,:New.FECHA_BORRADO);
END DBEP_TPA_BRI;
--/////////////////////
CREATE TRIGGER DBEP_TPA_BRU
BEFORE UPDATE
ON TBEP_TITULACIONES_PREFERENTES_AREA
FOR EACH ROW
DECLARE
BEGIN
	INSERT INTO TBEP_HTO_TITULACIONES_PREFERENTES_AREA (CODCAMBIO,LOG,BEPARE_CODNUM,BEPTIT_CODNUM,FLGBORRADO,FECHA_BORRADO)
    VALUES (QBEP_HTO_TPA.NEXTVAL,'BEFORE_UPDATE',:Old.BEPARE_CODNUM,:Old.BEPTIT_CODNUM,:Old.FLGBORRADO,:Old.FECHA_BORRADO);
    
 	INSERT INTO TBEP_HTO_TITULACIONES_PREFERENTES_AREA (CODCAMBIO,LOG,BEPARE_CODNUM,BEPTIT_CODNUM,FLGBORRADO,FECHA_BORRADO)
    VALUES (QBEP_HTO_TPA.NEXTVAL,'AFTER_UPDATE',:New.BEPARE_CODNUM,:New.BEPTIT_CODNUM,:New.FLGBORRADO,:New.FECHA_BORRADO);
END DBEP_TPA_BRU;
--/////////////////////
CREATE TRIGGER DBEP_TPA_BRD
BEFORE DELETE
ON TBEP_TITULACIONES_PREFERENTES_AREA
FOR EACH ROW
DECLARE
BEGIN
	INSERT INTO TBEP_HTO_TITULACIONES_PREFERENTES_AREA (CODCAMBIO,LOG,BEPARE_CODNUM,BEPTIT_CODNUM,FLGBORRADO,FECHA_BORRADO)
    VALUES (QBEP_HTO_TPA.NEXTVAL,'BEFORE_DELETE',:Old.BEPARE_CODNUM,:Old.BEPTIT_CODNUM,:Old.FLGBORRADO,:Old.FECHA_BORRADO);
END DBEP_TPA_BRD;