CREATE TABLE UVIRTUAL.TBEP_APARTADOSBAREMACION (	
	CODNUM NUMBER(11,0) NOT NULL, 
    CODIGO VARCHAR2(10 BYTE) NOT NULL,
    NOMBRE VARCHAR2(100 BYTE) NOT NULL,
    FLGACTIVO CHAR(1) DEFAULT 'S',
    PUNTUACIONMAXIMA NUMBER(5, 2) NULL,
    PORCENTAJEMAXIMO NUMBER(5, 2) NULL,
    MERITOS_PREFERENTES CHAR(1) DEFAULT 'N',
    FACTOR_MERITO_PREFERENTE NUMBER(5, 2) NULL,
    CONSTRAINT IBEP_PAPA PRIMARY KEY (CODNUM),
    CONSTRAINT IBEP_UAPA_CODIGO UNIQUE (CODIGO),
    CONSTRAINT RBEP_CAPA_FLGACTIVO CHECK (FLGACTIVO IN ('N','S')),
    CONSTRAINT RBEP_CAPA_MERITOS_PREFERENTES CHECK (MERITOS_PREFERENTES IN ('N','S'))
);
--/////////////////////
COMMENT ON COLUMN TBEP_APARTADOSBAREMACION.CODIGO IS 'Código del apartado de baremación';
--/////////////////////
COMMENT ON COLUMN TBEP_APARTADOSBAREMACION.NOMBRE IS 'Nombre del apartado';
--/////////////////////
COMMENT ON COLUMN TBEP_APARTADOSBAREMACION.FLGACTIVO IS 'Indica si está activo o no';
--/////////////////////
COMMENT ON COLUMN TBEP_APARTADOSBAREMACION.PUNTUACIONMAXIMA IS 'Puntuanción máxima del bloque';
--/////////////////////
COMMENT ON COLUMN TBEP_APARTADOSBAREMACION.PORCENTAJEMAXIMO IS 'Porcentaje máximo del bloque';
--/////////////////////
COMMENT ON COLUMN TBEP_APARTADOSBAREMACION.MERITOS_PREFERENTES IS 'Si se aplica el factor por mérito preferente';
--/////////////////////
COMMENT ON COLUMN TBEP_APARTADOSBAREMACION.FACTOR_MERITO_PREFERENTE IS 'Indica el factor por mérito preferente';
--/////////////////////
COMMENT ON TABLE TBEP_APARTADOSBAREMACION IS 'Apartado de la baremación. ALIAS: [bepapa] ACRONIMO: [APA]';
--/////////////////////
CREATE TABLE UVIRTUAL.TBEP_HTO_APARTADOSBAREMACION (
 	CODCAMBIO NUMBER(11,0) NOT NULL,
 	LOG VARCHAR(50) NOT NULL,
 	FECHALOG TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
	CODNUM NUMBER(11,0) NOT NULL,
    CODIGO VARCHAR2(10 BYTE) NOT NULL,
    NOMBRE VARCHAR2(100 BYTE) NOT NULL,
    FLGACTIVO CHAR(1) DEFAULT 'S',
    PUNTUACIONMAXIMA NUMBER(5, 2) NULL,
    PORCENTAJEMAXIMO NUMBER(5, 2) NULL,
    MERITOS_PREFERENTES CHAR(1) DEFAULT 'N',
    FACTOR_MERITO_PREFERENTE NUMBER(5, 2) NULL,
	CONSTRAINT IBEP_PAPA_HISTORICO PRIMARY KEY (CODCAMBIO)
);
--/////////////////////
CREATE SEQUENCE QBEP_APA START WITH 1;
--/////////////////////
CREATE SEQUENCE QBEP_HTO_APA START WITH 1;
--/////////////////////
CREATE TRIGGER DBEP_APA_BRI
BEFORE INSERT
ON TBEP_APARTADOSBAREMACION
FOR EACH ROW
DECLARE
BEGIN
    SELECT QBEP_APA.nextval into :new.CODNUM FROM dual;	 	

    INSERT INTO TBEP_HTO_APARTADOSBAREMACION (CODCAMBIO,LOG,CODNUM,CODIGO,NOMBRE,FLGACTIVO,PUNTUACIONMAXIMA,PORCENTAJEMAXIMO,MERITOS_PREFERENTES,FACTOR_MERITO_PREFERENTE)
    VALUES (QBEP_HTO_APA.NEXTVAL,'AFTER_INSERT',:New.CODNUM,:New.CODIGO,:New.NOMBRE,:New.FLGACTIVO,:New.PUNTUACIONMAXIMA,:New.PORCENTAJEMAXIMO,:New.MERITOS_PREFERENTES,:New.FACTOR_MERITO_PREFERENTE);
END DBEP_APA_BRI;
--/////////////////////
CREATE TRIGGER DBEP_APA_BRU
BEFORE UPDATE
ON TBEP_APARTADOSBAREMACION 
FOR EACH ROW
DECLARE
BEGIN
	INSERT INTO TBEP_HTO_APARTADOSBAREMACION (CODCAMBIO,LOG,CODNUM,CODIGO,NOMBRE,FLGACTIVO,PUNTUACIONMAXIMA,PORCENTAJEMAXIMO,MERITOS_PREFERENTES,FACTOR_MERITO_PREFERENTE)
    VALUES (QBEP_HTO_APA.NEXTVAL,'BEFORE_UPDATE',:Old.CODNUM,:Old.CODIGO,:Old.NOMBRE,:Old.FLGACTIVO,:Old.PUNTUACIONMAXIMA,:Old.PORCENTAJEMAXIMO,:Old.MERITOS_PREFERENTES,:Old.FACTOR_MERITO_PREFERENTE);   
    
 	INSERT INTO TBEP_HTO_APARTADOSBAREMACION (CODCAMBIO,LOG,CODNUM,CODIGO,NOMBRE,FLGACTIVO,PUNTUACIONMAXIMA,PORCENTAJEMAXIMO,MERITOS_PREFERENTES,FACTOR_MERITO_PREFERENTE)
    VALUES (QBEP_HTO_APA.NEXTVAL,'AFTER_UPDATE',:New.CODNUM,:New.CODIGO,:New.NOMBRE,:New.FLGACTIVO,:New.PUNTUACIONMAXIMA,:New.PORCENTAJEMAXIMO,:New.MERITOS_PREFERENTES,:New.FACTOR_MERITO_PREFERENTE);
END DBEP_APA_BRU;
--/////////////////////
CREATE TRIGGER DBEP_APA_BRD
BEFORE DELETE
ON TBEP_APARTADOSBAREMACION 
FOR EACH ROW
DECLARE
BEGIN
	INSERT INTO TBEP_HTO_APARTADOSBAREMACION (CODCAMBIO,LOG,CODNUM,CODIGO,NOMBRE,FLGACTIVO,PUNTUACIONMAXIMA,PORCENTAJEMAXIMO,MERITOS_PREFERENTES,FACTOR_MERITO_PREFERENTE)
    VALUES (QBEP_HTO_APA.NEXTVAL,'BEFORE_DELETE',:Old.CODNUM,:Old.CODIGO,:Old.NOMBRE,:Old.FLGACTIVO,:Old.PUNTUACIONMAXIMA,:Old.PORCENTAJEMAXIMO,:Old.MERITOS_PREFERENTES,:Old.FACTOR_MERITO_PREFERENTE);
END DBEP_APA_BRD;
