CREATE TABLE TBEP_APARTADOSBAREMACION (	
	CODNUM NUMBER(11,0) CONSTRAINT RBEP_NAPA_CODNUM NOT NULL,
    CODIGO VARCHAR2(10 CHAR) CONSTRAINT RBEP_NAPA_CODIGO NOT NULL,
    NOMBRE VARCHAR2(100 CHAR) CONSTRAINT RBEP_NAPA_NOMBRE NOT NULL,
    FLGACTIVO CHAR(1) DEFAULT 'S',
    PUNTUACIONMAXIMA NUMBER(10, 6) NULL,
    PORCENTAJEMAXIMO NUMBER(10, 6) NULL,
    UID_USUARIO VARCHAR2(100) CONSTRAINT RBEP_NAPA_UIDUSUARIO NOT NULL,
    CONSTRAINT IBEP_PAPA PRIMARY KEY (CODNUM),
    CONSTRAINT RBEP_CAPA_FLGACTIVO CHECK (FLGACTIVO IN ('N','S'))
);
--/////////////////////
COMMENT ON COLUMN TBEP_APARTADOSBAREMACION.CODIGO IS 'Código del apartado de baremación';
--/////////////////////
COMMENT ON COLUMN TBEP_APARTADOSBAREMACION.NOMBRE IS 'Nombre del apartado';
--/////////////////////
COMMENT ON COLUMN TBEP_APARTADOSBAREMACION.FLGACTIVO IS 'Indica si está activo o no';
--/////////////////////
COMMENT ON COLUMN TBEP_APARTADOSBAREMACION.PUNTUACIONMAXIMA IS 'Puntuanción máxima del bloque';
--/////////////////////
COMMENT ON COLUMN TBEP_APARTADOSBAREMACION.PORCENTAJEMAXIMO IS 'Porcentaje máximo del bloque';
--/////////////////////
COMMENT ON COLUMN TBEP_APARTADOSBAREMACION.UID_USUARIO IS 'Ultimo usuario que hace cambios en la tabla';
--/////////////////////
COMMENT ON TABLE TBEP_APARTADOSBAREMACION IS 'Apartado de la baremación. ALIAS: [bepapa] ACRONIMO: [APA]';
--/////////////////////
CREATE TABLE TBEP_HTO_APARTADOSBAREMACION (
 	LOG VARCHAR(50) CONSTRAINT RBEP_NAPA_HTO_LOG NOT NULL,
 	CODCAMBIO NUMBER(11,0) CONSTRAINT RBEP_NAPA_HTO_CODCAMBIO NOT NULL,
 	FECHALOG TIMESTAMP DEFAULT CURRENT_TIMESTAMP CONSTRAINT RBEP_NAPA_HTO_FECHALOG NOT NULL,
	CODNUM NUMBER(11,0) CONSTRAINT RBEP_NAPA_HTO_CODNUM NOT NULL,
    CODIGO VARCHAR2(10 CHAR) CONSTRAINT RBEP_NAPA_HTO_CODIGO NOT NULL,
    NOMBRE VARCHAR2(100 CHAR) CONSTRAINT RBEP_NAPA_HTO_NOMBRE NOT NULL,
    FLGACTIVO CHAR(1) DEFAULT 'S',
    PUNTUACIONMAXIMA NUMBER(10, 6) NULL,
    PORCENTAJEMAXIMO NUMBER(10, 6) NULL,
    UID_USUARIO VARCHAR2(100) CONSTRAINT RBEP_NAPA_HTO_UIDUSUARIO NOT NULL,
	CONSTRAINT IBEP_PAPA_HISTORICO PRIMARY KEY (CODCAMBIO)
);
--/////////////////////
CREATE SEQUENCE QBEP_APA START WITH 1;
--/////////////////////
CREATE SEQUENCE QBEP_HTO_APA START WITH 1;
--/////////////////////
CREATE TRIGGER DBEP_APA_BRI
BEFORE INSERT
ON TBEP_APARTADOSBAREMACION
FOR EACH ROW
DECLARE
BEGIN
    SELECT QBEP_APA.nextval into :new.CODNUM FROM dual;	 	

    INSERT INTO TBEP_HTO_APARTADOSBAREMACION (CODCAMBIO,LOG,CODNUM,CODIGO,NOMBRE,FLGACTIVO,PUNTUACIONMAXIMA,PORCENTAJEMAXIMO,UID_USUARIO)
    VALUES (QBEP_HTO_APA.NEXTVAL,'AFTER_INSERT',:New.CODNUM,:New.CODIGO,:New.NOMBRE,:New.FLGACTIVO,:New.PUNTUACIONMAXIMA,:New.PORCENTAJEMAXIMO,:New.UID_USUARIO);
END DBEP_APA_BRI;
--/////////////////////
CREATE TRIGGER DBEP_APA_BRU
BEFORE UPDATE
ON TBEP_APARTADOSBAREMACION 
FOR EACH ROW
DECLARE
BEGIN
	INSERT INTO TBEP_HTO_APARTADOSBAREMACION (CODCAMBIO,LOG,CODNUM,CODIGO,NOMBRE,FLGACTIVO,PUNTUACIONMAXIMA,PORCENTAJEMAXIMO,UID_USUARIO)
    VALUES (QBEP_HTO_APA.NEXTVAL,'BEFORE_UPDATE',:Old.CODNUM,:Old.CODIGO,:Old.NOMBRE,:Old.FLGACTIVO,:Old.PUNTUACIONMAXIMA,:Old.PORCENTAJEMAXIMO,:Old.UID_USUARIO);   
    
 	INSERT INTO TBEP_HTO_APARTADOSBAREMACION (CODCAMBIO,LOG,CODNUM,CODIGO,NOMBRE,FLGACTIVO,PUNTUACIONMAXIMA,PORCENTAJEMAXIMO,UID_USUARIO)
    VALUES (QBEP_HTO_APA.NEXTVAL,'AFTER_UPDATE',:New.CODNUM,:New.CODIGO,:New.NOMBRE,:New.FLGACTIVO,:New.PUNTUACIONMAXIMA,:New.PORCENTAJEMAXIMO,:New.UID_USUARIO);
END DBEP_APA_BRU;
--/////////////////////
CREATE TRIGGER DBEP_APA_BRD
BEFORE DELETE
ON TBEP_APARTADOSBAREMACION 
FOR EACH ROW
DECLARE
BEGIN
	INSERT INTO TBEP_HTO_APARTADOSBAREMACION (CODCAMBIO,LOG,CODNUM,CODIGO,NOMBRE,FLGACTIVO,PUNTUACIONMAXIMA,PORCENTAJEMAXIMO,UID_USUARIO)
    VALUES (QBEP_HTO_APA.NEXTVAL,'BEFORE_DELETE',:Old.CODNUM,:Old.CODIGO,:Old.NOMBRE,:Old.FLGACTIVO,:Old.PUNTUACIONMAXIMA,:Old.PORCENTAJEMAXIMO,:Old.UID_USUARIO);
END DBEP_APA_BRD;
