CREATE TABLE UVIRTUAL.TBEP_BLOQUESBAREMACION (	
	CODNUM NUMBER(11,0) CONSTRAINT RBEP_NBLO_CODNUM NOT NULL,
    BEPAPA_CODNUM NUMBER(11,0) CONSTRAINT RBEP_NBLO_BEPAPA_CODNUM NOT NULL,
    CODIGO VARCHAR2(10 CHAR) CONSTRAINT RBEP_NBLO_CODIGO NOT NULL,
    NOMBRE VARCHAR2(100 CHAR) CONSTRAINT RBEP_NBLO_NOMBRE NOT NULL,
    FLGACTIVO CHAR(1) DEFAULT 'S',
    NUMERO_MAXIMO_MERITOS NUMBER(2, 0) NULL, 
    CONSTRAINT IBEP_PBLO PRIMARY KEY (CODNUM),
    CONSTRAINT IBEP_UBLO_CODIGO UNIQUE (CODIGO, BEPAPA_CODNUM),
    CONSTRAINT IBEP_FBLO_APA FOREIGN KEY (BEPAPA_CODNUM) REFERENCES TBEP_APARTADOSBAREMACION (CODNUM),
    CONSTRAINT RBEP_CBLO_FLGACTIVO CHECK (FLGACTIVO IN ('N','S'))
);
--/////////////////////
COMMENT ON COLUMN TBEP_BLOQUESBAREMACION.CODIGO IS 'Código del bloque de baremación';
--/////////////////////
COMMENT ON COLUMN TBEP_BLOQUESBAREMACION.BEPAPA_CODNUM IS 'Fk a al apartado de baremación';
--/////////////////////
COMMENT ON COLUMN TBEP_BLOQUESBAREMACION.NOMBRE IS 'Nombre del bloque';
--/////////////////////
COMMENT ON COLUMN TBEP_BLOQUESBAREMACION.FLGACTIVO IS 'Indica si está activo o no';
--/////////////////////
COMMENT ON COLUMN TBEP_BLOQUESBAREMACION.NUMERO_MAXIMO_MERITOS IS 'Número máximo de méritos';
--/////////////////////
COMMENT ON TABLE TBEP_BLOQUESBAREMACION IS 'Bloque de la baremación. ALIAS: [bepblo] ACRONIMO: [BLO]';
--/////////////////////
CREATE TABLE UVIRTUAL.TBEP_HTO_BLOQUESBAREMACION (
 	CODCAMBIO NUMBER(11,0) CONSTRAINT RBEP_NBLO_HTO_CODCAMBIO NOT NULL,
 	LOG VARCHAR(50) CONSTRAINT RBEP_NBLO_HTO_LOG NOT NULL,
 	FECHALOG TIMESTAMP DEFAULT CURRENT_TIMESTAMP CONSTRAINT RBEP_NBLO_HTO_FECHALOG NOT NULL,
	CODNUM NUMBER(11,0) CONSTRAINT RBEP_NBLO_HTO_CODNUM NOT NULL,
    BEPAPA_CODNUM NUMBER(11,0) CONSTRAINT RBEP_NBLO_HTO_BEPAPA_CODNUM NOT NULL,
    CODIGO VARCHAR2(10 CHAR) CONSTRAINT RBEP_NBLO_HTO_CODIGO NOT NULL,
    NOMBRE VARCHAR2(100 CHAR) CONSTRAINT RBEP_NBLO_HTO_NOMBRE NOT NULL,
    FLGACTIVO CHAR(1) DEFAULT 'S',
    NUMERO_MAXIMO_MERITOS NUMBER(2, 0) NULL, 
	CONSTRAINT IBEP_PBLO_HISTORICO PRIMARY KEY (CODCAMBIO)
);
--/////////////////////
CREATE SEQUENCE QBEP_BLO START WITH 1;
--/////////////////////
CREATE SEQUENCE QBEP_HTO_BLO START WITH 1;
--/////////////////////
CREATE TRIGGER DBEP_BLO_BRI
BEFORE INSERT
ON TBEP_BLOQUESBAREMACION
FOR EACH ROW
DECLARE
BEGIN
    SELECT QBEP_BLO.nextval into :new.CODNUM FROM dual;

    INSERT INTO TBEP_HTO_BLOQUESBAREMACION (CODCAMBIO,LOG,CODNUM,BEPAPA_CODNUM,CODIGO,NOMBRE,FLGACTIVO,NUMERO_MAXIMO_MERITOS)
    VALUES (QBEP_HTO_BLO.NEXTVAL,'AFTER_INSERT',:New.CODNUM,:New.BEPAPA_CODNUM,:New.CODIGO,:New.NOMBRE,:New.FLGACTIVO,:New.NUMERO_MAXIMO_MERITOS);
END DBEP_BLO_BRI;
--/////////////////////
CREATE TRIGGER DBEP_BLO_BRU
BEFORE UPDATE
ON TBEP_BLOQUESBAREMACION
FOR EACH ROW
DECLARE
BEGIN
	INSERT INTO TBEP_HTO_BLOQUESBAREMACION (CODCAMBIO,LOG,CODNUM,BEPAPA_CODNUM,CODIGO,NOMBRE,FLGACTIVO,NUMERO_MAXIMO_MERITOS)
    VALUES (QBEP_HTO_BLO.NEXTVAL,'BEFORE_UPDATE',:Old.CODNUM,:Old.BEPAPA_CODNUM,:Old.CODIGO,:Old.NOMBRE,:Old.FLGACTIVO,:Old.NUMERO_MAXIMO_MERITOS);   
    
 	INSERT INTO TBEP_HTO_BLOQUESBAREMACION (CODCAMBIO,LOG,CODNUM,BEPAPA_CODNUM,CODIGO,NOMBRE,FLGACTIVO,NUMERO_MAXIMO_MERITOS)
    VALUES (QBEP_HTO_BLO.NEXTVAL,'AFTER_UPDATE',:New.CODNUM,:New.BEPAPA_CODNUM,:New.CODIGO,:New.NOMBRE,:New.FLGACTIVO,:New.NUMERO_MAXIMO_MERITOS);
END DBEP_BLO_BRU;
--/////////////////////
CREATE TRIGGER DBEP_BLO_BRD
BEFORE DELETE
ON TBEP_BLOQUESBAREMACION 
FOR EACH ROW
DECLARE
BEGIN
	INSERT INTO TBEP_HTO_BLOQUESBAREMACION (CODCAMBIO,LOG,CODNUM,BEPAPA_CODNUM,CODIGO,NOMBRE,FLGACTIVO,NUMERO_MAXIMO_MERITOS)
    VALUES (QBEP_HTO_BLO.NEXTVAL,'BEFORE_DELETE',:Old.CODNUM,:Old.BEPAPA_CODNUM,:Old.CODIGO,:Old.NOMBRE,:Old.FLGACTIVO,:Old.NUMERO_MAXIMO_MERITOS);
END DBEP_BLO_BRD;
