CREATE TABLE UVIRTUAL.TBEP_BLOQUESBAREMACION (	
	CODNUM NUMBER(11,0) NOT NULL, 
    BEPAPA_CODNUM NUMBER(11,0) NOT NULL,
    CODIGO VARCHAR2(10 BYTE) NOT NULL,
    NOMBRE VARCHAR2(100 BYTE) NOT NULL,
    FLGACTIVO CHAR(1) DEFAULT 'S',
    CONSTRAINT IBEP_PBLO PRIMARY KEY (CODNUM),
    CONSTRAINT IBEP_UBLO_CODIGO UNIQUE (CODIGO,BEPAPA_CODNUM),
    CONSTRAINT IBEP_FBLO_APA FOREIGN KEY (BEPAPA_CODNUM) REFERENCES TBEP_APARTADOSBAREMACION (CODNUM),
    CHECK (FLGACTIVO IN ('N','S'))    
);
--/////////////////////
COMMENT ON COLUMN TBEP_BLOQUESBAREMACION.CODIGO IS 'Código del bloque de baremación';
--/////////////////////
COMMENT ON COLUMN TBEP_BLOQUESBAREMACION.BEPAPA_CODNUM IS 'Fk a al apartado de baremación';
--/////////////////////
COMMENT ON COLUMN TBEP_BLOQUESBAREMACION.NOMBRE IS 'Nombre del bloque';
--/////////////////////
COMMENT ON COLUMN TBEP_BLOQUESBAREMACION.FLGACTIVO IS 'Indica si está activo o no';
--/////////////////////
COMMENT ON TABLE TBEP_BLOQUESBAREMACION IS 'Bloque de la baremación. ALIAS: [bepblo] ACRONIMO: [BLO]';
--/////////////////////
CREATE TABLE UVIRTUAL.TBEP_HTO_BLOQUESBAREMACION (
 	CODCAMBIO NUMBER(11,0) NOT NULL,
 	LOG VARCHAR(50) NOT NULL,
 	FECHALOG TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
	CODNUM NUMBER(11,0) NOT NULL,
    BEPAPA_CODNUM NUMBER(11,0) NOT NULL,
    CODIGO VARCHAR2(10 BYTE) NOT NULL,
    NOMBRE VARCHAR2(100 BYTE) NOT NULL,
    FLGACTIVO CHAR(1) DEFAULT 'S',
	CONSTRAINT IBEP_PBLO_HISTORICO PRIMARY KEY (CODCAMBIO)
);
--/////////////////////
CREATE SEQUENCE QBEP_BLO START WITH 1;
--/////////////////////
CREATE SEQUENCE QBEP_HTO_BLO START WITH 1;
--/////////////////////
CREATE TRIGGER DBEP_BLO_BRI
BEFORE INSERT
ON TBEP_BLOQUESBAREMACION
FOR EACH ROW
DECLARE
BEGIN
    SELECT QBEP_BLO.nextval into :new.CODNUM FROM dual;

    INSERT INTO TBEP_HTO_BLOQUESBAREMACION (CODCAMBIO,LOG,CODNUM,BEPAPA_CODNUM,CODIGO,NOMBRE,FLGACTIVO)
    VALUES (QBEP_HTO_BLO.NEXTVAL,'AFTER_INSERT',:New.CODNUM,:New.BEPAPA_CODNUM,:New.CODIGO,:New.NOMBRE,:New.FLGACTIVO);
END DBEP_BLO_BRI;
--/////////////////////
CREATE TRIGGER DBEP_BLO_BRU
BEFORE UPDATE
ON TBEP_BLOQUESBAREMACION
FOR EACH ROW
DECLARE
BEGIN
	INSERT INTO TBEP_HTO_BLOQUESBAREMACION (CODCAMBIO,LOG,CODNUM,BEPAPA_CODNUM,CODIGO,NOMBRE,FLGACTIVO)
    VALUES (QBEP_HTO_BLO.NEXTVAL,'BEFORE_UPDATE',:Old.CODNUM,:Old.BEPAPA_CODNUM,:Old.CODIGO,:Old.NOMBRE,:Old.FLGACTIVO);   
    
 	INSERT INTO TBEP_HTO_BLOQUESBAREMACION (CODCAMBIO,LOG,CODNUM,BEPAPA_CODNUM,CODIGO,NOMBRE,FLGACTIVO)
    VALUES (QBEP_HTO_BLO.NEXTVAL,'AFTER_UPDATE',:New.CODNUM,:New.BEPAPA_CODNUM,:New.CODIGO,:New.NOMBRE,:New.FLGACTIVO);
END DBEP_BLO_BRU;
--/////////////////////
CREATE TRIGGER DBEP_BLO_BRD
BEFORE DELETE
ON TBEP_BLOQUESBAREMACION 
FOR EACH ROW
DECLARE
BEGIN
	INSERT INTO TBEP_HTO_BLOQUESBAREMACION (CODCAMBIO,LOG,CODNUM,BEPAPA_CODNUM,CODIGO,NOMBRE,FLGACTIVO)
    VALUES (QBEP_HTO_BLO.NEXTVAL,'BEFORE_DELETE',:Old.CODNUM,:Old.BEPAPA_CODNUM,:Old.CODIGO,:Old.NOMBRE,:Old.FLGACTIVO);
END DBEP_BLO_BRD;
