CREATE TABLE UVIRTUAL.TBEP_CATEGORIABAREMACION (	
	CODNUM NUMBER(11,0) CONSTRAINT RBEP_NCAT_CODNUM NOT NULL,
    BEPBLO_CODNUM NUMBER(11,0) CONSTRAINT RBEP_NCAT_BEPBLO_CODNUM NOT NULL,
    CODIGO VARCHAR2(1 BYTE) CONSTRAINT RBEP_NCAT_CODIGO NOT NULL,
    NOMBRE VARCHAR2(100 BYTE) CONSTRAINT RBEP_NCAT_NOMBRE NOT NULL,
    FLGACTIVO CHAR(1) DEFAULT 'S',
    CONSTRAINT IBEP_PCAT PRIMARY KEY (CODNUM),
    CONSTRAINT IBEP_UCAT_CODIGO UNIQUE (CODIGO),
    CONSTRAINT IBEP_FCAT_BLO FOREIGN KEY (BEPBLO_CODNUM) REFERENCES TBEP_BLOQUESBAREMACION (CODNUM),
    CHECK (FLGACTIVO IN ('N','S'))
);
--/////////////////////
COMMENT ON COLUMN TBEP_CATEGORIABAREMACION.CODIGO IS 'Código de la categoría de baremación';
--/////////////////////
COMMENT ON COLUMN TBEP_CATEGORIABAREMACION.BEPBLO_CODNUM IS 'Fk a al bloque de baremación';
--/////////////////////
COMMENT ON COLUMN TBEP_CATEGORIABAREMACION.NOMBRE IS 'Nombre de la categoria';
--/////////////////////
COMMENT ON COLUMN TBEP_CATEGORIABAREMACION.FLGACTIVO IS 'Indica si está activa o no';
--/////////////////////
COMMENT ON TABLE TBEP_CATEGORIABAREMACION IS 'Categoría de la baremación. ALIAS: [bepcat] ACRONIMO: [CAT]';
--/////////////////////
CREATE TABLE UVIRTUAL.TBEP_HTO_CATEGORIABAREMACION (
 	CODCAMBIO NUMBER(11,0) CONSTRAINT RBEP_NCAT_HTO_CODCAMBIO NOT NULL,
 	LOG VARCHAR(50) CONSTRAINT RBEP_NCAT_HTO_LOG NOT NULL,
 	FECHALOG TIMESTAMP DEFAULT CURRENT_TIMESTAMP CONSTRAINT RBEP_NCAT_HTO_FECHALOG NOT NULL,
	CODNUM NUMBER(11,0) CONSTRAINT RBEP_NCAT_HTO_CODNUM NOT NULL,
    BEPBLO_CODNUM NUMBER(11,0) CONSTRAINT RBEP_NCAT_HTO_BEPBLO_CODNUM NOT NULL,
    CODIGO VARCHAR2(1 BYTE) CONSTRAINT RBEP_NCAT_HTO_CODIGO NOT NULL,
    NOMBRE VARCHAR2(100 BYTE) CONSTRAINT RBEP_NCAT_HTO_NOMBRE NOT NULL,
    FLGACTIVO CHAR(1) DEFAULT 'S',
	CONSTRAINT IBEP_PCAT_HISTORICO PRIMARY KEY (CODCAMBIO)
);
--/////////////////////
CREATE SEQUENCE QBEP_CAT START WITH 1;
--/////////////////////
CREATE SEQUENCE QBEP_HTO_CAT START WITH 1;
--/////////////////////
CREATE TRIGGER DBEP_CAT_BRI
BEFORE INSERT
ON TBEP_CATEGORIABAREMACION
FOR EACH ROW
DECLARE
BEGIN
    SELECT QBEP_CAT.nextval into :new.CODNUM FROM dual;

    INSERT INTO TBEP_HTO_CATEGORIABAREMACION (CODCAMBIO,LOG,CODNUM,BEPBLO_CODNUM,CODIGO,NOMBRE,FLGACTIVO)
    VALUES (QBEP_HTO_CAT.NEXTVAL,'AFTER_INSERT',:New.CODNUM,:New.BEPBLO_CODNUM,:New.CODIGO,:New.NOMBRE,:New.FLGACTIVO);
END DBEP_CAT_BRI;
--/////////////////////
CREATE TRIGGER DBEP_CAT_BRU
BEFORE UPDATE
ON TBEP_CATEGORIABAREMACION
FOR EACH ROW
DECLARE
BEGIN
	INSERT INTO TBEP_HTO_CATEGORIABAREMACION (CODCAMBIO,LOG,CODNUM,BEPBLO_CODNUM,CODIGO,NOMBRE,FLGACTIVO)
    VALUES (QBEP_HTO_CAT.NEXTVAL,'BEFORE_UPDATE',:Old.CODNUM,:Old.BEPBLO_CODNUM,:Old.CODIGO,:Old.NOMBRE,:Old.FLGACTIVO);   
    
 	INSERT INTO TBEP_HTO_CATEGORIABAREMACION (CODCAMBIO,LOG,CODNUM,BEPBLO_CODNUM,CODIGO,NOMBRE,FLGACTIVO)
    VALUES (QBEP_HTO_CAT.NEXTVAL,'AFTER_UPDATE',:New.CODNUM,:New.BEPBLO_CODNUM,:New.CODIGO,:New.NOMBRE,:New.FLGACTIVO);
END DBEP_CAT_BRU;
--/////////////////////
CREATE TRIGGER DBEP_CAT_BRD
BEFORE DELETE
ON TBEP_CATEGORIABAREMACION 
FOR EACH ROW
DECLARE
BEGIN
	INSERT INTO TBEP_HTO_CATEGORIABAREMACION (CODCAMBIO,LOG,CODNUM,BEPBLO_CODNUM,CODIGO,NOMBRE,FLGACTIVO)
    VALUES (QBEP_HTO_CAT.NEXTVAL,'BEFORE_DELETE',:Old.CODNUM,:Old.BEPBLO_CODNUM,:Old.CODIGO,:Old.NOMBRE,:Old.FLGACTIVO);
END DBEP_CAT_BRD;
