CREATE TABLE UVIRTUAL.TBEP_ITEMSBAREMACION (	
	CODNUM NUMBER(11,0) CONSTRAINT RBEP_NITE_CODNUM NOT NULL, 
	BEPBLO_CODNUM NUMBER(11,0) CONSTRAINT RBEP_NITE_BEPBLO_CODNUM NOT NULL,  
	CODIGO VARCHAR2(10 CHAR) CONSTRAINT RBEP_NITE_CODIGO NOT NULL,  
    NOMBRE VARCHAR2(1000 CHAR) CONSTRAINT RBEP_NITE_NOMBRE NOT NULL,  
    DESCRIPCION VARCHAR2(1000 CHAR) DEFAULT NULL,
    FLGACTIVO CHAR(1) DEFAULT 'S',
    UNIDADES VARCHAR2(10 CHAR) DEFAULT 'ENTERO',
    VALOR NUMBER(6, 2) CONSTRAINT RBEP_NITE_VALOR NOT NULL,   
    VALOR_MINIMO NUMBER(6, 2) CONSTRAINT RBEP_NITE_VALOR_MINIMO NOT NULL,  
    VALOR_MAXIMO NUMBER(6, 2) CONSTRAINT RBEP_NITE_VALOR_MAXIMO NOT NULL,  
    AFINIDAD VARCHAR2(10 CHAR) NULL,
    INDIVIDUALIZADO CHAR(1) DEFAULT 'S',
    CONSTRAINT IBEP_PITE PRIMARY KEY (CODNUM),
    CONSTRAINT IBEP_FBLO_ITE FOREIGN KEY (BEPBLO_CODNUM) REFERENCES TBEP_BLOQUESBAREMACION (CODNUM),
    CONSTRAINT RBEP_CITE_FLGACTIVO CHECK (FLGACTIVO IN ('N','S')),
    CONSTRAINT RBEP_CITE_UNIDADES CHECK (UNIDADES IN ('ENTERO','DECIMAL','SI/NO'))
);
--/////////////////////
COMMENT ON COLUMN TBEP_ITEMSBAREMACION.CODIGO IS 'Código del ítem de baremación';
--/////////////////////
COMMENT ON COLUMN TBEP_ITEMSBAREMACION.BEPBLO_CODNUM IS 'Fk al bloque de baremación';
--/////////////////////
COMMENT ON COLUMN TBEP_ITEMSBAREMACION.NOMBRE IS 'Nombre del ítem';
--/////////////////////
COMMENT ON COLUMN TBEP_ITEMSBAREMACION.DESCRIPCION IS 'Descripción del ítem';
--/////////////////////
COMMENT ON COLUMN TBEP_ITEMSBAREMACION.FLGACTIVO IS 'Indica si está activo o no';
--/////////////////////
COMMENT ON COLUMN TBEP_ITEMSBAREMACION.UNIDADES IS 'Tipo de unidades del item';
--/////////////////////
COMMENT ON COLUMN TBEP_ITEMSBAREMACION.VALOR IS 'Valor de las unidades del item';
--/////////////////////
COMMENT ON TABLE TBEP_ITEMSBAREMACION IS 'Item de la baremación. ALIAS: [bepite] ACRONIMO: [ITE]';
--/////////////////////
CREATE TABLE UVIRTUAL.TBEP_HTO_ITEMSBAREMACION (
 	CODCAMBIO NUMBER(11,0) CONSTRAINT RBEP_NITE_HTO_CODCAMBIO NOT NULL, 
 	LOG VARCHAR(50) CONSTRAINT RBEP_NITE_HTO_LOG NOT NULL, 
 	FECHALOG TIMESTAMP DEFAULT CURRENT_TIMESTAMP CONSTRAINT RBEP_NITE_HTO_FECHALOG NOT NULL,
	CODNUM NUMBER(11,0) CONSTRAINT RBEP_NITE_HTO_CODNUM NOT NULL, 
    BEPBLO_CODNUM NUMBER(11,0) CONSTRAINT RBEP_NITE_HTO_BEPBLO_CODNUM NOT NULL, 
    CODIGO VARCHAR2(10 CHAR) CONSTRAINT RBEP_NITE_HTO_CODIGO NOT NULL, 
    NOMBRE VARCHAR2(1000 CHAR) CONSTRAINT RBEP_NITE_HTO_NOMBRE NOT NULL, 
    DESCRIPCION VARCHAR2(1000 CHAR) DEFAULT NULL, 
    FLGACTIVO CHAR(1) DEFAULT 'S',
    UNIDADES VARCHAR2(10 CHAR) DEFAULT 'UNIDADES',
    VALOR NUMBER(6, 2) CONSTRAINT RBEP_NITE_HTO_VALOR NOT NULL,  
    VALOR_MINIMO NUMBER(6, 2) CONSTRAINT RBEP_NITE_HTO_VALOR_MINIMO NOT NULL, 
    VALOR_MAXIMO NUMBER(6, 2) CONSTRAINT RBEP_NITE_HTO_VALOR_MAXIMO NOT NULL, 
    AFINIDAD VARCHAR2(10 CHAR) NULL,  
    INDIVIDUALIZADO CHAR(1) DEFAULT 'S',
	CONSTRAINT IBEP_PITE_HISTORICO PRIMARY KEY (CODCAMBIO)
);
--/////////////////////
CREATE SEQUENCE QBEP_ITE START WITH 1;
--/////////////////////
CREATE SEQUENCE QBEP_HTO_ITE START WITH 1;
--/////////////////////
CREATE TRIGGER DBEP_ITE_BRI
BEFORE INSERT
ON TBEP_ITEMSBAREMACION
FOR EACH ROW
DECLARE
BEGIN
    SELECT QBEP_ITE.nextval into :new.CODNUM FROM dual;

    INSERT INTO TBEP_HTO_ITEMSBAREMACION (CODCAMBIO,LOG,CODNUM,BEPBLO_CODNUM,CODIGO,NOMBRE,DESCRIPCION,FLGACTIVO,UNIDADES,VALOR,VALOR_MINIMO,VALOR_MAXIMO,AFINIDAD,INDIVIDUALIZADO)
    VALUES (QBEP_HTO_ITE.NEXTVAL,'AFTER_INSERT',:New.CODNUM,:New.BEPBLO_CODNUM,:New.CODIGO,:New.NOMBRE,:New.DESCRIPCION,:New.FLGACTIVO,:New.UNIDADES,:New.VALOR,:New.VALOR_MINIMO,:New.VALOR_MAXIMO,:New.AFINIDAD,:New.INDIVIDUALIZADO);
END DBEP_ITE_BRI;
--/////////////////////
CREATE TRIGGER DBEP_ITE_BRU
BEFORE UPDATE
ON TBEP_ITEMSBAREMACION
FOR EACH ROW
DECLARE
BEGIN
	INSERT INTO TBEP_HTO_ITEMSBAREMACION (CODCAMBIO,LOG,CODNUM,BEPBLO_CODNUM,CODIGO,NOMBRE,DESCRIPCION,FLGACTIVO,UNIDADES,VALOR,VALOR_MINIMO,VALOR_MAXIMO,AFINIDAD,INDIVIDUALIZADO)
    VALUES (QBEP_HTO_ITE.NEXTVAL,'BEFORE_UPDATE',:Old.CODNUM,:Old.BEPBLO_CODNUM,:Old.CODIGO,:Old.NOMBRE,:Old.DESCRIPCION,:Old.FLGACTIVO,:Old.UNIDADES,:Old.VALOR,:Old.VALOR_MINIMO,:Old.VALOR_MAXIMO,:Old.AFINIDAD,:Old.INDIVIDUALIZADO);   
    
 	INSERT INTO TBEP_HTO_ITEMSBAREMACION (CODCAMBIO,LOG,CODNUM,BEPBLO_CODNUM,CODIGO,NOMBRE,DESCRIPCION,FLGACTIVO,UNIDADES,VALOR,VALOR_MINIMO,VALOR_MAXIMO,AFINIDAD,INDIVIDUALIZADO)
    VALUES (QBEP_HTO_ITE.NEXTVAL,'AFTER_UPDATE',:New.CODNUM,:New.BEPBLO_CODNUM,:New.CODIGO,:New.NOMBRE,:New.DESCRIPCION,:New.FLGACTIVO,:New.UNIDADES,:New.VALOR,:New.VALOR_MINIMO,:New.VALOR_MAXIMO,:New.AFINIDAD,:New.INDIVIDUALIZADO);
END DBEP_ITE_BRU;
--/////////////////////
CREATE TRIGGER DBEP_ITE_BRD
BEFORE DELETE
ON TBEP_ITEMSBAREMACION 
FOR EACH ROW
DECLARE
BEGIN
	INSERT INTO TBEP_HTO_ITEMSBAREMACION (CODCAMBIO,LOG,CODNUM,BEPBLO_CODNUM,CODIGO,NOMBRE,DESCRIPCION,FLGACTIVO,UNIDADES,VALOR,VALOR_MINIMO,VALOR_MAXIMO,AFINIDAD,INDIVIDUALIZADO)
    VALUES (QBEP_HTO_ITE.NEXTVAL,'BEFORE_DELETE',:Old.CODNUM,:Old.BEPBLO_CODNUM,:Old.CODIGO,:Old.NOMBRE,:Old.DESCRIPCION,:Old.FLGACTIVO,:Old.UNIDADES,:Old.VALOR,:Old.VALOR_MINIMO,:Old.VALOR_MAXIMO,:Old.AFINIDAD,:Old.INDIVIDUALIZADO);
END DBEP_ITE_BRD;
