CREATE TABLE TBEP_AFINIDADES (
	CODNUM NUMBER(11,0) CONSTRAINT RBEP_NAFI_CODNUM NOT NULL,
	CODIGO VARCHAR2(4 CHAR) CONSTRAINT RBEP_NAFI_CODIGO NOT NULL,
	DESCRIPCION VARCHAR2(250 CHAR) CONSTRAINT RBEP_NAFI_DESCRIPCION NOT NULL,
	MODULACION FLOAT(11) CONSTRAINT RBEP_NAFI_MODULACION NOT NULL,
	FLGBORRADO CHAR(1) DEFAULT 'N',
    FECHA_BORRADO TIMESTAMP NULL,
    UID_USUARIO VARCHAR2(100) CONSTRAINT RBEP_NAFI_UIDUSUARIO NOT NULL,
	CONSTRAINT IBEP_PAFI PRIMARY KEY (CODNUM),
	CONSTRAINT RBEP_CAFI_FLGBORRADO CHECK(FLGBORRADO IN ('N','S'))
);
--/////////////////////
COMMENT ON COLUMN TBEP_AFINIDADES.CODIGO IS 'Código de la afinidad';
--/////////////////////
COMMENT ON COLUMN TBEP_AFINIDADES.DESCRIPCION IS 'Descripcion de la afinidad';
--/////////////////////
COMMENT ON COLUMN TBEP_AFINIDADES.MODULACION IS 'Modulación relacionada a la afinidad';
--/////////////////////
COMMENT ON COLUMN TBEP_AFINIDADES.UID_USUARIO IS 'Ultimo usuario que hace cambios en la tabla';
--/////////////////////
COMMENT ON TABLE TBEP_AFINIDADES IS 'Tabla que almacena las afinidades del sistema. ALIAS: [bepafi] ACRONIMO: [AFI]';
--/////////////////////
CREATE TABLE TBEP_HTO_AFINIDADES (
 	CODCAMBIO NUMBER(11,0) CONSTRAINT RBEP_NAFI_HTO_CODCAMBIO NOT NULL,
 	LOG VARCHAR(50) CONSTRAINT RBEP_NAFI_HTO_LOG NOT NULL,
 	FECHALOG TIMESTAMP DEFAULT CURRENT_TIMESTAMP CONSTRAINT RBEP_NAFI_HTO_FECHALOG NOT NULL,
 	CODNUM NUMBER(11,0) CONSTRAINT RBEP_NAFI_HTO_CODNUM NOT NULL,
	CODIGO VARCHAR2(4 CHAR) CONSTRAINT RBEP_NAFI_HTO_CODIGO NOT NULL,
	DESCRIPCION VARCHAR2(250 CHAR) DEFAULT NULL,
	MODULACION FLOAT(11) CONSTRAINT RBEP_NAFI_HTO_MODULACION NOT NULL,
	FLGBORRADO CHAR(1) DEFAULT 'N',
    FECHA_BORRADO TIMESTAMP NULL,
    UID_USUARIO VARCHAR2(100) CONSTRAINT RBEP_NAFI_HTO_UIDUSUARIO NOT NULL,
	CONSTRAINT IBEP_PAFI_HISTORICO PRIMARY KEY (CODCAMBIO)
);
--/////////////////////
CREATE SEQUENCE QBEP_AFI START WITH 1;
--/////////////////////
CREATE SEQUENCE QBEP_HTO_AFI START WITH 1;
--/////////////////////
CREATE TRIGGER DBEP_AFI_BRI
BEFORE INSERT
ON TBEP_AFINIDADES
FOR EACH ROW
DECLARE
BEGIN
	SELECT QBEP_AFI.nextval into :new.CODNUM FROM dual;	 	
	
    INSERT INTO TBEP_HTO_AFINIDADES (CODCAMBIO,LOG,CODNUM,CODIGO,DESCRIPCION,MODULACION,FLGBORRADO,FECHA_BORRADO,UID_USUARIO)
    VALUES (QBEP_HTO_AFI.NEXTVAL,'AFTER_INSERT',:New.CODNUM,:New.CODIGO,:New.DESCRIPCION,:New.MODULACION,:New.FLGBORRADO,:New.FECHA_BORRADO,:New.UID_USUARIO);
END DBEP_AFI_BRI;
--/////////////////////
CREATE TRIGGER DBEP_AFI_BRU
BEFORE UPDATE
ON TBEP_AFINIDADES
FOR EACH ROW
DECLARE
BEGIN
	INSERT INTO TBEP_HTO_AFINIDADES (CODCAMBIO,LOG,CODNUM,CODIGO,DESCRIPCION,MODULACION,FLGBORRADO,FECHA_BORRADO,UID_USUARIO)
    VALUES (QBEP_HTO_AFI.NEXTVAL,'BEFORE_UPDATE',:Old.CODNUM,:Old.CODIGO,:Old.DESCRIPCION,:Old.MODULACION,:Old.FLGBORRADO,:Old.FECHA_BORRADO,:Old.UID_USUARIO);
    
 	INSERT INTO TBEP_HTO_AFINIDADES (CODCAMBIO,LOG,CODNUM,CODIGO,DESCRIPCION,MODULACION,FLGBORRADO,FECHA_BORRADO,UID_USUARIO)
    VALUES (QBEP_HTO_AFI.NEXTVAL,'AFTER_UPDATE',:New.CODNUM,:New.CODIGO,:New.DESCRIPCION,:New.MODULACION,:New.FLGBORRADO,:New.FECHA_BORRADO,:New.UID_USUARIO);
END DBEP_AFI_BRU;
--/////////////////////
CREATE TRIGGER DBEP_AFI_BRD
BEFORE DELETE
ON TBEP_AFINIDADES
FOR EACH ROW
DECLARE
BEGIN
	INSERT INTO TBEP_HTO_AFINIDADES (CODCAMBIO,LOG,CODNUM,CODIGO,DESCRIPCION,MODULACION,FLGBORRADO,FECHA_BORRADO,UID_USUARIO)
    VALUES (QBEP_HTO_AFI.NEXTVAL,'BEFORE_DELETE',:Old.CODNUM,:Old.CODIGO,:Old.DESCRIPCION,:Old.MODULACION,:Old.FLGBORRADO,:Old.FECHA_BORRADO,:Old.UID_USUARIO);
END DBEP_AFI_BRD;
