CREATE TABLE UVIRTUAL.TBEP_ITEMSBAREMACION (	
	CODNUM NUMBER(11,0) NOT NULL,
	BEPBLO_CODNUM NUMBER(11,0) NOT NULL,
	CODIGO VARCHAR2(10 BYTE) NOT NULL,
    NOMBRE VARCHAR2(100 BYTE) NOT NULL,
    FLGACTIVO CHAR(1) DEFAULT 'S',
    CONSTRAINT IBEP_PITE PRIMARY KEY (CODNUM),
    CONSTRAINT IBEP_UITE_CODIGO UNIQUE (CODIGO),
    CONSTRAINT IBEP_FBLO_ITE FOREIGN KEY (BEPBLO_CODNUM) REFERENCES TBEP_BLOQUESBAREMACION (CODNUM),
    CHECK (FLGACTIVO IN ('N','S'))    
);
--/////////////////////
COMMENT ON COLUMN TBEP_ITEMSBAREMACION.CODIGO IS 'Código del ítem de baremación';
--/////////////////////
COMMENT ON COLUMN TBEP_ITEMSBAREMACION.BEPBLO_CODNUM IS 'Fk al bloque de baremación';
--/////////////////////
COMMENT ON COLUMN TBEP_ITEMSBAREMACION.NOMBRE IS 'Nombre del ítem';
--/////////////////////
COMMENT ON COLUMN TBEP_ITEMSBAREMACION.FLGACTIVO IS 'Indica si está activo o no';
--/////////////////////
COMMENT ON TABLE TBEP_ITEMSBAREMACION IS 'Item de la baremación. ALIAS: [bepite] ACRONIMO: [ITE]';
--/////////////////////
CREATE TABLE UVIRTUAL.TBEP_HTO_ITEMSBAREMACION (
 	CODCAMBIO NUMBER(11,0) NOT NULL,
 	LOG VARCHAR(50) NOT NULL,
 	FECHALOG TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
	CODNUM NUMBER(11,0) NOT NULL,
    BEPBLO_CODNUM NUMBER(11,0) NOT NULL,
    CODIGO VARCHAR2(10 BYTE) NOT NULL,
    NOMBRE VARCHAR2(100 BYTE) NOT NULL,
    FLGACTIVO CHAR(1) DEFAULT 'S',
	CONSTRAINT IBEP_PITE_HISTORICO PRIMARY KEY (CODCAMBIO)
);
--/////////////////////
CREATE SEQUENCE QBEP_ITE START WITH 1;
--/////////////////////
CREATE SEQUENCE QBEP_HTO_ITE START WITH 1;
--/////////////////////
CREATE TRIGGER DBEP_ITE_BRI
BEFORE INSERT
ON TBEP_ITEMSBAREMACION
FOR EACH ROW
DECLARE
BEGIN
    SELECT QBEP_ITE.nextval into :new.CODNUM FROM dual;

    INSERT INTO TBEP_HTO_ITEMSBAREMACION (CODCAMBIO,LOG,CODNUM,BEPBLO_CODNUM,CODIGO,NOMBRE,FLGACTIVO)
    VALUES (QBEP_HTO_ITE.NEXTVAL,'AFTER_INSERT',:New.CODNUM,:New.BEPBLO_CODNUM,:New.CODIGO,:New.NOMBRE,:New.FLGACTIVO);
END DBEP_ITE_BRI;
--/////////////////////
CREATE TRIGGER DBEP_ITE_BRU
BEFORE UPDATE
ON TBEP_ITEMSBAREMACION
FOR EACH ROW
DECLARE
BEGIN
	INSERT INTO TBEP_HTO_ITEMSBAREMACION (CODCAMBIO,LOG,CODNUM,BEPBLO_CODNUM,CODIGO,NOMBRE,FLGACTIVO)
    VALUES (QBEP_HTO_ITE.NEXTVAL,'BEFORE_UPDATE',:Old.CODNUM,:Old.BEPBLO_CODNUM,:Old.CODIGO,:Old.NOMBRE,:Old.FLGACTIVO);   
    
 	INSERT INTO TBEP_HTO_ITEMSBAREMACION (CODCAMBIO,LOG,CODNUM,BEPBLO_CODNUM,CODIGO,NOMBRE,FLGACTIVO)
    VALUES (QBEP_HTO_ITE.NEXTVAL,'AFTER_UPDATE',:New.CODNUM,:New.BEPBLO_CODNUM,:New.CODIGO,:New.NOMBRE,:New.FLGACTIVO);
END DBEP_ITE_BRU;
--/////////////////////
CREATE TRIGGER DBEP_ITE_BRD
BEFORE DELETE
ON TBEP_ITEMSBAREMACION 
FOR EACH ROW
DECLARE
BEGIN
	INSERT INTO TBEP_HTO_ITEMSBAREMACION (CODCAMBIO,LOG,CODNUM,BEPBLO_CODNUM,CODIGO,NOMBRE,FLGACTIVO)
    VALUES (QBEP_HTO_ITE.NEXTVAL,'BEFORE_DELETE',:Old.CODNUM,:Old.BEPBLO_CODNUM,:Old.CODIGO,:Old.NOMBRE,:Old.FLGACTIVO);
END DBEP_ITE_BRD;