CREATE TABLE UVIRTUAL.TBEP_MERITOS (
	CODNUM NUMBER(11,0) CONSTRAINT RBEP_NMER_CODNUM NOT NULL, 
	BEPITE_CODNUM NUMBER(11,0) CONSTRAINT RBEP_NMER_BEPITE_CODNUM NOT NULL, 
	BEPUSU_CODNUM NUMBER(11,0) CONSTRAINT RBEP_NMER_BEPUSU_CODNUM NOT NULL, 
    VALOR FLOAT(11) CONSTRAINT RBEP_NMER_VALOR NOT NULL, 
    DESCRIPCION VARCHAR2(200 CHAR) CONSTRAINT RBEP_NMER_DESCRIPCION NOT NULL, 
    OBSERVACION VARCHAR2(300 CHAR),
    ARCHIVO BLOB CONSTRAINT RBEP_NMER_ARCHIVO NOT NULL,
    CONSTRAINT IBEP_PMER PRIMARY KEY (CODNUM),
    CONSTRAINT IBEP_FITE_MER FOREIGN KEY (BEPITE_CODNUM) REFERENCES TBEP_ITEMSBAREMACION (CODNUM),
    CONSTRAINT IBEP_FUSU_MER FOREIGN KEY (BEPUSU_CODNUM) REFERENCES TBEP_USUARIOS (CODNUM)
);
--/////////////////////
COMMENT ON COLUMN TBEP_MERITOS.BEPITE_CODNUM IS 'fk al ítem de baremación';
--/////////////////////
COMMENT ON COLUMN TBEP_MERITOS.BEPUSU_CODNUM IS 'fk al usuario';
--/////////////////////
COMMENT ON COLUMN TBEP_MERITOS.VALOR IS 'valor del mérito';
--/////////////////////
COMMENT ON COLUMN TBEP_MERITOS.DESCRIPCION IS 'descripción del mérito';
--/////////////////////
COMMENT ON COLUMN TBEP_MERITOS.ARCHIVO IS 'archivo blob que se almacena en la bd';
--/////////////////////
COMMENT ON COLUMN TBEP_MERITOS.OBSERVACION IS 'observación para la comisión';
--/////////////////////
COMMENT ON TABLE TBEP_MERITOS IS 'Mérito. ALIAS: [bepmer] ACRONIMO: [MER]';
--/////////////////////
CREATE TABLE UVIRTUAL.TBEP_HTO_MERITOS (
 	CODCAMBIO NUMBER(11,0) CONSTRAINT RBEP_NMER_HTO_CODCAMBIO NOT NULL, 
 	LOG VARCHAR(50) CONSTRAINT RBEP_NMER_HTO_LOG NOT NULL, 
 	FECHALOG TIMESTAMP DEFAULT CURRENT_TIMESTAMP CONSTRAINT RBEP_NMER_HTO_FECHALOG NOT NULL, 
	CODNUM NUMBER(11,0) CONSTRAINT RBEP_NMER_HTO_CODNUM NOT NULL, 
   	BEPITE_CODNUM NUMBER(11,0) CONSTRAINT RBEP_NMER_HTO_BEPITE_CODNUM NOT NULL, 
   	BEPUSU_CODNUM NUMBER(11,0) CONSTRAINT RBEP_NMER_HTO_BEPUSU_CODNUM NOT NULL, 
    VALOR FLOAT(11) CONSTRAINT RBEP_NMER_HTO_VALOR NOT NULL, 
    DESCRIPCION VARCHAR2(200 BYTE) CONSTRAINT RBEP_NMER_HTO_DESCRIPCION NOT NULL, 
    OBSERVACION VARCHAR2(300 BYTE),
    ARCHIVO BLOB CONSTRAINT RBEP_NMER_HTO_ARCHIVO NOT NULL,
	CONSTRAINT IBEP_PMER_HISTORICO PRIMARY KEY (CODCAMBIO)
);
--/////////////////////
CREATE SEQUENCE QBEP_MER START WITH 1;
--/////////////////////
CREATE SEQUENCE QBEP_HTO_MER START WITH 1;
--/////////////////////
CREATE TRIGGER DBEP_MER_BRI
BEFORE INSERT
ON TBEP_MERITOS
FOR EACH ROW
DECLARE
BEGIN
    SELECT QBEP_MER.nextval into :new.CODNUM FROM dual;

    INSERT INTO TBEP_HTO_MERITOS (CODCAMBIO,LOG,CODNUM,BEPITE_CODNUM,BEPUSU_CODNUM,VALOR,DESCRIPCION,OBSERVACION,ARCHIVO)
    VALUES (QBEP_HTO_MER.NEXTVAL,'AFTER_INSERT',:New.CODNUM,:New.BEPITE_CODNUM,:New.BEPUSU_CODNUM,:New.VALOR,:New.DESCRIPCION,:New.OBSERVACION,:New.ARCHIVO);
END DBEP_MER_BRI;
--/////////////////////
CREATE TRIGGER DBEP_MER_BRU
BEFORE UPDATE
ON TBEP_MERITOS 
FOR EACH ROW
DECLARE
BEGIN
	INSERT INTO TBEP_HTO_MERITOS (CODCAMBIO,LOG,CODNUM,BEPITE_CODNUM,BEPUSU_CODNUM,VALOR,DESCRIPCION,OBSERVACION,ARCHIVO)
    VALUES (QBEP_HTO_MER.NEXTVAL,'BEFORE_UPDATE',:Old.CODNUM,:Old.BEPITE_CODNUM,:Old.BEPUSU_CODNUM,:Old.VALOR,:Old.DESCRIPCION,:Old.OBSERVACION,:Old.ARCHIVO);
      	  
    INSERT INTO TBEP_HTO_MERITOS (CODCAMBIO,LOG,CODNUM,BEPITE_CODNUM,BEPUSU_CODNUM,VALOR,DESCRIPCION,OBSERVACION,ARCHIVO)
    VALUES (QBEP_HTO_MER.NEXTVAL,'AFTER_UPDATE',:New.CODNUM,:New.BEPITE_CODNUM,:New.BEPUSU_CODNUM,:New.VALOR,:New.DESCRIPCION,:New.OBSERVACION,:New.ARCHIVO);
END DBEP_MER_BRU;
--/////////////////////
CREATE TRIGGER DBEP_MER_BRD
BEFORE DELETE
ON TBEP_MERITOS 
FOR EACH ROW
DECLARE
BEGIN
	INSERT INTO TBEP_HTO_MERITOS (CODCAMBIO,LOG,CODNUM,BEPITE_CODNUM,BEPUSU_CODNUM,VALOR,DESCRIPCION,OBSERVACION,ARCHIVO)
    VALUES (QBEP_HTO_MER.NEXTVAL,'BEFORE_DELETE',:Old.CODNUM,:Old.BEPITE_CODNUM,:Old.BEPUSU_CODNUM,:Old.VALOR,:Old.DESCRIPCION,:Old.OBSERVACION,:Old.ARCHIVO);
END DBEP_MER_BRD;