CREATE TABLE UVIRTUAL.TBEP_EVALUADORES (	
	BEPARE_CODNUM NUMBER(11,0) CONSTRAINT RBEP_NEVA_BEPARE_CODNUM NOT NULL,
	BEPUSU_CODNUM NUMBER(11,0) CONSTRAINT RBEP_NEVA_BEPUSU_CODNUM NOT NULL,
	FLGACTIVO CHAR(1) DEFAULT 'S',
	CONSTRAINT IBEP_FEVA_ARE FOREIGN KEY (BEPARE_CODNUM) REFERENCES TBEP_AREAS (CODNUM),
	CONSTRAINT IBEP_FEVA_USU FOREIGN KEY (BEPUSU_CODNUM) REFERENCES TBEP_USUARIOS (CODNUM)
);
--/////////////////////
COMMENT ON COLUMN TBEP_EVALUADORES.BEPARE_CODNUM IS 'Clave foránea a tabla área';
--/////////////////////
COMMENT ON COLUMN TBEP_EVALUADORES.BEPUSU_CODNUM IS 'Clave foránea a tabla usuarios';
--/////////////////////
COMMENT ON COLUMN TBEP_EVALUADORES.FLGACTIVO IS 'Indica si el evaluador está borrado o no';
--/////////////////////
COMMENT ON TABLE TBEP_EVALUADORES IS 'Tabla que relaciona los usuarios con rol de miembros de la comisión a un área. ALIAS: [bepeva] ACRONIMO: [EVA]';
--/////////////////////
CREATE TABLE UVIRTUAL.TBEP_HTO_EVALUADORES (
 	CODCAMBIO NUMBER(11,0) CONSTRAINT RBEP_NEVA_HTO_CODCAMBIO NOT NULL,
 	LOG VARCHAR(50) CONSTRAINT RBEP_NEVA_HTO_LOG NOT NULL,
 	FECHALOG TIMESTAMP DEFAULT CURRENT_TIMESTAMP CONSTRAINT RBEP_NEVA_HTO_FECHALOG NOT NULL,
	BEPARE_CODNUM NUMBER(11,0) CONSTRAINT RBEP_NEVA_HTO_BEPARE_CODNUM NOT NULL,
	BEPUSU_CODNUM NUMBER(11,0) CONSTRAINT RBEP_NEVA_HTO_BEPUSU_CODNUM NOT NULL,
	FLGACTIVO CHAR(1) DEFAULT 'S',
	CONSTRAINT IBEP_PEVA_HISTORICO PRIMARY KEY (CODCAMBIO)
);
--/////////////////////
CREATE SEQUENCE QBEP_HTO_EVA START WITH 1;
--/////////////////////
CREATE TRIGGER DBEP_EVA_BRI
BEFORE INSERT
ON TBEP_EVALUADORES
FOR EACH ROW
DECLARE
BEGIN
    INSERT INTO TBEP_HTO_EVALUADORES (CODCAMBIO,LOG,BEPARE_CODNUM,BEPUSU_CODNUM,FLGACTIVO)
    VALUES (QBEP_HTO_EVA.NEXTVAL,'AFTER_INSERT',:New.BEPARE_CODNUM,:New.BEPUSU_CODNUM,:New.FLGACTIVO);
END DBEP_EVA_BRI;
--/////////////////////
CREATE TRIGGER DBEP_EVA_BRU
BEFORE UPDATE
ON TBEP_EVALUADORES
FOR EACH ROW
DECLARE
BEGIN
	INSERT INTO TBEP_HTO_EVALUADORES (CODCAMBIO,LOG,BEPARE_CODNUM,BEPUSU_CODNUM,FLGACTIVO)
    VALUES (QBEP_HTO_EVA.NEXTVAL,'BEFORE_UPDATE',:Old.BEPARE_CODNUM,:Old.BEPUSU_CODNUM,:Old.FLGACTIVO);
    
 	INSERT INTO TBEP_HTO_EVALUADORES (CODCAMBIO,LOG,BEPARE_CODNUM,BEPUSU_CODNUM,FLGACTIVO)
    VALUES (QBEP_HTO_EVA.NEXTVAL,'AFTER_UPDATE',:New.BEPARE_CODNUM,:New.BEPUSU_CODNUM,:New.FLGACTIVO);
END DBEP_EVA_BRU;
--/////////////////////
CREATE TRIGGER DBEP_EVA_BRD
BEFORE DELETE
ON TBEP_EVALUADORES
FOR EACH ROW
DECLARE
BEGIN
	INSERT INTO TBEP_HTO_EVALUADORES (CODCAMBIO,LOG,BEPARE_CODNUM,BEPUSU_CODNUM,FLGACTIVO)
    VALUES (QBEP_HTO_EVA.NEXTVAL,'BEFORE_DELETE',:Old.BEPARE_CODNUM,:Old.BEPUSU_CODNUM,:Old.FLGACTIVO);
END DBEP_EVA_BRD;