CREATE TABLE UVIRTUAL.TBEP_SOLICITUDES (	
    CODNUM NUMBER(11,0) CONSTRAINT RBEP_NSOL_CODNUM NOT NULL,
    BEPCON_CODNUM NUMBER(11,0) CONSTRAINT RBEP_NSOL_BEPCON_CODNUM NOT NULL,
    ESTADO VARCHAR2(7 BYTE) DEFAULT 'ABIERTA',
    CONSTRAINT IBEP_FSOL_CON FOREIGN KEY (BEPCON_CODNUM) REFERENCES TBEP_CONVOCATORIAS (CODNUM),
    CONSTRAINT RBEP_CSOL_ESTADO CHECK(ESTADO IN ('ABIERTA','CERRADA')),
    CONSTRAINT IBEP_PSOL PRIMARY KEY (CODNUM)
);
--/////////////////////
COMMENT ON COLUMN TBEP_SOLICITUDES.BEPCON_CODNUM IS 'Llave externa a las convocatorias';
--/////////////////////
COMMENT ON COLUMN TBEP_SOLICITUDES.ESTADO IS 'Estado de la solicitud';
--/////////////////////
COMMENT ON TABLE TBEP_SOLICITUDES IS 'Convocatorias de bolsa de empleo. ALIAS: [bepsol] ACRONIMO: [SOL]';
--/////////////////////
CREATE TABLE UVIRTUAL.TBEP_HTO_SOLICITUDES (
 	CODCAMBIO NUMBER(11,0) NOT NULL,
 	LOG VARCHAR(50) NOT NULL,
 	FECHALOG TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    CODNUM NUMBER(11,0) CONSTRAINT RBEP_NSOL_HTO_CODNUM NOT NULL,
    BEPCON_CODNUM NUMBER(11,0) CONSTRAINT RBEP_NSOL_HTO_BEPCON_CODNUM NOT NULL,
    ESTADO VARCHAR2(7 BYTE) DEFAULT 'ABIERTA',
	CONSTRAINT IBEP_PSOL_HISTORICO PRIMARY KEY (CODCAMBIO)
);
--/////////////////////
CREATE SEQUENCE QBEP_SOL START WITH 1;
--/////////////////////
CREATE SEQUENCE QBEP_HTO_SOL START WITH 1;
--/////////////////////
CREATE TRIGGER DBEP_SOL_BRI
BEFORE INSERT
ON TBEP_SOLICITUDES
FOR EACH ROW
DECLARE
BEGIN
    SELECT QBEP_SOL.nextval into :new.CODNUM FROM dual;

    INSERT INTO TBEP_HTO_SOLICITUDES (CODCAMBIO,LOG,CODNUM,BEPCON_CODNUM,ESTADO)
    VALUES (QBEP_HTO_SOL.NEXTVAL,'AFTER_INSERT',:New.CODNUM,:New.BEPCON_CODNUM,:New.ESTADO);
END DBEP_SOL_BRI;
--/////////////////////
CREATE TRIGGER DBEP_SOL_BRU
BEFORE UPDATE
ON TBEP_SOLICITUDES
FOR EACH ROW
DECLARE
BEGIN
	INSERT INTO TBEP_HTO_SOLICITUDES (CODCAMBIO,LOG,CODNUM,BEPCON_CODNUM,ESTADO)
    VALUES (QBEP_HTO_SOL.NEXTVAL,'BEFORE_UPDATE',:Old.CODNUM,:Old.BEPCON_CODNUM,:Old.ESTADO);
    
 	INSERT INTO TBEP_HTO_SOLICITUDES (CODCAMBIO,LOG,CODNUM,BEPCON_CODNUM,ESTADO)
    VALUES (QBEP_HTO_SOL.NEXTVAL,'AFTER_UPDATE',:New.CODNUM,:New.BEPCON_CODNUM,:New.ESTADO);
END DBEP_SOL_BRU;
--/////////////////////
CREATE TRIGGER DBEP_SOL_BRD
BEFORE DELETE
ON TBEP_SOLICITUDES
FOR EACH ROW
DECLARE
BEGIN
	INSERT INTO TBEP_HTO_SOLICITUDES (CODCAMBIO,LOG,CODNUM,BEPCON_CODNUM,ESTADO)
    VALUES (QBEP_HTO_SOL.NEXTVAL,'BEFORE_DELETE',:Old.CODNUM,:Old.BEPCON_CODNUM,:Old.ESTADO);
END DBEP_SOL_BRD;