CREATE TABLE UVIRTUAL.TBEP_CONVOCATORIAS (	
    CODNUM NUMBER(11,0) CONSTRAINT RBEP_NCON_CODNUM NOT NULL,
    DESCRIPCION VARCHAR2(150 CHAR) CONSTRAINT RBEP_NCON_DESCRIPCION NOT NULL,
    FECHACIERRE TIMESTAMP,
    ESTADO VARCHAR2(7 BYTE) DEFAULT 'ABIERTA',
    NUMBOLSASMAXIMO NUMBER(11,0) CONSTRAINT RBEP_NCON_NUMBOLSASMAXIMO NOT NULL,
    NUMMERITOSPORBLOQUE NUMBER(11,0) CONSTRAINT RBEP_NCON_NUMMERITOSPORBLOQUE NOT NULL,
    CONSTRAINT RBEP_CCON_ESTADO CHECK(ESTADO IN ('ABIERTA','CERRADA')),
    CONSTRAINT IBEP_PCON PRIMARY KEY (CODNUM)
);
--/////////////////////
COMMENT ON COLUMN TBEP_CONVOCATORIAS.DESCRIPCION IS 'Descripción de la convocatoria';
--/////////////////////
COMMENT ON COLUMN TBEP_CONVOCATORIAS.FECHACIERRE IS 'Fecha de cierre de la convocatoria';
--/////////////////////
COMMENT ON COLUMN TBEP_CONVOCATORIAS.ESTADO IS 'Estado de la convocatoria';
--/////////////////////
COMMENT ON COLUMN TBEP_CONVOCATORIAS.NUMBOLSASMAXIMO IS 'Número máximo de bolsas donde se puede apuntar el candidato';
--/////////////////////
COMMENT ON COLUMN TBEP_CONVOCATORIAS.NUMMERITOSPORBLOQUE IS 'Número máximo de meritos por bloque que puede añadir el candidato';
--/////////////////////
COMMENT ON TABLE TBEP_CONVOCATORIAS IS 'Convocatorias de bolsa de empleo. ALIAS: [bepcon] ACRONIMO: [CON]';
--/////////////////////
CREATE TABLE UVIRTUAL.TBEP_HTO_CONVOCATORIAS (
 	CODCAMBIO NUMBER(11,0) CONSTRAINT RBEP_NCON_HTO_CODCAMBIO NOT NULL,
 	LOG VARCHAR(50) CONSTRAINT RBEP_NCON_HTO_LOG NOT NULL,
 	FECHALOG TIMESTAMP DEFAULT CURRENT_TIMESTAMP CONSTRAINT RBEP_NCON_HTO_FECHALOG NOT NULL,
	CODNUM NUMBER(11,0) CONSTRAINT RBEP_NCON_HTO_CODNUM NOT NULL,
    DESCRIPCION CHAR(150) CONSTRAINT RBEP_NCON_HTO_DESCRIPCION NOT NULL,
    FECHACIERRE TIMESTAMP,
    ESTADO VARCHAR2(7 BYTE) DEFAULT 'ABIERTA',
    NUMBOLSASMAXIMO NUMBER(11,0) CONSTRAINT RBEP_NCON_HTO_NUMBOLSASMAXIMO NOT NULL,
    NUMMERITOSPORBLOQUE NUMBER(11,0) CONSTRAINT RBEP_NCON_HTO_NUMMERITOSPORBLOQUE NOT NULL,
	CONSTRAINT IBEP_PCON_HISTORICO PRIMARY KEY (CODCAMBIO)
);
--/////////////////////
CREATE SEQUENCE QBEP_CON START WITH 1;
--/////////////////////
CREATE SEQUENCE QBEP_HTO_CON START WITH 1;
--/////////////////////
CREATE TRIGGER DBEP_CON_BRI
BEFORE INSERT
ON TBEP_CONVOCATORIAS
FOR EACH ROW
DECLARE
BEGIN
    SELECT QBEP_CON.nextval into :new.CODNUM FROM dual;

    INSERT INTO TBEP_HTO_CONVOCATORIAS (CODCAMBIO,LOG,CODNUM,DESCRIPCION,FECHACIERRE,ESTADO,NUMBOLSASMAXIMO,NUMMERITOSPORBLOQUE)
    VALUES (QBEP_HTO_CON.NEXTVAL,'AFTER_INSERT',:New.CODNUM,:New.DESCRIPCION,:New.FECHACIERRE,:New.ESTADO,:New.NUMBOLSASMAXIMO,:New.NUMMERITOSPORBLOQUE);
END DBEP_CON_BRI;
--/////////////////////
CREATE TRIGGER DBEP_CON_BRU
BEFORE UPDATE
ON TBEP_CONVOCATORIAS
FOR EACH ROW
DECLARE
BEGIN
	INSERT INTO TBEP_HTO_CONVOCATORIAS (CODCAMBIO,LOG,CODNUM,DESCRIPCION,FECHACIERRE,ESTADO,NUMBOLSASMAXIMO,NUMMERITOSPORBLOQUE)
    VALUES (QBEP_HTO_CON.NEXTVAL,'BEFORE_UPDATE',:Old.CODNUM,:Old.DESCRIPCION,:Old.FECHACIERRE,:Old.ESTADO,:Old.NUMBOLSASMAXIMO,:Old.NUMMERITOSPORBLOQUE);
    
 	INSERT INTO TBEP_HTO_CONVOCATORIAS (CODCAMBIO,LOG,CODNUM,DESCRIPCION,FECHACIERRE,ESTADO,NUMBOLSASMAXIMO,NUMMERITOSPORBLOQUE)
    VALUES (QBEP_HTO_CON.NEXTVAL,'AFTER_UPDATE',:New.CODNUM,:New.DESCRIPCION,:New.FECHACIERRE,:New.ESTADO,:New.NUMBOLSASMAXIMO,:New.NUMMERITOSPORBLOQUE);
END DBEP_CON_BRU;
--/////////////////////
CREATE TRIGGER DBEP_CON_BRD
BEFORE DELETE
ON TBEP_CONVOCATORIAS
FOR EACH ROW
DECLARE
BEGIN
	INSERT INTO TBEP_HTO_CONVOCATORIAS (CODCAMBIO,LOG,CODNUM,DESCRIPCION,FECHACIERRE,ESTADO,NUMBOLSASMAXIMO,NUMMERITOSPORBLOQUE)
    VALUES (QBEP_HTO_CON.NEXTVAL,'BEFORE_DELETE',:Old.CODNUM,:Old.DESCRIPCION,:Old.FECHACIERRE,:Old.ESTADO,:Old.NUMBOLSASMAXIMO,:Old.NUMMERITOSPORBLOQUE);
END DBEP_CON_BRD;