CREATE TABLE UVIRTUAL.TBEP_USUARIOS_EXCLUIDOS_AREA (	
	CODNUM NUMBER(11,0) CONSTRAINT RBEP_NUSU_EXC_ARE_CODNUM NOT NULL,
	USUARIO NUMBER(11,0) CONSTRAINT RBEP_NUSU_EXC_ARE_USUARIO NOT NULL,
	AREA NUMBER(11,0) CONSTRAINT RBEP_NUSU_EXC_ARE_AREA NOT NULL,
    CONSTRAINT IBEP_PUSU_EXC_ARE PRIMARY KEY (CODNUM),
    CONSTRAINT IBEP_FUSU_EXC_ARE_USUARIO FOREIGN KEY (USUARIO) REFERENCES UVIRTUAL.TBEP_USUARIOS (CODNUM),
    CONSTRAINT IBEP_FUSU_EXC_ARE_AREA FOREIGN KEY (AREA) REFERENCES UVIRTUAL.TBEP_AREAS (CODNUM)
);
--/////////////////////
CREATE TABLE UVIRTUAL.TBEP_HTO_USUARIOS_EXCLUIDOS_AREA (
 	CODCAMBIO NUMBER(11,0) CONSTRAINT RBEP_NUSU_EXC_ARE_HTO_CODCAMBIO NOT NULL,
 	LOG VARCHAR(50) CONSTRAINT RBEP_NUSU_EXC_ARE_HTO_LOG NOT NULL,
 	FECHALOG TIMESTAMP DEFAULT CURRENT_TIMESTAMP CONSTRAINT RBEP_NUSU_EXC_ARE_HTO_FECHALOG NOT NULL,
	CODNUM NUMBER(11,0) CONSTRAINT RBEP_NUSU_EXC_ARE_HTO_CODNUM NOT NULL,
	USUARIO NUMBER(11,0) CONSTRAINT RBEP_NUSU_EXC_ARE_HTO_USUARIO NOT NULL,
	AREA NUMBER(11,0) CONSTRAINT RBEP_NUSU_EXC_ARE_HTO_AREA NOT NULL,
	CONSTRAINT IBEP_PUSU_EXC_ARE_HISTORICO PRIMARY KEY (CODCAMBIO)
);
--/////////////////////
CREATE SEQUENCE QBEP_USU_EXC_ARE START WITH 1;
--/////////////////////
CREATE SEQUENCE QBEP_HTO_USU_EXE_ARE START WITH 1;