CREATE TABLE UVIRTUAL.TBEP_USUARIOS_EXCLUIDOS_AREA (	
	CODNUM NUMBER(11,0) CONSTRAINT RBEP_NUSU_EXC_ARE_CODNUM NOT NULL,
	USUARIO NUMBER(11,0) CONSTRAINT RBEP_NUSU_EXC_ARE_USUARIO NOT NULL,
	AREA NUMBER(11,0) CONSTRAINT RBEP_NUSU_EXC_ARE_AREA NOT NULL,
    CONSTRAINT IBEP_PUSU_EXC_ARE PRIMARY KEY (CODNUM),
    CONSTRAINT IBEP_FUSU_EXC_ARE_USUARIO FOREIGN KEY (USUARIO) REFERENCES UVIRTUAL.TBEP_USUARIOS (CODNUM),
    CONSTRAINT IBEP_FUSU_EXC_ARE_AREA FOREIGN KEY (AREA) REFERENCES UVIRTUAL.TBEP_AREAS (CODNUM)
);
--/////////////////////
COMMENT ON COLUMN TBEP_USUARIOS_EXCLUIDOS_AREA.USUARIO IS 'Llave externa a los usuarios';
--/////////////////////
COMMENT ON COLUMN TBEP_USUARIOS_EXCLUIDOS_AREA.AREA IS 'Llave externa a las areas';
--/////////////////////
COMMENT ON TABLE TBEP_USUARIOS_EXCLUIDOS_AREA IS 'Usuarios excluidos de area. ALIAS: [bepusuexcare] ACRONIMO: [USUEXCARE]';
--/////////////////////
CREATE TABLE UVIRTUAL.TBEP_HTO_USUARIOS_EXCLUIDOS_AREA (
 	CODCAMBIO NUMBER(11,0) CONSTRAINT RBEP_NUSU_EXC_ARE_HTO_CODCAMBIO NOT NULL,
 	LOG VARCHAR(50) CONSTRAINT RBEP_NUSU_EXC_ARE_HTO_LOG NOT NULL,
 	FECHALOG TIMESTAMP DEFAULT CURRENT_TIMESTAMP CONSTRAINT RBEP_NUSU_EXC_ARE_HTO_FECHALOG NOT NULL,
	CODNUM NUMBER(11,0) CONSTRAINT RBEP_NUSU_EXC_ARE_HTO_CODNUM NOT NULL,
	USUARIO NUMBER(11,0) CONSTRAINT RBEP_NUSU_EXC_ARE_HTO_USUARIO NOT NULL,
	AREA NUMBER(11,0) CONSTRAINT RBEP_NUSU_EXC_ARE_HTO_AREA NOT NULL,
	CONSTRAINT IBEP_PUSU_EXC_ARE_HISTORICO PRIMARY KEY (CODCAMBIO)
);
--/////////////////////
CREATE SEQUENCE QBEP_USU_EXC_ARE START WITH 1;
--/////////////////////
CREATE SEQUENCE QBEP_USU_EXE_ARE_HTO START WITH 1;
--/////////////////////
CREATE TRIGGER DBEP_USU_EXC_ARE_BRI
BEFORE INSERT
ON TBEP_USUARIOS_EXCLUIDOS_AREA
FOR EACH ROW
DECLARE
BEGIN
    SELECT QBEP_USU_EXC_ARE.nextval into :new.CODNUM FROM dual;

    INSERT INTO TBEP_HTO_USUARIOS_EXCLUIDOS_AREA (CODCAMBIO,LOG,CODNUM,USUARIO,AREA)
    VALUES (QBEP_USU_EXE_ARE_HTO.NEXTVAL,'AFTER_INSERT',:New.CODNUM,:New.USUARIO,:New.AREA);
END DBEP_CON_BRI;
--/////////////////////
CREATE TRIGGER DBEP_USU_EXC_ARE_BRU
BEFORE UPDATE
ON TBEP_USUARIOS_EXCLUIDOS_AREA
FOR EACH ROW
DECLARE
BEGIN
	INSERT INTO TBEP_HTO_USUARIOS_EXCLUIDOS_AREA (CODCAMBIO,LOG,CODNUM,USUARIO,AREA)
    VALUES (QBEP_USU_EXE_ARE_HTO.NEXTVAL,'BEFORE_UPDATE',:Old.CODNUM,:Old.USUARIO,:Old.AREA);
    
 	INSERT INTO TBEP_HTO_CONVOCATORIAS (CODCAMBIO,LOG,CODNUM,USUARIO,AREA)
    VALUES (QBEP_USU_EXE_ARE_HTO.NEXTVAL,'AFTER_UPDATE',:New.CODNUM,:New.USUARIO,:New.AREA);
END DBEP_USU_EXC_ARE_BRU;
--/////////////////////
CREATE TRIGGER DBEP_USU_EXC_ARE_BRD
BEFORE DELETE
ON TBEP_USUARIOS_EXCLUIDOS_AREA
FOR EACH ROW
DECLARE
BEGIN
	INSERT INTO TBEP_HTO_USUARIOS_EXCLUIDOS_AREA (CODCAMBIO,LOG,CODNUM,USUARIO,AREA)
    VALUES (QBEP_USU_EXE_ARE_HTO.NEXTVAL,'BEFORE_DELETE',:Old.CODNUM,:Old.USUARIO,:Old.AREA);
END DBEP_USU_EXC_ARE_BRD;