CREATE TABLE UVIRTUAL.TBEP_SOLICITUDES (	
    CODNUM NUMBER(11,0) CONSTRAINT RBEP_NSOL_CODNUM NOT NULL,
    BEPUSU_CODNUM NUMBER(11,0) CONSTRAINT RBEP_NSOL_BEPUSU_CODNUM NOT NULL,
    BEPCON_CODNUM NUMBER(11,0) CONSTRAINT RBEP_NSOL_BEPCON_CODNUM NOT NULL,
    ESTADO VARCHAR2(7 BYTE) DEFAULT 'ABIERTA',
    FECHACONFIRMACION TIMESTAMP NULL,
    ARCHIVO BLOB NULL,
    CONSTRAINT IBEP_FSOL_USU FOREIGN KEY (BEPUSU_CODNUM) REFERENCES TBEP_USUARIOS (CODNUM),
    CONSTRAINT IBEP_FSOL_CON FOREIGN KEY (BEPCON_CODNUM) REFERENCES TBEP_CONVOCATORIAS (CODNUM),
    CONSTRAINT RBEP_CSOL_ESTADO CHECK(ESTADO IN ('ABIERTA','CERRADA')),
    CONSTRAINT IBEP_PSOL PRIMARY KEY (CODNUM)
);
--/////////////////////
COMMENT ON COLUMN TBEP_SOLICITUDES.BEPUSU_CODNUM IS 'Llave externa a los usuarios';
--/////////////////////
COMMENT ON COLUMN TBEP_SOLICITUDES.BEPCON_CODNUM IS 'Llave externa a las convocatorias';
--/////////////////////
COMMENT ON COLUMN TBEP_SOLICITUDES.ESTADO IS 'Estado de la solicitud';
--/////////////////////
COMMENT ON COLUMN TBEP_SOLICITUDES.FECHACONFIRMACION IS 'Fecha en la que se confirma y se cierra la solicitud';
--/////////////////////
COMMENT ON COLUMN TBEP_SOLICITUDES.ARCHIVO IS 'archivo blob que almacena un pdf con el resumen de la solicitud en la bd';
--/////////////////////
COMMENT ON TABLE TBEP_SOLICITUDES IS 'Convocatorias de bolsa de empleo. ALIAS: [bepsol] ACRONIMO: [SOL]';
--/////////////////////
CREATE TABLE UVIRTUAL.TBEP_HTO_SOLICITUDES (
 	CODCAMBIO NUMBER(11,0) CONSTRAINT RBEP_NSOL_HTO_CODCAMBIO NOT NULL,
 	LOG VARCHAR(50) CONSTRAINT RBEP_NSOL_HTO_LOG NOT NULL,
 	FECHALOG TIMESTAMP DEFAULT CURRENT_TIMESTAMP CONSTRAINT RBEP_NSOL_HTO_FECHALOG NOT NULL,
    CODNUM NUMBER(11,0) CONSTRAINT RBEP_NSOL_HTO_CODNUM NOT NULL,
    BEPUSU_CODNUM NUMBER(11,0) CONSTRAINT RBEP_NSOL_HTO_BEPUSU_CODNUM NOT NULL,
    BEPCON_CODNUM NUMBER(11,0) CONSTRAINT RBEP_NSOL_HTO_BEPCON_CODNUM NOT NULL,
    ESTADO VARCHAR2(7 BYTE) DEFAULT 'ABIERTA',
    FECHACONFIRMACION TIMESTAMP NULL,
    ARCHIVO BLOB NULL,
	CONSTRAINT IBEP_PSOL_HISTORICO PRIMARY KEY (CODCAMBIO)
);
--/////////////////////
CREATE SEQUENCE QBEP_SOL START WITH 1;
--/////////////////////
CREATE SEQUENCE QBEP_HTO_SOL START WITH 1;
--/////////////////////
CREATE TRIGGER DBEP_SOL_BRI
BEFORE INSERT
ON TBEP_SOLICITUDES
FOR EACH ROW
DECLARE
BEGIN
    SELECT QBEP_SOL.nextval into :new.CODNUM FROM dual;

    INSERT INTO TBEP_HTO_SOLICITUDES (CODCAMBIO,LOG,CODNUM,BEPUSU_CODNUM,BEPCON_CODNUM,ESTADO,FECHACONFIRMACION,ARCHIVO)
    VALUES (QBEP_HTO_SOL.NEXTVAL,'AFTER_INSERT',:New.CODNUM,:New.BEPUSU_CODNUM,:New.BEPCON_CODNUM,:New.ESTADO,:New.FECHACONFIRMACION,:New.ARCHIVO);
END DBEP_SOL_BRI;
--/////////////////////
CREATE TRIGGER DBEP_SOL_BRU
BEFORE UPDATE
ON TBEP_SOLICITUDES
FOR EACH ROW
DECLARE
BEGIN
	INSERT INTO TBEP_HTO_SOLICITUDES (CODCAMBIO,LOG,CODNUM,BEPUSU_CODNUM,BEPCON_CODNUM,ESTADO,FECHACONFIRMACION,ARCHIVO)
    VALUES (QBEP_HTO_SOL.NEXTVAL,'BEFORE_UPDATE',:Old.CODNUM,:Old.BEPUSU_CODNUM,:Old.BEPCON_CODNUM,:Old.ESTADO,:Old.FECHACONFIRMACION,:Old.ARCHIVO);
    
 	INSERT INTO TBEP_HTO_SOLICITUDES (CODCAMBIO,LOG,CODNUM,BEPUSU_CODNUM,BEPCON_CODNUM,ESTADO,FECHACONFIRMACION,ARCHIVO)
    VALUES (QBEP_HTO_SOL.NEXTVAL,'AFTER_UPDATE',:New.CODNUM,:New.BEPUSU_CODNUM,:New.BEPCON_CODNUM,:New.ESTADO,:New.FECHACONFIRMACION,:New.ARCHIVO);
END DBEP_SOL_BRU;
--/////////////////////
CREATE TRIGGER DBEP_SOL_BRD
BEFORE DELETE
ON TBEP_SOLICITUDES
FOR EACH ROW
DECLARE
BEGIN
	INSERT INTO TBEP_HTO_SOLICITUDES (CODCAMBIO,LOG,CODNUM,BEPUSU_CODNUM,BEPCON_CODNUM,ESTADO,FECHACONFIRMACION,ARCHIVO)
    VALUES (QBEP_HTO_SOL.NEXTVAL,'BEFORE_DELETE',:Old.CODNUM,:Old.BEPUSU_CODNUM,:Old.BEPCON_CODNUM,:Old.ESTADO,:Old.FECHACONFIRMACION,:Old.ARCHIVO);
END DBEP_SOL_BRD;