CREATE TABLE UVIRTUAL.TBEP_SOLICITUDBOLSAS (	
	BEPBOL_CODNUM NUMBER(11,0) NOT NULL,
	BEPSOL_CODNUM NUMBER(11,0) NOT NULL,
	CONSTRAINT IBEP_FSOBO_BOL FOREIGN KEY (BEPBOL_CODNUM) REFERENCES TBEP_BOLSAS (CODNUM),
	CONSTRAINT IBEP_FSOBO_SOL FOREIGN KEY (BEPSOL_CODNUM) REFERENCES TBEP_SOLICITUDES (CODNUM),
	CONSTRAINT IBEP_PSOBO PRIMARY KEY (BEPBOL_CODNUM, BEPSOL_CODNUM)
);
--/////////////////////
COMMENT ON COLUMN TBEP_SOLICITUDBOLSAS.BEPBOL_CODNUM IS 'Clave foránea a tabla bolsas';
--/////////////////////
COMMENT ON COLUMN TBEP_SOLICITUDBOLSAS.BEPSOL_CODNUM IS 'Clave foránea a tabla solicitudes';
--/////////////////////
COMMENT ON TABLE TBEP_SOLICITUDBOLSAS IS 'Tabla que relaciona las bolsas con las solicitudes. ALIAS: [bepsobo] ACRONIMO: [SOBO]';
--/////////////////////
CREATE TABLE UVIRTUAL.TBEP_HTO_SOLICITUDBOLSAS (
 	CODCAMBIO NUMBER(11,0) NOT NULL,
 	LOG VARCHAR(50) NOT NULL,
 	FECHALOG TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
	BEPBOL_CODNUM NUMBER(11,0) NOT NULL,
	BEPSOL_CODNUM NUMBER(11,0) NOT NULL,
	CONSTRAINT IBEP_PSOBO_HISTORICO PRIMARY KEY (CODCAMBIO)
);
--/////////////////////
CREATE SEQUENCE QBEP_SOBO START WITH 1;
--/////////////////////
CREATE SEQUENCE QBEP_HTO_SOBO START WITH 1;
--/////////////////////
CREATE TRIGGER DBEP_SOBO_BRI
BEFORE INSERT
ON TBEP_SOLICITUDBOLSAS
FOR EACH ROW
DECLARE
BEGIN
    INSERT INTO TBEP_HTO_SOLICITUDBOLSAS (CODCAMBIO,LOG,BEPBOL_CODNUM,BEPSOL_CODNUM)
    VALUES (QBEP_HTO_SOBO.NEXTVAL,'AFTER_INSERT',:New.BEPBOL_CODNUM,:New.BEPSOL_CODNUM);
END DBEP_SOBO_BRI;
--/////////////////////
CREATE TRIGGER DBEP_SOBO_BRU
BEFORE UPDATE
ON TBEP_SOLICITUDBOLSAS
FOR EACH ROW
DECLARE
BEGIN
	INSERT INTO TBEP_HTO_SOLICITUDBOLSAS (CODCAMBIO,LOG,BEPBOL_CODNUM,BEPSOL_CODNUM)
    VALUES (QBEP_HTO_SOBO.NEXTVAL,'BEFORE_UPDATE',:Old.BEPBOL_CODNUM,:Old.BEPSOL_CODNUM);
    
 	INSERT INTO TBEP_HTO_SOLICITUDBOLSAS (CODCAMBIO,LOG,BEPBOL_CODNUM,BEPSOL_CODNUM)
    VALUES (QBEP_HTO_SOBO.NEXTVAL,'AFTER_UPDATE',:New.BEPBOL_CODNUM,:New.BEPSOL_CODNUM);
END DBEP_SOBO_BRU;
--/////////////////////
CREATE TRIGGER DBEP_SOBO_BRD
BEFORE DELETE
ON TBEP_SOLICITUDBOLSAS
FOR EACH ROW
DECLARE
BEGIN
	INSERT INTO TBEP_HTO_SOLICITUDBOLSAS (CODCAMBIO,LOG,BEPBOL_CODNUM,BEPSOL_CODNUM)
    VALUES (QBEP_HTO_SOBO.NEXTVAL,'BEFORE_DELETE',:Old.BEPBOL_CODNUM,:Old.BEPSOL_CODNUM);
END DBEP_SOBO_BRD;