CREATE TABLE UVIRTUAL.TBEP_TITULACIONES_USUARIO (
	CODNUM NUMBER(11,0) CONSTRAINT RBEP_NTIT_USU_CODNUM NOT NULL,
	BEPTIT_USU_TIT_CODNUM NUMBER(11,0) NOT NULL,
	BEPTIT_USU_USU_CODNUM NUMBER(11,0) NOT NULL,
	DESCRIPCION VARCHAR2(250 CHAR) DEFAULT NULL,
	ARCHIVO BLOB CONSTRAINT RBEP_NTIT_USU_ARCHIVO NOT NULL,
	FLGBORRADO CHAR(1) DEFAULT 'N',
    FECHA_BORRADO TIMESTAMP NULL,
	CONSTRAINT IBEP_PTIT_USU PRIMARY KEY (CODNUM),
	CONSTRAINT IBEP_FTIT_USU_TIT FOREIGN KEY (BEPTIT_USU_TIT_CODNUM) REFERENCES TBEP_TITULACIONES (CODNUM),
	CONSTRAINT IBEP_FTIT_USU_USU FOREIGN KEY (BEPTIT_USU_USU_CODNUM) REFERENCES TBEP_USUARIOS (CODNUM),
	CONSTRAINT RBEP_CTIT_USU_FLGBORRADO CHECK(FLGBORRADO IN ('N','S'))
);
--/////////////////////
COMMENT ON COLUMN TBEP_TITULACIONES_USUARIO.BEPTIT_USU_TIT_CODNUM IS 'Clave foránea a tabla titulaciones';
--/////////////////////
COMMENT ON COLUMN TBEP_TITULACIONES_USUARIO.BEPTIT_USU_USU_CODNUM IS 'Clave foránea a tabla usuarios';
--/////////////////////
COMMENT ON TABLE TBEP_TITULACIONES_USUARIO IS 'Tabla que relaciona las titulaciones con los usuarios. ALIAS: [beptitusu] ACRONIMO: [TITUSU]';
--/////////////////////
CREATE TABLE UVIRTUAL.TBEP_HTO_TITULACIONES_USUARIO (
 	CODCAMBIO NUMBER(11,0) NOT NULL,
 	LOG VARCHAR(50) NOT NULL,
 	FECHALOG TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
	BEPTIT_USU_TIT_CODNUM NUMBER(11,0) NOT NULL,
	BEPTIT_USU_USU_CODNUM NUMBER(11,0) NOT NULL,
	DESCRIPCION VARCHAR2(250 CHAR) DEFAULT NULL,
	ARCHIVO BLOB CONSTRAINT RBEP_NTIT_USU_HTO_ARCHIVO NOT NULL,
	FLGBORRADO CHAR(1) DEFAULT 'N',
    FECHA_BORRADO TIMESTAMP NULL,
	CONSTRAINT IBEP_PTIT_USU_HISTORICO PRIMARY KEY (CODCAMBIO)
);
--/////////////////////
CREATE SEQUENCE QBEP_TIT_USU START WITH 1;
--/////////////////////
CREATE SEQUENCE QBEP_HTO_TIT_USU START WITH 1;
--/////////////////////
CREATE TRIGGER DBEP_TIT_USU_BRI
BEFORE INSERT
ON TBEP_TITULACIONES_USUARIO
FOR EACH ROW
DECLARE
BEGIN
	SELECT QBEP_TIT_USU.nextval into :new.CODNUM FROM dual;	 	
	
    INSERT INTO TBEP_HTO_TITULACIONES_USUARIO (CODCAMBIO,LOG,BEPTIT_USU_TIT_CODNUM,BEPTIT_USU_USU_CODNUM,DESCRIPCION,ARCHIVO,FLGBORRADO,FECHA_BORRADO)
    VALUES (QBEP_HTO_TIT_USU.NEXTVAL,'AFTER_INSERT',:New.BEPTIT_USU_TIT_CODNUM,:New.BEPTIT_USU_USU_CODNUM,:New.DESCRIPCION,:New.ARCHIVO,:New.FLGBORRADO,:New.FECHA_BORRADO);
END DBEP_TIT_USU_BRI;
--/////////////////////
CREATE TRIGGER DBEP_TIT_USU_BRU
BEFORE UPDATE
ON TBEP_TITULACIONES_USUARIO
FOR EACH ROW
DECLARE
BEGIN
	INSERT INTO TBEP_HTO_TITULACIONES_USUARIO (CODCAMBIO,LOG,BEPTIT_USU_TIT_CODNUM,BEPTIT_USU_USU_CODNUM,DESCRIPCION,ARCHIVO,FLGBORRADO,FECHA_BORRADO)
    VALUES (QBEP_HTO_TIT_USU.NEXTVAL,'BEFORE_UPDATE',:Old.BEPTIT_USU_TIT_CODNUM,:Old.BEPTIT_USU_USU_CODNUM,:Old.DESCRIPCION,:Old.ARCHIVO,:Old.FLGBORRADO,:Old.FECHA_BORRADO);
    
 	INSERT INTO TBEP_HTO_TITULACIONES_USUARIO (CODCAMBIO,LOG,BEPTIT_USU_TIT_CODNUM,BEPTIT_USU_USU_CODNUM,DESCRIPCION,ARCHIVO,FLGBORRADO,FECHA_BORRADO)
    VALUES (QBEP_HTO_TIT_USU.NEXTVAL,'AFTER_UPDATE',:New.BEPTIT_USU_TIT_CODNUM,:New.BEPTIT_USU_USU_CODNUM,:New.DESCRIPCION,:New.ARCHIVO,:New.FLGBORRADO,:New.FECHA_BORRADO);
END DBEP_TIT_USU_BRU;
--/////////////////////
CREATE TRIGGER DBEP_TIT_USU_BRD
BEFORE DELETE
ON TBEP_TITULACIONES_USUARIO
FOR EACH ROW
DECLARE
BEGIN
	INSERT INTO TBEP_HTO_TITULACIONES_USUARIO (CODCAMBIO,LOG,BEPTIT_USU_TIT_CODNUM,BEPTIT_USU_USU_CODNUM,DESCRIPCION,ARCHIVO,FLGBORRADO,FECHA_BORRADO)
    VALUES (QBEP_HTO_TIT_USU.NEXTVAL,'BEFORE_DELETE',:Old.BEPTIT_USU_TIT_CODNUM,:Old.BEPTIT_USU_USU_CODNUM,:Old.DESCRIPCION,:Old.ARCHIVO,:Old.FLGBORRADO,:Old.FECHA_BORRADO);
END DBEP_TIT_USU_BRD;