CREATE TABLE UVIRTUAL.TBEP_MERITOSPREFERENTES (	
	CODNUM NUMBER(11,0) CONSTRAINT RBEP_NMEP_CODNUM NOT NULL,
    DESCRIPCION VARCHAR2(1000 CHAR) CONSTRAINT RBEP_NMEP_DESCRIPCION NOT NULL, 
    TIPO VARCHAR2(15 CHAR) DEFAULT 'TITULACION',
    APLICABLE VARCHAR2(10 CHAR) DEFAULT 'BLOQUE',
    FACTOR VARCHAR2(20 CHAR) CONSTRAINT RBEP_NMEP_FACTOR NOT NULL,
    VALOR_MAXIMO NUMBER(6, 2) DEFAULT NULL,
    BEPTIT_TIPO_CODNUM NUMBER(11,0) NULL,
    BEPITE_TIPO_CODNUM NUMBER(11,0) NULL,
    BEPBLO_APLICABLE_CODNUM NUMBER(11,0) NULL,
    BEPAPA_APLICABLE_CODNUM NUMBER(11,0) NULL,
    BEPITE_APLICABLE_CODNUM NUMBER(11,0) NULL,
    CONSTRAINT RBEP_CMEP_TIPO CHECK (TIPO IN ('TITULACION','MERITO')),
    CONSTRAINT RBEP_CMEP_APLICABLE CHECK (APLICABLE IN ('BLOQUE','APARTADO','ITEM')),
    CONSTRAINT IBEP_FMEP_TIPO_TIT FOREIGN KEY (BEPTIT_TIPO_CODNUM) REFERENCES TBEP_TITULACIONES (CODNUM),
    CONSTRAINT IBEP_FMEP_TIPO_ITE FOREIGN KEY (BEPITE_TIPO_CODNUM) REFERENCES TBEP_ITEMSBAREMACION (CODNUM),
    CONSTRAINT IBEP_FMEP_APLICABLE_BLO FOREIGN KEY (BEPBLO_APLICABLE_CODNUM) REFERENCES TBEP_BLOQUESBAREMACION (CODNUM),
    CONSTRAINT IBEP_FMEP_APLICABLE_APA FOREIGN KEY (BEPAPA_APLICABLE_CODNUM) REFERENCES TBEP_APARTADOSBAREMACION (CODNUM),
    CONSTRAINT IBEP_FMEP_APLICABLE_ITE FOREIGN KEY (BEPITE_APLICABLE_CODNUM) REFERENCES TBEP_ITEMSBAREMACION (CODNUM),
	CONSTRAINT IBEP_PMEP PRIMARY KEY (CODNUM)
);
--/////////////////////
COMMENT ON COLUMN TBEP_MERITOSPREFERENTES.DESCRIPCION IS 'Descripción de mérito preferente';
--/////////////////////
COMMENT ON COLUMN TBEP_MERITOSPREFERENTES.TIPO IS 'Tipo de mérito preferente';
--/////////////////////
COMMENT ON COLUMN TBEP_MERITOSPREFERENTES.APLICABLE IS 'Donde se aplica el cálculo del mérito preferente';
--/////////////////////
COMMENT ON COLUMN TBEP_MERITOSPREFERENTES.FACTOR IS 'Formula de cálculo del merito preferente';
--/////////////////////
COMMENT ON COLUMN TBEP_MERITOSPREFERENTES.VALOR_MAXIMO IS 'Valor máximo del cálculo';
--/////////////////////
COMMENT ON COLUMN TBEP_MERITOSPREFERENTES.BEPTIT_TIPO_CODNUM IS 'Fk a las titulaciones para el campo tipo';
--/////////////////////
COMMENT ON COLUMN TBEP_MERITOSPREFERENTES.BEPITE_TIPO_CODNUM IS 'Fk a las item de baremacion para el campo tipo';
--/////////////////////
COMMENT ON COLUMN TBEP_MERITOSPREFERENTES.BEPBLO_APLICABLE_CODNUM IS 'Fk a las bloques de baremacion para el campo aplicable';
--/////////////////////
COMMENT ON COLUMN TBEP_MERITOSPREFERENTES.BEPAPA_APLICABLE_CODNUM IS 'Fk a las apartados de baremacion para el campo aplicable';
--/////////////////////
COMMENT ON COLUMN TBEP_MERITOSPREFERENTES.BEPITE_APLICABLE_CODNUM IS 'Fk a las items de baremacion para el campo aplicable';
--/////////////////////
COMMENT ON TABLE TBEP_MERITOSPREFERENTES IS 'Méritos preferentes. ALIAS: [bepmep] ACRONIMO: [MEP]';
--/////////////////////
CREATE TABLE UVIRTUAL.TBEP_HTO_MERITOSPREFERENTES (
    CODCAMBIO NUMBER(11,0) NOT NULL,
    LOG VARCHAR(50) NOT NULL,
    FECHALOG TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    CODNUM NUMBER(11,0) CONSTRAINT RBEP_NMEP_HTO_CODNUM NOT NULL,
    DESCRIPCION VARCHAR2(1000 CHAR) CONSTRAINT RBEP_NMEP_HTO_DESCRIPCION NOT NULL, 
    TIPO VARCHAR2(15 CHAR) DEFAULT 'TITULACION',
    APLICABLE VARCHAR2(10 CHAR) DEFAULT 'BLOQUE',
    FACTOR VARCHAR2(20 CHAR) CONSTRAINT RBEP_NMEP_HTO_FACTOR NOT NULL,
    VALOR_MAXIMO NUMBER(6, 2) DEFAULT NULL,
    BEPTIT_TIPO_CODNUM NUMBER(11,0) NULL,
    BEPITE_TIPO_CODNUM NUMBER(11,0) NULL,
    BEPBLO_APLICABLE_CODNUM NUMBER(11,0) NULL,
    BEPAPA_APLICABLE_CODNUM NUMBER(11,0) NULL,
    BEPITE_APLICABLE_CODNUM NUMBER(11,0) NULL,
    CONSTRAINT IBEP_PMEP_HTO_MERITOSPREFERENTES PRIMARY KEY (CODCAMBIO)
);
--/////////////////////
CREATE SEQUENCE QBEP_MEP START WITH 1;
--/////////////////////
CREATE SEQUENCE QBEP_HTO_MEP START WITH 1;
--/////////////////////
CREATE TRIGGER DBEP_MEP_BRI
BEFORE INSERT
ON TBEP_MERITOSPREFERENTES
FOR EACH ROW
DECLARE
BEGIN
    SELECT QBEP_MEP.nextval into :new.CODNUM FROM dual;

    INSERT INTO TBEP_HTO_MERITOSPREFERENTES (CODCAMBIO,LOG,CODNUM,DESCRIPCION,TIPO,APLICABLE,FACTOR,VALOR_MAXIMO,BEPTIT_TIPO_CODNUM,BEPITE_TIPO_CODNUM,BEPBLO_APLICABLE_CODNUM,BEPAPA_APLICABLE_CODNUM,BEPITE_APLICABLE_CODNUM)
    VALUES (QBEP_HTO_MEP.NEXTVAL,'AFTER_INSERT',:New.CODNUM,:New.DESCRIPCION,:New.TIPO,:New.APLICABLE,:New.FACTOR,:New.VALOR_MAXIMO,:New.BEPTIT_TIPO_CODNUM,:New.BEPITE_TIPO_CODNUM,:New.BEPBLO_APLICABLE_CODNUM,:New.BEPAPA_APLICABLE_CODNUM,:New.BEPITE_APLICABLE_CODNUM);
END DBEP_MEP_BRI;
--/////////////////////
CREATE TRIGGER DBEP_MEP_BRU
BEFORE UPDATE
ON TBEP_MERITOSPREFERENTES
FOR EACH ROW
DECLARE
BEGIN
    INSERT INTO TBEP_HTO_MERITOSPREFERENTES (CODCAMBIO,LOG,CODNUM,DESCRIPCION,TIPO,APLICABLE,FACTOR,VALOR_MAXIMO,BEPTIT_TIPO_CODNUM,BEPITE_TIPO_CODNUM,BEPBLO_APLICABLE_CODNUM,BEPAPA_APLICABLE_CODNUM,BEPITE_APLICABLE_CODNUM)
    VALUES (QBEP_HTO_MEP.NEXTVAL,'BEFORE_UPDATE',:Old.CODNUM,:Old.DESCRIPCION,:Old.TIPO,:Old.APLICABLE,:Old.FACTOR,:Old.VALOR_MAXIMO,:Old.BEPTIT_TIPO_CODNUM,:Old.BEPITE_TIPO_CODNUM,:Old.BEPBLO_APLICABLE_CODNUM,:Old.BEPAPA_APLICABLE_CODNUM,:Old.BEPITE_APLICABLE_CODNUM);
    
    INSERT INTO TBEP_HTO_MERITOSPREFERENTES (CODCAMBIO,LOG,CODNUM,DESCRIPCION,TIPO,APLICABLE,FACTOR,VALOR_MAXIMO,BEPTIT_TIPO_CODNUM,BEPITE_TIPO_CODNUM,BEPBLO_APLICABLE_CODNUM,BEPAPA_APLICABLE_CODNUM,BEPITE_APLICABLE_CODNUM)
    VALUES (QBEP_HTO_MEP.NEXTVAL,'AFTER_UPDATE',:New.CODNUM,:New.DESCRIPCION,:New.TIPO,:New.APLICABLE,:New.FACTOR,:New.VALOR_MAXIMO,:New.BEPTIT_TIPO_CODNUM,:New.BEPITE_TIPO_CODNUM,:New.BEPBLO_APLICABLE_CODNUM,:New.BEPAPA_APLICABLE_CODNUM,:New.BEPITE_APLICABLE_CODNUM);
END DBEP_MEP_BRU;
--/////////////////////
CREATE TRIGGER DBEP_MEP_BRD
BEFORE DELETE
ON TBEP_MERITOSPREFERENTES
FOR EACH ROW
DECLARE
BEGIN
    INSERT INTO TBEP_HTO_MERITOSPREFERENTES (CODCAMBIO,LOG,CODNUM,DESCRIPCION,TIPO,APLICABLE,FACTOR,VALOR_MAXIMO,BEPTIT_TIPO_CODNUM,BEPITE_TIPO_CODNUM,BEPBLO_APLICABLE_CODNUM,BEPAPA_APLICABLE_CODNUM,BEPITE_APLICABLE_CODNUM)
    VALUES (QBEP_HTO_MEP.NEXTVAL,'BEFORE_DELETE',:Old.CODNUM,:Old.DESCRIPCION,:Old.TIPO,:Old.APLICABLE,:Old.FACTOR,:Old.VALOR_MAXIMO,:Old.BEPTIT_TIPO_CODNUM,:Old.BEPITE_TIPO_CODNUM,:Old.BEPBLO_APLICABLE_CODNUM,:Old.BEPAPA_APLICABLE_CODNUM,:Old.BEPITE_APLICABLE_CODNUM);
END DBEP_MEP_BRD;
