CREATE TABLE UVIRTUAL.TBEP_SOLICITUD_BOLSAS (
	CODNUM NUMBER(11,0) CONSTRAINT RBEP_NSBO_CODNUM NOT NULL,
	BEPBOL_CODNUM NUMBER(11,0) CONSTRAINT RBEP_NSBO_BEPBOL_CODNUM NOT NULL,
	BEPSOL_CODNUM NUMBER(11,0) CONSTRAINT RBEP_NSBO_BEPSOL_CODNUM NOT NULL,
	CONSTRAINT IBEP_FSBO_BOL FOREIGN KEY (BEPBOL_CODNUM) REFERENCES TBEP_BOLSAS (CODNUM),
	CONSTRAINT IBEP_FSBO_SOL FOREIGN KEY (BEPSOL_CODNUM) REFERENCES TBEP_SOLICITUDES (CODNUM),
	CONSTRAINT IBEP_USBO UNIQUE (BEPBOL_CODNUM, BEPSOL_CODNUM),
	CONSTRAINT IBEP_PSBO PRIMARY KEY (CODNUM)
);
--/////////////////////
COMMENT ON COLUMN TBEP_SOLICITUD_BOLSAS.BEPBOL_CODNUM IS 'Clave foránea a tabla bolsas';
--/////////////////////
COMMENT ON COLUMN TBEP_SOLICITUD_BOLSAS.BEPSOL_CODNUM IS 'Clave foránea a tabla solicitudes';
--/////////////////////
COMMENT ON TABLE TBEP_SOLICITUD_BOLSAS IS 'Tabla que relaciona las bolsas con las solicitudes. ALIAS: [bepsbo] ACRONIMO: [SBO]';
--/////////////////////
CREATE TABLE UVIRTUAL.TBEP_HTO_SOLICITUD_BOLSAS (
 	CODCAMBIO NUMBER(11,0) CONSTRAINT RBEP_NSBO_HTO_CODCAMBIO NOT NULL,
 	LOG VARCHAR(50) CONSTRAINT RBEP_NSBO_HTO_LOG NOT NULL,
 	FECHALOG TIMESTAMP DEFAULT CURRENT_TIMESTAMP CONSTRAINT RBEP_NSBO_HTO_FECHALOG NOT NULL,
 	CODNUM NUMBER(11,0) CONSTRAINT RBEP_NSBO_HTO_CODNUM NOT NULL,
	BEPBOL_CODNUM NUMBER(11,0) CONSTRAINT RBEP_NSBO_HTO_BEPBOL_CODNUM NOT NULL,
	BEPSOL_CODNUM NUMBER(11,0) CONSTRAINT RBEP_NSBO_HTO_BEPSOL_CODNUM NOT NULL,
	CONSTRAINT IBEP_PSBO_HISTORICO PRIMARY KEY (CODCAMBIO)
);
--/////////////////////
CREATE SEQUENCE QBEP_SBO START WITH 1;
--/////////////////////
CREATE SEQUENCE QBEP_HTO_SBO START WITH 1;
--/////////////////////
CREATE TRIGGER DBEP_SBO_BRI
BEFORE INSERT
ON TBEP_SOLICITUD_BOLSAS
FOR EACH ROW
DECLARE
BEGIN
	SELECT QBEP_SBO.nextval into :new.CODNUM FROM dual;
	
    INSERT INTO TBEP_HTO_SOLICITUD_BOLSAS (CODCAMBIO,LOG,CODNUM,BEPBOL_CODNUM,BEPSOL_CODNUM)
    VALUES (QBEP_HTO_SBO.NEXTVAL,'AFTER_INSERT',:New.CODNUM,:New.BEPBOL_CODNUM,:New.BEPSOL_CODNUM);
END DBEP_SBO_BRI;
--/////////////////////
CREATE TRIGGER DBEP_SBO_BRU
BEFORE UPDATE
ON TBEP_SOLICITUD_BOLSAS
FOR EACH ROW
DECLARE
BEGIN
	INSERT INTO TBEP_HTO_SOLICITUD_BOLSAS (CODCAMBIO,LOG,CODNUM,BEPBOL_CODNUM,BEPSOL_CODNUM)
    VALUES (QBEP_HTO_SBO.NEXTVAL,'BEFORE_UPDATE',:Old.CODNUM,:Old.BEPBOL_CODNUM,:Old.BEPSOL_CODNUM);
    
 	INSERT INTO TBEP_HTO_SOLICITUD_BOLSAS (CODCAMBIO,LOG,CODNUM,BEPBOL_CODNUM,BEPSOL_CODNUM)
    VALUES (QBEP_HTO_SBO.NEXTVAL,'AFTER_UPDATE',:New.CODNUM,:New.BEPBOL_CODNUM,:New.BEPSOL_CODNUM);
END DBEP_SBO_BRU;
--/////////////////////
CREATE TRIGGER DBEP_SBO_BRD
BEFORE DELETE
ON TBEP_SOLICITUD_BOLSAS
FOR EACH ROW
DECLARE
BEGIN
	INSERT INTO TBEP_HTO_SOLICITUD_BOLSAS (CODCAMBIO,LOG,CODNUM,BEPBOL_CODNUM,BEPSOL_CODNUM)
    VALUES (QBEP_HTO_SBO.NEXTVAL,'BEFORE_DELETE',:Old.CODNUM,:Old.BEPBOL_CODNUM,:Old.BEPSOL_CODNUM);
END DBEP_SBO_BRD;