CREATE TABLE UVIRTUAL.TBEP_TITULACIONES_USUARIO (
	CODNUM NUMBER(11,0) CONSTRAINT RBEP_NTUS_CODNUM NOT NULL,
	BEPTUS_TIT_CODNUM NUMBER(11,0) CONSTRAINT RBEP_NTUS_BEPTUS_TIT_CODNUM NOT NULL,
	BEPTUS_USU_CODNUM NUMBER(11,0) CONSTRAINT RBEP_NTUS_BEPTUS_USU_CODNUM NOT NULL,
	DESCRIPCION VARCHAR2(250 CHAR) DEFAULT NULL,
	ARCHIVO BLOB CONSTRAINT RBEP_NTUS_ARCHIVO NOT NULL,
	FLGBORRADO CHAR(1) DEFAULT 'N',
    FECHA_BORRADO TIMESTAMP NULL,
	CONSTRAINT IBEP_PTUS PRIMARY KEY (CODNUM),
	CONSTRAINT IBEP_FTUS_TIT FOREIGN KEY (BEPTUS_TIT_CODNUM) REFERENCES TBEP_TITULACIONES (CODNUM),
	CONSTRAINT IBEP_FTUS_USU FOREIGN KEY (BEPTUS_USU_CODNUM) REFERENCES TBEP_USUARIOS (CODNUM),
	CONSTRAINT RBEP_CTUS_FLGBORRADO CHECK(FLGBORRADO IN ('N','S'))
);
--/////////////////////
COMMENT ON COLUMN TBEP_TITULACIONES_USUARIO.BEPTUS_TIT_CODNUM IS 'Clave foránea a tabla titulaciones';
--/////////////////////
COMMENT ON COLUMN TBEP_TITULACIONES_USUARIO.BEPTUS_USU_CODNUM IS 'Clave foránea a tabla usuarios';
--/////////////////////
COMMENT ON TABLE TBEP_TITULACIONES_USUARIO IS 'Tabla que relaciona las titulaciones con los usuarios. ALIAS: [beptus] ACRONIMO: [TUS]';
--/////////////////////
CREATE TABLE UVIRTUAL.TBEP_HTO_TITULACIONES_USUARIO (
 	CODCAMBIO NUMBER(11,0) CONSTRAINT RBEP_NTUS_HTO_CODCAMBIO NOT NULL,
 	LOG VARCHAR(50) CONSTRAINT RBEP_NTUS_HTO_LOG NOT NULL,
 	FECHALOG TIMESTAMP DEFAULT CURRENT_TIMESTAMP CONSTRAINT RBEP_NTUS_HTO_FECHALOG NOT NULL,
	BEPTUS_TIT_CODNUM NUMBER(11,0) CONSTRAINT RBEP_NTUS_HTO_BEPTUS_TIT_CODNUM NOT NULL,
	BEPTUS_USU_CODNUM NUMBER(11,0) CONSTRAINT RBEP_NTUS_HTO_BETUS_USU_CODNUM NOT NULL,
	DESCRIPCION VARCHAR2(250 CHAR) DEFAULT NULL,
	ARCHIVO BLOB CONSTRAINT RBEP_NTUS_HTO_ARCHIVO NOT NULL,
	FLGBORRADO CHAR(1) DEFAULT 'N',
    FECHA_BORRADO TIMESTAMP NULL,
	CONSTRAINT IBEP_PTUS_HISTORICO PRIMARY KEY (CODCAMBIO)
);
--/////////////////////
CREATE SEQUENCE QBEP_TUS START WITH 1;
--/////////////////////
CREATE SEQUENCE QBEP_HTO_TUS START WITH 1;
--/////////////////////
CREATE TRIGGER DBEP_TUS_BRI
BEFORE INSERT
ON TBEP_TITULACIONES_USUARIO
FOR EACH ROW
DECLARE
BEGIN
	SELECT QBEP_TUS.nextval into :new.CODNUM FROM dual;	 	
	
    INSERT INTO TBEP_HTO_TITULACIONES_USUARIO (CODCAMBIO,LOG,BEPTUS_TIT_CODNUM,BEPTUS_USU_CODNUM,DESCRIPCION,ARCHIVO,FLGBORRADO,FECHA_BORRADO)
    VALUES (QBEP_HTO_TUS.NEXTVAL,'AFTER_INSERT',:New.BEPTUS_TIT_CODNUM,:New.BEPTUS_USU_CODNUM,:New.DESCRIPCION,:New.ARCHIVO,:New.FLGBORRADO,:New.FECHA_BORRADO);
END DBEP_TUS_BRI;
--/////////////////////
CREATE TRIGGER DBEP_TUS_BRU
BEFORE UPDATE
ON TBEP_TITULACIONES_USUARIO
FOR EACH ROW
DECLARE
BEGIN
	INSERT INTO TBEP_HTO_TITULACIONES_USUARIO (CODCAMBIO,LOG,BEPTUSTIT_CODNUM,BEPTUS_USU_CODNUM,DESCRIPCION,ARCHIVO,FLGBORRADO,FECHA_BORRADO)
    VALUES (QBEP_HTO_TUS.NEXTVAL,'BEFORE_UPDATE',:Old.BEPTUS_TIT_CODNUM,:Old.BEPTUS_USU_CODNUM,:Old.DESCRIPCION,:Old.ARCHIVO,:Old.FLGBORRADO,:Old.FECHA_BORRADO);
    
 	INSERT INTO TBEP_HTO_TITULACIONES_USUARIO (CODCAMBIO,LOG,BEPTUS_TIT_CODNUM,BEPTUS_USU_CODNUM,DESCRIPCION,ARCHIVO,FLGBORRADO,FECHA_BORRADO)
    VALUES (QBEP_HTO_TUS.NEXTVAL,'AFTER_UPDATE',:New.BEPTUS_TIT_CODNUM,:New.BEPTUS_USU_CODNUM,:New.DESCRIPCION,:New.ARCHIVO,:New.FLGBORRADO,:New.FECHA_BORRADO);
END DBEP_TUS_BRU;
--/////////////////////
CREATE TRIGGER DBEP_TUS_BRD
BEFORE DELETE
ON TBEP_TITULACIONES_USUARIO
FOR EACH ROW
DECLARE
BEGIN
	INSERT INTO TBEP_HTO_TITULACIONES_USUARIO (CODCAMBIO,LOG,BEPTUS_TIT_CODNUM,BEPTUS_USU_CODNUM,DESCRIPCION,ARCHIVO,FLGBORRADO,FECHA_BORRADO)
    VALUES (QBEP_HTO_TUS.NEXTVAL,'BEFORE_DELETE',:Old.BEPTUS_TIT_CODNUM,:Old.BEPTUS_USU_CODNUM,:Old.DESCRIPCION,:Old.ARCHIVO,:Old.FLGBORRADO,:Old.FECHA_BORRADO);
END DBEP_TUS_BRD;