CREATE TABLE UVIRTUAL.TBEP_MERITOS_PREFERENTES (	
	CODNUM NUMBER(11,0) CONSTRAINT RBEP_NMEP_CODNUM NOT NULL,
    DESCRIPCION VARCHAR2(1000 CHAR) CONSTRAINT RBEP_NMEP_DESCRIPCION NOT NULL, 
    TIPO VARCHAR2(25 CHAR) DEFAULT 'TITULACION_PREFERENTE',
    TIPO_CALCULO VARCHAR(25) DEFAULT 'FACTOR',
    APLICABLE VARCHAR2(10 CHAR) DEFAULT 'BLOQUE',    
    FACTOR VARCHAR2(20 CHAR) CONSTRAINT RBEP_NMEP_FACTOR NOT NULL,
    VALOR_MAXIMO NUMBER(6, 2) DEFAULT NULL,
    BEPITE_TIPO_CODNUM NUMBER(11,0) DEFAULT NULL,
    BEPBLO_APLICABLE_CODNUM NUMBER(11,0) DEFAULT NULL,
    BEPAPA_APLICABLE_CODNUM NUMBER(11,0) DEFAULT NULL,
    BEPITE_APLICABLE_CODNUM NUMBER(11,0) DEFAULT NULL,
    FLGACTIVO CHAR(1) DEFAULT 'S',
    CONSTRAINT RBEP_CMEP_TIPO CHECK (TIPO IN ('TITULACION_PREFERENTE','MERITO')),
    CONSTRAINT RBEP_CMEP_TIPO_CALCULO CHECK (TIPO_CALCULO IN ('FACTOR','VALOR_MERITO_FACTOR')),
    CONSTRAINT RBEP_CMEP_APLICABLE CHECK (APLICABLE IN ('BLOQUE','APARTADO','ITEM','TOTAL')),
    CONSTRAINT IBEP_FMEP_TIPO_ITE FOREIGN KEY (BEPITE_TIPO_CODNUM) REFERENCES TBEP_ITEMSBAREMACION (CODNUM),
    CONSTRAINT IBEP_FMEP_APLICABLE_BLO FOREIGN KEY (BEPBLO_APLICABLE_CODNUM) REFERENCES TBEP_BLOQUESBAREMACION (CODNUM),
    CONSTRAINT IBEP_FMEP_APLICABLE_APA FOREIGN KEY (BEPAPA_APLICABLE_CODNUM) REFERENCES TBEP_APARTADOSBAREMACION (CODNUM),
    CONSTRAINT IBEP_FMEP_APLICABLE_ITE FOREIGN KEY (BEPITE_APLICABLE_CODNUM) REFERENCES TBEP_ITEMSBAREMACION (CODNUM),
    CONSTRAINT RBEP_CMEP_FLGACTIVO CHECK(FLGACTIVO IN ('N','S')),
	CONSTRAINT IBEP_PMEP PRIMARY KEY (CODNUM)
);
--/////////////////////
COMMENT ON COLUMN TBEP_MERITOS_PREFERENTES.DESCRIPCION IS 'Descripción de mérito preferente';
--/////////////////////
COMMENT ON COLUMN TBEP_MERITOS_PREFERENTES.TIPO IS 'Tipo de mérito preferente';
--/////////////////////
COMMENT ON COLUMN TBEP_MERITOS_PREFERENTES.TIPO_CALCULO IS 'Indica el tipo de calculo del mérito preferente';
--/////////////////////
COMMENT ON COLUMN TBEP_MERITOS_PREFERENTES.APLICABLE IS 'Donde se aplica el cálculo del mérito preferente';
--/////////////////////
COMMENT ON COLUMN TBEP_MERITOS_PREFERENTES.FACTOR IS 'Formula de cálculo del merito preferente';
--/////////////////////
COMMENT ON COLUMN TBEP_MERITOS_PREFERENTES.VALOR_MAXIMO IS 'Valor máximo del cálculo';
--/////////////////////
COMMENT ON COLUMN TBEP_MERITOS_PREFERENTES.BEPITE_TIPO_CODNUM IS 'Fk a las item de baremacion para el campo tipo';
--/////////////////////
COMMENT ON COLUMN TBEP_MERITOS_PREFERENTES.BEPBLO_APLICABLE_CODNUM IS 'Fk a las bloques de baremacion para el campo aplicable';
--/////////////////////
COMMENT ON COLUMN TBEP_MERITOS_PREFERENTES.BEPAPA_APLICABLE_CODNUM IS 'Fk a las apartados de baremacion para el campo aplicable';
--/////////////////////
COMMENT ON COLUMN TBEP_MERITOS_PREFERENTES.BEPITE_APLICABLE_CODNUM IS 'Fk a las items de baremacion para el campo aplicable';
--/////////////////////
COMMENT ON TABLE TBEP_MERITOS_PREFERENTES IS 'Méritos preferentes. ALIAS: [bepmep] ACRONIMO: [MEP]';
--/////////////////////
CREATE TABLE UVIRTUAL.TBEP_HTO_MERITOS_PREFERENTES (
    CODCAMBIO NUMBER(11,0) CONSTRAINT RBEP_NMEP_HTO_CODCAMBIO NOT NULL, 
    LOG VARCHAR(50) CONSTRAINT RBEP_NMEP_HTO_LOG NOT NULL, 
    FECHALOG TIMESTAMP DEFAULT CURRENT_TIMESTAMP CONSTRAINT RBEP_NMEP_HTO_FECHALOG NOT NULL, 
    CODNUM NUMBER(11,0) CONSTRAINT RBEP_NMEP_HTO_CODNUM NOT NULL,
    DESCRIPCION VARCHAR2(1000 CHAR) CONSTRAINT RBEP_NMEP_HTO_DESCRIPCION NOT NULL, 
    TIPO VARCHAR2(25 CHAR) DEFAULT 'TITULACION_PREFERENTE',
    TIPO_CALCULO VARCHAR(25) DEFAULT 'FACTOR',
    APLICABLE VARCHAR2(10 CHAR) DEFAULT 'BLOQUE',
    FACTOR VARCHAR2(20 CHAR) CONSTRAINT RBEP_NMEP_HTO_FACTOR NOT NULL,
    VALOR_MAXIMO NUMBER(6, 2) DEFAULT NULL,
    BEPITE_TIPO_CODNUM NUMBER(11,0) NULL,
    BEPBLO_APLICABLE_CODNUM NUMBER(11,0) NULL,
    BEPAPA_APLICABLE_CODNUM NUMBER(11,0) NULL,
    BEPITE_APLICABLE_CODNUM NUMBER(11,0) NULL,
    FLGACTIVO CHAR(1) DEFAULT 'N',
    CONSTRAINT IBEP_PMEP_HTO_MERITOSPREFERENTES PRIMARY KEY (CODCAMBIO)
);
--/////////////////////
CREATE SEQUENCE QBEP_MEP START WITH 1;
--/////////////////////
CREATE SEQUENCE QBEP_HTO_MEP START WITH 1;
--/////////////////////
CREATE TRIGGER DBEP_MEP_BRI
BEFORE INSERT
ON TBEP_MERITOS_PREFERENTES
FOR EACH ROW
DECLARE
BEGIN
    SELECT QBEP_MEP.nextval into :new.CODNUM FROM dual;

    INSERT INTO TBEP_HTO_MERITOS_PREFERENTES (CODCAMBIO,LOG,CODNUM,DESCRIPCION,TIPO,TIPO_CALCULO,APLICABLE,FACTOR,VALOR_MAXIMO,BEPITE_TIPO_CODNUM,BEPBLO_APLICABLE_CODNUM,BEPAPA_APLICABLE_CODNUM,BEPITE_APLICABLE_CODNUM,FLGACTIVO)
    VALUES (QBEP_HTO_MEP.NEXTVAL,'AFTER_INSERT',:New.CODNUM,:New.DESCRIPCION,:New.TIPO,:New.TIPO_CALCULO,:New.APLICABLE,:New.FACTOR,:New.VALOR_MAXIMO,:New.BEPITE_TIPO_CODNUM,:New.BEPBLO_APLICABLE_CODNUM,:New.BEPAPA_APLICABLE_CODNUM,:New.BEPITE_APLICABLE_CODNUM,:New.FLGACTIVO);
END DBEP_MEP_BRI;
--/////////////////////
CREATE TRIGGER DBEP_MEP_BRU
BEFORE UPDATE
ON TBEP_MERITOS_PREFERENTES
FOR EACH ROW
DECLARE
BEGIN
    INSERT INTO TBEP_HTO_MERITOS_PREFERENTES (CODCAMBIO,LOG,CODNUM,DESCRIPCION,TIPO,TIPO_CALCULO,APLICABLE,FACTOR,VALOR_MAXIMO,BEPITE_TIPO_CODNUM,BEPBLO_APLICABLE_CODNUM,BEPAPA_APLICABLE_CODNUM,BEPITE_APLICABLE_CODNUM,FLGACTIVO)
    VALUES (QBEP_HTO_MEP.NEXTVAL,'BEFORE_UPDATE',:Old.CODNUM,:Old.DESCRIPCION,:Old.TIPO,:Old.TIPO_CALCULO,:Old.APLICABLE,:Old.FACTOR,:Old.VALOR_MAXIMO,:Old.BEPITE_TIPO_CODNUM,:Old.BEPBLO_APLICABLE_CODNUM,:Old.BEPAPA_APLICABLE_CODNUM,:Old.BEPITE_APLICABLE_CODNUM,:Old.FLGACTIVO);
    
    INSERT INTO TBEP_HTO_MERITOS_PREFERENTES (CODCAMBIO,LOG,CODNUM,DESCRIPCION,TIPO,TIPO_CALCULO,APLICABLE,FACTOR,VALOR_MAXIMO,BEPITE_TIPO_CODNUM,BEPBLO_APLICABLE_CODNUM,BEPAPA_APLICABLE_CODNUM,BEPITE_APLICABLE_CODNUM,FLGACTIVO)
    VALUES (QBEP_HTO_MEP.NEXTVAL,'AFTER_UPDATE',:New.CODNUM,:New.DESCRIPCION,:New.TIPO,:New.TIPO_CALCULO,:New.APLICABLE,:New.FACTOR,:New.VALOR_MAXIMO,:New.BEPITE_TIPO_CODNUM,:New.BEPBLO_APLICABLE_CODNUM,:New.BEPAPA_APLICABLE_CODNUM,:New.BEPITE_APLICABLE_CODNUM,:New.FLGACTIVO);
END DBEP_MEP_BRU;
--/////////////////////
CREATE TRIGGER DBEP_MEP_BRD
BEFORE DELETE
ON TBEP_MERITOS_PREFERENTES
FOR EACH ROW
DECLARE
BEGIN
    INSERT INTO TBEP_HTO_MERITOS_PREFERENTES (CODCAMBIO,LOG,CODNUM,DESCRIPCION,TIPO,TIPO_CALCULO,APLICABLE,FACTOR,VALOR_MAXIMO,BEPITE_TIPO_CODNUM,BEPBLO_APLICABLE_CODNUM,BEPAPA_APLICABLE_CODNUM,BEPITE_APLICABLE_CODNUM,FLGACTIVO)
    VALUES (QBEP_HTO_MEP.NEXTVAL,'BEFORE_DELETE',:Old.CODNUM,:Old.DESCRIPCION,:Old.TIPO,:Old.TIPO_CALCULO,:Old.APLICABLE,:Old.FACTOR,:Old.VALOR_MAXIMO,:Old.BEPITE_TIPO_CODNUM,:Old.BEPBLO_APLICABLE_CODNUM,:Old.BEPAPA_APLICABLE_CODNUM,:Old.BEPITE_APLICABLE_CODNUM,:Old.FLGACTIVO);
END DBEP_MEP_BRD;
