CREATE TABLE TBEP_MER_PRE_OPCIONES (
    CODNUM NUMBER(11,0) CONSTRAINT RBEP_NMPO_CODNUM NOT NULL,
    BEPMEP_CODNUM NUMBER(11,0) CONSTRAINT RBEP_NMPO_BEPMEP_CODNUM NOT NULL, 
    NOMBRE VARCHAR2(50 CHAR) CONSTRAINT RBEP_NMPO_NOMBRE NOT NULL,
    FACTOR NUMBER(19,4) CONSTRAINT RBEP_NMPO_FACTOR NOT NULL,
    FLGBORRADO CHAR(1) DEFAULT 'N',
    FECHA_BORRADO TIMESTAMP NULL,
    UID_USUARIO VARCHAR2(100) CONSTRAINT RBEP_NMPO_UIDUSUARIO NOT NULL,
    CONSTRAINT IBEP_PMPO PRIMARY KEY (CODNUM),
    CONSTRAINT IBEP_FMPO_MEP FOREIGN KEY (BEPMEP_CODNUM) REFERENCES TBEP_MERITOS_PREFERENTES (CODNUM),
    CONSTRAINT RBEP_CMPO_FLGBORRADO CHECK (FLGBORRADO IN ('N','S'))
);
--/////////////////////
COMMENT ON COLUMN TBEP_MER_PRE_OPCIONES.BEPMEP_CODNUM IS 'Fk al mérito preferente';
--/////////////////////
COMMENT ON COLUMN TBEP_MER_PRE_OPCIONES.NOMBRE IS 'Nombre de la opción';
--/////////////////////
COMMENT ON COLUMN TBEP_MER_PRE_OPCIONES.FACTOR IS 'Factor de la opción';
--/////////////////////
COMMENT ON COLUMN TBEP_MER_PRE_OPCIONES.UID_USUARIO IS 'Ultimo usuario que hace cambios en la tabla';
--/////////////////////
COMMENT ON TABLE TBEP_MER_PRE_OPCIONES IS 'Méritos preferentes opciones. ALIAS: [bepmpo] ACRONIMO: [MPO]';
--/////////////////////
CREATE TABLE TBEP_HTO_MER_PRE_OPCIONES (
    CODCAMBIO NUMBER(11,0) CONSTRAINT RBEP_NMPO_HTO_CODCAMBIO NOT NULL, 
    LOG VARCHAR(50) CONSTRAINT RBEP_NMPO_HTO_LOG NOT NULL, 
    FECHALOG TIMESTAMP DEFAULT CURRENT_TIMESTAMP CONSTRAINT RBEP_NPO_HTO_FECHALOG NOT NULL, 
    CODNUM NUMBER(11,0) CONSTRAINT RBEP_NMPO_HTO_CODNUM NOT NULL,
    BEPMEP_CODNUM NUMBER(11,0) CONSTRAINT RBEP_NMPO_HTO_BEPMEP_CODNUM NOT NULL, 
    NOMBRE VARCHAR2(50 CHAR) CONSTRAINT RBEP_NMPO_HTO_NOMBRE NOT NULL,
    FACTOR NUMBER(19,4) CONSTRAINT RBEP_NMPO_HTO_FACTOR NOT NULL,
    FLGBORRADO CHAR(1) DEFAULT 'N',
    FECHA_BORRADO TIMESTAMP NULL,
    UID_USUARIO VARCHAR2(100) CONSTRAINT RBEP_NMPO_HTO_UIDUSUARIO NOT NULL,
    CONSTRAINT IBEP_PMPO_HTO PRIMARY KEY (CODCAMBIO)
);
--/////////////////////
CREATE SEQUENCE QBEP_MPO START WITH 1;
--/////////////////////
CREATE SEQUENCE QBEP_HTO_MPO START WITH 1;
--/////////////////////
CREATE TRIGGER DBEP_MPO_BRI
BEFORE INSERT
ON TBEP_MER_PRE_OPCIONES
FOR EACH ROW
DECLARE
BEGIN
    SELECT QBEP_MPO.nextval into :new.CODNUM FROM dual;

    INSERT INTO TBEP_HTO_MER_PRE_OPCIONES (CODCAMBIO,LOG,CODNUM,BEPMEP_CODNUM,NOMBRE,FACTOR,FLGBORRADO,FECHA_BORRADO,UID_USUARIO)
    VALUES (QBEP_HTO_MPO.NEXTVAL,'AFTER_INSERT',:New.CODNUM,:New.BEPMEP_CODNUM,:New.NOMBRE,:New.FACTOR,:New.FLGBORRADO,:New.FECHA_BORRADO,:New.UID_USUARIO);
END DBEP_MPO_BRI;
--/////////////////////
CREATE TRIGGER DBEP_MPO_BRU
BEFORE UPDATE
ON TBEP_MER_PRE_OPCIONES
FOR EACH ROW
DECLARE
BEGIN
    INSERT INTO TBEP_HTO_MER_PRE_OPCIONES (CODCAMBIO,LOG,CODNUM,BEPMEP_CODNUM,NOMBRE,FACTOR,FLGBORRADO,FECHA_BORRADO,UID_USUARIO)
    VALUES (QBEP_HTO_MPO.NEXTVAL,'BEFORE_UPDATE',:Old.CODNUM,:Old.BEPMEP_CODNUM,:Old.NOMBRE,:Old.FACTOR,:Old.FLGBORRADO,:Old.FECHA_BORRADO,:Old.UID_USUARIO);
    
    INSERT INTO TBEP_HTO_MER_PRE_OPCIONES (CODCAMBIO,LOG,CODNUM,BEPMEP_CODNUM,NOMBRE,FACTOR,FLGBORRADO,FECHA_BORRADO,UID_USUARIO)
    VALUES (QBEP_HTO_MPO.NEXTVAL,'AFTER_UPDATE',:New.CODNUM,:New.BEPMEP_CODNUM,:New.NOMBRE,:New.FACTOR,:New.FLGBORRADO,:New.FECHA_BORRADO,:New.UID_USUARIO);
END DBEP_MPO_BRU;
--/////////////////////
CREATE TRIGGER DBEP_MPO_BRD
BEFORE DELETE
ON TBEP_MER_PRE_OPCIONES
FOR EACH ROW
DECLARE
BEGIN
    INSERT INTO TBEP_HTO_MER_PRE_OPCIONES (CODCAMBIO,LOG,CODNUM,BEPMEP_CODNUM,NOMBRE,FACTOR,FLGBORRADO,FECHA_BORRADO,UID_USUARIO)
    VALUES (QBEP_HTO_MPO.NEXTVAL,'BEFORE_DELETE',:Old.CODNUM,:Old.BEPMEP_CODNUM,:Old.NOMBRE,:Old.FACTOR,:Old.FLGBORRADO,:Old.FECHA_BORRADO,:Old.UID_USUARIO);
END DBEP_MPO_BRD;
