CREATE TABLE UVIRTUAL.TBEP_SOLICITUD_BOLSAS_MERITOS (
	BEPSBO_CODNUM NUMBER(11,0) NOT NULL,
	BEPMER_CODNUM NUMBER(11,0) NOT NULL,
	FLGAFINIDAD CHAR(1) DEFAULT 'N',
	FLGEXCLUIDO CHAR(1) DEFAULT 'N',
	CONSTRAINT IBEP_FSBM_BOL FOREIGN KEY (BEPSBO_CODNUM) REFERENCES TBEP_SOLICITUD_BOLSAS (CODNUM),
	CONSTRAINT IBEP_FSBM_MER FOREIGN KEY (BEPMER_CODNUM) REFERENCES TBEP_MERITOS (CODNUM),
	CONSTRAINT IBEP_PSBM PRIMARY KEY (BEPSBO_CODNUM, BEPMER_CODNUM)
);
--/////////////////////
COMMENT ON COLUMN TBEP_SOLICITUD_BOLSAS_MERITOS.BEPSBO_CODNUM IS 'Clave foránea a tabla solicitudbolsas';
--/////////////////////
COMMENT ON COLUMN TBEP_SOLICITUD_BOLSAS_MERITOS.BEPMER_CODNUM IS 'Clave foránea a tabla méritos';
--/////////////////////
COMMENT ON COLUMN TBEP_SOLICITUD_BOLSAS_MERITOS.FLGAFINIDAD IS 'Indica si el mérito es afín al área';
--/////////////////////
COMMENT ON COLUMN TBEP_SOLICITUD_BOLSAS_MERITOS.FLGEXCLUIDO IS 'Indica si el mérito está excluido';
--/////////////////////
COMMENT ON TABLE TBEP_SOLICITUD_BOLSAS_MERITOS IS 'Tabla que relaciona los méritos con las bolsas y solicitudes. ALIAS: [bepsbm] ACRONIMO: [SBM]';
--/////////////////////
CREATE TABLE UVIRTUAL.TBEP_HTO_SOLICITUD_BOLSAS_MERITOS (
 	CODCAMBIO NUMBER(11,0) NOT NULL,
 	LOG VARCHAR(50) NOT NULL,
 	FECHALOG TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
	BEPSBO_CODNUM NUMBER(11,0) NOT NULL,
	BEPMER_CODNUM NUMBER(11,0) NOT NULL,
	FLGAFINIDAD CHAR(1) DEFAULT 'N',
	FLGEXCLUIDO CHAR(1) DEFAULT 'N',
	CONSTRAINT IBEP_PSBM_HISTORICO PRIMARY KEY (CODCAMBIO)
);
--/////////////////////
CREATE SEQUENCE QBEP_SBM START WITH 1;
--/////////////////////
CREATE SEQUENCE QBEP_HTO_SBM START WITH 1;
--/////////////////////
CREATE TRIGGER DBEP_SBM_BRI
BEFORE INSERT
ON TBEP_SOLICITUD_BOLSAS_MERITOS
FOR EACH ROW
DECLARE
BEGIN
    INSERT INTO TBEP_HTO_SOLICITUD_BOLSAS_MERITOS (CODCAMBIO,LOG,BEPSBO_CODNUM,BEPMER_CODNUM,FLGAFINIDAD,FLGEXCLUIDO)
    VALUES (QBEP_HTO_SBM.NEXTVAL,'AFTER_INSERT',:New.BEPSBO_CODNUM,:New.BEPMER_CODNUM,:New.FLGAFINIDAD,:New.FLGEXCLUIDO);
END DBEP_SBM_BRI;
--/////////////////////
CREATE TRIGGER DBEP_SBM_BRU
BEFORE UPDATE
ON TBEP_SOLICITUD_BOLSAS_MERITOS
FOR EACH ROW
DECLARE
BEGIN
	INSERT INTO TBEP_HTO_SOLICITUD_BOLSAS_MERITOS (CODCAMBIO,LOG,BEPSBO_CODNUM,BEPMER_CODNUM,FLGAFINIDAD,FLGEXCLUIDO)
    VALUES (QBEP_HTO_SBM.NEXTVAL,'BEFORE_UPDATE',:Old.BEPSBO_CODNUM,:Old.BEPMER_CODNUM,:Old.FLGAFINIDAD,:Old.FLGEXCLUIDO);
    
 	INSERT INTO TBEP_HTO_SOLICITUD_BOLSAS_MERITOS (CODCAMBIO,LOG,BEPSBO_CODNUM,BEPMER_CODNUM,FLGAFINIDAD,FLGEXCLUIDO)
    VALUES (QBEP_HTO_SBM.NEXTVAL,'AFTER_UPDATE',:New.BEPSBO_CODNUM,:New.BEPMER_CODNUM,:New.FLGAFINIDAD,:New.FLGEXCLUIDO);
END DBEP_SBM_BRU;
--/////////////////////
CREATE TRIGGER DBEP_SBM_BRD
BEFORE DELETE
ON TBEP_SOLICITUD_BOLSAS_MERITOS
FOR EACH ROW
DECLARE
BEGIN
	INSERT INTO TBEP_HTO_SOLICITUD_BOLSAS_MERITOS (CODCAMBIO,LOG,BEPSBO_CODNUM,BEPMER_CODNUM,FLGAFINIDAD,FLGEXCLUIDO)
    VALUES (QBEP_HTO_SBM.NEXTVAL,'BEFORE_DELETE',:Old.BEPSBO_CODNUM,:Old.BEPMER_CODNUM,:Old.FLGAFINIDAD,:Old.FLGEXCLUIDO);
END DBEP_SBM_BRD;