CREATE TABLE UVIRTUAL.TBEP_SOL_BOL_MER_VALORACION (
    CODNUM NUMBER(11,0) CONSTRAINT RBEP_NSBV_CODNUM NOT NULL,
	BEPSBM_CODNUM NUMBER(11,0) CONSTRAINT RBEP_NSBV_BEPSBM_CODNUM NOT NULL, 
	BEPAFI_CODNUM NUMBER(11,0) CONSTRAINT RBEP_NSBV_BEPAFI_CODNUM NOT NULL, 
	VALOR FLOAT(11) NULL, 
	CONSTRAINT IBEP_FSBV_SBM FOREIGN KEY (BEPSBM_CODNUM) REFERENCES TBEP_SOL_BOL_MERITOS (CODNUM),
	CONSTRAINT IBEP_FSBV_AFI FOREIGN KEY (BEPAFI_CODNUM) REFERENCES TBEP_AFINIDADES (CODNUM),
	CONSTRAINT IBEP_PSBV PRIMARY KEY (CODNUM)
);
--/////////////////////
COMMENT ON COLUMN TBEP_SOL_BOL_MER_VALORACION.BEPSBM_CODNUM IS 'Clave foránea a tabla solicitudbolsasmeritos';
--/////////////////////
COMMENT ON COLUMN TBEP_SOL_BOL_MER_VALORACION.BEPAFI_CODNUM IS 'Clave foránea a tabla afinidades';
--/////////////////////
COMMENT ON COLUMN TBEP_SOL_BOL_MER_VALORACION.VALOR IS 'Valoración del merito con afinidad';
--/////////////////////
COMMENT ON TABLE TBEP_SOL_BOL_MER_VALORACION IS 'Evaluaciones del mérito asociado a una bolsa y solicitud. ALIAS: [bepsbv] ACRONIMO: [SBV]';
--/////////////////////
CREATE TABLE UVIRTUAL.TBEP_HTO_SOL_BOL_MER_VALORA (
 	CODCAMBIO NUMBER(11,0) CONSTRAINT RBEP_NSBV_HTO_CODCAMBIO NOT NULL, 
 	LOG VARCHAR(50) CONSTRAINT RBEP_NSBV_HTO_LOG NOT NULL, 
 	FECHALOG TIMESTAMP DEFAULT CURRENT_TIMESTAMP CONSTRAINT RBEP_NSBV_HTO_FECHALOG NOT NULL, 
    CODNUM NUMBER(11,0) CONSTRAINT RBEP_NSBV_HTO_CODNUM NOT NULL,
    BEPSBM_CODNUM NUMBER(11,0) CONSTRAINT RBEP_NSBV_HTO_BEPSBM_CODNUM NOT NULL, 
    BEPAFI_CODNUM NUMBER(11,0) CONSTRAINT RBEP_NSBV_HTO_BEPAFI_CODNUM NOT NULL, 
    VALOR FLOAT(11) NULL, 
	CONSTRAINT IBEP_PSBV_HISTORICO PRIMARY KEY (CODCAMBIO)
);
--/////////////////////
CREATE SEQUENCE QBEP_SBV START WITH 1;
--/////////////////////
CREATE SEQUENCE QBEP_HTO_SBV START WITH 1;
--/////////////////////
CREATE TRIGGER DBEP_SBV_BRI
BEFORE INSERT
ON TBEP_SOL_BOL_MER_VALORACION
FOR EACH ROW
DECLARE
BEGIN
    SELECT QBEP_SBV.nextval into :new.CODNUM FROM dual;

    INSERT INTO TBEP_HTO_SOL_BOL_MER_VALORA (CODCAMBIO,LOG,CODNUM,BEPSBM_CODNUM,BEPAFI_CODNUM,VALOR)
    VALUES (QBEP_HTO_SBV.NEXTVAL,'AFTER_INSERT',:New.CODNUM,:New.BEPSBM_CODNUM,:New.BEPAFI_CODNUM,:New.VALOR);
END DBEP_SBM_BRI;
--/////////////////////
CREATE TRIGGER DBEP_SBV_BRU
BEFORE UPDATE
ON TBEP_SOL_BOL_MER_VALORACION
FOR EACH ROW
DECLARE
BEGIN
	INSERT INTO TBEP_HTO_SOL_BOL_MER_VALORA (CODCAMBIO,LOG,CODNUM,BEPSBM_CODNUM,BEPAFI_CODNUM,VALOR)
    VALUES (QBEP_HTO_SBV.NEXTVAL,'BEFORE_UPDATE',:Old.CODNUM,:Old.BEPSBM_CODNUM,:Old.BEPAFI_CODNUM,:Old.VALOR);
    
 	INSERT INTO TBEP_HTO_SOL_BOL_MER_VALORA (CODCAMBIO,LOG,CODNUM,BEPSBM_CODNUM,BEPAFI_CODNUM,VALOR)
    VALUES (QBEP_HTO_SBV.NEXTVAL,'AFTER_UPDATE',:New.CODNUM,:New.BEPSBM_CODNUM,:New.BEPAFI_CODNUM,:New.VALOR);
END DBEP_SBV_BRU;
--/////////////////////
CREATE TRIGGER DBEP_SBV_BRD
BEFORE DELETE
ON TBEP_SOL_BOL_MER_VALORACION
FOR EACH ROW
DECLARE
BEGIN
	INSERT INTO TBEP_HTO_SOL_BOL_MER_VALORA (CODCAMBIO,LOG,CODNUM,BEPSBM_CODNUM,BEPAFI_CODNUM,VALOR)
    VALUES (QBEP_HTO_SBV.NEXTVAL,'BEFORE_DELETE',:Old.CODNUM,:Old.BEPSBM_CODNUM,:Old.BEPAFI_CODNUM,:Old.VALOR);
END DBEP_SBV_BRD;
