CREATE TABLE TBEP_MERITOS_EXCLUYENTES (
	CODNUM NUMBER(11,0) CONSTRAINT RBEP_NMEX_CODNUM NOT NULL, 
	BEPITE_CODNUM_PADRE NUMBER(11,0) CONSTRAINT RBEP_NMEX_BEPITE_CODNUMPADRE NOT NULL, 
	BEPITE_CODNUM_HIJO NUMBER(11,0) CONSTRAINT RBEP_NMEX_BEPITE_CODNUMHIJO NOT NULL, 
	UID_USUARIO VARCHAR2(100) CONSTRAINT RBEP_NMEX_UIDUSUARIO NOT NULL,
    CONSTRAINT IBEP_PMEX PRIMARY KEY (CODNUM),
    CONSTRAINT IBEP_FITE_MEX_PADRE FOREIGN KEY (BEPITE_CODNUM_PADRE) REFERENCES TBEP_ITEMSBAREMACION (CODNUM),
    CONSTRAINT IBEP_FITE_MEX_HIJO FOREIGN KEY (BEPITE_CODNUM_HIJO) REFERENCES TBEP_ITEMSBAREMACION (CODNUM)
);
--/////////////////////
COMMENT ON COLUMN TBEP_MERITOS_EXCLUYENTES.BEPITE_CODNUM_PADRE IS 'fk al item padre';
--/////////////////////
COMMENT ON COLUMN TBEP_MERITOS_EXCLUYENTES.BEPITE_CODNUM_HIJO IS 'fk al item hijo (excluido)';
--/////////////////////
COMMENT ON COLUMN TBEP_MERITOS_EXCLUYENTES.UID_USUARIO IS 'Ultimo usuario que hace cambios en la tabla';
--/////////////////////
COMMENT ON TABLE TBEP_MERITOS_EXCLUYENTES IS 'Mérito Excluyentes. ALIAS: [bepmex] ACRONIMO: [MEX]';
--/////////////////////
CREATE TABLE TBEP_HTO_MERITOS_EXCLUYENTES (
 	CODCAMBIO NUMBER(11,0) CONSTRAINT RBEP_NMEX_HTO_CODCAMBIO NOT NULL, 
 	LOG VARCHAR(50) CONSTRAINT RBEP_NMEX_HTO_LOG NOT NULL, 
 	FECHALOG TIMESTAMP DEFAULT CURRENT_TIMESTAMP CONSTRAINT RBEP_NMEX_HTO_FECHALOG NOT NULL, 
	CODNUM NUMBER(11,0) CONSTRAINT RBEP_NMEX_HTO_CODNUM NOT NULL, 
  	BEPITE_CODNUM_PADRE NUMBER(11,0) CONSTRAINT RBEP_NMEX_HTO_BEPITE_CODPAD NOT NULL, 
	BEPITE_CODNUM_HIJO NUMBER(11,0) CONSTRAINT RBEP_NMEX_HTO_BEPITE_CODHIJ NOT NULL, 
	UID_USUARIO VARCHAR2(100) CONSTRAINT RBEP_NMEX_HTO_UIDUSUARIO NOT NULL,
	CONSTRAINT IBEP_PMEX_HISTORICO PRIMARY KEY (CODCAMBIO)
);
--/////////////////////
CREATE SEQUENCE QBEP_MEX START WITH 1;
--/////////////////////
CREATE SEQUENCE QBEP_HTO_MEX START WITH 1;
--/////////////////////
CREATE TRIGGER DBEP_MEX_BRI
BEFORE INSERT
ON TBEP_MERITOS_EXCLUYENTES
FOR EACH ROW
DECLARE
BEGIN
    SELECT QBEP_MEX.nextval into :new.CODNUM FROM dual;

    INSERT INTO TBEP_HTO_MERITOS_EXCLUYENTES (CODCAMBIO,LOG,CODNUM,BEPITE_CODNUM_PADRE,BEPITE_CODNUM_HIJO,UID_USUARIO)
    VALUES (QBEP_HTO_MEX.NEXTVAL,'AFTER_INSERT',:New.CODNUM,:New.BEPITE_CODNUM_PADRE,:New.BEPITE_CODNUM_HIJO,:New.UID_USUARIO);
END DBEP_MEX_BRI;
--/////////////////////
CREATE TRIGGER DBEP_MEX_BRU
BEFORE UPDATE
ON TBEP_MERITOS_EXCLUYENTES 
FOR EACH ROW
DECLARE
BEGIN
	INSERT INTO TBEP_HTO_MERITOS_EXCLUYENTES (CODCAMBIO,LOG,CODNUM,BEPITE_CODNUM_PADRE,BEPITE_CODNUM_HIJO,UID_USUARIO)
    VALUES (QBEP_HTO_MEX.NEXTVAL,'BEFORE_UPDATE',:Old.CODNUM,:Old.BEPITE_CODNUM_PADRE,:Old.BEPITE_CODNUM_HIJO,:Old.UID_USUARIO);
      	  
    INSERT INTO TBEP_HTO_MERITOS_EXCLUYENTES (CODCAMBIO,LOG,CODNUM,BEPITE_CODNUM_PADRE,BEPITE_CODNUM_HIJO,UID_USUARIO)
    VALUES (QBEP_HTO_MEX.NEXTVAL,'AFTER_UPDATE',:New.CODNUM,:New.BEPITE_CODNUM_PADRE,:New.BEPITE_CODNUM_HIJO,:New.UID_USUARIO);
END DBEP_MEX_BRU;
--/////////////////////
CREATE TRIGGER DBEP_MEX_BRD
BEFORE DELETE
ON TBEP_MERITOS_EXCLUYENTES 
FOR EACH ROW
DECLARE
BEGIN
	INSERT INTO TBEP_HTO_MERITOS_EXCLUYENTES (CODCAMBIO,LOG,CODNUM,BEPITE_CODNUM_PADRE,BEPITE_CODNUM_HIJO,UID_USUARIO)
    VALUES (QBEP_HTO_MEX.NEXTVAL,'BEFORE_DELETE',:Old.CODNUM,:Old.BEPITE_CODNUM_PADRE,:Old.BEPITE_CODNUM_HIJO,:Old.UID_USUARIO);
END DBEP_MEX_BRD;
