CREATE TABLE TBEP_PARAMETROS_CONFIG (
    CODNUM NUMBER(11,0) CONSTRAINT RBEP_NPAC_CODNUM NOT NULL,
    NOMBRE VARCHAR2(100 CHAR) CONSTRAINT RBEP_NPAC_NOMBRE NOT NULL,
	VALOR VARCHAR2(500 CHAR) CONSTRAINT RBEP_NPAC_VALOR NOT NULL, 
	DESCRIPCION VARCHAR2(500 CHAR) DEFAULT NULL, 
    CONSTRAINT IBEP_PPAC PRIMARY KEY (CODNUM)
);
--/////////////////////
COMMENT ON COLUMN TBEP_PARAMETROS_CONFIG.NOMBRE IS 'Nombre del parámetro';
--/////////////////////
COMMENT ON COLUMN TBEP_PARAMETROS_CONFIG.VALOR IS 'Valor del parámetro de configuración';
--/////////////////////
COMMENT ON COLUMN TBEP_PARAMETROS_CONFIG.DESCRIPCION IS 'Información adicional del parámetro';
--/////////////////////
CREATE TABLE TBEP_HTO_PARAMETROS_CONFIG (
 	CODCAMBIO NUMBER(11,0) CONSTRAINT RBEP_NPAC_HTO_CODCAMBIO NOT NULL, 
 	LOG VARCHAR(50) CONSTRAINT RBEP_NPAC_HTO_LOG NOT NULL, 
 	FECHALOG TIMESTAMP DEFAULT CURRENT_TIMESTAMP CONSTRAINT RBEP_NPAC_HTO_FECHALOG NOT NULL, 
    CODNUM NUMBER(11,0) CONSTRAINT RBEP_NPAC_HTO_CODNUM NOT NULL,
    NOMBRE VARCHAR2(100 CHAR) CONSTRAINT RBEP_NPAC_HTO_NOMBRE NOT NULL,
	VALOR VARCHAR2(500 CHAR) CONSTRAINT RBEP_NPAC_HTO_VALOR NOT NULL, 
	DESCRIPCION VARCHAR2(500 CHAR) DEFAULT NULL, 
	CONSTRAINT IBEP_PPAC_HISTORICO PRIMARY KEY (CODCAMBIO)
);
--/////////////////////
CREATE SEQUENCE QBEP_PAC START WITH 1;
--/////////////////////
CREATE SEQUENCE QBEP_HTO_PAC START WITH 1;
--/////////////////////
CREATE TRIGGER DBEP_PAC_BRI
BEFORE INSERT
ON TBEP_PARAMETROS_CONFIG
FOR EACH ROW
DECLARE
BEGIN
    SELECT QBEP_PAC.nextval into :new.CODNUM FROM dual;

    INSERT INTO TBEP_HTO_PARAMETROS_CONFIG (CODCAMBIO,LOG,CODNUM,NOMBRE,VALOR,DESCRIPCION)
    VALUES (QBEP_HTO_PAC.NEXTVAL,'AFTER_INSERT',:New.CODNUM,:New.NOMBRE,:New.VALOR,:New.DESCRIPCION);
END DBEP_PAC_BRI;
--/////////////////////
CREATE TRIGGER DBEP_PAC_BRU
BEFORE UPDATE
ON TBEP_PARAMETROS_CONFIG
FOR EACH ROW
DECLARE
BEGIN
	INSERT INTO TBEP_HTO_PARAMETROS_CONFIG (CODCAMBIO,LOG,CODNUM,NOMBRE,VALOR,DESCRIPCION)
    VALUES (QBEP_HTO_PAC.NEXTVAL,'BEFORE_UPDATE',:Old.CODNUM,:Old.NOMBRE,:Old.VALOR,:Old.DESCRIPCION);
    
 	INSERT INTO TBEP_HTO_PARAMETROS_CONFIG (CODCAMBIO,LOG,CODNUM,NOMBRE,VALOR,DESCRIPCION)
    VALUES (QBEP_HTO_PAC.NEXTVAL,'AFTER_UPDATE',:New.CODNUM,:New.NOMBRE,:New.VALOR,:New.DESCRIPCION);
END DBEP_PAC_BRU;
--/////////////////////
CREATE TRIGGER DBEP_PAC_BRD
BEFORE DELETE
ON TBEP_PARAMETROS_CONFIG
FOR EACH ROW
DECLARE
BEGIN
	INSERT INTO TBEP_HTO_PARAMETROS_CONFIG (CODCAMBIO,LOG,CODNUM,NOMBRE,VALOR,DESCRIPCION)
    VALUES (QBEP_HTO_PAC.NEXTVAL,'BEFORE_DELETE',:Old.CODNUM,:Old.NOMBRE,:Old.VALOR,:Old.DESCRIPCION);
END DBEP_PAC_BRD;
