INSERT INTO UVIRTUAL.TBEP_MERITOS_PREFERENTES
(CODIGO, NOMBRE, OBSERVACIONES, TIPO, TIPO_CALCULO, APLICABLE, BASE, FACTOR, VALOR_MAXIMO, BEPITE_TIPO_CODNUM, BEPBLO_APLICABLE_CODNUM, BEPAPA_APLICABLE_CODNUM, BEPITE_APLICABLE_CODNUM, FLGACTIVO)
VALUES('1', 'Merito 1', 'Estar en posesión de alguna de las titulaciones preferentes de acceso a la plaza.', 'TITULACION_PREFERENTE', 'FACTOR', 'APARTADO', NULL, 1.5, NULL, NULL, NULL, 1, NULL, 'S');
INSERT INTO UVIRTUAL.TBEP_MERITOS_PREFERENTES
(CODIGO, NOMBRE, OBSERVACIONES, TIPO, TIPO_CALCULO, APLICABLE, BASE, FACTOR, VALOR_MAXIMO, BEPITE_TIPO_CODNUM, BEPBLO_APLICABLE_CODNUM, BEPAPA_APLICABLE_CODNUM, BEPITE_APLICABLE_CODNUM, FLGACTIVO)
VALUES('2', 'Merito 2','Haber cumplido el período de cuatro años de formación de personal investigador a que se refiere el art. 64 de la LAU (solo para las plazas de ayudante)', 'MERITO', 'FACTOR', 'APARTADO', NULL, 1.1, NULL, 15, NULL, 3, NULL, 'S');
INSERT INTO UVIRTUAL.TBEP_MERITOS_PREFERENTES
(CODIGO, NOMBRE, OBSERVACIONES, TIPO, TIPO_CALCULO, APLICABLE, BASE, FACTOR, VALOR_MAXIMO, BEPITE_TIPO_CODNUM, BEPBLO_APLICABLE_CODNUM, BEPAPA_APLICABLE_CODNUM, BEPITE_APLICABLE_CODNUM, FLGACTIVO)
VALUES('3', 'Merito 3','Estar acreditado como Profesor Colaborador', 'POSESION', 'FACTOR', 'TOTAL', NULL, 1.1, NULL, NULL, NULL, NULL, NULL, 'S');