INSERT INTO UVIRTUAL.TBEP_MERITOS_PREFERENTES
(CODNUM, DESCRIPCION, TIPO, TIPO_CALCULO, APLICABLE, FACTOR, VALOR_MAXIMO, BEPITE_TIPO_CODNUM, BEPBLO_APLICABLE_CODNUM, BEPAPA_APLICABLE_CODNUM, BEPITE_APLICABLE_CODNUM, FLGACTIVO)
VALUES(1, 'Estar en posesión de alguna de las titulaciones preferentes de acceso a la plaza.', 'TITULACION_PREFERENTE', 'FACTOR', 'APARTADO', '1.5', NULL, 1, 1, 1, 1, 'S');