CREATE TABLE TBEP_MER_PRE_USUARIO (    
    CODNUM NUMBER(11,0) CONSTRAINT RBEP_NMPU_CODNUM NOT NULL,
    BEPMEP_CODNUM NUMBER(11,0) CONSTRAINT RBEP_NMPU_BEPMEP_CODNUM NOT NULL,
    BEPUSU_CODNUM NUMBER(11,0) CONSTRAINT RBEP_NMPU_BEPUSU_CODNUM NOT NULL,
    BEPMPO_CODNUM NUMBER(11,0) DEFAULT NULL,
    DESCRIPCION VARCHAR2(250 CHAR) DEFAULT NULL,
    ARCHIVO BLOB CONSTRAINT RBEP_NMPU_ARCHIVO NOT NULL,
    FLGBORRADO CHAR(1) DEFAULT 'N',
    FECHA_BORRADO TIMESTAMP NULL,
    FLGVALIDADO CHAR(1) DEFAULT 'N',
    FECHA_VALIDADO TIMESTAMP NULL,
    CONSTRAINT IBEP_PMPU PRIMARY KEY (CODNUM),
    CONSTRAINT IBEP_FMPU_MEP FOREIGN KEY (BEPMEP_CODNUM) REFERENCES TBEP_MERITOS_PREFERENTES (CODNUM),
    CONSTRAINT IBEP_FMPU_USU FOREIGN KEY (BEPUSU_CODNUM) REFERENCES TBEP_USUARIOS (CODNUM),
    CONSTRAINT IBEP_FMPU_MOP FOREIGN KEY (BEPMPO_CODNUM) REFERENCES TBEP_MER_PRE_OPCIONES (CODNUM),
    CONSTRAINT RBEP_CMPU_FLGBORRADO CHECK(FLGBORRADO IN ('N','S')),
    CONSTRAINT RBEP_CMPU_FLGVALIDADA CHECK(FLGVALIDADO IN ('N','S'))    
);
--/////////////////////
COMMENT ON COLUMN TBEP_MER_PRE_USUARIO.BEPMEP_CODNUM IS 'Fk. a mérito preferente';
--/////////////////////
COMMENT ON COLUMN TBEP_MER_PRE_USUARIO.BEPUSU_CODNUM IS 'Fk. a usuario';
--/////////////////////
COMMENT ON COLUMN TBEP_MER_PRE_USUARIO.BEPMPO_CODNUM IS 'Fk. a la opción si existe';
--/////////////////////
COMMENT ON COLUMN TBEP_MER_PRE_USUARIO.DESCRIPCION IS 'Descripción del candidato al mérito preferente';
--/////////////////////
COMMENT ON COLUMN TBEP_MER_PRE_USUARIO.ARCHIVO IS 'Archivo pdf con el merito preferente';
--/////////////////////
COMMENT ON COLUMN TBEP_MER_PRE_USUARIO.FLGBORRADO IS 'Indica si está borrado';
--/////////////////////
COMMENT ON COLUMN TBEP_MER_PRE_USUARIO.FECHA_BORRADO IS 'Indica la fecha de borrado';
--/////////////////////
COMMENT ON COLUMN TBEP_MER_PRE_USUARIO.FLGVALIDADO IS 'Indica si está validado el mérito preferente';
--/////////////////////
COMMENT ON COLUMN TBEP_MER_PRE_USUARIO.FECHA_VALIDADO IS 'Fecha de validación';
--/////////////////////
COMMENT ON TABLE TBEP_MER_PRE_USUARIO IS 'Méritos preferentes usuario. ALIAS: [bepmpu] ACRONIMO: [MPU]';
--/////////////////////
CREATE TABLE TBEP_HTO_MER_PRE_USUARIO (
    CODCAMBIO NUMBER(11,0) CONSTRAINT RBEP_NMPU_HTO_CODCAMBIO NOT NULL, 
    LOG VARCHAR(50) CONSTRAINT RBEP_NMPU_HTO_LOG NOT NULL, 
    FECHALOG TIMESTAMP DEFAULT CURRENT_TIMESTAMP CONSTRAINT RBEP_NMPU_HTO_FECHALOG NOT NULL, 
    CODNUM NUMBER(11,0) CONSTRAINT RBEP_NMPU_HTO_CODNUM NOT NULL,
    BEPMEP_CODNUM NUMBER(11,0) CONSTRAINT RBEP_NMPU_HTO_BEPMEP_CODNUM NOT NULL,
    BEPUSU_CODNUM NUMBER(11,0) CONSTRAINT RBEP_NMPU_HTO_BEPUSU_CODNUM NOT NULL,
    BEPMPO_CODNUM NUMBER(11,0) DEFAULT NULL,
    DESCRIPCION VARCHAR2(250 CHAR) DEFAULT NULL,
    ARCHIVO BLOB CONSTRAINT RBEP_NMPU_HTO_ARCHIVO NOT NULL,
    FLGBORRADO CHAR(1) DEFAULT 'N',
    FECHA_BORRADO TIMESTAMP NULL,
    FLGVALIDADO CHAR(1) DEFAULT 'N',
    FECHA_VALIDADO TIMESTAMP NULL,
    CONSTRAINT IBEP_PMPU_HTO PRIMARY KEY (CODCAMBIO)
);
--/////////////////////
CREATE SEQUENCE QBEP_MPU START WITH 1;
--/////////////////////
CREATE SEQUENCE QBEP_HTO_MPU START WITH 1;
--/////////////////////
CREATE TRIGGER DBEP_MPU_BRI
BEFORE INSERT
ON TBEP_MER_PRE_USUARIO
FOR EACH ROW
DECLARE
BEGIN
    SELECT QBEP_MPU.nextval into :new.CODNUM FROM dual;

    INSERT INTO TBEP_HTO_MER_PRE_USUARIO (CODCAMBIO,LOG,CODNUM,BEPMEP_CODNUM,BEPUSU_CODNUM,BEPMPO_CODNUM,DESCRIPCION,ARCHIVO,FLGBORRADO,FECHA_BORRADO,FLGVALIDADO,FECHA_VALIDADO)
    VALUES (QBEP_HTO_MPU.NEXTVAL,'AFTER_INSERT',:New.CODNUM,:New.BEPMEP_CODNUM,:New.BEPUSU_CODNUM,:New.BEPMPO_CODNUM,:New.DESCRIPCION,:New.ARCHIVO,:New.FLGBORRADO,:New.FECHA_BORRADO,:New.FLGVALIDADO,:New.FECHA_VALIDADO);
END DBEP_MPU_BRI;
--/////////////////////
CREATE TRIGGER DBEP_MPU_BRU
BEFORE UPDATE
ON TBEP_MER_PRE_USUARIO
FOR EACH ROW
DECLARE
BEGIN
    INSERT INTO TBEP_HTO_MER_PRE_USUARIO (CODCAMBIO,LOG,CODNUM,BEPMEP_CODNUM,BEPUSU_CODNUM,BEPMPO_CODNUM,DESCRIPCION,ARCHIVO,FLGBORRADO,FECHA_BORRADO,FLGVALIDADO,FECHA_VALIDADO)
    VALUES (QBEP_HTO_MPU.NEXTVAL,'BEFORE_UPDATE',:Old.CODNUM,:Old.BEPMEP_CODNUM,:Old.BEPUSU_CODNUM,:Old.BEPMPO_CODNUM,:Old.DESCRIPCION,:Old.ARCHIVO,:Old.FLGBORRADO,:Old.FECHA_BORRADO,:Old.FLGVALIDADO,:Old.FECHA_VALIDADO);
    
    INSERT INTO TBEP_HTO_MER_PRE_USUARIO (CODCAMBIO,LOG,CODNUM,BEPMEP_CODNUM,BEPUSU_CODNUM,BEPMPO_CODNUM,DESCRIPCION,ARCHIVO,FLGBORRADO,FECHA_BORRADO,FLGVALIDADO,FECHA_VALIDADO)
    VALUES (QBEP_HTO_MPU.NEXTVAL,'AFTER_UPDATE',:New.CODNUM,:New.BEPMEP_CODNUM,:New.BEPUSU_CODNUM,:New.BEPMPO_CODNUM,:New.DESCRIPCION,:New.ARCHIVO,:New.FLGBORRADO,:New.FECHA_BORRADO,:New.FLGVALIDADO,:New.FECHA_VALIDADO);
END DBEP_MPU_BRU;
--/////////////////////
CREATE TRIGGER DBEP_MPU_BRD
BEFORE DELETE
ON TBEP_MER_PRE_USUARIO
FOR EACH ROW
DECLARE
BEGIN
    INSERT INTO TBEP_HTO_MER_PRE_USUARIO (CODCAMBIO,LOG,CODNUM,BEPMEP_CODNUM,BEPUSU_CODNUM,BEPMPO_CODNUM,DESCRIPCION,ARCHIVO,FLGBORRADO,FECHA_BORRADO,FLGVALIDADO,FECHA_VALIDADO)
    VALUES (QBEP_HTO_MPU.NEXTVAL,'BEFORE_DELETE',:Old.CODNUM,:Old.BEPMEP_CODNUM,:Old.BEPUSU_CODNUM,:Old.BEPMPO_CODNUM,:Old.DESCRIPCION,:Old.ARCHIVO,:Old.FLGBORRADO,:Old.FECHA_BORRADO,:Old.FLGVALIDADO,:Old.FECHA_VALIDADO);
END DBEP_MPU_BRD;