CREATE TABLE TBEP_MENSAJES (
    CODNUM NUMBER(11,0) CONSTRAINT RBEP_NMEN_CODNUM NOT NULL, 
    TITULO VARCHAR2(500) CONSTRAINT RBEP_NMEN_TITULO NOT NULL, 
    CUERPO CLOB CONSTRAINT RBEP_NMEN_DESCRIPCION NOT NULL, 
    FECHA_CREACION TIMESTAMP CONSTRAINT RBEP_NMEN_FECHA_CREACION NOT NULL, 
    ESTADO CHAR(8) DEFAULT 'BORRADOR',
    UID_USUARIO VARCHAR2(100) CONSTRAINT RBEP_NMEN_UID_USUARIO NOT NULL,
    CONSTRAINT IBEP_PMEN PRIMARY KEY (CODNUM),    
    CONSTRAINT RBEP_CMEN_ESTADO CHECK(ESTADO IN ('BORRADOR','ENVIADO'))
);
--/////////////////////
COMMENT ON COLUMN TBEP_MENSAJES.TITULO IS 'Título del mensaje';
--/////////////////////
COMMENT ON COLUMN TBEP_MENSAJES.CUERPO IS 'Cuerpo del mensaje';
--/////////////////////
COMMENT ON COLUMN TBEP_MENSAJES.FECHA_CREACION IS 'Fecha de cración del mensaje';
--/////////////////////
COMMENT ON COLUMN TBEP_MENSAJES.ESTADO IS 'Estado del mensaje';
--/////////////////////
COMMENT ON TABLE TBEP_MENSAJES IS 'Mensajes. ALIAS: [bepmen] ACRONIMO: [MEN]';
--/////////////////////
CREATE TABLE TBEP_HTO_MENSAJES (
    CODCAMBIO NUMBER(11,0) CONSTRAINT RBEP_NMEN_HTO_CODCAMBIO NOT NULL, 
    LOG VARCHAR(50) CONSTRAINT RBEP_NMEN_HTO_LOG NOT NULL, 
    FECHALOG TIMESTAMP DEFAULT CURRENT_TIMESTAMP CONSTRAINT RBEP_NMEN_HTO_FECHALOG NOT NULL, 
    CODNUM NUMBER(11,0) CONSTRAINT RBEP_NMEN_HTO_CODNUM NOT NULL, 
    TITULO VARCHAR2(500) CONSTRAINT RBEP_NMEN_HTO_TITULO NOT NULL, 
    CUERPO CLOB CONSTRAINT RBEP_NMEN_HTO_DESCRIPCION NOT NULL, 
    FECHA_CREACION TIMESTAMP CONSTRAINT RBEP_NMEN_HTO_FECHA_CREACION NOT NULL, 
    ESTADO CHAR(8) DEFAULT 'BORRADOR',
    UID_USUARIO VARCHAR2(100) CONSTRAINT RBEP_NMEN_HTO_UID_USUARIO NOT NULL,
    CONSTRAINT IBEP_PMEN_HISTORICO PRIMARY KEY (CODCAMBIO)
);
--/////////////////////
CREATE SEQUENCE QBEP_MEN START WITH 1;
--/////////////////////
CREATE SEQUENCE QBEP_HTO_MEN START WITH 1;
--/////////////////////
CREATE TRIGGER DBEP_MEN_BRI
BEFORE INSERT
ON TBEP_MENSAJES
FOR EACH ROW
DECLARE
BEGIN
    SELECT QBEP_MEN.nextval into :new.CODNUM FROM dual;

    INSERT INTO TBEP_HTO_MENSAJES (CODCAMBIO,LOG,CODNUM,TITULO,CUERPO,FECHA_CREACION,ESTADO,UID_USUARIO)
    VALUES (QBEP_HTO_MEN.NEXTVAL,'AFTER_INSERT',:New.CODNUM,:New.TITULO,:New.CUERPO,:New.FECHA_CREACION,:New.ESTADO,:New.UID_USUARIO);
END DBEP_MEN_BRI;
--/////////////////////
CREATE TRIGGER DBEP_MEN_BRU
BEFORE UPDATE
ON TBEP_MENSAJES 
FOR EACH ROW
DECLARE
BEGIN
    INSERT INTO TBEP_HTO_MENSAJES (CODCAMBIO,LOG,CODNUM,TITULO,CUERPO,FECHA_CREACION,ESTADO,UID_USUARIO)
    VALUES (QBEP_HTO_MEN.NEXTVAL,'BEFORE_UPDATE',:Old.CODNUM,:Old.TITULO,:Old.CUERPO,:Old.FECHA_CREACION,:Old.ESTADO,:Old.UID_USUARIO);
          
    INSERT INTO TBEP_HTO_MENSAJES (CODCAMBIO,LOG,CODNUM,TITULO,CUERPO,FECHA_CREACION,ESTADO,UID_USUARIO)
    VALUES (QBEP_HTO_MEN.NEXTVAL,'AFTER_UPDATE',:New.CODNUM,:New.TITULO,:New.CUERPO,:New.FECHA_CREACION,:New.ESTADO,:New.UID_USUARIO);
END DBEP_MEN_BRU;
--/////////////////////
CREATE TRIGGER DBEP_MEN_BRD
BEFORE DELETE
ON TBEP_MENSAJES 
FOR EACH ROW
DECLARE
BEGIN
    INSERT INTO TBEP_HTO_MENSAJES (CODCAMBIO,LOG,CODNUM,TITULO,CUERPO,FECHA_CREACION,ESTADO,UID_USUARIO)
    VALUES (QBEP_HTO_MEN.NEXTVAL,'BEFORE_DELETE',:Old.CODNUM,:Old.TITULO,:Old.CUERPO,:Old.FECHA_CREACION,:Old.ESTADO,:Old.UID_USUARIO);
END DBEP_MEN_BRD;
