CREATE TABLE TBEP_MEN_DESTINATARIOS (
    CODNUM NUMBER(11,0) CONSTRAINT RBEP_NMDE_CODNUM NOT NULL, 
    BEPMEN_CODNUM NUMBER(11,0) CONSTRAINT RBEP_NMDE_BEPMEN_CODNUM NOT NULL,
    BEPUSU_CODNUM NUMBER(11,0) CONSTRAINT RBEP_NMDE_BEPUSU_CODNUM NOT NULL,
    CONSTRAINT IBEP_PMDE PRIMARY KEY (CODNUM), 
    CONSTRAINT IBEP_FMDE_MEN FOREIGN KEY (BEPMEN_CODNUM) REFERENCES TBEP_MENSAJES (CODNUM),
    CONSTRAINT IBEP_FMDE_USU FOREIGN KEY (BEPUSU_CODNUM) REFERENCES TBEP_USUARIOS (CODNUM)
);
--/////////////////////
COMMENT ON COLUMN TBEP_MEN_DESTINATARIOS.BEPMEN_CODNUM IS 'Fk. mensaje';
--/////////////////////
COMMENT ON COLUMN TBEP_MEN_DESTINATARIOS.BEPUSU_CODNUM IS 'Fk. usuario bolsa empleo';
--/////////////////////
COMMENT ON TABLE TBEP_MEN_DESTINATARIOS IS 'Destinatarios de un mensaje. ALIAS: [bepmde] ACRONIMO: [MDE]';
--/////////////////////
CREATE TABLE TBEP_HTO_MEN_DESTINATARIOS (
    CODCAMBIO NUMBER(11,0) CONSTRAINT RBEP_NMDE_HTO_CODCAMBIO NOT NULL, 
    LOG VARCHAR(50) CONSTRAINT RBEP_NMDE_HTO_LOG NOT NULL, 
    FECHALOG TIMESTAMP DEFAULT CURRENT_TIMESTAMP CONSTRAINT RBEP_NMDE_HTO_FECHALOG NOT NULL, 
    CODNUM NUMBER(11,0) CONSTRAINT RBEP_NMDE_HTO_CODNUM NOT NULL, 
    BEPMEN_CODNUM NUMBER(11,0) CONSTRAINT RBEP_NMDE_HTO_BEPMEN_CODNUM NOT NULL,
    BEPUSU_CODNUM NUMBER(11,0) CONSTRAINT RBEP_NMDE_HTO_BEPUSU_CODNUM NOT NULL,
    CONSTRAINT IBEP_PMDE_HISTORICO PRIMARY KEY (CODCAMBIO)
);
--/////////////////////
CREATE SEQUENCE QBEP_MDE START WITH 1;
--/////////////////////
CREATE SEQUENCE QBEP_HTO_MDE START WITH 1;
--/////////////////////
CREATE TRIGGER DBEP_MDE_BRI
BEFORE INSERT
ON TBEP_MEN_DESTINATARIOS
FOR EACH ROW
DECLARE
BEGIN
    SELECT QBEP_MDE.nextval into :new.CODNUM FROM dual;

    INSERT INTO TBEP_HTO_MEN_DESTINATARIOS (CODCAMBIO,LOG,CODNUM,BEPMEN_CODNUM,BEPUSU_CODNUM)
    VALUES (QBEP_HTO_MDE.NEXTVAL,'AFTER_INSERT',:New.CODNUM,:New.BEPMEN_CODNUM,:New.BEPUSU_CODNUM);
END DBEP_MDE_BRI;
--/////////////////////
CREATE TRIGGER DBEP_MDE_BRU
BEFORE UPDATE
ON TBEP_MEN_DESTINATARIOS 
FOR EACH ROW
DECLARE
BEGIN
    INSERT INTO TBEP_HTO_MEN_DESTINATARIOS (CODCAMBIO,LOG,CODNUM,BEPMEN_CODNUM,BEPUSU_CODNUM)
    VALUES (QBEP_HTO_MDE.NEXTVAL,'BEFORE_UPDATE',:Old.CODNUM,:Old.BEPMEN_CODNUM,:Old.BEPUSU_CODNUM);
          
    INSERT INTO TBEP_HTO_MEN_DESTINATARIOS (CODCAMBIO,LOG,CODNUM,BEPMEN_CODNUM,BEPUSU_CODNUM)
    VALUES (QBEP_HTO_MDE.NEXTVAL,'AFTER_UPDATE',:New.CODNUM,:New.BEPMEN_CODNUM,:New.BEPUSU_CODNUM);
END DBEP_MDE_BRU;
--/////////////////////
CREATE TRIGGER DBEP_MDE_BRD
BEFORE DELETE
ON TBEP_MEN_DESTINATARIOS 
FOR EACH ROW
DECLARE
BEGIN
    INSERT INTO TBEP_HTO_MEN_DESTINATARIOS (CODCAMBIO,LOG,CODNUM,BEPMEN_CODNUM,BEPUSU_CODNUM)
    VALUES (QBEP_HTO_MDE.NEXTVAL,'BEFORE_DELETE',:Old.CODNUM,:Old.BEPMEN_CODNUM,:Old.BEPUSU_CODNUM);
END DBEP_MDE_BRD;
