INSERT INTO adm_parametros (config_codalf, param_codalf, desid, valor) VALUES ( DEFAULT, 'bolsaempleo.urlAyuda', 'url que enlace a la ayuda ', 'https://www.ujaen.es/gobierno/secord/bolsaempleo-academia'); 
INSERT INTO ADM_ROL (rol_codnum, descripcion, valor) VALUES(1050, 'Integrantes del Servicio de Personal', 'bolemppersonal');
INSERT INTO ADM_ROL (rol_codnum, descripcion, valor) VALUES(1051, 'Candidatos', 'bolempcandidato');
INSERT INTO ADM_ROL (rol_codnum, descripcion, valor) VALUES(1052, 'Director departamento', 'bolempdirdepartamento');
INSERT INTO ADM_ROL (rol_codnum, descripcion, valor) VALUES(1053, 'Equipos de valoración', 'bolempequipovaloracion');
INSERT INTO ADM_USUARIO_ROL (USERUID, ROL_CODNUM, FLG_ADMIN) VALUES ('usig', 1050, 'N');
INSERT INTO ADM_MENU (MNU_CODNUM, CONTROLADOR, FLG_DISPONIBLE, FLG_MOSTRAR, FLG_CREAMENU, FLG_PDFINTERNO, FLG_EXCEL, FLG_WORD, FLG_ANONIMO, PADRE_CODNUM, FLG_LOG) VALUES (999999, 'informacionadministrativa.bolsaempleo', 'S', 'S', 'S','N', 'N', 'N', 'N', 16, 'N');
INSERT INTO ADM_MENU_DOM (MNU_CODNUM, DOM_CODALF) VALUES (999999, 'ujaen.es');
INSERT INTO ADM_MENU_IDM (MNU_CODNUM, IDM_CODALF, DESCRIPCION) VALUES (999999, 'es', 'Bolsa empleo');
INSERT INTO ADM_MENU_SIS (MNU_CODNUM, SIS_CODALF) VALUES (999999, 'uvirtual');
INSERT INTO ADM_MENU_RED (MNU_CODNUM, RED, DESCRIPCION, FLG_DESACT) VALUES (999999, '0.0.0.0/0', 'Publico', 'N');
INSERT INTO ADM_MENU_ROL (MNU_CODNUM, ROL_CODNUM, FLG_DESACT, FLG_ADMIN) VALUES (999999, 1050, 'N', 'N');
INSERT INTO ADM_MENU_ROL (MNU_CODNUM, ROL_CODNUM, FLG_DESACT, FLG_ADMIN) VALUES (999999, 1051, 'N', 'N');
INSERT INTO ADM_MENU_ROL (MNU_CODNUM, ROL_CODNUM, FLG_DESACT, FLG_ADMIN) VALUES (999999, 1052, 'N', 'N');
INSERT INTO ADM_MENU_ROL (MNU_CODNUM, ROL_CODNUM, FLG_DESACT, FLG_ADMIN) VALUES (999999, 1053, 'N', 'N');