version: '3'
 
services:
  memcached:
    image: memcached:latest
    ports:
      - 11211:11211 

  oracledb:
    image: '${ORACLE_IMAGE}'
    environment:
      - ORACLE_PWD=pwd123
      - ORACLE_CHARACTERSET=WE8ISO8859P15
    ports:
      - 1521:1521 
      - 5500:5500
    volumes:
      - '${ORACLE_DATA}:/opt/oracle/oradata'
      - '${ORACLE_SCRIPTS_STARTUP}:/opt/oracle/scripts/startup'

  uvirtual:
    build: .
    depends_on:
      - memcached
      - oracledb
    environment:
      - TZ='CST'
      - SHOW="a"
      - dbUrl=oracledb
      - memcacheUrl=memcached
      - CATALINA_OPTS=-DdbUrl=oracledb -DmemcacheUrl=memcached
    ports:
      - 8888:8080
    entrypoint: ["/wait-for-it.sh","oracledb:1580","--timeout=0","--strict", "--", "catalina.sh", "run" ]
    links:
      - memcached
      - oracledb
