INSERT INTO ARCOS.VUJA_NET_BEP_AR_PERSONA (CODINT,STRTIPODOCUMENTO,IDNIF,LETRANIF,STRNOMBRE,STRAPELLIDO1,STRAPELLIDO2,EMAIL_ALTA)
VALUES (1,'DNI','12345678','A','USIG','USIGAPELLIDO1','USIGAPELLIDO2','usig@usig.com');
INSERT INTO ARCOS.VUJA_NET_BEP_AR_PERSONA (CODINT,STRTIPODOCUMENTO,IDNIF,LETRANIF,STRNOMBRE,STRAPELLIDO1,STRAPELLIDO2,EMAIL_ALTA)
VALUES (3,'DNI','12345678','P','Personal1','Personal1APELLIDO1','Personal1APELLIDO2','Personal1@Personal1.com');
INSERT INTO ARCOS.VUJA_NET_BEP_AR_PERSONA (CODINT,STRTIPODOCUMENTO,IDNIF,LETRANIF,STRNOMBRE,STRAPELLIDO1,STRAPELLIDO2,EMAIL_ALTA)
VALUES (4,'DNI','22345678','P','Personal2','Personal2APELLIDO1','Personal2APELLIDO2','Personal2@Personal1.com');
INSERT INTO ARCOS.VUJA_NET_BEP_AR_PERSONA (CODINT,STRTIPODOCUMENTO,IDNIF,LETRANIF,STRNOMBRE,STRAPELLIDO1,STRAPELLIDO2,EMAIL_ALTA)
VALUES (5,'DNI','32345678','P','Personal3','Personal3APELLIDO1','Personal3APELLIDO2','Personal3@Personal1.com');
INSERT INTO ARCOS.VUJA_NET_BEP_AR_PERSONA (CODINT,STRTIPODOCUMENTO,IDNIF,LETRANIF,STRNOMBRE,STRAPELLIDO1,STRAPELLIDO2,EMAIL_ALTA)
VALUES (6,'DNI','42345678','P','Personal4','Personal4APELLIDO1','Personal4APELLIDO2','Personal4@Personal1.com');
INSERT INTO ARCOS.VUJA_NET_BEP_AR_PERSONA (CODINT,STRTIPODOCUMENTO,IDNIF,LETRANIF,STRNOMBRE,STRAPELLIDO1,STRAPELLIDO2,EMAIL_ALTA)
VALUES (7,'DNI','52345678','P','Personal5','Personal5APELLIDO1','Personal5APELLIDO2','Personal5@Personal1.com');


INSERT INTO ARCOS.VUJA_NET_BEP_AR_PERSONA (CODINT,STRTIPODOCUMENTO,IDNIF,LETRANIF,STRNOMBRE,STRAPELLIDO1,STRAPELLIDO2,EMAIL_ALTA)
VALUES (8,'DNI','12345678','B','Comision1','Comision1APELLIDO1','Comision1APELLIDO2','Comision1@Comision1.com');
INSERT INTO ARCOS.VUJA_NET_BEP_AR_PERSONA (CODINT,STRTIPODOCUMENTO,IDNIF,LETRANIF,STRNOMBRE,STRAPELLIDO1,STRAPELLIDO2,EMAIL_ALTA)
VALUES (9,'DNI','22345678','B','Comision2','Comision2APELLIDO1','Comision2APELLIDO2','Comision2@Comision1.com');
INSERT INTO ARCOS.VUJA_NET_BEP_AR_PERSONA (CODINT,STRTIPODOCUMENTO,IDNIF,LETRANIF,STRNOMBRE,STRAPELLIDO1,STRAPELLIDO2,EMAIL_ALTA)
VALUES (10,'DNI','32345678','B','Comision3','Comision3APELLIDO1','Comision3APELLIDO2','Comision3@Comision1.com');
INSERT INTO ARCOS.VUJA_NET_BEP_AR_PERSONA (CODINT,STRTIPODOCUMENTO,IDNIF,LETRANIF,STRNOMBRE,STRAPELLIDO1,STRAPELLIDO2,EMAIL_ALTA)
VALUES (11,'DNI','42345678','B','Comision4','Comision4APELLIDO1','Comision4APELLIDO2','Comision4@Comision1.com');
INSERT INTO ARCOS.VUJA_NET_BEP_AR_PERSONA (CODINT,STRTIPODOCUMENTO,IDNIF,LETRANIF,STRNOMBRE,STRAPELLIDO1,STRAPELLIDO2,EMAIL_ALTA)
VALUES (12,'DNI','52345678','B','Comision5','Comision5APELLIDO1','Comision5APELLIDO2','Comision5@Comision1.com');


INSERT INTO ARCOS.VUJA_NET_BEP_AR_PERSONA (CODINT,STRTIPODOCUMENTO,IDNIF,LETRANIF,STRNOMBRE,STRAPELLIDO1,STRAPELLIDO2,EMAIL_ALTA)
VALUES (13,'DNI','52345678','C','Candidato1','Candidato1APELLIDO1','Candidato1APELLIDO2','Candidato1@Comision1.com');
INSERT INTO ARCOS.VUJA_NET_BEP_AR_PERSONA (CODINT,STRTIPODOCUMENTO,IDNIF,LETRANIF,STRNOMBRE,STRAPELLIDO1,STRAPELLIDO2,EMAIL_ALTA)
VALUES (14,'DNI','52345678','C','Candidato2','Candidato2APELLIDO1','Candidato2APELLIDO2','Candidato2@Comision1.com');
INSERT INTO ARCOS.VUJA_NET_BEP_AR_PERSONA (CODINT,STRTIPODOCUMENTO,IDNIF,LETRANIF,STRNOMBRE,STRAPELLIDO1,STRAPELLIDO2,EMAIL_ALTA)
VALUES (15,'DNI','52345678','C','Candidato3','Candidato3APELLIDO1','Candidato3APELLIDO2','Candidato3@Comision1.com');
INSERT INTO ARCOS.VUJA_NET_BEP_AR_PERSONA (CODINT,STRTIPODOCUMENTO,IDNIF,LETRANIF,STRNOMBRE,STRAPELLIDO1,STRAPELLIDO2,EMAIL_ALTA)
VALUES (16,'DNI','52345678','C','Candidato4','Candidato4APELLIDO1','Candidato4APELLIDO2','Candidato4@Comision1.com');
INSERT INTO ARCOS.VUJA_NET_BEP_AR_PERSONA (CODINT,STRTIPODOCUMENTO,IDNIF,LETRANIF,STRNOMBRE,STRAPELLIDO1,STRAPELLIDO2,EMAIL_ALTA)
VALUES (17,'DNI','52345678','C','Candidato5','Candidato5APELLIDO1','Candidato5APELLIDO2','Candidato5@Comision1.com');
INSERT INTO ARCOS.VUJA_NET_BEP_AR_PERSONA (CODINT,STRTIPODOCUMENTO,IDNIF,LETRANIF,STRNOMBRE,STRAPELLIDO1,STRAPELLIDO2,EMAIL_ALTA)
VALUES (18,'DNI','52345678','C','Candidato6','Candidato6APELLIDO1','Candidato6APELLIDO2','Candidato6@Comision1.com');
INSERT INTO ARCOS.VUJA_NET_BEP_AR_PERSONA (CODINT,STRTIPODOCUMENTO,IDNIF,LETRANIF,STRNOMBRE,STRAPELLIDO1,STRAPELLIDO2,EMAIL_ALTA)
VALUES (19,'DNI','52345678','C','Candidato7','Candidato7APELLIDO1','Candidato7APELLIDO2','Candidato7@Comision1.com');
INSERT INTO ARCOS.VUJA_NET_BEP_AR_PERSONA (CODINT,STRTIPODOCUMENTO,IDNIF,LETRANIF,STRNOMBRE,STRAPELLIDO1,STRAPELLIDO2,EMAIL_ALTA)
VALUES (20,'DNI','52345678','C','Candidato8','Candidato8APELLIDO1','Candidato8APELLIDO2','Candidato8@Comision1.com');
INSERT INTO ARCOS.VUJA_NET_BEP_AR_PERSONA (CODINT,STRTIPODOCUMENTO,IDNIF,LETRANIF,STRNOMBRE,STRAPELLIDO1,STRAPELLIDO2,EMAIL_ALTA)
VALUES (21,'DNI','52345678','C','Candidato9','Candidato9APELLIDO1','Candidato9APELLIDO2','Candidato9@Comision1.com');
INSERT INTO ARCOS.VUJA_NET_BEP_AR_PERSONA (CODINT,STRTIPODOCUMENTO,IDNIF,LETRANIF,STRNOMBRE,STRAPELLIDO1,STRAPELLIDO2,EMAIL_ALTA)
VALUES (22,'DNI','52345678','C','Candidato10','Candidato10APELLIDO1','Candidato10APELLIDO2','Candidato10@Comision1.com');

INSERT INTO ARCOS.VUJA_NET_BEP_AR_PERSONA (CODINT,STRTIPODOCUMENTO,IDNIF,LETRANIF,STRNOMBRE,STRAPELLIDO1,STRAPELLIDO2,EMAIL_ALTA)
VALUES (23,'DNI','52345678','C','Pruebas1','Pruebas1APELLIDO1','Pruebas1APELLIDO2','Pruebas1@Pruebas1.com');
INSERT INTO ARCOS.VUJA_NET_BEP_AR_PERSONA (CODINT,STRTIPODOCUMENTO,IDNIF,LETRANIF,STRNOMBRE,STRAPELLIDO1,STRAPELLIDO2,EMAIL_ALTA)
VALUES (24,'DNI','52345678','C','Pruebas2','Pruebas2APELLIDO1','Pruebas2APELLIDO2','Pruebas1@Pruebas1.com');

INSERT INTO ARCOS.VUJA_NET_BEP_AR_PERSONA (CODINT,STRTIPODOCUMENTO,IDNIF,LETRANIF,STRNOMBRE,STRAPELLIDO1,STRAPELLIDO2,EMAIL_ALTA)
VALUES (25,'DNI','52345678','C','Director1','apellido1','apellido1','director1@director1.com');
INSERT INTO ARCOS.VUJA_NET_BEP_AR_PERSONA (CODINT,STRTIPODOCUMENTO,IDNIF,LETRANIF,STRNOMBRE,STRAPELLIDO1,STRAPELLIDO2,EMAIL_ALTA)
VALUES (26,'DNI','52345678','C','Director2','apellido2','apellido2','director2@director2.com');

/*NO TOCAR NI ASOCIAR*/
INSERT INTO ARCOS.VUJA_NET_BEP_AR_PERSONA (CODINT,STRTIPODOCUMENTO,IDNIF,LETRANIF,STRNOMBRE,STRAPELLIDO1,STRAPELLIDO2,EMAIL_ALTA)
VALUES (100,'NIF','11111111','C','TEST','TESTAPELLIDO1','TESTAPELLIDO2','test@test.com');