INSERT INTO ARCOS.VUJA_NET_BEP_AR_PERSONA (CODINT,STRTIPODOCUMENTO,IDNIF,LETRANIF,PRSNIF,STRNOMBRE,STRAPELLIDO1,STRAPELLIDO2,EMAIL_ALTA,SEXO)
VALUES (1,'DNI','04269173','M','04269173M','USIG','USIGAPELLIDO1','USIGAPELLIDO2','usig@usig.com','V');
INSERT INTO ARCOS.VUJA_NET_BEP_AR_PERSONA (CODINT,STRTIPODOCUMENTO,IDNIF,LETRANIF,PRSNIF,STRNOMBRE,STRAPELLIDO1,STRAPELLIDO2,EMAIL_ALTA,SEXO)
VALUES (3,'DNI','62607992','Z','62607992Z','Personal1','Personal1APELLIDO1','Personal1APELLIDO2','Personal1@Personal1.com','M');
INSERT INTO ARCOS.VUJA_NET_BEP_AR_PERSONA (CODINT,STRTIPODOCUMENTO,IDNIF,LETRANIF,PRSNIF,STRNOMBRE,STRAPELLIDO1,STRAPELLIDO2,EMAIL_ALTA,SEXO)
VALUES (4,'DNI','73177876','H','73177876H','Personal2','Personal2APELLIDO1','Personal2APELLIDO2','Personal2@Personal1.com','V');
INSERT INTO ARCOS.VUJA_NET_BEP_AR_PERSONA (CODINT,STRTIPODOCUMENTO,IDNIF,LETRANIF,PRSNIF,STRNOMBRE,STRAPELLIDO1,STRAPELLIDO2,EMAIL_ALTA,SEXO)
VALUES (5,'DNI','30731352','V','30731352V','Personal3','Personal3APELLIDO1','Personal3APELLIDO2','Personal3@Personal1.com','M');
INSERT INTO ARCOS.VUJA_NET_BEP_AR_PERSONA (CODINT,STRTIPODOCUMENTO,IDNIF,LETRANIF,PRSNIF,STRNOMBRE,STRAPELLIDO1,STRAPELLIDO2,EMAIL_ALTA,SEXO)
VALUES (6,'DNI','12725260','G','12725260G','Personal4','Personal4APELLIDO1','Personal4APELLIDO2','Personal4@Personal1.com','V');
INSERT INTO ARCOS.VUJA_NET_BEP_AR_PERSONA (CODINT,STRTIPODOCUMENTO,IDNIF,LETRANIF,PRSNIF,STRNOMBRE,STRAPELLIDO1,STRAPELLIDO2,EMAIL_ALTA,SEXO)
VALUES (7,'DNI','19756896','B','19756896B','Personal5','Personal5APELLIDO1','Personal5APELLIDO2','Personal5@Personal1.com','M');

INSERT INTO ARCOS.VUJA_NET_BEP_AR_PERSONA (CODINT,STRTIPODOCUMENTO,IDNIF,LETRANIF,PRSNIF,STRNOMBRE,STRAPELLIDO1,STRAPELLIDO2,EMAIL_ALTA,SEXO)
VALUES (8,'DNI','36393760','D','36393760D','Comision1','Comision1APELLIDO1','Comision1APELLIDO2','Comision1@Comision1.com','V');
INSERT INTO ARCOS.VUJA_NET_BEP_AR_PERSONA (CODINT,STRTIPODOCUMENTO,IDNIF,LETRANIF,PRSNIF,STRNOMBRE,STRAPELLIDO1,STRAPELLIDO2,EMAIL_ALTA,SEXO)
VALUES (9,'DNI','29947958','A','29947958A','Comision2','Comision2APELLIDO1','Comision2APELLIDO2','Comision2@Comision1.com','M');
INSERT INTO ARCOS.VUJA_NET_BEP_AR_PERSONA (CODINT,STRTIPODOCUMENTO,IDNIF,LETRANIF,PRSNIF,STRNOMBRE,STRAPELLIDO1,STRAPELLIDO2,EMAIL_ALTA,SEXO)
VALUES (10,'DNI','95001060','C','95001060C','Comision3','Comision3APELLIDO1','Comision3APELLIDO2','Comision3@Comision1.com','V');
INSERT INTO ARCOS.VUJA_NET_BEP_AR_PERSONA (CODINT,STRTIPODOCUMENTO,IDNIF,LETRANIF,PRSNIF,STRNOMBRE,STRAPELLIDO1,STRAPELLIDO2,EMAIL_ALTA,SEXO)
VALUES (11,'DNI','78060443','F','78060443F','Comision4','Comision4APELLIDO1','Comision4APELLIDO2','Comision4@Comision1.com','M');
INSERT INTO ARCOS.VUJA_NET_BEP_AR_PERSONA (CODINT,STRTIPODOCUMENTO,IDNIF,LETRANIF,PRSNIF,STRNOMBRE,STRAPELLIDO1,STRAPELLIDO2,EMAIL_ALTA,SEXO)
VALUES (12,'DNI','51992686','J','51992686J','Comision5','Comision5APELLIDO1','Comision5APELLIDO2','Comision5@Comision1.com','V');

INSERT INTO ARCOS.VUJA_NET_BEP_AR_PERSONA (CODINT,STRTIPODOCUMENTO,IDNIF,LETRANIF,PRSNIF,STRNOMBRE,STRAPELLIDO1,STRAPELLIDO2,EMAIL_ALTA,SEXO)
VALUES (13,'DNI','43396488','L','43396488L','Candidato1','Candidato1APELLIDO1','Candidato1APELLIDO2','Candidato1@Comision1.com','M');
INSERT INTO ARCOS.VUJA_NET_BEP_AR_PERSONA (CODINT,STRTIPODOCUMENTO,IDNIF,LETRANIF,PRSNIF,STRNOMBRE,STRAPELLIDO1,STRAPELLIDO2,EMAIL_ALTA,SEXO)
VALUES (14,'DNI','91606989','J','91606989J','Candidato2','Candidato2APELLIDO1','Candidato2APELLIDO2','Candidato2@Comision1.com','V');
INSERT INTO ARCOS.VUJA_NET_BEP_AR_PERSONA (CODINT,STRTIPODOCUMENTO,IDNIF,LETRANIF,PRSNIF,STRNOMBRE,STRAPELLIDO1,STRAPELLIDO2,EMAIL_ALTA,SEXO)
VALUES (15,'DNI','51906000','Z','51906000Z','Candidato3','Candidato3APELLIDO1','Candidato3APELLIDO2','Candidato3@Comision1.com','M');
INSERT INTO ARCOS.VUJA_NET_BEP_AR_PERSONA (CODINT,STRTIPODOCUMENTO,IDNIF,LETRANIF,PRSNIF,STRNOMBRE,STRAPELLIDO1,STRAPELLIDO2,EMAIL_ALTA,SEXO)
VALUES (16,'DNI','00834172','P','00834172P','Candidato4','Candidato4APELLIDO1','Candidato4APELLIDO2','Candidato4@Comision1.com','V');
INSERT INTO ARCOS.VUJA_NET_BEP_AR_PERSONA (CODINT,STRTIPODOCUMENTO,IDNIF,LETRANIF,PRSNIF,STRNOMBRE,STRAPELLIDO1,STRAPELLIDO2,EMAIL_ALTA,SEXO)
VALUES (17,'DNI','37790895','D','37790895D','Candidato5','Candidato5APELLIDO1','Candidato5APELLIDO2','Candidato5@Comision1.com','M');
INSERT INTO ARCOS.VUJA_NET_BEP_AR_PERSONA (CODINT,STRTIPODOCUMENTO,IDNIF,LETRANIF,PRSNIF,STRNOMBRE,STRAPELLIDO1,STRAPELLIDO2,EMAIL_ALTA,SEXO)
VALUES (18,'DNI','29330022','P','29330022P','Candidato6','Candidato6APELLIDO1','Candidato6APELLIDO2','Candidato6@Comision1.com','V');
INSERT INTO ARCOS.VUJA_NET_BEP_AR_PERSONA (CODINT,STRTIPODOCUMENTO,IDNIF,LETRANIF,PRSNIF,STRNOMBRE,STRAPELLIDO1,STRAPELLIDO2,EMAIL_ALTA,SEXO)
VALUES (19,'DNI','37270880','R','37270880R','Candidato7','Candidato7APELLIDO1','Candidato7APELLIDO2','Candidato7@Comision1.com','M');
INSERT INTO ARCOS.VUJA_NET_BEP_AR_PERSONA (CODINT,STRTIPODOCUMENTO,IDNIF,LETRANIF,PRSNIF,STRNOMBRE,STRAPELLIDO1,STRAPELLIDO2,EMAIL_ALTA,SEXO)
VALUES (20,'DNI','45538940','K','45538940K','Candidato8','Candidato8APELLIDO1','Candidato8APELLIDO2','Candidato8@Comision1.com','V');
INSERT INTO ARCOS.VUJA_NET_BEP_AR_PERSONA (CODINT,STRTIPODOCUMENTO,IDNIF,LETRANIF,PRSNIF,STRNOMBRE,STRAPELLIDO1,STRAPELLIDO2,EMAIL_ALTA,SEXO)
VALUES (21,'DNI','69420803','H','69420803H','Candidato9','Candidato9APELLIDO1','Candidato9APELLIDO2','Candidato9@Comision1.com','M');
INSERT INTO ARCOS.VUJA_NET_BEP_AR_PERSONA (CODINT,STRTIPODOCUMENTO,IDNIF,LETRANIF,PRSNIF,STRNOMBRE,STRAPELLIDO1,STRAPELLIDO2,EMAIL_ALTA,SEXO)
VALUES (22,'DNI','33530756','E','33530756E','Candidato10','Candidato10APELLIDO1','Candidato10APELLIDO2','Candidato10@Comision1.com','V');

INSERT INTO ARCOS.VUJA_NET_BEP_AR_PERSONA (CODINT,STRTIPODOCUMENTO,IDNIF,LETRANIF,PRSNIF,STRNOMBRE,STRAPELLIDO1,STRAPELLIDO2,EMAIL_ALTA,SEXO)
VALUES (23,'DNI','67995554','X','67995554X','Pruebas1','Pruebas1APELLIDO1','Pruebas1APELLIDO2','Pruebas1@Pruebas1.com','M');
INSERT INTO ARCOS.VUJA_NET_BEP_AR_PERSONA (CODINT,STRTIPODOCUMENTO,IDNIF,LETRANIF,PRSNIF,STRNOMBRE,STRAPELLIDO1,STRAPELLIDO2,EMAIL_ALTA,SEXO)
VALUES (24,'DNI','50677767','G','50677767G','Pruebas2','Pruebas2APELLIDO1','Pruebas2APELLIDO2','Pruebas1@Pruebas1.com','V');

INSERT INTO ARCOS.VUJA_NET_BEP_AR_PERSONA (CODINT,STRTIPODOCUMENTO,IDNIF,LETRANIF,PRSNIF,STRNOMBRE,STRAPELLIDO1,STRAPELLIDO2,EMAIL_ALTA,SEXO)
VALUES (25,'DNI','03465896','A','03465896A','Director1','apellido1','apellido1','director1@director1.com','M');
INSERT INTO ARCOS.VUJA_NET_BEP_AR_PERSONA (CODINT,STRTIPODOCUMENTO,IDNIF,LETRANIF,PRSNIF,STRNOMBRE,STRAPELLIDO1,STRAPELLIDO2,EMAIL_ALTA,SEXO)
VALUES (26,'DNI','38389405','J','38389405J','Director2','apellido2','apellido2','director2@director2.com','V');

/*NO TOCAR NI ASOCIAR*/
INSERT INTO ARCOS.VUJA_NET_BEP_AR_PERSONA (CODINT,STRTIPODOCUMENTO,IDNIF,LETRANIF,PRSNIF,STRNOMBRE,STRAPELLIDO1,STRAPELLIDO2,EMAIL_ALTA,SEXO)
VALUES (100,'NIF','45257820','F','45257820F','TEST','TESTAPELLIDO1','TESTAPELLIDO2','test@test.com','M');