INSERT INTO ARCOS.VUJA_NET_BEP_AR_PERSONA (CODINT,STRTIPODOCUMENTO,IDNIF,LETRANIF,PRSNIF,STRNOMBRE,STRAPELLIDO1,STRAPELLIDO2,EMAIL_ALTA)
VALUES (1,'DNI','04269173','M','04269173M','USIG','Apellido1','Apellido2','usig@usig.com');
INSERT INTO ARCOS.VUJA_NET_BEP_AR_PERSONA (CODINT,STRTIPODOCUMENTO,IDNIF,LETRANIF,PRSNIF,STRNOMBRE,STRAPELLIDO1,STRAPELLIDO2,EMAIL_ALTA)
VALUES (3,'DNI','62607992','Z','62607992Z','Personal1','Apellido1','Apellido2','Personal1@Personal1.com');
INSERT INTO ARCOS.VUJA_NET_BEP_AR_PERSONA (CODINT,STRTIPODOCUMENTO,IDNIF,LETRANIF,PRSNIF,STRNOMBRE,STRAPELLIDO1,STRAPELLIDO2,EMAIL_ALTA)
VALUES (4,'DNI','73177876','H','73177876H','Personal2','Apellido1','Apellido2','Personal2@Personal1.com');
INSERT INTO ARCOS.VUJA_NET_BEP_AR_PERSONA (CODINT,STRTIPODOCUMENTO,IDNIF,LETRANIF,PRSNIF,STRNOMBRE,STRAPELLIDO1,STRAPELLIDO2,EMAIL_ALTA)
VALUES (5,'DNI','30731352','V','30731352V','Personal3','Apellido1','Apellido2','Personal3@Personal1.com');
INSERT INTO ARCOS.VUJA_NET_BEP_AR_PERSONA (CODINT,STRTIPODOCUMENTO,IDNIF,LETRANIF,PRSNIF,STRNOMBRE,STRAPELLIDO1,STRAPELLIDO2,EMAIL_ALTA)
VALUES (6,'DNI','12725260','G','12725260G','Personal4','Apellido1','Apellido2','Personal4@Personal1.com');
INSERT INTO ARCOS.VUJA_NET_BEP_AR_PERSONA (CODINT,STRTIPODOCUMENTO,IDNIF,LETRANIF,PRSNIF,STRNOMBRE,STRAPELLIDO1,STRAPELLIDO2,EMAIL_ALTA)
VALUES (7,'DNI','19756896','B','19756896B','Personal5','Apellido1','Apellido2','Personal5@Personal1.com');

INSERT INTO ARCOS.VUJA_NET_BEP_AR_PERSONA (CODINT,STRTIPODOCUMENTO,IDNIF,LETRANIF,PRSNIF,STRNOMBRE,STRAPELLIDO1,STRAPELLIDO2,EMAIL_ALTA)
VALUES (8,'DNI','36393760','D','36393760D','Comision1','Apellido1','Apellido2','Comision1@Comision1.com');
INSERT INTO ARCOS.VUJA_NET_BEP_AR_PERSONA (CODINT,STRTIPODOCUMENTO,IDNIF,LETRANIF,PRSNIF,STRNOMBRE,STRAPELLIDO1,STRAPELLIDO2,EMAIL_ALTA)
VALUES (9,'DNI','29947958','A','29947958A','Comision2','Apellido1','Apellido2','Comision2@Comision1.com');
INSERT INTO ARCOS.VUJA_NET_BEP_AR_PERSONA (CODINT,STRTIPODOCUMENTO,IDNIF,LETRANIF,PRSNIF,STRNOMBRE,STRAPELLIDO1,STRAPELLIDO2,EMAIL_ALTA)
VALUES (10,'DNI','95001060','C','95001060C','Comision3','Apellido1','Apellido2','Comision3@Comision1.com');
INSERT INTO ARCOS.VUJA_NET_BEP_AR_PERSONA (CODINT,STRTIPODOCUMENTO,IDNIF,LETRANIF,PRSNIF,STRNOMBRE,STRAPELLIDO1,STRAPELLIDO2,EMAIL_ALTA)
VALUES (11,'DNI','78060443','F','78060443F','Comision4','Apellido1','Apellido2','Comision4@Comision1.com');
INSERT INTO ARCOS.VUJA_NET_BEP_AR_PERSONA (CODINT,STRTIPODOCUMENTO,IDNIF,LETRANIF,PRSNIF,STRNOMBRE,STRAPELLIDO1,STRAPELLIDO2,EMAIL_ALTA)
VALUES (12,'DNI','51992686','J','51992686J','Comision5','Apellido1','Apellido2','Comision5@Comision1.com');

INSERT INTO ARCOS.VUJA_NET_BEP_AR_PERSONA (CODINT,STRTIPODOCUMENTO,IDNIF,LETRANIF,PRSNIF,STRNOMBRE,STRAPELLIDO1,STRAPELLIDO2,EMAIL_ALTA)
VALUES (13,'DNI','43396488','L','43396488L','Candidato1','Apellido1','Apellido2','Candidato1@Comision1.com');
INSERT INTO ARCOS.VUJA_NET_BEP_AR_PERSONA (CODINT,STRTIPODOCUMENTO,IDNIF,LETRANIF,PRSNIF,STRNOMBRE,STRAPELLIDO1,STRAPELLIDO2,EMAIL_ALTA)
VALUES (14,'DNI','91606989','J','91606989J','Candidato2','Apellido1','Apellido2','Candidato2@Comision1.com');
INSERT INTO ARCOS.VUJA_NET_BEP_AR_PERSONA (CODINT,STRTIPODOCUMENTO,IDNIF,LETRANIF,PRSNIF,STRNOMBRE,STRAPELLIDO1,STRAPELLIDO2,EMAIL_ALTA)
VALUES (15,'DNI','51906000','Z','51906000Z','Candidato3','Apellido1','Apellido2','Candidato3@Comision1.com');
INSERT INTO ARCOS.VUJA_NET_BEP_AR_PERSONA (CODINT,STRTIPODOCUMENTO,IDNIF,LETRANIF,PRSNIF,STRNOMBRE,STRAPELLIDO1,STRAPELLIDO2,EMAIL_ALTA)
VALUES (16,'DNI','00834172','P','00834172P','Candidato4','Apellido1','Apellido2','Candidato4@Comision1.com');
INSERT INTO ARCOS.VUJA_NET_BEP_AR_PERSONA (CODINT,STRTIPODOCUMENTO,IDNIF,LETRANIF,PRSNIF,STRNOMBRE,STRAPELLIDO1,STRAPELLIDO2,EMAIL_ALTA)
VALUES (17,'DNI','37790895','D','37790895D','Candidato5','Apellido1','Apellido2','Candidato5@Comision1.com');
INSERT INTO ARCOS.VUJA_NET_BEP_AR_PERSONA (CODINT,STRTIPODOCUMENTO,IDNIF,LETRANIF,PRSNIF,STRNOMBRE,STRAPELLIDO1,STRAPELLIDO2,EMAIL_ALTA)
VALUES (18,'DNI','29330022','P','29330022P','Candidato6','Apellido1','Apellido2','Candidato6@Comision1.com');
INSERT INTO ARCOS.VUJA_NET_BEP_AR_PERSONA (CODINT,STRTIPODOCUMENTO,IDNIF,LETRANIF,PRSNIF,STRNOMBRE,STRAPELLIDO1,STRAPELLIDO2,EMAIL_ALTA)
VALUES (19,'DNI','37270880','R','37270880R','Candidato7','Apellido1','Apellido2','Candidato7@Comision1.com');
INSERT INTO ARCOS.VUJA_NET_BEP_AR_PERSONA (CODINT,STRTIPODOCUMENTO,IDNIF,LETRANIF,PRSNIF,STRNOMBRE,STRAPELLIDO1,STRAPELLIDO2,EMAIL_ALTA)
VALUES (20,'DNI','45538940','K','45538940K','Candidato8','Apellido1','Apellido2','Candidato8@Comision1.com');
INSERT INTO ARCOS.VUJA_NET_BEP_AR_PERSONA (CODINT,STRTIPODOCUMENTO,IDNIF,LETRANIF,PRSNIF,STRNOMBRE,STRAPELLIDO1,STRAPELLIDO2,EMAIL_ALTA)
VALUES (21,'DNI','69420803','H','69420803H','Candidato9','Apellido1','Apellido2','Candidato9@Comision1.com');
INSERT INTO ARCOS.VUJA_NET_BEP_AR_PERSONA (CODINT,STRTIPODOCUMENTO,IDNIF,LETRANIF,PRSNIF,STRNOMBRE,STRAPELLIDO1,STRAPELLIDO2,EMAIL_ALTA)
VALUES (22,'DNI','33530756','E','33530756E','Candidato10','Apellido1','Apellido2','Candidato10@Comision1.com');

INSERT INTO ARCOS.VUJA_NET_BEP_AR_PERSONA (CODINT,STRTIPODOCUMENTO,IDNIF,LETRANIF,PRSNIF,STRNOMBRE,STRAPELLIDO1,STRAPELLIDO2,EMAIL_ALTA)
VALUES (23,'DNI','67995554','X','67995554X','Pruebas1','Apellido1','Apellido2','Pruebas1@Pruebas1.com');
INSERT INTO ARCOS.VUJA_NET_BEP_AR_PERSONA (CODINT,STRTIPODOCUMENTO,IDNIF,LETRANIF,PRSNIF,STRNOMBRE,STRAPELLIDO1,STRAPELLIDO2,EMAIL_ALTA)
VALUES (24,'DNI','50677767','G','50677767G','Pruebas2','Apellido1','Apellido2','Pruebas1@Pruebas1.com');

INSERT INTO ARCOS.VUJA_NET_BEP_AR_PERSONA (CODINT,STRTIPODOCUMENTO,IDNIF,LETRANIF,PRSNIF,STRNOMBRE,STRAPELLIDO1,STRAPELLIDO2,EMAIL_ALTA)
VALUES (25,'DNI','03465896','A','03465896A','Director1','Apellido1','Apellido1','director1@director1.com');
INSERT INTO ARCOS.VUJA_NET_BEP_AR_PERSONA (CODINT,STRTIPODOCUMENTO,IDNIF,LETRANIF,PRSNIF,STRNOMBRE,STRAPELLIDO1,STRAPELLIDO2,EMAIL_ALTA)
VALUES (26,'DNI','38389405','J','38389405J','Director2','Apellido2','Apellido2','director2@director2.com');

/*NO TOCAR NI ASOCIAR*/
INSERT INTO ARCOS.VUJA_NET_BEP_AR_PERSONA (CODINT,STRTIPODOCUMENTO,IDNIF,LETRANIF,PRSNIF,STRNOMBRE,STRAPELLIDO1,STRAPELLIDO2,EMAIL_ALTA)
VALUES (100,'NIF','45257820','F','45257820F','TEST','Apellido1','Apellido2','test@test.com');
INSERT INTO ARCOS.VUJA_NET_BEP_AR_PERSONA (CODINT,STRTIPODOCUMENTO,IDNIF,LETRANIF,PRSNIF,STRNOMBRE,STRAPELLIDO1,STRAPELLIDO2,EMAIL_ALTA)
VALUES (101,'NIF','11111222','Z','11111222Z','TESTTITULACION','Apellido1','Apellido2','test@testtitulacion.com');
