INSERT INTO ARCOS.V_PERSONA_INTRANET (CODINT, UJAENDNI, NUMDOCUMENTO, STRTIPODOCUMENTO, STRNOMBRE, STRAPELLIDO1, STRAPELLIDO2, SEXO, COD_PERSONA_AC, COD_PERSONA_RH, BLNMANUAL) 
Values (3, '12345678', '62607992Z', 'DNI', 'Personal1', 'Usuario de', 'personal1', 'V', 3, 3, 'S');
INSERT INTO ARCOS.V_CUENTAS_INTRANET (IDCUENTA, IDIDENTIFICADOR, STRDN, CODINT, IDDOMINIO, BLNBLOQUEADA, BLNCTAGGL, BLNCTAGGLSUSP, BLNINSTITUCIONAL, STRDESCRIPCION, STRCORREORUTA)
Values (3, 'personal1', 'uid=personal1,cn=users,dc=ujaen,dc=es', 3, 'ujaen.es',  'N', 'N', 'N', 'N', 'Usuario de personal, personal1', 'personal1@xxx');
INSERT INTO ARCOS.V_PERSONA_INTRANET (CODINT, UJAENDNI, NUMDOCUMENTO, STRTIPODOCUMENTO, STRNOMBRE, STRAPELLIDO1, STRAPELLIDO2, SEXO, COD_PERSONA_AC, COD_PERSONA_RH, BLNMANUAL) 
Values (4, '12345678', '73177876H', 'DNI', 'Personal2', 'Usuario de', 'personal2', 'V', 4, 4, 'S');
INSERT INTO ARCOS.V_CUENTAS_INTRANET (IDCUENTA, IDIDENTIFICADOR, STRDN, CODINT, IDDOMINIO, BLNBLOQUEADA, BLNCTAGGL, BLNCTAGGLSUSP, BLNINSTITUCIONAL, STRDESCRIPCION, STRCORREORUTA)
Values (4, 'personal2', 'uid=personal2,cn=users,dc=ujaen,dc=es', 4, 'ujaen.es',  'N', 'N', 'N', 'N', 'Usuario de personal, personal2', 'personal2@xxx');
INSERT INTO ARCOS.V_PERSONA_INTRANET (CODINT, UJAENDNI, NUMDOCUMENTO, STRTIPODOCUMENTO, STRNOMBRE, STRAPELLIDO1, STRAPELLIDO2, SEXO, COD_PERSONA_AC, COD_PERSONA_RH, BLNMANUAL) 
Values (5, '12345678', '30731352V', 'DNI', 'Personal3', 'Usuario de', 'personal3', 'V', 5, 5, 'S');
INSERT INTO ARCOS.V_CUENTAS_INTRANET (IDCUENTA, IDIDENTIFICADOR, STRDN, CODINT, IDDOMINIO, BLNBLOQUEADA, BLNCTAGGL, BLNCTAGGLSUSP, BLNINSTITUCIONAL, STRDESCRIPCION, STRCORREORUTA)
Values (5, 'personal3', 'uid=personal3,cn=users,dc=ujaen,dc=es', 5, 'ujaen.es',  'N', 'N', 'N', 'N', 'Usuario de personal, personal3', 'personal3@xxx');
INSERT INTO ARCOS.V_PERSONA_INTRANET (CODINT, UJAENDNI, NUMDOCUMENTO, STRTIPODOCUMENTO, STRNOMBRE, STRAPELLIDO1, STRAPELLIDO2, SEXO, COD_PERSONA_AC, COD_PERSONA_RH, BLNMANUAL) 
Values (6, '12345678', '12725260G', 'DNI', 'Personal4', 'Usuario de', 'personal4', 'V', 6, 6, 'S');
INSERT INTO ARCOS.V_CUENTAS_INTRANET (IDCUENTA, IDIDENTIFICADOR, STRDN, CODINT, IDDOMINIO, BLNBLOQUEADA, BLNCTAGGL, BLNCTAGGLSUSP, BLNINSTITUCIONAL, STRDESCRIPCION, STRCORREORUTA)
Values (6, 'personal4', 'uid=personal4,cn=users,dc=ujaen,dc=es', 6, 'ujaen.es',  'N', 'N', 'N', 'N', 'Usuario de personal, personal4', 'personal4@xxx');
INSERT INTO ARCOS.V_PERSONA_INTRANET (CODINT, UJAENDNI, NUMDOCUMENTO, STRTIPODOCUMENTO, STRNOMBRE, STRAPELLIDO1, STRAPELLIDO2, SEXO, COD_PERSONA_AC, COD_PERSONA_RH, BLNMANUAL) 
Values (7, '12345678', '19756896B', 'DNI', 'Personal5', 'Usuario de', 'personal5', 'V', 7, 7, 'S');
INSERT INTO ARCOS.V_CUENTAS_INTRANET (IDCUENTA, IDIDENTIFICADOR, STRDN, CODINT, IDDOMINIO, BLNBLOQUEADA, BLNCTAGGL, BLNCTAGGLSUSP, BLNINSTITUCIONAL, STRDESCRIPCION, STRCORREORUTA)
Values (7, 'personal5', 'uid=personal5,cn=users,dc=ujaen,dc=es', 7, 'ujaen.es',  'N', 'N', 'N', 'N', 'Usuario de personal, personal5', 'personal5@xxx');


INSERT INTO ARCOS.V_PERSONA_INTRANET (CODINT, UJAENDNI, NUMDOCUMENTO, STRTIPODOCUMENTO, STRNOMBRE, STRAPELLIDO1, STRAPELLIDO2, SEXO, COD_PERSONA_AC, COD_PERSONA_RH, BLNMANUAL) 
Values (8, '12345678', '36393760D', 'DNI', 'Comision1', 'Usuario de', 'comision1', 'V', 8, 8, 'S');
INSERT INTO ARCOS.V_CUENTAS_INTRANET (IDCUENTA, IDIDENTIFICADOR, STRDN, CODINT, IDDOMINIO, BLNBLOQUEADA, BLNCTAGGL, BLNCTAGGLSUSP, BLNINSTITUCIONAL, STRDESCRIPCION, STRCORREORUTA)
Values (8, 'comision1', 'uid=comision1,cn=users,dc=ujaen,dc=es', 8, 'ujaen.es',  'N', 'N', 'N', 'N', 'Usuario de comision, comision1', 'comision1@xxx');
INSERT INTO ARCOS.V_PERSONA_INTRANET (CODINT, UJAENDNI, NUMDOCUMENTO, STRTIPODOCUMENTO, STRNOMBRE, STRAPELLIDO1, STRAPELLIDO2, SEXO, COD_PERSONA_AC, COD_PERSONA_RH, BLNMANUAL) 
Values (9, '12345678', '29947958A', 'DNI', 'Comision2', 'Usuario de', 'comision2', 'V', 9, 9, 'S');
INSERT INTO ARCOS.V_CUENTAS_INTRANET (IDCUENTA, IDIDENTIFICADOR, STRDN, CODINT, IDDOMINIO, BLNBLOQUEADA, BLNCTAGGL, BLNCTAGGLSUSP, BLNINSTITUCIONAL, STRDESCRIPCION, STRCORREORUTA)
Values (9, 'comision2', 'uid=comision2,cn=users,dc=ujaen,dc=es', 9, 'ujaen.es',  'N', 'N', 'N', 'N', 'Usuario de comision, comision2', 'comision2@xxx');
INSERT INTO ARCOS.V_PERSONA_INTRANET (CODINT, UJAENDNI, NUMDOCUMENTO, STRTIPODOCUMENTO, STRNOMBRE, STRAPELLIDO1, STRAPELLIDO2, SEXO, COD_PERSONA_AC, COD_PERSONA_RH, BLNMANUAL) 
Values (10, '12345678', '95001060C', 'DNI', 'Comision3', 'Usuario de', 'comision3', 'V', 10, 10, 'S');
INSERT INTO ARCOS.V_CUENTAS_INTRANET (IDCUENTA, IDIDENTIFICADOR, STRDN, CODINT, IDDOMINIO, BLNBLOQUEADA, BLNCTAGGL, BLNCTAGGLSUSP, BLNINSTITUCIONAL, STRDESCRIPCION, STRCORREORUTA)
Values (10, 'comision3', 'uid=comision3,cn=users,dc=ujaen,dc=es', 10, 'ujaen.es',  'N', 'N', 'N', 'N', 'Usuario de comision, comision3', 'comision3@xxx');
INSERT INTO ARCOS.V_PERSONA_INTRANET (CODINT, UJAENDNI, NUMDOCUMENTO, STRTIPODOCUMENTO, STRNOMBRE, STRAPELLIDO1, STRAPELLIDO2, SEXO, COD_PERSONA_AC, COD_PERSONA_RH, BLNMANUAL) 
Values (11, '12345678', '78060443F', 'DNI', 'Comision4', 'Usuario de', 'comision4', 'V', 11, 11, 'S');
INSERT INTO ARCOS.V_CUENTAS_INTRANET (IDCUENTA, IDIDENTIFICADOR, STRDN, CODINT, IDDOMINIO, BLNBLOQUEADA, BLNCTAGGL, BLNCTAGGLSUSP, BLNINSTITUCIONAL, STRDESCRIPCION, STRCORREORUTA)
Values (11, 'comision4', 'uid=comision4,cn=users,dc=ujaen,dc=es', 11, 'ujaen.es',  'N', 'N', 'N', 'N', 'Usuario de comision, comision4', 'comision4@xxx');
INSERT INTO ARCOS.V_PERSONA_INTRANET (CODINT, UJAENDNI, NUMDOCUMENTO, STRTIPODOCUMENTO, STRNOMBRE, STRAPELLIDO1, STRAPELLIDO2, SEXO, COD_PERSONA_AC, COD_PERSONA_RH, BLNMANUAL) 
Values (12, '12345678', '51992686J', 'DNI', 'Comision5', 'Usuario de', 'comision5', 'V', 12, 12, 'S');
INSERT INTO ARCOS.V_CUENTAS_INTRANET (IDCUENTA, IDIDENTIFICADOR, STRDN, CODINT, IDDOMINIO, BLNBLOQUEADA, BLNCTAGGL, BLNCTAGGLSUSP, BLNINSTITUCIONAL, STRDESCRIPCION, STRCORREORUTA)
Values (12, 'comision5', 'uid=comision5,cn=users,dc=ujaen,dc=es', 12, 'ujaen.es',  'N', 'N', 'N', 'N', 'Usuario de comision, comision5', 'comision5@xxx');


INSERT INTO ARCOS.V_PERSONA_INTRANET (CODINT, UJAENDNI, NUMDOCUMENTO, STRTIPODOCUMENTO, STRNOMBRE, STRAPELLIDO1, STRAPELLIDO2, SEXO, COD_PERSONA_AC, COD_PERSONA_RH, BLNMANUAL) 
Values (13, '12345678', '43396488L', 'DNI', 'Candidato1', 'Usuario de', 'candidato1', 'V', 13, 13, 'S');
INSERT INTO ARCOS.V_CUENTAS_INTRANET (IDCUENTA, IDIDENTIFICADOR, STRDN, CODINT, IDDOMINIO, BLNBLOQUEADA, BLNCTAGGL, BLNCTAGGLSUSP, BLNINSTITUCIONAL, STRDESCRIPCION, STRCORREORUTA)
Values (13, 'candidato1', 'uid=candidato1,cn=users,dc=ujaen,dc=es', 13, 'ujaen.es',  'N', 'N', 'N', 'N', 'Usuario de candidato, candidato1', 'candidato1@xxx');
INSERT INTO ARCOS.V_PERSONA_INTRANET (CODINT, UJAENDNI, NUMDOCUMENTO, STRTIPODOCUMENTO, STRNOMBRE, STRAPELLIDO1, STRAPELLIDO2, SEXO, COD_PERSONA_AC, COD_PERSONA_RH, BLNMANUAL) 
Values (14, '12345678', '91606989J', 'DNI', 'Candidato2', 'Usuario de', 'candidato2', 'V', 14, 14, 'S');
INSERT INTO ARCOS.V_CUENTAS_INTRANET (IDCUENTA, IDIDENTIFICADOR, STRDN, CODINT, IDDOMINIO, BLNBLOQUEADA, BLNCTAGGL, BLNCTAGGLSUSP, BLNINSTITUCIONAL, STRDESCRIPCION, STRCORREORUTA)
Values (14, 'candidato2', 'uid=candidato2,cn=users,dc=ujaen,dc=es', 14, 'ujaen.es',  'N', 'N', 'N', 'N', 'Usuario de candidato, candidato2', 'candidato2@xxx');
INSERT INTO ARCOS.V_PERSONA_INTRANET (CODINT, UJAENDNI, NUMDOCUMENTO, STRTIPODOCUMENTO, STRNOMBRE, STRAPELLIDO1, STRAPELLIDO2, SEXO, COD_PERSONA_AC, COD_PERSONA_RH, BLNMANUAL) 
Values (15, '12345678', '51906000Z', 'DNI', 'Candidato3', 'Usuario de', 'candidato3', 'V', 15, 15, 'S');
INSERT INTO ARCOS.V_CUENTAS_INTRANET (IDCUENTA, IDIDENTIFICADOR, STRDN, CODINT, IDDOMINIO, BLNBLOQUEADA, BLNCTAGGL, BLNCTAGGLSUSP, BLNINSTITUCIONAL, STRDESCRIPCION, STRCORREORUTA)
Values (15, 'candidato3', 'uid=candidato3,cn=users,dc=ujaen,dc=es', 15, 'ujaen.es',  'N', 'N', 'N', 'N', 'Usuario de candidato, candidato3', 'candidato3@xxx');
INSERT INTO ARCOS.V_PERSONA_INTRANET (CODINT, UJAENDNI, NUMDOCUMENTO, STRTIPODOCUMENTO, STRNOMBRE, STRAPELLIDO1, STRAPELLIDO2, SEXO, COD_PERSONA_AC, COD_PERSONA_RH, BLNMANUAL) 
Values (16, '12345678', '00834172P', 'DNI', 'Candidato4', 'Usuario de', 'candidato4', 'V', 16, 16, 'S');
INSERT INTO ARCOS.V_CUENTAS_INTRANET (IDCUENTA, IDIDENTIFICADOR, STRDN, CODINT, IDDOMINIO, BLNBLOQUEADA, BLNCTAGGL, BLNCTAGGLSUSP, BLNINSTITUCIONAL, STRDESCRIPCION, STRCORREORUTA)
Values (16, 'candidato4', 'uid=candidato4,cn=users,dc=ujaen,dc=es', 16, 'ujaen.es',  'N', 'N', 'N', 'N', 'Usuario de candidato, candidato4', 'candidato4@xxx');
INSERT INTO ARCOS.V_PERSONA_INTRANET (CODINT, UJAENDNI, NUMDOCUMENTO, STRTIPODOCUMENTO, STRNOMBRE, STRAPELLIDO1, STRAPELLIDO2, SEXO, COD_PERSONA_AC, COD_PERSONA_RH, BLNMANUAL) 
Values (17, '12345678', '37790895D', 'DNI', 'Candidato5', 'Usuario de', 'candidato5', 'V', 17, 17, 'S');
INSERT INTO ARCOS.V_CUENTAS_INTRANET (IDCUENTA, IDIDENTIFICADOR, STRDN, CODINT, IDDOMINIO, BLNBLOQUEADA, BLNCTAGGL, BLNCTAGGLSUSP, BLNINSTITUCIONAL, STRDESCRIPCION, STRCORREORUTA)
Values (17, 'candidato5', 'uid=candidato5,cn=users,dc=ujaen,dc=es', 17, 'ujaen.es',  'N', 'N', 'N', 'N', 'Usuario de candidato, candidato5', 'candidato5@xxx');
INSERT INTO ARCOS.V_PERSONA_INTRANET (CODINT, UJAENDNI, NUMDOCUMENTO, STRTIPODOCUMENTO, STRNOMBRE, STRAPELLIDO1, STRAPELLIDO2, SEXO, COD_PERSONA_AC, COD_PERSONA_RH, BLNMANUAL) 
Values (18, '12345678', '29330022P', 'DNI', 'Candidato6', 'Usuario de', 'candidato6', 'V', 18, 18, 'S');
INSERT INTO ARCOS.V_CUENTAS_INTRANET (IDCUENTA, IDIDENTIFICADOR, STRDN, CODINT, IDDOMINIO, BLNBLOQUEADA, BLNCTAGGL, BLNCTAGGLSUSP, BLNINSTITUCIONAL, STRDESCRIPCION, STRCORREORUTA)
Values (18, 'candidato6', 'uid=candidato6,cn=users,dc=ujaen,dc=es', 18, 'ujaen.es',  'N', 'N', 'N', 'N', 'Usuario de candidato, candidato6', 'candidato6@xxx');
INSERT INTO ARCOS.V_PERSONA_INTRANET (CODINT, UJAENDNI, NUMDOCUMENTO, STRTIPODOCUMENTO, STRNOMBRE, STRAPELLIDO1, STRAPELLIDO2, SEXO, COD_PERSONA_AC, COD_PERSONA_RH, BLNMANUAL) 
Values (19, '12345678', '37270880R', 'DNI', 'Candidato7', 'Usuario de', 'candidato7', 'V', 19, 19, 'S');
INSERT INTO ARCOS.V_CUENTAS_INTRANET (IDCUENTA, IDIDENTIFICADOR, STRDN, CODINT, IDDOMINIO, BLNBLOQUEADA, BLNCTAGGL, BLNCTAGGLSUSP, BLNINSTITUCIONAL, STRDESCRIPCION, STRCORREORUTA)
Values (19, 'candidato7', 'uid=candidato7,cn=users,dc=ujaen,dc=es', 19, 'ujaen.es',  'N', 'N', 'N', 'N', 'Usuario de candidato, candidato7', 'candidato7@xxx');
INSERT INTO ARCOS.V_PERSONA_INTRANET (CODINT, UJAENDNI, NUMDOCUMENTO, STRTIPODOCUMENTO, STRNOMBRE, STRAPELLIDO1, STRAPELLIDO2, SEXO, COD_PERSONA_AC, COD_PERSONA_RH, BLNMANUAL) 
Values (20, '12345678', '45538940K', 'DNI', 'Candidato8', 'Usuario de', 'candidato8', 'V', 20, 20, 'S');
INSERT INTO ARCOS.V_CUENTAS_INTRANET (IDCUENTA, IDIDENTIFICADOR, STRDN, CODINT, IDDOMINIO, BLNBLOQUEADA, BLNCTAGGL, BLNCTAGGLSUSP, BLNINSTITUCIONAL, STRDESCRIPCION, STRCORREORUTA)
Values (20, 'candidato8', 'uid=candidato8,cn=users,dc=ujaen,dc=es', 20, 'ujaen.es',  'N', 'N', 'N', 'N', 'Usuario de candidato, candidato8', 'candidato8@xxx');
INSERT INTO ARCOS.V_PERSONA_INTRANET (CODINT, UJAENDNI, NUMDOCUMENTO, STRTIPODOCUMENTO, STRNOMBRE, STRAPELLIDO1, STRAPELLIDO2, SEXO, COD_PERSONA_AC, COD_PERSONA_RH, BLNMANUAL) 
Values (21, '12345678', '69420803H', 'DNI', 'Candidato9', 'Usuario de', 'candidato9', 'V', 21, 21, 'S');
INSERT INTO ARCOS.V_CUENTAS_INTRANET (IDCUENTA, IDIDENTIFICADOR, STRDN, CODINT, IDDOMINIO, BLNBLOQUEADA, BLNCTAGGL, BLNCTAGGLSUSP, BLNINSTITUCIONAL, STRDESCRIPCION, STRCORREORUTA)
Values (21, 'candidato9', 'uid=candidato9,cn=users,dc=ujaen,dc=es', 21, 'ujaen.es',  'N', 'N', 'N', 'N', 'Usuario de candidato, candidato9', 'candidato9@xxx');
INSERT INTO ARCOS.V_PERSONA_INTRANET (CODINT, UJAENDNI, NUMDOCUMENTO, STRTIPODOCUMENTO, STRNOMBRE, STRAPELLIDO1, STRAPELLIDO2, SEXO, COD_PERSONA_AC, COD_PERSONA_RH, BLNMANUAL) 
Values (22, '12345678', '33530756E', 'DNI', 'Candidato10', 'Usuario de', 'candidato10', 'V', 22, 22, 'S');
INSERT INTO ARCOS.V_CUENTAS_INTRANET (IDCUENTA, IDIDENTIFICADOR, STRDN, CODINT, IDDOMINIO, BLNBLOQUEADA, BLNCTAGGL, BLNCTAGGLSUSP, BLNINSTITUCIONAL, STRDESCRIPCION, STRCORREORUTA)
Values (22, 'candidato10', 'uid=candidato10,cn=users,dc=ujaen,dc=es', 22, 'ujaen.es',  'N', 'N', 'N', 'N', 'Usuario de candidato, candidato10', 'candidato10@xxx');
INSERT INTO ARCOS.V_PERSONA_INTRANET (CODINT, UJAENDNI, NUMDOCUMENTO, STRTIPODOCUMENTO, STRNOMBRE, STRAPELLIDO1, STRAPELLIDO2, SEXO, COD_PERSONA_AC, COD_PERSONA_RH, BLNMANUAL) 
Values (23, '12345678', '67995554X', 'DNI', 'Pruebas1', 'Usuario de', 'pruebas1', 'V', 23, 23, 'S');
INSERT INTO ARCOS.V_CUENTAS_INTRANET (IDCUENTA, IDIDENTIFICADOR, STRDN, CODINT, IDDOMINIO, BLNBLOQUEADA, BLNCTAGGL, BLNCTAGGLSUSP, BLNINSTITUCIONAL, STRDESCRIPCION, STRCORREORUTA)
Values (23, 'pruebas1', 'uid=pruebas1,cn=users,dc=ujaen,dc=es', 23, 'ujaen.es',  'N', 'N', 'N', 'N', 'Usuario de pruebas, pruebas1', 'pruebas1@xxx');
INSERT INTO ARCOS.V_PERSONA_INTRANET (CODINT, UJAENDNI, NUMDOCUMENTO, STRTIPODOCUMENTO, STRNOMBRE, STRAPELLIDO1, STRAPELLIDO2, SEXO, COD_PERSONA_AC, COD_PERSONA_RH, BLNMANUAL) 
Values (24, '12345678', '50677767G', 'DNI', 'Pruebas2', 'Usuario de', 'pruebas2', 'V', 24, 24, 'S');
INSERT INTO ARCOS.V_CUENTAS_INTRANET (IDCUENTA, IDIDENTIFICADOR, STRDN, CODINT, IDDOMINIO, BLNBLOQUEADA, BLNCTAGGL, BLNCTAGGLSUSP, BLNINSTITUCIONAL, STRDESCRIPCION, STRCORREORUTA)
Values (24, 'pruebas2', 'uid=pruebas2,cn=users,dc=ujaen,dc=es', 24, 'ujaen.es',  'N', 'N', 'N', 'N', 'Usuario de pruebas, pruebas2', 'pruebas2@xxx');
INSERT INTO ARCOS.V_PERSONA_INTRANET (CODINT, UJAENDNI, NUMDOCUMENTO, STRTIPODOCUMENTO, STRNOMBRE, STRAPELLIDO1, STRAPELLIDO2, SEXO, COD_PERSONA_AC, COD_PERSONA_RH, BLNMANUAL) 
Values (25, '12345678', '03465896A', 'DNI', 'Director1', 'director1', 'director1', 'V', 25, 25, 'S');
INSERT INTO ARCOS.V_CUENTAS_INTRANET (IDCUENTA, IDIDENTIFICADOR, STRDN, CODINT, IDDOMINIO, BLNBLOQUEADA, BLNCTAGGL, BLNCTAGGLSUSP, BLNINSTITUCIONAL, STRDESCRIPCION, STRCORREORUTA)
Values (25, 'director1', 'uid=director1,cn=users,dc=ujaen,dc=es', 25, 'ujaen.es',  'N', 'N', 'N', 'N', 'director1', 'director1@xxx');
INSERT INTO ARCOS.V_PERSONA_INTRANET (CODINT, UJAENDNI, NUMDOCUMENTO, STRTIPODOCUMENTO, STRNOMBRE, STRAPELLIDO1, STRAPELLIDO2, SEXO, COD_PERSONA_AC, COD_PERSONA_RH, BLNMANUAL) 
Values (26, '12345678', '38389405J', 'DNI', 'Director2', 'director2', 'director2', 'V', 26, 26, 'S');
INSERT INTO ARCOS.V_CUENTAS_INTRANET (IDCUENTA, IDIDENTIFICADOR, STRDN, CODINT, IDDOMINIO, BLNBLOQUEADA, BLNCTAGGL, BLNCTAGGLSUSP, BLNINSTITUCIONAL, STRDESCRIPCION, STRCORREORUTA)
Values (26, 'director2', 'uid=director2,cn=users,dc=ujaen,dc=es', 26, 'ujaen.es',  'N', 'N', 'N', 'N', 'director2', 'director1@xxx');
INSERT INTO ARCOS.V_PERSONA_INTRANET (CODINT, UJAENDNI, NUMDOCUMENTO, STRTIPODOCUMENTO, STRNOMBRE, STRAPELLIDO1, STRAPELLIDO2, SEXO, COD_PERSONA_AC, COD_PERSONA_RH, BLNMANUAL) 
Values (100, '12345678', '45257820F', 'DNI', 'Test', 'Usuario de', 'test', 'V', 100, 100, 'S');
INSERT INTO ARCOS.V_CUENTAS_INTRANET (IDCUENTA, IDIDENTIFICADOR, STRDN, CODINT, IDDOMINIO, BLNBLOQUEADA, BLNCTAGGL, BLNCTAGGLSUSP, BLNINSTITUCIONAL, STRDESCRIPCION, STRCORREORUTA)
Values (100, 'test', 'uid=test,cn=users,dc=ujaen,dc=es', 100, 'ujaen.es',  'N', 'N', 'N', 'N', 'Usuario de testeo, test', 'test@xxx');
INSERT INTO ARCOS.V_PERSONA_INTRANET (CODINT, UJAENDNI, NUMDOCUMENTO, STRTIPODOCUMENTO, STRNOMBRE, STRAPELLIDO1, STRAPELLIDO2, SEXO, COD_PERSONA_AC, COD_PERSONA_RH, BLNMANUAL) 
Values (101, '11111222', '11111222Z', 'DNI', 'TestTitulacion', 'Usuario de', 'test', 'V', 100, 100, 'S');
INSERT INTO ARCOS.V_CUENTAS_INTRANET (IDCUENTA, IDIDENTIFICADOR, STRDN, CODINT, IDDOMINIO, BLNBLOQUEADA, BLNCTAGGL, BLNCTAGGLSUSP, BLNINSTITUCIONAL, STRDESCRIPCION, STRCORREORUTA)
Values (101, 'testTitulacion', 'uid=test,cn=users,dc=ujaen,dc=es', 100, 'ujaen.es',  'N', 'N', 'N', 'N', 'Usuario de testeo, test', 'test@xxx');