CREATE TABLE VUJA_NET_BEP_AR_PERSONA
(
  CODINT                  NUMBER,
  STRTIPODOCUMENTO        VARCHAR2(8),
  IDNIF                   VARCHAR2(20),
  LETRANIF                VARCHAR2(1),
  STRNOMBRE               VARCHAR2(45),
  STRAPELLIDO1            VARCHAR2(45),
  STRAPELLIDO2            VARCHAR2(45),
  EMAIL_ALTA              VARCHAR2(100)
)