DROP TABLE UXXIRRHH.VUJA_NET_BEP_RH_DEPTO_SECC_AREA;
--/////////////////////
CREATE TABLE UXXIRRHH.VUJA_NET_BEP_RH_DEPTO_SECC_AREA
(
  ID_DEPARTAMENTO        VARCHAR2(8 BYTE)       NOT NULL,
  DES_DEPARTAMENTO       VARCHAR2(40 BYTE),
  ID_SECCION             VARCHAR2(8 BYTE)       NOT NULL,
  DES_SECCION            VARCHAR2(40 BYTE),
  ID_AREA_CONOCIMIENTO   VARCHAR2(8 BYTE)       NOT NULL,
  DES_AREA_CONOCIMIENTO  VARCHAR2(50 BYTE)
);