Insert into UXXIRRHH.VUJA_NET_BEP_RH_DEPTO_SECC_AREA
   (ID_DEPARTAMENTO, DES_DEPARTAMENTO, ID_SECCION, DES_SECCION, ID_AREA_CONOCIMIENTO, 
    DES_AREA_CONOCIMIENTO)
 Values
   ('U109', 'DIDACTICA EXPR. MUSICAL PLASTICA y CORP.', 'S109', 'DIDACT. EXPR. MUS., PLASTICA Y CORPORAL', '635', 
    'MÚSICA');
Insert into UXXIRRHH.VUJA_NET_BEP_RH_DEPTO_SECC_AREA
   (ID_DEPARTAMENTO, DES_DEPARTAMENTO, ID_SECCION, DES_SECCION, ID_AREA_CONOCIMIENTO, 
    DES_AREA_CONOCIMIENTO)
 Values
   ('U116', 'FÍSICA', 'S153', 'Física', '398', 
    'FÍSICA DE LA TIERRA');
Insert into UXXIRRHH.VUJA_NET_BEP_RH_DEPTO_SECC_AREA
   (ID_DEPARTAMENTO, DES_DEPARTAMENTO, ID_SECCION, DES_SECCION, ID_AREA_CONOCIMIENTO, 
    DES_AREA_CONOCIMIENTO)
 Values
   ('U116', 'FÍSICA', 'S153.', 'FÍSICA (LINARES)', '398', 
    'FÍSICA DE LA TIERRA');
Insert into UXXIRRHH.VUJA_NET_BEP_RH_DEPTO_SECC_AREA
   (ID_DEPARTAMENTO, DES_DEPARTAMENTO, ID_SECCION, DES_SECCION, ID_AREA_CONOCIMIENTO, 
    DES_AREA_CONOCIMIENTO)
 Values
   ('U999', 'ASIGNATURAS SIN ADSCRIPCIÓN', 'U999', 'ASIGNATURAS SIN ADSCRIPCIÓN', '000', 
    'ASIGNATURAS SIN ADSCRIPCIÓN');
Insert into UXXIRRHH.VUJA_NET_BEP_RH_DEPTO_SECC_AREA
   (ID_DEPARTAMENTO, DES_DEPARTAMENTO, ID_SECCION, DES_SECCION, ID_AREA_CONOCIMIENTO, 
    DES_AREA_CONOCIMIENTO)
 Values
   ('U101', 'ADMÓN. DE EMPRESAS, CONTAB. Y SOCIOLOGIA', 'S101', 'Admón de Empresas, Contab. y Sociología', '095', 
    'COMERCIALIZACIÓN E INVESTIGACIÓN DE MERCADOS');
Insert into UXXIRRHH.VUJA_NET_BEP_RH_DEPTO_SECC_AREA
   (ID_DEPARTAMENTO, DES_DEPARTAMENTO, ID_SECCION, DES_SECCION, ID_AREA_CONOCIMIENTO, 
    DES_AREA_CONOCIMIENTO)
 Values
   ('U136', 'ORG. DE EMPRESAS, MÁRKETING Y SOCIOLOGÍA', 'S136', 'ORG. DE EMPRESAS, MÁRKETING Y SOCIOLOGIA', '095', 
    'COMERCIALIZACIÓN E INVESTIGACIÓN DE MERCADOS');
Insert into UXXIRRHH.VUJA_NET_BEP_RH_DEPTO_SECC_AREA
   (ID_DEPARTAMENTO, DES_DEPARTAMENTO, ID_SECCION, DES_SECCION, ID_AREA_CONOCIMIENTO, 
    DES_AREA_CONOCIMIENTO)
 Values
   ('U136', 'ORG. DE EMPRESAS, MÁRKETING Y SOCIOLOGÍA', 'S136.', 'ORG. DE EMPR., MÁRK. Y SOCIOL. (LINARES)', '095', 
    'COMERCIALIZACIÓN E INVESTIGACIÓN DE MERCADOS');
Insert into UXXIRRHH.VUJA_NET_BEP_RH_DEPTO_SECC_AREA
   (ID_DEPARTAMENTO, DES_DEPARTAMENTO, ID_SECCION, DES_SECCION, ID_AREA_CONOCIMIENTO, 
    DES_AREA_CONOCIMIENTO)
 Values
   ('U101', 'ADMÓN. DE EMPRESAS, CONTAB. Y SOCIOLOGIA', 'S101', 'Admón de Empresas, Contab. y Sociología', '230', 
    'ECONOMÍA FINANCIERA Y CONTABILIDAD');
Insert into UXXIRRHH.VUJA_NET_BEP_RH_DEPTO_SECC_AREA
   (ID_DEPARTAMENTO, DES_DEPARTAMENTO, ID_SECCION, DES_SECCION, ID_AREA_CONOCIMIENTO, 
    DES_AREA_CONOCIMIENTO)
 Values
   ('U137', 'ECONOMÍA FINANCIERA Y CONTABILIDAD', 'S137', 'ECONOMÍA FINANCIERA Y CONTABILIDAD', '230', 
    'ECONOMÍA FINANCIERA Y CONTABILIDAD');
Insert into UXXIRRHH.VUJA_NET_BEP_RH_DEPTO_SECC_AREA
   (ID_DEPARTAMENTO, DES_DEPARTAMENTO, ID_SECCION, DES_SECCION, ID_AREA_CONOCIMIENTO, 
    DES_AREA_CONOCIMIENTO)
 Values
   ('U101', 'ADMÓN. DE EMPRESAS, CONTAB. Y SOCIOLOGIA', 'S101', 'Admón de Empresas, Contab. y Sociología', '650', 
    'ORGANIZACIÓN DE EMPRESAS');
Insert into UXXIRRHH.VUJA_NET_BEP_RH_DEPTO_SECC_AREA
   (ID_DEPARTAMENTO, DES_DEPARTAMENTO, ID_SECCION, DES_SECCION, ID_AREA_CONOCIMIENTO, 
    DES_AREA_CONOCIMIENTO)
 Values
   ('U136', 'ORG. DE EMPRESAS, MÁRKETING Y SOCIOLOGÍA', 'S136', 'ORG. DE EMPRESAS, MÁRKETING Y SOCIOLOGIA', '650', 
    'ORGANIZACIÓN DE EMPRESAS');
Insert into UXXIRRHH.VUJA_NET_BEP_RH_DEPTO_SECC_AREA
   (ID_DEPARTAMENTO, DES_DEPARTAMENTO, ID_SECCION, DES_SECCION, ID_AREA_CONOCIMIENTO, 
    DES_AREA_CONOCIMIENTO)
 Values
   ('U136', 'ORG. DE EMPRESAS, MÁRKETING Y SOCIOLOGÍA', 'S136.', 'ORG. DE EMPR., MÁRK. Y SOCIOL. (LINARES)', '650', 
    'ORGANIZACIÓN DE EMPRESAS');
Insert into UXXIRRHH.VUJA_NET_BEP_RH_DEPTO_SECC_AREA
   (ID_DEPARTAMENTO, DES_DEPARTAMENTO, ID_SECCION, DES_SECCION, ID_AREA_CONOCIMIENTO, 
    DES_AREA_CONOCIMIENTO)
 Values
   ('U101', 'ADMÓN. DE EMPRESAS, CONTAB. Y SOCIOLOGIA', 'S101', 'Admón de Empresas, Contab. y Sociología', '775', 
    'SOCIOLOGÍA');
Insert into UXXIRRHH.VUJA_NET_BEP_RH_DEPTO_SECC_AREA
   (ID_DEPARTAMENTO, DES_DEPARTAMENTO, ID_SECCION, DES_SECCION, ID_AREA_CONOCIMIENTO, 
    DES_AREA_CONOCIMIENTO)
 Values
   ('U136', 'ORG. DE EMPRESAS, MÁRKETING Y SOCIOLOGÍA', 'S136', 'ORG. DE EMPRESAS, MÁRKETING Y SOCIOLOGIA', '775', 
    'SOCIOLOGÍA');
Insert into UXXIRRHH.VUJA_NET_BEP_RH_DEPTO_SECC_AREA
   (ID_DEPARTAMENTO, DES_DEPARTAMENTO, ID_SECCION, DES_SECCION, ID_AREA_CONOCIMIENTO, 
    DES_AREA_CONOCIMIENTO)
 Values
   ('U136', 'ORG. DE EMPRESAS, MÁRKETING Y SOCIOLOGÍA', 'S136.', 'ORG. DE EMPR., MÁRK. Y SOCIOL. (LINARES)', '775', 
    'SOCIOLOGÍA');
Insert into UXXIRRHH.VUJA_NET_BEP_RH_DEPTO_SECC_AREA
   (ID_DEPARTAMENTO, DES_DEPARTAMENTO, ID_SECCION, DES_SECCION, ID_AREA_CONOCIMIENTO, 
    DES_AREA_CONOCIMIENTO)
 Values
   ('U102', 'BIOLOGIA ANIMAL, BIOL.VEGETAL Y ECOLOGIA', 'S102', 'BIOLOGIA ANIMAL, VEGETAL Y ECOLOGIA', '045', 
    'BIOLOGÍA ANIMAL');
Insert into UXXIRRHH.VUJA_NET_BEP_RH_DEPTO_SECC_AREA
   (ID_DEPARTAMENTO, DES_DEPARTAMENTO, ID_SECCION, DES_SECCION, ID_AREA_CONOCIMIENTO, 
    DES_AREA_CONOCIMIENTO)
 Values
   ('U102', 'BIOLOGIA ANIMAL, BIOL.VEGETAL Y ECOLOGIA', 'S102', 'BIOLOGIA ANIMAL, VEGETAL Y ECOLOGIA', '055', 
    'BIOLOGÍA VEGETAL');
Insert into UXXIRRHH.VUJA_NET_BEP_RH_DEPTO_SECC_AREA
   (ID_DEPARTAMENTO, DES_DEPARTAMENTO, ID_SECCION, DES_SECCION, ID_AREA_CONOCIMIENTO, 
    DES_AREA_CONOCIMIENTO)
 Values
   ('U102', 'BIOLOGIA ANIMAL, BIOL.VEGETAL Y ECOLOGIA', 'S102', 'BIOLOGIA ANIMAL, VEGETAL Y ECOLOGIA', '220', 
    'ECOLOGÍA');
Insert into UXXIRRHH.VUJA_NET_BEP_RH_DEPTO_SECC_AREA
   (ID_DEPARTAMENTO, DES_DEPARTAMENTO, ID_SECCION, DES_SECCION, ID_AREA_CONOCIMIENTO, 
    DES_AREA_CONOCIMIENTO)
 Values
   ('U103', 'BIOLOGÍA EXPERIMENTAL', 'S103', 'BIOLOGIA EXPERIMENTAL', '050', 
    'BIOLOGÍA CELULAR');
Insert into UXXIRRHH.VUJA_NET_BEP_RH_DEPTO_SECC_AREA
   (ID_DEPARTAMENTO, DES_DEPARTAMENTO, ID_SECCION, DES_SECCION, ID_AREA_CONOCIMIENTO, 
    DES_AREA_CONOCIMIENTO)
 Values
   ('U103', 'BIOLOGÍA EXPERIMENTAL', 'S103', 'BIOLOGIA EXPERIMENTAL', '060', 
    'BIOQUÍMICA Y BIOLOGÍA MOLECULAR');
Insert into UXXIRRHH.VUJA_NET_BEP_RH_DEPTO_SECC_AREA
   (ID_DEPARTAMENTO, DES_DEPARTAMENTO, ID_SECCION, DES_SECCION, ID_AREA_CONOCIMIENTO, 
    DES_AREA_CONOCIMIENTO)
 Values
   ('U103', 'BIOLOGÍA EXPERIMENTAL', 'S103', 'BIOLOGIA EXPERIMENTAL', '420', 
    'GENÉTICA');
Insert into UXXIRRHH.VUJA_NET_BEP_RH_DEPTO_SECC_AREA
   (ID_DEPARTAMENTO, DES_DEPARTAMENTO, ID_SECCION, DES_SECCION, ID_AREA_CONOCIMIENTO, 
    DES_AREA_CONOCIMIENTO)
 Values
   ('U104', 'DERECHO PÚBLICO Y DERECHO PRIV. ESPECIAL', 'S104', 'DERECHO PUBLICO Y D. PRIVADO ESPECIAL', '070', 
    'CIENCIA POLÍTICA Y DE LA ADMINISTRACIÓN');
Insert into UXXIRRHH.VUJA_NET_BEP_RH_DEPTO_SECC_AREA
   (ID_DEPARTAMENTO, DES_DEPARTAMENTO, ID_SECCION, DES_SECCION, ID_AREA_CONOCIMIENTO, 
    DES_AREA_CONOCIMIENTO)
 Values
   ('U138', 'DERECHO PÚBLICO Y D. PRIVADO ESPECIAL', 'S138', 'DERECHO PCO. Y DERECHO PRIVADO ESPEC.', '070', 
    'CIENCIA POLÍTICA Y DE LA ADMINISTRACIÓN');
Insert into UXXIRRHH.VUJA_NET_BEP_RH_DEPTO_SECC_AREA
   (ID_DEPARTAMENTO, DES_DEPARTAMENTO, ID_SECCION, DES_SECCION, ID_AREA_CONOCIMIENTO, 
    DES_AREA_CONOCIMIENTO)
 Values
   ('U104', 'DERECHO PÚBLICO Y DERECHO PRIV. ESPECIAL', 'S104', 'DERECHO PUBLICO Y D. PRIVADO ESPECIAL', '125', 
    'DERECHO ADMINISTRATIVO');
Insert into UXXIRRHH.VUJA_NET_BEP_RH_DEPTO_SECC_AREA
   (ID_DEPARTAMENTO, DES_DEPARTAMENTO, ID_SECCION, DES_SECCION, ID_AREA_CONOCIMIENTO, 
    DES_AREA_CONOCIMIENTO)
 Values
   ('U139', 'DERECHO PÚBLICO', 'S139', 'DERECHO PÚBLICO', '125', 
    'DERECHO ADMINISTRATIVO');
Insert into UXXIRRHH.VUJA_NET_BEP_RH_DEPTO_SECC_AREA
   (ID_DEPARTAMENTO, DES_DEPARTAMENTO, ID_SECCION, DES_SECCION, ID_AREA_CONOCIMIENTO, 
    DES_AREA_CONOCIMIENTO)
 Values
   ('U104', 'DERECHO PÚBLICO Y DERECHO PRIV. ESPECIAL', 'S104', 'DERECHO PUBLICO Y D. PRIVADO ESPECIAL', '140', 
    'DERECHO DEL TRABAJO Y DE LA SEGURIDAD SOCIAL');
Insert into UXXIRRHH.VUJA_NET_BEP_RH_DEPTO_SECC_AREA
   (ID_DEPARTAMENTO, DES_DEPARTAMENTO, ID_SECCION, DES_SECCION, ID_AREA_CONOCIMIENTO, 
    DES_AREA_CONOCIMIENTO)
 Values
   ('U138', 'DERECHO PÚBLICO Y D. PRIVADO ESPECIAL', 'S138', 'DERECHO PCO. Y DERECHO PRIVADO ESPEC.', '140', 
    'DERECHO DEL TRABAJO Y DE LA SEGURIDAD SOCIAL');
Insert into UXXIRRHH.VUJA_NET_BEP_RH_DEPTO_SECC_AREA
   (ID_DEPARTAMENTO, DES_DEPARTAMENTO, ID_SECCION, DES_SECCION, ID_AREA_CONOCIMIENTO, 
    DES_AREA_CONOCIMIENTO)
 Values
   ('U104', 'DERECHO PÚBLICO Y DERECHO PRIV. ESPECIAL', 'S104', 'DERECHO PUBLICO Y D. PRIVADO ESPECIAL', '165', 
    'DERECHO MERCANTIL');
Insert into UXXIRRHH.VUJA_NET_BEP_RH_DEPTO_SECC_AREA
   (ID_DEPARTAMENTO, DES_DEPARTAMENTO, ID_SECCION, DES_SECCION, ID_AREA_CONOCIMIENTO, 
    DES_AREA_CONOCIMIENTO)
 Values
   ('U138', 'DERECHO PÚBLICO Y D. PRIVADO ESPECIAL', 'S138', 'DERECHO PCO. Y DERECHO PRIVADO ESPEC.', '165', 
    'DERECHO MERCANTIL');
Insert into UXXIRRHH.VUJA_NET_BEP_RH_DEPTO_SECC_AREA
   (ID_DEPARTAMENTO, DES_DEPARTAMENTO, ID_SECCION, DES_SECCION, ID_AREA_CONOCIMIENTO, 
    DES_AREA_CONOCIMIENTO)
 Values
   ('U104', 'DERECHO PÚBLICO Y DERECHO PRIV. ESPECIAL', 'S104', 'DERECHO PUBLICO Y D. PRIVADO ESPECIAL', '470', 
    'HISTORIA DEL DERECHO Y DE LAS INSTITUCIONES');
Insert into UXXIRRHH.VUJA_NET_BEP_RH_DEPTO_SECC_AREA
   (ID_DEPARTAMENTO, DES_DEPARTAMENTO, ID_SECCION, DES_SECCION, ID_AREA_CONOCIMIENTO, 
    DES_AREA_CONOCIMIENTO)
 Values
   ('U138', 'DERECHO PÚBLICO Y D. PRIVADO ESPECIAL', 'S138', 'DERECHO PCO. Y DERECHO PRIVADO ESPEC.', '470', 
    'HISTORIA DEL DERECHO Y DE LAS INSTITUCIONES');
Insert into UXXIRRHH.VUJA_NET_BEP_RH_DEPTO_SECC_AREA
   (ID_DEPARTAMENTO, DES_DEPARTAMENTO, ID_SECCION, DES_SECCION, ID_AREA_CONOCIMIENTO, 
    DES_AREA_CONOCIMIENTO)
 Values
   ('U106', 'DERECHO ECLES.,INTER.PUBL., PROC. Y ROM.', 'S106', 'DERECHO ECLES.,INT. PUB.,PROC Y ROM', '145', 
    'DERECHO ECLESIÁSTICO DEL ESTADO');
Insert into UXXIRRHH.VUJA_NET_BEP_RH_DEPTO_SECC_AREA
   (ID_DEPARTAMENTO, DES_DEPARTAMENTO, ID_SECCION, DES_SECCION, ID_AREA_CONOCIMIENTO, 
    DES_AREA_CONOCIMIENTO)
 Values
   ('U140', 'DERECHO PÚBLICO Y COMÚN EUROPEO', 'S140', 'PÚBLICO Y COMÚN EUROPEO', '145', 
    'DERECHO ECLESIÁSTICO DEL ESTADO');
Insert into UXXIRRHH.VUJA_NET_BEP_RH_DEPTO_SECC_AREA
   (ID_DEPARTAMENTO, DES_DEPARTAMENTO, ID_SECCION, DES_SECCION, ID_AREA_CONOCIMIENTO, 
    DES_AREA_CONOCIMIENTO)
 Values
   ('U106', 'DERECHO ECLES.,INTER.PUBL., PROC. Y ROM.', 'S106', 'DERECHO ECLES.,INT. PUB.,PROC Y ROM', '175', 
    'DERECHO PROCESAL');
Insert into UXXIRRHH.VUJA_NET_BEP_RH_DEPTO_SECC_AREA
   (ID_DEPARTAMENTO, DES_DEPARTAMENTO, ID_SECCION, DES_SECCION, ID_AREA_CONOCIMIENTO, 
    DES_AREA_CONOCIMIENTO)
 Values
   ('U140', 'DERECHO PÚBLICO Y COMÚN EUROPEO', 'S140', 'PÚBLICO Y COMÚN EUROPEO', '175', 
    'DERECHO PROCESAL');
Insert into UXXIRRHH.VUJA_NET_BEP_RH_DEPTO_SECC_AREA
   (ID_DEPARTAMENTO, DES_DEPARTAMENTO, ID_SECCION, DES_SECCION, ID_AREA_CONOCIMIENTO, 
    DES_AREA_CONOCIMIENTO)
 Values
   ('U106', 'DERECHO ECLES.,INTER.PUBL., PROC. Y ROM.', 'S106', 'DERECHO ECLES.,INT. PUB.,PROC Y ROM', '180', 
    'DERECHO ROMANO');
Insert into UXXIRRHH.VUJA_NET_BEP_RH_DEPTO_SECC_AREA
   (ID_DEPARTAMENTO, DES_DEPARTAMENTO, ID_SECCION, DES_SECCION, ID_AREA_CONOCIMIENTO, 
    DES_AREA_CONOCIMIENTO)
 Values
   ('U140', 'DERECHO PÚBLICO Y COMÚN EUROPEO', 'S140', 'PÚBLICO Y COMÚN EUROPEO', '180', 
    'DERECHO ROMANO');
Insert into UXXIRRHH.VUJA_NET_BEP_RH_DEPTO_SECC_AREA
   (ID_DEPARTAMENTO, DES_DEPARTAMENTO, ID_SECCION, DES_SECCION, ID_AREA_CONOCIMIENTO, 
    DES_AREA_CONOCIMIENTO)
 Values
   ('U107', 'DERECHO PENAL, FIL.DCHO. FIL.MORAL Y FIL', 'S107', 'DERECHO PENAL, FIL. DER. FIL.MORAL Y FIL', '170', 
    'DERECHO PENAL');
Insert into UXXIRRHH.VUJA_NET_BEP_RH_DEPTO_SECC_AREA
   (ID_DEPARTAMENTO, DES_DEPARTAMENTO, ID_SECCION, DES_SECCION, ID_AREA_CONOCIMIENTO, 
    DES_AREA_CONOCIMIENTO)
 Values
   ('U107', 'DERECHO PENAL, FIL.DCHO. FIL.MORAL Y FIL', 'S107', 'DERECHO PENAL, FIL. DER. FIL.MORAL Y FIL', '381', 
    'FILOSOFÍA DEL DERECHO');
Insert into UXXIRRHH.VUJA_NET_BEP_RH_DEPTO_SECC_AREA
   (ID_DEPARTAMENTO, DES_DEPARTAMENTO, ID_SECCION, DES_SECCION, ID_AREA_CONOCIMIENTO, 
    DES_AREA_CONOCIMIENTO)
 Values
   ('U108', 'DIDÁCTICA DE LAS CIENCIAS', 'S108', 'DIDACTICA DE LAS CIENCIAS', '200', 
    'DIDÁCTICA DE LA MATEMÁTICA');
Insert into UXXIRRHH.VUJA_NET_BEP_RH_DEPTO_SECC_AREA
   (ID_DEPARTAMENTO, DES_DEPARTAMENTO, ID_SECCION, DES_SECCION, ID_AREA_CONOCIMIENTO, 
    DES_AREA_CONOCIMIENTO)
 Values
   ('U108', 'DIDÁCTICA DE LAS CIENCIAS', 'S108', 'DIDACTICA DE LAS CIENCIAS', '210', 
    'DIDÁCTICA DE LAS CIENCIAS SOCIALES');
Insert into UXXIRRHH.VUJA_NET_BEP_RH_DEPTO_SECC_AREA
   (ID_DEPARTAMENTO, DES_DEPARTAMENTO, ID_SECCION, DES_SECCION, ID_AREA_CONOCIMIENTO, 
    DES_AREA_CONOCIMIENTO)
 Values
   ('U109', 'DIDACTICA EXPR. MUSICAL PLASTICA y CORP.', 'S109', 'DIDACT. EXPR. MUS., PLASTICA Y CORPORAL', '185', 
    'DIBUJO');
Insert into UXXIRRHH.VUJA_NET_BEP_RH_DEPTO_SECC_AREA
   (ID_DEPARTAMENTO, DES_DEPARTAMENTO, ID_SECCION, DES_SECCION, ID_AREA_CONOCIMIENTO, 
    DES_AREA_CONOCIMIENTO)
 Values
   ('U109', 'DIDACTICA EXPR. MUSICAL PLASTICA y CORP.', 'S109', 'DIDACT. EXPR. MUS., PLASTICA Y CORPORAL', '187', 
    'DIDÁCTICA DE LA EXPRESIÓN CORPORAL');
Insert into UXXIRRHH.VUJA_NET_BEP_RH_DEPTO_SECC_AREA
   (ID_DEPARTAMENTO, DES_DEPARTAMENTO, ID_SECCION, DES_SECCION, ID_AREA_CONOCIMIENTO, 
    DES_AREA_CONOCIMIENTO)
 Values
   ('U109', 'DIDACTICA EXPR. MUSICAL PLASTICA y CORP.', 'S109', 'DIDACT. EXPR. MUS., PLASTICA Y CORPORAL', '193', 
    'DIDÁCTICA DE LA EXPRESIÓN PLÁSTICA');
Insert into UXXIRRHH.VUJA_NET_BEP_RH_DEPTO_SECC_AREA
   (ID_DEPARTAMENTO, DES_DEPARTAMENTO, ID_SECCION, DES_SECCION, ID_AREA_CONOCIMIENTO, 
    DES_AREA_CONOCIMIENTO)
 Values
   ('U109', 'DIDACTICA EXPR. MUSICAL PLASTICA y CORP.', 'S109', 'DIDACT. EXPR. MUS., PLASTICA Y CORPORAL', '245', 
    'EDUCACIÓN FÍSICA Y DEPORTIVA');
Insert into UXXIRRHH.VUJA_NET_BEP_RH_DEPTO_SECC_AREA
   (ID_DEPARTAMENTO, DES_DEPARTAMENTO, ID_SECCION, DES_SECCION, ID_AREA_CONOCIMIENTO, 
    DES_AREA_CONOCIMIENTO)
 Values
   ('U110', 'ECONOMIA', 'S110', 'ECONOMIA', '480', 
    'HISTORIA DE INSTITUCIONES ECONÓMICAS');
Insert into UXXIRRHH.VUJA_NET_BEP_RH_DEPTO_SECC_AREA
   (ID_DEPARTAMENTO, DES_DEPARTAMENTO, ID_SECCION, DES_SECCION, ID_AREA_CONOCIMIENTO, 
    DES_AREA_CONOCIMIENTO)
 Values
   ('U110', 'ECONOMIA', 'S110.', 'ECONOMIA (LINARES)', '480', 
    'HISTORIA DE INSTITUCIONES ECONÓMICAS');
Insert into UXXIRRHH.VUJA_NET_BEP_RH_DEPTO_SECC_AREA
   (ID_DEPARTAMENTO, DES_DEPARTAMENTO, ID_SECCION, DES_SECCION, ID_AREA_CONOCIMIENTO, 
    DES_AREA_CONOCIMIENTO)
 Values
   ('U111', 'ING ELECTRÓNICA DE TELECOM. Y AUTOMATICA', 'S157', 'Ing. Electónica, de Telecom. y Automat.', '520', 
    'INGENIERÍA DE SISTEMAS Y AUTOMÁTICA');
Insert into UXXIRRHH.VUJA_NET_BEP_RH_DEPTO_SECC_AREA
   (ID_DEPARTAMENTO, DES_DEPARTAMENTO, ID_SECCION, DES_SECCION, ID_AREA_CONOCIMIENTO, 
    DES_AREA_CONOCIMIENTO)
 Values
   ('U133', 'ING. ELECTRÓNICA Y AUTOMATICA', 'S133', 'ING. ELECTRÓNICA Y AUTOMÁTICA', '520', 
    'INGENIERÍA DE SISTEMAS Y AUTOMÁTICA');
Insert into UXXIRRHH.VUJA_NET_BEP_RH_DEPTO_SECC_AREA
   (ID_DEPARTAMENTO, DES_DEPARTAMENTO, ID_SECCION, DES_SECCION, ID_AREA_CONOCIMIENTO, 
    DES_AREA_CONOCIMIENTO)
 Values
   ('U133', 'ING. ELECTRÓNICA Y AUTOMATICA', 'S133.', 'ING. ELECTRÓNICA Y AUTOMÁTICA (LINARES)', '520', 
    'INGENIERÍA DE SISTEMAS Y AUTOMÁTICA');
Insert into UXXIRRHH.VUJA_NET_BEP_RH_DEPTO_SECC_AREA
   (ID_DEPARTAMENTO, DES_DEPARTAMENTO, ID_SECCION, DES_SECCION, ID_AREA_CONOCIMIENTO, 
    DES_AREA_CONOCIMIENTO)
 Values
   ('U111', 'ING ELECTRÓNICA DE TELECOM. Y AUTOMATICA', 'S157', 'Ing. Electónica, de Telecom. y Automat.', '560', 
    'INGENIERÍA TELEMÁTICA');
Insert into UXXIRRHH.VUJA_NET_BEP_RH_DEPTO_SECC_AREA
   (ID_DEPARTAMENTO, DES_DEPARTAMENTO, ID_SECCION, DES_SECCION, ID_AREA_CONOCIMIENTO, 
    DES_AREA_CONOCIMIENTO)
 Values
   ('U134', 'INGENIERÍA DE TELECOMUNICACIÓN', 'S134', 'INGENIERÍA DE TELECOMUNICACIÓN', '560', 
    'INGENIERÍA TELEMÁTICA');
Insert into UXXIRRHH.VUJA_NET_BEP_RH_DEPTO_SECC_AREA
   (ID_DEPARTAMENTO, DES_DEPARTAMENTO, ID_SECCION, DES_SECCION, ID_AREA_CONOCIMIENTO, 
    DES_AREA_CONOCIMIENTO)
 Values
   ('U134', 'INGENIERÍA DE TELECOMUNICACIÓN', 'S134.', 'INGENIERÍA DE TELECOMUNICACIÓN (LINARES)', '560', 
    'INGENIERÍA TELEMÁTICA');
Insert into UXXIRRHH.VUJA_NET_BEP_RH_DEPTO_SECC_AREA
   (ID_DEPARTAMENTO, DES_DEPARTAMENTO, ID_SECCION, DES_SECCION, ID_AREA_CONOCIMIENTO, 
    DES_AREA_CONOCIMIENTO)
 Values
   ('U111', 'ING ELECTRÓNICA DE TELECOM. Y AUTOMATICA', 'S157', 'Ing. Electónica, de Telecom. y Automat.', '800', 
    'TEORÍA DE LA SEÑAL Y COMUNICACIONES');
Insert into UXXIRRHH.VUJA_NET_BEP_RH_DEPTO_SECC_AREA
   (ID_DEPARTAMENTO, DES_DEPARTAMENTO, ID_SECCION, DES_SECCION, ID_AREA_CONOCIMIENTO, 
    DES_AREA_CONOCIMIENTO)
 Values
   ('U134', 'INGENIERÍA DE TELECOMUNICACIÓN', 'S134', 'INGENIERÍA DE TELECOMUNICACIÓN', '800', 
    'TEORÍA DE LA SEÑAL Y COMUNICACIONES');
Insert into UXXIRRHH.VUJA_NET_BEP_RH_DEPTO_SECC_AREA
   (ID_DEPARTAMENTO, DES_DEPARTAMENTO, ID_SECCION, DES_SECCION, ID_AREA_CONOCIMIENTO, 
    DES_AREA_CONOCIMIENTO)
 Values
   ('U134', 'INGENIERÍA DE TELECOMUNICACIÓN', 'S134.', 'INGENIERÍA DE TELECOMUNICACIÓN (LINARES)', '800', 
    'TEORÍA DE LA SEÑAL Y COMUNICACIONES');
Insert into UXXIRRHH.VUJA_NET_BEP_RH_DEPTO_SECC_AREA
   (ID_DEPARTAMENTO, DES_DEPARTAMENTO, ID_SECCION, DES_SECCION, ID_AREA_CONOCIMIENTO, 
    DES_AREA_CONOCIMIENTO)
 Values
   ('U113', 'INGENIERÍA GRÁFICA, DISENO Y PROYECTOS', 'S150', 'Ingeniería Gráfica, Diseño y Proyectos', '300', 
    'EXPRESIÓN GRÁFICA ARQUITECTÓNICA');
Insert into UXXIRRHH.VUJA_NET_BEP_RH_DEPTO_SECC_AREA
   (ID_DEPARTAMENTO, DES_DEPARTAMENTO, ID_SECCION, DES_SECCION, ID_AREA_CONOCIMIENTO, 
    DES_AREA_CONOCIMIENTO)
 Values
   ('U113', 'INGENIERÍA GRÁFICA, DISENO Y PROYECTOS', 'S150.', 'ING. GRÁFICA, DISEÑO Y PROY. (LINARES)', '300', 
    'EXPRESIÓN GRÁFICA ARQUITECTÓNICA');
Insert into UXXIRRHH.VUJA_NET_BEP_RH_DEPTO_SECC_AREA
   (ID_DEPARTAMENTO, DES_DEPARTAMENTO, ID_SECCION, DES_SECCION, ID_AREA_CONOCIMIENTO, 
    DES_AREA_CONOCIMIENTO)
 Values
   ('U112', 'ESTADISTICA E INVESTIGACIÓN OPERATIVA', 'S112', 'ESTADISTICA E INVESTIGACION OPERATIVA', '265', 
    'ESTADÍSTICA E INVESTIGACIÓN OPERATIVA');
Insert into UXXIRRHH.VUJA_NET_BEP_RH_DEPTO_SECC_AREA
   (ID_DEPARTAMENTO, DES_DEPARTAMENTO, ID_SECCION, DES_SECCION, ID_AREA_CONOCIMIENTO, 
    DES_AREA_CONOCIMIENTO)
 Values
   ('U112', 'ESTADISTICA E INVESTIGACIÓN OPERATIVA', 'S112.', 'ESTADÍSTICA E INVEST. OPERAT. (LINARES)', '265', 
    'ESTADÍSTICA E INVESTIGACIÓN OPERATIVA');
Insert into UXXIRRHH.VUJA_NET_BEP_RH_DEPTO_SECC_AREA
   (ID_DEPARTAMENTO, DES_DEPARTAMENTO, ID_SECCION, DES_SECCION, ID_AREA_CONOCIMIENTO, 
    DES_AREA_CONOCIMIENTO)
 Values
   ('U113', 'INGENIERÍA GRÁFICA, DISENO Y PROYECTOS', 'S150', 'Ingeniería Gráfica, Diseño y Proyectos', '305', 
    'EXPRESIÓN GRÁFICA EN LA INGENIERÍA');
Insert into UXXIRRHH.VUJA_NET_BEP_RH_DEPTO_SECC_AREA
   (ID_DEPARTAMENTO, DES_DEPARTAMENTO, ID_SECCION, DES_SECCION, ID_AREA_CONOCIMIENTO, 
    DES_AREA_CONOCIMIENTO)
 Values
   ('U113', 'INGENIERÍA GRÁFICA, DISENO Y PROYECTOS', 'S150.', 'ING. GRÁFICA, DISEÑO Y PROY. (LINARES)', '305', 
    'EXPRESIÓN GRÁFICA EN LA INGENIERÍA');
Insert into UXXIRRHH.VUJA_NET_BEP_RH_DEPTO_SECC_AREA
   (ID_DEPARTAMENTO, DES_DEPARTAMENTO, ID_SECCION, DES_SECCION, ID_AREA_CONOCIMIENTO, 
    DES_AREA_CONOCIMIENTO)
 Values
   ('U113', 'INGENIERÍA GRÁFICA, DISENO Y PROYECTOS', 'S150', 'Ingeniería Gráfica, Diseño y Proyectos', '720', 
    'PROYECTOS DE INGENIERÍA');
Insert into UXXIRRHH.VUJA_NET_BEP_RH_DEPTO_SECC_AREA
   (ID_DEPARTAMENTO, DES_DEPARTAMENTO, ID_SECCION, DES_SECCION, ID_AREA_CONOCIMIENTO, 
    DES_AREA_CONOCIMIENTO)
 Values
   ('U113', 'INGENIERÍA GRÁFICA, DISENO Y PROYECTOS', 'S150.', 'ING. GRÁFICA, DISEÑO Y PROY. (LINARES)', '720', 
    'PROYECTOS DE INGENIERÍA');
Insert into UXXIRRHH.VUJA_NET_BEP_RH_DEPTO_SECC_AREA
   (ID_DEPARTAMENTO, DES_DEPARTAMENTO, ID_SECCION, DES_SECCION, ID_AREA_CONOCIMIENTO, 
    DES_AREA_CONOCIMIENTO)
 Values
   ('U114', 'FILOLOGÍA ESPAÑOLA', 'S114', 'FILOLOGIA ESPAÑOLA', '195', 
    'DIDÁCTICA DE LA LENGUA Y LA LITERATURA');
Insert into UXXIRRHH.VUJA_NET_BEP_RH_DEPTO_SECC_AREA
   (ID_DEPARTAMENTO, DES_DEPARTAMENTO, ID_SECCION, DES_SECCION, ID_AREA_CONOCIMIENTO, 
    DES_AREA_CONOCIMIENTO)
 Values
   ('U114', 'FILOLOGÍA ESPAÑOLA', 'S114', 'FILOLOGIA ESPAÑOLA', '575', 
    'LINGÜÍSTICA GENERAL');
Insert into UXXIRRHH.VUJA_NET_BEP_RH_DEPTO_SECC_AREA
   (ID_DEPARTAMENTO, DES_DEPARTAMENTO, ID_SECCION, DES_SECCION, ID_AREA_CONOCIMIENTO, 
    DES_AREA_CONOCIMIENTO)
 Values
   ('U114', 'FILOLOGÍA ESPAÑOLA', 'S114', 'FILOLOGIA ESPAÑOLA', '583', 
    'LITERATURA ESPAÑOLA');
Insert into UXXIRRHH.VUJA_NET_BEP_RH_DEPTO_SECC_AREA
   (ID_DEPARTAMENTO, DES_DEPARTAMENTO, ID_SECCION, DES_SECCION, ID_AREA_CONOCIMIENTO, 
    DES_AREA_CONOCIMIENTO)
 Values
   ('U115', 'FILOLOGÍA INGLESA', 'S115', 'FILOLOGIA INGLESA', '345', 
    'FILOLOGÍA INGLESA');
Insert into UXXIRRHH.VUJA_NET_BEP_RH_DEPTO_SECC_AREA
   (ID_DEPARTAMENTO, DES_DEPARTAMENTO, ID_SECCION, DES_SECCION, ID_AREA_CONOCIMIENTO, 
    DES_AREA_CONOCIMIENTO)
 Values
   ('U115', 'FILOLOGÍA INGLESA', 'S115.', 'FILOLOGÍA INGLESA (LINARES)', '345', 
    'FILOLOGÍA INGLESA');
Insert into UXXIRRHH.VUJA_NET_BEP_RH_DEPTO_SECC_AREA
   (ID_DEPARTAMENTO, DES_DEPARTAMENTO, ID_SECCION, DES_SECCION, ID_AREA_CONOCIMIENTO, 
    DES_AREA_CONOCIMIENTO)
 Values
   ('U117', 'GEOLOGÍA', 'S156', 'Geología', '120', 
    'CRISTALOGRAFÍA Y MINERALOGÍA');
Insert into UXXIRRHH.VUJA_NET_BEP_RH_DEPTO_SECC_AREA
   (ID_DEPARTAMENTO, DES_DEPARTAMENTO, ID_SECCION, DES_SECCION, ID_AREA_CONOCIMIENTO, 
    DES_AREA_CONOCIMIENTO)
 Values
   ('U117', 'GEOLOGÍA', 'S156.', 'GEOLOGÍA (LINARES)', '120', 
    'CRISTALOGRAFÍA Y MINERALOGÍA');
Insert into UXXIRRHH.VUJA_NET_BEP_RH_DEPTO_SECC_AREA
   (ID_DEPARTAMENTO, DES_DEPARTAMENTO, ID_SECCION, DES_SECCION, ID_AREA_CONOCIMIENTO, 
    DES_AREA_CONOCIMIENTO)
 Values
   ('U117', 'GEOLOGÍA', 'S156', 'Geología', '240', 
    'EDAFOLOGÍA Y QUÍMICA AGRÍCOLA');
Insert into UXXIRRHH.VUJA_NET_BEP_RH_DEPTO_SECC_AREA
   (ID_DEPARTAMENTO, DES_DEPARTAMENTO, ID_SECCION, DES_SECCION, ID_AREA_CONOCIMIENTO, 
    DES_AREA_CONOCIMIENTO)
 Values
   ('U117', 'GEOLOGÍA', 'S156.', 'GEOLOGÍA (LINARES)', '240', 
    'EDAFOLOGÍA Y QUÍMICA AGRÍCOLA');
Insert into UXXIRRHH.VUJA_NET_BEP_RH_DEPTO_SECC_AREA
   (ID_DEPARTAMENTO, DES_DEPARTAMENTO, ID_SECCION, DES_SECCION, ID_AREA_CONOCIMIENTO, 
    DES_AREA_CONOCIMIENTO)
 Values
   ('U117', 'GEOLOGÍA', 'S156', 'Geología', '280', 
    'ESTRATIGRAFÍA');
Insert into UXXIRRHH.VUJA_NET_BEP_RH_DEPTO_SECC_AREA
   (ID_DEPARTAMENTO, DES_DEPARTAMENTO, ID_SECCION, DES_SECCION, ID_AREA_CONOCIMIENTO, 
    DES_AREA_CONOCIMIENTO)
 Values
   ('U117', 'GEOLOGÍA', 'S156.', 'GEOLOGÍA (LINARES)', '280', 
    'ESTRATIGRAFÍA');
Insert into UXXIRRHH.VUJA_NET_BEP_RH_DEPTO_SECC_AREA
   (ID_DEPARTAMENTO, DES_DEPARTAMENTO, ID_SECCION, DES_SECCION, ID_AREA_CONOCIMIENTO, 
    DES_AREA_CONOCIMIENTO)
 Values
   ('U118', 'INFORMÁTICA', 'S159', 'Informática', '570', 
    'LENGUAJES Y SISTEMAS INFORMÁTICOS');
Insert into UXXIRRHH.VUJA_NET_BEP_RH_DEPTO_SECC_AREA
   (ID_DEPARTAMENTO, DES_DEPARTAMENTO, ID_SECCION, DES_SECCION, ID_AREA_CONOCIMIENTO, 
    DES_AREA_CONOCIMIENTO)
 Values
   ('U118', 'INFORMÁTICA', 'S159.', 'INFORMÁTICA (LINARES)', '570', 
    'LENGUAJES Y SISTEMAS INFORMÁTICOS');
Insert into UXXIRRHH.VUJA_NET_BEP_RH_DEPTO_SECC_AREA
   (ID_DEPARTAMENTO, DES_DEPARTAMENTO, ID_SECCION, DES_SECCION, ID_AREA_CONOCIMIENTO, 
    DES_AREA_CONOCIMIENTO)
 Values
   ('U119', 'INGENIERÍA CARTOGR. GEODESICA Y FOTOGRAM', 'S119', 'INGENIERIA CARTOGRAFICA GEODESICA Y FOT.', '505', 
    'INGENIERÍA CARTOGRÁFICA, GEODÉSICA Y FOTOGRAMETRÍA');
Insert into UXXIRRHH.VUJA_NET_BEP_RH_DEPTO_SECC_AREA
   (ID_DEPARTAMENTO, DES_DEPARTAMENTO, ID_SECCION, DES_SECCION, ID_AREA_CONOCIMIENTO, 
    DES_AREA_CONOCIMIENTO)
 Values
   ('U119', 'INGENIERÍA CARTOGR. GEODESICA Y FOTOGRAM', 'S119.', 'ING. CARTOGRÁF. GEODES. Y FOT. (LINARES)', '505', 
    'INGENIERÍA CARTOGRÁFICA, GEODÉSICA Y FOTOGRAMETRÍA');
Insert into UXXIRRHH.VUJA_NET_BEP_RH_DEPTO_SECC_AREA
   (ID_DEPARTAMENTO, DES_DEPARTAMENTO, ID_SECCION, DES_SECCION, ID_AREA_CONOCIMIENTO, 
    DES_AREA_CONOCIMIENTO)
 Values
   ('U121', 'INGENIERÍA MECÁNICA Y MINERA', 'S154', 'Ingeniería Mecánica y Minera (Linares)', '545', 
    'INGENIERÍA MECÁNICA');
Insert into UXXIRRHH.VUJA_NET_BEP_RH_DEPTO_SECC_AREA
   (ID_DEPARTAMENTO, DES_DEPARTAMENTO, ID_SECCION, DES_SECCION, ID_AREA_CONOCIMIENTO, 
    DES_AREA_CONOCIMIENTO)
 Values
   ('U121', 'INGENIERÍA MECÁNICA Y MINERA', 'S1541', 'Ingeniería Mecánica y Minera EPS', '545', 
    'INGENIERÍA MECÁNICA');
Insert into UXXIRRHH.VUJA_NET_BEP_RH_DEPTO_SECC_AREA
   (ID_DEPARTAMENTO, DES_DEPARTAMENTO, ID_SECCION, DES_SECCION, ID_AREA_CONOCIMIENTO, 
    DES_AREA_CONOCIMIENTO)
 Values
   ('U121', 'INGENIERÍA MECÁNICA Y MINERA', 'S154', 'Ingeniería Mecánica y Minera (Linares)', '600', 
    'MECÁNICA DE FLUIDOS');
Insert into UXXIRRHH.VUJA_NET_BEP_RH_DEPTO_SECC_AREA
   (ID_DEPARTAMENTO, DES_DEPARTAMENTO, ID_SECCION, DES_SECCION, ID_AREA_CONOCIMIENTO, 
    DES_AREA_CONOCIMIENTO)
 Values
   ('U121', 'INGENIERÍA MECÁNICA Y MINERA', 'S1541', 'Ingeniería Mecánica y Minera EPS', '600', 
    'MECÁNICA DE FLUIDOS');
Insert into UXXIRRHH.VUJA_NET_BEP_RH_DEPTO_SECC_AREA
   (ID_DEPARTAMENTO, DES_DEPARTAMENTO, ID_SECCION, DES_SECCION, ID_AREA_CONOCIMIENTO, 
    DES_AREA_CONOCIMIENTO)
 Values
   ('U122', 'INGENIERÍA QUIM.,AMBIENTAL Y DE LOS MAT.', 'S151', 'Ingeniería Química, Ambiental y de los M', '555', 
    'INGENIERÍA QUÍMICA');
Insert into UXXIRRHH.VUJA_NET_BEP_RH_DEPTO_SECC_AREA
   (ID_DEPARTAMENTO, DES_DEPARTAMENTO, ID_SECCION, DES_SECCION, ID_AREA_CONOCIMIENTO, 
    DES_AREA_CONOCIMIENTO)
 Values
   ('U122', 'INGENIERÍA QUIM.,AMBIENTAL Y DE LOS MAT.', 'S151.', 'IN. QUÍM, AMBIENTAL Y DE LOS M (LINARES)', '555', 
    'INGENIERÍA QUÍMICA');
Insert into UXXIRRHH.VUJA_NET_BEP_RH_DEPTO_SECC_AREA
   (ID_DEPARTAMENTO, DES_DEPARTAMENTO, ID_SECCION, DES_SECCION, ID_AREA_CONOCIMIENTO, 
    DES_AREA_CONOCIMIENTO)
 Values
   ('U122', 'INGENIERÍA QUIM.,AMBIENTAL Y DE LOS MAT.', 'S151', 'Ingeniería Química, Ambiental y de los M', '790', 
    'TECNOLOGIAS DEL MEDIO AMBIENTE');
Insert into UXXIRRHH.VUJA_NET_BEP_RH_DEPTO_SECC_AREA
   (ID_DEPARTAMENTO, DES_DEPARTAMENTO, ID_SECCION, DES_SECCION, ID_AREA_CONOCIMIENTO, 
    DES_AREA_CONOCIMIENTO)
 Values
   ('U122', 'INGENIERÍA QUIM.,AMBIENTAL Y DE LOS MAT.', 'S151.', 'IN. QUÍM, AMBIENTAL Y DE LOS M (LINARES)', '790', 
    'TECNOLOGIAS DEL MEDIO AMBIENTE');
Insert into UXXIRRHH.VUJA_NET_BEP_RH_DEPTO_SECC_AREA
   (ID_DEPARTAMENTO, DES_DEPARTAMENTO, ID_SECCION, DES_SECCION, ID_AREA_CONOCIMIENTO, 
    DES_AREA_CONOCIMIENTO)
 Values
   ('U123', 'LENGUAS Y CULTURAS MEDITERRÁNEAS', 'S123', 'LENGUAS Y CULTURAS MEDITERRANEAS', '285', 
    'ESTUDIOS ÁRABES E ISLÁMICOS');
Insert into UXXIRRHH.VUJA_NET_BEP_RH_DEPTO_SECC_AREA
   (ID_DEPARTAMENTO, DES_DEPARTAMENTO, ID_SECCION, DES_SECCION, ID_AREA_CONOCIMIENTO, 
    DES_AREA_CONOCIMIENTO)
 Values
   ('U124', 'MATEMÁTICAS', 'S152', 'Matemáticas', '005', 
    'ÁLGEBRA');
Insert into UXXIRRHH.VUJA_NET_BEP_RH_DEPTO_SECC_AREA
   (ID_DEPARTAMENTO, DES_DEPARTAMENTO, ID_SECCION, DES_SECCION, ID_AREA_CONOCIMIENTO, 
    DES_AREA_CONOCIMIENTO)
 Values
   ('U124', 'MATEMÁTICAS', 'S152.', 'MATEMÁTICAS (LINARES)', '005', 
    'ÁLGEBRA');
Insert into UXXIRRHH.VUJA_NET_BEP_RH_DEPTO_SECC_AREA
   (ID_DEPARTAMENTO, DES_DEPARTAMENTO, ID_SECCION, DES_SECCION, ID_AREA_CONOCIMIENTO, 
    DES_AREA_CONOCIMIENTO)
 Values
   ('U124', 'MATEMÁTICAS', 'S152', 'Matemáticas', '015', 
    'ANÁLISIS MATEMÁTICO');
Insert into UXXIRRHH.VUJA_NET_BEP_RH_DEPTO_SECC_AREA
   (ID_DEPARTAMENTO, DES_DEPARTAMENTO, ID_SECCION, DES_SECCION, ID_AREA_CONOCIMIENTO, 
    DES_AREA_CONOCIMIENTO)
 Values
   ('U124', 'MATEMÁTICAS', 'S152.', 'MATEMÁTICAS (LINARES)', '015', 
    'ANÁLISIS MATEMÁTICO');
Insert into UXXIRRHH.VUJA_NET_BEP_RH_DEPTO_SECC_AREA
   (ID_DEPARTAMENTO, DES_DEPARTAMENTO, ID_SECCION, DES_SECCION, ID_AREA_CONOCIMIENTO, 
    DES_AREA_CONOCIMIENTO)
 Values
   ('U125', 'PEDAGOGÍA', 'S125', 'PEDAGOGIA', '215', 
    'DIDÁCTICA Y ORGANIZACIÓN ESCOLAR');
Insert into UXXIRRHH.VUJA_NET_BEP_RH_DEPTO_SECC_AREA
   (ID_DEPARTAMENTO, DES_DEPARTAMENTO, ID_SECCION, DES_SECCION, ID_AREA_CONOCIMIENTO, 
    DES_AREA_CONOCIMIENTO)
 Values
   ('U125', 'PEDAGOGÍA', 'S125', 'PEDAGOGIA', '805', 
    'TEORÍA E HISTORIA DE LA EDUCACIÓN');
Insert into UXXIRRHH.VUJA_NET_BEP_RH_DEPTO_SECC_AREA
   (ID_DEPARTAMENTO, DES_DEPARTAMENTO, ID_SECCION, DES_SECCION, ID_AREA_CONOCIMIENTO, 
    DES_AREA_CONOCIMIENTO)
 Values
   ('U126', 'PSICOLOGÍA', 'S158', '01', '620', 
    'METODOLOGÍA DE LAS CIENCIAS DEL COMPORTAMIENTO');
Insert into UXXIRRHH.VUJA_NET_BEP_RH_DEPTO_SECC_AREA
   (ID_DEPARTAMENTO, DES_DEPARTAMENTO, ID_SECCION, DES_SECCION, ID_AREA_CONOCIMIENTO, 
    DES_AREA_CONOCIMIENTO)
 Values
   ('U126', 'PSICOLOGÍA', 'S158', '01', '725', 
    'PSICOBIOLOGÍA');
Insert into UXXIRRHH.VUJA_NET_BEP_RH_DEPTO_SECC_AREA
   (ID_DEPARTAMENTO, DES_DEPARTAMENTO, ID_SECCION, DES_SECCION, ID_AREA_CONOCIMIENTO, 
    DES_AREA_CONOCIMIENTO)
 Values
   ('U126', 'PSICOLOGÍA', 'S158', '01', '730', 
    'PSICOLOGÍA BÁSICA');
Insert into UXXIRRHH.VUJA_NET_BEP_RH_DEPTO_SECC_AREA
   (ID_DEPARTAMENTO, DES_DEPARTAMENTO, ID_SECCION, DES_SECCION, ID_AREA_CONOCIMIENTO, 
    DES_AREA_CONOCIMIENTO)
 Values
   ('U126', 'PSICOLOGÍA', 'S158', '01', '735', 
    'PSICOLOGÍA EVOLUTIVA Y DE LA EDUCACIÓN');
Insert into UXXIRRHH.VUJA_NET_BEP_RH_DEPTO_SECC_AREA
   (ID_DEPARTAMENTO, DES_DEPARTAMENTO, ID_SECCION, DES_SECCION, ID_AREA_CONOCIMIENTO, 
    DES_AREA_CONOCIMIENTO)
 Values
   ('U126', 'PSICOLOGÍA', 'S158', '01', '813', 
    'TRABAJO SOCIAL Y SERVICIOS SOCIALES');
Insert into UXXIRRHH.VUJA_NET_BEP_RH_DEPTO_SECC_AREA
   (ID_DEPARTAMENTO, DES_DEPARTAMENTO, ID_SECCION, DES_SECCION, ID_AREA_CONOCIMIENTO, 
    DES_AREA_CONOCIMIENTO)
 Values
   ('U126', 'PSICOLOGÍA', 'S158"', 'Psicología (trabajo social)', '813', 
    'TRABAJO SOCIAL Y SERVICIOS SOCIALES');
Insert into UXXIRRHH.VUJA_NET_BEP_RH_DEPTO_SECC_AREA
   (ID_DEPARTAMENTO, DES_DEPARTAMENTO, ID_SECCION, DES_SECCION, ID_AREA_CONOCIMIENTO, 
    DES_AREA_CONOCIMIENTO)
 Values
   ('U127', 'QUÍMICA FÍSICA Y ANALÍTICA', 'S127', 'QUIMICA FISICA Y ANALITICA', '750', 
    'QUÍMICA ANALÍTICA');
Insert into UXXIRRHH.VUJA_NET_BEP_RH_DEPTO_SECC_AREA
   (ID_DEPARTAMENTO, DES_DEPARTAMENTO, ID_SECCION, DES_SECCION, ID_AREA_CONOCIMIENTO, 
    DES_AREA_CONOCIMIENTO)
 Values
   ('U127', 'QUÍMICA FÍSICA Y ANALÍTICA', 'S127.', 'QUÍMICA FÍSICA Y ANALÍTICA (LINARES)', '750', 
    'QUÍMICA ANALÍTICA');
Insert into UXXIRRHH.VUJA_NET_BEP_RH_DEPTO_SECC_AREA
   (ID_DEPARTAMENTO, DES_DEPARTAMENTO, ID_SECCION, DES_SECCION, ID_AREA_CONOCIMIENTO, 
    DES_AREA_CONOCIMIENTO)
 Values
   ('U128', 'QUÍMICA INORGÁNICA Y ORGÁNICA', 'S128', 'QUIMICA INORGANICA Y ORGANICA', '760', 
    'QUÍMICA INORGÁNICA');
Insert into UXXIRRHH.VUJA_NET_BEP_RH_DEPTO_SECC_AREA
   (ID_DEPARTAMENTO, DES_DEPARTAMENTO, ID_SECCION, DES_SECCION, ID_AREA_CONOCIMIENTO, 
    DES_AREA_CONOCIMIENTO)
 Values
   ('U128', 'QUÍMICA INORGÁNICA Y ORGÁNICA', 'S128.', 'QUÍMICA INORGÁNICA Y ORGÁNICA (LINARES)', '760', 
    'QUÍMICA INORGÁNICA');
Insert into UXXIRRHH.VUJA_NET_BEP_RH_DEPTO_SECC_AREA
   (ID_DEPARTAMENTO, DES_DEPARTAMENTO, ID_SECCION, DES_SECCION, ID_AREA_CONOCIMIENTO, 
    DES_AREA_CONOCIMIENTO)
 Values
   ('U128', 'QUÍMICA INORGÁNICA Y ORGÁNICA', 'S128', 'QUIMICA INORGANICA Y ORGANICA', '765', 
    'QUÍMICA ORGÁNICA');
Insert into UXXIRRHH.VUJA_NET_BEP_RH_DEPTO_SECC_AREA
   (ID_DEPARTAMENTO, DES_DEPARTAMENTO, ID_SECCION, DES_SECCION, ID_AREA_CONOCIMIENTO, 
    DES_AREA_CONOCIMIENTO)
 Values
   ('U128', 'QUÍMICA INORGÁNICA Y ORGÁNICA', 'S128.', 'QUÍMICA INORGÁNICA Y ORGÁNICA (LINARES)', '765', 
    'QUÍMICA ORGÁNICA');
Insert into UXXIRRHH.VUJA_NET_BEP_RH_DEPTO_SECC_AREA
   (ID_DEPARTAMENTO, DES_DEPARTAMENTO, ID_SECCION, DES_SECCION, ID_AREA_CONOCIMIENTO, 
    DES_AREA_CONOCIMIENTO)
 Values
   ('U129', 'TERRITORIO Y PATRIMONIO HISTÓRICO', 'S129', 'TERRITORIO Y PATRIMONIO HISTORICO', '033', 
    'ARQUEOLOGÍA');
Insert into UXXIRRHH.VUJA_NET_BEP_RH_DEPTO_SECC_AREA
   (ID_DEPARTAMENTO, DES_DEPARTAMENTO, ID_SECCION, DES_SECCION, ID_AREA_CONOCIMIENTO, 
    DES_AREA_CONOCIMIENTO)
 Values
   ('U131', 'PATRIMONIO HISTORICO', 'S131', 'PATRIMONIO HISTORICO', '033', 
    'ARQUEOLOGÍA');
Insert into UXXIRRHH.VUJA_NET_BEP_RH_DEPTO_SECC_AREA
   (ID_DEPARTAMENTO, DES_DEPARTAMENTO, ID_SECCION, DES_SECCION, ID_AREA_CONOCIMIENTO, 
    DES_AREA_CONOCIMIENTO)
 Values
   ('IUAI', 'INSTITUTO UNIV. DE ARQUEOLOGIA IBERICA', 'SIUAI', 'INSTITUTO UNIV. DE ARQUEOLOGIA IBERICA', '033', 
    'ARQUEOLOGÍA');
Insert into UXXIRRHH.VUJA_NET_BEP_RH_DEPTO_SECC_AREA
   (ID_DEPARTAMENTO, DES_DEPARTAMENTO, ID_SECCION, DES_SECCION, ID_AREA_CONOCIMIENTO, 
    DES_AREA_CONOCIMIENTO)
 Values
   ('U129', 'TERRITORIO Y PATRIMONIO HISTÓRICO', 'S129', 'TERRITORIO Y PATRIMONIO HISTORICO', '435', 
    'GEOGRAFÍA HUMANA');
Insert into UXXIRRHH.VUJA_NET_BEP_RH_DEPTO_SECC_AREA
   (ID_DEPARTAMENTO, DES_DEPARTAMENTO, ID_SECCION, DES_SECCION, ID_AREA_CONOCIMIENTO, 
    DES_AREA_CONOCIMIENTO)
 Values
   ('U132', 'ANTROPOLOGIA, GEOGRAFÍA E HISTORIA', 'S132', 'ANTROPOLOGIA, GEOGRAFÍA E HISTORIA', '435', 
    'GEOGRAFÍA HUMANA');
Insert into UXXIRRHH.VUJA_NET_BEP_RH_DEPTO_SECC_AREA
   (ID_DEPARTAMENTO, DES_DEPARTAMENTO, ID_SECCION, DES_SECCION, ID_AREA_CONOCIMIENTO, 
    DES_AREA_CONOCIMIENTO)
 Values
   ('U129', 'TERRITORIO Y PATRIMONIO HISTÓRICO', 'S129', 'TERRITORIO Y PATRIMONIO HISTORICO', '485', 
    'HISTORIA MEDIEVAL');
Insert into UXXIRRHH.VUJA_NET_BEP_RH_DEPTO_SECC_AREA
   (ID_DEPARTAMENTO, DES_DEPARTAMENTO, ID_SECCION, DES_SECCION, ID_AREA_CONOCIMIENTO, 
    DES_AREA_CONOCIMIENTO)
 Values
   ('U131', 'PATRIMONIO HISTORICO', 'S131', 'PATRIMONIO HISTORICO', '485', 
    'HISTORIA MEDIEVAL');
Insert into UXXIRRHH.VUJA_NET_BEP_RH_DEPTO_SECC_AREA
   (ID_DEPARTAMENTO, DES_DEPARTAMENTO, ID_SECCION, DES_SECCION, ID_AREA_CONOCIMIENTO, 
    DES_AREA_CONOCIMIENTO)
 Values
   ('U129', 'TERRITORIO Y PATRIMONIO HISTÓRICO', 'S129', 'TERRITORIO Y PATRIMONIO HISTORICO', '695', 
    'PREHISTORIA');
Insert into UXXIRRHH.VUJA_NET_BEP_RH_DEPTO_SECC_AREA
   (ID_DEPARTAMENTO, DES_DEPARTAMENTO, ID_SECCION, DES_SECCION, ID_AREA_CONOCIMIENTO, 
    DES_AREA_CONOCIMIENTO)
 Values
   ('U131', 'PATRIMONIO HISTORICO', 'S131', 'PATRIMONIO HISTORICO', '695', 
    'PREHISTORIA');
Insert into UXXIRRHH.VUJA_NET_BEP_RH_DEPTO_SECC_AREA
   (ID_DEPARTAMENTO, DES_DEPARTAMENTO, ID_SECCION, DES_SECCION, ID_AREA_CONOCIMIENTO, 
    DES_AREA_CONOCIMIENTO)
 Values
   ('U130', 'CIENCIAS DE LA SALUD', 'S130', 'CIENCIAS DE LA SALUD (EXPERIMENTALES)', '080', 
    'CIENCIAS MORFOLÓGICAS');
Insert into UXXIRRHH.VUJA_NET_BEP_RH_DEPTO_SECC_AREA
   (ID_DEPARTAMENTO, DES_DEPARTAMENTO, ID_SECCION, DES_SECCION, ID_AREA_CONOCIMIENTO, 
    DES_AREA_CONOCIMIENTO)
 Values
   ('U130', 'CIENCIAS DE LA SALUD', 'S130*', 'CIENCIAS DE LA SALUD (LINARES)', '080', 
    'CIENCIAS MORFOLÓGICAS');
Insert into UXXIRRHH.VUJA_NET_BEP_RH_DEPTO_SECC_AREA
   (ID_DEPARTAMENTO, DES_DEPARTAMENTO, ID_SECCION, DES_SECCION, ID_AREA_CONOCIMIENTO, 
    DES_AREA_CONOCIMIENTO)
 Values
   ('U130', 'CIENCIAS DE LA SALUD', 'S130', 'CIENCIAS DE LA SALUD (EXPERIMENTALES)', '610', 
    'MEDICINA');
Insert into UXXIRRHH.VUJA_NET_BEP_RH_DEPTO_SECC_AREA
   (ID_DEPARTAMENTO, DES_DEPARTAMENTO, ID_SECCION, DES_SECCION, ID_AREA_CONOCIMIENTO, 
    DES_AREA_CONOCIMIENTO)
 Values
   ('U130', 'CIENCIAS DE LA SALUD', 'S130*', 'CIENCIAS DE LA SALUD (LINARES)', '610', 
    'MEDICINA');
Insert into UXXIRRHH.VUJA_NET_BEP_RH_DEPTO_SECC_AREA
   (ID_DEPARTAMENTO, DES_DEPARTAMENTO, ID_SECCION, DES_SECCION, ID_AREA_CONOCIMIENTO, 
    DES_AREA_CONOCIMIENTO)
 Values
   ('U105', 'DERECHO CIVIL, DCHO. FINAN. Y TRIBUTARIO', 'S105', 'DERECHO CIVIL, D. FINANCIERO Y TRIBUTARI', '150', 
    'DERECHO FINANCIERO Y TRIBUTARIO');
Insert into UXXIRRHH.VUJA_NET_BEP_RH_DEPTO_SECC_AREA
   (ID_DEPARTAMENTO, DES_DEPARTAMENTO, ID_SECCION, DES_SECCION, ID_AREA_CONOCIMIENTO, 
    DES_AREA_CONOCIMIENTO)
 Values
   ('U104', 'DERECHO PÚBLICO Y DERECHO PRIV. ESPECIAL', 'S104', 'DERECHO PUBLICO Y D. PRIVADO ESPECIAL', '155', 
    'DERECHO INTERNACIONAL PRIVADO');
Insert into UXXIRRHH.VUJA_NET_BEP_RH_DEPTO_SECC_AREA
   (ID_DEPARTAMENTO, DES_DEPARTAMENTO, ID_SECCION, DES_SECCION, ID_AREA_CONOCIMIENTO, 
    DES_AREA_CONOCIMIENTO)
 Values
   ('U138', 'DERECHO PÚBLICO Y D. PRIVADO ESPECIAL', 'S138', 'DERECHO PCO. Y DERECHO PRIVADO ESPEC.', '155', 
    'DERECHO INTERNACIONAL PRIVADO');
Insert into UXXIRRHH.VUJA_NET_BEP_RH_DEPTO_SECC_AREA
   (ID_DEPARTAMENTO, DES_DEPARTAMENTO, ID_SECCION, DES_SECCION, ID_AREA_CONOCIMIENTO, 
    DES_AREA_CONOCIMIENTO)
 Values
   ('U105', 'DERECHO CIVIL, DCHO. FINAN. Y TRIBUTARIO', 'S105', 'DERECHO CIVIL, D. FINANCIERO Y TRIBUTARI', '130', 
    'DERECHO CIVIL');
Insert into UXXIRRHH.VUJA_NET_BEP_RH_DEPTO_SECC_AREA
   (ID_DEPARTAMENTO, DES_DEPARTAMENTO, ID_SECCION, DES_SECCION, ID_AREA_CONOCIMIENTO, 
    DES_AREA_CONOCIMIENTO)
 Values
   ('U107', 'DERECHO PENAL, FIL.DCHO. FIL.MORAL Y FIL', 'S107', 'DERECHO PENAL, FIL. DER. FIL.MORAL Y FIL', '375', 
    'FILOSOFÍA');
Insert into UXXIRRHH.VUJA_NET_BEP_RH_DEPTO_SECC_AREA
   (ID_DEPARTAMENTO, DES_DEPARTAMENTO, ID_SECCION, DES_SECCION, ID_AREA_CONOCIMIENTO, 
    DES_AREA_CONOCIMIENTO)
 Values
   ('U107', 'DERECHO PENAL, FIL.DCHO. FIL.MORAL Y FIL', 'S107', 'DERECHO PENAL, FIL. DER. FIL.MORAL Y FIL', '383', 
    'FILOSOFÍA MORAL');
Insert into UXXIRRHH.VUJA_NET_BEP_RH_DEPTO_SECC_AREA
   (ID_DEPARTAMENTO, DES_DEPARTAMENTO, ID_SECCION, DES_SECCION, ID_AREA_CONOCIMIENTO, 
    DES_AREA_CONOCIMIENTO)
 Values
   ('U108', 'DIDÁCTICA DE LAS CIENCIAS', 'S108', 'DIDACTICA DE LAS CIENCIAS', '205', 
    'DIDÁCTICA DE LAS CIENCIAS EXPERIMENTALES');
Insert into UXXIRRHH.VUJA_NET_BEP_RH_DEPTO_SECC_AREA
   (ID_DEPARTAMENTO, DES_DEPARTAMENTO, ID_SECCION, DES_SECCION, ID_AREA_CONOCIMIENTO, 
    DES_AREA_CONOCIMIENTO)
 Values
   ('U110', 'ECONOMIA', 'S110', 'ECONOMIA', '225', 
    'ECONOMÍA APLICADA');
Insert into UXXIRRHH.VUJA_NET_BEP_RH_DEPTO_SECC_AREA
   (ID_DEPARTAMENTO, DES_DEPARTAMENTO, ID_SECCION, DES_SECCION, ID_AREA_CONOCIMIENTO, 
    DES_AREA_CONOCIMIENTO)
 Values
   ('U110', 'ECONOMIA', 'S110.', 'ECONOMIA (LINARES)', '225', 
    'ECONOMÍA APLICADA');
Insert into UXXIRRHH.VUJA_NET_BEP_RH_DEPTO_SECC_AREA
   (ID_DEPARTAMENTO, DES_DEPARTAMENTO, ID_SECCION, DES_SECCION, ID_AREA_CONOCIMIENTO, 
    DES_AREA_CONOCIMIENTO)
 Values
   ('U110', 'ECONOMIA', 'S110', 'ECONOMIA', '415', 
    'FUNDAMENTOS DEL ANÁLISIS ECONÓMICO');
Insert into UXXIRRHH.VUJA_NET_BEP_RH_DEPTO_SECC_AREA
   (ID_DEPARTAMENTO, DES_DEPARTAMENTO, ID_SECCION, DES_SECCION, ID_AREA_CONOCIMIENTO, 
    DES_AREA_CONOCIMIENTO)
 Values
   ('U110', 'ECONOMIA', 'S110.', 'ECONOMIA (LINARES)', '415', 
    'FUNDAMENTOS DEL ANÁLISIS ECONÓMICO');
Insert into UXXIRRHH.VUJA_NET_BEP_RH_DEPTO_SECC_AREA
   (ID_DEPARTAMENTO, DES_DEPARTAMENTO, ID_SECCION, DES_SECCION, ID_AREA_CONOCIMIENTO, 
    DES_AREA_CONOCIMIENTO)
 Values
   ('U111', 'ING ELECTRÓNICA DE TELECOM. Y AUTOMATICA', 'S157', 'Ing. Electónica, de Telecom. y Automat.', '785', 
    'TECNOLOGÍA ELECTRÓNICA');
Insert into UXXIRRHH.VUJA_NET_BEP_RH_DEPTO_SECC_AREA
   (ID_DEPARTAMENTO, DES_DEPARTAMENTO, ID_SECCION, DES_SECCION, ID_AREA_CONOCIMIENTO, 
    DES_AREA_CONOCIMIENTO)
 Values
   ('U133', 'ING. ELECTRÓNICA Y AUTOMATICA', 'S133', 'ING. ELECTRÓNICA Y AUTOMÁTICA', '785', 
    'TECNOLOGÍA ELECTRÓNICA');
Insert into UXXIRRHH.VUJA_NET_BEP_RH_DEPTO_SECC_AREA
   (ID_DEPARTAMENTO, DES_DEPARTAMENTO, ID_SECCION, DES_SECCION, ID_AREA_CONOCIMIENTO, 
    DES_AREA_CONOCIMIENTO)
 Values
   ('U133', 'ING. ELECTRÓNICA Y AUTOMATICA', 'S133.', 'ING. ELECTRÓNICA Y AUTOMÁTICA (LINARES)', '785', 
    'TECNOLOGÍA ELECTRÓNICA');
Insert into UXXIRRHH.VUJA_NET_BEP_RH_DEPTO_SECC_AREA
   (ID_DEPARTAMENTO, DES_DEPARTAMENTO, ID_SECCION, DES_SECCION, ID_AREA_CONOCIMIENTO, 
    DES_AREA_CONOCIMIENTO)
 Values
   ('U117', 'GEOLOGÍA', 'S156', 'Geología', '425', 
    'GEODINÁMICA');
Insert into UXXIRRHH.VUJA_NET_BEP_RH_DEPTO_SECC_AREA
   (ID_DEPARTAMENTO, DES_DEPARTAMENTO, ID_SECCION, DES_SECCION, ID_AREA_CONOCIMIENTO, 
    DES_AREA_CONOCIMIENTO)
 Values
   ('U117', 'GEOLOGÍA', 'S156.', 'GEOLOGÍA (LINARES)', '425', 
    'GEODINÁMICA');
Insert into UXXIRRHH.VUJA_NET_BEP_RH_DEPTO_SECC_AREA
   (ID_DEPARTAMENTO, DES_DEPARTAMENTO, ID_SECCION, DES_SECCION, ID_AREA_CONOCIMIENTO, 
    DES_AREA_CONOCIMIENTO)
 Values
   ('U118', 'INFORMÁTICA', 'S159', 'Informática', '075', 
    'CIENCIA DE LA COMPUTACIÓN E INT. ARTIFICIAL');
Insert into UXXIRRHH.VUJA_NET_BEP_RH_DEPTO_SECC_AREA
   (ID_DEPARTAMENTO, DES_DEPARTAMENTO, ID_SECCION, DES_SECCION, ID_AREA_CONOCIMIENTO, 
    DES_AREA_CONOCIMIENTO)
 Values
   ('U118', 'INFORMÁTICA', 'S159.', 'INFORMÁTICA (LINARES)', '075', 
    'CIENCIA DE LA COMPUTACIÓN E INT. ARTIFICIAL');
Insert into UXXIRRHH.VUJA_NET_BEP_RH_DEPTO_SECC_AREA
   (ID_DEPARTAMENTO, DES_DEPARTAMENTO, ID_SECCION, DES_SECCION, ID_AREA_CONOCIMIENTO, 
    DES_AREA_CONOCIMIENTO)
 Values
   ('U121', 'INGENIERÍA MECÁNICA Y MINERA', 'S154', 'Ingeniería Mecánica y Minera (Linares)', '295', 
    'EXPLOTACIÓN DE MINAS');
Insert into UXXIRRHH.VUJA_NET_BEP_RH_DEPTO_SECC_AREA
   (ID_DEPARTAMENTO, DES_DEPARTAMENTO, ID_SECCION, DES_SECCION, ID_AREA_CONOCIMIENTO, 
    DES_AREA_CONOCIMIENTO)
 Values
   ('U121', 'INGENIERÍA MECÁNICA Y MINERA', 'S1541', 'Ingeniería Mecánica y Minera EPS', '295', 
    'EXPLOTACIÓN DE MINAS');
Insert into UXXIRRHH.VUJA_NET_BEP_RH_DEPTO_SECC_AREA
   (ID_DEPARTAMENTO, DES_DEPARTAMENTO, ID_SECCION, DES_SECCION, ID_AREA_CONOCIMIENTO, 
    DES_AREA_CONOCIMIENTO)
 Values
   ('U121', 'INGENIERÍA MECÁNICA Y MINERA', 'S154', 'Ingeniería Mecánica y Minera (Linares)', '590', 
    'MÁQUINAS Y MOTORES TÉRMICOS');
Insert into UXXIRRHH.VUJA_NET_BEP_RH_DEPTO_SECC_AREA
   (ID_DEPARTAMENTO, DES_DEPARTAMENTO, ID_SECCION, DES_SECCION, ID_AREA_CONOCIMIENTO, 
    DES_AREA_CONOCIMIENTO)
 Values
   ('U121', 'INGENIERÍA MECÁNICA Y MINERA', 'S1541', 'Ingeniería Mecánica y Minera EPS', '590', 
    'MÁQUINAS Y MOTORES TÉRMICOS');
Insert into UXXIRRHH.VUJA_NET_BEP_RH_DEPTO_SECC_AREA
   (ID_DEPARTAMENTO, DES_DEPARTAMENTO, ID_SECCION, DES_SECCION, ID_AREA_CONOCIMIENTO, 
    DES_AREA_CONOCIMIENTO)
 Values
   ('U123', 'LENGUAS Y CULTURAS MEDITERRÁNEAS', 'S123', 'LENGUAS Y CULTURAS MEDITERRANEAS', '335', 
    'FILOLOGÍA FRANCESA');
Insert into UXXIRRHH.VUJA_NET_BEP_RH_DEPTO_SECC_AREA
   (ID_DEPARTAMENTO, DES_DEPARTAMENTO, ID_SECCION, DES_SECCION, ID_AREA_CONOCIMIENTO, 
    DES_AREA_CONOCIMIENTO)
 Values
   ('U123', 'LENGUAS Y CULTURAS MEDITERRÁNEAS', 'S123', 'LENGUAS Y CULTURAS MEDITERRANEAS', '355', 
    'FILOLOGÍA LATINA');
Insert into UXXIRRHH.VUJA_NET_BEP_RH_DEPTO_SECC_AREA
   (ID_DEPARTAMENTO, DES_DEPARTAMENTO, ID_SECCION, DES_SECCION, ID_AREA_CONOCIMIENTO, 
    DES_AREA_CONOCIMIENTO)
 Values
   ('U124', 'MATEMÁTICAS', 'S152', 'Matemáticas', '440', 
    'GEOMETRÍA Y TOPOLOGÍA');
Insert into UXXIRRHH.VUJA_NET_BEP_RH_DEPTO_SECC_AREA
   (ID_DEPARTAMENTO, DES_DEPARTAMENTO, ID_SECCION, DES_SECCION, ID_AREA_CONOCIMIENTO, 
    DES_AREA_CONOCIMIENTO)
 Values
   ('U124', 'MATEMÁTICAS', 'S152.', 'MATEMÁTICAS (LINARES)', '440', 
    'GEOMETRÍA Y TOPOLOGÍA');
Insert into UXXIRRHH.VUJA_NET_BEP_RH_DEPTO_SECC_AREA
   (ID_DEPARTAMENTO, DES_DEPARTAMENTO, ID_SECCION, DES_SECCION, ID_AREA_CONOCIMIENTO, 
    DES_AREA_CONOCIMIENTO)
 Values
   ('U129', 'TERRITORIO Y PATRIMONIO HISTÓRICO', 'S129', 'TERRITORIO Y PATRIMONIO HISTORICO', '010', 
    'ANÁLISIS GEOGRÁFICO REGIONAL');
Insert into UXXIRRHH.VUJA_NET_BEP_RH_DEPTO_SECC_AREA
   (ID_DEPARTAMENTO, DES_DEPARTAMENTO, ID_SECCION, DES_SECCION, ID_AREA_CONOCIMIENTO, 
    DES_AREA_CONOCIMIENTO)
 Values
   ('U132', 'ANTROPOLOGIA, GEOGRAFÍA E HISTORIA', 'S132', 'ANTROPOLOGIA, GEOGRAFÍA E HISTORIA', '010', 
    'ANÁLISIS GEOGRÁFICO REGIONAL');
Insert into UXXIRRHH.VUJA_NET_BEP_RH_DEPTO_SECC_AREA
   (ID_DEPARTAMENTO, DES_DEPARTAMENTO, ID_SECCION, DES_SECCION, ID_AREA_CONOCIMIENTO, 
    DES_AREA_CONOCIMIENTO)
 Values
   ('U129', 'TERRITORIO Y PATRIMONIO HISTÓRICO', 'S129', 'TERRITORIO Y PATRIMONIO HISTORICO', '445', 
    'HISTORIA ANTIGUA');
Insert into UXXIRRHH.VUJA_NET_BEP_RH_DEPTO_SECC_AREA
   (ID_DEPARTAMENTO, DES_DEPARTAMENTO, ID_SECCION, DES_SECCION, ID_AREA_CONOCIMIENTO, 
    DES_AREA_CONOCIMIENTO)
 Values
   ('U132', 'ANTROPOLOGIA, GEOGRAFÍA E HISTORIA', 'S132', 'ANTROPOLOGIA, GEOGRAFÍA E HISTORIA', '445', 
    'HISTORIA ANTIGUA');
Insert into UXXIRRHH.VUJA_NET_BEP_RH_DEPTO_SECC_AREA
   (ID_DEPARTAMENTO, DES_DEPARTAMENTO, ID_SECCION, DES_SECCION, ID_AREA_CONOCIMIENTO, 
    DES_AREA_CONOCIMIENTO)
 Values
   ('U129', 'TERRITORIO Y PATRIMONIO HISTÓRICO', 'S129', 'TERRITORIO Y PATRIMONIO HISTORICO', '465', 
    'HISTORIA DEL ARTE');
Insert into UXXIRRHH.VUJA_NET_BEP_RH_DEPTO_SECC_AREA
   (ID_DEPARTAMENTO, DES_DEPARTAMENTO, ID_SECCION, DES_SECCION, ID_AREA_CONOCIMIENTO, 
    DES_AREA_CONOCIMIENTO)
 Values
   ('U131', 'PATRIMONIO HISTORICO', 'S131', 'PATRIMONIO HISTORICO', '465', 
    'HISTORIA DEL ARTE');
Insert into UXXIRRHH.VUJA_NET_BEP_RH_DEPTO_SECC_AREA
   (ID_DEPARTAMENTO, DES_DEPARTAMENTO, ID_SECCION, DES_SECCION, ID_AREA_CONOCIMIENTO, 
    DES_AREA_CONOCIMIENTO)
 Values
   ('U130', 'CIENCIAS DE LA SALUD', 'S130', 'CIENCIAS DE LA SALUD (EXPERIMENTALES)', '255', 
    'ENFERMERÍA');
Insert into UXXIRRHH.VUJA_NET_BEP_RH_DEPTO_SECC_AREA
   (ID_DEPARTAMENTO, DES_DEPARTAMENTO, ID_SECCION, DES_SECCION, ID_AREA_CONOCIMIENTO, 
    DES_AREA_CONOCIMIENTO)
 Values
   ('U135', 'ENFERMERÍA', 'S135', 'ENFERMERÍA', '255', 
    'ENFERMERÍA');
Insert into UXXIRRHH.VUJA_NET_BEP_RH_DEPTO_SECC_AREA
   (ID_DEPARTAMENTO, DES_DEPARTAMENTO, ID_SECCION, DES_SECCION, ID_AREA_CONOCIMIENTO, 
    DES_AREA_CONOCIMIENTO)
 Values
   ('U130', 'CIENCIAS DE LA SALUD', 'S130.', 'CIENCIAS DE LA SALUD (CIENCIAS SALUD)', '255', 
    'ENFERMERÍA');
Insert into UXXIRRHH.VUJA_NET_BEP_RH_DEPTO_SECC_AREA
   (ID_DEPARTAMENTO, DES_DEPARTAMENTO, ID_SECCION, DES_SECCION, ID_AREA_CONOCIMIENTO, 
    DES_AREA_CONOCIMIENTO)
 Values
   ('U130', 'CIENCIAS DE LA SALUD', 'S130"', 'CIENCIAS DE LA SALUD (FACULTAD)', '255', 
    'ENFERMERÍA');
Insert into UXXIRRHH.VUJA_NET_BEP_RH_DEPTO_SECC_AREA
   (ID_DEPARTAMENTO, DES_DEPARTAMENTO, ID_SECCION, DES_SECCION, ID_AREA_CONOCIMIENTO, 
    DES_AREA_CONOCIMIENTO)
 Values
   ('U135', 'ENFERMERÍA', 'S135.', 'ENFERMERÍA (FACULTAD)', '255', 
    'ENFERMERÍA');
Insert into UXXIRRHH.VUJA_NET_BEP_RH_DEPTO_SECC_AREA
   (ID_DEPARTAMENTO, DES_DEPARTAMENTO, ID_SECCION, DES_SECCION, ID_AREA_CONOCIMIENTO, 
    DES_AREA_CONOCIMIENTO)
 Values
   ('U130', 'CIENCIAS DE LA SALUD', 'S130', 'CIENCIAS DE LA SALUD (EXPERIMENTALES)', '410', 
    'FISIOLOGÍA');
Insert into UXXIRRHH.VUJA_NET_BEP_RH_DEPTO_SECC_AREA
   (ID_DEPARTAMENTO, DES_DEPARTAMENTO, ID_SECCION, DES_SECCION, ID_AREA_CONOCIMIENTO, 
    DES_AREA_CONOCIMIENTO)
 Values
   ('U130', 'CIENCIAS DE LA SALUD', 'S130*', 'CIENCIAS DE LA SALUD (LINARES)', '410', 
    'FISIOLOGÍA');
Insert into UXXIRRHH.VUJA_NET_BEP_RH_DEPTO_SECC_AREA
   (ID_DEPARTAMENTO, DES_DEPARTAMENTO, ID_SECCION, DES_SECCION, ID_AREA_CONOCIMIENTO, 
    DES_AREA_CONOCIMIENTO)
 Values
   ('U123', 'LENGUAS Y CULTURAS MEDITERRÁNEAS', 'S123', 'LENGUAS Y CULTURAS MEDITERRANEAS', '796', 
    'TEORÍA DE LA LITERATURA Y LITERATURA COMPARADA');
Insert into UXXIRRHH.VUJA_NET_BEP_RH_DEPTO_SECC_AREA
   (ID_DEPARTAMENTO, DES_DEPARTAMENTO, ID_SECCION, DES_SECCION, ID_AREA_CONOCIMIENTO, 
    DES_AREA_CONOCIMIENTO)
 Values
   ('U102', 'BIOLOGIA ANIMAL, BIOL.VEGETAL Y ECOLOGIA', 'S102', 'BIOLOGIA ANIMAL, VEGETAL Y ECOLOGIA', '819', 
    'ZOOLOGÍA');
Insert into UXXIRRHH.VUJA_NET_BEP_RH_DEPTO_SECC_AREA
   (ID_DEPARTAMENTO, DES_DEPARTAMENTO, ID_SECCION, DES_SECCION, ID_AREA_CONOCIMIENTO, 
    DES_AREA_CONOCIMIENTO)
 Values
   ('U102', 'BIOLOGIA ANIMAL, BIOL.VEGETAL Y ECOLOGIA', 'S102', 'BIOLOGIA ANIMAL, VEGETAL Y ECOLOGIA', '412', 
    'FISIOLOGÍA VEGETAL');
Insert into UXXIRRHH.VUJA_NET_BEP_RH_DEPTO_SECC_AREA
   (ID_DEPARTAMENTO, DES_DEPARTAMENTO, ID_SECCION, DES_SECCION, ID_AREA_CONOCIMIENTO, 
    DES_AREA_CONOCIMIENTO)
 Values
   ('U102', 'BIOLOGIA ANIMAL, BIOL.VEGETAL Y ECOLOGIA', 'S102', 'BIOLOGIA ANIMAL, VEGETAL Y ECOLOGIA', '063', 
    'BOTÁNICA');
Insert into UXXIRRHH.VUJA_NET_BEP_RH_DEPTO_SECC_AREA
   (ID_DEPARTAMENTO, DES_DEPARTAMENTO, ID_SECCION, DES_SECCION, ID_AREA_CONOCIMIENTO, 
    DES_AREA_CONOCIMIENTO)
 Values
   ('U130', 'CIENCIAS DE LA SALUD', 'S130', 'CIENCIAS DE LA SALUD (EXPERIMENTALES)', '027', 
    'ANATOMÍA Y EMBRIOLOGÍA HUMANA');
Insert into UXXIRRHH.VUJA_NET_BEP_RH_DEPTO_SECC_AREA
   (ID_DEPARTAMENTO, DES_DEPARTAMENTO, ID_SECCION, DES_SECCION, ID_AREA_CONOCIMIENTO, 
    DES_AREA_CONOCIMIENTO)
 Values
   ('U130', 'CIENCIAS DE LA SALUD', 'S130*', 'CIENCIAS DE LA SALUD (LINARES)', '027', 
    'ANATOMÍA Y EMBRIOLOGÍA HUMANA');
Insert into UXXIRRHH.VUJA_NET_BEP_RH_DEPTO_SECC_AREA
   (ID_DEPARTAMENTO, DES_DEPARTAMENTO, ID_SECCION, DES_SECCION, ID_AREA_CONOCIMIENTO, 
    DES_AREA_CONOCIMIENTO)
 Values
   ('U116', 'FÍSICA', 'S153', 'Física', '038', 
    'ASTRONOMÍA Y ASTROFÍSICA');
Insert into UXXIRRHH.VUJA_NET_BEP_RH_DEPTO_SECC_AREA
   (ID_DEPARTAMENTO, DES_DEPARTAMENTO, ID_SECCION, DES_SECCION, ID_AREA_CONOCIMIENTO, 
    DES_AREA_CONOCIMIENTO)
 Values
   ('U116', 'FÍSICA', 'S153.', 'FÍSICA (LINARES)', '038', 
    'ASTRONOMÍA Y ASTROFÍSICA');
Insert into UXXIRRHH.VUJA_NET_BEP_RH_DEPTO_SECC_AREA
   (ID_DEPARTAMENTO, DES_DEPARTAMENTO, ID_SECCION, DES_SECCION, ID_AREA_CONOCIMIENTO, 
    DES_AREA_CONOCIMIENTO)
 Values
   ('U117', 'GEOLOGÍA', 'S156', 'Geología', '427', 
    'GEODINÁMICA EXTERNA');
Insert into UXXIRRHH.VUJA_NET_BEP_RH_DEPTO_SECC_AREA
   (ID_DEPARTAMENTO, DES_DEPARTAMENTO, ID_SECCION, DES_SECCION, ID_AREA_CONOCIMIENTO, 
    DES_AREA_CONOCIMIENTO)
 Values
   ('U117', 'GEOLOGÍA', 'S156.', 'GEOLOGÍA (LINARES)', '427', 
    'GEODINÁMICA EXTERNA');
Insert into UXXIRRHH.VUJA_NET_BEP_RH_DEPTO_SECC_AREA
   (ID_DEPARTAMENTO, DES_DEPARTAMENTO, ID_SECCION, DES_SECCION, ID_AREA_CONOCIMIENTO, 
    DES_AREA_CONOCIMIENTO)
 Values
   ('U117', 'GEOLOGÍA', 'S156', 'Geología', '428', 
    'GEODINAMICA INTERNA');
Insert into UXXIRRHH.VUJA_NET_BEP_RH_DEPTO_SECC_AREA
   (ID_DEPARTAMENTO, DES_DEPARTAMENTO, ID_SECCION, DES_SECCION, ID_AREA_CONOCIMIENTO, 
    DES_AREA_CONOCIMIENTO)
 Values
   ('U117', 'GEOLOGÍA', 'S156.', 'GEOLOGÍA (LINARES)', '428', 
    'GEODINAMICA INTERNA');
Insert into UXXIRRHH.VUJA_NET_BEP_RH_DEPTO_SECC_AREA
   (ID_DEPARTAMENTO, DES_DEPARTAMENTO, ID_SECCION, DES_SECCION, ID_AREA_CONOCIMIENTO, 
    DES_AREA_CONOCIMIENTO)
 Values
   ('U130', 'CIENCIAS DE LA SALUD', 'S130', 'CIENCIAS DE LA SALUD (EXPERIMENTALES)', '566', 
    'INMUNOLOGÍA');
Insert into UXXIRRHH.VUJA_NET_BEP_RH_DEPTO_SECC_AREA
   (ID_DEPARTAMENTO, DES_DEPARTAMENTO, ID_SECCION, DES_SECCION, ID_AREA_CONOCIMIENTO, 
    DES_AREA_CONOCIMIENTO)
 Values
   ('U130', 'CIENCIAS DE LA SALUD', 'S130*', 'CIENCIAS DE LA SALUD (LINARES)', '566', 
    'INMUNOLOGÍA');
Insert into UXXIRRHH.VUJA_NET_BEP_RH_DEPTO_SECC_AREA
   (ID_DEPARTAMENTO, DES_DEPARTAMENTO, ID_SECCION, DES_SECCION, ID_AREA_CONOCIMIENTO, 
    DES_AREA_CONOCIMIENTO)
 Values
   ('U130', 'CIENCIAS DE LA SALUD', 'S130', 'CIENCIAS DE LA SALUD (EXPERIMENTALES)', '413', 
    'FISIOTERAPIA');
Insert into UXXIRRHH.VUJA_NET_BEP_RH_DEPTO_SECC_AREA
   (ID_DEPARTAMENTO, DES_DEPARTAMENTO, ID_SECCION, DES_SECCION, ID_AREA_CONOCIMIENTO, 
    DES_AREA_CONOCIMIENTO)
 Values
   ('U130', 'CIENCIAS DE LA SALUD', 'S130.', 'CIENCIAS DE LA SALUD (CIENCIAS SALUD)', '413', 
    'FISIOTERAPIA');
Insert into UXXIRRHH.VUJA_NET_BEP_RH_DEPTO_SECC_AREA
   (ID_DEPARTAMENTO, DES_DEPARTAMENTO, ID_SECCION, DES_SECCION, ID_AREA_CONOCIMIENTO, 
    DES_AREA_CONOCIMIENTO)
 Values
   ('U130', 'CIENCIAS DE LA SALUD', 'S130"', 'CIENCIAS DE LA SALUD (FACULTAD)', '413', 
    'FISIOTERAPIA');
Insert into UXXIRRHH.VUJA_NET_BEP_RH_DEPTO_SECC_AREA
   (ID_DEPARTAMENTO, DES_DEPARTAMENTO, ID_SECCION, DES_SECCION, ID_AREA_CONOCIMIENTO, 
    DES_AREA_CONOCIMIENTO)
 Values
   ('U130', 'CIENCIAS DE LA SALUD', 'S130*', 'CIENCIAS DE LA SALUD (LINARES)', '413', 
    'FISIOTERAPIA');
Insert into UXXIRRHH.VUJA_NET_BEP_RH_DEPTO_SECC_AREA
   (ID_DEPARTAMENTO, DES_DEPARTAMENTO, ID_SECCION, DES_SECCION, ID_AREA_CONOCIMIENTO, 
    DES_AREA_CONOCIMIENTO)
 Values
   ('U130', 'CIENCIAS DE LA SALUD', 'S130', 'CIENCIAS DE LA SALUD (EXPERIMENTALES)', '090', 
    'CIRUGÍA');
Insert into UXXIRRHH.VUJA_NET_BEP_RH_DEPTO_SECC_AREA
   (ID_DEPARTAMENTO, DES_DEPARTAMENTO, ID_SECCION, DES_SECCION, ID_AREA_CONOCIMIENTO, 
    DES_AREA_CONOCIMIENTO)
 Values
   ('U130', 'CIENCIAS DE LA SALUD', 'S130*', 'CIENCIAS DE LA SALUD (LINARES)', '090', 
    'CIRUGÍA');
Insert into UXXIRRHH.VUJA_NET_BEP_RH_DEPTO_SECC_AREA
   (ID_DEPARTAMENTO, DES_DEPARTAMENTO, ID_SECCION, DES_SECCION, ID_AREA_CONOCIMIENTO, 
    DES_AREA_CONOCIMIENTO)
 Values
   ('U114', 'FILOLOGÍA ESPAÑOLA', 'S114', 'FILOLOGIA ESPAÑOLA', '567', 
    'LENGUA ESPAÑOLA');
Insert into UXXIRRHH.VUJA_NET_BEP_RH_DEPTO_SECC_AREA
   (ID_DEPARTAMENTO, DES_DEPARTAMENTO, ID_SECCION, DES_SECCION, ID_AREA_CONOCIMIENTO, 
    DES_AREA_CONOCIMIENTO)
 Values
   ('U114', 'FILOLOGÍA ESPAÑOLA', 'S114', 'FILOLOGIA ESPAÑOLA', '795', 
    'TEORÍA DE LA LITERATURA');
Insert into UXXIRRHH.VUJA_NET_BEP_RH_DEPTO_SECC_AREA
   (ID_DEPARTAMENTO, DES_DEPARTAMENTO, ID_SECCION, DES_SECCION, ID_AREA_CONOCIMIENTO, 
    DES_AREA_CONOCIMIENTO)
 Values
   ('U123', 'LENGUAS Y CULTURAS MEDITERRÁNEAS', 'S123', 'LENGUAS Y CULTURAS MEDITERRANEAS', '795', 
    'TEORÍA DE LA LITERATURA');
Insert into UXXIRRHH.VUJA_NET_BEP_RH_DEPTO_SECC_AREA
   (ID_DEPARTAMENTO, DES_DEPARTAMENTO, ID_SECCION, DES_SECCION, ID_AREA_CONOCIMIENTO, 
    DES_AREA_CONOCIMIENTO)
 Values
   ('U116', 'FÍSICA', 'S153', 'Física', '400', 
    'FÍSICA DE LA TIERRA, ASTRONOMÍA Y ASTROFÍSICA');
Insert into UXXIRRHH.VUJA_NET_BEP_RH_DEPTO_SECC_AREA
   (ID_DEPARTAMENTO, DES_DEPARTAMENTO, ID_SECCION, DES_SECCION, ID_AREA_CONOCIMIENTO, 
    DES_AREA_CONOCIMIENTO)
 Values
   ('U116', 'FÍSICA', 'S153.', 'FÍSICA (LINARES)', '400', 
    'FÍSICA DE LA TIERRA, ASTRONOMÍA Y ASTROFÍSICA');
Insert into UXXIRRHH.VUJA_NET_BEP_RH_DEPTO_SECC_AREA
   (ID_DEPARTAMENTO, DES_DEPARTAMENTO, ID_SECCION, DES_SECCION, ID_AREA_CONOCIMIENTO, 
    DES_AREA_CONOCIMIENTO)
 Values
   ('U118', 'INFORMÁTICA', 'S159', 'Informática', '035', 
    'ARQUITECTURA Y TECNOLOGÍA DE COMPUTADORES');
Insert into UXXIRRHH.VUJA_NET_BEP_RH_DEPTO_SECC_AREA
   (ID_DEPARTAMENTO, DES_DEPARTAMENTO, ID_SECCION, DES_SECCION, ID_AREA_CONOCIMIENTO, 
    DES_AREA_CONOCIMIENTO)
 Values
   ('U118', 'INFORMÁTICA', 'S159.', 'INFORMÁTICA (LINARES)', '035', 
    'ARQUITECTURA Y TECNOLOGÍA DE COMPUTADORES');
Insert into UXXIRRHH.VUJA_NET_BEP_RH_DEPTO_SECC_AREA
   (ID_DEPARTAMENTO, DES_DEPARTAMENTO, ID_SECCION, DES_SECCION, ID_AREA_CONOCIMIENTO, 
    DES_AREA_CONOCIMIENTO)
 Values
   ('U120', 'INGENIERÍA ELÉCTRICA', 'S155', 'Ingeniería Eléctrica', '535', 
    'INGENIERÍA ELÉCTRICA');
Insert into UXXIRRHH.VUJA_NET_BEP_RH_DEPTO_SECC_AREA
   (ID_DEPARTAMENTO, DES_DEPARTAMENTO, ID_SECCION, DES_SECCION, ID_AREA_CONOCIMIENTO, 
    DES_AREA_CONOCIMIENTO)
 Values
   ('U120', 'INGENIERÍA ELÉCTRICA', 'S155.', 'INGENIERÍA ELÉCTRICA (LINARES)', '535', 
    'INGENIERÍA ELÉCTRICA');
Insert into UXXIRRHH.VUJA_NET_BEP_RH_DEPTO_SECC_AREA
   (ID_DEPARTAMENTO, DES_DEPARTAMENTO, ID_SECCION, DES_SECCION, ID_AREA_CONOCIMIENTO, 
    DES_AREA_CONOCIMIENTO)
 Values
   ('U121', 'INGENIERÍA MECÁNICA Y MINERA', 'S154', 'Ingeniería Mecánica y Minera (Linares)', '710', 
    'PROSPECCIÓN E INVESTIGACIÓN MINERA');
Insert into UXXIRRHH.VUJA_NET_BEP_RH_DEPTO_SECC_AREA
   (ID_DEPARTAMENTO, DES_DEPARTAMENTO, ID_SECCION, DES_SECCION, ID_AREA_CONOCIMIENTO, 
    DES_AREA_CONOCIMIENTO)
 Values
   ('U121', 'INGENIERÍA MECÁNICA Y MINERA', 'S1541', 'Ingeniería Mecánica y Minera EPS', '710', 
    'PROSPECCIÓN E INVESTIGACIÓN MINERA');
Insert into UXXIRRHH.VUJA_NET_BEP_RH_DEPTO_SECC_AREA
   (ID_DEPARTAMENTO, DES_DEPARTAMENTO, ID_SECCION, DES_SECCION, ID_AREA_CONOCIMIENTO, 
    DES_AREA_CONOCIMIENTO)
 Values
   ('U123', 'LENGUAS Y CULTURAS MEDITERRÁNEAS', 'S123', 'LENGUAS Y CULTURAS MEDITERRANEAS', '340', 
    'FILOLOGÍA GRIEGA');
Insert into UXXIRRHH.VUJA_NET_BEP_RH_DEPTO_SECC_AREA
   (ID_DEPARTAMENTO, DES_DEPARTAMENTO, ID_SECCION, DES_SECCION, ID_AREA_CONOCIMIENTO, 
    DES_AREA_CONOCIMIENTO)
 Values
   ('U124', 'MATEMÁTICAS', 'S152', 'Matemáticas', '595', 
    'MATEMÁTICA APLICADA');
Insert into UXXIRRHH.VUJA_NET_BEP_RH_DEPTO_SECC_AREA
   (ID_DEPARTAMENTO, DES_DEPARTAMENTO, ID_SECCION, DES_SECCION, ID_AREA_CONOCIMIENTO, 
    DES_AREA_CONOCIMIENTO)
 Values
   ('U124', 'MATEMÁTICAS', 'S152.', 'MATEMÁTICAS (LINARES)', '595', 
    'MATEMÁTICA APLICADA');
Insert into UXXIRRHH.VUJA_NET_BEP_RH_DEPTO_SECC_AREA
   (ID_DEPARTAMENTO, DES_DEPARTAMENTO, ID_SECCION, DES_SECCION, ID_AREA_CONOCIMIENTO, 
    DES_AREA_CONOCIMIENTO)
 Values
   ('U125', 'PEDAGOGÍA', 'S125', 'PEDAGOGIA', '625', 
    'METODOS DE INVEST. Y DIAGNÓSTICO EN EDUCACIÓN');
Insert into UXXIRRHH.VUJA_NET_BEP_RH_DEPTO_SECC_AREA
   (ID_DEPARTAMENTO, DES_DEPARTAMENTO, ID_SECCION, DES_SECCION, ID_AREA_CONOCIMIENTO, 
    DES_AREA_CONOCIMIENTO)
 Values
   ('U126', 'PSICOLOGÍA', 'S158', '01', '680', 
    'PERSONALIDAD, EVALUACIÓN Y TRATAMIENTO PSICOLÓGICO');
Insert into UXXIRRHH.VUJA_NET_BEP_RH_DEPTO_SECC_AREA
   (ID_DEPARTAMENTO, DES_DEPARTAMENTO, ID_SECCION, DES_SECCION, ID_AREA_CONOCIMIENTO, 
    DES_AREA_CONOCIMIENTO)
 Values
   ('U126', 'PSICOLOGÍA', 'S158', '01', '740', 
    'PSICOLOGÍA SOCIAL');
Insert into UXXIRRHH.VUJA_NET_BEP_RH_DEPTO_SECC_AREA
   (ID_DEPARTAMENTO, DES_DEPARTAMENTO, ID_SECCION, DES_SECCION, ID_AREA_CONOCIMIENTO, 
    DES_AREA_CONOCIMIENTO)
 Values
   ('U127', 'QUÍMICA FÍSICA Y ANALÍTICA', 'S127', 'QUIMICA FISICA Y ANALITICA', '755', 
    'QUÍMICA FÍSICA');
Insert into UXXIRRHH.VUJA_NET_BEP_RH_DEPTO_SECC_AREA
   (ID_DEPARTAMENTO, DES_DEPARTAMENTO, ID_SECCION, DES_SECCION, ID_AREA_CONOCIMIENTO, 
    DES_AREA_CONOCIMIENTO)
 Values
   ('U127', 'QUÍMICA FÍSICA Y ANALÍTICA', 'S127.', 'QUÍMICA FÍSICA Y ANALÍTICA (LINARES)', '755', 
    'QUÍMICA FÍSICA');
Insert into UXXIRRHH.VUJA_NET_BEP_RH_DEPTO_SECC_AREA
   (ID_DEPARTAMENTO, DES_DEPARTAMENTO, ID_SECCION, DES_SECCION, ID_AREA_CONOCIMIENTO, 
    DES_AREA_CONOCIMIENTO)
 Values
   ('U129', 'TERRITORIO Y PATRIMONIO HISTÓRICO', 'S129', 'TERRITORIO Y PATRIMONIO HISTORICO', '030', 
    'ANTROPOLOGÍA SOCIAL');
Insert into UXXIRRHH.VUJA_NET_BEP_RH_DEPTO_SECC_AREA
   (ID_DEPARTAMENTO, DES_DEPARTAMENTO, ID_SECCION, DES_SECCION, ID_AREA_CONOCIMIENTO, 
    DES_AREA_CONOCIMIENTO)
 Values
   ('U132', 'ANTROPOLOGIA, GEOGRAFÍA E HISTORIA', 'S132', 'ANTROPOLOGIA, GEOGRAFÍA E HISTORIA', '030', 
    'ANTROPOLOGÍA SOCIAL');
Insert into UXXIRRHH.VUJA_NET_BEP_RH_DEPTO_SECC_AREA
   (ID_DEPARTAMENTO, DES_DEPARTAMENTO, ID_SECCION, DES_SECCION, ID_AREA_CONOCIMIENTO, 
    DES_AREA_CONOCIMIENTO)
 Values
   ('U129', 'TERRITORIO Y PATRIMONIO HISTÓRICO', 'S129', 'TERRITORIO Y PATRIMONIO HISTORICO', '450', 
    'HISTORIA CONTEMPORÁNEA');
Insert into UXXIRRHH.VUJA_NET_BEP_RH_DEPTO_SECC_AREA
   (ID_DEPARTAMENTO, DES_DEPARTAMENTO, ID_SECCION, DES_SECCION, ID_AREA_CONOCIMIENTO, 
    DES_AREA_CONOCIMIENTO)
 Values
   ('U132', 'ANTROPOLOGIA, GEOGRAFÍA E HISTORIA', 'S132', 'ANTROPOLOGIA, GEOGRAFÍA E HISTORIA', '450', 
    'HISTORIA CONTEMPORÁNEA');
Insert into UXXIRRHH.VUJA_NET_BEP_RH_DEPTO_SECC_AREA
   (ID_DEPARTAMENTO, DES_DEPARTAMENTO, ID_SECCION, DES_SECCION, ID_AREA_CONOCIMIENTO, 
    DES_AREA_CONOCIMIENTO)
 Values
   ('U130', 'CIENCIAS DE LA SALUD', 'S130', 'CIENCIAS DE LA SALUD (EXPERIMENTALES)', '630', 
    'MICROBIOLOGÍA');
Insert into UXXIRRHH.VUJA_NET_BEP_RH_DEPTO_SECC_AREA
   (ID_DEPARTAMENTO, DES_DEPARTAMENTO, ID_SECCION, DES_SECCION, ID_AREA_CONOCIMIENTO, 
    DES_AREA_CONOCIMIENTO)
 Values
   ('U130', 'CIENCIAS DE LA SALUD', 'S130*', 'CIENCIAS DE LA SALUD (LINARES)', '630', 
    'MICROBIOLOGÍA');
Insert into UXXIRRHH.VUJA_NET_BEP_RH_DEPTO_SECC_AREA
   (ID_DEPARTAMENTO, DES_DEPARTAMENTO, ID_SECCION, DES_SECCION, ID_AREA_CONOCIMIENTO, 
    DES_AREA_CONOCIMIENTO)
 Values
   ('U104', 'DERECHO PÚBLICO Y DERECHO PRIV. ESPECIAL', 'S104', 'DERECHO PUBLICO Y D. PRIVADO ESPECIAL', '135', 
    'DERECHO CONSTITUCIONAL');
Insert into UXXIRRHH.VUJA_NET_BEP_RH_DEPTO_SECC_AREA
   (ID_DEPARTAMENTO, DES_DEPARTAMENTO, ID_SECCION, DES_SECCION, ID_AREA_CONOCIMIENTO, 
    DES_AREA_CONOCIMIENTO)
 Values
   ('U139', 'DERECHO PÚBLICO', 'S139', 'DERECHO PÚBLICO', '135', 
    'DERECHO CONSTITUCIONAL');
Insert into UXXIRRHH.VUJA_NET_BEP_RH_DEPTO_SECC_AREA
   (ID_DEPARTAMENTO, DES_DEPARTAMENTO, ID_SECCION, DES_SECCION, ID_AREA_CONOCIMIENTO, 
    DES_AREA_CONOCIMIENTO)
 Values
   ('U106', 'DERECHO ECLES.,INTER.PUBL., PROC. Y ROM.', 'S106', 'DERECHO ECLES.,INT. PUB.,PROC Y ROM', '160', 
    'DCHO. INTERNACIONAL PÚBLICO Y REL. INTERNACIONALES');
Insert into UXXIRRHH.VUJA_NET_BEP_RH_DEPTO_SECC_AREA
   (ID_DEPARTAMENTO, DES_DEPARTAMENTO, ID_SECCION, DES_SECCION, ID_AREA_CONOCIMIENTO, 
    DES_AREA_CONOCIMIENTO)
 Values
   ('U140', 'DERECHO PÚBLICO Y COMÚN EUROPEO', 'S140', 'PÚBLICO Y COMÚN EUROPEO', '160', 
    'DCHO. INTERNACIONAL PÚBLICO Y REL. INTERNACIONALES');
Insert into UXXIRRHH.VUJA_NET_BEP_RH_DEPTO_SECC_AREA
   (ID_DEPARTAMENTO, DES_DEPARTAMENTO, ID_SECCION, DES_SECCION, ID_AREA_CONOCIMIENTO, 
    DES_AREA_CONOCIMIENTO)
 Values
   ('U109', 'DIDACTICA EXPR. MUSICAL PLASTICA y CORP.', 'S109', 'DIDACT. EXPR. MUS., PLASTICA Y CORPORAL', '189', 
    'DIDÁCTICA DE LA EXPRESIÓN MUSICAL');
Insert into UXXIRRHH.VUJA_NET_BEP_RH_DEPTO_SECC_AREA
   (ID_DEPARTAMENTO, DES_DEPARTAMENTO, ID_SECCION, DES_SECCION, ID_AREA_CONOCIMIENTO, 
    DES_AREA_CONOCIMIENTO)
 Values
   ('U116', 'FÍSICA', 'S153', 'Física', '385', 
    'FÍSICA APLICADA');
Insert into UXXIRRHH.VUJA_NET_BEP_RH_DEPTO_SECC_AREA
   (ID_DEPARTAMENTO, DES_DEPARTAMENTO, ID_SECCION, DES_SECCION, ID_AREA_CONOCIMIENTO, 
    DES_AREA_CONOCIMIENTO)
 Values
   ('U116', 'FÍSICA', 'S153.', 'FÍSICA (LINARES)', '385', 
    'FÍSICA APLICADA');
Insert into UXXIRRHH.VUJA_NET_BEP_RH_DEPTO_SECC_AREA
   (ID_DEPARTAMENTO, DES_DEPARTAMENTO, ID_SECCION, DES_SECCION, ID_AREA_CONOCIMIENTO, 
    DES_AREA_CONOCIMIENTO)
 Values
   ('U116', 'FÍSICA', 'S153', 'Física', '605', 
    'MECÁNICA DE MEDIOS CONTINUOS Y TEORÍA DE ESTRUCTUR');
Insert into UXXIRRHH.VUJA_NET_BEP_RH_DEPTO_SECC_AREA
   (ID_DEPARTAMENTO, DES_DEPARTAMENTO, ID_SECCION, DES_SECCION, ID_AREA_CONOCIMIENTO, 
    DES_AREA_CONOCIMIENTO)
 Values
   ('U121', 'INGENIERÍA MECÁNICA Y MINERA', 'S154', 'Ingeniería Mecánica y Minera (Linares)', '605', 
    'MECÁNICA DE MEDIOS CONTINUOS Y TEORÍA DE ESTRUCTUR');
Insert into UXXIRRHH.VUJA_NET_BEP_RH_DEPTO_SECC_AREA
   (ID_DEPARTAMENTO, DES_DEPARTAMENTO, ID_SECCION, DES_SECCION, ID_AREA_CONOCIMIENTO, 
    DES_AREA_CONOCIMIENTO)
 Values
   ('U121', 'INGENIERÍA MECÁNICA Y MINERA', 'S1541', 'Ingeniería Mecánica y Minera EPS', '605', 
    'MECÁNICA DE MEDIOS CONTINUOS Y TEORÍA DE ESTRUCTUR');
Insert into UXXIRRHH.VUJA_NET_BEP_RH_DEPTO_SECC_AREA
   (ID_DEPARTAMENTO, DES_DEPARTAMENTO, ID_SECCION, DES_SECCION, ID_AREA_CONOCIMIENTO, 
    DES_AREA_CONOCIMIENTO)
 Values
   ('U116', 'FÍSICA', 'S153.', 'FÍSICA (LINARES)', '605', 
    'MECÁNICA DE MEDIOS CONTINUOS Y TEORÍA DE ESTRUCTUR');
Insert into UXXIRRHH.VUJA_NET_BEP_RH_DEPTO_SECC_AREA
   (ID_DEPARTAMENTO, DES_DEPARTAMENTO, ID_SECCION, DES_SECCION, ID_AREA_CONOCIMIENTO, 
    DES_AREA_CONOCIMIENTO)
 Values
   ('U122', 'INGENIERÍA QUIM.,AMBIENTAL Y DE LOS MAT.', 'S151', 'Ingeniería Química, Ambiental y de los M', '065', 
    'CIENCIA DE MATERIALES E INGENIERÍA METALÚRGICA');
Insert into UXXIRRHH.VUJA_NET_BEP_RH_DEPTO_SECC_AREA
   (ID_DEPARTAMENTO, DES_DEPARTAMENTO, ID_SECCION, DES_SECCION, ID_AREA_CONOCIMIENTO, 
    DES_AREA_CONOCIMIENTO)
 Values
   ('U122', 'INGENIERÍA QUIM.,AMBIENTAL Y DE LOS MAT.', 'S151.', 'IN. QUÍM, AMBIENTAL Y DE LOS M (LINARES)', '065', 
    'CIENCIA DE MATERIALES E INGENIERÍA METALÚRGICA');
Insert into UXXIRRHH.VUJA_NET_BEP_RH_DEPTO_SECC_AREA
   (ID_DEPARTAMENTO, DES_DEPARTAMENTO, ID_SECCION, DES_SECCION, ID_AREA_CONOCIMIENTO, 
    DES_AREA_CONOCIMIENTO)
 Values
   ('U129', 'TERRITORIO Y PATRIMONIO HISTÓRICO', 'S129', 'TERRITORIO Y PATRIMONIO HISTORICO', '430', 
    'GEOGRAFÍA FÍSICA');
Insert into UXXIRRHH.VUJA_NET_BEP_RH_DEPTO_SECC_AREA
   (ID_DEPARTAMENTO, DES_DEPARTAMENTO, ID_SECCION, DES_SECCION, ID_AREA_CONOCIMIENTO, 
    DES_AREA_CONOCIMIENTO)
 Values
   ('U132', 'ANTROPOLOGIA, GEOGRAFÍA E HISTORIA', 'S132', 'ANTROPOLOGIA, GEOGRAFÍA E HISTORIA', '430', 
    'GEOGRAFÍA FÍSICA');
Insert into UXXIRRHH.VUJA_NET_BEP_RH_DEPTO_SECC_AREA
   (ID_DEPARTAMENTO, DES_DEPARTAMENTO, ID_SECCION, DES_SECCION, ID_AREA_CONOCIMIENTO, 
    DES_AREA_CONOCIMIENTO)
 Values
   ('U129', 'TERRITORIO Y PATRIMONIO HISTÓRICO', 'S129', 'TERRITORIO Y PATRIMONIO HISTORICO', '490', 
    'HISTORIA MODERNA');
Insert into UXXIRRHH.VUJA_NET_BEP_RH_DEPTO_SECC_AREA
   (ID_DEPARTAMENTO, DES_DEPARTAMENTO, ID_SECCION, DES_SECCION, ID_AREA_CONOCIMIENTO, 
    DES_AREA_CONOCIMIENTO)
 Values
   ('U132', 'ANTROPOLOGIA, GEOGRAFÍA E HISTORIA', 'S132', 'ANTROPOLOGIA, GEOGRAFÍA E HISTORIA', '490', 
    'HISTORIA MODERNA');
Insert into UXXIRRHH.VUJA_NET_BEP_RH_DEPTO_SECC_AREA
   (ID_DEPARTAMENTO, DES_DEPARTAMENTO, ID_SECCION, DES_SECCION, ID_AREA_CONOCIMIENTO, 
    DES_AREA_CONOCIMIENTO)
 Values
   ('U130', 'CIENCIAS DE LA SALUD', 'S130', 'CIENCIAS DE LA SALUD (EXPERIMENTALES)', '615', 
    'MEDICINA PREVENTIVA Y SALUD PÚBLICA');
Insert into UXXIRRHH.VUJA_NET_BEP_RH_DEPTO_SECC_AREA
   (ID_DEPARTAMENTO, DES_DEPARTAMENTO, ID_SECCION, DES_SECCION, ID_AREA_CONOCIMIENTO, 
    DES_AREA_CONOCIMIENTO)
 Values
   ('U130', 'CIENCIAS DE LA SALUD', 'S130*', 'CIENCIAS DE LA SALUD (LINARES)', '615', 
    'MEDICINA PREVENTIVA Y SALUD PÚBLICA');
Insert into UXXIRRHH.VUJA_NET_BEP_RH_DEPTO_SECC_AREA
   (ID_DEPARTAMENTO, DES_DEPARTAMENTO, ID_SECCION, DES_SECCION, ID_AREA_CONOCIMIENTO, 
    DES_AREA_CONOCIMIENTO)
 Values
   ('U199', 'DEPARTAMENTO OBSOLETO', 'S199', 'SECCION DE DEPARTAMENTO OBSOLETO', '330', 
    'FILOLOGÍA ESPAÑOLA (OBSOLETA)');
Insert into UXXIRRHH.VUJA_NET_BEP_RH_DEPTO_SECC_AREA
   (ID_DEPARTAMENTO, DES_DEPARTAMENTO, ID_SECCION, DES_SECCION, ID_AREA_CONOCIMIENTO, 
    DES_AREA_CONOCIMIENTO)
 Values
   ('U199', 'DEPARTAMENTO OBSOLETO', 'S199', 'SECCION DE DEPARTAMENTO OBSOLETO', '380', 
    'FILOSOFÍA DEL DERECHO, MORAL Y POLÍTICA (OBSOLETO)');
Insert into UXXIRRHH.VUJA_NET_BEP_RH_DEPTO_SECC_AREA
   (ID_DEPARTAMENTO, DES_DEPARTAMENTO, ID_SECCION, DES_SECCION, ID_AREA_CONOCIMIENTO, 
    DES_AREA_CONOCIMIENTO)
 Values
   ('U199', 'DEPARTAMENTO OBSOLETO', 'S199', 'SECCION DE DEPARTAMENTO OBSOLETO', '999', 
    'ÁREA OBSOLETA');
Insert into UXXIRRHH.VUJA_NET_BEP_RH_DEPTO_SECC_AREA
   (ID_DEPARTAMENTO, DES_DEPARTAMENTO, ID_SECCION, DES_SECCION, ID_AREA_CONOCIMIENTO, 
    DES_AREA_CONOCIMIENTO)
 Values
   ('EXTRANJE', 'PROFESOR ESTANCIA EN EL EXTRANJERO', 'EXTRANJE', 'PROFESOR ESTANCIA EN EL EXTRANJERO', 'EXTRANJE', 
    'PROFESOR ESTANCIA EN EL EXTRANJERO');
Insert into UXXIRRHH.VUJA_NET_BEP_RH_DEPTO_SECC_AREA
   (ID_DEPARTAMENTO, DES_DEPARTAMENTO, ID_SECCION, DES_SECCION, ID_AREA_CONOCIMIENTO, 
    DES_AREA_CONOCIMIENTO)
 Values
   ('CAI', 'CENTRO ANDALUZ DE ARQUEOLOGÍA IBÉRICA', 'SCAI', 'CENTRO ANDALUZ DE ARQUEOLOGÍA IBÉRICA', 'ACAI', 
    'CENTRO ANDALUZ DE ARQUEOLOGÍA IBÉRICA');
Insert into UXXIRRHH.VUJA_NET_BEP_RH_DEPTO_SECC_AREA
   (ID_DEPARTAMENTO, DES_DEPARTAMENTO, ID_SECCION, DES_SECCION, ID_AREA_CONOCIMIENTO, 
    DES_AREA_CONOCIMIENTO)
 Values
   ('NODEPART', 'Sin departamento. No existe la plaza.', 'NOSECCIO', 'Sin sección. No existe plaza asociada.', 'NOAREA', 
    'No existe área ya que no existe una plaza asociada');
Insert into UXXIRRHH.VUJA_NET_BEP_RH_DEPTO_SECC_AREA
   (ID_DEPARTAMENTO, DES_DEPARTAMENTO, ID_SECCION, DES_SECCION, ID_AREA_CONOCIMIENTO, 
    DES_AREA_CONOCIMIENTO)
 Values
   ('U121', 'INGENIERÍA MECÁNICA Y MINERA', 'S154', 'Ingeniería Mecánica y Minera (Linares)', '510', 
    'INGENIERIA DE LA CONSTRUCCIÓN');
Insert into UXXIRRHH.VUJA_NET_BEP_RH_DEPTO_SECC_AREA
   (ID_DEPARTAMENTO, DES_DEPARTAMENTO, ID_SECCION, DES_SECCION, ID_AREA_CONOCIMIENTO, 
    DES_AREA_CONOCIMIENTO)
 Values
   ('U121', 'INGENIERÍA MECÁNICA Y MINERA', 'S154', 'Ingeniería Mecánica y Minera (Linares)', '515', 
    'INGENIERIA DE LOS PROCESOS DE FABRICACIÓN');
Insert into UXXIRRHH.VUJA_NET_BEP_RH_DEPTO_SECC_AREA
   (ID_DEPARTAMENTO, DES_DEPARTAMENTO, ID_SECCION, DES_SECCION, ID_AREA_CONOCIMIENTO, 
    DES_AREA_CONOCIMIENTO)
 Values
   ('U121', 'INGENIERÍA MECÁNICA Y MINERA', 'S1541', 'Ingeniería Mecánica y Minera EPS', '515', 
    'INGENIERIA DE LOS PROCESOS DE FABRICACIÓN');
Insert into UXXIRRHH.VUJA_NET_BEP_RH_DEPTO_SECC_AREA
   (ID_DEPARTAMENTO, DES_DEPARTAMENTO, ID_SECCION, DES_SECCION, ID_AREA_CONOCIMIENTO, 
    DES_AREA_CONOCIMIENTO)
 Values
   ('CICT', 'CENTRO INSTRUMENTACIÓN CIENTIFICO TECNIC', 'SCICT', 'CENTRO INSTRUMENTACION CIENTIFICO TECNIC', 'ACICT', 
    'CENTRO INSTRUMENTACION CIENTIFICO TECNICO');
Insert into UXXIRRHH.VUJA_NET_BEP_RH_DEPTO_SECC_AREA
   (ID_DEPARTAMENTO, DES_DEPARTAMENTO, ID_SECCION, DES_SECCION, ID_AREA_CONOCIMIENTO, 
    DES_AREA_CONOCIMIENTO)
 Values
   ('VICERREC', 'VICERRECTORADO DE RELACIONES INTERNAN', 'RRII', 'VICERRECTORADO DE RELACIONES INTERNANCI', 'ME', 
    'MOVILIDAD ERASMUS');
Insert into UXXIRRHH.VUJA_NET_BEP_RH_DEPTO_SECC_AREA
   (ID_DEPARTAMENTO, DES_DEPARTAMENTO, ID_SECCION, DES_SECCION, ID_AREA_CONOCIMIENTO, 
    DES_AREA_CONOCIMIENTO)
 Values
   ('CEAEMA', 'CENTRO ESTUDIOS AVAN ENERGIA MEDIO AMBIE', 'SCEAEMA', 'CENTRO ESTUDIOS AVAN ENERGIA MEDIO AMBIE', 'ACEAEMA', 
    'CENTRO ESTUDIOS AVANZ ENERGIA MEDIO AMBIENTE');
Insert into UXXIRRHH.VUJA_NET_BEP_RH_DEPTO_SECC_AREA
   (ID_DEPARTAMENTO, DES_DEPARTAMENTO, ID_SECCION, DES_SECCION, ID_AREA_CONOCIMIENTO, 
    DES_AREA_CONOCIMIENTO)
 Values
   ('IUAI', 'INSTITUTO UNIV. DE ARQUEOLOGIA IBERICA', 'SIUAI', 'INSTITUTO UNIV. DE ARQUEOLOGIA IBERICA', 'AIUAI', 
    'INSTITUTO UNIVERSITARIO DE ARQUEOLOGIA IBERICA');
Insert into UXXIRRHH.VUJA_NET_BEP_RH_DEPTO_SECC_AREA
   (ID_DEPARTAMENTO, DES_DEPARTAMENTO, ID_SECCION, DES_SECCION, ID_AREA_CONOCIMIENTO, 
    DES_AREA_CONOCIMIENTO)
 Values
   ('CEAOAO', 'CENTRO EST. AVAN. EN OLIVAR Y ACEITES', 'SCEAOAO', 'CENTRO EST. AVAN. EN OLIVAR Y ACEITES', 'ACEAOAO', 
    'CENTRO EST. AVAN. EN OLIVAR Y ACEITES DE OLIVAR');
Insert into UXXIRRHH.VUJA_NET_BEP_RH_DEPTO_SECC_AREA
   (ID_DEPARTAMENTO, DES_DEPARTAMENTO, ID_SECCION, DES_SECCION, ID_AREA_CONOCIMIENTO, 
    DES_AREA_CONOCIMIENTO)
 Values
   ('CEACT', 'CENTRO EST. AVAN. EN CIENCIAS TIERRA', 'SCEACT', 'CENTRO EST. AVAN. EN CIENCIAS TIERRA', 'ACEACT', 
    'CENTRO EST. AVAN. EN CIENCIAS TIERRA');