DROP TABLE VUJA_NET_BEP_RH_DEPARTAMENTO_PDI;
--/////////////////////
CREATE TABLE VUJA_NET_BEP_RH_DEPARTAMENTO_PDI
(
  PRSNIF                VARCHAR2(16),
  ID_DEPARTAMENTO       VARCHAR2(8),
  ID_AREA_CONOCIMIENTO  VARCHAR2(8),
  F_DESDE               DATE,
  F_HASTA               DATE
);
