ALTER TABLE TBEP_SOLICITUDES ADD (
	FLGEXCLUIDO CHAR(1) DEFAULT 'N',
	RAZON_EXCLUSION VARCHAR2(500) NULL,
    FECHA_EXCLUSION TIMESTAMP NULL
);
--/////////////////////
COMMENT ON COLUMN TBEP_SOLICITUDES.FLGEXCLUIDO IS 'Indica si el usuario está excluido de la solicitud';
--/////////////////////
COMMENT ON COLUMN TBEP_SOLICITUDES.RAZON_EXCLUSION IS 'Comentario para indicar por que ha sido excluido';
--/////////////////////
COMMENT ON COLUMN TBEP_SOLICITUDES.FECHA_EXCLUSION IS 'Fecha cuando se le excluye';
--/////////////////////
ALTER TABLE TBEP_HTO_SOLICITUDES ADD (
	FLGEXCLUIDO CHAR(1) DEFAULT 'N',
	RAZON_EXCLUSION VARCHAR2(500) NULL,
    FECHA_EXCLUSION TIMESTAMP NULL
);
--/////////////////////
CREATE OR REPLACE TRIGGER DBEP_SOL_BRI
BEFORE INSERT
ON TBEP_SOLICITUDES
FOR EACH ROW
DECLARE
BEGIN
    SELECT QBEP_SOL.nextval into :new.CODNUM FROM dual;

    INSERT INTO TBEP_HTO_SOLICITUDES (CODCAMBIO,LOG,CODNUM,BEPUSU_CODNUM,BEPCON_CODNUM,ESTADO,FECHACONFIRMACION,ARCHIVO,UID_USUARIO,FLGEXCLUIDO,RAZON_EXCLUSION,FECHA_EXCLUSION)
    VALUES (QBEP_HTO_SOL.NEXTVAL,'AFTER_INSERT',:New.CODNUM,:New.BEPUSU_CODNUM,:New.BEPCON_CODNUM,:New.ESTADO,:New.FECHACONFIRMACION,:New.ARCHIVO,:New.UID_USUARIO,:New.FLGEXCLUIDO,:New.RAZON_EXCLUSION,:New.FECHA_EXCLUSION);
END DBEP_SOL_BRI;
--/////////////////////
CREATE OR REPLACE TRIGGER DBEP_SOL_BRU
BEFORE UPDATE
ON TBEP_SOLICITUDES
FOR EACH ROW
DECLARE
BEGIN
	INSERT INTO TBEP_HTO_SOLICITUDES (CODCAMBIO,LOG,CODNUM,BEPUSU_CODNUM,BEPCON_CODNUM,ESTADO,FECHACONFIRMACION,ARCHIVO,UID_USUARIO,FLGEXCLUIDO,RAZON_EXCLUSION,FECHA_EXCLUSION)
    VALUES (QBEP_HTO_SOL.NEXTVAL,'BEFORE_UPDATE',:Old.CODNUM,:Old.BEPUSU_CODNUM,:Old.BEPCON_CODNUM,:Old.ESTADO,:Old.FECHACONFIRMACION,:Old.ARCHIVO,:Old.UID_USUARIO,:Old.FLGEXCLUIDO,:Old.RAZON_EXCLUSION,:Old.FECHA_EXCLUSION);
    
 	INSERT INTO TBEP_HTO_SOLICITUDES (CODCAMBIO,LOG,CODNUM,BEPUSU_CODNUM,BEPCON_CODNUM,ESTADO,FECHACONFIRMACION,ARCHIVO,UID_USUARIO,FLGEXCLUIDO,RAZON_EXCLUSION,FECHA_EXCLUSION)
    VALUES (QBEP_HTO_SOL.NEXTVAL,'AFTER_UPDATE',:New.CODNUM,:New.BEPUSU_CODNUM,:New.BEPCON_CODNUM,:New.ESTADO,:New.FECHACONFIRMACION,:New.ARCHIVO,:New.UID_USUARIO,:New.FLGEXCLUIDO,:New.RAZON_EXCLUSION,:New.FECHA_EXCLUSION);
END DBEP_SOL_BRU;
--/////////////////////
CREATE OR REPLACE TRIGGER DBEP_SOL_BRD
BEFORE DELETE
ON TBEP_SOLICITUDES
FOR EACH ROW
DECLARE
BEGIN
	INSERT INTO TBEP_HTO_SOLICITUDES (CODCAMBIO,LOG,CODNUM,BEPUSU_CODNUM,BEPCON_CODNUM,ESTADO,FECHACONFIRMACION,ARCHIVO,UID_USUARIO,FLGEXCLUIDO,RAZON_EXCLUSION,FECHA_EXCLUSION)
    VALUES (QBEP_HTO_SOL.NEXTVAL,'BEFORE_DELETE',:Old.CODNUM,:Old.BEPUSU_CODNUM,:Old.BEPCON_CODNUM,:Old.ESTADO,:Old.FECHACONFIRMACION,:Old.ARCHIVO,:Old.UID_USUARIO,:Old.FLGEXCLUIDO,:Old.RAZON_EXCLUSION,:Old.FECHA_EXCLUSION);
END DBEP_SOL_BRD;