ALTER TABLE TBEP_MENSAJES ADD FECHA_ENVIO TIMESTAMP CONSTRAINT RBEP_NMEN_FECHA_ENVIO NULL;
--/////////////////////
ALTER TABLE TBEP_MENSAJES DROP CONSTRAINT RBEP_CMEN_ESTADO;
--/////////////////////
ALTER TABLE TBEP_MENSAJES ADD CONSTRAINT RBEP_CMEN_ESTADO CHECK(ESTADO IN ('BORRADOR','ENVIADO','ENVIANDO'));
--/////////////////////
ALTER TABLE TBEP_MEN_DESTINATARIOS ADD ESTADO CHAR(10) DEFAULT 'SIN ENVIAR';
--/////////////////////
ALTER TABLE TBEP_MEN_DESTINATARIOS ADD CONSTRAINT RBEP_CMDE_ESTADO CHECK(ESTADO IN ('ENVIADO','SIN ENVIAR','FALLO'));
--/////////////////////
COMMENT ON COLUMN TBEP_MEN_DESTINATARIOS.ESTADO IS 'Estado del mensaje para un destinatario';
--/////////////////////
ALTER TABLE TBEP_HTO_MEN_DESTINATARIOS ADD ESTADO CHAR(10) DEFAULT 'SIN ENVIAR';
--/////////////////////
CREATE OR REPLACE TRIGGER DBEP_MDE_BRI
BEFORE INSERT
ON TBEP_MEN_DESTINATARIOS
FOR EACH ROW
DECLARE
BEGIN
    SELECT QBEP_MDE.nextval into :new.CODNUM FROM dual;

    INSERT INTO TBEP_HTO_MEN_DESTINATARIOS (CODCAMBIO,LOG,CODNUM,BEPMEN_CODNUM,BEPUSU_CODNUM,ESTADO,UID_USUARIO)
    VALUES (QBEP_HTO_MDE.NEXTVAL,'AFTER_INSERT',:New.CODNUM,:New.BEPMEN_CODNUM,:New.BEPUSU_CODNUM,:New.ESTADO,:New.UID_USUARIO);
END DBEP_MDE_BRI;
--/////////////////////
CREATE OR REPLACE TRIGGER DBEP_MDE_BRU
BEFORE UPDATE
ON TBEP_MEN_DESTINATARIOS 
FOR EACH ROW
DECLARE
BEGIN
    INSERT INTO TBEP_HTO_MEN_DESTINATARIOS (CODCAMBIO,LOG,CODNUM,BEPMEN_CODNUM,BEPUSU_CODNUM,ESTADO,UID_USUARIO)
    VALUES (QBEP_HTO_MDE.NEXTVAL,'BEFORE_UPDATE',:Old.CODNUM,:Old.BEPMEN_CODNUM,:Old.BEPUSU_CODNUM,:Old.ESTADO,:Old.UID_USUARIO);
          
    INSERT INTO TBEP_HTO_MEN_DESTINATARIOS (CODCAMBIO,LOG,CODNUM,BEPMEN_CODNUM,BEPUSU_CODNUM,ESTADO,UID_USUARIO)
    VALUES (QBEP_HTO_MDE.NEXTVAL,'AFTER_UPDATE',:New.CODNUM,:New.BEPMEN_CODNUM,:New.BEPUSU_CODNUM,:New.ESTADO,:New.UID_USUARIO);
END DBEP_MDE_BRU;
--/////////////////////
CREATE OR REPLACE TRIGGER DBEP_MDE_BRD
BEFORE DELETE
ON TBEP_MEN_DESTINATARIOS 
FOR EACH ROW
DECLARE
BEGIN
    INSERT INTO TBEP_HTO_MEN_DESTINATARIOS (CODCAMBIO,LOG,CODNUM,BEPMEN_CODNUM,BEPUSU_CODNUM,ESTADO,UID_USUARIO)
    VALUES (QBEP_HTO_MDE.NEXTVAL,'BEFORE_DELETE',:Old.CODNUM,:Old.BEPMEN_CODNUM,:Old.BEPUSU_CODNUM,:Old.ESTADO,:Old.UID_USUARIO);
END DBEP_MDE_BRD;