ALTER TABLE TBEP_SOL_BOL_MERITOS ADD (
	DESGLOSE VARCHAR2(250 CHAR) NULL,
	RESULTADO NUMBER(10, 6) NULL
);
--/////////////////////
ALTER TABLE TBEP_SOLICITUD_BOLSAS ADD (
	TOTAL NUMBER(10, 6) NULL,
	TOTALSINAPLICAR NUMBER(10, 6) NULL,
	DESGLOSETOTAL VARCHAR2(250 CHAR) NULL,
	DESGLOSEDESCRIPCION VARCHAR2(1000 CHAR) NULL,
	ARCHIVO BLOB NULL,
	FECHABAREMACION TIMESTAMP NULL
);
--/////////////////////
ALTER TABLE TBEP_BOLSAS ADD (
	FLGPENBAREMACION CHAR(1) DEFAULT 'N',
	FECHABAREMACION TIMESTAMP NULL,
	CONSTRAINT RBEP_CBOL_FLGPENBAREMACION CHECK(FLGPENBAREMACION IN ('N','S'))
);
--/////////////////////
COMMENT ON COLUMN TBEP_SOL_BOL_MERITOS.DESGLOSE IS 'Desglose de la puntuación del mérito';
--/////////////////////
COMMENT ON COLUMN TBEP_SOL_BOL_MERITOS.RESULTADO IS 'Puntuación final del mérito en una bolsa';
--/////////////////////
COMMENT ON COLUMN TBEP_SOLICITUD_BOLSAS.TOTAL IS 'Puntuación total de la solicitud para una bolsa';
--/////////////////////
COMMENT ON COLUMN TBEP_SOLICITUD_BOLSAS.TOTALSINAPLICAR IS 'Puntuación total sin aplicar el máximo valor de los méritos preferentes y acreditaciones';
--/////////////////////
COMMENT ON COLUMN TBEP_SOLICITUD_BOLSAS.DESGLOSETOTAL IS 'Desglose de la puntuación total de la solicitud';
--/////////////////////
COMMENT ON COLUMN TBEP_SOLICITUD_BOLSAS.DESGLOSEDESCRIPCION IS 'Descripción del desglose de la solicitud';
--/////////////////////
COMMENT ON COLUMN TBEP_SOLICITUD_BOLSAS.ARCHIVO IS 'Archivo de resultados del candidato en un área';
--/////////////////////
COMMENT ON COLUMN TBEP_SOLICITUD_BOLSAS.FECHABAREMACION IS 'Fecha de baremación de una solicitud para un área';
--/////////////////////
COMMENT ON COLUMN TBEP_BOLSAS.FLGPENBAREMACION IS 'Indica si la bolsa está pendiente de baremación';
--/////////////////////
COMMENT ON COLUMN TBEP_BOLSAS.FECHABAREMACION IS 'Fecha de baremación';
--/////////////////////
ALTER TABLE TBEP_HTO_SOL_BOL_MERITOS ADD (
	DESGLOSE VARCHAR2(250 CHAR) NULL,
	RESULTADO NUMBER(10, 6) NULL
);
--/////////////////////
ALTER TABLE TBEP_HTO_SOLICITUD_BOLSAS ADD (
	TOTAL NUMBER(10, 6) NULL,
	TOTALSINAPLICAR NUMBER(10, 6) NULL,
	DESGLOSETOTAL VARCHAR2(250 CHAR) NULL,
	DESGLOSEDESCRIPCION VARCHAR2(1000 CHAR) NULL,
	ARCHIVO BLOB NULL,
	FECHABAREMACION TIMESTAMP NULL
);
--/////////////////////
ALTER TABLE TBEP_HTO_BOLSAS ADD (
	FLGPENBAREMACION CHAR(1) DEFAULT 'N',
	FECHABAREMACION TIMESTAMP NULL
);
--/////////////////////
CREATE OR REPLACE TRIGGER DBEP_SBM_BRI
BEFORE INSERT
ON TBEP_SOL_BOL_MERITOS
FOR EACH ROW
DECLARE
BEGIN
    SELECT QBEP_SBM.nextval into :new.CODNUM FROM dual;

    INSERT INTO TBEP_HTO_SOL_BOL_MERITOS (CODCAMBIO,LOG,CODNUM,BEPSBO_CODNUM,BEPMER_CODNUM,FLGEXCLUIDO,FLGVALIDADO,OBSERVACION_CANDIDATO,DESGLOSE,RESULTADO,UID_USUARIO)
    VALUES (QBEP_HTO_SBM.NEXTVAL,'AFTER_INSERT',:New.CODNUM,:New.BEPSBO_CODNUM,:New.BEPMER_CODNUM,:New.FLGEXCLUIDO,:New.FLGVALIDADO,:New.OBSERVACION_CANDIDATO,:New.DESGLOSE,:New.RESULTADO,:New.UID_USUARIO);
END DBEP_SBM_BRI;
--/////////////////////
CREATE OR REPLACE TRIGGER DBEP_SBM_BRU
BEFORE UPDATE
ON TBEP_SOL_BOL_MERITOS
FOR EACH ROW
DECLARE
BEGIN
	INSERT INTO TBEP_HTO_SOL_BOL_MERITOS (CODCAMBIO,LOG,CODNUM,BEPSBO_CODNUM,BEPMER_CODNUM,FLGEXCLUIDO,FLGVALIDADO,OBSERVACION_CANDIDATO,DESGLOSE,RESULTADO,UID_USUARIO)
    VALUES (QBEP_HTO_SBM.NEXTVAL,'BEFORE_UPDATE',:Old.CODNUM,:Old.BEPSBO_CODNUM,:Old.BEPMER_CODNUM,:Old.FLGEXCLUIDO,:Old.FLGVALIDADO,:Old.OBSERVACION_CANDIDATO,:Old.DESGLOSE,:Old.RESULTADO,:Old.UID_USUARIO);
    
 	INSERT INTO TBEP_HTO_SOL_BOL_MERITOS (CODCAMBIO,LOG,CODNUM,BEPSBO_CODNUM,BEPMER_CODNUM,FLGEXCLUIDO,FLGVALIDADO,OBSERVACION_CANDIDATO,DESGLOSE,RESULTADO,UID_USUARIO)
    VALUES (QBEP_HTO_SBM.NEXTVAL,'AFTER_UPDATE',:New.CODNUM,:New.BEPSBO_CODNUM,:New.BEPMER_CODNUM,:New.FLGEXCLUIDO,:New.FLGVALIDADO,:New.OBSERVACION_CANDIDATO,:New.DESGLOSE,:New.RESULTADO,:New.UID_USUARIO);
END DBEP_SBM_BRU;
--/////////////////////
CREATE OR REPLACE TRIGGER DBEP_SBM_BRD
BEFORE DELETE
ON TBEP_SOL_BOL_MERITOS
FOR EACH ROW
DECLARE
BEGIN
	INSERT INTO TBEP_HTO_SOL_BOL_MERITOS (CODCAMBIO,LOG,CODNUM,BEPSBO_CODNUM,BEPMER_CODNUM,FLGEXCLUIDO,FLGVALIDADO,OBSERVACION_CANDIDATO,DESGLOSE,RESULTADO,UID_USUARIO)
    VALUES (QBEP_HTO_SBM.NEXTVAL,'BEFORE_DELETE',:Old.CODNUM,:Old.BEPSBO_CODNUM,:Old.BEPMER_CODNUM,:Old.FLGEXCLUIDO,:Old.FLGVALIDADO,:Old.OBSERVACION_CANDIDATO,:Old.DESGLOSE,:Old.RESULTADO,:Old.UID_USUARIO);
END DBEP_SBM_BRD;
--/////////////////////
CREATE OR REPLACE TRIGGER DBEP_SBO_BRI
BEFORE INSERT
ON TBEP_SOLICITUD_BOLSAS
FOR EACH ROW
DECLARE
BEGIN
	SELECT QBEP_SBO.nextval into :new.CODNUM FROM dual;
	
    INSERT INTO TBEP_HTO_SOLICITUD_BOLSAS (CODCAMBIO,LOG,CODNUM,BEPBOL_CODNUM,BEPSOL_CODNUM,TOTAL,TOTALSINAPLICAR,DESGLOSETOTAL,DESGLOSEDESCRIPCION,ARCHIVO,FECHABAREMACION,UID_USUARIO)
    VALUES (QBEP_HTO_SBO.NEXTVAL,'AFTER_INSERT',:New.CODNUM,:New.BEPBOL_CODNUM,:New.BEPSOL_CODNUM,:New.TOTAL,:New.TOTALSINAPLICAR,:New.DESGLOSETOTAL,:New.DESGLOSEDESCRIPCION,:New.ARCHIVO,:New.FECHABAREMACION,:New.UID_USUARIO);
END DBEP_SBO_BRI;
--/////////////////////
CREATE OR REPLACE TRIGGER DBEP_SBO_BRU
BEFORE UPDATE
ON TBEP_SOLICITUD_BOLSAS
FOR EACH ROW
DECLARE
BEGIN
	INSERT INTO TBEP_HTO_SOLICITUD_BOLSAS (CODCAMBIO,LOG,CODNUM,BEPBOL_CODNUM,BEPSOL_CODNUM,TOTAL,TOTALSINAPLICAR,DESGLOSETOTAL,DESGLOSEDESCRIPCION,ARCHIVO,FECHABAREMACION,UID_USUARIO)
    VALUES (QBEP_HTO_SBO.NEXTVAL,'BEFORE_UPDATE',:Old.CODNUM,:Old.BEPBOL_CODNUM,:Old.BEPSOL_CODNUM,:Old.TOTAL,:Old.TOTALSINAPLICAR,:Old.DESGLOSETOTAL,:Old.DESGLOSEDESCRIPCION,:Old.ARCHIVO,:Old.FECHABAREMACION,:Old.UID_USUARIO);
    
 	INSERT INTO TBEP_HTO_SOLICITUD_BOLSAS (CODCAMBIO,LOG,CODNUM,BEPBOL_CODNUM,BEPSOL_CODNUM,TOTAL,TOTALSINAPLICAR,DESGLOSETOTAL,DESGLOSEDESCRIPCION,ARCHIVO,FECHABAREMACION,UID_USUARIO)
    VALUES (QBEP_HTO_SBO.NEXTVAL,'AFTER_UPDATE',:New.CODNUM,:New.BEPBOL_CODNUM,:New.BEPSOL_CODNUM,:New.TOTAL,:New.TOTALSINAPLICAR,:New.DESGLOSETOTAL,:New.DESGLOSEDESCRIPCION,:New.ARCHIVO,:New.FECHABAREMACION,:New.UID_USUARIO);
END DBEP_SBO_BRU;
--/////////////////////
CREATE OR REPLACE TRIGGER DBEP_SBO_BRD
BEFORE DELETE
ON TBEP_SOLICITUD_BOLSAS
FOR EACH ROW
DECLARE
BEGIN
	INSERT INTO TBEP_HTO_SOLICITUD_BOLSAS (CODCAMBIO,LOG,CODNUM,BEPBOL_CODNUM,BEPSOL_CODNUM,TOTAL,TOTALSINAPLICAR,DESGLOSETOTAL,DESGLOSEDESCRIPCION,ARCHIVO,FECHABAREMACION,UID_USUARIO)
    VALUES (QBEP_HTO_SBO.NEXTVAL,'BEFORE_DELETE',:Old.CODNUM,:Old.BEPBOL_CODNUM,:Old.BEPSOL_CODNUM,:Old.TOTAL,:Old.TOTALSINAPLICAR,:Old.DESGLOSETOTAL,:Old.DESGLOSEDESCRIPCION,:Old.ARCHIVO,:Old.FECHABAREMACION,:Old.UID_USUARIO);
END DBEP_SBO_BRD;
--/////////////////////
CREATE OR REPLACE TRIGGER DBEP_BOL_BRI
BEFORE INSERT
ON TBEP_BOLSAS
FOR EACH ROW
DECLARE
BEGIN
    SELECT QBEP_BOL.nextval into :new.CODNUM FROM dual;
    
    INSERT INTO TBEP_HTO_BOLSAS (CODCAMBIO,LOG,CODNUM,BEPARE_CODNUM,ESTADO,FLGBAREMABLE,FECHAACTUALIZACION,FECHABLOQUEO,FECHADEBLOQUEO,FLGPENBAREMACION,FECHABAREMACION,UID_USUARIO)
    VALUES (QBEP_HTO_ARE.NEXTVAL,'AFTER_INSERT',:New.CODNUM,:New.BEPARE_CODNUM,:New.ESTADO,:New.FLGBAREMABLE,:New.FECHAACTUALIZACION,:New.FECHABLOQUEO,:New.FECHADEBLOQUEO,:New.FLGPENBAREMACION,:New.FECHABAREMACION,:New.UID_USUARIO);
END DBEP_BOL_BRI;
--/////////////////////
CREATE OR REPLACE TRIGGER DBEP_BOL_BRU
BEFORE UPDATE
ON TBEP_BOLSAS
FOR EACH ROW
DECLARE
BEGIN
	INSERT INTO TBEP_HTO_BOLSAS (CODCAMBIO,LOG,CODNUM,BEPARE_CODNUM,ESTADO,FLGBAREMABLE,FECHAACTUALIZACION,FECHABLOQUEO,FECHADEBLOQUEO,FLGPENBAREMACION,FECHABAREMACION,UID_USUARIO)
    VALUES (QBEP_HTO_ARE.NEXTVAL,'BEFORE_UPDATE',:Old.CODNUM,:Old.BEPARE_CODNUM,:Old.ESTADO,:Old.FLGBAREMABLE,:Old.FECHAACTUALIZACION,:Old.FECHABLOQUEO,:Old.FECHADEBLOQUEO,:Old.FLGPENBAREMACION,:Old.FECHABAREMACION,:Old.UID_USUARIO);
    
    INSERT INTO TBEP_HTO_BOLSAS (CODCAMBIO,LOG,CODNUM,BEPARE_CODNUM,ESTADO,FLGBAREMABLE,FECHAACTUALIZACION,FECHABLOQUEO,FECHADEBLOQUEO,FLGPENBAREMACION,FECHABAREMACION,UID_USUARIO)
    VALUES (QBEP_HTO_ARE.NEXTVAL,'AFTER_UPDATE',:New.CODNUM,:New.BEPARE_CODNUM,:New.ESTADO,:New.FLGBAREMABLE,:New.FECHAACTUALIZACION,:New.FECHABLOQUEO,:New.FECHADEBLOQUEO,:New.FLGPENBAREMACION,:New.FECHABAREMACION,:New.UID_USUARIO);
END DBEP_BOL_BRU;
--/////////////////////
CREATE OR REPLACE TRIGGER DBEP_BOL_BRD
BEFORE DELETE
ON TBEP_BOLSAS
FOR EACH ROW
DECLARE
BEGIN
	INSERT INTO TBEP_HTO_BOLSAS (CODCAMBIO,LOG,CODNUM,BEPARE_CODNUM,ESTADO,FLGBAREMABLE,FECHAACTUALIZACION,FECHABLOQUEO,FECHADEBLOQUEO,FLGPENBAREMACION,FECHABAREMACION,UID_USUARIO)
    VALUES (QBEP_HTO_ARE.NEXTVAL,'BEFORE_DELETE',:Old.CODNUM,:Old.BEPARE_CODNUM,:Old.ESTADO,:Old.FLGBAREMABLE,:Old.FECHAACTUALIZACION,:Old.FECHABLOQUEO,:Old.FECHADEBLOQUEO,:Old.FLGPENBAREMACION,:Old.FECHABAREMACION,:Old.UID_USUARIO);
END DBEP_BOL_BRD;
--/////////////////////