ALTER TABLE TBEP_SOLICITUD_BOLSAS ADD (
	PUNTUACION NUMBER(10, 6) NULL,
	ARCHIVO BLOB NULL
);
--/////////////////////
ALTER TABLE TBEP_BOLSAS ADD (
	FLGPENBAREMACION CHAR(1) DEFAULT 'N',
	FECHABAREMACION TIMESTAMP NULL,
	CONSTRAINT RBEP_CBOL_FLGPENBAREMACION CHECK(FLGPENBAREMACION IN ('N','S'))
);
--/////////////////////
COMMENT ON COLUMN TBEP_SOLICITUD_BOLSAS.PUNTUACION IS 'Puntuación final de la solicitud';
--/////////////////////
COMMENT ON COLUMN TBEP_SOLICITUD_BOLSAS.ARCHIVO IS 'Archivo de resultados del candidato en un área';
--/////////////////////
COMMENT ON COLUMN TBEP_BOLSAS.FLGPENBAREMACION IS 'Indica si la bolsa está pendiente de baremación';
--/////////////////////
COMMENT ON COLUMN TBEP_BOLSAS.FECHABAREMACION IS 'Fecha de baremación';
--/////////////////////
ALTER TABLE TBEP_HTO_SOLICITUD_BOLSAS ADD (
	PUNTUACION NUMBER(10, 6) NULL,
	ARCHIVO BLOB NULL
);
--/////////////////////
ALTER TABLE TBEP_HTO_BOLSAS ADD (
	FLGPENBAREMACION CHAR(1) DEFAULT 'N',
	FECHABAREMACION TIMESTAMP NULL
);
--/////////////////////
CREATE OR REPLACE TRIGGER DBEP_SBO_BRI
BEFORE INSERT
ON TBEP_SOLICITUD_BOLSAS
FOR EACH ROW
DECLARE
BEGIN
	SELECT QBEP_SBO.nextval into :new.CODNUM FROM dual;
	
    INSERT INTO TBEP_HTO_SOLICITUD_BOLSAS (CODCAMBIO,LOG,CODNUM,BEPBOL_CODNUM,BEPSOL_CODNUM,PUNTUACION,ARCHIVO,UID_USUARIO)
    VALUES (QBEP_HTO_SBO.NEXTVAL,'AFTER_INSERT',:New.CODNUM,:New.BEPBOL_CODNUM,:New.BEPSOL_CODNUM,:New.PUNTUACION,:New.ARCHIVO,:New.UID_USUARIO);
END DBEP_SBO_BRI;
--/////////////////////
CREATE OR REPLACE TRIGGER DBEP_SBO_BRU
BEFORE UPDATE
ON TBEP_SOLICITUD_BOLSAS
FOR EACH ROW
DECLARE
BEGIN
	INSERT INTO TBEP_HTO_SOLICITUD_BOLSAS (CODCAMBIO,LOG,CODNUM,BEPBOL_CODNUM,BEPSOL_CODNUM,PUNTUACION,ARCHIVO,UID_USUARIO)
    VALUES (QBEP_HTO_SBO.NEXTVAL,'BEFORE_UPDATE',:Old.CODNUM,:Old.BEPBOL_CODNUM,:Old.BEPSOL_CODNUM,:Old.PUNTUACION,:Old.ARCHIVO,:Old.UID_USUARIO);
    
 	INSERT INTO TBEP_HTO_SOLICITUD_BOLSAS (CODCAMBIO,LOG,CODNUM,BEPBOL_CODNUM,BEPSOL_CODNUM,PUNTUACION,ARCHIVO,UID_USUARIO)
    VALUES (QBEP_HTO_SBO.NEXTVAL,'AFTER_UPDATE',:New.CODNUM,:New.BEPBOL_CODNUM,:New.BEPSOL_CODNUM,:New.PUNTUACION,:New.ARCHIVO,:New.UID_USUARIO);
END DBEP_SBO_BRU;
--/////////////////////
CREATE OR REPLACE TRIGGER DBEP_SBO_BRD
BEFORE DELETE
ON TBEP_SOLICITUD_BOLSAS
FOR EACH ROW
DECLARE
BEGIN
	INSERT INTO TBEP_HTO_SOLICITUD_BOLSAS (CODCAMBIO,LOG,CODNUM,BEPBOL_CODNUM,BEPSOL_CODNUM,PUNTUACION,ARCHIVO,UID_USUARIO)
    VALUES (QBEP_HTO_SBO.NEXTVAL,'BEFORE_DELETE',:Old.CODNUM,:Old.BEPBOL_CODNUM,:Old.BEPSOL_CODNUM,:Old.PUNTUACION,:Old.ARCHIVO,:Old.UID_USUARIO);
END DBEP_SBO_BRD;
--/////////////////////
CREATE OR REPLACE TRIGGER DBEP_BOL_BRI
BEFORE INSERT
ON TBEP_BOLSAS
FOR EACH ROW
DECLARE
BEGIN
    SELECT QBEP_BOL.nextval into :new.CODNUM FROM dual;
    
    INSERT INTO TBEP_HTO_BOLSAS (CODCAMBIO,LOG,CODNUM,BEPARE_CODNUM,ESTADO,FLGBAREMABLE,FECHAACTUALIZACION,FECHABLOQUEO,FECHADEBLOQUEO,FLGPENBAREMACION,FECHABAREMACION,UID_USUARIO)
    VALUES (QBEP_HTO_ARE.NEXTVAL,'AFTER_INSERT',:New.CODNUM,:New.BEPARE_CODNUM,:New.ESTADO,:New.FLGBAREMABLE,:New.FECHAACTUALIZACION,:New.FECHABLOQUEO,:New.FECHADEBLOQUEO,:New.FLGPENBAREMACION,:New.FECHABAREMACION,:New.UID_USUARIO);
END DBEP_BOL_BRI;
--/////////////////////
CREATE OR REPLACE TRIGGER DBEP_BOL_BRU
BEFORE UPDATE
ON TBEP_BOLSAS
FOR EACH ROW
DECLARE
BEGIN
	INSERT INTO TBEP_HTO_BOLSAS (CODCAMBIO,LOG,CODNUM,BEPARE_CODNUM,ESTADO,FLGBAREMABLE,FECHAACTUALIZACION,FECHABLOQUEO,FECHADEBLOQUEO,FLGPENBAREMACION,FECHABAREMACION,UID_USUARIO)
    VALUES (QBEP_HTO_ARE.NEXTVAL,'BEFORE_UPDATE',:Old.CODNUM,:Old.BEPARE_CODNUM,:Old.ESTADO,:Old.FLGBAREMABLE,:Old.FECHAACTUALIZACION,:Old.FECHABLOQUEO,:Old.FECHADEBLOQUEO,:Old.FLGPENBAREMACION,:Old.FECHABAREMACION,:Old.UID_USUARIO);
    
    INSERT INTO TBEP_HTO_BOLSAS (CODCAMBIO,LOG,CODNUM,BEPARE_CODNUM,ESTADO,FLGBAREMABLE,FECHAACTUALIZACION,FECHABLOQUEO,FECHADEBLOQUEO,FLGPENBAREMACION,FECHABAREMACION,UID_USUARIO)
    VALUES (QBEP_HTO_ARE.NEXTVAL,'AFTER_UPDATE',:New.CODNUM,:New.BEPARE_CODNUM,:New.ESTADO,:New.FLGBAREMABLE,:New.FECHAACTUALIZACION,:New.FECHABLOQUEO,:New.FECHADEBLOQUEO,:New.FLGPENBAREMACION,:New.FECHABAREMACION,:New.UID_USUARIO);
END DBEP_BOL_BRU;
--/////////////////////
CREATE OR REPLACE TRIGGER DBEP_BOL_BRD
BEFORE DELETE
ON TBEP_BOLSAS
FOR EACH ROW
DECLARE
BEGIN
	INSERT INTO TBEP_HTO_BOLSAS (CODCAMBIO,LOG,CODNUM,BEPARE_CODNUM,ESTADO,FLGBAREMABLE,FECHAACTUALIZACION,FECHABLOQUEO,FECHADEBLOQUEO,FLGPENBAREMACION,FECHABAREMACION,UID_USUARIO)
    VALUES (QBEP_HTO_ARE.NEXTVAL,'BEFORE_DELETE',:Old.CODNUM,:Old.BEPARE_CODNUM,:Old.ESTADO,:Old.FLGBAREMABLE,:Old.FECHAACTUALIZACION,:Old.FECHABLOQUEO,:Old.FECHADEBLOQUEO,:Old.FLGPENBAREMACION,:Old.FECHABAREMACION,:Old.UID_USUARIO);
END DBEP_BOL_BRD;
--/////////////////////