INSERT INTO ADM_MENU_ROL (MNU_CODNUM, ROL_CODNUM, FLG_DESACT, FLG_ADMIN) VALUES (1105, 1051, 'N', 'N');
--/////////////////////
INSERT INTO ADM_MENU_ROL (MNU_CODNUM, ROL_CODNUM, FLG_DESACT, FLG_ADMIN) VALUES (1105, 1053, 'N', 'N');
--/////////////////////
INSERT INTO ADM_MENU_ROL (MNU_CODNUM, ROL_CODNUM, FLG_DESACT, FLG_ADMIN) VALUES (1102, 1053, 'N', 'N');