ALTER TABLE TBEP_MERITOS_PREFERENTES ADD PREFIJO_INFORME VARCHAR2(10 CHAR) NULL;
--/////////////////////
COMMENT ON COLUMN TBEP_MERITOS_PREFERENTES.PREFIJO_INFORME IS 'Prefijo para el desglose en el informe de resultados';
--/////////////////////
ALTER TABLE TBEP_HTO_MER_PREFERENTES ADD PREFIJO_INFORME VARCHAR2(10 CHAR) NULL;
--/////////////////////
CREATE OR REPLACE TRIGGER DBEP_MEP_BRI
BEFORE INSERT
ON TBEP_MERITOS_PREFERENTES
FOR EACH ROW
DECLARE
BEGIN
    SELECT QBEP_MEP.nextval into :new.CODNUM FROM dual;

    INSERT INTO TBEP_HTO_MER_PREFERENTES (CODCAMBIO,LOG,CODNUM,CODIGO,NOMBRE,OBSERVACIONES,TIPO,TIPO_CALCULO,APLICABLE,BASE,FACTOR,VALOR_MAXIMO,BEPITE_TIPO_CODNUM,BEPBLO_APLICABLE_CODNUM,BEPAPA_APLICABLE_CODNUM,BEPITE_APLICABLE_CODNUM,FLGACTIVO,PREFIJO_INFORME,UID_USUARIO)
    VALUES (QBEP_HTO_MEP.NEXTVAL,'AFTER_INSERT',:New.CODNUM,:New.CODIGO,:New.NOMBRE,:New.OBSERVACIONES,:New.TIPO,:New.TIPO_CALCULO,:New.APLICABLE,:New.BASE,:New.FACTOR,:New.VALOR_MAXIMO,:New.BEPITE_TIPO_CODNUM,:New.BEPBLO_APLICABLE_CODNUM,:New.BEPAPA_APLICABLE_CODNUM,:New.BEPITE_APLICABLE_CODNUM,:New.FLGACTIVO,:New.PREFIJO_INFORME,:New.UID_USUARIO);
END DBEP_MEP_BRI;
--/////////////////////
CREATE OR REPLACE TRIGGER DBEP_MEP_BRU
BEFORE UPDATE
ON TBEP_MERITOS_PREFERENTES
FOR EACH ROW
DECLARE
BEGIN
    INSERT INTO TBEP_HTO_MER_PREFERENTES (CODCAMBIO,LOG,CODNUM,CODIGO,NOMBRE,OBSERVACIONES,TIPO,TIPO_CALCULO,APLICABLE,BASE,FACTOR,VALOR_MAXIMO,BEPITE_TIPO_CODNUM,BEPBLO_APLICABLE_CODNUM,BEPAPA_APLICABLE_CODNUM,BEPITE_APLICABLE_CODNUM,FLGACTIVO,PREFIJO_INFORME,UID_USUARIO)
    VALUES (QBEP_HTO_MEP.NEXTVAL,'BEFORE_UPDATE',:Old.CODNUM,:Old.CODIGO,:Old.NOMBRE,:Old.OBSERVACIONES,:Old.TIPO,:Old.TIPO_CALCULO,:Old.APLICABLE,:Old.BASE,:Old.FACTOR,:Old.VALOR_MAXIMO,:Old.BEPITE_TIPO_CODNUM,:Old.BEPBLO_APLICABLE_CODNUM,:Old.BEPAPA_APLICABLE_CODNUM,:Old.BEPITE_APLICABLE_CODNUM,:Old.FLGACTIVO,:Old.PREFIJO_INFORME,:Old.UID_USUARIO);
    
    INSERT INTO TBEP_HTO_MER_PREFERENTES (CODCAMBIO,LOG,CODNUM,CODIGO,NOMBRE,OBSERVACIONES,TIPO,TIPO_CALCULO,APLICABLE,BASE,FACTOR,VALOR_MAXIMO,BEPITE_TIPO_CODNUM,BEPBLO_APLICABLE_CODNUM,BEPAPA_APLICABLE_CODNUM,BEPITE_APLICABLE_CODNUM,FLGACTIVO,PREFIJO_INFORME,UID_USUARIO)
    VALUES (QBEP_HTO_MEP.NEXTVAL,'AFTER_UPDATE',:New.CODNUM,:New.CODIGO,:New.NOMBRE,:New.OBSERVACIONES,:New.TIPO,:New.TIPO_CALCULO,:New.APLICABLE,:New.BASE,:New.FACTOR,:New.VALOR_MAXIMO,:New.BEPITE_TIPO_CODNUM,:New.BEPBLO_APLICABLE_CODNUM,:New.BEPAPA_APLICABLE_CODNUM,:New.BEPITE_APLICABLE_CODNUM,:New.FLGACTIVO,:New.PREFIJO_INFORME,:New.UID_USUARIO);
END DBEP_MEP_BRU;
--/////////////////////
CREATE OR REPLACE TRIGGER DBEP_MEP_BRD
BEFORE DELETE
ON TBEP_MERITOS_PREFERENTES
FOR EACH ROW
DECLARE
BEGIN
    INSERT INTO TBEP_HTO_MER_PREFERENTES (CODCAMBIO,LOG,CODNUM,CODIGO,NOMBRE,OBSERVACIONES,TIPO,TIPO_CALCULO,APLICABLE,BASE,FACTOR,VALOR_MAXIMO,BEPITE_TIPO_CODNUM,BEPBLO_APLICABLE_CODNUM,BEPAPA_APLICABLE_CODNUM,BEPITE_APLICABLE_CODNUM,FLGACTIVO,PREFIJO_INFORME,UID_USUARIO)
    VALUES (QBEP_HTO_MEP.NEXTVAL,'BEFORE_DELETE',:Old.CODNUM,:Old.CODIGO,:Old.NOMBRE,:Old.OBSERVACIONES,:Old.TIPO,:Old.TIPO_CALCULO,:Old.APLICABLE,:Old.BASE,:Old.FACTOR,:Old.VALOR_MAXIMO,:Old.BEPITE_TIPO_CODNUM,:Old.BEPBLO_APLICABLE_CODNUM,:Old.BEPAPA_APLICABLE_CODNUM,:Old.BEPITE_APLICABLE_CODNUM,:Old.FLGACTIVO,:Old.PREFIJO_INFORME,:Old.UID_USUARIO);
END DBEP_MEP_BRD;