CREATE TABLE TBEP_PLAZAS_OFERTADAS (
	CODNUM NUMBER(11,0) CONSTRAINT RBEP_NPLO_CODNUM NOT NULL,
	BEPARE_CODNUM NUMBER(11,0) CONSTRAINT RBEP_NPLO_BEPARE_CODNUM NOT NULL,
	FECHA_CREACION TIMESTAMP CONSTRAINT RBEP_NPLO_FECHA_CREACION NOT NULL,
	FECHA_ABIERTA TIMESTAMP NULL,
	FECHA_CERRADA TIMESTAMP NULL,
    ESTADO CHAR(8) DEFAULT 'BORRADOR',
    CONSTRAINT IBEP_FPLO_ARE FOREIGN KEY (BEPARE_CODNUM) REFERENCES TBEP_AREAS (CODNUM),
    CONSTRAINT RBEP_CPLO_ESTADO CHECK(ESTADO IN ('BORRADOR','VALIDACION', 'ABIERTA', 'CERRADA'))
);
--/////////////////////
COMMENT ON COLUMN TBEP_PLAZAS_OFERTADAS.FECHA_CREACION IS 'Fecha de creación de la plaza';
--/////////////////////
COMMENT ON COLUMN TBEP_PLAZAS_OFERTADAS.FECHA_ABIERTA IS 'Fecha de apertura de la plaza';
--/////////////////////
COMMENT ON COLUMN TBEP_PLAZAS_OFERTADAS.FECHA_CERRADA IS 'Fecha de cierra de la plaza';
--/////////////////////
COMMENT ON COLUMN TBEP_PLAZAS_OFERTADAS.ESTADO IS 'Estado de la plaza';
--/////////////////////
COMMENT ON TABLE TBEP_PLAZAS_OFERTADAS IS 'Plazas ofertadas. ALIAS: [bepplo] ACRONIMO: [PLO]';