ALTER TABLE TBEP_SOLICITUD_BOLSAS DROP COLUMN ARCHIVO;
--/////////////////////
ALTER TABLE TBEP_SOLICITUD_BOLSAS ADD (
	ACREDITACIONES_VALIDADAS CLOB NULL,
	TITULACIONES_VALIDADAS CLOB NULL
);
--/////////////////////
COMMENT ON COLUMN TBEP_SOLICITUD_BOLSAS.ACREDITACIONES_VALIDADAS IS 'Resumen con las acreditaciones validadas del candidato al momento de hacer el cálculo';
--/////////////////////
COMMENT ON COLUMN TBEP_SOLICITUD_BOLSAS.TITULACIONES_VALIDADAS IS 'Resumen de las titulaciones validadas del candidato al momento de hacer el cálculo';
--/////////////////////
ALTER TABLE TBEP_HTO_SOLICITUD_BOLSAS ADD (
	ACREDITACIONES_VALIDADAS CLOB NULL,
	TITULACIONES_VALIDADAS CLOB NULL
);
--/////////////////////
CREATE OR REPLACE TRIGGER DBEP_SBO_BRI
BEFORE INSERT
ON TBEP_SOLICITUD_BOLSAS
FOR EACH ROW
DECLARE
BEGIN
	SELECT QBEP_SBO.nextval into :new.CODNUM FROM dual;
	
    INSERT INTO TBEP_HTO_SOLICITUD_BOLSAS (CODCAMBIO,LOG,CODNUM,BEPBOL_CODNUM,BEPSOL_CODNUM,TOTAL,TOTALSINAPLICAR,DESGLOSETOTAL,DESGLOSEDESCRIPCION,FECHABAREMACION,ACREDITACIONES_VALIDADAS,TITULACIONES_VALIDADAS,UID_USUARIO)
    VALUES (QBEP_HTO_SBO.NEXTVAL,'AFTER_INSERT',:New.CODNUM,:New.BEPBOL_CODNUM,:New.BEPSOL_CODNUM,:New.TOTAL,:New.TOTALSINAPLICAR,:New.DESGLOSETOTAL,:New.DESGLOSEDESCRIPCION,:New.FECHABAREMACION,:New.ACREDITACIONES_VALIDADAS,:New.TITULACIONES_VALIDADAS,:New.UID_USUARIO);
END DBEP_SBO_BRI;
--/////////////////////
CREATE OR REPLACE TRIGGER DBEP_SBO_BRU
BEFORE UPDATE
ON TBEP_SOLICITUD_BOLSAS
FOR EACH ROW
DECLARE
BEGIN
	INSERT INTO TBEP_HTO_SOLICITUD_BOLSAS (CODCAMBIO,LOG,CODNUM,BEPBOL_CODNUM,BEPSOL_CODNUM,TOTAL,TOTALSINAPLICAR,DESGLOSETOTAL,DESGLOSEDESCRIPCION,FECHABAREMACION,ACREDITACIONES_VALIDADAS,TITULACIONES_VALIDADAS,UID_USUARIO)
    VALUES (QBEP_HTO_SBO.NEXTVAL,'BEFORE_UPDATE',:Old.CODNUM,:Old.BEPBOL_CODNUM,:Old.BEPSOL_CODNUM,:Old.TOTAL,:Old.TOTALSINAPLICAR,:Old.DESGLOSETOTAL,:Old.DESGLOSEDESCRIPCION,:Old.FECHABAREMACION,:Old.ACREDITACIONES_VALIDADAS,:Old.TITULACIONES_VALIDADAS,:Old.UID_USUARIO);
    
 	INSERT INTO TBEP_HTO_SOLICITUD_BOLSAS (CODCAMBIO,LOG,CODNUM,BEPBOL_CODNUM,BEPSOL_CODNUM,TOTAL,TOTALSINAPLICAR,DESGLOSETOTAL,DESGLOSEDESCRIPCION,FECHABAREMACION,ACREDITACIONES_VALIDADAS,TITULACIONES_VALIDADAS,UID_USUARIO)
    VALUES (QBEP_HTO_SBO.NEXTVAL,'AFTER_UPDATE',:New.CODNUM,:New.BEPBOL_CODNUM,:New.BEPSOL_CODNUM,:New.TOTAL,:New.TOTALSINAPLICAR,:New.DESGLOSETOTAL,:New.DESGLOSEDESCRIPCION,:New.FECHABAREMACION,:New.ACREDITACIONES_VALIDADAS,:New.TITULACIONES_VALIDADAS,:New.UID_USUARIO);
END DBEP_SBO_BRU;
--/////////////////////
CREATE OR REPLACE TRIGGER DBEP_SBO_BRD
BEFORE DELETE
ON TBEP_SOLICITUD_BOLSAS
FOR EACH ROW
DECLARE
BEGIN
	INSERT INTO TBEP_HTO_SOLICITUD_BOLSAS (CODCAMBIO,LOG,CODNUM,BEPBOL_CODNUM,BEPSOL_CODNUM,TOTAL,TOTALSINAPLICAR,DESGLOSETOTAL,DESGLOSEDESCRIPCION,FECHABAREMACION,ACREDITACIONES_VALIDADAS,TITULACIONES_VALIDADAS,UID_USUARIO)
    VALUES (QBEP_HTO_SBO.NEXTVAL,'BEFORE_DELETE',:Old.CODNUM,:Old.BEPBOL_CODNUM,:Old.BEPSOL_CODNUM,:Old.TOTAL,:Old.TOTALSINAPLICAR,:Old.DESGLOSETOTAL,:Old.DESGLOSEDESCRIPCION,:Old.FECHABAREMACION,:Old.ACREDITACIONES_VALIDADAS,:Old.TITULACIONES_VALIDADAS,:Old.UID_USUARIO);
END DBEP_SBO_BRD;