UPDATE TBEP_APARTADOSBAREMACION SET PORCENTAJEMAXIMO = 0.4 WHERE PORCENTAJEMAXIMO = 0.5 AND CODIGO = 'I';
--/////////////////////
UPDATE TBEP_APARTADOSBAREMACION SET PORCENTAJEMAXIMO = 0.3 WHERE PORCENTAJEMAXIMO = 0.2 AND CODIGO = 'II';