UPDATE (
	SELECT PORCENTAJEMAXIMO FROM TBEP_APARTADOSBAREMACION
	WHERE PORCENTAJEMAXIMO = 0.5
)
SET PORCENTAJEMAXIMO = 0.4;
--/////////////////////
UPDATE (
	SELECT PORCENTAJEMAXIMO FROM TBEP_APARTADOSBAREMACION
	WHERE PORCENTAJEMAXIMO = 0.2
)
SET PORCENTAJEMAXIMO = 0.3;