CREATE OR REPLACE TRIGGER DBEP_SBM_BRI
BEFORE INSERT
ON TBEP_SOL_BOL_MERITOS
FOR EACH ROW
DECLARE
BEGIN
    SELECT QBEP_SBM.nextval into :new.CODNUM FROM dual;

    INSERT INTO TBEP_HTO_SOL_BOL_MERITOS (CODCAMBIO,LOG,CODNUM,BEPSBO_CODNUM,BEPMER_CODNUM,FLGEXCLUIDO,FLGVALIDADO,OBSERVACION_CANDIDATO,VALOR,DESGLOSE,RESULTADO,BEPITE_CODNUM,UID_USUARIO)
    VALUES (QBEP_HTO_SBM.NEXTVAL,'AFTER_INSERT',:New.CODNUM,:New.BEPSBO_CODNUM,:New.BEPMER_CODNUM,:New.FLGEXCLUIDO,:New.FLGVALIDADO,:New.OBSERVACION_CANDIDATO,:New.VALOR,:New.DESGLOSE,:New.RESULTADO,:New.BEPITE_CODNUM,:New.UID_USUARIO);
END DBEP_SBM_BRI;
--/////////////////////
CREATE OR REPLACE TRIGGER DBEP_SBM_BRU
BEFORE UPDATE
ON TBEP_SOL_BOL_MERITOS
FOR EACH ROW
DECLARE
BEGIN
	INSERT INTO TBEP_HTO_SOL_BOL_MERITOS (CODCAMBIO,LOG,CODNUM,BEPSBO_CODNUM,BEPMER_CODNUM,FLGEXCLUIDO,FLGVALIDADO,OBSERVACION_CANDIDATO,VALOR,DESGLOSE,RESULTADO,BEPITE_CODNUM,UID_USUARIO)
    VALUES (QBEP_HTO_SBM.NEXTVAL,'BEFORE_UPDATE',:Old.CODNUM,:Old.BEPSBO_CODNUM,:Old.BEPMER_CODNUM,:Old.FLGEXCLUIDO,:Old.FLGVALIDADO,:Old.OBSERVACION_CANDIDATO,:Old.VALOR,:Old.DESGLOSE,:Old.RESULTADO,:Old.BEPITE_CODNUM,:Old.UID_USUARIO);
    
 	INSERT INTO TBEP_HTO_SOL_BOL_MERITOS (CODCAMBIO,LOG,CODNUM,BEPSBO_CODNUM,BEPMER_CODNUM,FLGEXCLUIDO,FLGVALIDADO,OBSERVACION_CANDIDATO,VALOR,DESGLOSE,RESULTADO,BEPITE_CODNUM,UID_USUARIO)
    VALUES (QBEP_HTO_SBM.NEXTVAL,'AFTER_UPDATE',:New.CODNUM,:New.BEPSBO_CODNUM,:New.BEPMER_CODNUM,:New.FLGEXCLUIDO,:New.FLGVALIDADO,:New.OBSERVACION_CANDIDATO,:New.VALOR,:New.DESGLOSE,:New.RESULTADO,:New.BEPITE_CODNUM,:New.UID_USUARIO);
END DBEP_SBM_BRU;
--/////////////////////
CREATE OR REPLACE TRIGGER DBEP_SBM_BRD
BEFORE DELETE
ON TBEP_SOL_BOL_MERITOS
FOR EACH ROW
DECLARE
BEGIN
	INSERT INTO TBEP_HTO_SOL_BOL_MERITOS (CODCAMBIO,LOG,CODNUM,BEPSBO_CODNUM,BEPMER_CODNUM,FLGEXCLUIDO,FLGVALIDADO,OBSERVACION_CANDIDATO,VALOR,DESGLOSE,RESULTADO,BEPITE_CODNUM,UID_USUARIO)
    VALUES (QBEP_HTO_SBM.NEXTVAL,'BEFORE_DELETE',:Old.CODNUM,:Old.BEPSBO_CODNUM,:Old.BEPMER_CODNUM,:Old.FLGEXCLUIDO,:Old.FLGVALIDADO,:Old.OBSERVACION_CANDIDATO,:Old.VALOR,:Old.DESGLOSE,:Old.RESULTADO,:Old.BEPITE_CODNUM,:Old.UID_USUARIO);
END DBEP_SBM_BRD;