INSERT INTO ADM_MENU (MNU_CODNUM, CONTROLADOR, FLG_DISPONIBLE, FLG_MOSTRAR, FLG_CREAMENU, FLG_PDFINTERNO, FLG_EXCEL, FLG_WORD, FLG_ANONIMO, PADRE_CODNUM, FLG_LOG) VALUES (1134, 'informacionadministrativa.bolsaempleo.contratacion', 'S', 'S', 'S','N', 'N', 'N', 'N', 1100, 'N');
--/////////////////////
INSERT INTO ADM_MENU_DOM (MNU_CODNUM, DOM_CODALF) VALUES (1134, 'ujaen.es');
--/////////////////////
INSERT INTO ADM_MENU_IDM (MNU_CODNUM, IDM_CODALF, DESCRIPCION) VALUES (1134, 'es', '   Contratación');
--/////////////////////
INSERT INTO ADM_MENU_SIS (MNU_CODNUM, SIS_CODALF) VALUES (1134, 'uvirtual');
--/////////////////////
INSERT INTO ADM_MENU_RED (MNU_CODNUM, RED, DESCRIPCION, FLG_DESACT) VALUES (1134, '0.0.0.0/0', 'Publico', 'N');
--/////////////////////
INSERT INTO ADM_MENU_ROL (MNU_CODNUM, ROL_CODNUM, FLG_DESACT, FLG_ADMIN) VALUES (1134, 1050, 'N', 'N');
--/////////////////////
INSERT INTO ADM_MENU_ROL (MNU_CODNUM, ROL_CODNUM, FLG_DESACT, FLG_ADMIN) VALUES (1134, 1053, 'N', 'N');
--/////////////////////
DELETE FROM ADM_MENU_ROL WHERE MNU_CODNUM = 1134 AND ROL_CODNUM IN (1050, 1051, 1052, 1053, 1);
--/////////////////////
DELETE FROM ADM_MENU_DOM WHERE MNU_CODNUM = 1134;
--/////////////////////
DELETE FROM ADM_MENU_IDM WHERE MNU_CODNUM = 1134;
--/////////////////////
DELETE FROM ADM_MENU_SIS WHERE MNU_CODNUM = 1134;
--/////////////////////
DELETE FROM ADM_MENU_RED WHERE MNU_CODNUM = 1134;
--/////////////////////
DELETE FROM ADM_MENU WHERE MNU_CODNUM = 1134;
--/////////////////////
CREATE TABLE TBEP_PLAZAS_OFERTADAS (
	CODNUM NUMBER(11,0) CONSTRAINT RBEP_NPLO_CODNUM NOT NULL,
	BEPARE_CODNUM NUMBER(11,0) CONSTRAINT RBEP_NPLO_BEPARE_CODNUM NOT NULL,
	FECHA_CREACION TIMESTAMP DEFAULT CURRENT_TIMESTAMP CONSTRAINT RBEP_NPLO_FECHA_CREACION NOT NULL,
	FECHA_ABIERTA TIMESTAMP NULL,
	FECHA_CERRADA TIMESTAMP NULL,
    ESTADO CHAR(8) DEFAULT 'BORRADOR',
    UID_USUARIO VARCHAR2(100) CONSTRAINT RBEP_NPLO_UIDUSUARIO NOT NULL,
    CONSTRAINT IBEP_PPLO PRIMARY KEY (CODNUM),
    CONSTRAINT IBEP_FPLO_ARE FOREIGN KEY (BEPARE_CODNUM) REFERENCES TBEP_AREAS (CODNUM),
    CONSTRAINT RBEP_CPLO_ESTADO CHECK(ESTADO IN ('BORRADOR','VALIDACION', 'ABIERTA', 'CERRADA'))
);
--/////////////////////
COMMENT ON COLUMN TBEP_PLAZAS_OFERTADAS.FECHA_CREACION IS 'Fecha de creación de la plaza';
--/////////////////////
COMMENT ON COLUMN TBEP_PLAZAS_OFERTADAS.FECHA_ABIERTA IS 'Fecha de apertura de la plaza';
--/////////////////////
COMMENT ON COLUMN TBEP_PLAZAS_OFERTADAS.FECHA_CERRADA IS 'Fecha de cierre de la plaza';
--/////////////////////
COMMENT ON COLUMN TBEP_PLAZAS_OFERTADAS.ESTADO IS 'Estado de la plaza';
--/////////////////////
COMMENT ON TABLE TBEP_PLAZAS_OFERTADAS IS 'Plazas ofertadas. ALIAS: [bepplo] ACRONIMO: [PLO]';
--/////////////////////
CREATE TABLE TBEP_HTO_PLAZAS_OFERTADAS (
	CODCAMBIO NUMBER(11,0) CONSTRAINT RBEP_NPLO_HTO_CODCAMBIO NOT NULL,
	LOG VARCHAR(50) CONSTRAINT RBEP_NPLO_HTO_LOG NOT NULL,
 	FECHALOG TIMESTAMP DEFAULT CURRENT_TIMESTAMP CONSTRAINT RBEP_NPLO_HTO_FECHALOG NOT NULL,
 	BEPARE_CODNUM NUMBER(11,0) CONSTRAINT RBEP_NPLO_HTO_BEPARE_CODNUM NOT NULL,
 	FECHA_CREACION TIMESTAMP CONSTRAINT RBEP_NPLO_HTO_FECHA_CREACION NOT NULL,
	FECHA_ABIERTA TIMESTAMP NULL,
	FECHA_CERRADA TIMESTAMP NULL,
    ESTADO CHAR(8) DEFAULT 'BORRADOR',
    UID_USUARIO VARCHAR2(100) CONSTRAINT RBEP_NPLO_HTO_UIDUSUARIO NOT NULL,
 	CONSTRAINT IBEP_PPLO_HISTORICO PRIMARY KEY (CODCAMBIO)
);
--/////////////////////
CREATE SEQUENCE QBEP_PLO START WITH 1;
--/////////////////////
CREATE SEQUENCE QBEP_HTO_PLO START WITH 1;
--/////////////////////
CREATE TRIGGER DBEP_PLO_BRI
BEFORE INSERT
ON TBEP_PLAZAS_OFERTADAS
FOR EACH ROW
DECLARE
BEGIN
    SELECT QBEP_PLO.nextval into :new.CODNUM FROM dual;
    
    INSERT INTO TBEP_HTO_PLAZAS_OFERTADAS (CODCAMBIO,LOG,CODNUM,BEPARE_CODNUM,FECHA_CREACION,FECHA_ABIERTA,FECHA_CERRADA,ESTADO,UID_USUARIO)
    VALUES (QBEP_HTO_PLO.NEXTVAL,'AFTER_INSERT',:New.CODNUM,:New.BEPARE_CODNUM,:New.FECHA_CREACION,:New.FECHA_ABIERTA,:New.FECHA_CERRADA,:New.ESTADO,:New.UID_USUARIO);
END DBEP_PLO_BRI;
--/////////////////////
CREATE TRIGGER DBEP_PLO_BRU
BEFORE UPDATE
ON TBEP_PLAZAS_OFERTADAS
FOR EACH ROW
DECLARE
BEGIN
	INSERT INTO TBEP_HTO_PLAZAS_OFERTADAS (CODCAMBIO,LOG,CODNUM,BEPARE_CODNUM,FECHA_CREACION,FECHA_ABIERTA,FECHA_CERRADA,ESTADO,UID_USUARIO)
    VALUES (QBEP_HTO_PLO.NEXTVAL,'BEFORE_UPDATE',:Old.CODNUM,:Old.BEPARE_CODNUM,:Old.FECHA_CREACION,:Old.FECHA_ABIERTA,:Old.FECHA_CERRADA,:Old.ESTADO,:Old.UID_USUARIO);
    
 	INSERT INTO TBEP_HTO_PLAZAS_OFERTADAS (CODCAMBIO,LOG,CODNUM,BEPARE_CODNUM,FECHA_CREACION,FECHA_ABIERTA,FECHA_CERRADA,ESTADO,UID_USUARIO)
    VALUES (QBEP_HTO_PLO.NEXTVAL,'AFTER_UPDATE',:New.CODNUM,:New.BEPARE_CODNUM,:New.FECHA_CREACION,:New.FECHA_ABIERTA,:New.FECHA_CERRADA,:New.ESTADO,:New.UID_USUARIO);
END DBEP_PLO_BRU;
--/////////////////////
CREATE TRIGGER DBEP_PLO_BRD
BEFORE DELETE
ON TBEP_PLAZAS_OFERTADAS
FOR EACH ROW
DECLARE
BEGIN
	INSERT INTO TBEP_HTO_PLAZAS_OFERTADAS (CODCAMBIO,LOG,CODNUM,BEPARE_CODNUM,FECHA_CREACION,FECHA_ABIERTA,FECHA_CERRADA,ESTADO,UID_USUARIO)
    VALUES (QBEP_HTO_PLO.NEXTVAL,'BEFORE_DELETE',:Old.CODNUM,:Old.BEPARE_CODNUM,:Old.FECHA_CREACION,:Old.FECHA_ABIERTA,:Old.FECHA_CERRADA,:Old.ESTADO,:Old.UID_USUARIO);
END DBEP_PLO_BRD;