CREATE TABLE TBEP_DEDICACIONES (
	CODNUM NUMBER(11,0) CONSTRAINT RBEP_NDED_CODNUM NOT NULL,
	TEXTO VARCHAR2(200) CONSTRAINT RBEP_NDED_TEXTO NOT NULL,
	SUELDO NUMBER(10, 2) CONSTRAINT RBEP_NDED_SUELDO NOT NULL,
	FECHA_VIGENCIA TIMESTAMP DEFAULT CURRENT_TIMESTAMP CONSTRAINT RBEP_NDED_FECHA_VIGENCIA  NOT NULL,
	FLGACTIVA CHAR(1) DEFAULT 'S',
	UID_USUARIO VARCHAR2(100) CONSTRAINT RBEP_NDED_UIDUSUARIO NOT NULL,
	CONSTRAINT IBEP_PDED PRIMARY KEY (CODNUM)
);
--/////////////////////
COMMENT ON COLUMN TBEP_DEDICACIONES.TEXTO IS 'Dedicación semanal de la plaza';
--/////////////////////
COMMENT ON COLUMN TBEP_DEDICACIONES.SUELDO IS 'Retribución bruta mensual para la dedicación descrita';
--/////////////////////
COMMENT ON COLUMN TBEP_DEDICACIONES.FECHA_VIGENCIA IS 'Muestra la fecha desde la que está vigente la dedicación';
--/////////////////////
COMMENT ON COLUMN TBEP_DEDICACIONES.FLGACTIVA IS 'Indica si la dedicación está borrada o no';
--/////////////////////
COMMENT ON TABLE TBEP_DEDICACIONES IS 'Dedicaciones. ALIAS: [bepded] ACRONIMO: [DED]';
--/////////////////////
CREATE TABLE TBEP_HTO_DEDICACIONES (
	CODCAMBIO NUMBER(11,0) CONSTRAINT RBEP_NDED_HTO_CODCAMBIO NOT NULL,
	LOG VARCHAR(50) CONSTRAINT RBEP_NDED_HTO_LOG NOT NULL,
	FECHALOG TIMESTAMP DEFAULT CURRENT_TIMESTAMP CONSTRAINT RBEP_NDED_HTO_FECHALOG NOT NULL,
	CODNUM NUMBER(11,0) CONSTRAINT RBEP_NDED_HTO_CODNUM NOT NULL,
	TEXTO VARCHAR2(200) CONSTRAINT RBEP_NDED_HTO_TEXTO NOT NULL,
	SUELDO NUMBER(10, 2) CONSTRAINT RBEP_NDED_HTO_SUELDO NOT NULL,
	FECHA_VIGENCIA  TIMESTAMP CONSTRAINT RBEP_NDED_HTO_FECHA_VIGENCIA  NOT NULL,
	FLGACTIVA CHAR(1) DEFAULT 'S',
	UID_USUARIO VARCHAR2(100) CONSTRAINT RBEP_NDED_HTO_UIDUSUARIO NOT NULL,
	CONSTRAINT IBEP_PDED_HISTORICO PRIMARY KEY (CODCAMBIO)
);
--/////////////////////
CREATE SEQUENCE QBEP_DED START WITH 1;
--/////////////////////
CREATE SEQUENCE QBEP_HTO_DED START WITH 1;
--/////////////////////
CREATE TRIGGER DBEP_DED_BRI
BEFORE INSERT
ON TBEP_DEDICACIONES
FOR EACH ROW
DECLARE
BEGIN
	SELECT QBEP_DED.nextval into :new.CODNUM FROM dual;
	
	INSERT INTO TBEP_HTO_DEDICACIONES (CODCAMBIO,LOG,CODNUM,TEXTO,SUELDO,FECHA_VIGENCIA,FLGACTIVA,UID_USUARIO)
	VALUES (QBEP_HTO_DED.NEXTVAL,'AFTER_INSERT',:New.CODNUM,:New.TEXTO,:New.SUELDO,:New.FECHA_VIGENCIA,:New.FLGACTIVA,:New.UID_USUARIO);
END DBEP_DED_BRI;
--/////////////////////
CREATE TRIGGER DBEP_DED_BRU
BEFORE UPDATE
ON TBEP_DEDICACIONES
FOR EACH ROW
DECLARE
BEGIN
	INSERT INTO TBEP_HTO_DEDICACIONES (CODCAMBIO,LOG,CODNUM,TEXTO,SUELDO,FECHA_VIGENCIA,FLGACTIVA,UID_USUARIO)
	VALUES (QBEP_HTO_DED.NEXTVAL,'BEFORE_UPDATE',:Old.CODNUM,:Old.TEXTO,:Old.SUELDO,:Old.FECHA_VIGENCIA,:Old.FLGACTIVA,:Old.UID_USUARIO);
	
	INSERT INTO TBEP_HTO_DEDICACIONES (CODCAMBIO,LOG,CODNUM,TEXTO,SUELDO,FECHA_VIGENCIA,FLGACTIVA,UID_USUARIO)
	VALUES (QBEP_HTO_DED.NEXTVAL,'AFTER_UPDATE',:New.CODNUM,:New.TEXTO,:New.SUELDO,:New.FECHA_VIGENCIA,:New.FLGACTIVA,:New.UID_USUARIO);
END DBEP_DED_BRU;
--/////////////////////
CREATE TRIGGER DBEP_DED_BRD
BEFORE DELETE
ON TBEP_DEDICACIONES
FOR EACH ROW
DECLARE
BEGIN
	INSERT INTO TBEP_HTO_DEDICACIONES (CODCAMBIO,LOG,CODNUM,TEXTO,SUELDO,FECHA_VIGENCIA,FLGACTIVA,UID_USUARIO)
	VALUES (QBEP_HTO_DED.NEXTVAL,'BEFORE_DELETE',:Old.CODNUM,:Old.TEXTO,:Old.SUELDO,:Old.FECHA_VIGENCIA,:Old.FLGACTIVA,:Old.UID_USUARIO);
END DBEP_DED_BRD;