CREATE TABLE TBEP_PLAZAS_OFERTADAS (
	CODNUM NUMBER(11,0) CONSTRAINT RBEP_NPLO_CODNUM NOT NULL,
	BEPARE_CODNUM NUMBER(11,0) CONSTRAINT RBEP_NPLO_BEPARE_CODNUM NOT NULL,
	BEPDED_CODNUM NUMBER(11,0) NULL,
	JUSTIFICACION VARCHAR2(400) CONSTRAINT RBEP_NPLO_JUSTIFICACION NOT NULL,
	DURACION_PREVISTA VARCHAR2(100) NULL,
	CUATRIMESTRE CHAR(15) NULL,
	CENTRO_DESTINO CHAR(7) CONSTRAINT RBEP_NPLO_CENTRO_DESTINO NOT NULL,
	FECHA_CREACION TIMESTAMP DEFAULT CURRENT_TIMESTAMP CONSTRAINT RBEP_NPLO_FECHA_CREACION NOT NULL,
	FECHA_ABIERTA TIMESTAMP NULL,
	FECHA_FIN_OFERTA TIMESTAMP NULL,
	FECHA_CERRADA TIMESTAMP NULL,
	HORARIO BLOB CONSTRAINT RBEP_NPLO_HORARIO NULL,
	NRI BLOB CONSTRAINT RBEP_NPLO_NRI NULL,
	NRI_FECHA TIMESTAMP NULL,
	ESTADO CHAR(12) DEFAULT 'CREACION',
	OBSERVACIONES_INTERNAS VARCHAR2(300 CHAR) NULL,
	UID_USUARIO VARCHAR2(100) CONSTRAINT RBEP_NPLO_UIDUSUARIO NOT NULL,
	CONSTRAINT IBEP_PPLO PRIMARY KEY (CODNUM),
	CONSTRAINT IBEP_FPLO_ARE FOREIGN KEY (BEPARE_CODNUM) REFERENCES TBEP_AREAS (CODNUM),
	CONSTRAINT IBEP_FPLO_DED FOREIGN KEY (BEPDED_CODNUM) REFERENCES TBEP_DEDICACIONES (CODNUM),
	CONSTRAINT RBEP_CPLO_ESTADO CHECK(ESTADO IN ('CREACION','TRAMITACION', 'ABIERTA', 'CONTRATACION', 'CERRADA')),
	CONSTRAINT RBEP_CPLO_CUATRIMESTRE CHECK(CUATRIMESTRE IN ('1º CUATRIMESTRE','2º CUATRIMESTRE', 'TODO EL CURSO')),
	CONSTRAINT RBEP_CPLO_CENTRO_DESTINO CHECK(CENTRO_DESTINO IN ('JAEN','LINARES'))
);
--/////////////////////
COMMENT ON COLUMN TBEP_PLAZAS_OFERTADAS.BEPARE_CODNUM IS 'Clave foránea a tabla áreas';
--/////////////////////
COMMENT ON COLUMN TBEP_PLAZAS_OFERTADAS.BEPDED_CODNUM IS 'Clave foránea a tabla dedicaciones';
--/////////////////////
COMMENT ON COLUMN TBEP_PLAZAS_OFERTADAS.JUSTIFICACION IS 'Describe la causa que orgina la contratación de un sustituto';
--/////////////////////
COMMENT ON COLUMN TBEP_PLAZAS_OFERTADAS.DURACION_PREVISTA IS 'Indica la duración prevista o la fecha fin de la sustitución';
--/////////////////////
COMMENT ON COLUMN TBEP_PLAZAS_OFERTADAS.CUATRIMESTRE IS 'Indica el cuatrimestre para el que está previsto la sustitución';
--/////////////////////
COMMENT ON COLUMN TBEP_PLAZAS_OFERTADAS.CENTRO_DESTINO IS 'Indica la localidad en la que se realizará la sustitución';
--/////////////////////
COMMENT ON COLUMN TBEP_PLAZAS_OFERTADAS.FECHA_CREACION IS 'Fecha de creación de la plaza';
--/////////////////////
COMMENT ON COLUMN TBEP_PLAZAS_OFERTADAS.FECHA_ABIERTA IS 'Fecha de apertura de la plaza';
--/////////////////////
COMMENT ON COLUMN TBEP_PLAZAS_OFERTADAS.FECHA_FIN_OFERTA IS 'Indica el día hasta el que estará abierta la oferta para la aceptación de los candidatos';
--/////////////////////
COMMENT ON COLUMN TBEP_PLAZAS_OFERTADAS.FECHA_CERRADA IS 'Fecha de cierre de la plaza';
--/////////////////////
COMMENT ON COLUMN TBEP_PLAZAS_OFERTADAS.HORARIO IS 'Se almacenarán como datos adjuntos los horarios de docencia de la plaza';
--/////////////////////
COMMENT ON COLUMN TBEP_PLAZAS_OFERTADAS.NRI IS 'Se almacenarán como datos adjuntos la NRI por la que se autoriza el inicio del procedimiento de sustitución';
--/////////////////////
COMMENT ON COLUMN TBEP_PLAZAS_OFERTADAS.NRI_FECHA IS 'Mostrará la fecha en la que incorpora la NRI';
--/////////////////////
COMMENT ON COLUMN TBEP_PLAZAS_OFERTADAS.ESTADO IS 'Muestra el estado en el que se encuentra la plaza';
--/////////////////////
COMMENT ON TABLE TBEP_PLAZAS_OFERTADAS IS 'Plazas ofertadas. ALIAS: [bepplo] ACRONIMO: [PLO]';
--/////////////////////
CREATE TABLE TBEP_HTO_PLAZAS_OFERTADAS (
	CODCAMBIO NUMBER(11,0) CONSTRAINT RBEP_NPLO_HTO_CODCAMBIO NOT NULL,
	LOG VARCHAR(50) CONSTRAINT RBEP_NPLO_HTO_LOG NOT NULL,
	FECHALOG TIMESTAMP DEFAULT CURRENT_TIMESTAMP CONSTRAINT RBEP_NPLO_HTO_FECHALOG NOT NULL,
	CODNUM NUMBER(11,0) CONSTRAINT RBEP_NPLO_HTO_CODNUM NOT NULL,
	BEPARE_CODNUM NUMBER(11,0) CONSTRAINT RBEP_NPLO_HTO_BEPARE_CODNUM NOT NULL,
	BEPDED_CODNUM NUMBER(11,0) NULL,
	JUSTIFICACION VARCHAR2(400) CONSTRAINT RBEP_NPLO_HTO_JUSTIFICACION NOT NULL,
	DURACION_PREVISTA VARCHAR2(100) NULL,
	CUATRIMESTRE CHAR(15) NULL,
	CENTRO_DESTINO CHAR(7) CONSTRAINT RBEP_NPLO_HTO_CENTRO_DESTINO NOT NULL,
	FECHA_CREACION TIMESTAMP CONSTRAINT RBEP_NPLO_HTO_FECHA_CREACION NOT NULL,
	FECHA_ABIERTA TIMESTAMP NULL,
	FECHA_FIN_OFERTA TIMESTAMP NULL,
	FECHA_CERRADA TIMESTAMP NULL,
	HORARIO BLOB CONSTRAINT RBEP_NPLO_HTO_HORARIO NULL,
	NRI BLOB CONSTRAINT RBEP_NPLO_HTO_NRI NULL,
	NRI_FECHA TIMESTAMP NULL,
	ESTADO CHAR(12) DEFAULT 'CREACION',
	OBSERVACIONES_INTERNAS VARCHAR2(300 CHAR) NULL,
	UID_USUARIO VARCHAR2(100) CONSTRAINT RBEP_NPLO_HTO_UIDUSUARIO NOT NULL,
	CONSTRAINT IBEP_PPLO_HISTORICO PRIMARY KEY (CODCAMBIO)
);
--/////////////////////
CREATE SEQUENCE QBEP_PLO START WITH 1;
--/////////////////////
CREATE SEQUENCE QBEP_HTO_PLO START WITH 1;
--/////////////////////
CREATE TRIGGER DBEP_PLO_BRI
BEFORE INSERT
ON TBEP_PLAZAS_OFERTADAS
FOR EACH ROW
DECLARE
BEGIN
	SELECT QBEP_PLO.nextval into :new.CODNUM FROM dual;
	
	INSERT INTO TBEP_HTO_PLAZAS_OFERTADAS (CODCAMBIO,LOG,CODNUM,BEPARE_CODNUM,BEPDED_CODNUM,JUSTIFICACION,DURACION_PREVISTA,CUATRIMESTRE,CENTRO_DESTINO,FECHA_CREACION,FECHA_ABIERTA,FECHA_FIN_OFERTA,FECHA_CERRADA,HORARIO,NRI,NRI_FECHA,ESTADO,OBSERVACIONES_INTERNAS,UID_USUARIO)
	VALUES (QBEP_HTO_PLO.NEXTVAL,'AFTER_INSERT',:New.CODNUM,:New.BEPARE_CODNUM,:New.BEPDED_CODNUM,:New.JUSTIFICACION,:New.DURACION_PREVISTA,:New.CUATRIMESTRE,:New.CENTRO_DESTINO,:New.FECHA_CREACION,:New.FECHA_ABIERTA,:New.FECHA_FIN_OFERTA,:New.FECHA_CERRADA,:New.HORARIO,:New.NRI,:New.NRI_FECHA,:New.ESTADO,:New.OBSERVACIONES_INTERNAS,:New.UID_USUARIO);
END DBEP_PLO_BRI;
--/////////////////////
CREATE TRIGGER DBEP_PLO_BRU
BEFORE UPDATE
ON TBEP_PLAZAS_OFERTADAS
FOR EACH ROW
DECLARE
BEGIN
	INSERT INTO TBEP_HTO_PLAZAS_OFERTADAS (CODCAMBIO,LOG,CODNUM,BEPARE_CODNUM,BEPDED_CODNUM,JUSTIFICACION,DURACION_PREVISTA,CUATRIMESTRE,CENTRO_DESTINO,FECHA_CREACION,FECHA_ABIERTA,FECHA_FIN_OFERTA,FECHA_CERRADA,HORARIO,NRI,NRI_FECHA,ESTADO,OBSERVACIONES_INTERNAS,UID_USUARIO)
	VALUES (QBEP_HTO_PLO.NEXTVAL,'BEFORE_UPDATE',:Old.CODNUM,:Old.BEPARE_CODNUM,:Old.BEPDED_CODNUM,:Old.JUSTIFICACION,:Old.DURACION_PREVISTA,:Old.CUATRIMESTRE,:Old.CENTRO_DESTINO,:Old.FECHA_CREACION,:Old.FECHA_ABIERTA,:Old.FECHA_FIN_OFERTA,:Old.FECHA_CERRADA,:Old.HORARIO,:Old.NRI,:Old.NRI_FECHA,:Old.ESTADO,:Old.OBSERVACIONES_INTERNAS,:Old.UID_USUARIO);
	
	INSERT INTO TBEP_HTO_PLAZAS_OFERTADAS (CODCAMBIO,LOG,CODNUM,BEPARE_CODNUM,BEPDED_CODNUM,JUSTIFICACION,DURACION_PREVISTA,CUATRIMESTRE,CENTRO_DESTINO,FECHA_CREACION,FECHA_ABIERTA,FECHA_FIN_OFERTA,FECHA_CERRADA,HORARIO,NRI,NRI_FECHA,ESTADO,OBSERVACIONES_INTERNAS,UID_USUARIO)
	VALUES (QBEP_HTO_PLO.NEXTVAL,'AFTER_UPDATE',:New.CODNUM,:New.BEPARE_CODNUM,:New.BEPDED_CODNUM,:New.JUSTIFICACION,:New.DURACION_PREVISTA,:New.CUATRIMESTRE,:New.CENTRO_DESTINO,:New.FECHA_CREACION,:New.FECHA_ABIERTA,:New.FECHA_FIN_OFERTA,:New.FECHA_CERRADA,:New.HORARIO,:New.NRI,:New.NRI_FECHA,:New.ESTADO,:New.OBSERVACIONES_INTERNAS,:New.UID_USUARIO);
END DBEP_PLO_BRU;
--/////////////////////
CREATE TRIGGER DBEP_PLO_BRD
BEFORE DELETE
ON TBEP_PLAZAS_OFERTADAS
FOR EACH ROW
DECLARE
BEGIN
	INSERT INTO TBEP_HTO_PLAZAS_OFERTADAS (CODCAMBIO,LOG,CODNUM,BEPARE_CODNUM,BEPDED_CODNUM,JUSTIFICACION,DURACION_PREVISTA,CUATRIMESTRE,CENTRO_DESTINO,FECHA_CREACION,FECHA_ABIERTA,FECHA_FIN_OFERTA,FECHA_CERRADA,HORARIO,NRI,NRI_FECHA,ESTADO,OBSERVACIONES_INTERNAS,UID_USUARIO)
	VALUES (QBEP_HTO_PLO.NEXTVAL,'BEFORE_DELETE',:Old.CODNUM,:Old.BEPARE_CODNUM,:Old.BEPDED_CODNUM,:Old.JUSTIFICACION,:Old.DURACION_PREVISTA,:Old.CUATRIMESTRE,:Old.CENTRO_DESTINO,:Old.FECHA_CREACION,:Old.FECHA_ABIERTA,:Old.FECHA_FIN_OFERTA,:Old.FECHA_CERRADA,:Old.HORARIO,:Old.NRI,:Old.NRI_FECHA,:Old.ESTADO,:Old.OBSERVACIONES_INTERNAS,:Old.UID_USUARIO);
END DBEP_PLO_BRD;