CREATE TABLE TBEP_CONTRATACIONES (
	CODNUM NUMBER(11,0) CONSTRAINT RBEP_NCNT_CODNUM NOT NULL,
	BEPPLO_CODNUM NUMBER(11,0) CONSTRAINT RBEP_NCNT_BEPPLO_CODNUM NOT NULL,
	BEPUSU_CODNUM NUMBER(11,0) CONSTRAINT RBEP_NCNT_BEPUSU_CODNUM NOT NULL,
	FECHA_ENVIO TIMESTAMP NULL,
	FECHA_CITA TIMESTAMP NULL,
	RESULTADO CHAR(10) DEFAULT 'PENDIENTE',
	FECHA_RESULTADO TIMESTAMP NULL,
	UID_USUARIO VARCHAR2(100) CONSTRAINT RBEP_NCNT_UIDUSUARIO NOT NULL,
	CONSTRAINT IBEP_PCNT PRIMARY KEY (CODNUM),
	CONSTRAINT IBEP_FCNT_PLO FOREIGN KEY (BEPPLO_CODNUM) REFERENCES TBEP_PLAZAS_OFERTADAS (CODNUM),
	CONSTRAINT IBEP_FCNT_USU FOREIGN KEY (BEPUSU_CODNUM) REFERENCES TBEP_USUARIOS (CODNUM),
	CONSTRAINT IBEP_UCNT UNIQUE (BEPPLO_CODNUM, BEPUSU_CODNUM),
	CONSTRAINT RBEP_CCNT_RESULTADO CHECK(RESULTADO IN ('ACEPTADA','RECHAZADA', 'PENDIENTE', 'SUSPENDIDO'))
);
--/////////////////////
COMMENT ON COLUMN TBEP_CONTRATACIONES.BEPPLO_CODNUM IS 'Clave foránea a tabla plazas ofertadas';
--/////////////////////
COMMENT ON COLUMN TBEP_CONTRATACIONES.BEPUSU_CODNUM IS 'Clave foránea a tabla usuarios';
--/////////////////////
COMMENT ON COLUMN TBEP_CONTRATACIONES.FECHA_ENVIO IS 'Muestra la fecha en la que se envía la comunicación al candidato';
--/////////////////////
COMMENT ON COLUMN TBEP_CONTRATACIONES.FECHA_CITA IS 'Indica el día en el que el candidato se tendrá que personar para la firma';
--/////////////////////
COMMENT ON COLUMN TBEP_CONTRATACIONES.RESULTADO IS 'Toma los datos de la la confirmación de la aceptación o de a renuncia de la plaza por el candidato';
--/////////////////////
COMMENT ON COLUMN TBEP_CONTRATACIONES.FECHA_RESULTADO IS 'Indica la fecha en la que el candidato ha aceptado o rechazado';
--/////////////////////
COMMENT ON COLUMN TBEP_CONTRATACIONES.UID_USUARIO IS 'Ultimo usuario que hace cambios en la tabla';
--/////////////////////
COMMENT ON TABLE TBEP_CONTRATACIONES IS 'Contrataciones. ALIAS: [bepcnt] ACRONIMO: [CNT]';
--/////////////////////
CREATE TABLE TBEP_HTO_CONTRATACIONES (
	CODCAMBIO NUMBER(11,0) CONSTRAINT RBEP_NCNT_HTO_CODCAMBIO NOT NULL,
	LOG VARCHAR(50) CONSTRAINT RBEP_NCNT_HTO_LOG NOT NULL,
	FECHALOG TIMESTAMP DEFAULT CURRENT_TIMESTAMP CONSTRAINT RBEP_NCNT_HTO_FECHALOG NOT NULL,
	CODNUM NUMBER(11,0) CONSTRAINT RBEP_NCNT_HTO_CODNUM NOT NULL,
	BEPPLO_CODNUM NUMBER(11,0) CONSTRAINT RBEP_NCNT_HTO_BEPPLO_CODNUM NOT NULL,
	BEPUSU_CODNUM NUMBER(11,0) CONSTRAINT RBEP_NCNT_HTO_BEPUSU_CODNUM NOT NULL,
	FECHA_ENVIO TIMESTAMP NULL,
	FECHA_CITA TIMESTAMP NULL,
	RESULTADO CHAR(10) DEFAULT 'PENDIENTE',
	FECHA_RESULTADO TIMESTAMP NULL,
	UID_USUARIO VARCHAR2(100) CONSTRAINT RBEP_NCNT_HTO_UIDUSUARIO NOT NULL,
	CONSTRAINT IBEP_PCNT_HISTORICO PRIMARY KEY (CODCAMBIO)
);
--/////////////////////
CREATE SEQUENCE QBEP_CNT START WITH 1;
--/////////////////////
CREATE SEQUENCE QBEP_HTO_CNT START WITH 1;
--/////////////////////
CREATE TRIGGER DBEP_CNT_BRI
BEFORE INSERT
ON TBEP_CONTRATACIONES
FOR EACH ROW
DECLARE
BEGIN
	SELECT QBEP_CNT.nextval into :new.CODNUM FROM dual;
	
	INSERT INTO TBEP_HTO_CONTRATACIONES (CODCAMBIO,LOG,CODNUM,BEPPLO_CODNUM,BEPUSU_CODNUM,FECHA_ENVIO,FECHA_CITA,RESULTADO,FECHA_RESULTADO,UID_USUARIO)
	VALUES (QBEP_HTO_CNT.NEXTVAL,'AFTER_INSERT',:New.CODNUM,:New.BEPPLO_CODNUM,:New.BEPUSU_CODNUM,:New.FECHA_ENVIO,:New.FECHA_CITA,:New.RESULTADO,:New.FECHA_RESULTADO,:New.UID_USUARIO);
END DBEP_CNT_BRI;
--/////////////////////
CREATE TRIGGER DBEP_CNT_BRU
BEFORE UPDATE
ON TBEP_CONTRATACIONES
FOR EACH ROW
DECLARE
BEGIN
	INSERT INTO TBEP_HTO_CONTRATACIONES (CODCAMBIO,LOG,CODNUM,BEPPLO_CODNUM,BEPUSU_CODNUM,FECHA_ENVIO,FECHA_CITA,RESULTADO,FECHA_RESULTADO,UID_USUARIO)
	VALUES (QBEP_HTO_CNT.NEXTVAL,'BEFORE_UPDATE',:Old.CODNUM,:Old.BEPPLO_CODNUM,:Old.BEPUSU_CODNUM,:Old.FECHA_ENVIO,:Old.FECHA_CITA,:Old.RESULTADO,:Old.FECHA_RESULTADO,:Old.UID_USUARIO);
	
	INSERT INTO TBEP_HTO_CONTRATACIONES (CODCAMBIO,LOG,CODNUM,BEPPLO_CODNUM,BEPUSU_CODNUM,FECHA_ENVIO,FECHA_CITA,RESULTADO,FECHA_RESULTADO,UID_USUARIO)
	VALUES (QBEP_HTO_CNT.NEXTVAL,'AFTER_UPDATE',:New.CODNUM,:New.BEPPLO_CODNUM,:New.BEPUSU_CODNUM,:New.FECHA_ENVIO,:New.FECHA_CITA,:New.RESULTADO,:New.FECHA_RESULTADO,:New.UID_USUARIO);
END DBEP_CNT_BRU;
--/////////////////////
CREATE TRIGGER DBEP_CNT_BRD
BEFORE DELETE
ON TBEP_CONTRATACIONES
FOR EACH ROW
DECLARE
BEGIN
	INSERT INTO TBEP_HTO_CONTRATACIONES (CODCAMBIO,LOG,CODNUM,BEPPLO_CODNUM,BEPUSU_CODNUM,FECHA_ENVIO,FECHA_CITA,RESULTADO,FECHA_RESULTADO,UID_USUARIO)
	VALUES (QBEP_HTO_CNT.NEXTVAL,'BEFORE_DELETE',:Old.CODNUM,:Old.BEPPLO_CODNUM,:Old.BEPUSU_CODNUM,:Old.FECHA_ENVIO,:Old.FECHA_CITA,:Old.RESULTADO,:Old.FECHA_RESULTADO,:Old.UID_USUARIO);
END DBEP_CNT_BRD;