CREATE TABLE TBEP_OFERTAS_CANDIDATOS (
	CODNUM NUMBER(11,0) CONSTRAINT RBEP_NOFC_CODNUM NOT NULL,
	BEPPLO_CODNUM NUMBER(11,0) CONSTRAINT RBEP_NOFC_BEPPLO_CODNUM NOT NULL,
	BEPUSU_CODNUM NUMBER(11,0) CONSTRAINT RBEP_NOFC_BEPUSU_CODNUM NOT NULL,
	RESULTADO CHAR(10) NULL,
	FECHA_RESULTADO TIMESTAMP NULL,
	UID_USUARIO VARCHAR2(100) CONSTRAINT RBEP_NOFC_UIDUSUARIO NOT NULL,
	CONSTRAINT IBEP_POFC PRIMARY KEY (CODNUM),
	CONSTRAINT IBEP_FOFC_PLO FOREIGN KEY (BEPPLO_CODNUM) REFERENCES TBEP_PLAZAS_OFERTADAS (CODNUM),
	CONSTRAINT IBEP_FOFC_USU FOREIGN KEY (BEPUSU_CODNUM) REFERENCES TBEP_USUARIOS (CODNUM),
	CONSTRAINT RBEP_COFC_RESULTADO CHECK(RESULTADO IN ('ACEPTADA','RECHAZADA'))
);
--/////////////////////
COMMENT ON COLUMN TBEP_OFERTAS_CANDIDATOS.BEPPLO_CODNUM IS 'Clave foránea a tabla plazas ofertadas';
--/////////////////////
COMMENT ON COLUMN TBEP_OFERTAS_CANDIDATOS.BEPUSU_CODNUM IS 'Clave foránea a tabla usuarios';
--/////////////////////
COMMENT ON COLUMN TBEP_OFERTAS_CANDIDATOS.RESULTADO IS 'Toma los datos de la la confirmación de la aceptación o de a renuncia de la plaza por el candidato';
--/////////////////////
COMMENT ON COLUMN TBEP_OFERTAS_CANDIDATOS.FECHA_RESULTADO IS 'Indica la fecha en la que el candidato ha aceptado o rechazado';
--/////////////////////
COMMENT ON TABLE TBEP_OFERTAS_CANDIDATOS IS 'Ofertas candidatos. ALIAS: [bepofc] ACRONIMO: [OFC]';
--/////////////////////
CREATE TABLE TBEP_HTO_OFERTAS_CANDIDATOS (
	CODCAMBIO NUMBER(11,0) CONSTRAINT RBEP_NOFC_HTO_CODCAMBIO NOT NULL,
	LOG VARCHAR(50) CONSTRAINT RBEP_NOFC_HTO_LOG NOT NULL,
	FECHALOG TIMESTAMP DEFAULT CURRENT_TIMESTAMP CONSTRAINT RBEP_NOFC_HTO_FECHALOG NOT NULL,
	CODNUM NUMBER(11,0) CONSTRAINT RBEP_NOFC_HTO_CODNUM NOT NULL,
	BEPPLO_CODNUM NUMBER(11,0) CONSTRAINT RBEP_NOFC_HTO_BEPPLO_CODNUM NOT NULL,
	BEPUSU_CODNUM NUMBER(11,0) CONSTRAINT RBEP_NOFC_HTO_BEPUSU_CODNUM NOT NULL,
	RESULTADO CHAR(10) DEFAULT 'IGNORADA',
	FECHA_RESULTADO TIMESTAMP NULL,
	UID_USUARIO VARCHAR2(100) CONSTRAINT RBEP_NOFC_HTO_UIDUSUARIO NOT NULL,
	CONSTRAINT IBEP_POFC_HISTORICO PRIMARY KEY (CODCAMBIO)
);
--/////////////////////
CREATE SEQUENCE QBEP_OFC START WITH 1;
--/////////////////////
CREATE SEQUENCE QBEP_HTO_OFC START WITH 1;
--/////////////////////
CREATE TRIGGER DBEP_OFC_BRI
BEFORE INSERT
ON TBEP_OFERTAS_CANDIDATOS
FOR EACH ROW
DECLARE
BEGIN
	SELECT QBEP_OFC.nextval into :new.CODNUM FROM dual;
	
	INSERT INTO TBEP_HTO_OFERTAS_CANDIDATOS (CODCAMBIO,LOG,CODNUM,BEPPLO_CODNUM,BEPUSU_CODNUM,RESULTADO,FECHA_RESULTADO,UID_USUARIO)
	VALUES (QBEP_HTO_OFC.NEXTVAL,'AFTER_INSERT',:New.CODNUM,:New.BEPPLO_CODNUM,:New.BEPUSU_CODNUM,:New.RESULTADO,:New.FECHA_RESULTADO,:New.UID_USUARIO);
END DBEP_OFC_BRI;
--/////////////////////
CREATE TRIGGER DBEP_OFC_BRU
BEFORE UPDATE
ON TBEP_OFERTAS_CANDIDATOS
FOR EACH ROW
DECLARE
BEGIN
	INSERT INTO TBEP_HTO_OFERTAS_CANDIDATOS (CODCAMBIO,LOG,CODNUM,BEPPLO_CODNUM,BEPUSU_CODNUM,RESULTADO,FECHA_RESULTADO,UID_USUARIO)
	VALUES (QBEP_HTO_OFC.NEXTVAL,'BEFORE_UPDATE',:Old.CODNUM,:Old.BEPPLO_CODNUM,:Old.BEPUSU_CODNUM,:Old.RESULTADO,:Old.FECHA_RESULTADO,:Old.UID_USUARIO);
	
	INSERT INTO TBEP_HTO_OFERTAS_CANDIDATOS (CODCAMBIO,LOG,CODNUM,BEPPLO_CODNUM,BEPUSU_CODNUM,RESULTADO,FECHA_RESULTADO,UID_USUARIO)
	VALUES (QBEP_HTO_OFC.NEXTVAL,'AFTER_UPDATE',:New.CODNUM,:New.BEPPLO_CODNUM,:New.BEPUSU_CODNUM,:New.RESULTADO,:New.FECHA_RESULTADO,:New.UID_USUARIO);
END DBEP_OFC_BRU;
--/////////////////////
CREATE TRIGGER DBEP_OFC_BRD
BEFORE DELETE
ON TBEP_OFERTAS_CANDIDATOS
FOR EACH ROW
DECLARE
BEGIN
	INSERT INTO TBEP_HTO_OFERTAS_CANDIDATOS (CODCAMBIO,LOG,CODNUM,BEPPLO_CODNUM,BEPUSU_CODNUM,RESULTADO,FECHA_RESULTADO,UID_USUARIO)
	VALUES (QBEP_HTO_OFC.NEXTVAL,'BEFORE_DELETE',:Old.CODNUM,:Old.BEPPLO_CODNUM,:Old.BEPUSU_CODNUM,:Old.RESULTADO,:Old.FECHA_RESULTADO,:Old.UID_USUARIO);
END DBEP_OFC_BRD;