CREATE TABLE TBEP_PLANTILLAS (
	CODNUM NUMBER(11,0) CONSTRAINT RBEP_NPLS_CODNUM NOT NULL,
	NOMBRE VARCHAR2(150) CONSTRAINT RBEP_NPLS_NOMBRE NOT NULL,
	TITULO VARCHAR2(500) CONSTRAINT RBEP_NPLS_TITULO NOT NULL,
	CUERPO CLOB CONSTRAINT RBEP_NPLS_DESCRIPCION NOT NULL,
	UID_USUARIO VARCHAR2(100) CONSTRAINT RBEP_NPLS_UID_USUARIO NOT NULL,
	CONSTRAINT IBEP_PPLS PRIMARY KEY (CODNUM)
);
--/////////////////////
COMMENT ON COLUMN TBEP_PLANTILLAS.NOMBRE IS 'Nombre de la plantilla';
--/////////////////////
COMMENT ON COLUMN TBEP_PLANTILLAS.TITULO IS 'Título de la plantilla';
--/////////////////////
COMMENT ON COLUMN TBEP_PLANTILLAS.CUERPO IS 'Cuerpo de la plantilla';
--/////////////////////
COMMENT ON COLUMN TBEP_PLANTILLAS.UID_USUARIO IS 'Ultimo usuario que hace cambios en la tabla';
--/////////////////////
COMMENT ON TABLE TBEP_PLANTILLAS IS 'Plantillas. ALIAS: [beppls] ACRONIMO: [PLS]';
--/////////////////////
CREATE TABLE TBEP_HTO_PLANTILLAS (
	CODCAMBIO NUMBER(11,0) CONSTRAINT RBEP_NPLS_HTO_CODCAMBIO NOT NULL,
	LOG VARCHAR(50) CONSTRAINT RBEP_NPLS_HTO_LOG NOT NULL,
	FECHALOG TIMESTAMP DEFAULT CURRENT_TIMESTAMP CONSTRAINT RBEP_NPLS_HTO_FECHALOG NOT NULL,
	CODNUM NUMBER(11,0) CONSTRAINT RBEP_NPLS_HTO_CODNUM NOT NULL,
	NOMBRE VARCHAR2(150) CONSTRAINT RBEP_NPLS_HTO_NOMBRE NOT NULL,
	TITULO VARCHAR2(500) CONSTRAINT RBEP_NPLS_HTO_TITULO NOT NULL,
	CUERPO CLOB CONSTRAINT RBEP_NPLS_HTO_DESCRIPCION NOT NULL,
	UID_USUARIO VARCHAR2(100) CONSTRAINT RBEP_NPLS_HTO_UID_USUARIO NOT NULL,
	CONSTRAINT IBEP_PPLS_HISTORICO PRIMARY KEY (CODCAMBIO)
);
--/////////////////////
CREATE SEQUENCE QBEP_PLS START WITH 1;
--/////////////////////
CREATE SEQUENCE QBEP_HTO_PLS START WITH 1;
--/////////////////////
CREATE TRIGGER DBEP_PLS_BRI
BEFORE INSERT
ON TBEP_PLANTILLAS
FOR EACH ROW
DECLARE
BEGIN
	SELECT QBEP_PLS.nextval into :new.CODNUM FROM dual;

	INSERT INTO TBEP_HTO_PLANTILLAS (CODCAMBIO,LOG,CODNUM,NOMBRE,TITULO,CUERPO,UID_USUARIO)
	VALUES (QBEP_HTO_PLS.NEXTVAL,'AFTER_INSERT',:New.CODNUM,:New.NOMBRE,:New.TITULO,:New.CUERPO,:New.UID_USUARIO);
END DBEP_PLS_BRI;
--/////////////////////
CREATE TRIGGER DBEP_PLS_BRU
BEFORE UPDATE
ON TBEP_PLANTILLAS 
FOR EACH ROW
DECLARE
BEGIN
	INSERT INTO TBEP_HTO_PLANTILLAS (CODCAMBIO,LOG,CODNUM,NOMBRE,TITULO,CUERPO,UID_USUARIO)
	VALUES (QBEP_HTO_PLS.NEXTVAL,'BEFORE_UPDATE',:Old.CODNUM,:Old.NOMBRE,:Old.TITULO,:Old.CUERPO,:Old.UID_USUARIO);
	
	INSERT INTO TBEP_HTO_PLANTILLAS (CODCAMBIO,LOG,CODNUM,NOMBRE,TITULO,CUERPO,UID_USUARIO)
	VALUES (QBEP_HTO_PLS.NEXTVAL,'AFTER_UPDATE',:New.CODNUM,:New.NOMBRE,:New.TITULO,:New.CUERPO,:New.UID_USUARIO);
END DBEP_PLS_BRU;
--/////////////////////
CREATE TRIGGER DBEP_PLS_BRD
BEFORE DELETE
ON TBEP_PLANTILLAS 
FOR EACH ROW
DECLARE
BEGIN
	INSERT INTO TBEP_HTO_PLANTILLAS (CODCAMBIO,LOG,CODNUM,NOMBRE,TITULO,CUERPO,UID_USUARIO)
	VALUES (QBEP_HTO_PLS.NEXTVAL,'BEFORE_DELETE',:Old.CODNUM,:Old.NOMBRE,:Old.TITULO,:Old.CUERPO,:Old.UID_USUARIO);
END DBEP_PLS_BRD;