CREATE TABLE TBEP_ESTADO_CANDIDATOS (
	CODNUM NUMBER(11,0) CONSTRAINT RBEP_NESC_CODNUM NOT NULL,
	BEPUSU_CODNUM NUMBER(11,0) CONSTRAINT RBEP_NESC_BEPUSU_CODNUM NOT NULL,
	BEPPLO_CODNUM NUMBER(11,0) NULL,
	ESTADO VARCHAR2(26 BYTE) DEFAULT 'DISPONIBLE',
	UID_USUARIO VARCHAR2(100) CONSTRAINT RBEP_NESC_UIDUSUARIO NOT NULL,
	CONSTRAINT IBEP_PESC PRIMARY KEY (CODNUM),
	CONSTRAINT IBEP_FESC_PLO FOREIGN KEY (BEPPLO_CODNUM) REFERENCES TBEP_PLAZAS_OFERTADAS (CODNUM),
	CONSTRAINT RBEP_CESC_ESTADO CHECK(ESTADO IN ('DISPONIBLE','CONTRATADO', 'CONTRATADO 1º CUATRIMESTRE', 'CONTRATADO PARCIAL', 'SUSPENSION PROVISIONAL', 'NO DISPONIBLE'))
);
--/////////////////////
COMMENT ON COLUMN TBEP_ESTADO_CANDIDATOS.BEPPLO_CODNUM IS 'Clave foránea a tabla plazas ofertadas';
--/////////////////////
COMMENT ON COLUMN TBEP_ESTADO_CANDIDATOS.BEPUSU_CODNUM IS 'Clave foránea a tabla usuarios';
--/////////////////////
COMMENT ON COLUMN TBEP_ESTADO_CANDIDATOS.ESTADO IS 'Muestra el estado del candidato';
--/////////////////////
COMMENT ON TABLE TBEP_ESTADO_CANDIDATOS IS 'Estado candidatos. ALIAS: [bepesc] ACRONIMO: [ESC]';
--/////////////////////
CREATE TABLE TBEP_HTO_ESTADO_CANDIDATOS (
	CODCAMBIO NUMBER(11,0) CONSTRAINT RBEP_NESC_HTO_CODCAMBIO NOT NULL,
	LOG VARCHAR(50) CONSTRAINT RBEP_NESC_HTO_LOG NOT NULL,
	FECHALOG TIMESTAMP DEFAULT CURRENT_TIMESTAMP CONSTRAINT RBEP_NESC_HTO_FECHALOG NOT NULL,
	CODNUM NUMBER(11,0) CONSTRAINT RBEP_NESC_HTO_CODNUM NOT NULL,
	BEPUSU_CODNUM NUMBER(11,0) CONSTRAINT RBEP_NESC_HTO_BEPUSU_CODNUM NOT NULL,
	BEPPLO_CODNUM NUMBER(11,0) NULL,
	ESTADO VARCHAR2(26 BYTE) DEFAULT 'DISPONIBLE',
	UID_USUARIO VARCHAR2(100) CONSTRAINT RBEP_NESC_HTO_UIDUSUARIO NOT NULL,
	CONSTRAINT IBEP_PESC_HISTORICO PRIMARY KEY (CODCAMBIO)
);
--/////////////////////
CREATE SEQUENCE QBEP_ESC START WITH 1;
--/////////////////////
CREATE SEQUENCE QBEP_HTO_ESC START WITH 1;
--/////////////////////
CREATE TRIGGER DBEP_ESC_BRI
BEFORE INSERT
ON TBEP_ESTADO_CANDIDATOS
FOR EACH ROW
DECLARE
BEGIN
	SELECT QBEP_ESC.nextval into :new.CODNUM FROM dual;
	
	INSERT INTO TBEP_HTO_ESTADO_CANDIDATOS (CODCAMBIO,LOG,CODNUM,BEPUSU_CODNUM,BEPPLO_CODNUM,ESTADO,UID_USUARIO)
	VALUES (QBEP_HTO_ESC.NEXTVAL,'AFTER_INSERT',:New.CODNUM,:New.BEPUSU_CODNUM,:New.BEPPLO_CODNUM,:New.ESTADO,:New.UID_USUARIO);
END DBEP_ESC_BRI;
--/////////////////////
CREATE TRIGGER DBEP_ESC_BRU
BEFORE UPDATE
ON TBEP_ESTADO_CANDIDATOS
FOR EACH ROW
DECLARE
BEGIN
	INSERT INTO TBEP_HTO_ESTADO_CANDIDATOS (CODCAMBIO,LOG,CODNUM,BEPUSU_CODNUM,BEPPLO_CODNUM,ESTADO,UID_USUARIO)
	VALUES (QBEP_HTO_ESC.NEXTVAL,'BEFORE_UPDATE',:Old.CODNUM,:Old.BEPUSU_CODNUM,:Old.BEPPLO_CODNUM,:Old.ESTADO,:Old.UID_USUARIO);
	
	INSERT INTO TBEP_HTO_ESTADO_CANDIDATOS (CODCAMBIO,LOG,CODNUM,BEPUSU_CODNUM,BEPPLO_CODNUM,ESTADO,UID_USUARIO)
	VALUES (QBEP_HTO_ESC.NEXTVAL,'AFTER_UPDATE',:New.CODNUM,:New.BEPUSU_CODNUM,:New.BEPPLO_CODNUM,:New.ESTADO,:New.UID_USUARIO);
END DBEP_ESC_BRU;
--/////////////////////
CREATE TRIGGER DBEP_ESC_BRD
BEFORE DELETE
ON TBEP_ESTADO_CANDIDATOS
FOR EACH ROW
DECLARE
BEGIN
	INSERT INTO TBEP_HTO_ESTADO_CANDIDATOS (CODCAMBIO,LOG,CODNUM,BEPUSU_CODNUM,BEPPLO_CODNUM,ESTADO,UID_USUARIO)
	VALUES (QBEP_HTO_ESC.NEXTVAL,'BEFORE_DELETE',:Old.CODNUM,:Old.BEPUSU_CODNUM,:Old.BEPPLO_CODNUM,:Old.ESTADO,:Old.UID_USUARIO);
END DBEP_ESC_BRD;