ALTER TABLE TBEP_MEN_DESTINATARIOS MODIFY (BEPUSU_CODNUM NULL);
--/////////////////////
ALTER TABLE TBEP_HTO_MEN_DESTINATARIOS MODIFY (BEPUSU_CODNUM NULL);
--/////////////////////
ALTER TABLE TBEP_MEN_DESTINATARIOS ADD EMAIL VARCHAR2(100) DEFAULT NULL;
--/////////////////////
COMMENT ON COLUMN TBEP_MEN_DESTINATARIOS.EMAIL IS 'Email del destinatario para usuarios fuera de la plataforma';
--/////////////////////
ALTER TABLE TBEP_HTO_MEN_DESTINATARIOS ADD EMAIL VARCHAR2(100) DEFAULT NULL;
--/////////////////////
CREATE OR REPLACE TRIGGER DBEP_MDE_BRI
BEFORE INSERT
ON TBEP_MEN_DESTINATARIOS
FOR EACH ROW
DECLARE
BEGIN
	SELECT QBEP_MDE.nextval into :new.CODNUM FROM dual;

	INSERT INTO TBEP_HTO_MEN_DESTINATARIOS (CODCAMBIO,LOG,CODNUM,BEPMEN_CODNUM,BEPUSU_CODNUM,ESTADO,EMAIL,UID_USUARIO)
	VALUES (QBEP_HTO_MDE.NEXTVAL,'AFTER_INSERT',:New.CODNUM,:New.BEPMEN_CODNUM,:New.BEPUSU_CODNUM,:New.ESTADO,:New.EMAIL,:New.UID_USUARIO);
END DBEP_MDE_BRI;
--/////////////////////
CREATE OR REPLACE TRIGGER DBEP_MDE_BRU
BEFORE UPDATE
ON TBEP_MEN_DESTINATARIOS 
FOR EACH ROW
DECLARE
BEGIN
	INSERT INTO TBEP_HTO_MEN_DESTINATARIOS (CODCAMBIO,LOG,CODNUM,BEPMEN_CODNUM,BEPUSU_CODNUM,ESTADO,EMAIL,UID_USUARIO)
	VALUES (QBEP_HTO_MDE.NEXTVAL,'BEFORE_UPDATE',:Old.CODNUM,:Old.BEPMEN_CODNUM,:Old.BEPUSU_CODNUM,:Old.ESTADO,:Old.EMAIL,:Old.UID_USUARIO);
	
	INSERT INTO TBEP_HTO_MEN_DESTINATARIOS (CODCAMBIO,LOG,CODNUM,BEPMEN_CODNUM,BEPUSU_CODNUM,ESTADO,EMAIL,UID_USUARIO)
	VALUES (QBEP_HTO_MDE.NEXTVAL,'AFTER_UPDATE',:New.CODNUM,:New.BEPMEN_CODNUM,:New.BEPUSU_CODNUM,:New.ESTADO,:New.EMAIL,:New.UID_USUARIO);
END DBEP_MDE_BRU;
--/////////////////////
CREATE OR REPLACE TRIGGER DBEP_MDE_BRD
BEFORE DELETE
ON TBEP_MEN_DESTINATARIOS 
FOR EACH ROW
DECLARE
BEGIN
	INSERT INTO TBEP_HTO_MEN_DESTINATARIOS (CODCAMBIO,LOG,CODNUM,BEPMEN_CODNUM,BEPUSU_CODNUM,ESTADO,EMAIL,UID_USUARIO)
	VALUES (QBEP_HTO_MDE.NEXTVAL,'BEFORE_DELETE',:Old.CODNUM,:Old.BEPMEN_CODNUM,:Old.BEPUSU_CODNUM,:Old.ESTADO,:Old.EMAIL,:Old.UID_USUARIO);
END DBEP_MDE_BRD;