ALTER TABLE TBEP_MENSAJES ADD ADJUNTO BLOB NULL;
--/////////////////////
COMMENT ON COLUMN TBEP_MENSAJES.ADJUNTO IS 'Archivo adjunto para el email';
--/////////////////////
ALTER TABLE TBEP_HTO_MENSAJES ADD ADJUNTO BLOB NULL;
--/////////////////////
CREATE OR REPLACE TRIGGER DBEP_MEN_BRI
BEFORE INSERT
ON TBEP_MENSAJES
FOR EACH ROW
DECLARE
BEGIN
	SELECT QBEP_MEN.nextval into :new.CODNUM FROM dual;
	
	INSERT INTO TBEP_HTO_MENSAJES (CODCAMBIO,LOG,CODNUM,TITULO,CUERPO,FECHA_CREACION,ESTADO,UID_USUARIO,FECHA_ENVIO,ADJUNTO)
	VALUES (QBEP_HTO_MEN.NEXTVAL,'AFTER_INSERT',:New.CODNUM,:New.TITULO,:New.CUERPO,:New.FECHA_CREACION,:New.ESTADO,:New.UID_USUARIO,:New.FECHA_ENVIO,:New.ADJUNTO);
END DBEP_MEN_BRI;
--/////////////////////
CREATE OR REPLACE TRIGGER DBEP_MEN_BRU
BEFORE UPDATE
ON TBEP_MENSAJES 
FOR EACH ROW
DECLARE
BEGIN
	INSERT INTO TBEP_HTO_MENSAJES (CODCAMBIO,LOG,CODNUM,TITULO,CUERPO,FECHA_CREACION,ESTADO,UID_USUARIO,FECHA_ENVIO,ADJUNTO)
	VALUES (QBEP_HTO_MEN.NEXTVAL,'BEFORE_UPDATE',:Old.CODNUM,:Old.TITULO,:Old.CUERPO,:Old.FECHA_CREACION,:Old.ESTADO,:Old.UID_USUARIO,:Old.FECHA_ENVIO,:Old.ADJUNTO);
	
	INSERT INTO TBEP_HTO_MENSAJES (CODCAMBIO,LOG,CODNUM,TITULO,CUERPO,FECHA_CREACION,ESTADO,UID_USUARIO,FECHA_ENVIO,ADJUNTO)
	VALUES (QBEP_HTO_MEN.NEXTVAL,'AFTER_UPDATE',:New.CODNUM,:New.TITULO,:New.CUERPO,:New.FECHA_CREACION,:New.ESTADO,:New.UID_USUARIO,:New.FECHA_ENVIO,:New.ADJUNTO);
END DBEP_MEN_BRU;
--/////////////////////
CREATE OR REPLACE TRIGGER DBEP_MEN_BRD
BEFORE DELETE
ON TBEP_MENSAJES 
FOR EACH ROW
DECLARE
BEGIN
	INSERT INTO TBEP_HTO_MENSAJES (CODCAMBIO,LOG,CODNUM,TITULO,CUERPO,FECHA_CREACION,ESTADO,UID_USUARIO,FECHA_ENVIO,ADJUNTO)
	VALUES (QBEP_HTO_MEN.NEXTVAL,'BEFORE_DELETE',:Old.CODNUM,:Old.TITULO,:Old.CUERPO,:Old.FECHA_CREACION,:Old.ESTADO,:Old.UID_USUARIO,:Old.FECHA_ENVIO,:Old.ADJUNTO);
END DBEP_MEN_BRD;