ALTER TABLE TBEP_PLAZAS_OFERTADAS ADD ID_PLAZA VARCHAR2(50 CHAR) NULL;
--/////////////////////
COMMENT ON COLUMN TBEP_PLAZAS_OFERTADAS.ID_PLAZA IS 'Código de la plaza';
--/////////////////////
ALTER TABLE TBEP_HTO_PLAZAS_OFERTADAS ADD ID_PLAZA VARCHAR2(50 CHAR) NULL;
--/////////////////////
ALTER TABLE TBEP_PLAZAS_OFERTADAS ADD FLGACTIVA CHAR(1) DEFAULT 'S';
--/////////////////////
COMMENT ON COLUMN TBEP_PLAZAS_OFERTADAS.FLGACTIVA IS 'Indica si la plaza está borrada o no';
--/////////////////////
ALTER TABLE TBEP_HTO_PLAZAS_OFERTADAS ADD FLGACTIVA CHAR(1) DEFAULT 'S';
--/////////////////////
ALTER TABLE TBEP_PLAZAS_OFERTADAS MODIFY CENTRO_DESTINO VARCHAR2(15 BYTE);
--/////////////////////
ALTER TABLE TBEP_PLAZAS_OFERTADAS DROP CONSTRAINT RBEP_CPLO_CENTRO_DESTINO;
--/////////////////////
ALTER TABLE TBEP_PLAZAS_OFERTADAS ADD CONSTRAINT RBEP_CPLO_CENTRO_DESTINO CHECK(CENTRO_DESTINO IN ('JAEN','LINARES','JAEN/LINARES'));
--/////////////////////
ALTER TABLE TBEP_HTO_PLAZAS_OFERTADAS MODIFY CENTRO_DESTINO VARCHAR2(15 BYTE);
--/////////////////////
CREATE OR REPLACE TRIGGER DBEP_PLO_BRI
BEFORE INSERT
ON TBEP_PLAZAS_OFERTADAS
FOR EACH ROW
DECLARE
BEGIN
	SELECT QBEP_PLO.nextval into :new.CODNUM FROM dual;
	
	INSERT INTO TBEP_HTO_PLAZAS_OFERTADAS (CODCAMBIO,LOG,CODNUM,BEPARE_CODNUM,BEPDED_CODNUM,JUSTIFICACION,DURACION_PREVISTA,CUATRIMESTRE,CENTRO_DESTINO,FECHA_CREACION,FECHA_ABIERTA,FECHA_FIN_OFERTA,FECHA_CERRADA,HORARIO,NRI,NRI_FECHA,ESTADO,OBSERVACIONES_INTERNAS,ID_PLAZA,FLGACTIVA,UID_USUARIO)
	VALUES (QBEP_HTO_PLO.NEXTVAL,'AFTER_INSERT',:New.CODNUM,:New.BEPARE_CODNUM,:New.BEPDED_CODNUM,:New.JUSTIFICACION,:New.DURACION_PREVISTA,:New.CUATRIMESTRE,:New.CENTRO_DESTINO,:New.FECHA_CREACION,:New.FECHA_ABIERTA,:New.FECHA_FIN_OFERTA,:New.FECHA_CERRADA,:New.HORARIO,:New.NRI,:New.NRI_FECHA,:New.ESTADO,:New.OBSERVACIONES_INTERNAS,:New.ID_PLAZA,:New.FLGACTIVA,:New.UID_USUARIO);
END DBEP_PLO_BRI;
--/////////////////////
CREATE OR REPLACE TRIGGER DBEP_PLO_BRU
BEFORE UPDATE
ON TBEP_PLAZAS_OFERTADAS
FOR EACH ROW
DECLARE
BEGIN
	INSERT INTO TBEP_HTO_PLAZAS_OFERTADAS (CODCAMBIO,LOG,CODNUM,BEPARE_CODNUM,BEPDED_CODNUM,JUSTIFICACION,DURACION_PREVISTA,CUATRIMESTRE,CENTRO_DESTINO,FECHA_CREACION,FECHA_ABIERTA,FECHA_FIN_OFERTA,FECHA_CERRADA,HORARIO,NRI,NRI_FECHA,ESTADO,OBSERVACIONES_INTERNAS,ID_PLAZA,FLGACTIVA,UID_USUARIO)
	VALUES (QBEP_HTO_PLO.NEXTVAL,'BEFORE_UPDATE',:Old.CODNUM,:Old.BEPARE_CODNUM,:Old.BEPDED_CODNUM,:Old.JUSTIFICACION,:Old.DURACION_PREVISTA,:Old.CUATRIMESTRE,:Old.CENTRO_DESTINO,:Old.FECHA_CREACION,:Old.FECHA_ABIERTA,:Old.FECHA_FIN_OFERTA,:Old.FECHA_CERRADA,:Old.HORARIO,:Old.NRI,:Old.NRI_FECHA,:Old.ESTADO,:Old.OBSERVACIONES_INTERNAS,:Old.ID_PLAZA,:Old.FLGACTIVA,:Old.UID_USUARIO);
	
	INSERT INTO TBEP_HTO_PLAZAS_OFERTADAS (CODCAMBIO,LOG,CODNUM,BEPARE_CODNUM,BEPDED_CODNUM,JUSTIFICACION,DURACION_PREVISTA,CUATRIMESTRE,CENTRO_DESTINO,FECHA_CREACION,FECHA_ABIERTA,FECHA_FIN_OFERTA,FECHA_CERRADA,HORARIO,NRI,NRI_FECHA,ESTADO,OBSERVACIONES_INTERNAS,ID_PLAZA,FLGACTIVA,UID_USUARIO)
	VALUES (QBEP_HTO_PLO.NEXTVAL,'AFTER_UPDATE',:New.CODNUM,:New.BEPARE_CODNUM,:New.BEPDED_CODNUM,:New.JUSTIFICACION,:New.DURACION_PREVISTA,:New.CUATRIMESTRE,:New.CENTRO_DESTINO,:New.FECHA_CREACION,:New.FECHA_ABIERTA,:New.FECHA_FIN_OFERTA,:New.FECHA_CERRADA,:New.HORARIO,:New.NRI,:New.NRI_FECHA,:New.ESTADO,:New.OBSERVACIONES_INTERNAS,:New.ID_PLAZA,:New.FLGACTIVA,:New.UID_USUARIO);
END DBEP_PLO_BRU;
--/////////////////////
CREATE OR REPLACE TRIGGER DBEP_PLO_BRD
BEFORE DELETE
ON TBEP_PLAZAS_OFERTADAS
FOR EACH ROW
DECLARE
BEGIN
	INSERT INTO TBEP_HTO_PLAZAS_OFERTADAS (CODCAMBIO,LOG,CODNUM,BEPARE_CODNUM,BEPDED_CODNUM,JUSTIFICACION,DURACION_PREVISTA,CUATRIMESTRE,CENTRO_DESTINO,FECHA_CREACION,FECHA_ABIERTA,FECHA_FIN_OFERTA,FECHA_CERRADA,HORARIO,NRI,NRI_FECHA,ESTADO,OBSERVACIONES_INTERNAS,ID_PLAZA,FLGACTIVA,UID_USUARIO)
	VALUES (QBEP_HTO_PLO.NEXTVAL,'BEFORE_DELETE',:Old.CODNUM,:Old.BEPARE_CODNUM,:Old.BEPDED_CODNUM,:Old.JUSTIFICACION,:Old.DURACION_PREVISTA,:Old.CUATRIMESTRE,:Old.CENTRO_DESTINO,:Old.FECHA_CREACION,:Old.FECHA_ABIERTA,:Old.FECHA_FIN_OFERTA,:Old.FECHA_CERRADA,:Old.HORARIO,:Old.NRI,:Old.NRI_FECHA,:Old.ESTADO,:Old.OBSERVACIONES_INTERNAS,:Old.ID_PLAZA,:Old.FLGACTIVA,:Old.UID_USUARIO);
END DBEP_PLO_BRD;