ALTER TABLE TBEP_DEDICACIONES ADD TIPO VARCHAR2(15 BYTE) DEFAULT 'TIEMPO COMPLETO';
--/////////////////////
ALTER TABLE TBEP_DEDICACIONES ADD CONSTRAINT RBEP_CDED_TIPO CHECK(TIPO IN ('TIEMPO COMPLETO','TIEMPO PARCIAL'));
--/////////////////////
COMMENT ON COLUMN TBEP_DEDICACIONES.TIPO IS 'Tipo de dedicación si es a tiempo completo o parcial';
--/////////////////////
ALTER TABLE TBEP_HTO_DEDICACIONES ADD TIPO VARCHAR2(15 BYTE) NULL;
--/////////////////////
CREATE OR REPLACE TRIGGER DBEP_DED_BRI
BEFORE INSERT
ON TBEP_DEDICACIONES
FOR EACH ROW
DECLARE
BEGIN
	SELECT QBEP_DED.nextval into :new.CODNUM FROM dual;
	
	INSERT INTO TBEP_HTO_DEDICACIONES (CODCAMBIO,LOG,CODNUM,TEXTO,SUELDO,FECHA_VIGENCIA,FLGACTIVA,TIPO,UID_USUARIO)
	VALUES (QBEP_HTO_DED.NEXTVAL,'AFTER_INSERT',:New.CODNUM,:New.TEXTO,:New.SUELDO,:New.FECHA_VIGENCIA,:New.FLGACTIVA,:New.TIPO,:New.UID_USUARIO);
END DBEP_DED_BRI;
--/////////////////////
CREATE OR REPLACE TRIGGER DBEP_DED_BRU
BEFORE UPDATE
ON TBEP_DEDICACIONES
FOR EACH ROW
DECLARE
BEGIN
	INSERT INTO TBEP_HTO_DEDICACIONES (CODCAMBIO,LOG,CODNUM,TEXTO,SUELDO,FECHA_VIGENCIA,FLGACTIVA,TIPO,UID_USUARIO)
	VALUES (QBEP_HTO_DED.NEXTVAL,'BEFORE_UPDATE',:Old.CODNUM,:Old.TEXTO,:Old.SUELDO,:Old.FECHA_VIGENCIA,:Old.FLGACTIVA,:Old.TIPO,:Old.UID_USUARIO);
	
	INSERT INTO TBEP_HTO_DEDICACIONES (CODCAMBIO,LOG,CODNUM,TEXTO,SUELDO,FECHA_VIGENCIA,FLGACTIVA,TIPO,UID_USUARIO)
	VALUES (QBEP_HTO_DED.NEXTVAL,'AFTER_UPDATE',:New.CODNUM,:New.TEXTO,:New.SUELDO,:New.FECHA_VIGENCIA,:New.FLGACTIVA,:New.TIPO,:New.UID_USUARIO);
END DBEP_DED_BRU;
--/////////////////////
CREATE OR REPLACE TRIGGER DBEP_DED_BRD
BEFORE DELETE
ON TBEP_DEDICACIONES
FOR EACH ROW
DECLARE
BEGIN
	INSERT INTO TBEP_HTO_DEDICACIONES (CODCAMBIO,LOG,CODNUM,TEXTO,SUELDO,FECHA_VIGENCIA,FLGACTIVA,TIPO,UID_USUARIO)
	VALUES (QBEP_HTO_DED.NEXTVAL,'BEFORE_DELETE',:Old.CODNUM,:Old.TEXTO,:Old.SUELDO,:Old.FECHA_VIGENCIA,:Old.FLGACTIVA,:Old.TIPO,:Old.UID_USUARIO);
END DBEP_DED_BRD;