ALTER TABLE TBEP_PLAZAS_OFERTADAS ADD CURSO VARCHAR2(50 CHAR) DEFAULT TO_CHAR(SYSDATE, 'YY') || '/' || TO_CHAR(add_months(SYSDATE, 12), 'YY');
--/////////////////////
COMMENT ON COLUMN TBEP_PLAZAS_OFERTADAS.CURSO IS 'Curso académico de la plaza';
--/////////////////////
ALTER TABLE TBEP_HTO_PLAZAS_OFERTADAS ADD CURSO VARCHAR2(50 CHAR) DEFAULT TO_CHAR(SYSDATE, 'YY') || '/' || TO_CHAR(add_months(SYSDATE, 12), 'YY');
--/////////////////////
CREATE OR REPLACE TRIGGER DBEP_PLO_BRI
BEFORE INSERT
ON TBEP_PLAZAS_OFERTADAS
FOR EACH ROW
DECLARE
BEGIN
	SELECT QBEP_PLO.nextval into :new.CODNUM FROM dual;
	
	INSERT INTO TBEP_HTO_PLAZAS_OFERTADAS (CODCAMBIO,LOG,CODNUM,BEPARE_CODNUM,BEPDED_CODNUM,JUSTIFICACION,DURACION_PREVISTA,CUATRIMESTRE,CENTRO_DESTINO,FECHA_CREACION,FECHA_ABIERTA,FECHA_FIN_OFERTA,FECHA_CERRADA,HORARIO,NRI,NRI_FECHA,ESTADO,OBSERVACIONES_INTERNAS,ID_PLAZA,FLGACTIVA,CURSO,UID_USUARIO)
	VALUES (QBEP_HTO_PLO.NEXTVAL,'AFTER_INSERT',:New.CODNUM,:New.BEPARE_CODNUM,:New.BEPDED_CODNUM,:New.JUSTIFICACION,:New.DURACION_PREVISTA,:New.CUATRIMESTRE,:New.CENTRO_DESTINO,:New.FECHA_CREACION,:New.FECHA_ABIERTA,:New.FECHA_FIN_OFERTA,:New.FECHA_CERRADA,:New.HORARIO,:New.NRI,:New.NRI_FECHA,:New.ESTADO,:New.OBSERVACIONES_INTERNAS,:New.ID_PLAZA,:New.FLGACTIVA,:New.CURSO,:New.UID_USUARIO);
END DBEP_PLO_BRI;
--/////////////////////
CREATE OR REPLACE TRIGGER DBEP_PLO_BRU
BEFORE UPDATE
ON TBEP_PLAZAS_OFERTADAS
FOR EACH ROW
DECLARE
BEGIN
	INSERT INTO TBEP_HTO_PLAZAS_OFERTADAS (CODCAMBIO,LOG,CODNUM,BEPARE_CODNUM,BEPDED_CODNUM,JUSTIFICACION,DURACION_PREVISTA,CUATRIMESTRE,CENTRO_DESTINO,FECHA_CREACION,FECHA_ABIERTA,FECHA_FIN_OFERTA,FECHA_CERRADA,HORARIO,NRI,NRI_FECHA,ESTADO,OBSERVACIONES_INTERNAS,ID_PLAZA,FLGACTIVA,CURSO,UID_USUARIO)
	VALUES (QBEP_HTO_PLO.NEXTVAL,'BEFORE_UPDATE',:Old.CODNUM,:Old.BEPARE_CODNUM,:Old.BEPDED_CODNUM,:Old.JUSTIFICACION,:Old.DURACION_PREVISTA,:Old.CUATRIMESTRE,:Old.CENTRO_DESTINO,:Old.FECHA_CREACION,:Old.FECHA_ABIERTA,:Old.FECHA_FIN_OFERTA,:Old.FECHA_CERRADA,:Old.HORARIO,:Old.NRI,:Old.NRI_FECHA,:Old.ESTADO,:Old.OBSERVACIONES_INTERNAS,:Old.ID_PLAZA,:Old.FLGACTIVA,:Old.CURSO,:Old.UID_USUARIO);
	
	INSERT INTO TBEP_HTO_PLAZAS_OFERTADAS (CODCAMBIO,LOG,CODNUM,BEPARE_CODNUM,BEPDED_CODNUM,JUSTIFICACION,DURACION_PREVISTA,CUATRIMESTRE,CENTRO_DESTINO,FECHA_CREACION,FECHA_ABIERTA,FECHA_FIN_OFERTA,FECHA_CERRADA,HORARIO,NRI,NRI_FECHA,ESTADO,OBSERVACIONES_INTERNAS,ID_PLAZA,FLGACTIVA,CURSO,UID_USUARIO)
	VALUES (QBEP_HTO_PLO.NEXTVAL,'AFTER_UPDATE',:New.CODNUM,:New.BEPARE_CODNUM,:New.BEPDED_CODNUM,:New.JUSTIFICACION,:New.DURACION_PREVISTA,:New.CUATRIMESTRE,:New.CENTRO_DESTINO,:New.FECHA_CREACION,:New.FECHA_ABIERTA,:New.FECHA_FIN_OFERTA,:New.FECHA_CERRADA,:New.HORARIO,:New.NRI,:New.NRI_FECHA,:New.ESTADO,:New.OBSERVACIONES_INTERNAS,:New.ID_PLAZA,:New.FLGACTIVA,:New.CURSO,:New.UID_USUARIO);
END DBEP_PLO_BRU;
--/////////////////////
CREATE OR REPLACE TRIGGER DBEP_PLO_BRD
BEFORE DELETE
ON TBEP_PLAZAS_OFERTADAS
FOR EACH ROW
DECLARE
BEGIN
	INSERT INTO TBEP_HTO_PLAZAS_OFERTADAS (CODCAMBIO,LOG,CODNUM,BEPARE_CODNUM,BEPDED_CODNUM,JUSTIFICACION,DURACION_PREVISTA,CUATRIMESTRE,CENTRO_DESTINO,FECHA_CREACION,FECHA_ABIERTA,FECHA_FIN_OFERTA,FECHA_CERRADA,HORARIO,NRI,NRI_FECHA,ESTADO,OBSERVACIONES_INTERNAS,ID_PLAZA,FLGACTIVA,CURSO,UID_USUARIO)
	VALUES (QBEP_HTO_PLO.NEXTVAL,'BEFORE_DELETE',:Old.CODNUM,:Old.BEPARE_CODNUM,:Old.BEPDED_CODNUM,:Old.JUSTIFICACION,:Old.DURACION_PREVISTA,:Old.CUATRIMESTRE,:Old.CENTRO_DESTINO,:Old.FECHA_CREACION,:Old.FECHA_ABIERTA,:Old.FECHA_FIN_OFERTA,:Old.FECHA_CERRADA,:Old.HORARIO,:Old.NRI,:Old.NRI_FECHA,:Old.ESTADO,:Old.OBSERVACIONES_INTERNAS,:Old.ID_PLAZA,:Old.FLGACTIVA,:Old.CURSO,:Old.UID_USUARIO);
END DBEP_PLO_BRD;