ALTER TABLE TBEP_PLAZAS_OFERTADAS DROP CONSTRAINT RBEP_CPLO_ESTADO;
--/////////////////////
UPDATE TBEP_PLAZAS_OFERTADAS SET ESTADO = 'APROBACION' WHERE ESTADO = 'TRAMITACION';
--/////////////////////
ALTER TABLE TBEP_PLAZAS_OFERTADAS ADD CONSTRAINT RBEP_CPLO_ESTADO CHECK(ESTADO IN ('CREACION','APROBACION', 'ABIERTA', 'CONTRATACION', 'CERRADA'));