ALTER TABLE TBEP_CONVOCATORIAS ADD FECHA_FINALIZACION TIMESTAMP;
--/////////////////////
ALTER TABLE TBEP_CONVOCATORIAS MODIFY ESTADO VARCHAR2(10 BYTE);
--/////////////////////
ALTER TABLE TBEP_HTO_CONVOCATORIAS MODIFY ESTADO VARCHAR2(10 BYTE);
--/////////////////////
COMMENT ON COLUMN TBEP_CONVOCATORIAS.FECHA_FINALIZACION IS 'Fecha de finalización de la convocatoria';
--/////////////////////
ALTER TABLE TBEP_HTO_CONVOCATORIAS ADD FECHA_FINALIZACION TIMESTAMP;
--/////////////////////
ALTER TABLE TBEP_CONVOCATORIAS DROP CONSTRAINT RBEP_CCON_ESTADO;
--/////////////////////
ALTER TABLE TBEP_CONVOCATORIAS ADD CONSTRAINT RBEP_CCON_ESTADO CHECK(ESTADO IN ('ABIERTA','CERRADA','FINALIZADA'));
--/////////////////////
CREATE OR REPLACE TRIGGER DBEP_CON_BRI
BEFORE INSERT
ON TBEP_CONVOCATORIAS
FOR EACH ROW
DECLARE
BEGIN
	SELECT QBEP_CON.nextval into :new.CODNUM FROM dual;
	
	INSERT INTO TBEP_HTO_CONVOCATORIAS (CODCAMBIO,LOG,CODNUM,DESCRIPCION,FECHACIERRE,ESTADO,NUMBOLSASMAXIMO,NUMMERITOSPORBLOQUE,FECHA_FINALIZACION,UID_USUARIO)
	VALUES (QBEP_HTO_CON.NEXTVAL,'AFTER_INSERT',:New.CODNUM,:New.DESCRIPCION,:New.FECHACIERRE,:New.ESTADO,:New.NUMBOLSASMAXIMO,:New.NUMMERITOSPORBLOQUE,:New.FECHA_FINALIZACION,:New.UID_USUARIO);
END DBEP_CON_BRI;
--/////////////////////
CREATE OR REPLACE TRIGGER DBEP_CON_BRU
BEFORE UPDATE
ON TBEP_CONVOCATORIAS
FOR EACH ROW
DECLARE
BEGIN
	INSERT INTO TBEP_HTO_CONVOCATORIAS (CODCAMBIO,LOG,CODNUM,DESCRIPCION,FECHACIERRE,ESTADO,NUMBOLSASMAXIMO,NUMMERITOSPORBLOQUE,FECHA_FINALIZACION,UID_USUARIO)
	VALUES (QBEP_HTO_CON.NEXTVAL,'BEFORE_UPDATE',:Old.CODNUM,:Old.DESCRIPCION,:Old.FECHACIERRE,:Old.ESTADO,:Old.NUMBOLSASMAXIMO,:Old.NUMMERITOSPORBLOQUE,:Old.FECHA_FINALIZACION,:Old.UID_USUARIO);
	
	INSERT INTO TBEP_HTO_CONVOCATORIAS (CODCAMBIO,LOG,CODNUM,DESCRIPCION,FECHACIERRE,ESTADO,NUMBOLSASMAXIMO,NUMMERITOSPORBLOQUE,FECHA_FINALIZACION,UID_USUARIO)
	VALUES (QBEP_HTO_CON.NEXTVAL,'AFTER_UPDATE',:New.CODNUM,:New.DESCRIPCION,:New.FECHACIERRE,:New.ESTADO,:New.NUMBOLSASMAXIMO,:New.NUMMERITOSPORBLOQUE,:New.FECHA_FINALIZACION,:New.UID_USUARIO);
END DBEP_CON_BRU;
--/////////////////////
CREATE OR REPLACE TRIGGER DBEP_CON_BRD
BEFORE DELETE
ON TBEP_CONVOCATORIAS
FOR EACH ROW
DECLARE
BEGIN
	INSERT INTO TBEP_HTO_CONVOCATORIAS (CODCAMBIO,LOG,CODNUM,DESCRIPCION,FECHACIERRE,ESTADO,NUMBOLSASMAXIMO,NUMMERITOSPORBLOQUE,FECHA_FINALIZACION,UID_USUARIO)
	VALUES (QBEP_HTO_CON.NEXTVAL,'BEFORE_DELETE',:Old.CODNUM,:Old.DESCRIPCION,:Old.FECHACIERRE,:Old.ESTADO,:Old.NUMBOLSASMAXIMO,:Old.NUMMERITOSPORBLOQUE,:Old.FECHA_FINALIZACION,:Old.UID_USUARIO);
END DBEP_CON_BRD;