INSERT INTO ADM_MENU (MNU_CODNUM, CONTROLADOR, FLG_DISPONIBLE, FLG_MOSTRAR, FLG_CREAMENU, FLG_PDFINTERNO, FLG_EXCEL, FLG_WORD, FLG_ANONIMO, PADRE_CODNUM, FLG_LOG) VALUES (1138, 'informacionadministrativa.bolsaempleo.alegaciones', 'S', 'S', 'S','N', 'N', 'N', 'N', 1100, 'N');
--/////////////////////
INSERT INTO ADM_MENU_DOM (MNU_CODNUM, DOM_CODALF) VALUES (1138, 'ujaen.es');
--/////////////////////
INSERT INTO ADM_MENU_IDM (MNU_CODNUM, IDM_CODALF, DESCRIPCION) VALUES (1138, 'es', 'Alegaciones');
--/////////////////////
INSERT INTO ADM_MENU_SIS (MNU_CODNUM, SIS_CODALF) VALUES (1138, 'uvirtual');
--/////////////////////
INSERT INTO ADM_MENU_RED (MNU_CODNUM, RED, DESCRIPCION, FLG_DESACT) VALUES (1138, '0.0.0.0/0', 'Publico', 'N');
--/////////////////////
INSERT INTO ADM_MENU_ROL (MNU_CODNUM, ROL_CODNUM, FLG_DESACT, FLG_ADMIN) VALUES (1138, 1050, 'N', 'N');
--/////////////////////
INSERT INTO ADM_MENU_ROL (MNU_CODNUM, ROL_CODNUM, FLG_DESACT, FLG_ADMIN) VALUES (1138, 1053, 'N', 'N');