ALTER TABLE TBEP_BOLSAS ADD (
	FECHABAREMACIONFIN TIMESTAMP NULL,
	FECHAHABCONTRATOS TIMESTAMP NULL
);
--/////////////////////
COMMENT ON COLUMN TBEP_BOLSAS.FECHABAREMACIONFIN IS 'Fecha de baremación definitiva';
--/////////////////////
COMMENT ON COLUMN TBEP_BOLSAS.FECHAHABCONTRATOS IS 'Fecha desde la cual se puede iniciar la contratación en la bolsa';
--/////////////////////
ALTER TABLE TBEP_HTO_BOLSAS ADD (
	FECHABAREMACIONFIN TIMESTAMP NULL,
	FECHAHABCONTRATOS TIMESTAMP NULL
);
--/////////////////////
CREATE OR REPLACE TRIGGER DBEP_BOL_BRI
BEFORE INSERT
ON TBEP_BOLSAS
FOR EACH ROW
DECLARE
BEGIN
    SELECT QBEP_BOL.nextval into :new.CODNUM FROM dual;
    
    INSERT INTO TBEP_HTO_BOLSAS (CODCAMBIO,LOG,CODNUM,BEPARE_CODNUM,ESTADO,FLGBAREMABLE,FECHAACTUALIZACION,FECHABLOQUEO,FECHADEBLOQUEO,FLGPENBAREMACION,FECHABAREMACION,FECHABAREMACIONFIN,FECHAHABCONTRATOS,UID_USUARIO)
    VALUES (QBEP_HTO_ARE.NEXTVAL,'AFTER_INSERT',:New.CODNUM,:New.BEPARE_CODNUM,:New.ESTADO,:New.FLGBAREMABLE,:New.FECHAACTUALIZACION,:New.FECHABLOQUEO,:New.FECHADEBLOQUEO,:New.FLGPENBAREMACION,:New.FECHABAREMACION,:New.FECHABAREMACIONFIN,:New.FECHAHABCONTRATOS,:New.UID_USUARIO);
END DBEP_BOL_BRI;
--/////////////////////
CREATE OR REPLACE TRIGGER DBEP_BOL_BRU
BEFORE UPDATE
ON TBEP_BOLSAS
FOR EACH ROW
DECLARE
BEGIN
	INSERT INTO TBEP_HTO_BOLSAS (CODCAMBIO,LOG,CODNUM,BEPARE_CODNUM,ESTADO,FLGBAREMABLE,FECHAACTUALIZACION,FECHABLOQUEO,FECHADEBLOQUEO,FLGPENBAREMACION,FECHABAREMACION,FECHABAREMACIONFIN,FECHAHABCONTRATOS,UID_USUARIO)
    VALUES (QBEP_HTO_ARE.NEXTVAL,'BEFORE_UPDATE',:Old.CODNUM,:Old.BEPARE_CODNUM,:Old.ESTADO,:Old.FLGBAREMABLE,:Old.FECHAACTUALIZACION,:Old.FECHABLOQUEO,:Old.FECHADEBLOQUEO,:Old.FLGPENBAREMACION,:Old.FECHABAREMACION,:Old.FECHABAREMACIONFIN,:Old.FECHAHABCONTRATOS,:Old.UID_USUARIO);
    
    INSERT INTO TBEP_HTO_BOLSAS (CODCAMBIO,LOG,CODNUM,BEPARE_CODNUM,ESTADO,FLGBAREMABLE,FECHAACTUALIZACION,FECHABLOQUEO,FECHADEBLOQUEO,FLGPENBAREMACION,FECHABAREMACION,FECHABAREMACIONFIN,FECHAHABCONTRATOS,UID_USUARIO)
    VALUES (QBEP_HTO_ARE.NEXTVAL,'AFTER_UPDATE',:New.CODNUM,:New.BEPARE_CODNUM,:New.ESTADO,:New.FLGBAREMABLE,:New.FECHAACTUALIZACION,:New.FECHABLOQUEO,:New.FECHADEBLOQUEO,:New.FLGPENBAREMACION,:New.FECHABAREMACION,:New.FECHABAREMACIONFIN,:New.FECHAHABCONTRATOS,:New.UID_USUARIO);
END DBEP_BOL_BRU;
--/////////////////////
CREATE OR REPLACE TRIGGER DBEP_BOL_BRD
BEFORE DELETE
ON TBEP_BOLSAS
FOR EACH ROW
DECLARE
BEGIN
	INSERT INTO TBEP_HTO_BOLSAS (CODCAMBIO,LOG,CODNUM,BEPARE_CODNUM,ESTADO,FLGBAREMABLE,FECHAACTUALIZACION,FECHABLOQUEO,FECHADEBLOQUEO,FLGPENBAREMACION,FECHABAREMACION,FECHABAREMACIONFIN,FECHAHABCONTRATOS,UID_USUARIO)
    VALUES (QBEP_HTO_ARE.NEXTVAL,'BEFORE_DELETE',:Old.CODNUM,:Old.BEPARE_CODNUM,:Old.ESTADO,:Old.FLGBAREMABLE,:Old.FECHAACTUALIZACION,:Old.FECHABLOQUEO,:Old.FECHADEBLOQUEO,:Old.FLGPENBAREMACION,:Old.FECHABAREMACION,:Old.FECHABAREMACIONFIN,:Old.FECHAHABCONTRATOS,:Old.UID_USUARIO);
END DBEP_BOL_BRD;