ALTER TABLE TBEP_MER_PRE_USUARIO ADD (
	FLGACTIVO CHAR(1) DEFAULT 'S',
	CONSTRAINT RBEP_CMPU_FLGACTIVO CHECK(FLGACTIVO IN ('N','S'))
);
--/////////////////////
COMMENT ON COLUMN TBEP_MER_PRE_USUARIO.FLGACTIVO IS 'Indica si está activa o no. Solo una activa por candidato.';
--/////////////////////
ALTER TABLE TBEP_HTO_MER_PRE_USUARIO ADD FLGACTIVO CHAR(1) DEFAULT 'S';
--/////////////////////
CREATE OR REPLACE TRIGGER DBEP_MPU_BRI
BEFORE INSERT
ON TBEP_MER_PRE_USUARIO
FOR EACH ROW
DECLARE
BEGIN
    SELECT QBEP_MPU.nextval into :new.CODNUM FROM dual;

    INSERT INTO TBEP_HTO_MER_PRE_USUARIO (CODCAMBIO,LOG,CODNUM,BEPMEP_CODNUM,BEPUSU_CODNUM,BEPMPO_CODNUM,DESCRIPCION,ARCHIVO,FLGBORRADO,FECHA_BORRADO,FLGVALIDADO,FECHA_VALIDADO,UID_USUARIO,FLGACTIVO)
    VALUES (QBEP_HTO_MPU.NEXTVAL,'AFTER_INSERT',:New.CODNUM,:New.BEPMEP_CODNUM,:New.BEPUSU_CODNUM,:New.BEPMPO_CODNUM,:New.DESCRIPCION,:New.ARCHIVO,:New.FLGBORRADO,:New.FECHA_BORRADO,:New.FLGVALIDADO,:New.FECHA_VALIDADO,:New.UID_USUARIO,:New.FLGACTIVO);
END DBEP_MPU_BRI;
--/////////////////////
CREATE OR REPLACE TRIGGER DBEP_MPU_BRU
BEFORE UPDATE
ON TBEP_MER_PRE_USUARIO
FOR EACH ROW
DECLARE
BEGIN
    INSERT INTO TBEP_HTO_MER_PRE_USUARIO (CODCAMBIO,LOG,CODNUM,BEPMEP_CODNUM,BEPUSU_CODNUM,BEPMPO_CODNUM,DESCRIPCION,ARCHIVO,FLGBORRADO,FECHA_BORRADO,FLGVALIDADO,FECHA_VALIDADO,UID_USUARIO,FLGACTIVO)
    VALUES (QBEP_HTO_MPU.NEXTVAL,'BEFORE_UPDATE',:Old.CODNUM,:Old.BEPMEP_CODNUM,:Old.BEPUSU_CODNUM,:Old.BEPMPO_CODNUM,:Old.DESCRIPCION,:Old.ARCHIVO,:Old.FLGBORRADO,:Old.FECHA_BORRADO,:Old.FLGVALIDADO,:Old.FECHA_VALIDADO,:Old.UID_USUARIO,:Old.FLGACTIVO);

    INSERT INTO TBEP_HTO_MER_PRE_USUARIO (CODCAMBIO,LOG,CODNUM,BEPMEP_CODNUM,BEPUSU_CODNUM,BEPMPO_CODNUM,DESCRIPCION,ARCHIVO,FLGBORRADO,FECHA_BORRADO,FLGVALIDADO,FECHA_VALIDADO,UID_USUARIO,FLGACTIVO)
    VALUES (QBEP_HTO_MPU.NEXTVAL,'AFTER_UPDATE',:New.CODNUM,:New.BEPMEP_CODNUM,:New.BEPUSU_CODNUM,:New.BEPMPO_CODNUM,:New.DESCRIPCION,:New.ARCHIVO,:New.FLGBORRADO,:New.FECHA_BORRADO,:New.FLGVALIDADO,:New.FECHA_VALIDADO,:New.UID_USUARIO,:New.FLGACTIVO);
END DBEP_MPU_BRU;
--/////////////////////
CREATE OR REPLACE TRIGGER DBEP_MPU_BRD
BEFORE DELETE
ON TBEP_MER_PRE_USUARIO
FOR EACH ROW
DECLARE
BEGIN
    INSERT INTO TBEP_HTO_MER_PRE_USUARIO (CODCAMBIO,LOG,CODNUM,BEPMEP_CODNUM,BEPUSU_CODNUM,BEPMPO_CODNUM,DESCRIPCION,ARCHIVO,FLGBORRADO,FECHA_BORRADO,FLGVALIDADO,FECHA_VALIDADO,UID_USUARIO,FLGACTIVO)
    VALUES (QBEP_HTO_MPU.NEXTVAL,'BEFORE_DELETE',:Old.CODNUM,:Old.BEPMEP_CODNUM,:Old.BEPUSU_CODNUM,:Old.BEPMPO_CODNUM,:Old.DESCRIPCION,:Old.ARCHIVO,:Old.FLGBORRADO,:Old.FECHA_BORRADO,:Old.FLGVALIDADO,:Old.FECHA_VALIDADO,:Old.UID_USUARIO,:Old.FLGACTIVO);
END DBEP_MPU_BRD;