INSERT INTO ADM_MENU_ROL (MNU_CODNUM, ROL_CODNUM, FLG_DESACT, FLG_ADMIN) VALUES (1108, 1052, 'N', 'N');
--/////////////////////
UPDATE ADM_MENU_IDM SET DESCRIPCION = '   Miembros comisión' WHERE MNU_CODNUM = 1108;