CREATE TABLE TBEP_ALEGACIONES (
    CODNUM NUMBER(11,0) CONSTRAINT RBEP_NALE_CODNUM NOT NULL,
    BEPSBO_CODNUM NUMBER(11,0) CONSTRAINT RBEP_NALE_BEPSBO_CODNUM NOT NULL,
    ESTADO VARCHAR2(20 BYTE) DEFAULT 'PENDIENTE',
    FECHACREACION TIMESTAMP DEFAULT CURRENT_TIMESTAMP CONSTRAINT RBEP_NALE_FECHA NOT NULL,
    FECHACONFIRMACION TIMESTAMP NULL,
    FECHAENVIODEPARTAMENTO TIMESTAMP NULL,
    FECHARESOLUCIONDEPARTAMENTO TIMESTAMP NULL,
    FECHARESOLUCIONFINAL TIMESTAMP NULL,
    DESRESOLUCIONDEP CLOB NULL,
    DESRESOLUCIONFINAL CLOB NULL,
    UID_USUARIO VARCHAR2(100) CONSTRAINT RBEP_NALE_UIDUSUARIO NOT NULL,
    CONSTRAINT IBEP_PALE PRIMARY KEY (CODNUM),
    CONSTRAINT IBEP_FALE_SBO FOREIGN KEY (BEPSBO_CODNUM) REFERENCES TBEP_SOLICITUD_BOLSAS (CODNUM),
    CONSTRAINT RBEP_CALE_ESTADO CHECK(ESTADO IN ('PENDIENTE','PRESENTADA','ENRESOLUCION','ENDEPARTAMENTO','INFORMADA','RESUELTA'))
);
--/////////////////////
COMMENT ON COLUMN TBEP_ALEGACIONES.BEPSBO_CODNUM IS 'Llave externa a la bolsa en la solicitud';
--/////////////////////
COMMENT ON COLUMN TBEP_ALEGACIONES.ESTADO IS 'Estado de la alegación';
--/////////////////////
COMMENT ON COLUMN TBEP_ALEGACIONES.FECHACREACION IS 'Fecha y hora en que se creó la alegación';
--/////////////////////
COMMENT ON COLUMN TBEP_ALEGACIONES.FECHACONFIRMACION IS 'Fecha y hora de confirmación de la alegación';
--/////////////////////
COMMENT ON COLUMN TBEP_ALEGACIONES.FECHAENVIODEPARTAMENTO IS 'Fecha de envío al departamento';
--/////////////////////
COMMENT ON COLUMN TBEP_ALEGACIONES.FECHARESOLUCIONDEPARTAMENTO IS 'Fecha de resolución por el departamento';
--/////////////////////
COMMENT ON COLUMN TBEP_ALEGACIONES.FECHARESOLUCIONFINAL IS 'Fecha de resolución final de la alegación';
--/////////////////////
COMMENT ON COLUMN TBEP_ALEGACIONES.DESRESOLUCIONDEP IS 'Descripción de la resolución por el departamento';
--/////////////////////
COMMENT ON COLUMN TBEP_ALEGACIONES.DESRESOLUCIONFINAL IS 'Descripción final de la resolución';
--/////////////////////
COMMENT ON TABLE TBEP_ALEGACIONES IS 'Alegaciones. ALIAS: [bepale] ACRONIMO: [ALE]';
--/////////////////////
CREATE TABLE TBEP_HTO_ALEGACIONES (
 	CODCAMBIO NUMBER(11,0) CONSTRAINT RBEP_NALE_HTO_CODCAMBIO NOT NULL,
 	LOG VARCHAR(50) CONSTRAINT RBEP_NALE_HTO_LOG NOT NULL,
 	FECHALOG TIMESTAMP DEFAULT CURRENT_TIMESTAMP CONSTRAINT RBEP_NALE_HTO_FECHALOG NOT NULL,
    CODNUM NUMBER(11,0) CONSTRAINT RBEP_NALE_HTO_CODNUM NOT NULL,
    BEPSBO_CODNUM NUMBER(11,0) CONSTRAINT RBEP_NALE_HTO_BEPSBO_CODNUM NOT NULL,
    ESTADO VARCHAR2(20 BYTE),
    FECHACREACION TIMESTAMP DEFAULT CURRENT_TIMESTAMP CONSTRAINT RBEP_NALE_HTO_FECHA NOT NULL,
    FECHACONFIRMACION TIMESTAMP NULL,
    FECHAENVIODEPARTAMENTO TIMESTAMP NULL,
    FECHARESOLUCIONDEPARTAMENTO TIMESTAMP NULL,
    FECHARESOLUCIONFINAL TIMESTAMP NULL,
    DESRESOLUCIONDEP CLOB NULL,
    DESRESOLUCIONFINAL CLOB NULL,
    UID_USUARIO VARCHAR2(100) CONSTRAINT RBEP_NALE_HTO_UIDUSUARIO NOT NULL,
    CONSTRAINT IBEP_PALE_HISTORICO PRIMARY KEY (CODCAMBIO)
);
--/////////////////////
CREATE SEQUENCE QBEP_ALE START WITH 1;
--/////////////////////
CREATE SEQUENCE QBEP_HTO_ALE START WITH 1;
--/////////////////////
CREATE TRIGGER DBEP_ALE_BRI
BEFORE INSERT
ON TBEP_ALEGACIONES
FOR EACH ROW
DECLARE
BEGIN
    SELECT QBEP_ALE.nextval into :new.CODNUM FROM dual;
    INSERT INTO TBEP_HTO_ALEGACIONES (CODCAMBIO,LOG,CODNUM,BEPSBO_CODNUM,ESTADO,FECHACREACION,FECHACONFIRMACION,FECHAENVIODEPARTAMENTO,FECHARESOLUCIONDEPARTAMENTO,FECHARESOLUCIONFINAL,DESRESOLUCIONDEP,DESRESOLUCIONFINAL,UID_USUARIO)
    VALUES (QBEP_HTO_ALE.NEXTVAL,'AFTER_INSERT',:New.CODNUM,:New.BEPSBO_CODNUM,:New.ESTADO,:New.FECHACREACION,:New.FECHACONFIRMACION,:New.FECHAENVIODEPARTAMENTO,:New.FECHARESOLUCIONDEPARTAMENTO,:New.FECHARESOLUCIONFINAL,:New.DESRESOLUCIONDEP,:New.DESRESOLUCIONFINAL,:New.UID_USUARIO);
END DBEP_ALE_BRI;
--/////////////////////
CREATE TRIGGER DBEP_ALE_BRU
BEFORE UPDATE
ON TBEP_ALEGACIONES
FOR EACH ROW
DECLARE
BEGIN
    INSERT INTO TBEP_HTO_ALEGACIONES (CODCAMBIO,LOG,CODNUM,BEPSBO_CODNUM,ESTADO,FECHACREACION,FECHACONFIRMACION,FECHAENVIODEPARTAMENTO,FECHARESOLUCIONDEPARTAMENTO,FECHARESOLUCIONFINAL,DESRESOLUCIONDEP,DESRESOLUCIONFINAL,UID_USUARIO)
    VALUES (QBEP_HTO_ALE.NEXTVAL,'BEFORE_UPDATE',:Old.CODNUM,:Old.BEPSBO_CODNUM,:Old.ESTADO,:Old.FECHACREACION,:Old.FECHACONFIRMACION,:Old.FECHAENVIODEPARTAMENTO,:Old.FECHARESOLUCIONDEPARTAMENTO,:Old.FECHARESOLUCIONFINAL,:Old.DESRESOLUCIONDEP,:Old.DESRESOLUCIONFINAL,:Old.UID_USUARIO);
    INSERT INTO TBEP_HTO_ALEGACIONES (CODCAMBIO,LOG,CODNUM,BEPSBO_CODNUM,ESTADO,FECHACREACION,FECHACONFIRMACION,FECHAENVIODEPARTAMENTO,FECHARESOLUCIONDEPARTAMENTO,FECHARESOLUCIONFINAL,DESRESOLUCIONDEP,DESRESOLUCIONFINAL,UID_USUARIO)
    VALUES (QBEP_HTO_ALE.NEXTVAL,'AFTER_UPDATE',:New.CODNUM,:New.BEPSBO_CODNUM,:New.ESTADO,:New.FECHACREACION,:New.FECHACONFIRMACION,:New.FECHAENVIODEPARTAMENTO,:New.FECHARESOLUCIONDEPARTAMENTO,:New.FECHARESOLUCIONFINAL,:New.DESRESOLUCIONDEP,:New.DESRESOLUCIONFINAL,:New.UID_USUARIO);
END DBEP_ALE_BRU;
--/////////////////////
CREATE TRIGGER DBEP_ALE_BRD
BEFORE DELETE
ON TBEP_ALEGACIONES
FOR EACH ROW
DECLARE
BEGIN
    INSERT INTO TBEP_HTO_ALEGACIONES (CODCAMBIO,LOG,CODNUM,BEPSBO_CODNUM,ESTADO,FECHACREACION,FECHACONFIRMACION,FECHAENVIODEPARTAMENTO,FECHARESOLUCIONDEPARTAMENTO,FECHARESOLUCIONFINAL,DESRESOLUCIONDEP,DESRESOLUCIONFINAL,UID_USUARIO)
    VALUES (QBEP_HTO_ALE.NEXTVAL,'BEFORE_DELETE',:Old.CODNUM,:Old.BEPSBO_CODNUM,:Old.ESTADO,:Old.FECHACREACION,:Old.FECHACONFIRMACION,:Old.FECHAENVIODEPARTAMENTO,:Old.FECHARESOLUCIONDEPARTAMENTO,:Old.FECHARESOLUCIONFINAL,:Old.DESRESOLUCIONDEP,:Old.DESRESOLUCIONFINAL,:Old.UID_USUARIO);
END DBEP_ALE_BRD;
--/////////////////////
CREATE TABLE TBEP_SOL_MER_BOL_ALEGACION (
    CODNUM NUMBER(11,0) CONSTRAINT RBEP_NALM_CODNUM NOT NULL,
    BEPALE_CODNUM NUMBER(11,0) CONSTRAINT RBEP_NALM_BEPALE_CODNUM NOT NULL,
    BEPSBM_CODNUM NUMBER(11,0),
    DESCRIPCION CLOB NULL,
    UID_USUARIO VARCHAR2(100) CONSTRAINT RBEP_NALM_UIDUSUARIO NOT NULL,
    CONSTRAINT IBEP_PALM PRIMARY KEY (CODNUM),
    CONSTRAINT IBEP_FALM_ALE FOREIGN KEY (BEPALE_CODNUM) REFERENCES TBEP_ALEGACIONES (CODNUM),
    CONSTRAINT IBEP_FALM_SBM FOREIGN KEY (BEPSBM_CODNUM) REFERENCES TBEP_SOL_BOL_MERITOS (CODNUM)
);
--/////////////////////
COMMENT ON COLUMN TBEP_SOL_MER_BOL_ALEGACION.BEPALE_CODNUM IS 'Llave externa a la alegación asociada';
--/////////////////////
COMMENT ON COLUMN TBEP_SOL_MER_BOL_ALEGACION.BEPSBM_CODNUM IS 'Llave externa a la solicitud de bolsa y méritos. Null para alegación general en la solicitud';
--/////////////////////
COMMENT ON COLUMN TBEP_SOL_MER_BOL_ALEGACION.DESCRIPCION IS 'Descripción de la alegación sobre el mérito';
--/////////////////////
COMMENT ON COLUMN TBEP_SOL_MER_BOL_ALEGACION.UID_USUARIO IS 'Último usuario que modifica el registro';
--/////////////////////
COMMENT ON TABLE TBEP_SOL_MER_BOL_ALEGACION IS 'Alegaciones asociadas a los méritos de una alegación. ALIAS: [bepalm] ACRONIMO: [ALM]';
--/////////////////////
CREATE TABLE TBEP_HTO_SOL_MER_BOL_ALEGACION (
    CODCAMBIO NUMBER(11,0) CONSTRAINT RBEP_NALM_HTO_CODCAMBIO NOT NULL,
    LOG VARCHAR(50) CONSTRAINT RBEP_NALM_HTO_LOG NOT NULL,
    FECHALOG TIMESTAMP DEFAULT CURRENT_TIMESTAMP CONSTRAINT RBEP_NALM_HTO_FECHALOG NOT NULL,
    CODNUM NUMBER(11,0) CONSTRAINT RBEP_NALM_HTO_CODNUM NOT NULL,
    BEPALE_CODNUM NUMBER(11,0) CONSTRAINT RBEP_NALM_HTO_BEPALE_CODNUM NOT NULL,
    BEPSBM_CODNUM NUMBER(11,0),
    DESCRIPCION CLOB NULL,
    UID_USUARIO VARCHAR2(100) CONSTRAINT RBEP_NALM_HTO_UIDUSUARIO NOT NULL,
    CONSTRAINT IBEP_PALM_HISTORICO PRIMARY KEY (CODCAMBIO)
);
--/////////////////////
CREATE SEQUENCE QBEP_ALM START WITH 1;
--/////////////////////
CREATE SEQUENCE QBEP_HTO_ALM START WITH 1;
--/////////////////////
CREATE TRIGGER DBEP_ALM_BRI
BEFORE INSERT
ON TBEP_SOL_MER_BOL_ALEGACION
FOR EACH ROW
DECLARE
BEGIN
    SELECT QBEP_ALM.nextval into :new.CODNUM FROM dual;
    INSERT INTO TBEP_HTO_SOL_MER_BOL_ALEGACION (CODCAMBIO,LOG,CODNUM,BEPALE_CODNUM,BEPSBM_CODNUM,DESCRIPCION,UID_USUARIO)
    VALUES (QBEP_HTO_ALM.NEXTVAL,'AFTER_INSERT',:New.CODNUM,:New.BEPALE_CODNUM,:New.BEPSBM_CODNUM,:New.DESCRIPCION,:New.UID_USUARIO);
END DBEP_ALM_BRI;
--/////////////////////
CREATE TRIGGER DBEP_ALM_BRU
BEFORE UPDATE
ON TBEP_SOL_MER_BOL_ALEGACION
FOR EACH ROW
DECLARE
BEGIN
    INSERT INTO TBEP_HTO_SOL_MER_BOL_ALEGACION (CODCAMBIO,LOG,CODNUM,BEPALE_CODNUM,BEPSBM_CODNUM,DESCRIPCION,UID_USUARIO)
    VALUES (QBEP_HTO_ALM.NEXTVAL,'BEFORE_UPDATE',:Old.CODNUM,:Old.BEPALE_CODNUM,:Old.BEPSBM_CODNUM,:Old.DESCRIPCION,:Old.UID_USUARIO);
    INSERT INTO TBEP_HTO_SOL_MER_BOL_ALEGACION (CODCAMBIO,LOG,CODNUM,BEPALE_CODNUM,BEPSBM_CODNUM,DESCRIPCION,UID_USUARIO)
    VALUES (QBEP_HTO_ALM.NEXTVAL,'AFTER_UPDATE',:New.CODNUM,:New.BEPALE_CODNUM,:New.BEPSBM_CODNUM,:New.DESCRIPCION,:New.UID_USUARIO);
END DBEP_ALM_BRU;
--/////////////////////
CREATE TRIGGER DBEP_ALM_BRD
BEFORE DELETE
ON TBEP_SOL_MER_BOL_ALEGACION
FOR EACH ROW
DECLARE
BEGIN
    INSERT INTO TBEP_HTO_SOL_MER_BOL_ALEGACION (CODCAMBIO,LOG,CODNUM,BEPALE_CODNUM,BEPSBM_CODNUM,DESCRIPCION,UID_USUARIO)
    VALUES (QBEP_HTO_ALM.NEXTVAL,'BEFORE_DELETE',:Old.CODNUM,:Old.BEPALE_CODNUM,:Old.BEPSBM_CODNUM,:Old.DESCRIPCION,:Old.UID_USUARIO);
END DBEP_ALM_BRD;
--/////////////////////
CREATE TABLE TBEP_SOL_MER_BOL_ALE_FILE (
    CODNUM NUMBER(11,0) CONSTRAINT RBEP_NALF_CODNUM NOT NULL,
    NOMBRE_ARCHIVO VARCHAR2(255) CONSTRAINT RBEP_NALF_NOMBRE_ARCHIVO NOT NULL,
    BEPALM_CODNUM NUMBER(11,0) CONSTRAINT RBEP_NALF_BEPALM_CODNUM NOT NULL,
    UID_USUARIO VARCHAR2(100) CONSTRAINT RBEP_NALF_UIDUSUARIO NOT NULL,
    CONSTRAINT IBEP_PALF PRIMARY KEY (CODNUM),
    CONSTRAINT IBEP_FALF_ALM FOREIGN KEY (BEPALM_CODNUM) REFERENCES TBEP_SOL_MER_BOL_ALEGACION (CODNUM)
);
--/////////////////////
COMMENT ON COLUMN TBEP_SOL_MER_BOL_ALE_FILE.NOMBRE_ARCHIVO IS 'Nombre del archivo asociado a la alegación';
--/////////////////////
COMMENT ON COLUMN TBEP_SOL_MER_BOL_ALE_FILE.BEPALM_CODNUM IS 'Referencia a la alegación de méritos';
--/////////////////////
COMMENT ON COLUMN TBEP_SOL_MER_BOL_ALE_FILE.UID_USUARIO IS 'Último usuario que modifica el registro';
--/////////////////////
COMMENT ON TABLE TBEP_SOL_MER_BOL_ALE_FILE IS 'Archivos asociados a la alegación de méritos. ALIAS: [bepalf] ACRONIMO: [ALF]';
--/////////////////////
CREATE TABLE TBEP_HTO_SOL_MER_BOL_ALE_FILE (
    CODCAMBIO NUMBER(11,0) CONSTRAINT RBEP_NALF_HTO_CODCAMBIO NOT NULL,
    LOG VARCHAR(50) CONSTRAINT RBEP_NALF_HTO_LOG NOT NULL,
    FECHALOG TIMESTAMP DEFAULT CURRENT_TIMESTAMP CONSTRAINT RBEP_NALF_HTO_FECHALOG NOT NULL,
    CODNUM NUMBER(11,0) CONSTRAINT RBEP_NALF_HTO_CODNUM NOT NULL,
    NOMBRE_ARCHIVO VARCHAR2(255) CONSTRAINT RBEP_NALF_HTO_NOMBRE_ARCHIVO NOT NULL,
    BEPALM_CODNUM NUMBER(11,0) CONSTRAINT RBEP_NALF_HTO_BEPALM_CODNUM NOT NULL,
    UID_USUARIO VARCHAR2(100) CONSTRAINT RBEP_NALF_HTO_UIDUSUARIO NOT NULL,
    CONSTRAINT IBEP_PALF_HISTORICO PRIMARY KEY (CODCAMBIO)
);
--/////////////////////
CREATE SEQUENCE QBEP_ALF START WITH 1;
--/////////////////////
CREATE SEQUENCE QBEP_HTO_ALF START WITH 1;
--/////////////////////
CREATE TRIGGER DBEP_ALF_BRI
BEFORE INSERT
ON TBEP_SOL_MER_BOL_ALE_FILE
FOR EACH ROW
DECLARE
BEGIN
    SELECT QBEP_ALF.nextval into :new.CODNUM FROM dual;
    INSERT INTO TBEP_HTO_SOL_MER_BOL_ALE_FILE (CODCAMBIO,LOG,CODNUM,NOMBRE_ARCHIVO,BEPALM_CODNUM,UID_USUARIO)
    VALUES (QBEP_HTO_ALF.NEXTVAL,'AFTER_INSERT',:New.CODNUM,:New.NOMBRE_ARCHIVO,:New.BEPALM_CODNUM,:New.UID_USUARIO);
END DBEP_ALF_BRI;
--/////////////////////
CREATE TRIGGER DBEP_ALF_BRU
BEFORE UPDATE
ON TBEP_SOL_MER_BOL_ALE_FILE
FOR EACH ROW
DECLARE
BEGIN
    INSERT INTO TBEP_HTO_SOL_MER_BOL_ALE_FILE (CODCAMBIO,LOG,CODNUM,NOMBRE_ARCHIVO,BEPALM_CODNUM,UID_USUARIO)
    VALUES (QBEP_HTO_ALF.NEXTVAL,'BEFORE_UPDATE',:Old.CODNUM,:Old.NOMBRE_ARCHIVO,:Old.BEPALM_CODNUM,:Old.UID_USUARIO);
    INSERT INTO TBEP_HTO_SOL_MER_BOL_ALE_FILE (CODCAMBIO,LOG,CODNUM,NOMBRE_ARCHIVO,BEPALM_CODNUM,UID_USUARIO)
    VALUES (QBEP_HTO_ALF.NEXTVAL,'AFTER_UPDATE',:New.CODNUM,:New.NOMBRE_ARCHIVO,:New.BEPALM_CODNUM,:New.UID_USUARIO);
END DBEP_ALF_BRU;
--/////////////////////
CREATE TRIGGER DBEP_ALF_BRD
BEFORE DELETE
ON TBEP_SOL_MER_BOL_ALE_FILE
FOR EACH ROW
DECLARE
BEGIN
    INSERT INTO TBEP_HTO_SOL_MER_BOL_ALE_FILE (CODCAMBIO,LOG,CODNUM,NOMBRE_ARCHIVO,BEPALM_CODNUM,UID_USUARIO)
    VALUES (QBEP_HTO_ALF.NEXTVAL,'BEFORE_DELETE',:Old.CODNUM,:Old.NOMBRE_ARCHIVO,:Old.BEPALM_CODNUM,:Old.UID_USUARIO);
END DBEP_ALF_BRD;
--/////////////////////
-- Menú candidato: Mis Alegaciones
--/////////////////////
INSERT INTO ADM_MENU (MNU_CODNUM, CONTROLADOR, FLG_DISPONIBLE, FLG_MOSTRAR, FLG_CREAMENU, FLG_PDFINTERNO, FLG_EXCEL, FLG_WORD, FLG_ANONIMO, PADRE_CODNUM, FLG_LOG) VALUES (1139, 'informacionadministrativa.bolsaempleo.misalegaciones', 'S', 'S', 'S','N', 'N', 'N', 'N', 1100, 'N');
--/////////////////////
INSERT INTO ADM_MENU_DOM (MNU_CODNUM, DOM_CODALF) VALUES (1139, 'ujaen.es');
--/////////////////////
INSERT INTO ADM_MENU_IDM (MNU_CODNUM, IDM_CODALF, DESCRIPCION) VALUES (1139, 'es', 'Mis Alegaciones');
--/////////////////////
INSERT INTO ADM_MENU_SIS (MNU_CODNUM, SIS_CODALF) VALUES (1139, 'uvirtual');
--/////////////////////
INSERT INTO ADM_MENU_RED (MNU_CODNUM, RED, DESCRIPCION, FLG_DESACT) VALUES (1139, '0.0.0.0/0', 'Publico', 'N');
--/////////////////////
INSERT INTO ADM_MENU_ROL (MNU_CODNUM, ROL_CODNUM, FLG_DESACT, FLG_ADMIN) VALUES (1139, 1052, 'N', 'N');
--/////////////////////
-- Plantillas
--/////////////////////
INSERT INTO TBEP_PLANTILLAS (NOMBRE,TITULO,CUERPO,UID_USUARIO)
VALUES (
    'Plantilla alegación resuelta',
    'Contestación a la alegación – <<idalegacion>> - <<nombre_area>>',
    '<!DOCTYPE html>
<html>
<head></head>
<body>
<div class="comment-container">
<div class="action-comment can-view-video markeddown js-comment" dir="auto">
<div class="current-comment js-friendly-links js-open-card">

<p>Estimado/a &lt;&lt;nombre_candidato&gt;&gt; &lt;&lt;apellidos_candidato&gt;&gt;</p>

<p>
Se informa que ya puede consultar el PDF con la contestación a su alegación con identificador
<strong>&lt;&lt;idalegacion&gt;&gt;</strong>, presentada por usted el
<strong>&lt;&lt;fecha_confirmacion&gt;&gt;</strong>, contra los resultados provisionales del
área de conocimiento de <strong>&lt;&lt;nombre_area&gt;&gt;</strong>.
</p>

<p>
Tras la publicación de la Resolución del Vicerrectorado de Personal Docente e Investigador por
la que se eleven a definitivos los resultados de la bolsa de sustitución del profesorado en el área
de conocimiento de <strong>&lt;&lt;nombre_area&gt;&gt;</strong>, podrá consultar los mismos en la
aplicación informática a la que se puede acceder desde la página web del Servicio de Personal:
</p>

<p>
<a href="https://www.ujaen.es/servicios/servpod/bolsa-de-sustitucion-pdi">
https://www.ujaen.es/servicios/servpod/bolsa-de-sustitucion-pdi
</a>
</p>

<p>
Contra la mencionada Resolución, podrá interponer recurso de alzada, en el plazo de un mes,
ante el Rector de la Universidad de Jaén, conforme a lo dispuesto en los artículos 121 y 122 de
la Ley 39/2015, de 1 de octubre, de Procedimiento Administrativo Común de las Administraciones Públicas.
</p>

<p>Un saludo</p>

<p>Jefe del Servicio de Personal</p>

</div>
</div>
</div>
</body>
</html>',
    'CARGA_INICIAL'
);
--/////////////////////
INSERT INTO TBEP_PLANTILLAS (NOMBRE,TITULO,CUERPO,UID_USUARIO)
VALUES (
    'Plantilla alegación enviada a departamento',
    'Alegación presentada – <<idalegacion>> - <<nombre_area>> - <<nombre_candidato>>',
    '<!DOCTYPE html>
<html>
<head></head>
<body>
<div class="comment-container">
<div class="action-comment can-view-video markeddown js-comment" dir="auto">
<div class="current-comment js-friendly-links js-open-card">

<p>Estimado/a Director/a</p>

<p>
Se adjunta alegación presentada por D./Dª.
<strong>&lt;&lt;nombre_candidato&gt;&gt; &lt;&lt;apellidos_candidato&gt;&gt;</strong>
contra los resultados provisionales del área de conocimiento
<strong>&lt;&lt;nombre_area&gt;&gt;</strong>.
</p>

<p>
Te ruego que con la mayor celeridad que sea posible emitas informe, a través de la plataforma
de la bolsa de sustituciones del profesorado, acerca de los méritos alegados.
</p>

<p>Un saludo</p>

<p>Jefe del Servicio de Personal</p>

</div>
</div>
</div>
</body>
</html>',
    'CARGA_INICIAL'
);--/////////////////////
INSERT INTO TBEP_PARAMETROS_CONFIG (NOMBRE,VALOR,DESCRIPCION,UID_USUARIO)
SELECT 'bolsaempleo.local.idPlantillaAlegacionResuelta', CODNUM, 'Id de la plantilla para notificar al candidato que su alegación ha sido resuelta', 'CARGA_INICIAL'
FROM TBEP_PLANTILLAS
WHERE NOMBRE='Plantilla alegación resuelta';
--/////////////////////
INSERT INTO TBEP_PARAMETROS_CONFIG (NOMBRE,VALOR,DESCRIPCION,UID_USUARIO)
SELECT 'bolsaempleo.local.idPlantillaAlegacionEnviadaDepartamento', CODNUM, 'Id de la plantilla para notificar sobre una alegación enviada al departamento', 'CARGA_INICIAL'
FROM TBEP_PLANTILLAS
WHERE NOMBRE='Plantilla alegación enviada a departamento';
--/////////////////////
-- Bolsas
--/////////////////////
ALTER TABLE TBEP_BOLSAS ADD (FECHAFINALEGACIONES TIMESTAMP NULL);
--/////////////////////
COMMENT ON COLUMN TBEP_BOLSAS.FECHAFINALEGACIONES IS 'Fecha y hora límite para presentar alegaciones';
--/////////////////////
ALTER TABLE TBEP_HTO_BOLSAS ADD (FECHAFINALEGACIONES TIMESTAMP NULL);
--/////////////////////
CREATE OR REPLACE TRIGGER DBEP_BOL_BRI
BEFORE INSERT
ON TBEP_BOLSAS
FOR EACH ROW
DECLARE
BEGIN
    SELECT QBEP_BOL.nextval into :new.CODNUM FROM dual;

    INSERT INTO TBEP_HTO_BOLSAS (CODCAMBIO,LOG,CODNUM,BEPARE_CODNUM,ESTADO,FLGBAREMABLE,FECHAACTUALIZACION,FECHABLOQUEO,FECHADEBLOQUEO,FLGPENBAREMACION,FECHABAREMACION,FECHABAREMACIONFIN,FECHAHABCONTRATOS,FECHAFINALEGACIONES,UID_USUARIO)
    VALUES (QBEP_HTO_ARE.NEXTVAL,'AFTER_INSERT',:New.CODNUM,:New.BEPARE_CODNUM,:New.ESTADO,:New.FLGBAREMABLE,:New.FECHAACTUALIZACION,:New.FECHABLOQUEO,:New.FECHADEBLOQUEO,:New.FLGPENBAREMACION,:New.FECHABAREMACION,:New.FECHABAREMACIONFIN,:New.FECHAHABCONTRATOS,:New.FECHAFINALEGACIONES,:New.UID_USUARIO);
END DBEP_BOL_BRI;
--/////////////////////
CREATE OR REPLACE TRIGGER DBEP_BOL_BRU
BEFORE UPDATE
ON TBEP_BOLSAS
FOR EACH ROW
DECLARE
BEGIN
	INSERT INTO TBEP_HTO_BOLSAS (CODCAMBIO,LOG,CODNUM,BEPARE_CODNUM,ESTADO,FLGBAREMABLE,FECHAACTUALIZACION,FECHABLOQUEO,FECHADEBLOQUEO,FLGPENBAREMACION,FECHABAREMACION,FECHABAREMACIONFIN,FECHAHABCONTRATOS,FECHAFINALEGACIONES,UID_USUARIO)
    VALUES (QBEP_HTO_ARE.NEXTVAL,'BEFORE_UPDATE',:Old.CODNUM,:Old.BEPARE_CODNUM,:Old.ESTADO,:Old.FLGBAREMABLE,:Old.FECHAACTUALIZACION,:Old.FECHABLOQUEO,:Old.FECHADEBLOQUEO,:Old.FLGPENBAREMACION,:Old.FECHABAREMACION,:Old.FECHABAREMACIONFIN,:Old.FECHAHABCONTRATOS,:Old.FECHAFINALEGACIONES,:Old.UID_USUARIO);

    INSERT INTO TBEP_HTO_BOLSAS (CODCAMBIO,LOG,CODNUM,BEPARE_CODNUM,ESTADO,FLGBAREMABLE,FECHAACTUALIZACION,FECHABLOQUEO,FECHADEBLOQUEO,FLGPENBAREMACION,FECHABAREMACION,FECHABAREMACIONFIN,FECHAHABCONTRATOS,FECHAFINALEGACIONES,UID_USUARIO)
    VALUES (QBEP_HTO_ARE.NEXTVAL,'AFTER_UPDATE',:New.CODNUM,:New.BEPARE_CODNUM,:New.ESTADO,:New.FLGBAREMABLE,:New.FECHAACTUALIZACION,:New.FECHABLOQUEO,:New.FECHADEBLOQUEO,:New.FLGPENBAREMACION,:New.FECHABAREMACION,:New.FECHABAREMACIONFIN,:New.FECHAHABCONTRATOS,:New.FECHAFINALEGACIONES,:New.UID_USUARIO);
END DBEP_BOL_BRU;
--/////////////////////
CREATE OR REPLACE TRIGGER DBEP_BOL_BRD
BEFORE DELETE
ON TBEP_BOLSAS
FOR EACH ROW
DECLARE
BEGIN
	INSERT INTO TBEP_HTO_BOLSAS (CODCAMBIO,LOG,CODNUM,BEPARE_CODNUM,ESTADO,FLGBAREMABLE,FECHAACTUALIZACION,FECHABLOQUEO,FECHADEBLOQUEO,FLGPENBAREMACION,FECHABAREMACION,FECHABAREMACIONFIN,FECHAHABCONTRATOS,FECHAFINALEGACIONES,UID_USUARIO)
    VALUES (QBEP_HTO_ARE.NEXTVAL,'BEFORE_DELETE',:Old.CODNUM,:Old.BEPARE_CODNUM,:Old.ESTADO,:Old.FLGBAREMABLE,:Old.FECHAACTUALIZACION,:Old.FECHABLOQUEO,:Old.FECHADEBLOQUEO,:Old.FLGPENBAREMACION,:Old.FECHABAREMACION,:Old.FECHABAREMACIONFIN,:Old.FECHAHABCONTRATOS,:Old.FECHAFINALEGACIONES,:Old.UID_USUARIO);
END DBEP_BOL_BRD;
