alter session set "_ORACLE_SCRIPT"=true; 
CREATE USER uvirtual IDENTIFIED BY pwd123;
CREATE USER uxxirrhh IDENTIFIED BY pwd123;
CREATE USER arcos IDENTIFIED BY pwd123;
CREATE USER uxxiac IDENTIFIED BY pwd123;
CREATE USER uxxiec IDENTIFIED BY pwd123;
CREATE USER tramuja IDENTIFIED BY pwd123;
CREATE USER todo IDENTIFIED BY pwd123;
GRANT ALL PRIVILEGES TO todo;

GRANT CREATE SESSION TO uvirtual;
GRANT CREATE SESSION TO uxxirrhh;
GRANT CREATE SESSION TO arcos;
GRANT CREATE SESSION TO uxxiac;
GRANT CREATE SESSION TO uxxiec;
GRANT CREATE SESSION TO tramuja;

GRANT CONNECT, RESOURCE TO uvirtual;
GRANT CONNECT, RESOURCE TO uxxirrhh;
GRANT CONNECT, RESOURCE TO arcos;
GRANT CONNECT, RESOURCE TO uxxiac;
GRANT CONNECT, RESOURCE TO uxxiec;
GRANT CONNECT, RESOURCE TO tramuja;

GRANT CREATE VIEW TO uvirtual;

ALTER USER uvirtual quota 100M on USERS;
ALTER USER uxxirrhh quota 100M on USERS;
ALTER USER arcos quota 100M on USERS;
ALTER USER uxxiac quota 100M on USERS;
ALTER USER uxxiec quota 100M on USERS;
ALTER USER tramuja quota 100M on USERS;
