-- ARCOS.CUENTAACTIVA definition
CREATE TABLE "ARCOS"."CUENTAACTIVA" 
   (	"IDIDENTIFICADOR" VARCHAR2(75)
   );
--/////////////////////
-- ARCOS.VINFO_CTA_PRS_GRP_INTRANET definition
CREATE TABLE "ARCOS"."VINFO_CTA_PRS_GRP_INTRANET" 
   (	"IDIDENTIFICADOR" VARCHAR2(75), 
	"UJAENDNI" VARCHAR2(20), 
	"GRUPO" VARCHAR2(100), 
	"BLNMANUAL" VARCHAR2(1), 
	"DATULTIMAACTUALIZACION" DATE
   );  
--/////////////////////
-- ARCOS.VINFO_CTA_SRV_ACT_INTRANET definition
CREATE TABLE "ARCOS"."VINFO_CTA_SRV_ACT_INTRANET" 
   (	"IDIDENTIFICADOR" VARCHAR2(75), 
	"IDSERVICIO" VARCHAR2(75), 
	"DATALTA" DATE, 
	"DATFINALIZACION" DATE, 
	"BLNHABILITADA" VARCHAR2(1), 
	"IDCUENTA" NUMBER(9,0)
   );
--/////////////////////
-- ARCOS.VINFO_LST_ALIAS definition
CREATE TABLE "ARCOS"."VINFO_LST_ALIAS" 
   (	"IDIDENTIFICADOR" VARCHAR2(75), 
	"IDDOMINIO" VARCHAR2(75), 
	"STRCORREORUTA" VARCHAR2(75), 
	"STRDESCRIPCION" VARCHAR2(75), 
	"IDNIF" VARCHAR2(75), 
	"STRNOMBRE" VARCHAR2(75), 
	"STRAPELLIDO1" VARCHAR2(75), 
	"STRAPELLIDO2" VARCHAR2(75), 
	"CODINT" NUMBER
   );
--/////////////////////
-- ARCOS.V_CUENTAS_INTRANET definition
CREATE TABLE "ARCOS"."V_CUENTAS_INTRANET" 
   (	"IDCUENTA" NUMBER(9,0), 
	"IDIDENTIFICADOR" VARCHAR2(75), 
	"STRDN" VARCHAR2(106), 
	"CODINT" NUMBER, 
	"IDDOMINIO" VARCHAR2(75), 
	"BLNBLOQUEADA" VARCHAR2(1), 
	"BLNCTAGGL" VARCHAR2(1), 
	"BLNCTAGGLSUSP" VARCHAR2(1), 
	"BLNINSTITUCIONAL" VARCHAR2(1), 
	"STRDESCRIPCION" VARCHAR2(125), 
	"STRCORREORUTA" VARCHAR2(125),
	CONSTRAINT pk_v_cuentas_intranet PRIMARY KEY (idcuenta)
   );
--/////////////////////
-- ARCOS.V_PERSONA_INTRANET definition
CREATE TABLE "ARCOS"."V_PERSONA_INTRANET" 
   (	"CODINT" NUMBER, 
	"UJAENDNI" VARCHAR2(20), 
	"NUMDOCUMENTO" VARCHAR2(4000), 
	"STRTIPODOCUMENTO" VARCHAR2(8), 
	"STRNOMBRE" VARCHAR2(45), 
	"STRAPELLIDO1" VARCHAR2(45), 
	"STRAPELLIDO2" VARCHAR2(45), 
	"SEXO" VARCHAR2(1), 
	"COD_PERSONA_AC" NUMBER(8,0), 
	"COD_PERSONA_RH" NUMBER(8,0), 
	"BLNMANUAL" VARCHAR2(1),
	CONSTRAINT pk_v_persona_intranet PRIMARY KEY (codint)
   );
--/////////////////////
-- ARCOS.V_RESPORGANICO_INTRANET definition
CREATE TABLE "ARCOS"."V_RESPORGANICO_INTRANET" 
   (	"IDIDENTIFICADOR" VARCHAR2(75), 
	"IDCUENTA" NUMBER(9,0), 
	"IDSERVICIO" VARCHAR2(75), 
	"DATALTA" DATE, 
	"DATULTIMOACCESO" DATE, 
	"DATFINALIZACION" DATE, 
	"STRCUOTA" VARCHAR2(75), 
	"STRDIRECTORIO" VARCHAR2(75), 
	"BLNHABILITADA" VARCHAR2(1), 
	"STRSERVICIO" VARCHAR2(75)
   );