-- UVIRTUAL.ADM_AVISO_INICIO definition
CREATE TABLE "UVIRTUAL"."ADM_AVISO_INICIO" 
   (	"DESCRIPCION" VARCHAR2(1000) NOT NULL ENABLE, 
	"TIPO" VARCHAR2(1) NOT NULL ENABLE, 
	"DATINI" DATE DEFAULT sysdate NOT NULL ENABLE, 
	"DATFIN" DATE NOT NULL ENABLE, 
	"CODNUM" NUMBER(3,0) NOT NULL ENABLE, 
	"TEXTO_AMPLIADO" CLOB, 
	 CONSTRAINT "CK_AVS_TIPO" CHECK (tipo in ('I', 'A')) ENABLE, 
	 CONSTRAINT "ADM_AVISO_INICIO_PK" PRIMARY KEY ("CODNUM"));

COMMENT ON COLUMN "UVIRTUAL"."ADM_AVISO_INICIO"."DESCRIPCION" IS 'Texto del aviso';
   COMMENT ON COLUMN "UVIRTUAL"."ADM_AVISO_INICIO"."TIPO" IS 'Tipo de aviso: I=informativo, A=advertencia';
   COMMENT ON COLUMN "UVIRTUAL"."ADM_AVISO_INICIO"."DATINI" IS 'Fecha en la que empieza de mostrarse el aviso';
   COMMENT ON COLUMN "UVIRTUAL"."ADM_AVISO_INICIO"."DATFIN" IS 'Fecha en la que deja de mostrarse el aviso';
   COMMENT ON COLUMN "UVIRTUAL"."ADM_AVISO_INICIO"."CODNUM" IS 'código interno de aviso';
   COMMENT ON COLUMN "UVIRTUAL"."ADM_AVISO_INICIO"."TEXTO_AMPLIADO" IS 'texto ampliado del aviso';
   COMMENT ON TABLE "UVIRTUAL"."ADM_AVISO_INICIO"  IS 'Avisos en la página de entrada de uvirtual';


-- UVIRTUAL.ADM_COLA definition

CREATE TABLE "UVIRTUAL"."ADM_COLA" 
   (	"COLA_CODALF" VARCHAR2(20), 
	"DESID" VARCHAR2(1000), 
	"FLG_TOPIC" VARCHAR2(1) DEFAULT 'N', 
	 CHECK (flg_topic in ('S', 'N')) ENABLE, 
	 PRIMARY KEY ("COLA_CODALF"));


-- UVIRTUAL.ADM_DOM definition

CREATE TABLE "UVIRTUAL"."ADM_DOM" 
   (	"DOM_CODALF" VARCHAR2(200), 
	 PRIMARY KEY ("DOM_CODALF"));

COMMENT ON COLUMN "UVIRTUAL"."ADM_DOM"."DOM_CODALF" IS 'Nombre del dominio';
   COMMENT ON TABLE "UVIRTUAL"."ADM_DOM"  IS 'Dominios de cuentas de usuario definidos en la Universidad';


-- UVIRTUAL.ADM_IDIOMA definition

CREATE TABLE "UVIRTUAL"."ADM_IDIOMA" 
   (	"IDM_CODALF" VARCHAR2(5), 
	"DESCRIPCION" VARCHAR2(30), 
	 CONSTRAINT "PK_IDM" PRIMARY KEY ("IDM_CODALF"));

COMMENT ON COLUMN "UVIRTUAL"."ADM_IDIOMA"."IDM_CODALF" IS 'descripción corta del idioma, será utilizada en la url';
   COMMENT ON COLUMN "UVIRTUAL"."ADM_IDIOMA"."DESCRIPCION" IS 'Nombre del idioma (en su propio idioma, para poder ser mostrado en pantalla)';
   COMMENT ON TABLE "UVIRTUAL"."ADM_IDIOMA"  IS 'Idiomas soportados en campus virtual - incluido el neutro';


-- UVIRTUAL.ADM_MENU definition

CREATE TABLE "UVIRTUAL"."ADM_MENU" 
   (	"MNU_CODNUM" NUMBER(6,0), 
	"CONTROLADOR" VARCHAR2(200), 
	"FLG_DISPONIBLE" VARCHAR2(1), 
	"FLG_MOSTRAR" VARCHAR2(1), 
	"FLG_CREAMENU" VARCHAR2(1), 
	"FLG_PDFINTERNO" VARCHAR2(1), 
	"FLG_EXCEL" VARCHAR2(1) DEFAULT ('N'), 
	"FLG_WORD" VARCHAR2(1) DEFAULT ('N'), 
	"FLG_ANONIMO" VARCHAR2(1), 
	"PADRE_CODNUM" NUMBER(6,0), 
	"DIRECCION" VARCHAR2(200), 
	"TELEFONO" VARCHAR2(30), 
	"FAX" VARCHAR2(30), 
	"EMAIL" VARCHAR2(200), 
	"FLG_LOG" VARCHAR2(1) DEFAULT ('N'), 
	 CONSTRAINT "CK_MNU_ANN" CHECK (flg_anonimo IN ('S', 'N')) ENABLE, 
	 CONSTRAINT "CK_MNU_DOCX" CHECK (flg_word IN ('S', 'N')) ENABLE, 
	 CONSTRAINT "CK_MNU_DSP" CHECK (flg_disponible IN ('S', 'N')) ENABLE, 
	 CONSTRAINT "CK_MNU_LOG" CHECK (flg_log IN ('S', 'N')) ENABLE, 
	 CONSTRAINT "CK_MNU_MEN" CHECK (flg_creamenu IN ('S', 'N')) ENABLE, 
	 CONSTRAINT "CK_MNU_MOS" CHECK (flg_mostrar IN ('S', 'N')) ENABLE, 
	 CONSTRAINT "CK_MNU_PDF" CHECK (flg_pdfinterno IN ('S', 'N')) ENABLE, 
	 CONSTRAINT "CK_MNU_XSLX" CHECK (flg_excel IN ('S', 'N')) ENABLE, 
	 CONSTRAINT "PK_MNU" PRIMARY KEY ("MNU_CODNUM"));

COMMENT ON COLUMN "UVIRTUAL"."ADM_MENU"."MNU_CODNUM" IS 'Código interno del menú';
   COMMENT ON COLUMN "UVIRTUAL"."ADM_MENU"."CONTROLADOR" IS 'Nombre de la acción';
   COMMENT ON COLUMN "UVIRTUAL"."ADM_MENU"."FLG_DISPONIBLE" IS 'Indica si la acción está disponible o fuera de servicio';
   COMMENT ON COLUMN "UVIRTUAL"."ADM_MENU"."FLG_MOSTRAR" IS 'Cuando se crea un menú automáticamente, aparece o no la acción';
   COMMENT ON COLUMN "UVIRTUAL"."ADM_MENU"."FLG_CREAMENU" IS 'Si se añade por filtros la cabecera, menu, etc. o se deja la página tal cual';
   COMMENT ON COLUMN "UVIRTUAL"."ADM_MENU"."FLG_PDFINTERNO" IS 'Mostrar generar pdf de forma interna ';
   COMMENT ON COLUMN "UVIRTUAL"."ADM_MENU"."FLG_EXCEL" IS 'Mostrar generar excel de forma interna ';
   COMMENT ON COLUMN "UVIRTUAL"."ADM_MENU"."FLG_WORD" IS 'Mostrar generar word de forma interna ';
   COMMENT ON COLUMN "UVIRTUAL"."ADM_MENU"."FLG_ANONIMO" IS 'Se puede acceder de forma anónima al menú (opción pública)';
   COMMENT ON COLUMN "UVIRTUAL"."ADM_MENU"."PADRE_CODNUM" IS 'Padre del menú para un menú jerárquico';
   COMMENT ON COLUMN "UVIRTUAL"."ADM_MENU"."DIRECCION" IS 'Dirección a mostrar en el pie de página';
   COMMENT ON COLUMN "UVIRTUAL"."ADM_MENU"."TELEFONO" IS 'Teléfono a mostrar en el pie de página';
   COMMENT ON COLUMN "UVIRTUAL"."ADM_MENU"."FAX" IS 'Número de fax a mostrar en el pie de página';
   COMMENT ON COLUMN "UVIRTUAL"."ADM_MENU"."EMAIL" IS 'Dirección de correo electrónico a mostrar en el pie de página';
   COMMENT ON COLUMN "UVIRTUAL"."ADM_MENU"."FLG_LOG" IS 'Log de accesos a la acción, por defecto S';
   COMMENT ON TABLE "UVIRTUAL"."ADM_MENU"  IS 'Elementos accesibles de la aplicación';


-- UVIRTUAL.ADM_NODO definition

CREATE TABLE "UVIRTUAL"."ADM_NODO" 
   (	"NODO_CODALF" VARCHAR2(20), 
	"DESID" VARCHAR2(100), 
	 PRIMARY KEY ("NODO_CODALF"));


-- UVIRTUAL.ADM_PARAMETROS definition

CREATE TABLE "UVIRTUAL"."ADM_PARAMETROS" 
   (	"CONFIG_CODALF" VARCHAR2(30) DEFAULT 'default' NOT NULL ENABLE, 
	"PARAM_CODALF" VARCHAR2(100) NOT NULL ENABLE, 
	"DESID" VARCHAR2(200), 
	"VALOR" CLOB, 
	 PRIMARY KEY ("CONFIG_CODALF", "PARAM_CODALF"));


-- UVIRTUAL.ADM_ROL definition

CREATE TABLE "UVIRTUAL"."ADM_ROL" 
   (	"ROL_CODNUM" NUMBER(3,0), 
	"DESCRIPCION" VARCHAR2(100), 
	"VALOR" VARCHAR2(100), 
	 CONSTRAINT "CK_ADM_ROL_VAL" CHECK ((instr(valor, ':') = 0) and (instr(valor,'.') = 0)) ENABLE, 
	 CONSTRAINT "PK_ROL" PRIMARY KEY ("ROL_CODNUM"), 
	 CONSTRAINT "UK_ADM_ROL_VAL" UNIQUE ("VALOR"));

COMMENT ON COLUMN "UVIRTUAL"."ADM_ROL"."ROL_CODNUM" IS 'Código interno del rol';
   COMMENT ON COLUMN "UVIRTUAL"."ADM_ROL"."DESCRIPCION" IS 'Descripción del rol';
   COMMENT ON COLUMN "UVIRTUAL"."ADM_ROL"."VALOR" IS 'Código alfabético del rol';
   COMMENT ON TABLE "UVIRTUAL"."ADM_ROL"  IS 'Roles definidos en la aplicación';


-- UVIRTUAL.ADM_SISTEMA definition

CREATE TABLE "UVIRTUAL"."ADM_SISTEMA" 
   (	"SIS_CODALF" VARCHAR2(10) NOT NULL ENABLE, 
	"DESCRIPCION" VARCHAR2(100) NOT NULL ENABLE, 
	"FLG_MANTO" VARCHAR2(1) DEFAULT 'N' NOT NULL ENABLE, 
	"DESC_MANTO" VARCHAR2(1000), 
	"DAT_MANTO" DATE, 
	 CONSTRAINT "CK_SIS_MNT" CHECK (flg_manto in ('S', 'N')) ENABLE, 
	 PRIMARY KEY ("SIS_CODALF"));

COMMENT ON COLUMN "UVIRTUAL"."ADM_SISTEMA"."SIS_CODALF" IS 'Código del sistema';
   COMMENT ON COLUMN "UVIRTUAL"."ADM_SISTEMA"."DESCRIPCION" IS 'Nombre del sistema al que se conecta Universidad Virtual';
   COMMENT ON COLUMN "UVIRTUAL"."ADM_SISTEMA"."FLG_MANTO" IS 'Indica si el sistema está en mantenimiento (S) u operativo (N)';
   COMMENT ON COLUMN "UVIRTUAL"."ADM_SISTEMA"."DESC_MANTO" IS 'Motivo a mostrar por el que un sistema está en mantenimiento';
   COMMENT ON COLUMN "UVIRTUAL"."ADM_SISTEMA"."DAT_MANTO" IS 'Si el valor no es nulo y flg_manto es S indica la fecha y hora en que entra en mantenimiento';
   COMMENT ON TABLE "UVIRTUAL"."ADM_SISTEMA"  IS 'Sistemas a los que tiene conexión Universidad Virtual';


-- UVIRTUAL.ADM_VERSION definition

CREATE TABLE "UVIRTUAL"."ADM_VERSION" 
   (	"CODALF" VARCHAR2(100), 
	"VERSION" NUMBER(20,0), 
	 CONSTRAINT "PK_VER" PRIMARY KEY ("CODALF"));

COMMENT ON COLUMN "UVIRTUAL"."ADM_VERSION"."CODALF" IS 'Código o clave de la versión';
   COMMENT ON COLUMN "UVIRTUAL"."ADM_VERSION"."VERSION" IS 'Número de la versión';
   COMMENT ON TABLE "UVIRTUAL"."ADM_VERSION"  IS 'Valores de las distintas versiones del menú, etc.';


-- UVIRTUAL.AVISO_APLICACION_CAMPO definition

CREATE TABLE "UVIRTUAL"."AVISO_APLICACION_CAMPO" 
   (	"CODALF" VARCHAR2(3), 
	"DESCRIPCION" VARCHAR2(100) NOT NULL ENABLE, 
	 CONSTRAINT "AVISO_APLICACION_CAMPO_PK" PRIMARY KEY ("CODALF"));

COMMENT ON COLUMN "UVIRTUAL"."AVISO_APLICACION_CAMPO"."CODALF" IS 'codigo';
   COMMENT ON COLUMN "UVIRTUAL"."AVISO_APLICACION_CAMPO"."DESCRIPCION" IS 'descripcion';
   COMMENT ON TABLE "UVIRTUAL"."AVISO_APLICACION_CAMPO"  IS 'campo usado por la aplicacion para enviar mensajes';


-- UVIRTUAL.AVISO_APLICACION_TIPO definition

CREATE TABLE "UVIRTUAL"."AVISO_APLICACION_TIPO" 
   (	"CODALF" VARCHAR2(20), 
	"DESCRIPCION" VARCHAR2(100) NOT NULL ENABLE, 
	 CONSTRAINT "AVISO_TIPO_APLICACION_PK" PRIMARY KEY ("CODALF"));

COMMENT ON COLUMN "UVIRTUAL"."AVISO_APLICACION_TIPO"."CODALF" IS 'codigo';
   COMMENT ON COLUMN "UVIRTUAL"."AVISO_APLICACION_TIPO"."DESCRIPCION" IS 'descripcion';
   COMMENT ON TABLE "UVIRTUAL"."AVISO_APLICACION_TIPO"  IS 'Tipos de medio de contacto para la cuenta tic';


-- UVIRTUAL.AVISO_LOG_RECIBIDOS definition

CREATE TABLE "UVIRTUAL"."AVISO_LOG_RECIBIDOS" 
   (	"ORIGEN" VARCHAR2(100), 
	"FECHA" DATE, 
	"APLICACION" VARCHAR2(3), 
	"MENSAJE" VARCHAR2(2000)
   );

COMMENT ON COLUMN "UVIRTUAL"."AVISO_LOG_RECIBIDOS"."ORIGEN" IS 'el origen del mensaje';
   COMMENT ON COLUMN "UVIRTUAL"."AVISO_LOG_RECIBIDOS"."FECHA" IS 'fecha en que se recibe';
   COMMENT ON COLUMN "UVIRTUAL"."AVISO_LOG_RECIBIDOS"."APLICACION" IS 'aplicacion que lo ha recibido';
   COMMENT ON COLUMN "UVIRTUAL"."AVISO_LOG_RECIBIDOS"."MENSAJE" IS 'cuerpo del mensaje';
   COMMENT ON TABLE "UVIRTUAL"."AVISO_LOG_RECIBIDOS"  IS 'logs de los mensajes recibidos en mensajeria instantanea';


-- UVIRTUAL.AVISO_PERSONAL_SOLICITUD definition

CREATE TABLE "UVIRTUAL"."AVISO_PERSONAL_SOLICITUD" 
   (	"CODNUM" NUMBER, 
	"ASUNTO" VARCHAR2(200) NOT NULL ENABLE, 
	"MENSAJE" VARCHAR2(4000) NOT NULL ENABLE, 
	"DATSOLICITUD" DATE NOT NULL ENABLE, 
	"CUENTA_ORIGEN" VARCHAR2(75) NOT NULL ENABLE, 
	 CONSTRAINT "AVISO_PERSONAL_SOLICITUD_PK" PRIMARY KEY ("CODNUM"));

COMMENT ON COLUMN "UVIRTUAL"."AVISO_PERSONAL_SOLICITUD"."CODNUM" IS 'codigo de solicitud';
   COMMENT ON COLUMN "UVIRTUAL"."AVISO_PERSONAL_SOLICITUD"."ASUNTO" IS 'asunto';
   COMMENT ON COLUMN "UVIRTUAL"."AVISO_PERSONAL_SOLICITUD"."MENSAJE" IS 'cuerpo del mensaje';
   COMMENT ON COLUMN "UVIRTUAL"."AVISO_PERSONAL_SOLICITUD"."DATSOLICITUD" IS 'fecha en que se realiza la solicitud';
   COMMENT ON COLUMN "UVIRTUAL"."AVISO_PERSONAL_SOLICITUD"."CUENTA_ORIGEN" IS 'cuenta que realiza la solicitud';
   COMMENT ON TABLE "UVIRTUAL"."AVISO_PERSONAL_SOLICITUD"  IS 'Solicitudes de envio de aviso personal. padre de aviso_personal. ';


-- UVIRTUAL.ENLACE_INDICE definition

CREATE TABLE "UVIRTUAL"."ENLACE_INDICE" 
   (	"ENLACE_CODNUM" NUMBER(3,0) NOT NULL ENABLE, 
	"IMAGEN" VARCHAR2(200), 
	"TITULO" VARCHAR2(200), 
	"ORDEN" NUMBER(3,0), 
	"URL_AUTENTICADO" VARCHAR2(200), 
	"URL_NO_AUTENTICADO" VARCHAR2(200), 
	"FECHA_INICIO" DATE, 
	"FECHA_FIN" DATE, 
	 PRIMARY KEY ("ENLACE_CODNUM"));

COMMENT ON COLUMN "UVIRTUAL"."ENLACE_INDICE"."ENLACE_CODNUM" IS 'Código único del enlace';
   COMMENT ON COLUMN "UVIRTUAL"."ENLACE_INDICE"."IMAGEN" IS 'URL de la imagen a mostrar';
   COMMENT ON COLUMN "UVIRTUAL"."ENLACE_INDICE"."TITULO" IS 'Nombre a mostrar como title de la imagen y como texto alternativo';
   COMMENT ON COLUMN "UVIRTUAL"."ENLACE_INDICE"."ORDEN" IS 'Orden en el que se mostrará el enlace';
   COMMENT ON COLUMN "UVIRTUAL"."ENLACE_INDICE"."URL_AUTENTICADO" IS 'URL del enlace cuando se está autenticado';
   COMMENT ON COLUMN "UVIRTUAL"."ENLACE_INDICE"."URL_NO_AUTENTICADO" IS 'URL del enlace cuando no se está autenticado';
   COMMENT ON COLUMN "UVIRTUAL"."ENLACE_INDICE"."FECHA_INICIO" IS 'Fecha en la que se inicia la fecha a mostrar';
   COMMENT ON COLUMN "UVIRTUAL"."ENLACE_INDICE"."FECHA_FIN" IS 'Fecha en la que se dejará de mostrar';
   COMMENT ON TABLE "UVIRTUAL"."ENLACE_INDICE"  IS 'Tabla con los enlaces a mostar en la página inicial';


-- UVIRTUAL.LOG_ACCESO definition

CREATE TABLE "UVIRTUAL"."LOG_ACCESO" 
   (	"FECHA" DATE, 
	"SERVIDOR" VARCHAR2(200), 
	"ACCESO" VARCHAR2(4000), 
	"IP" VARCHAR2(20), 
	"SESION" VARCHAR2(200), 
	"USUARIO" VARCHAR2(100), 
	"TIEMPO" NUMBER(9,0), 
	"COMENTARIO" CLOB, 
	"PARAMS" CLOB, 
	"EXCEPCION" CLOB
   );

COMMENT ON COLUMN "UVIRTUAL"."LOG_ACCESO"."FECHA" IS 'Fecha en la que se produce el acceso';
   COMMENT ON COLUMN "UVIRTUAL"."LOG_ACCESO"."SERVIDOR" IS 'Servidor por el que se accede';
   COMMENT ON COLUMN "UVIRTUAL"."LOG_ACCESO"."ACCESO" IS 'URL a la que se solicita el acceso';
   COMMENT ON COLUMN "UVIRTUAL"."LOG_ACCESO"."IP" IS 'Dirección IP desde la que se accede';
   COMMENT ON COLUMN "UVIRTUAL"."LOG_ACCESO"."SESION" IS 'Identificador de la sesión del usuario';
   COMMENT ON COLUMN "UVIRTUAL"."LOG_ACCESO"."USUARIO" IS 'Usuario que accede o null si es no autenticado';
   COMMENT ON COLUMN "UVIRTUAL"."LOG_ACCESO"."TIEMPO" IS 'Tiempo que se tarda en generar la respuesta';
   COMMENT ON COLUMN "UVIRTUAL"."LOG_ACCESO"."COMENTARIO" IS 'Texto que pueden poner los servlets para almacenar en el log';
   COMMENT ON COLUMN "UVIRTUAL"."LOG_ACCESO"."PARAMS" IS 'Parámetros enviados en caso de excepción';
   COMMENT ON COLUMN "UVIRTUAL"."LOG_ACCESO"."EXCEPCION" IS 'Texto con la descripción del error';
   COMMENT ON TABLE "UVIRTUAL"."LOG_ACCESO"  IS 'Tabla con los accesos a Universidad Virtual';


-- UVIRTUAL.ADM_AVISO_ROL definition

CREATE TABLE "UVIRTUAL"."ADM_AVISO_ROL" 
   (	"AVI_CODNUM" NUMBER(3,0) NOT NULL ENABLE, 
	"ROL_CODNUM" NUMBER(3,0) NOT NULL ENABLE, 
	 FOREIGN KEY ("AVI_CODNUM")
	  REFERENCES "UVIRTUAL"."ADM_AVISO_INICIO" ("CODNUM") ENABLE, 
	 FOREIGN KEY ("ROL_CODNUM")
	  REFERENCES "UVIRTUAL"."ADM_ROL" ("ROL_CODNUM") ENABLE
   );


-- UVIRTUAL.ADM_COLA_MSG definition

CREATE TABLE "UVIRTUAL"."ADM_COLA_MSG" 
   (	"MSG_ID" TIMESTAMP (6) DEFAULT systimestamp, 
	"COLA_CODALF" VARCHAR2(20) NOT NULL ENABLE, 
	"DATOS" VARCHAR2(2000), 
	"DATENV" DATE DEFAULT sysdate, 
	"DATBLOQUEO" DATE, 
	"DATFIN" DATE, 
	"NODO_CODALF" VARCHAR2(20), 
	 PRIMARY KEY ("MSG_ID"), 
	 FOREIGN KEY ("COLA_CODALF")
	  REFERENCES "UVIRTUAL"."ADM_COLA" ("COLA_CODALF") ENABLE, 
	 FOREIGN KEY ("NODO_CODALF")
	  REFERENCES "UVIRTUAL"."ADM_NODO" ("NODO_CODALF") ENABLE
   );


-- UVIRTUAL.ADM_COLA_NODO definition

CREATE TABLE "UVIRTUAL"."ADM_COLA_NODO" 
   (	"COLA_CODALF" VARCHAR2(20), 
	"NODO_CODALF" VARCHAR2(20), 
	 PRIMARY KEY ("COLA_CODALF", "NODO_CODALF"), 
	 FOREIGN KEY ("COLA_CODALF")
	  REFERENCES "UVIRTUAL"."ADM_COLA" ("COLA_CODALF") ENABLE, 
	 FOREIGN KEY ("NODO_CODALF")
	  REFERENCES "UVIRTUAL"."ADM_NODO" ("NODO_CODALF") ENABLE
   );


-- UVIRTUAL.ADM_CPSCOLAMSGNODO definition

CREATE TABLE "UVIRTUAL"."ADM_CPSCOLAMSGNODO" 
   (	"MSG_ID" TIMESTAMP (6), 
	"NODO_CODALF" VARCHAR2(20), 
	"DATBLOQUEO" DATE, 
	"DATFIN" DATE, 
	 PRIMARY KEY ("MSG_ID", "NODO_CODALF"), 
	 FOREIGN KEY ("NODO_CODALF")
	  REFERENCES "UVIRTUAL"."ADM_NODO" ("NODO_CODALF") ENABLE
   );


-- UVIRTUAL.ADM_MENU_DOM definition

CREATE TABLE "UVIRTUAL"."ADM_MENU_DOM" 
   (	"MNU_CODNUM" NUMBER(6,0), 
	"DOM_CODALF" VARCHAR2(200), 
	 CONSTRAINT "PK_MNU_DOM" PRIMARY KEY ("MNU_CODNUM", "DOM_CODALF"), 
	 CONSTRAINT "FK_MNU_DOM_DOM" FOREIGN KEY ("DOM_CODALF")
	  REFERENCES "UVIRTUAL"."ADM_DOM" ("DOM_CODALF") ENABLE, 
	 CONSTRAINT "FK_MNU_DOM_MNU" FOREIGN KEY ("MNU_CODNUM")
	  REFERENCES "UVIRTUAL"."ADM_MENU" ("MNU_CODNUM") ENABLE
   );

COMMENT ON COLUMN "UVIRTUAL"."ADM_MENU_DOM"."MNU_CODNUM" IS 'Código interno del menú';
   COMMENT ON COLUMN "UVIRTUAL"."ADM_MENU_DOM"."DOM_CODALF" IS 'Identificador del dominio';
   COMMENT ON TABLE "UVIRTUAL"."ADM_MENU_DOM"  IS 'Roles que tienen acceso a un menú o acción';


-- UVIRTUAL.ADM_MENU_IDM definition

CREATE TABLE "UVIRTUAL"."ADM_MENU_IDM" 
   (	"MNU_CODNUM" NUMBER(6,0), 
	"IDM_CODALF" VARCHAR2(5), 
	"DESCRIPCION" VARCHAR2(100), 
	 CONSTRAINT "PK_MNU_IDM" PRIMARY KEY ("MNU_CODNUM", "IDM_CODALF"), 
	 CONSTRAINT "FK_MNU_IDM_IDM" FOREIGN KEY ("IDM_CODALF")
	  REFERENCES "UVIRTUAL"."ADM_IDIOMA" ("IDM_CODALF") ENABLE, 
	 CONSTRAINT "FK_MNU_IDM_MNU" FOREIGN KEY ("MNU_CODNUM")
	  REFERENCES "UVIRTUAL"."ADM_MENU" ("MNU_CODNUM") ENABLE
   );

COMMENT ON COLUMN "UVIRTUAL"."ADM_MENU_IDM"."MNU_CODNUM" IS 'Código interno del menú';
   COMMENT ON COLUMN "UVIRTUAL"."ADM_MENU_IDM"."IDM_CODALF" IS 'Código del idioma';
   COMMENT ON COLUMN "UVIRTUAL"."ADM_MENU_IDM"."DESCRIPCION" IS 'Texto del menú en el idioma';
   COMMENT ON TABLE "UVIRTUAL"."ADM_MENU_IDM"  IS 'Texto de las acciones en los distintos idiomas';


-- UVIRTUAL.ADM_MENU_RED definition

CREATE TABLE "UVIRTUAL"."ADM_MENU_RED" 
   (	"MNU_CODNUM" NUMBER(6,0), 
	"RED" VARCHAR2(100), 
	"DESCRIPCION" VARCHAR2(200), 
	"FLG_DESACT" VARCHAR2(1), 
	 CONSTRAINT "CK_ADM_MNU_RED_DES" CHECK (flg_desact IN ('S', 'N')) ENABLE, 
	 CONSTRAINT "PK_MNU_RED" PRIMARY KEY ("MNU_CODNUM", "RED"), 
	 CONSTRAINT "FK_MNU_RED_MNU" FOREIGN KEY ("MNU_CODNUM")
	  REFERENCES "UVIRTUAL"."ADM_MENU" ("MNU_CODNUM") ENABLE
   );

COMMENT ON COLUMN "UVIRTUAL"."ADM_MENU_RED"."MNU_CODNUM" IS 'Código interno del menú';
   COMMENT ON COLUMN "UVIRTUAL"."ADM_MENU_RED"."RED" IS 'Red con acceso por ejemplo 0.0.0.0/0';
   COMMENT ON COLUMN "UVIRTUAL"."ADM_MENU_RED"."DESCRIPCION" IS 'Descripción del acceso';
   COMMENT ON COLUMN "UVIRTUAL"."ADM_MENU_RED"."FLG_DESACT" IS 'Desactivar temporalmente este acceso';
   COMMENT ON TABLE "UVIRTUAL"."ADM_MENU_RED"  IS 'Filtro de redes con accesos al menú';


-- UVIRTUAL.ADM_MENU_ROL definition

CREATE TABLE "UVIRTUAL"."ADM_MENU_ROL" 
   (	"MNU_CODNUM" NUMBER(6,0), 
	"ROL_CODNUM" NUMBER(3,0), 
	"FLG_DESACT" VARCHAR2(1), 
	"FLG_ADMIN" VARCHAR2(1), 
	 CONSTRAINT "CK_ADM_MNU_ROL_ADM" CHECK (flg_admin IN ('S', 'N')) ENABLE, 
	 CONSTRAINT "CK_ADM_MNU_ROL_DES" CHECK (flg_desact IN ('S', 'N')) ENABLE, 
	 CONSTRAINT "PK_MNU_ROL" PRIMARY KEY ("MNU_CODNUM", "ROL_CODNUM"), 
	 CONSTRAINT "FK_MNU_ROL_MNU" FOREIGN KEY ("MNU_CODNUM")
	  REFERENCES "UVIRTUAL"."ADM_MENU" ("MNU_CODNUM") ENABLE, 
	 CONSTRAINT "FK_MNU_ROL_ROL" FOREIGN KEY ("ROL_CODNUM")
	  REFERENCES "UVIRTUAL"."ADM_ROL" ("ROL_CODNUM") ENABLE
   );

COMMENT ON COLUMN "UVIRTUAL"."ADM_MENU_ROL"."MNU_CODNUM" IS 'Código interno del menú';
   COMMENT ON COLUMN "UVIRTUAL"."ADM_MENU_ROL"."ROL_CODNUM" IS 'Código internl del rol';
   COMMENT ON COLUMN "UVIRTUAL"."ADM_MENU_ROL"."FLG_DESACT" IS 'Indica si el acceso está temporalmente desactivado';
   COMMENT ON COLUMN "UVIRTUAL"."ADM_MENU_ROL"."FLG_ADMIN" IS 'Indica si el rol tiene acceso de administrador (siempre accede)';
   COMMENT ON TABLE "UVIRTUAL"."ADM_MENU_ROL"  IS 'Roles que tienen acceso a un menú o acción';


-- UVIRTUAL.ADM_MENU_SIS definition

CREATE TABLE "UVIRTUAL"."ADM_MENU_SIS" 
   (	"MNU_CODNUM" NUMBER(6,0) NOT NULL ENABLE, 
	"SIS_CODALF" VARCHAR2(10) NOT NULL ENABLE, 
	 CONSTRAINT "PK_MNU_SIS" PRIMARY KEY ("MNU_CODNUM", "SIS_CODALF"), 
	 CONSTRAINT "FK_MNU_SIS_MNU" FOREIGN KEY ("MNU_CODNUM")
	  REFERENCES "UVIRTUAL"."ADM_MENU" ("MNU_CODNUM") ENABLE, 
	 CONSTRAINT "FK_MNU_SIS_SIS" FOREIGN KEY ("SIS_CODALF")
	  REFERENCES "UVIRTUAL"."ADM_SISTEMA" ("SIS_CODALF") ENABLE
   );

COMMENT ON COLUMN "UVIRTUAL"."ADM_MENU_SIS"."MNU_CODNUM" IS 'Código del menú';
   COMMENT ON COLUMN "UVIRTUAL"."ADM_MENU_SIS"."SIS_CODALF" IS 'Código del sistema';
   COMMENT ON TABLE "UVIRTUAL"."ADM_MENU_SIS"  IS 'Tabla de relación entre un menú y los sistemas que utiliza';


-- UVIRTUAL.ADM_ROL_DOM definition

CREATE TABLE "UVIRTUAL"."ADM_ROL_DOM" 
   (	"ROL_CODNUM" NUMBER(3,0) NOT NULL ENABLE, 
	"DOM_CODALF" VARCHAR2(200) NOT NULL ENABLE, 
	 CONSTRAINT "PK_ROL_DOM" PRIMARY KEY ("ROL_CODNUM", "DOM_CODALF"), 
	 CONSTRAINT "FK_ROL_DOM_DOM" FOREIGN KEY ("DOM_CODALF")
	  REFERENCES "UVIRTUAL"."ADM_DOM" ("DOM_CODALF") ENABLE, 
	 CONSTRAINT "FK_ROL_DOM_ROL" FOREIGN KEY ("ROL_CODNUM")
	  REFERENCES "UVIRTUAL"."ADM_ROL" ("ROL_CODNUM") ENABLE
   );

COMMENT ON COLUMN "UVIRTUAL"."ADM_ROL_DOM"."ROL_CODNUM" IS 'Código del rol al que se limita el dominio';
   COMMENT ON COLUMN "UVIRTUAL"."ADM_ROL_DOM"."DOM_CODALF" IS 'Código del dominio que puede tener el rol';
   COMMENT ON TABLE "UVIRTUAL"."ADM_ROL_DOM"  IS 'Tabla con la relación de roles y los dominios que pueden tener dicho rol';


-- UVIRTUAL.ADM_USUARIO_ROL definition

CREATE TABLE "UVIRTUAL"."ADM_USUARIO_ROL" 
   (	"USERUID" VARCHAR2(100), 
	"ROL_CODNUM" NUMBER(3,0), 
	"FLG_ADMIN" VARCHAR2(1), 
	 CONSTRAINT "CK_USR_ROL_ADM" CHECK (flg_admin IN ('S', 'N')) ENABLE, 
	 CONSTRAINT "PK_USR_ROL" PRIMARY KEY ("USERUID", "ROL_CODNUM"), 
	 CONSTRAINT "FK_USR_ROL_ROL" FOREIGN KEY ("ROL_CODNUM")
	  REFERENCES "UVIRTUAL"."ADM_ROL" ("ROL_CODNUM") ENABLE
   );

COMMENT ON COLUMN "UVIRTUAL"."ADM_USUARIO_ROL"."USERUID" IS 'UID del usuario';
   COMMENT ON COLUMN "UVIRTUAL"."ADM_USUARIO_ROL"."ROL_CODNUM" IS 'Código interno del rol';
   COMMENT ON COLUMN "UVIRTUAL"."ADM_USUARIO_ROL"."FLG_ADMIN" IS 'El usuario administra este rol';
   COMMENT ON TABLE "UVIRTUAL"."ADM_USUARIO_ROL"  IS 'Asignaciones manuales usuario-rol';


-- UVIRTUAL.AVISO_APLICACION definition

CREATE TABLE "UVIRTUAL"."AVISO_APLICACION" 
   (	"CODALF" VARCHAR2(3), 
	"DESCRIPCION" VARCHAR2(100) NOT NULL ENABLE, 
	"TIPO_CONTACTO" VARCHAR2(3) NOT NULL ENABLE, 
	"PRIORIDAD" NUMBER(6,0) DEFAULT 999 NOT NULL ENABLE, 
	"BLNBLOQUEADA" VARCHAR2(1) DEFAULT 'N' NOT NULL ENABLE, 
	"VERIFICACION" VARCHAR2(1) DEFAULT 'S', 
	"CAMPO" VARCHAR2(3) DEFAULT 'COR' NOT NULL ENABLE, 
	 CONSTRAINT "AVISO_APLICACION_PK" PRIMARY KEY ("CODALF"), 
	 CONSTRAINT "FK_AVISO_APL_CAMPO" FOREIGN KEY ("CAMPO")
	  REFERENCES "UVIRTUAL"."AVISO_APLICACION_CAMPO" ("CODALF") ENABLE, 
	 CONSTRAINT "FK_AVISO_APL_TIPO" FOREIGN KEY ("TIPO_CONTACTO")
	  REFERENCES "UVIRTUAL"."AVISO_APLICACION_TIPO" ("CODALF") ENABLE
   );

COMMENT ON COLUMN "UVIRTUAL"."AVISO_APLICACION"."CODALF" IS 'codigo';
   COMMENT ON COLUMN "UVIRTUAL"."AVISO_APLICACION"."DESCRIPCION" IS 'descripcion';
   COMMENT ON COLUMN "UVIRTUAL"."AVISO_APLICACION"."TIPO_CONTACTO" IS 'tipo de medio de contacto';
   COMMENT ON COLUMN "UVIRTUAL"."AVISO_APLICACION"."PRIORIDAD" IS 'prioridad de la aplicación';
   COMMENT ON COLUMN "UVIRTUAL"."AVISO_APLICACION"."BLNBLOQUEADA" IS 'aplicación bloqueada';
   COMMENT ON COLUMN "UVIRTUAL"."AVISO_APLICACION"."VERIFICACION" IS 'la aplicacion requere verificacion por parte del usuario';
   COMMENT ON COLUMN "UVIRTUAL"."AVISO_APLICACION"."CAMPO" IS 'campo que usa la aplicacion para enviar mensajes';
   COMMENT ON TABLE "UVIRTUAL"."AVISO_APLICACION"  IS 'aplcicaciones que se usan para los distintos medios de contacto';


-- UVIRTUAL.AVISO_PERSONAL_ENVIO definition

CREATE TABLE "UVIRTUAL"."AVISO_PERSONAL_ENVIO" 
   (	"CODNUM" NUMBER, 
	"CUENTA_ORIGEN" VARCHAR2(75) NOT NULL ENABLE, 
	"CUENTA_DESTINO" VARCHAR2(75) NOT NULL ENABLE, 
	"ASUNTO" VARCHAR2(200), 
	"MENSAJE" VARCHAR2(4000) NOT NULL ENABLE, 
	"DATENVIO" DATE NOT NULL ENABLE, 
	"DATLECTURA" DATE, 
	"DATBORRADO" DATE, 
	"APLICACION" VARCHAR2(3), 
	"DATENVIO_APLICACION" DATE, 
	"LOG_APLICACION" VARCHAR2(4000), 
	"SOLICITUD" NUMBER, 
	 CONSTRAINT "AVISO_PERSONAL_PK" PRIMARY KEY ("CODNUM"), 
	 CONSTRAINT "FK_AVISO_APLICACION" FOREIGN KEY ("APLICACION")
	  REFERENCES "UVIRTUAL"."AVISO_APLICACION" ("CODALF") ENABLE, 
	 CONSTRAINT "FK_AVISO_PERSONAL_ENVIO_SOL" FOREIGN KEY ("SOLICITUD")
	  REFERENCES "UVIRTUAL"."AVISO_PERSONAL_SOLICITUD" ("CODNUM") ENABLE
   );

COMMENT ON COLUMN "UVIRTUAL"."AVISO_PERSONAL_ENVIO"."CODNUM" IS 'codigo';
   COMMENT ON COLUMN "UVIRTUAL"."AVISO_PERSONAL_ENVIO"."CUENTA_ORIGEN" IS 'cuenta que envia el mensaje';
   COMMENT ON COLUMN "UVIRTUAL"."AVISO_PERSONAL_ENVIO"."CUENTA_DESTINO" IS 'cuenta a la que se le envia el mensaje';
   COMMENT ON COLUMN "UVIRTUAL"."AVISO_PERSONAL_ENVIO"."ASUNTO" IS 'asunto del mensaje';
   COMMENT ON COLUMN "UVIRTUAL"."AVISO_PERSONAL_ENVIO"."MENSAJE" IS 'cuerpo del mensaje';
   COMMENT ON COLUMN "UVIRTUAL"."AVISO_PERSONAL_ENVIO"."DATENVIO" IS 'fecha en la que el usuario origen  realizo el envio';
   COMMENT ON COLUMN "UVIRTUAL"."AVISO_PERSONAL_ENVIO"."DATLECTURA" IS 'fecha en la que el usuario destino leyo el aviso en uvirtual';
   COMMENT ON COLUMN "UVIRTUAL"."AVISO_PERSONAL_ENVIO"."DATBORRADO" IS 'fecha en la que el usuario destino borro al aviso';
   COMMENT ON COLUMN "UVIRTUAL"."AVISO_PERSONAL_ENVIO"."APLICACION" IS 'aplicación por la que se envio el aviso';
   COMMENT ON COLUMN "UVIRTUAL"."AVISO_PERSONAL_ENVIO"."DATENVIO_APLICACION" IS 'fecha en la que la aplicacion realizo el envio';
   COMMENT ON COLUMN "UVIRTUAL"."AVISO_PERSONAL_ENVIO"."LOG_APLICACION" IS 'los de la aplicacion de envio';
   COMMENT ON COLUMN "UVIRTUAL"."AVISO_PERSONAL_ENVIO"."SOLICITUD" IS 'solicitud de envio';
   COMMENT ON TABLE "UVIRTUAL"."AVISO_PERSONAL_ENVIO"  IS 'Tabla de avisos personales de universidad virtual';


-- UVIRTUAL.AVISO_PREFERENCIA definition

CREATE TABLE "UVIRTUAL"."AVISO_PREFERENCIA" 
   (	"IDIDENTIFICADOR" VARCHAR2(75), 
	"APLICACION" VARCHAR2(3), 
	"PRIORIDAD" NUMBER(6,0), 
	"VERIFICADO" VARCHAR2(1) DEFAULT 'N' NOT NULL ENABLE, 
	"CODIGO_VERIFICACION" VARCHAR2(20), 
	"SELECCIONADO" VARCHAR2(1) DEFAULT 'S' NOT NULL ENABLE, 
	"MEDIO" VARCHAR2(100), 
	"DATENVIO" DATE, 
	"DATVERIFICADO" DATE, 
	"IDENTIFICADOR_EXTERNO" VARCHAR2(100), 
	 CONSTRAINT "PK_AVISO_PREFERENCIA" PRIMARY KEY ("IDIDENTIFICADOR", "APLICACION"), 
	 CONSTRAINT "UK_AVISO_PREFERENCIA_MEDIO" UNIQUE ("APLICACION", "CODIGO_VERIFICACION", "MEDIO"), 
	 CONSTRAINT "FK_AVISO_PREFERENCIA_APLICA" FOREIGN KEY ("APLICACION")
	  REFERENCES "UVIRTUAL"."AVISO_APLICACION" ("CODALF") ENABLE
   );

COMMENT ON COLUMN "UVIRTUAL"."AVISO_PREFERENCIA"."IDIDENTIFICADOR" IS 'identificador de cuenta';
   COMMENT ON COLUMN "UVIRTUAL"."AVISO_PREFERENCIA"."APLICACION" IS 'aplicacion para avisos';
   COMMENT ON COLUMN "UVIRTUAL"."AVISO_PREFERENCIA"."PRIORIDAD" IS 'prioridad de eleccion';
   COMMENT ON COLUMN "UVIRTUAL"."AVISO_PREFERENCIA"."VERIFICADO" IS 'indica si el usuario ha verificado la propiedad del medio';
   COMMENT ON COLUMN "UVIRTUAL"."AVISO_PREFERENCIA"."CODIGO_VERIFICACION" IS 'codigo temporal de verificacion';
   COMMENT ON COLUMN "UVIRTUAL"."AVISO_PREFERENCIA"."SELECCIONADO" IS 'indica si el medio esta seleccionado';
   COMMENT ON COLUMN "UVIRTUAL"."AVISO_PREFERENCIA"."MEDIO" IS 'medio al que se le ha enviado el codigo de verificacion';
   COMMENT ON COLUMN "UVIRTUAL"."AVISO_PREFERENCIA"."DATENVIO" IS 'ultima fecha de verificacion en la que se envió el codigo de verificacion';
   COMMENT ON COLUMN "UVIRTUAL"."AVISO_PREFERENCIA"."DATVERIFICADO" IS 'fecha en la que se verifico el codigo';
   COMMENT ON TABLE "UVIRTUAL"."AVISO_PREFERENCIA"  IS 'tabla que contiene los medios de contacto para un usuario';


-- UVIRTUAL.CONTROL_ACCESO_ROL definition

CREATE TABLE "UVIRTUAL"."CONTROL_ACCESO_ROL" 
   (	"USERUID" VARCHAR2(100), 
	"ROL_CODNUM" NUMBER(3,0), 
	"NOMBRE" VARCHAR2(100), 
	 CONSTRAINT "PK_CACC_ROL" PRIMARY KEY ("USERUID", "ROL_CODNUM"), 
	 CONSTRAINT "FK_CACC_ROL_ROL" FOREIGN KEY ("ROL_CODNUM")
	  REFERENCES "UVIRTUAL"."ADM_ROL" ("ROL_CODNUM") ENABLE
   );

COMMENT ON COLUMN "UVIRTUAL"."CONTROL_ACCESO_ROL"."USERUID" IS 'UID del usuario';
   COMMENT ON COLUMN "UVIRTUAL"."CONTROL_ACCESO_ROL"."ROL_CODNUM" IS 'Código interno del rol';
   COMMENT ON COLUMN "UVIRTUAL"."CONTROL_ACCESO_ROL"."NOMBRE" IS 'Nombre del usuario';
   COMMENT ON TABLE "UVIRTUAL"."CONTROL_ACCESO_ROL"  IS 'Asignaciones manuales usuario-rol';


-- UVIRTUAL.ENLACE_INDICE_ROL definition

CREATE TABLE "UVIRTUAL"."ENLACE_INDICE_ROL" 
   (	"ENLACE_CODNUM" NUMBER(3,0) NOT NULL ENABLE, 
	"ROL_CODNUM" NUMBER(3,0) NOT NULL ENABLE, 
	 CONSTRAINT "PK_ENLACE_ROL" PRIMARY KEY ("ENLACE_CODNUM", "ROL_CODNUM"), 
	 CONSTRAINT "FK_ENLACE_ROL_ENLACE" FOREIGN KEY ("ENLACE_CODNUM")
	  REFERENCES "UVIRTUAL"."ENLACE_INDICE" ("ENLACE_CODNUM") ENABLE, 
	 CONSTRAINT "FK_ENLACE_ROL_ROL" FOREIGN KEY ("ROL_CODNUM")
	  REFERENCES "UVIRTUAL"."ADM_ROL" ("ROL_CODNUM") ENABLE
   );

COMMENT ON COLUMN "UVIRTUAL"."ENLACE_INDICE_ROL"."ENLACE_CODNUM" IS 'Código único del enlace';
   COMMENT ON COLUMN "UVIRTUAL"."ENLACE_INDICE_ROL"."ROL_CODNUM" IS 'Rol con acceso';
   COMMENT ON TABLE "UVIRTUAL"."ENLACE_INDICE_ROL"  IS 'Tabla con los enlaces a mostar en función del rol';