CREATE TABLE UXXIRRHH.V_TIC_UJA
(
  TIPO_PERSONAL   VARCHAR2(50 BYTE),
  NOMBRE          VARCHAR2(50 BYTE),
  APELLIDO1       VARCHAR2(50 BYTE),
  APELLIDO2       VARCHAR2(50 BYTE),
  TIPO_DOCUMENTO  VARCHAR2(50 BYTE),
  NIF             VARCHAR2(50 BYTE),
  NIF_TRATADO     VARCHAR2(50 BYTE),
  COD_PERSONA     VARCHAR2(50 BYTE)
);

CREATE TABLE UXXIRRHH.V_LDAP_BLANCAS
(
  COD_PERSONA        NUMBER(8),
  TIPO_PERSONAL      CHAR(6 BYTE),
  TIPO_PERSONAL_DET  VARCHAR2(6 BYTE),
  NOMBRE             VARCHAR2(32 BYTE),
  APELLIDO1          VARCHAR2(33 BYTE),
  APELLIDO2          VARCHAR2(33 BYTE),
  ID_PLAZA           VARCHAR2(17 BYTE),
  DESC_PLAZA         VARCHAR2(60 BYTE),
  ID_DEPTO_UNIDAD    VARCHAR2(8 BYTE),
  DEPTO_UNIDAD       VARCHAR2(40 BYTE),
  ID_AREA_SUBUNIDAD  VARCHAR2(8 BYTE),
  AREA_SUBUNIDAD     VARCHAR2(50 BYTE),
  ID_CARGO           VARCHAR2(8 BYTE),
  DESC_CARGO         VARCHAR2(100 BYTE),
  EDIFICIO           VARCHAR2(8 BYTE),
  DESC_EDIFICIO      VARCHAR2(40 BYTE),
  LOCALIDAD          VARCHAR2(40 BYTE),
  DESPACHO           VARCHAR2(200 BYTE),
  TELEFONO           VARCHAR2(20 BYTE),
  BUZON              VARCHAR2(15 BYTE),
  MAIL               VARCHAR2(80 BYTE),
  UBICADO_SN         VARCHAR2(1 BYTE),
  DESC_CONOCIMIENTO  VARCHAR2(50 BYTE)
);

CREATE TABLE UXXIRRHH.V_INTRANET_TIPO_PERSONAL
(
  COD_PERSONA  NUMBER(8),
  PAS_SN       VARCHAR2(1 BYTE),
  UBICADO_SN   VARCHAR2(1 BYTE)
);
