CREATE TABLE UXXIAC.VUJA_NET_ACTAS_PAS_PLAN
(
  CODNUM      NUMBER(8)                         NOT NULL,
  DNIPRS      VARCHAR2(15 BYTE)                 NOT NULL,
  PLA_CODALF  VARCHAR2(4 BYTE)                  NOT NULL
);

CREATE TABLE UXXIAC.VUJA_NET_PLAASSMATR
(
  PLA_CODALF      VARCHAR2(4 BYTE),
  EXP_NUMORD      NUMBER(7),
  ALU_DNIALU      VARCHAR2(15 BYTE),
  FLGBLO          VARCHAR2(1 BYTE),
  ANY_ANYACA      VARCHAR2(7 BYTE),
  MAT_ANU_CODNUM  NUMBER(3),
  ASS_CODNUM      NUMBER(9),
  NUMMAT          NUMBER(2),
  TAS_CODALF      VARCHAR2(1 BYTE),
  GAS_CODNUM      NUMBER(2),
  CIC_NUMCIC      NUMBER(2),
  CUR_NUMCUR      NUMBER(2),
  LMA_ANU_CODNUM  NUMBER(3),
  EST_CODALF      VARCHAR2(3 BYTE),
  PLA_NOMID1      VARCHAR2(75 BYTE),
  PLA_NOMID3      VARCHAR2(75 BYTE),
  ASS_NOMID1      VARCHAR2(100 BYTE),
  ASS_NOMID3      VARCHAR2(100 BYTE)
);

CREATE TABLE UXXIAC.VUJA_NET_PLANCURSOACTUAL
(
  ALU_DNIALU  VARCHAR2(15 BYTE),
  PLA_CODALF  VARCHAR2(4 BYTE),
  NUMORD      NUMBER(7)
);