Insert into UXXIRRHH.V_TIC_UJA
   (TIPO_PERSONAL, NOMBRE, APELLIDO1, APELLIDO2, TIPO_DOCUMENTO, 
    NIF, NIF_TRATADO, COD_PERSONA)
 Values
   ('1', '1', '1', '1', '1', 
    '1', '12345678', '1');

Insert into UXXIRRHH.V_LDAP_BLANCAS
   (COD_PERSONA, TIPO_PERSONAL, TIPO_PERSONAL_DET, NOMBRE, APELLIDO1, 
    APELLIDO2, ID_PLAZA, DESC_PLAZA, ID_DEPTO_UNIDAD, DEPTO_UNIDAD, 
    ID_AREA_SUBUNIDAD, AREA_SUBUNIDAD, ID_CARGO, DESC_CARGO, EDIFICIO, 
    DESC_EDIFICIO, LOCALIDAD, DESPACHO, TELEFONO, BUZON, 
    MAIL, UBICADO_SN, DESC_CONOCIMIENTO)
 Values
   (1, '1     ', '1', '1', '1', 
    '1', '1', '1', '1', '1', 
    '1', '1', '1', '1', '1', 
    '1', '1', '1', '1', '1', 
    '1', '1', 'INGENIERIA');
    
