UPDATE (
	SELECT bepsbm.VALOR, bepmer.VALOR AS VALOR_MERITO FROM TBEP_SOL_BOL_MERITOS bepsbm
		INNER JOIN TBEP_MERITOS bepmer ON bepmer.CODNUM = bepsbm.BEPMER_CODNUM 
		INNER JOIN TBEP_ITEMSBAREMACION bepite ON bepite.CODNUM = bepmer.BEPITE_CODNUM 
		WHERE bepite.AFINIDAD IS NULL AND bepsbm.FLGVALIDADO = 'S'
)
SET VALOR = VALOR_MERITO;