INSERT INTO TBEP_PLAZAS_OFERTADAS (BEPARE_CODNUM,UID_USUARIO)
SELECT
	bepade.BEPARE_CODNUM AS BEPARE_CODNUM,
	'CARGA_INICIAL' AS UID_USUARIO
FROM TBEP_AREAS_DEPARTAMENTOS bepade
INNER JOIN TBEP_DEPARTAMENTOS bepdep ON bepdep.CODNUM = bepade.BEPDEP_CODNUM 
WHERE bepdep.DES_DEPARTAMENTO LIKE '%MATEMÁTICAS%' FETCH FIRST 4 ROWS ONLY;