INSERT INTO TBEP_DEDICACIONES (TEXTO,SUELDO,UID_USUARIO)
VALUES ('Tiempo completo',20000,'CARGA_INICIAL');
--/////////////////////
INSERT INTO TBEP_DEDICACIONES (TEXTO,SUELDO,UID_USUARIO)
VALUES ('Tiempo parcial (6 horas)',10000,'CARGA_INICIAL');