INSERT INTO TBEP_DEDICACIONES (TEXTO,SUELDO,UID_USUARIO)
VALUES ('Tiempo completo',2000,'CARGA_INICIAL');
--/////////////////////
INSERT INTO TBEP_DEDICACIONES (TEXTO,SUELDO,UID_USUARIO)
VALUES ('Tiempo parcial (6 horas)',1000,'CARGA_INICIAL');