UPDATE TBEP_CONVOCATORIAS SET FECHA_FINALIZACION = SYSDATE, ESTADO = 'FINALIZADA' WHERE DESCRIPCION = 'Convocatoria de prueba 1';
--/////////////////////
INSERT INTO TBEP_CONVOCATORIAS (DESCRIPCION, FECHACIERRE, ESTADO, NUMBOLSASMAXIMO, NUMMERITOSPORBLOQUE, UID_USUARIO)
VALUES ('Convocatoria de prueba 2', to_timestamp('2022-12-29 23:59:59', 'yyyy-mm-dd hh24:mi:ss'), 'ABIERTA', 5, 10, 'CARGA_INICIAL');