INSERT INTO TBEP_SOLICITUDES (BEPUSU_CODNUM, BEPCON_CODNUM, ESTADO, UID_USUARIO) VALUES (
	(SELECT CODNUM FROM TBEP_USUARIOS WHERE CODCUENTA = 'candidato1'),
	(SELECT CODNUM FROM TBEP_CONVOCATORIAS WHERE DESCRIPCION = 'Convocatoria de prueba 2'),
	'CERRADA', 'CARGA_INICIAL');
--/////////////////////
INSERT INTO TBEP_SOLICITUDES (BEPUSU_CODNUM, BEPCON_CODNUM, ESTADO, UID_USUARIO) VALUES (
	(SELECT CODNUM FROM TBEP_USUARIOS WHERE CODCUENTA = 'candidato3'), 
	(SELECT CODNUM FROM TBEP_CONVOCATORIAS WHERE DESCRIPCION = 'Convocatoria de prueba 2'), 
	'CERRADA', 'CARGA_INICIAL');