INSERT INTO TBEP_SOLICITUD_BOLSAS (BEPBOL_CODNUM, BEPSOL_CODNUM, UID_USUARIO)
	VALUES (2,
	(SELECT CODNUM FROM TBEP_SOLICITUDES WHERE BEPUSU_CODNUM = (SELECT CODNUM FROM TBEP_USUARIOS WHERE CODCUENTA = 'candidato1') AND BEPCON_CODNUM = (SELECT CODNUM FROM TBEP_CONVOCATORIAS WHERE DESCRIPCION = 'Convocatoria de prueba 2')),
	'CARGA_INICIAL');
--/////////////////////
INSERT INTO TBEP_SOLICITUD_BOLSAS (BEPBOL_CODNUM, BEPSOL_CODNUM, UID_USUARIO)
	VALUES (4,
	(SELECT CODNUM FROM TBEP_SOLICITUDES WHERE BEPUSU_CODNUM = (SELECT CODNUM FROM TBEP_USUARIOS WHERE CODCUENTA = 'candidato1') AND BEPCON_CODNUM = (SELECT CODNUM FROM TBEP_CONVOCATORIAS WHERE DESCRIPCION = 'Convocatoria de prueba 2')),
	'CARGA_INICIAL');
--/////////////////////
INSERT INTO TBEP_SOLICITUD_BOLSAS (BEPBOL_CODNUM, BEPSOL_CODNUM, UID_USUARIO)
	VALUES (8,
	(SELECT CODNUM FROM TBEP_SOLICITUDES WHERE BEPUSU_CODNUM = (SELECT CODNUM FROM TBEP_USUARIOS WHERE CODCUENTA = 'candidato1') AND BEPCON_CODNUM = (SELECT CODNUM FROM TBEP_CONVOCATORIAS WHERE DESCRIPCION = 'Convocatoria de prueba 2')),
	'CARGA_INICIAL');
--/////////////////////
INSERT INTO TBEP_SOLICITUD_BOLSAS (BEPBOL_CODNUM, BEPSOL_CODNUM, UID_USUARIO)
	VALUES (9,
	(SELECT CODNUM FROM TBEP_SOLICITUDES WHERE BEPUSU_CODNUM = (SELECT CODNUM FROM TBEP_USUARIOS WHERE CODCUENTA = 'candidato1') AND BEPCON_CODNUM = (SELECT CODNUM FROM TBEP_CONVOCATORIAS WHERE DESCRIPCION = 'Convocatoria de prueba 2')),
	'CARGA_INICIAL');
--/////////////////////
INSERT INTO TBEP_SOLICITUD_BOLSAS (BEPBOL_CODNUM, BEPSOL_CODNUM, UID_USUARIO)
	VALUES (2,
	(SELECT CODNUM FROM TBEP_SOLICITUDES WHERE BEPUSU_CODNUM = (SELECT CODNUM FROM TBEP_USUARIOS WHERE CODCUENTA = 'candidato3') AND BEPCON_CODNUM = (SELECT CODNUM FROM TBEP_CONVOCATORIAS WHERE DESCRIPCION = 'Convocatoria de prueba 2')),
	'CARGA_INICIAL');