INSERT INTO TBEP_SOL_BOL_MERITOS (BEPSBO_CODNUM,BEPMER_CODNUM,UID_USUARIO)
	VALUES (
	(SELECT CODNUM FROM TBEP_SOLICITUD_BOLSAS WHERE BEPSOL_CODNUM = 
		(SELECT CODNUM FROM TBEP_SOLICITUDES WHERE BEPUSU_CODNUM = 
			(SELECT CODNUM FROM TBEP_USUARIOS WHERE CODCUENTA = 'candidato1') 
		AND BEPCON_CODNUM = (SELECT CODNUM FROM TBEP_CONVOCATORIAS WHERE DESCRIPCION = 'Convocatoria de prueba 2'))
	AND BEPBOL_CODNUM = 2),
	1,
	'CARGA_INICIAL');
--/////////////////////
INSERT INTO TBEP_SOL_BOL_MERITOS (BEPSBO_CODNUM,BEPMER_CODNUM,UID_USUARIO)
	VALUES (
	(SELECT CODNUM FROM TBEP_SOLICITUD_BOLSAS WHERE BEPSOL_CODNUM = 
		(SELECT CODNUM FROM TBEP_SOLICITUDES WHERE BEPUSU_CODNUM = 
			(SELECT CODNUM FROM TBEP_USUARIOS WHERE CODCUENTA = 'candidato1') 
		AND BEPCON_CODNUM = (SELECT CODNUM FROM TBEP_CONVOCATORIAS WHERE DESCRIPCION = 'Convocatoria de prueba 2'))
	AND BEPBOL_CODNUM = 2),
	2,
	'CARGA_INICIAL');
--/////////////////////
INSERT INTO TBEP_SOL_BOL_MERITOS (BEPSBO_CODNUM,BEPMER_CODNUM,UID_USUARIO)
	VALUES (
	(SELECT CODNUM FROM TBEP_SOLICITUD_BOLSAS WHERE BEPSOL_CODNUM = 
		(SELECT CODNUM FROM TBEP_SOLICITUDES WHERE BEPUSU_CODNUM = 
			(SELECT CODNUM FROM TBEP_USUARIOS WHERE CODCUENTA = 'candidato1') 
		AND BEPCON_CODNUM = (SELECT CODNUM FROM TBEP_CONVOCATORIAS WHERE DESCRIPCION = 'Convocatoria de prueba 2'))
	AND BEPBOL_CODNUM = 2),
	3,
	'CARGA_INICIAL');
--/////////////////////
INSERT INTO TBEP_SOL_BOL_MERITOS (BEPSBO_CODNUM,BEPMER_CODNUM,UID_USUARIO)
	VALUES (
	(SELECT CODNUM FROM TBEP_SOLICITUD_BOLSAS WHERE BEPSOL_CODNUM = 
		(SELECT CODNUM FROM TBEP_SOLICITUDES WHERE BEPUSU_CODNUM = 
			(SELECT CODNUM FROM TBEP_USUARIOS WHERE CODCUENTA = 'candidato1') 
		AND BEPCON_CODNUM = (SELECT CODNUM FROM TBEP_CONVOCATORIAS WHERE DESCRIPCION = 'Convocatoria de prueba 2'))
	AND BEPBOL_CODNUM = 4),
	2,
	'CARGA_INICIAL');
--/////////////////////
INSERT INTO TBEP_SOL_BOL_MERITOS (BEPSBO_CODNUM,BEPMER_CODNUM,UID_USUARIO)
	VALUES (
	(SELECT CODNUM FROM TBEP_SOLICITUD_BOLSAS WHERE BEPSOL_CODNUM = 
		(SELECT CODNUM FROM TBEP_SOLICITUDES WHERE BEPUSU_CODNUM = 
			(SELECT CODNUM FROM TBEP_USUARIOS WHERE CODCUENTA = 'candidato1') 
		AND BEPCON_CODNUM = (SELECT CODNUM FROM TBEP_CONVOCATORIAS WHERE DESCRIPCION = 'Convocatoria de prueba 2'))
	AND BEPBOL_CODNUM = 4),
	4,
	'CARGA_INICIAL');
--/////////////////////
INSERT INTO TBEP_SOL_BOL_MERITOS (BEPSBO_CODNUM,BEPMER_CODNUM,UID_USUARIO)
	VALUES (
	(SELECT CODNUM FROM TBEP_SOLICITUD_BOLSAS WHERE BEPSOL_CODNUM = 
		(SELECT CODNUM FROM TBEP_SOLICITUDES WHERE BEPUSU_CODNUM = 
			(SELECT CODNUM FROM TBEP_USUARIOS WHERE CODCUENTA = 'candidato1') 
		AND BEPCON_CODNUM = (SELECT CODNUM FROM TBEP_CONVOCATORIAS WHERE DESCRIPCION = 'Convocatoria de prueba 2'))
	AND BEPBOL_CODNUM = 8),
	1,
	'CARGA_INICIAL');
--/////////////////////
INSERT INTO TBEP_SOL_BOL_MERITOS (BEPSBO_CODNUM,BEPMER_CODNUM,UID_USUARIO)
	VALUES (
	(SELECT CODNUM FROM TBEP_SOLICITUD_BOLSAS WHERE BEPSOL_CODNUM = 
		(SELECT CODNUM FROM TBEP_SOLICITUDES WHERE BEPUSU_CODNUM = 
			(SELECT CODNUM FROM TBEP_USUARIOS WHERE CODCUENTA = 'candidato1') 
		AND BEPCON_CODNUM = (SELECT CODNUM FROM TBEP_CONVOCATORIAS WHERE DESCRIPCION = 'Convocatoria de prueba 2'))
	AND BEPBOL_CODNUM = 8),
	5,
	'CARGA_INICIAL');
--/////////////////////
INSERT INTO TBEP_SOL_BOL_MERITOS (BEPSBO_CODNUM,BEPMER_CODNUM,UID_USUARIO)
	VALUES (
	(SELECT CODNUM FROM TBEP_SOLICITUD_BOLSAS WHERE BEPSOL_CODNUM = 
		(SELECT CODNUM FROM TBEP_SOLICITUDES WHERE BEPUSU_CODNUM = 
			(SELECT CODNUM FROM TBEP_USUARIOS WHERE CODCUENTA = 'candidato1') 
		AND BEPCON_CODNUM = (SELECT CODNUM FROM TBEP_CONVOCATORIAS WHERE DESCRIPCION = 'Convocatoria de prueba 2'))
	AND BEPBOL_CODNUM = 8),
	3,
	'CARGA_INICIAL');
--/////////////////////
INSERT INTO TBEP_SOL_BOL_MERITOS (BEPSBO_CODNUM,BEPMER_CODNUM,FLGVALIDADO,UID_USUARIO)
	VALUES (
	(SELECT CODNUM FROM TBEP_SOLICITUD_BOLSAS WHERE BEPSOL_CODNUM = 
		(SELECT CODNUM FROM TBEP_SOLICITUDES WHERE BEPUSU_CODNUM = 
			(SELECT CODNUM FROM TBEP_USUARIOS WHERE CODCUENTA = 'candidato1') 
		AND BEPCON_CODNUM = (SELECT CODNUM FROM TBEP_CONVOCATORIAS WHERE DESCRIPCION = 'Convocatoria de prueba 2'))
	AND BEPBOL_CODNUM = 2),
	9,
	'S',
	'CARGA_INICIAL');
--/////////////////////
INSERT INTO TBEP_SOL_BOL_MERITOS (BEPSBO_CODNUM,BEPMER_CODNUM,FLGVALIDADO,UID_USUARIO)
	VALUES (
	(SELECT CODNUM FROM TBEP_SOLICITUD_BOLSAS WHERE BEPSOL_CODNUM = 
		(SELECT CODNUM FROM TBEP_SOLICITUDES WHERE BEPUSU_CODNUM = 
			(SELECT CODNUM FROM TBEP_USUARIOS WHERE CODCUENTA = 'candidato1') 
		AND BEPCON_CODNUM = (SELECT CODNUM FROM TBEP_CONVOCATORIAS WHERE DESCRIPCION = 'Convocatoria de prueba 2'))
	AND BEPBOL_CODNUM = 4),
	9,
	'S',
	'CARGA_INICIAL');
--/////////////////////
INSERT INTO TBEP_SOL_BOL_MERITOS (BEPSBO_CODNUM,BEPMER_CODNUM,FLGVALIDADO,UID_USUARIO)
	VALUES (
	(SELECT CODNUM FROM TBEP_SOLICITUD_BOLSAS WHERE BEPSOL_CODNUM = 
		(SELECT CODNUM FROM TBEP_SOLICITUDES WHERE BEPUSU_CODNUM = 
			(SELECT CODNUM FROM TBEP_USUARIOS WHERE CODCUENTA = 'candidato1') 
		AND BEPCON_CODNUM = (SELECT CODNUM FROM TBEP_CONVOCATORIAS WHERE DESCRIPCION = 'Convocatoria de prueba 2'))
	AND BEPBOL_CODNUM = 2),
	16,
	'S',
	'CARGA_INICIAL');
--/////////////////////
INSERT INTO TBEP_SOL_BOL_MERITOS (BEPSBO_CODNUM,BEPMER_CODNUM,FLGVALIDADO,UID_USUARIO)
	VALUES (
	(SELECT CODNUM FROM TBEP_SOLICITUD_BOLSAS WHERE BEPSOL_CODNUM = 
		(SELECT CODNUM FROM TBEP_SOLICITUDES WHERE BEPUSU_CODNUM = 
			(SELECT CODNUM FROM TBEP_USUARIOS WHERE CODCUENTA = 'candidato1') 
		AND BEPCON_CODNUM = 2)
	AND BEPBOL_CODNUM = 4),
	16,
	'S',
	'CARGA_INICIAL');
--/////////////////////
INSERT INTO TBEP_SOL_BOL_MERITOS (BEPSBO_CODNUM,BEPMER_CODNUM,FLGVALIDADO,UID_USUARIO)
	VALUES (
	(SELECT CODNUM FROM TBEP_SOLICITUD_BOLSAS WHERE BEPSOL_CODNUM = 
		(SELECT CODNUM FROM TBEP_SOLICITUDES WHERE BEPUSU_CODNUM = 
			(SELECT CODNUM FROM TBEP_USUARIOS WHERE CODCUENTA = 'candidato1') 
		AND BEPCON_CODNUM = (SELECT CODNUM FROM TBEP_CONVOCATORIAS WHERE DESCRIPCION = 'Convocatoria de prueba 2'))
	AND BEPBOL_CODNUM = 8),
	16,
	'S',
	'CARGA_INICIAL');
--/////////////////////
INSERT INTO TBEP_SOL_BOL_MERITOS (BEPSBO_CODNUM,BEPMER_CODNUM,FLGVALIDADO,UID_USUARIO)
	VALUES (
	(SELECT CODNUM FROM TBEP_SOLICITUD_BOLSAS WHERE BEPSOL_CODNUM = 
		(SELECT CODNUM FROM TBEP_SOLICITUDES WHERE BEPUSU_CODNUM = 
			(SELECT CODNUM FROM TBEP_USUARIOS WHERE CODCUENTA = 'candidato3') 
		AND BEPCON_CODNUM = (SELECT CODNUM FROM TBEP_CONVOCATORIAS WHERE DESCRIPCION = 'Convocatoria de prueba 2'))
	AND BEPBOL_CODNUM = 2),
	10,
	'S',
	'CARGA_INICIAL');
--/////////////////////
INSERT INTO TBEP_SOL_BOL_MERITOS (BEPSBO_CODNUM,BEPMER_CODNUM,FLGVALIDADO,UID_USUARIO)
	VALUES (
	(SELECT CODNUM FROM TBEP_SOLICITUD_BOLSAS WHERE BEPSOL_CODNUM = 
		(SELECT CODNUM FROM TBEP_SOLICITUDES WHERE BEPUSU_CODNUM = 
			(SELECT CODNUM FROM TBEP_USUARIOS WHERE CODCUENTA = 'candidato3') 
		AND BEPCON_CODNUM = (SELECT CODNUM FROM TBEP_CONVOCATORIAS WHERE DESCRIPCION = 'Convocatoria de prueba 2'))
	AND BEPBOL_CODNUM = 2),
	11,
	'S',
	'CARGA_INICIAL');
--/////////////////////
INSERT INTO TBEP_SOL_BOL_MERITOS (BEPSBO_CODNUM,BEPMER_CODNUM,FLGVALIDADO,UID_USUARIO)
	VALUES (
	(SELECT CODNUM FROM TBEP_SOLICITUD_BOLSAS WHERE BEPSOL_CODNUM = 
		(SELECT CODNUM FROM TBEP_SOLICITUDES WHERE BEPUSU_CODNUM = 
			(SELECT CODNUM FROM TBEP_USUARIOS WHERE CODCUENTA = 'candidato3') 
		AND BEPCON_CODNUM = (SELECT CODNUM FROM TBEP_CONVOCATORIAS WHERE DESCRIPCION = 'Convocatoria de prueba 2'))
	AND BEPBOL_CODNUM = 2),
	12,
	'S',
	'CARGA_INICIAL');
--/////////////////////
INSERT INTO TBEP_SOL_BOL_MERITOS (BEPSBO_CODNUM,BEPMER_CODNUM,FLGVALIDADO,UID_USUARIO)
	VALUES (
	(SELECT CODNUM FROM TBEP_SOLICITUD_BOLSAS WHERE BEPSOL_CODNUM = 
		(SELECT CODNUM FROM TBEP_SOLICITUDES WHERE BEPUSU_CODNUM = 
			(SELECT CODNUM FROM TBEP_USUARIOS WHERE CODCUENTA = 'candidato3') 
		AND BEPCON_CODNUM = (SELECT CODNUM FROM TBEP_CONVOCATORIAS WHERE DESCRIPCION = 'Convocatoria de prueba 2'))
	AND BEPBOL_CODNUM = 2),
	13,
	'S',
	'CARGA_INICIAL');
--/////////////////////
INSERT INTO TBEP_SOL_BOL_MERITOS (BEPSBO_CODNUM,BEPMER_CODNUM,FLGVALIDADO,UID_USUARIO)
	VALUES (
	(SELECT CODNUM FROM TBEP_SOLICITUD_BOLSAS WHERE BEPSOL_CODNUM = 
		(SELECT CODNUM FROM TBEP_SOLICITUDES WHERE BEPUSU_CODNUM = 
			(SELECT CODNUM FROM TBEP_USUARIOS WHERE CODCUENTA = 'candidato3') 
		AND BEPCON_CODNUM = (SELECT CODNUM FROM TBEP_CONVOCATORIAS WHERE DESCRIPCION = 'Convocatoria de prueba 2'))
	AND BEPBOL_CODNUM = 2),
	14,
	'S',
	'CARGA_INICIAL');
--/////////////////////
INSERT INTO TBEP_SOL_BOL_MERITOS (BEPSBO_CODNUM,BEPMER_CODNUM,FLGVALIDADO,UID_USUARIO)
	VALUES (
	(SELECT CODNUM FROM TBEP_SOLICITUD_BOLSAS WHERE BEPSOL_CODNUM = 
		(SELECT CODNUM FROM TBEP_SOLICITUDES WHERE BEPUSU_CODNUM = 
			(SELECT CODNUM FROM TBEP_USUARIOS WHERE CODCUENTA = 'candidato3') 
		AND BEPCON_CODNUM = (SELECT CODNUM FROM TBEP_CONVOCATORIAS WHERE DESCRIPCION = 'Convocatoria de prueba 2'))
	AND BEPBOL_CODNUM = 2),
	15,
	'S',
	'CARGA_INICIAL');