CREATE TABLE VUJA_MRD_RH_CARGOS
(
  PRSNIF              VARCHAR2(16),
  ID_FAMILIA_CARGO    VARCHAR2(8)    NOT NULL,
  DES_FAMILIA_CARGO  VARCHAR2(40),
  ID_CARGO            VARCHAR2(8)    NOT NULL,
  DES_CARGO          VARCHAR2(100),
  F_INICIO_CARGO      DATE           NOT NULL,
  F_FIN_CARGO         DATE
);
