INSERT INTO TBEP_TITULACIONES (CODNUM,NOMBRE,UID_USUARIO)
VALUES (1,'Grado en Geografía e Historia','CARGA_INICIAL');
INSERT INTO TBEP_TITULACIONES (CODNUM,NOMBRE,UID_USUARIO)
VALUES (2,'Licenciatura en Filosofía y Letras (sección de Geografía)','CARGA_INICIAL');
INSERT INTO TBEP_TITULACIONES (CODNUM,NOMBRE,UID_USUARIO)
VALUES (3,'Licenciatura en Geografía','CARGA_INICIAL');
INSERT INTO TBEP_TITULACIONES (CODNUM,NOMBRE,UID_USUARIO)
VALUES (4,'Licenciatura en Geografía e Historia ','CARGA_INICIAL');
INSERT INTO TBEP_TITULACIONES (CODNUM,NOMBRE,UID_USUARIO)
VALUES (5,'Licenciatura en Humanidades','CARGA_INICIAL');
INSERT INTO TBEP_TITULACIONES (CODNUM,NOMBRE,UID_USUARIO)
VALUES (6,'Grado en Química','CARGA_INICIAL');
INSERT INTO TBEP_TITULACIONES (CODNUM,NOMBRE,UID_USUARIO)
VALUES (7,'Grado en Ciencias Ambientales','CARGA_INICIAL');
INSERT INTO TBEP_TITULACIONES (CODNUM,NOMBRE,UID_USUARIO)
VALUES (8,'Grado en Geología','CARGA_INICIAL');
INSERT INTO TBEP_TITULACIONES (CODNUM,NOMBRE,UID_USUARIO)
VALUES (9,'Grado en Ingeniería Geológica','CARGA_INICIAL');
INSERT INTO TBEP_TITULACIONES (CODNUM,NOMBRE,UID_USUARIO)
VALUES (10,'Grado en Ingeniería de Minas','CARGA_INICIAL');
INSERT INTO TBEP_TITULACIONES (CODNUM,NOMBRE,UID_USUARIO)
VALUES (11,'Licenciatura en Ciencias Ambientales','CARGA_INICIAL');
INSERT INTO TBEP_TITULACIONES (CODNUM,NOMBRE,UID_USUARIO)
VALUES (12,'Licenciatura en Geologia','CARGA_INICIAL');
INSERT INTO TBEP_TITULACIONES (CODNUM,NOMBRE,UID_USUARIO)
VALUES (13,'Ingeniería de Minas','CARGA_INICIAL');
INSERT INTO TBEP_TITULACIONES (CODNUM,NOMBRE,UID_USUARIO)
VALUES (14,'Ingeniería Geológica','CARGA_INICIAL');
INSERT INTO TBEP_TITULACIONES (CODNUM,NOMBRE,UID_USUARIO)
VALUES (15,'Licenciatura en Química','CARGA_INICIAL');
INSERT INTO TBEP_TITULACIONES (CODNUM,NOMBRE,UID_USUARIO)
VALUES (16,'Grado en Gestión y Administración Pública','CARGA_INICIAL');
INSERT INTO TBEP_TITULACIONES (CODNUM,NOMBRE,UID_USUARIO)
VALUES (17,'Licenciado en derecho y ADE','CARGA_INICIAL');
INSERT INTO TBEP_TITULACIONES (CODNUM,NOMBRE,UID_USUARIO)
VALUES (18,'Grado en Derecho y Administración de Empresas','CARGA_INICIAL');
INSERT INTO TBEP_TITULACIONES (CODNUM,NOMBRE,UID_USUARIO)
VALUES (19,'Licenciatura en Derecho','CARGA_INICIAL');
INSERT INTO TBEP_TITULACIONES (CODNUM,NOMBRE,UID_USUARIO)
VALUES (20,'Grado en Derecho','CARGA_INICIAL');
INSERT INTO TBEP_TITULACIONES (CODNUM,NOMBRE,UID_USUARIO)
VALUES (21,'Grado en Ciencias del Trabajo','CARGA_INICIAL');
INSERT INTO TBEP_TITULACIONES (CODNUM,NOMBRE,UID_USUARIO)
VALUES (22,'Licenciatura en Ciencias del Trabajo','CARGA_INICIAL');
INSERT INTO TBEP_TITULACIONES (CODNUM,NOMBRE,UID_USUARIO)
VALUES (23,'Graduado Social','CARGA_INICIAL');
INSERT INTO TBEP_TITULACIONES (CODNUM,NOMBRE,UID_USUARIO)
VALUES (24,'Diplomado en Relaciones Laborales','CARGA_INICIAL');
INSERT INTO TBEP_TITULACIONES (CODNUM,NOMBRE,UID_USUARIO)
VALUES (25,'Grado en Bellas Artes','CARGA_INICIAL');
INSERT INTO TBEP_TITULACIONES (CODNUM,NOMBRE,UID_USUARIO)
VALUES (26,'Licenciatura en Bellas Artes','CARGA_INICIAL');
INSERT INTO TBEP_TITULACIONES (CODNUM,NOMBRE,UID_USUARIO)
VALUES (27,'Graduado en ciencias de la actividad Física y del Deporte','CARGA_INICIAL');
INSERT INTO TBEP_TITULACIONES (CODNUM,NOMBRE,UID_USUARIO)
VALUES (28,'Licenciatura en Ciencias de la Actividad Física y del Deporte','CARGA_INICIAL');
INSERT INTO TBEP_TITULACIONES (CODNUM,NOMBRE,UID_USUARIO)
VALUES (29,'Grado en Educación Primaria con mención de Educación Física','CARGA_INICIAL');
INSERT INTO TBEP_TITULACIONES (CODNUM,NOMBRE,UID_USUARIO)
VALUES (30,'Diplomado en Educación Física + Máster relacionado con Actividad Física','CARGA_INICIAL');
INSERT INTO TBEP_TITULACIONES (CODNUM,NOMBRE,UID_USUARIO)
VALUES (31,'Diplomado en Educación Física + Máster en Educación Secundaria','CARGA_INICIAL');
INSERT INTO TBEP_TITULACIONES (CODNUM,NOMBRE,UID_USUARIO)
VALUES (32,'Graduado en Historia y Ciencias de la Música','CARGA_INICIAL');
INSERT INTO TBEP_TITULACIONES (CODNUM,NOMBRE,UID_USUARIO)
VALUES (33,'Titulado Superior de Conservatorio de Música','CARGA_INICIAL');
INSERT INTO TBEP_TITULACIONES (CODNUM,NOMBRE,UID_USUARIO)
VALUES (34,'Licenciatura en Musicología','CARGA_INICIAL');
INSERT INTO TBEP_TITULACIONES (CODNUM,NOMBRE,UID_USUARIO)
VALUES (35,'Licenciatura en Historia y Ciencias de la Música','CARGA_INICIAL');
INSERT INTO TBEP_TITULACIONES (CODNUM,NOMBRE,UID_USUARIO)
VALUES (36,'Licenciatura en Comunicación Audiovisual ','CARGA_INICIAL');
INSERT INTO TBEP_TITULACIONES (CODNUM,NOMBRE,UID_USUARIO)
VALUES (37,'Grado en Comunicación Audiovisual','CARGA_INICIAL');
INSERT INTO TBEP_TITULACIONES (CODNUM,NOMBRE,UID_USUARIO)
VALUES (38,'Grado Oficial Universitario Cinematografía y artes audiovisuales','CARGA_INICIAL');
INSERT INTO TBEP_TITULACIONES (CODNUM,NOMBRE,UID_USUARIO)
VALUES (39,'Grado en Artes Visuales y Danza','CARGA_INICIAL');
INSERT INTO TBEP_TITULACIONES (CODNUM,NOMBRE,UID_USUARIO)
VALUES (40,'Licenciatura en filología hispánica','CARGA_INICIAL');
INSERT INTO TBEP_TITULACIONES (CODNUM,NOMBRE,UID_USUARIO)
VALUES (41,'Grado en filología hispánica','CARGA_INICIAL');
INSERT INTO TBEP_TITULACIONES (CODNUM,NOMBRE,UID_USUARIO)
VALUES (42,'Licenciatura en filosofía y letras (sección de filología hispánica)','CARGA_INICIAL');
INSERT INTO TBEP_TITULACIONES (CODNUM,NOMBRE,UID_USUARIO)
VALUES (43,'Grado en Matemáticas','CARGA_INICIAL');
INSERT INTO TBEP_TITULACIONES (CODNUM,NOMBRE,UID_USUARIO)
VALUES (44,'Licenciatura en Matemáticas','CARGA_INICIAL');
INSERT INTO TBEP_TITULACIONES (CODNUM,NOMBRE,UID_USUARIO)
VALUES (45,'Grado en Biología','CARGA_INICIAL');
INSERT INTO TBEP_TITULACIONES (CODNUM,NOMBRE,UID_USUARIO)
VALUES (46,'Licenciatura en Biología','CARGA_INICIAL');
INSERT INTO TBEP_TITULACIONES (CODNUM,NOMBRE,UID_USUARIO)
VALUES (47,'Licenciatura en Física','CARGA_INICIAL');
INSERT INTO TBEP_TITULACIONES (CODNUM,NOMBRE,UID_USUARIO)
VALUES (48,'Grado en Física','CARGA_INICIAL');
INSERT INTO TBEP_TITULACIONES (CODNUM,NOMBRE,UID_USUARIO)
VALUES (49,'Grado en Humanidades','CARGA_INICIAL');
INSERT INTO TBEP_TITULACIONES (CODNUM,NOMBRE,UID_USUARIO)
VALUES (50,'Grado en historia','CARGA_INICIAL');
INSERT INTO TBEP_TITULACIONES (CODNUM,NOMBRE,UID_USUARIO)
VALUES (51,'Grado en historia del arte','CARGA_INICIAL');
INSERT INTO TBEP_TITULACIONES (CODNUM,NOMBRE,UID_USUARIO)
VALUES (52,'Grado en Geografía','CARGA_INICIAL');
INSERT INTO TBEP_TITULACIONES (CODNUM,NOMBRE,UID_USUARIO)
VALUES (53,'Licenciatura en Historia','CARGA_INICIAL');
INSERT INTO TBEP_TITULACIONES (CODNUM,NOMBRE,UID_USUARIO)
VALUES (54,'Licenciatura en Historia del Arte','CARGA_INICIAL');
INSERT INTO TBEP_TITULACIONES (CODNUM,NOMBRE,UID_USUARIO)
VALUES (55,'Grado en Pedagogía','CARGA_INICIAL');
INSERT INTO TBEP_TITULACIONES (CODNUM,NOMBRE,UID_USUARIO)
VALUES (56,'Grado en Psicopedagogía','CARGA_INICIAL');
INSERT INTO TBEP_TITULACIONES (CODNUM,NOMBRE,UID_USUARIO)
VALUES (57,'Licenciatura en Ciencias de la Educación','CARGA_INICIAL');
INSERT INTO TBEP_TITULACIONES (CODNUM,NOMBRE,UID_USUARIO)
VALUES (58,'Licenciatura en Filosofía y Ciencias de la Educación: Sección Ciencias de la Educación, en todas sus especialidades.','CARGA_INICIAL');
INSERT INTO TBEP_TITULACIONES (CODNUM,NOMBRE,UID_USUARIO)
VALUES (59,'Licenciatura en Filosofía y Letras: División Filosofía y Ciencias de la Educación. Sección Ciencias de la Educación. Sección de Pedagogía. ','CARGA_INICIAL');
INSERT INTO TBEP_TITULACIONES (CODNUM,NOMBRE,UID_USUARIO)
VALUES (60,'Licenciatura en Filosofía y Ciencias de la Educación (Sección Pedagogía)','CARGA_INICIAL');
INSERT INTO TBEP_TITULACIONES (CODNUM,NOMBRE,UID_USUARIO)
VALUES (61,'Licenciatura en Pedagogía','CARGA_INICIAL');
INSERT INTO TBEP_TITULACIONES (CODNUM,NOMBRE,UID_USUARIO)
VALUES (62,'Licenciatura en Psicopedagogía','CARGA_INICIAL');
INSERT INTO TBEP_TITULACIONES (CODNUM,NOMBRE,UID_USUARIO)
VALUES (63,'Grado en Economía','CARGA_INICIAL');
INSERT INTO TBEP_TITULACIONES (CODNUM,NOMBRE,UID_USUARIO)
VALUES (64,'Licenciatura en Administración y Dirección de Empresas','CARGA_INICIAL');
INSERT INTO TBEP_TITULACIONES (CODNUM,NOMBRE,UID_USUARIO)
VALUES (65,'Licenciatura en Ciencias Económicas y Empresariales','CARGA_INICIAL');
INSERT INTO TBEP_TITULACIONES (CODNUM,NOMBRE,UID_USUARIO)
VALUES (66,'Diplomado en Ciencias Empresariales más Máster en Economía y Empresa (Se considerará dicho Máster cuando el 75 por 100 de los créditos impartidos correspondan a las asignaturas específicas de Economía y Empresa)','CARGA_INICIAL');
INSERT INTO TBEP_TITULACIONES (CODNUM,NOMBRE,UID_USUARIO)
VALUES (67,'Grado en Administración y Dirección de Empresas','CARGA_INICIAL');
INSERT INTO TBEP_TITULACIONES (CODNUM,NOMBRE,UID_USUARIO)
VALUES (68,'Grado en Finanzas y Contabilidad','CARGA_INICIAL');
INSERT INTO TBEP_TITULACIONES (CODNUM,NOMBRE,UID_USUARIO)
VALUES (69,'Licenciado en Educación Física o Ciencias de la Actividad Física y del Deporte','CARGA_INICIAL');
INSERT INTO TBEP_TITULACIONES (CODNUM,NOMBRE,UID_USUARIO)
VALUES (70,'Graduado en Ciencias de la Actividad Física y el Deporte','CARGA_INICIAL');
INSERT INTO TBEP_TITULACIONES (CODNUM,NOMBRE,UID_USUARIO)
VALUES (71,'Diplomado en Enfermería','CARGA_INICIAL');
INSERT INTO TBEP_TITULACIONES (CODNUM,NOMBRE,UID_USUARIO)
VALUES (72,'Grado en Enfermería','CARGA_INICIAL');
INSERT INTO TBEP_TITULACIONES (CODNUM,NOMBRE,UID_USUARIO)
VALUES (73,'Diplomado en Estadística','CARGA_INICIAL');
INSERT INTO TBEP_TITULACIONES (CODNUM,NOMBRE,UID_USUARIO)
VALUES (74,'Licenciado en matemáticas especialidad estadística e investigación operativa','CARGA_INICIAL');
INSERT INTO TBEP_TITULACIONES (CODNUM,NOMBRE,UID_USUARIO)
VALUES (75,'Grado en Estadística','CARGA_INICIAL');
INSERT INTO TBEP_TITULACIONES (CODNUM,NOMBRE,UID_USUARIO)
VALUES (76,'Grado en Matemáticas con Máster de al menos 18 créditos de asignaturas propias de Estadística e Investigación Operativa','CARGA_INICIAL');
INSERT INTO TBEP_TITULACIONES (CODNUM,NOMBRE,UID_USUARIO)
VALUES (77,'Grado en Estadística y Empresa','CARGA_INICIAL');
INSERT INTO TBEP_TITULACIONES (CODNUM,NOMBRE,UID_USUARIO)
VALUES (78,'Licenciatura en Ciencias y Técnicas  Estadísticas','CARGA_INICIAL');
INSERT INTO TBEP_TITULACIONES (CODNUM,NOMBRE,UID_USUARIO)
VALUES (79,'Grado en Medicina y Cirugía','CARGA_INICIAL');
INSERT INTO TBEP_TITULACIONES (CODNUM,NOMBRE,UID_USUARIO)
VALUES (80,'Licenciatura en Medicina y Cirugia','CARGA_INICIAL');
INSERT INTO TBEP_TITULACIONES (CODNUM,NOMBRE,UID_USUARIO)
VALUES (81,'Grado en Fisioterapia','CARGA_INICIAL');
INSERT INTO TBEP_TITULACIONES (CODNUM,NOMBRE,UID_USUARIO)
VALUES (82,'Diplomado en Fisioterapia','CARGA_INICIAL');
INSERT INTO TBEP_TITULACIONES (CODNUM,NOMBRE,UID_USUARIO)
VALUES (83,'Grado en Estudios Árabes e Islámicos','CARGA_INICIAL');
INSERT INTO TBEP_TITULACIONES (CODNUM,NOMBRE,UID_USUARIO)
VALUES (84,'Licenciatura en Filología Semítica (Árabo-Islámica)','CARGA_INICIAL');
INSERT INTO TBEP_TITULACIONES (CODNUM,NOMBRE,UID_USUARIO)
VALUES (85,'Grado en Filología Árabe','CARGA_INICIAL');
INSERT INTO TBEP_TITULACIONES (CODNUM,NOMBRE,UID_USUARIO)
VALUES (86,'Licenciatura en Filología Árabe','CARGA_INICIAL');
INSERT INTO TBEP_TITULACIONES (CODNUM,NOMBRE,UID_USUARIO)
VALUES (87,'Grado en Estudios Semíticos e Islámicos','CARGA_INICIAL');
INSERT INTO TBEP_TITULACIONES (CODNUM,NOMBRE,UID_USUARIO)
VALUES (88,'Máster en Ingeniería de Minas','CARGA_INICIAL');
INSERT INTO TBEP_TITULACIONES (CODNUM,NOMBRE,UID_USUARIO)
VALUES (89,'Licenciatura en Antropología Social','CARGA_INICIAL');
INSERT INTO TBEP_TITULACIONES (CODNUM,NOMBRE,UID_USUARIO)
VALUES (90,'Grado en Antropología Social','CARGA_INICIAL');
INSERT INTO TBEP_TITULACIONES (CODNUM,NOMBRE,UID_USUARIO)
VALUES (91,'Grado en Ingeniería Civil','CARGA_INICIAL');
INSERT INTO TBEP_TITULACIONES (CODNUM,NOMBRE,UID_USUARIO)
VALUES (92,'Grado en Ingeniería Industrial','CARGA_INICIAL');
INSERT INTO TBEP_TITULACIONES (CODNUM,NOMBRE,UID_USUARIO)
VALUES (93,'Ingeniero Técnico en Obras Públicas','CARGA_INICIAL');
INSERT INTO TBEP_TITULACIONES (CODNUM,NOMBRE,UID_USUARIO)
VALUES (94,'Ingeniero Técnico Industrial','CARGA_INICIAL');
INSERT INTO TBEP_TITULACIONES (CODNUM,NOMBRE,UID_USUARIO)
VALUES (95,'Ingeniero Técnico de Minas','CARGA_INICIAL');
INSERT INTO TBEP_TITULACIONES (CODNUM,NOMBRE,UID_USUARIO)
VALUES (96,'Ingeniero en Caminos, Canales y Puertos','CARGA_INICIAL');
INSERT INTO TBEP_TITULACIONES (CODNUM,NOMBRE,UID_USUARIO)
VALUES (97,'Ingeniero Industrial','CARGA_INICIAL');
INSERT INTO TBEP_TITULACIONES (CODNUM,NOMBRE,UID_USUARIO)
VALUES (98,'Licenciatura en Humanidades con perfil de Arqueología','CARGA_INICIAL');
INSERT INTO TBEP_TITULACIONES (CODNUM,NOMBRE,UID_USUARIO)
VALUES (99,'Licenciado en historia del arte (mención/itinerario arqueología)','CARGA_INICIAL');
INSERT INTO TBEP_TITULACIONES (CODNUM,NOMBRE,UID_USUARIO)
VALUES (100,'Grado historia del arte (mención/itinerario arqueología)','CARGA_INICIAL');
INSERT INTO TBEP_TITULACIONES (CODNUM,NOMBRE,UID_USUARIO)
VALUES (101,'Grado en Arqueología','CARGA_INICIAL');
INSERT INTO TBEP_TITULACIONES (CODNUM,NOMBRE,UID_USUARIO)
VALUES (102,'Licenciatura en Filología Española','CARGA_INICIAL');
INSERT INTO TBEP_TITULACIONES (CODNUM,NOMBRE,UID_USUARIO)
VALUES (103,'Licenciatura en Filosofía y Letras (sección de Filología Española)','CARGA_INICIAL');
INSERT INTO TBEP_TITULACIONES (CODNUM,NOMBRE,UID_USUARIO)
VALUES (104,'Licenciatura en Filología Francesa','CARGA_INICIAL');
INSERT INTO TBEP_TITULACIONES (CODNUM,NOMBRE,UID_USUARIO)
VALUES (105,'Grado en Estudios Franceses','CARGA_INICIAL');
INSERT INTO TBEP_TITULACIONES (CODNUM,NOMBRE,UID_USUARIO)
VALUES (106,'Grado en Traducción e Interpretación (Primera lengua: Francés)','CARGA_INICIAL');
INSERT INTO TBEP_TITULACIONES (CODNUM,NOMBRE,UID_USUARIO)
VALUES (107,'Licenciatura de Traducción e Interpretación (Primera lengua: Francés)','CARGA_INICIAL');
INSERT INTO TBEP_TITULACIONES (CODNUM,NOMBRE,UID_USUARIO)
VALUES (108,'Licenciatura en Filología Clásica','CARGA_INICIAL');
INSERT INTO TBEP_TITULACIONES (CODNUM,NOMBRE,UID_USUARIO)
VALUES (109,'Grado en Filología Clásica','CARGA_INICIAL');
INSERT INTO TBEP_TITULACIONES (CODNUM,NOMBRE,UID_USUARIO)
VALUES (110,'Licenciatura en Filología Inglesa','CARGA_INICIAL');
INSERT INTO TBEP_TITULACIONES (CODNUM,NOMBRE,UID_USUARIO)
VALUES (111,'Grado en Estudios Ingleses','CARGA_INICIAL');
INSERT INTO TBEP_TITULACIONES (CODNUM,NOMBRE,UID_USUARIO)
VALUES (112,'Máster Universitario en Ingeniería Informática','CARGA_INICIAL');
INSERT INTO TBEP_TITULACIONES (CODNUM,NOMBRE,UID_USUARIO)
VALUES (113,'Ingeniería en Informática','CARGA_INICIAL');
INSERT INTO TBEP_TITULACIONES (CODNUM,NOMBRE,UID_USUARIO)
VALUES (114,'Grado en Ciencias Políticas y de la Administración','CARGA_INICIAL');
INSERT INTO TBEP_TITULACIONES (CODNUM,NOMBRE,UID_USUARIO)
VALUES (115,'Grado en Ciencias Políticas','CARGA_INICIAL');
INSERT INTO TBEP_TITULACIONES (CODNUM,NOMBRE,UID_USUARIO)
VALUES (116,'Licenciatura en Ciencias Políticas','CARGA_INICIAL');
INSERT INTO TBEP_TITULACIONES (CODNUM,NOMBRE,UID_USUARIO)
VALUES (117,'Licenciatura en Filosofía','CARGA_INICIAL');
INSERT INTO TBEP_TITULACIONES (CODNUM,NOMBRE,UID_USUARIO)
VALUES (118,'Grado en Filosofía','CARGA_INICIAL');
INSERT INTO TBEP_TITULACIONES (CODNUM,NOMBRE,UID_USUARIO)
VALUES (119,'Licenciatura en Bioquímica','CARGA_INICIAL');
INSERT INTO TBEP_TITULACIONES (CODNUM,NOMBRE,UID_USUARIO)
VALUES (120,'Grado en Veterinaria','CARGA_INICIAL');
INSERT INTO TBEP_TITULACIONES (CODNUM,NOMBRE,UID_USUARIO)
VALUES (121,'Grado en Bioquímica','CARGA_INICIAL');
INSERT INTO TBEP_TITULACIONES (CODNUM,NOMBRE,UID_USUARIO)
VALUES (122,'Licenciatura en Farmacia','CARGA_INICIAL');
INSERT INTO TBEP_TITULACIONES (CODNUM,NOMBRE,UID_USUARIO)
VALUES (123,'Licenciatura en Veterinaria','CARGA_INICIAL');
INSERT INTO TBEP_TITULACIONES (CODNUM,NOMBRE,UID_USUARIO)
VALUES (124,'Grado en Farmacia','CARGA_INICIAL');
INSERT INTO TBEP_TITULACIONES (CODNUM,NOMBRE,UID_USUARIO)
VALUES (125,'Grado en Medicina','CARGA_INICIAL');
INSERT INTO TBEP_TITULACIONES (CODNUM,NOMBRE,UID_USUARIO)
VALUES (126,'Licenciatura en Medicina','CARGA_INICIAL');
INSERT INTO TBEP_TITULACIONES (CODNUM,NOMBRE,UID_USUARIO)
VALUES (127,'Licenciatura en Filosofía y Letras (sección de Historia)','CARGA_INICIAL');
INSERT INTO TBEP_TITULACIONES (CODNUM,NOMBRE,UID_USUARIO)
VALUES (128,'Licenciatura en Geografía e Historia (Historia del Arte)','CARGA_INICIAL');
INSERT INTO TBEP_TITULACIONES (CODNUM,NOMBRE,UID_USUARIO)
VALUES (129,'Licenciatura en Humanidades con perfil en Historia del Arte','CARGA_INICIAL');
INSERT INTO TBEP_TITULACIONES (CODNUM,NOMBRE,UID_USUARIO)
VALUES (130,'Grado en Biomedicina','CARGA_INICIAL');
INSERT INTO TBEP_TITULACIONES (CODNUM,NOMBRE,UID_USUARIO)
VALUES (131,'Máster en Arquitectura','CARGA_INICIAL');
INSERT INTO TBEP_TITULACIONES (CODNUM,NOMBRE,UID_USUARIO)
VALUES (132,'Máster en Ingeniería de Caminos, Canales y Puertos','CARGA_INICIAL');
INSERT INTO TBEP_TITULACIONES (CODNUM,NOMBRE,UID_USUARIO)
VALUES (133,'Arquitectura','CARGA_INICIAL');
INSERT INTO TBEP_TITULACIONES (CODNUM,NOMBRE,UID_USUARIO)
VALUES (134,'Máster en Ingeniería Industrial','CARGA_INICIAL');
INSERT INTO TBEP_TITULACIONES (CODNUM,NOMBRE,UID_USUARIO)
VALUES (135,'Máster en Ingeniería de Telecomunicación','CARGA_INICIAL');
INSERT INTO TBEP_TITULACIONES (CODNUM,NOMBRE,UID_USUARIO)
VALUES (136,'Máster en Mecatrónica','CARGA_INICIAL');
INSERT INTO TBEP_TITULACIONES (CODNUM,NOMBRE,UID_USUARIO)
VALUES (137,'Máster en Ingeniería Electrónica, Robótica y Automática','CARGA_INICIAL');
INSERT INTO TBEP_TITULACIONES (CODNUM,NOMBRE,UID_USUARIO)
VALUES (138,'Ingeniero de Telecomunicación','CARGA_INICIAL');
INSERT INTO TBEP_TITULACIONES (CODNUM,NOMBRE,UID_USUARIO)
VALUES (139,'Ingeniero Químico','CARGA_INICIAL');
INSERT INTO TBEP_TITULACIONES (CODNUM,NOMBRE,UID_USUARIO)
VALUES (140,'Grado en Ingeniería Química Industrial','CARGA_INICIAL');
INSERT INTO TBEP_TITULACIONES (CODNUM,NOMBRE,UID_USUARIO)
VALUES (141,'Licenciatura en Ciencias Químicas','CARGA_INICIAL');
INSERT INTO TBEP_TITULACIONES (CODNUM,NOMBRE,UID_USUARIO)
VALUES (142,'Licenciatura en Lingüística','CARGA_INICIAL');
INSERT INTO TBEP_TITULACIONES (CODNUM,NOMBRE,UID_USUARIO)
VALUES (143,'Grado en Linguistica','CARGA_INICIAL');
INSERT INTO TBEP_TITULACIONES (CODNUM,NOMBRE,UID_USUARIO)
VALUES (144,'Licenciatura en filología románica','CARGA_INICIAL');
INSERT INTO TBEP_TITULACIONES (CODNUM,NOMBRE,UID_USUARIO)
VALUES (145,'Grado en teoría de la literatura y literatura comparada','CARGA_INICIAL');
INSERT INTO TBEP_TITULACIONES (CODNUM,NOMBRE,UID_USUARIO)
VALUES (146,'Licenciatura en teoría de la literatura y literatura comparada','CARGA_INICIAL');
INSERT INTO TBEP_TITULACIONES (CODNUM,NOMBRE,UID_USUARIO)
VALUES (147,'Grado en Filología Románica','CARGA_INICIAL');
INSERT INTO TBEP_TITULACIONES (CODNUM,NOMBRE,UID_USUARIO)
VALUES (148,'Doctor en Matemáticas','CARGA_INICIAL');
INSERT INTO TBEP_TITULACIONES (CODNUM,NOMBRE,UID_USUARIO)
VALUES (149,'Grado en Biotecnología','CARGA_INICIAL');
INSERT INTO TBEP_TITULACIONES (CODNUM,NOMBRE,UID_USUARIO)
VALUES (150,'Licenciatura en Química especialidad en Bioquímica','CARGA_INICIAL');
INSERT INTO TBEP_TITULACIONES (CODNUM,NOMBRE,UID_USUARIO)
VALUES (151,'Máster en Ingeniería Aeronáutica','CARGA_INICIAL');
INSERT INTO TBEP_TITULACIONES (CODNUM,NOMBRE,UID_USUARIO)
VALUES (152,'Ingeniero Aeronáutico','CARGA_INICIAL');
INSERT INTO TBEP_TITULACIONES (CODNUM,NOMBRE,UID_USUARIO)
VALUES (153,'Grado en Psicología','CARGA_INICIAL');
INSERT INTO TBEP_TITULACIONES (CODNUM,NOMBRE,UID_USUARIO)
VALUES (154,'Licenciatura en Filosofía y Ciencias de la Educación Sección: Psicología','CARGA_INICIAL');
INSERT INTO TBEP_TITULACIONES (CODNUM,NOMBRE,UID_USUARIO)
VALUES (155,'Licenciatura en Psicología','CARGA_INICIAL');
INSERT INTO TBEP_TITULACIONES (CODNUM,NOMBRE,UID_USUARIO)
VALUES (156,'Grado en Ingeniería de Tecnologías Mineras','CARGA_INICIAL');
INSERT INTO TBEP_TITULACIONES (CODNUM,NOMBRE,UID_USUARIO)
VALUES (157,'Licenciatura en Ciencias Políticas y de la Administración','CARGA_INICIAL');
INSERT INTO TBEP_TITULACIONES (CODNUM,NOMBRE,UID_USUARIO)
VALUES (158,'Diplomado en Gestión y Administración Pública','CARGA_INICIAL');
INSERT INTO TBEP_TITULACIONES (CODNUM,NOMBRE,UID_USUARIO)
VALUES (159,'Grado en Ciencias Políticas y Sociología','CARGA_INICIAL');
INSERT INTO TBEP_TITULACIONES (CODNUM,NOMBRE,UID_USUARIO)
VALUES (160,'Licenciatura en Ciencias Políticas y Sociologia','CARGA_INICIAL');
INSERT INTO TBEP_TITULACIONES (CODNUM,NOMBRE,UID_USUARIO)
VALUES (161,'Grado Ingeniero Químico','CARGA_INICIAL');
INSERT INTO TBEP_TITULACIONES (CODNUM,NOMBRE,UID_USUARIO)
VALUES (162,'Grado en Sociología','CARGA_INICIAL');
INSERT INTO TBEP_TITULACIONES (CODNUM,NOMBRE,UID_USUARIO)
VALUES (163,'Licenciado en Sociología','CARGA_INICIAL');
INSERT INTO TBEP_TITULACIONES (CODNUM,NOMBRE,UID_USUARIO)
VALUES (164,'Máster en Física','CARGA_INICIAL');
INSERT INTO TBEP_TITULACIONES (CODNUM,NOMBRE,UID_USUARIO)
VALUES (165,'Máster en Ingeniería Electrónica','CARGA_INICIAL');
INSERT INTO TBEP_TITULACIONES (CODNUM,NOMBRE,UID_USUARIO)
VALUES (166,'Máster en Sistemas Electrónicos','CARGA_INICIAL');
INSERT INTO TBEP_TITULACIONES (CODNUM,NOMBRE,UID_USUARIO)
VALUES (167,'Ingeniería Electrónica','CARGA_INICIAL');
INSERT INTO TBEP_TITULACIONES (CODNUM,NOMBRE,UID_USUARIO)
VALUES (168,'Máster en Teoría de la Literatura y Literatura Comparada','CARGA_INICIAL');
INSERT INTO TBEP_TITULACIONES (CODNUM,NOMBRE,UID_USUARIO)
VALUES (169,'Doctor con programa de doctorado en Teoría de la Literatura y Literatura Comparada','CARGA_INICIAL');
INSERT INTO TBEP_TITULACIONES (CODNUM,NOMBRE,UID_USUARIO)
VALUES (170,'Grado en Trabajo Social','CARGA_INICIAL');
INSERT INTO TBEP_TITULACIONES (CODNUM,NOMBRE,UID_USUARIO)
VALUES (171,'Diplomado en Trabajo Social','CARGA_INICIAL');
INSERT INTO TBEP_TITULACIONES (CODNUM,NOMBRE,UID_USUARIO)
VALUES (172,'Grado en marketing','CARGA_INICIAL');
INSERT INTO TBEP_TITULACIONES (CODNUM,NOMBRE,UID_USUARIO)
VALUES (173,'Licenciatura en Investigación y Técnicas de Mercados','CARGA_INICIAL');
INSERT INTO TBEP_TITULACIONES (CODNUM,NOMBRE,UID_USUARIO)
VALUES (174,'Licenciatura en Economía','CARGA_INICIAL');