INSERT INTO TBEP_TIT_PREFERENTES_AREA (BEPARE_CODNUM, BEPTIT_CODNUM)
VALUES (12,1);
INSERT INTO TBEP_TIT_PREFERENTES_AREA (BEPARE_CODNUM, BEPTIT_CODNUM)
VALUES (12,2);
INSERT INTO TBEP_TIT_PREFERENTES_AREA (BEPARE_CODNUM, BEPTIT_CODNUM)
VALUES (12,3);
INSERT INTO TBEP_TIT_PREFERENTES_AREA (BEPARE_CODNUM, BEPTIT_CODNUM)
VALUES (12,4);
INSERT INTO TBEP_TIT_PREFERENTES_AREA (BEPARE_CODNUM, BEPTIT_CODNUM)
VALUES (12,5);
INSERT INTO TBEP_TIT_PREFERENTES_AREA (BEPARE_CODNUM, BEPTIT_CODNUM)
VALUES (30,6);
INSERT INTO TBEP_TIT_PREFERENTES_AREA (BEPARE_CODNUM, BEPTIT_CODNUM)
VALUES (30,7);
INSERT INTO TBEP_TIT_PREFERENTES_AREA (BEPARE_CODNUM, BEPTIT_CODNUM)
VALUES (30,8);
INSERT INTO TBEP_TIT_PREFERENTES_AREA (BEPARE_CODNUM, BEPTIT_CODNUM)
VALUES (30,9);
INSERT INTO TBEP_TIT_PREFERENTES_AREA (BEPARE_CODNUM, BEPTIT_CODNUM)
VALUES (30,10);
INSERT INTO TBEP_TIT_PREFERENTES_AREA (BEPARE_CODNUM, BEPTIT_CODNUM)
VALUES (30,11);
INSERT INTO TBEP_TIT_PREFERENTES_AREA (BEPARE_CODNUM, BEPTIT_CODNUM)
VALUES (30,12);
INSERT INTO TBEP_TIT_PREFERENTES_AREA (BEPARE_CODNUM, BEPTIT_CODNUM)
VALUES (30,13);
INSERT INTO TBEP_TIT_PREFERENTES_AREA (BEPARE_CODNUM, BEPTIT_CODNUM)
VALUES (30,14);
INSERT INTO TBEP_TIT_PREFERENTES_AREA (BEPARE_CODNUM, BEPTIT_CODNUM)
VALUES (30,15);
INSERT INTO TBEP_TIT_PREFERENTES_AREA (BEPARE_CODNUM, BEPTIT_CODNUM)
VALUES (31,16);
INSERT INTO TBEP_TIT_PREFERENTES_AREA (BEPARE_CODNUM, BEPTIT_CODNUM)
VALUES (31,17);
INSERT INTO TBEP_TIT_PREFERENTES_AREA (BEPARE_CODNUM, BEPTIT_CODNUM)
VALUES (31,18);
INSERT INTO TBEP_TIT_PREFERENTES_AREA (BEPARE_CODNUM, BEPTIT_CODNUM)
VALUES (31,19);
INSERT INTO TBEP_TIT_PREFERENTES_AREA (BEPARE_CODNUM, BEPTIT_CODNUM)
VALUES (31,20);
INSERT INTO TBEP_TIT_PREFERENTES_AREA (BEPARE_CODNUM, BEPTIT_CODNUM)
VALUES (32,19);
INSERT INTO TBEP_TIT_PREFERENTES_AREA (BEPARE_CODNUM, BEPTIT_CODNUM)
VALUES (32,20);
INSERT INTO TBEP_TIT_PREFERENTES_AREA (BEPARE_CODNUM, BEPTIT_CODNUM)
VALUES (33,19);
INSERT INTO TBEP_TIT_PREFERENTES_AREA (BEPARE_CODNUM, BEPTIT_CODNUM)
VALUES (33,20);
INSERT INTO TBEP_TIT_PREFERENTES_AREA (BEPARE_CODNUM, BEPTIT_CODNUM)
VALUES (34,21);
INSERT INTO TBEP_TIT_PREFERENTES_AREA (BEPARE_CODNUM, BEPTIT_CODNUM)
VALUES (34,22);
INSERT INTO TBEP_TIT_PREFERENTES_AREA (BEPARE_CODNUM, BEPTIT_CODNUM)
VALUES (34,23);
INSERT INTO TBEP_TIT_PREFERENTES_AREA (BEPARE_CODNUM, BEPTIT_CODNUM)
VALUES (34,19);
INSERT INTO TBEP_TIT_PREFERENTES_AREA (BEPARE_CODNUM, BEPTIT_CODNUM)
VALUES (34,20);
INSERT INTO TBEP_TIT_PREFERENTES_AREA (BEPARE_CODNUM, BEPTIT_CODNUM)
VALUES (34,24);
INSERT INTO TBEP_TIT_PREFERENTES_AREA (BEPARE_CODNUM, BEPTIT_CODNUM)
VALUES (35,19);
INSERT INTO TBEP_TIT_PREFERENTES_AREA (BEPARE_CODNUM, BEPTIT_CODNUM)
VALUES (35,20);
INSERT INTO TBEP_TIT_PREFERENTES_AREA (BEPARE_CODNUM, BEPTIT_CODNUM)
VALUES (36,19);
INSERT INTO TBEP_TIT_PREFERENTES_AREA (BEPARE_CODNUM, BEPTIT_CODNUM)
VALUES (36,20);
INSERT INTO TBEP_TIT_PREFERENTES_AREA (BEPARE_CODNUM, BEPTIT_CODNUM)
VALUES (37,19);
INSERT INTO TBEP_TIT_PREFERENTES_AREA (BEPARE_CODNUM, BEPTIT_CODNUM)
VALUES (37,20);
INSERT INTO TBEP_TIT_PREFERENTES_AREA (BEPARE_CODNUM, BEPTIT_CODNUM)
VALUES (38,19);
INSERT INTO TBEP_TIT_PREFERENTES_AREA (BEPARE_CODNUM, BEPTIT_CODNUM)
VALUES (38,20);
INSERT INTO TBEP_TIT_PREFERENTES_AREA (BEPARE_CODNUM, BEPTIT_CODNUM)
VALUES (39,19);
INSERT INTO TBEP_TIT_PREFERENTES_AREA (BEPARE_CODNUM, BEPTIT_CODNUM)
VALUES (39,20);
INSERT INTO TBEP_TIT_PREFERENTES_AREA (BEPARE_CODNUM, BEPTIT_CODNUM)
VALUES (40,19);
INSERT INTO TBEP_TIT_PREFERENTES_AREA (BEPARE_CODNUM, BEPTIT_CODNUM)
VALUES (40,20);
INSERT INTO TBEP_TIT_PREFERENTES_AREA (BEPARE_CODNUM, BEPTIT_CODNUM)
VALUES (41,19);
INSERT INTO TBEP_TIT_PREFERENTES_AREA (BEPARE_CODNUM, BEPTIT_CODNUM)
VALUES (41,20);
INSERT INTO TBEP_TIT_PREFERENTES_AREA (BEPARE_CODNUM, BEPTIT_CODNUM)
VALUES (42,19);
INSERT INTO TBEP_TIT_PREFERENTES_AREA (BEPARE_CODNUM, BEPTIT_CODNUM)
VALUES (42,20);
INSERT INTO TBEP_TIT_PREFERENTES_AREA (BEPARE_CODNUM, BEPTIT_CODNUM)
VALUES (43,25);
INSERT INTO TBEP_TIT_PREFERENTES_AREA (BEPARE_CODNUM, BEPTIT_CODNUM)
VALUES (43,26);
INSERT INTO TBEP_TIT_PREFERENTES_AREA (BEPARE_CODNUM, BEPTIT_CODNUM)
VALUES (44,27);
INSERT INTO TBEP_TIT_PREFERENTES_AREA (BEPARE_CODNUM, BEPTIT_CODNUM)
VALUES (44,28);
INSERT INTO TBEP_TIT_PREFERENTES_AREA (BEPARE_CODNUM, BEPTIT_CODNUM)
VALUES (44,29);
INSERT INTO TBEP_TIT_PREFERENTES_AREA (BEPARE_CODNUM, BEPTIT_CODNUM)
VALUES (44,30);
INSERT INTO TBEP_TIT_PREFERENTES_AREA (BEPARE_CODNUM, BEPTIT_CODNUM)
VALUES (44,31);
INSERT INTO TBEP_TIT_PREFERENTES_AREA (BEPARE_CODNUM, BEPTIT_CODNUM)
VALUES (45,32);
INSERT INTO TBEP_TIT_PREFERENTES_AREA (BEPARE_CODNUM, BEPTIT_CODNUM)
VALUES (45,33);
INSERT INTO TBEP_TIT_PREFERENTES_AREA (BEPARE_CODNUM, BEPTIT_CODNUM)
VALUES (45,34);
INSERT INTO TBEP_TIT_PREFERENTES_AREA (BEPARE_CODNUM, BEPTIT_CODNUM)
VALUES (45,35);
INSERT INTO TBEP_TIT_PREFERENTES_AREA (BEPARE_CODNUM, BEPTIT_CODNUM)
VALUES (46,25);
INSERT INTO TBEP_TIT_PREFERENTES_AREA (BEPARE_CODNUM, BEPTIT_CODNUM)
VALUES (46,36);
INSERT INTO TBEP_TIT_PREFERENTES_AREA (BEPARE_CODNUM, BEPTIT_CODNUM)
VALUES (46,26);
INSERT INTO TBEP_TIT_PREFERENTES_AREA (BEPARE_CODNUM, BEPTIT_CODNUM)
VALUES (46,37);
INSERT INTO TBEP_TIT_PREFERENTES_AREA (BEPARE_CODNUM, BEPTIT_CODNUM)
VALUES (46,38);
INSERT INTO TBEP_TIT_PREFERENTES_AREA (BEPARE_CODNUM, BEPTIT_CODNUM)
VALUES (46,39);
INSERT INTO TBEP_TIT_PREFERENTES_AREA (BEPARE_CODNUM, BEPTIT_CODNUM)
VALUES (47,40);
INSERT INTO TBEP_TIT_PREFERENTES_AREA (BEPARE_CODNUM, BEPTIT_CODNUM)
VALUES (47,41);
INSERT INTO TBEP_TIT_PREFERENTES_AREA (BEPARE_CODNUM, BEPTIT_CODNUM)
VALUES (47,42);
INSERT INTO TBEP_TIT_PREFERENTES_AREA (BEPARE_CODNUM, BEPTIT_CODNUM)
VALUES (48,43);
INSERT INTO TBEP_TIT_PREFERENTES_AREA (BEPARE_CODNUM, BEPTIT_CODNUM)
VALUES (48,44);
INSERT INTO TBEP_TIT_PREFERENTES_AREA (BEPARE_CODNUM, BEPTIT_CODNUM)
VALUES (49,45);
INSERT INTO TBEP_TIT_PREFERENTES_AREA (BEPARE_CODNUM, BEPTIT_CODNUM)
VALUES (49,46);
INSERT INTO TBEP_TIT_PREFERENTES_AREA (BEPARE_CODNUM, BEPTIT_CODNUM)
VALUES (49,47);
INSERT INTO TBEP_TIT_PREFERENTES_AREA (BEPARE_CODNUM, BEPTIT_CODNUM)
VALUES (49,48);
INSERT INTO TBEP_TIT_PREFERENTES_AREA (BEPARE_CODNUM, BEPTIT_CODNUM)
VALUES (49,6);
INSERT INTO TBEP_TIT_PREFERENTES_AREA (BEPARE_CODNUM, BEPTIT_CODNUM)
VALUES (49,7);
INSERT INTO TBEP_TIT_PREFERENTES_AREA (BEPARE_CODNUM, BEPTIT_CODNUM)
VALUES (49,8);
INSERT INTO TBEP_TIT_PREFERENTES_AREA (BEPARE_CODNUM, BEPTIT_CODNUM)
VALUES (49,11);
INSERT INTO TBEP_TIT_PREFERENTES_AREA (BEPARE_CODNUM, BEPTIT_CODNUM)
VALUES (49,12);
INSERT INTO TBEP_TIT_PREFERENTES_AREA (BEPARE_CODNUM, BEPTIT_CODNUM)
VALUES (49,15);
INSERT INTO TBEP_TIT_PREFERENTES_AREA (BEPARE_CODNUM, BEPTIT_CODNUM)
VALUES (50,49);
INSERT INTO TBEP_TIT_PREFERENTES_AREA (BEPARE_CODNUM, BEPTIT_CODNUM)
VALUES (50,50);
INSERT INTO TBEP_TIT_PREFERENTES_AREA (BEPARE_CODNUM, BEPTIT_CODNUM)
VALUES (50,51);
INSERT INTO TBEP_TIT_PREFERENTES_AREA (BEPARE_CODNUM, BEPTIT_CODNUM)
VALUES (50,52);
INSERT INTO TBEP_TIT_PREFERENTES_AREA (BEPARE_CODNUM, BEPTIT_CODNUM)
VALUES (50,53);
INSERT INTO TBEP_TIT_PREFERENTES_AREA (BEPARE_CODNUM, BEPTIT_CODNUM)
VALUES (50,54);
INSERT INTO TBEP_TIT_PREFERENTES_AREA (BEPARE_CODNUM, BEPTIT_CODNUM)
VALUES (50,5);
INSERT INTO TBEP_TIT_PREFERENTES_AREA (BEPARE_CODNUM, BEPTIT_CODNUM)
VALUES (50,3);
INSERT INTO TBEP_TIT_PREFERENTES_AREA (BEPARE_CODNUM, BEPTIT_CODNUM)
VALUES (51,55);
INSERT INTO TBEP_TIT_PREFERENTES_AREA (BEPARE_CODNUM, BEPTIT_CODNUM)
VALUES (51,56);
INSERT INTO TBEP_TIT_PREFERENTES_AREA (BEPARE_CODNUM, BEPTIT_CODNUM)
VALUES (51,57);
INSERT INTO TBEP_TIT_PREFERENTES_AREA (BEPARE_CODNUM, BEPTIT_CODNUM)
VALUES (51,58);
INSERT INTO TBEP_TIT_PREFERENTES_AREA (BEPARE_CODNUM, BEPTIT_CODNUM)
VALUES (51,59);
INSERT INTO TBEP_TIT_PREFERENTES_AREA (BEPARE_CODNUM, BEPTIT_CODNUM)
VALUES (51,60);
INSERT INTO TBEP_TIT_PREFERENTES_AREA (BEPARE_CODNUM, BEPTIT_CODNUM)
VALUES (51,61);
INSERT INTO TBEP_TIT_PREFERENTES_AREA (BEPARE_CODNUM, BEPTIT_CODNUM)
VALUES (51,62);
INSERT INTO TBEP_TIT_PREFERENTES_AREA (BEPARE_CODNUM, BEPTIT_CODNUM)
VALUES (53,63);
INSERT INTO TBEP_TIT_PREFERENTES_AREA (BEPARE_CODNUM, BEPTIT_CODNUM)
VALUES (53,64);
INSERT INTO TBEP_TIT_PREFERENTES_AREA (BEPARE_CODNUM, BEPTIT_CODNUM)
VALUES (53,65);
INSERT INTO TBEP_TIT_PREFERENTES_AREA (BEPARE_CODNUM, BEPTIT_CODNUM)
VALUES (53,66);
INSERT INTO TBEP_TIT_PREFERENTES_AREA (BEPARE_CODNUM, BEPTIT_CODNUM)
VALUES (53,67);
INSERT INTO TBEP_TIT_PREFERENTES_AREA (BEPARE_CODNUM, BEPTIT_CODNUM)
VALUES (53,68);
INSERT INTO TBEP_TIT_PREFERENTES_AREA (BEPARE_CODNUM, BEPTIT_CODNUM)
VALUES (53,174);
INSERT INTO TBEP_TIT_PREFERENTES_AREA (BEPARE_CODNUM, BEPTIT_CODNUM)
VALUES (54,63);
INSERT INTO TBEP_TIT_PREFERENTES_AREA (BEPARE_CODNUM, BEPTIT_CODNUM)
VALUES (54,64);
INSERT INTO TBEP_TIT_PREFERENTES_AREA (BEPARE_CODNUM, BEPTIT_CODNUM)
VALUES (54,65);
INSERT INTO TBEP_TIT_PREFERENTES_AREA (BEPARE_CODNUM, BEPTIT_CODNUM)
VALUES (54,67);
INSERT INTO TBEP_TIT_PREFERENTES_AREA (BEPARE_CODNUM, BEPTIT_CODNUM)
VALUES (54,68);
INSERT INTO TBEP_TIT_PREFERENTES_AREA (BEPARE_CODNUM, BEPTIT_CODNUM)
VALUES (54,174);
INSERT INTO TBEP_TIT_PREFERENTES_AREA (BEPARE_CODNUM, BEPTIT_CODNUM)
VALUES (55,7);
INSERT INTO TBEP_TIT_PREFERENTES_AREA (BEPARE_CODNUM, BEPTIT_CODNUM)
VALUES (55,8);
INSERT INTO TBEP_TIT_PREFERENTES_AREA (BEPARE_CODNUM, BEPTIT_CODNUM)
VALUES (55,9);
INSERT INTO TBEP_TIT_PREFERENTES_AREA (BEPARE_CODNUM, BEPTIT_CODNUM)
VALUES (55,11);
INSERT INTO TBEP_TIT_PREFERENTES_AREA (BEPARE_CODNUM, BEPTIT_CODNUM)
VALUES (55,12);
INSERT INTO TBEP_TIT_PREFERENTES_AREA (BEPARE_CODNUM, BEPTIT_CODNUM)
VALUES (55,14);
INSERT INTO TBEP_TIT_PREFERENTES_AREA (BEPARE_CODNUM, BEPTIT_CODNUM)
VALUES (56,69);
INSERT INTO TBEP_TIT_PREFERENTES_AREA (BEPARE_CODNUM, BEPTIT_CODNUM)
VALUES (56,70);
INSERT INTO TBEP_TIT_PREFERENTES_AREA (BEPARE_CODNUM, BEPTIT_CODNUM)
VALUES (57,71);
INSERT INTO TBEP_TIT_PREFERENTES_AREA (BEPARE_CODNUM, BEPTIT_CODNUM)
VALUES (57,72);
INSERT INTO TBEP_TIT_PREFERENTES_AREA (BEPARE_CODNUM, BEPTIT_CODNUM)
VALUES (58,73);
INSERT INTO TBEP_TIT_PREFERENTES_AREA (BEPARE_CODNUM, BEPTIT_CODNUM)
VALUES (58,74);
INSERT INTO TBEP_TIT_PREFERENTES_AREA (BEPARE_CODNUM, BEPTIT_CODNUM)
VALUES (58,75);
INSERT INTO TBEP_TIT_PREFERENTES_AREA (BEPARE_CODNUM, BEPTIT_CODNUM)
VALUES (58,76);
INSERT INTO TBEP_TIT_PREFERENTES_AREA (BEPARE_CODNUM, BEPTIT_CODNUM)
VALUES (58,77);
INSERT INTO TBEP_TIT_PREFERENTES_AREA (BEPARE_CODNUM, BEPTIT_CODNUM)
VALUES (58,78);
INSERT INTO TBEP_TIT_PREFERENTES_AREA (BEPARE_CODNUM, BEPTIT_CODNUM)
VALUES (14,45);
INSERT INTO TBEP_TIT_PREFERENTES_AREA (BEPARE_CODNUM, BEPTIT_CODNUM)
VALUES (14,46);
INSERT INTO TBEP_TIT_PREFERENTES_AREA (BEPARE_CODNUM, BEPTIT_CODNUM)
VALUES (14,70);
INSERT INTO TBEP_TIT_PREFERENTES_AREA (BEPARE_CODNUM, BEPTIT_CODNUM)
VALUES (14,28);
INSERT INTO TBEP_TIT_PREFERENTES_AREA (BEPARE_CODNUM, BEPTIT_CODNUM)
VALUES (14,79);
INSERT INTO TBEP_TIT_PREFERENTES_AREA (BEPARE_CODNUM, BEPTIT_CODNUM)
VALUES (14,80);
INSERT INTO TBEP_TIT_PREFERENTES_AREA (BEPARE_CODNUM, BEPTIT_CODNUM)
VALUES (14,81);
INSERT INTO TBEP_TIT_PREFERENTES_AREA (BEPARE_CODNUM, BEPTIT_CODNUM)
VALUES (14,82);
INSERT INTO TBEP_TIT_PREFERENTES_AREA (BEPARE_CODNUM, BEPTIT_CODNUM)
VALUES (59,7);
INSERT INTO TBEP_TIT_PREFERENTES_AREA (BEPARE_CODNUM, BEPTIT_CODNUM)
VALUES (59,8);
INSERT INTO TBEP_TIT_PREFERENTES_AREA (BEPARE_CODNUM, BEPTIT_CODNUM)
VALUES (59,9);
INSERT INTO TBEP_TIT_PREFERENTES_AREA (BEPARE_CODNUM, BEPTIT_CODNUM)
VALUES (59,10);
INSERT INTO TBEP_TIT_PREFERENTES_AREA (BEPARE_CODNUM, BEPTIT_CODNUM)
VALUES (59,11);
INSERT INTO TBEP_TIT_PREFERENTES_AREA (BEPARE_CODNUM, BEPTIT_CODNUM)
VALUES (59,12);
INSERT INTO TBEP_TIT_PREFERENTES_AREA (BEPARE_CODNUM, BEPTIT_CODNUM)
VALUES (59,13);
INSERT INTO TBEP_TIT_PREFERENTES_AREA (BEPARE_CODNUM, BEPTIT_CODNUM)
VALUES (59,14);
INSERT INTO TBEP_TIT_PREFERENTES_AREA (BEPARE_CODNUM, BEPTIT_CODNUM)
VALUES (60,83);
INSERT INTO TBEP_TIT_PREFERENTES_AREA (BEPARE_CODNUM, BEPTIT_CODNUM)
VALUES (60,84);
INSERT INTO TBEP_TIT_PREFERENTES_AREA (BEPARE_CODNUM, BEPTIT_CODNUM)
VALUES (60,85);
INSERT INTO TBEP_TIT_PREFERENTES_AREA (BEPARE_CODNUM, BEPTIT_CODNUM)
VALUES (60,86);
INSERT INTO TBEP_TIT_PREFERENTES_AREA (BEPARE_CODNUM, BEPTIT_CODNUM)
VALUES (60,87);
INSERT INTO TBEP_TIT_PREFERENTES_AREA (BEPARE_CODNUM, BEPTIT_CODNUM)
VALUES (61,88);
INSERT INTO TBEP_TIT_PREFERENTES_AREA (BEPARE_CODNUM, BEPTIT_CODNUM)
VALUES (61,13);
INSERT INTO TBEP_TIT_PREFERENTES_AREA (BEPARE_CODNUM, BEPTIT_CODNUM)
VALUES (15,89);
INSERT INTO TBEP_TIT_PREFERENTES_AREA (BEPARE_CODNUM, BEPTIT_CODNUM)
VALUES (15,90);
INSERT INTO TBEP_TIT_PREFERENTES_AREA (BEPARE_CODNUM, BEPTIT_CODNUM)
VALUES (63,91);
INSERT INTO TBEP_TIT_PREFERENTES_AREA (BEPARE_CODNUM, BEPTIT_CODNUM)
VALUES (63,92);
INSERT INTO TBEP_TIT_PREFERENTES_AREA (BEPARE_CODNUM, BEPTIT_CODNUM)
VALUES (63,93);
INSERT INTO TBEP_TIT_PREFERENTES_AREA (BEPARE_CODNUM, BEPTIT_CODNUM)
VALUES (63,94);
INSERT INTO TBEP_TIT_PREFERENTES_AREA (BEPARE_CODNUM, BEPTIT_CODNUM)
VALUES (63,95);
INSERT INTO TBEP_TIT_PREFERENTES_AREA (BEPARE_CODNUM, BEPTIT_CODNUM)
VALUES (63,96);
INSERT INTO TBEP_TIT_PREFERENTES_AREA (BEPARE_CODNUM, BEPTIT_CODNUM)
VALUES (63,97);
INSERT INTO TBEP_TIT_PREFERENTES_AREA (BEPARE_CODNUM, BEPTIT_CODNUM)
VALUES (63,13);
INSERT INTO TBEP_TIT_PREFERENTES_AREA (BEPARE_CODNUM, BEPTIT_CODNUM)
VALUES (63,10);
INSERT INTO TBEP_TIT_PREFERENTES_AREA (BEPARE_CODNUM, BEPTIT_CODNUM)
VALUES (16,1);
INSERT INTO TBEP_TIT_PREFERENTES_AREA (BEPARE_CODNUM, BEPTIT_CODNUM)
VALUES (16,98);
INSERT INTO TBEP_TIT_PREFERENTES_AREA (BEPARE_CODNUM, BEPTIT_CODNUM)
VALUES (16,99);
INSERT INTO TBEP_TIT_PREFERENTES_AREA (BEPARE_CODNUM, BEPTIT_CODNUM)
VALUES (16,50);
INSERT INTO TBEP_TIT_PREFERENTES_AREA (BEPARE_CODNUM, BEPTIT_CODNUM)
VALUES (16,100);
INSERT INTO TBEP_TIT_PREFERENTES_AREA (BEPARE_CODNUM, BEPTIT_CODNUM)
VALUES (16,101);
INSERT INTO TBEP_TIT_PREFERENTES_AREA (BEPARE_CODNUM, BEPTIT_CODNUM)
VALUES (16,4);
INSERT INTO TBEP_TIT_PREFERENTES_AREA (BEPARE_CODNUM, BEPTIT_CODNUM)
VALUES (64,102);
INSERT INTO TBEP_TIT_PREFERENTES_AREA (BEPARE_CODNUM, BEPTIT_CODNUM)
VALUES (64,103);
INSERT INTO TBEP_TIT_PREFERENTES_AREA (BEPARE_CODNUM, BEPTIT_CODNUM)
VALUES (65,104);
INSERT INTO TBEP_TIT_PREFERENTES_AREA (BEPARE_CODNUM, BEPTIT_CODNUM)
VALUES (65,105);
INSERT INTO TBEP_TIT_PREFERENTES_AREA (BEPARE_CODNUM, BEPTIT_CODNUM)
VALUES (65,106);
INSERT INTO TBEP_TIT_PREFERENTES_AREA (BEPARE_CODNUM, BEPTIT_CODNUM)
VALUES (65,107);
INSERT INTO TBEP_TIT_PREFERENTES_AREA (BEPARE_CODNUM, BEPTIT_CODNUM)
VALUES (66,108);
INSERT INTO TBEP_TIT_PREFERENTES_AREA (BEPARE_CODNUM, BEPTIT_CODNUM)
VALUES (66,109);
INSERT INTO TBEP_TIT_PREFERENTES_AREA (BEPARE_CODNUM, BEPTIT_CODNUM)
VALUES (67,110);
INSERT INTO TBEP_TIT_PREFERENTES_AREA (BEPARE_CODNUM, BEPTIT_CODNUM)
VALUES (67,111);
INSERT INTO TBEP_TIT_PREFERENTES_AREA (BEPARE_CODNUM, BEPTIT_CODNUM)
VALUES (17,112);
INSERT INTO TBEP_TIT_PREFERENTES_AREA (BEPARE_CODNUM, BEPTIT_CODNUM)
VALUES (17,113);
INSERT INTO TBEP_TIT_PREFERENTES_AREA (BEPARE_CODNUM, BEPTIT_CODNUM)
VALUES (68,108);
INSERT INTO TBEP_TIT_PREFERENTES_AREA (BEPARE_CODNUM, BEPTIT_CODNUM)
VALUES (68,109);
INSERT INTO TBEP_TIT_PREFERENTES_AREA (BEPARE_CODNUM, BEPTIT_CODNUM)
VALUES (18,47);
INSERT INTO TBEP_TIT_PREFERENTES_AREA (BEPARE_CODNUM, BEPTIT_CODNUM)
VALUES (18,48);
INSERT INTO TBEP_TIT_PREFERENTES_AREA (BEPARE_CODNUM, BEPTIT_CODNUM)
VALUES (71,114);
INSERT INTO TBEP_TIT_PREFERENTES_AREA (BEPARE_CODNUM, BEPTIT_CODNUM)
VALUES (71,115);
INSERT INTO TBEP_TIT_PREFERENTES_AREA (BEPARE_CODNUM, BEPTIT_CODNUM)
VALUES (71,116);
INSERT INTO TBEP_TIT_PREFERENTES_AREA (BEPARE_CODNUM, BEPTIT_CODNUM)
VALUES (71,19);
INSERT INTO TBEP_TIT_PREFERENTES_AREA (BEPARE_CODNUM, BEPTIT_CODNUM)
VALUES (71,20);
INSERT INTO TBEP_TIT_PREFERENTES_AREA (BEPARE_CODNUM, BEPTIT_CODNUM)
VALUES (72,117);
INSERT INTO TBEP_TIT_PREFERENTES_AREA (BEPARE_CODNUM, BEPTIT_CODNUM)
VALUES (72,118);
INSERT INTO TBEP_TIT_PREFERENTES_AREA (BEPARE_CODNUM, BEPTIT_CODNUM)
VALUES (73,47);
INSERT INTO TBEP_TIT_PREFERENTES_AREA (BEPARE_CODNUM, BEPTIT_CODNUM)
VALUES (73,48);
INSERT INTO TBEP_TIT_PREFERENTES_AREA (BEPARE_CODNUM, BEPTIT_CODNUM)
VALUES (74,47);
INSERT INTO TBEP_TIT_PREFERENTES_AREA (BEPARE_CODNUM, BEPTIT_CODNUM)
VALUES (74,48);
INSERT INTO TBEP_TIT_PREFERENTES_AREA (BEPARE_CODNUM, BEPTIT_CODNUM)
VALUES (76,45);
INSERT INTO TBEP_TIT_PREFERENTES_AREA (BEPARE_CODNUM, BEPTIT_CODNUM)
VALUES (76,46);
INSERT INTO TBEP_TIT_PREFERENTES_AREA (BEPARE_CODNUM, BEPTIT_CODNUM)
VALUES (76,119);
INSERT INTO TBEP_TIT_PREFERENTES_AREA (BEPARE_CODNUM, BEPTIT_CODNUM)
VALUES (76,27);
INSERT INTO TBEP_TIT_PREFERENTES_AREA (BEPARE_CODNUM, BEPTIT_CODNUM)
VALUES (76,28);
INSERT INTO TBEP_TIT_PREFERENTES_AREA (BEPARE_CODNUM, BEPTIT_CODNUM)
VALUES (76,120);
INSERT INTO TBEP_TIT_PREFERENTES_AREA (BEPARE_CODNUM, BEPTIT_CODNUM)
VALUES (76,121);
INSERT INTO TBEP_TIT_PREFERENTES_AREA (BEPARE_CODNUM, BEPTIT_CODNUM)
VALUES (76,79);
INSERT INTO TBEP_TIT_PREFERENTES_AREA (BEPARE_CODNUM, BEPTIT_CODNUM)
VALUES (76,122);
INSERT INTO TBEP_TIT_PREFERENTES_AREA (BEPARE_CODNUM, BEPTIT_CODNUM)
VALUES (76,80);
INSERT INTO TBEP_TIT_PREFERENTES_AREA (BEPARE_CODNUM, BEPTIT_CODNUM)
VALUES (76,123);
INSERT INTO TBEP_TIT_PREFERENTES_AREA (BEPARE_CODNUM, BEPTIT_CODNUM)
VALUES (76,124);
INSERT INTO TBEP_TIT_PREFERENTES_AREA (BEPARE_CODNUM, BEPTIT_CODNUM)
VALUES (78,81);
INSERT INTO TBEP_TIT_PREFERENTES_AREA (BEPARE_CODNUM, BEPTIT_CODNUM)
VALUES (78,82);
INSERT INTO TBEP_TIT_PREFERENTES_AREA (BEPARE_CODNUM, BEPTIT_CODNUM)
VALUES (79,63);
INSERT INTO TBEP_TIT_PREFERENTES_AREA (BEPARE_CODNUM, BEPTIT_CODNUM)
VALUES (79,64);
INSERT INTO TBEP_TIT_PREFERENTES_AREA (BEPARE_CODNUM, BEPTIT_CODNUM)
VALUES (79,65);
INSERT INTO TBEP_TIT_PREFERENTES_AREA (BEPARE_CODNUM, BEPTIT_CODNUM)
VALUES (79,66);
INSERT INTO TBEP_TIT_PREFERENTES_AREA (BEPARE_CODNUM, BEPTIT_CODNUM)
VALUES (79,67);
INSERT INTO TBEP_TIT_PREFERENTES_AREA (BEPARE_CODNUM, BEPTIT_CODNUM)
VALUES (79,68);
INSERT INTO TBEP_TIT_PREFERENTES_AREA (BEPARE_CODNUM, BEPTIT_CODNUM)
VALUES (79,174);
INSERT INTO TBEP_TIT_PREFERENTES_AREA (BEPARE_CODNUM, BEPTIT_CODNUM)
VALUES (80,125);
INSERT INTO TBEP_TIT_PREFERENTES_AREA (BEPARE_CODNUM, BEPTIT_CODNUM)
VALUES (80,46);
INSERT INTO TBEP_TIT_PREFERENTES_AREA (BEPARE_CODNUM, BEPTIT_CODNUM)
VALUES (80,119);
INSERT INTO TBEP_TIT_PREFERENTES_AREA (BEPARE_CODNUM, BEPTIT_CODNUM)
VALUES (80,126);
INSERT INTO TBEP_TIT_PREFERENTES_AREA (BEPARE_CODNUM, BEPTIT_CODNUM)
VALUES (82,7);
INSERT INTO TBEP_TIT_PREFERENTES_AREA (BEPARE_CODNUM, BEPTIT_CODNUM)
VALUES (82,8);
INSERT INTO TBEP_TIT_PREFERENTES_AREA (BEPARE_CODNUM, BEPTIT_CODNUM)
VALUES (82,9);
INSERT INTO TBEP_TIT_PREFERENTES_AREA (BEPARE_CODNUM, BEPTIT_CODNUM)
VALUES (82,10);
INSERT INTO TBEP_TIT_PREFERENTES_AREA (BEPARE_CODNUM, BEPTIT_CODNUM)
VALUES (82,11);
INSERT INTO TBEP_TIT_PREFERENTES_AREA (BEPARE_CODNUM, BEPTIT_CODNUM)
VALUES (82,12);
INSERT INTO TBEP_TIT_PREFERENTES_AREA (BEPARE_CODNUM, BEPTIT_CODNUM)
VALUES (82,13);
INSERT INTO TBEP_TIT_PREFERENTES_AREA (BEPARE_CODNUM, BEPTIT_CODNUM)
VALUES (82,14);
INSERT INTO TBEP_TIT_PREFERENTES_AREA (BEPARE_CODNUM, BEPTIT_CODNUM)
VALUES (83,7);
INSERT INTO TBEP_TIT_PREFERENTES_AREA (BEPARE_CODNUM, BEPTIT_CODNUM)
VALUES (83,8);
INSERT INTO TBEP_TIT_PREFERENTES_AREA (BEPARE_CODNUM, BEPTIT_CODNUM)
VALUES (83,9);
INSERT INTO TBEP_TIT_PREFERENTES_AREA (BEPARE_CODNUM, BEPTIT_CODNUM)
VALUES (83,10);
INSERT INTO TBEP_TIT_PREFERENTES_AREA (BEPARE_CODNUM, BEPTIT_CODNUM)
VALUES (83,11);
INSERT INTO TBEP_TIT_PREFERENTES_AREA (BEPARE_CODNUM, BEPTIT_CODNUM)
VALUES (83,12);
INSERT INTO TBEP_TIT_PREFERENTES_AREA (BEPARE_CODNUM, BEPTIT_CODNUM)
VALUES (83,13);
INSERT INTO TBEP_TIT_PREFERENTES_AREA (BEPARE_CODNUM, BEPTIT_CODNUM)
VALUES (83,14);
INSERT INTO TBEP_TIT_PREFERENTES_AREA (BEPARE_CODNUM, BEPTIT_CODNUM)
VALUES (84,1);
INSERT INTO TBEP_TIT_PREFERENTES_AREA (BEPARE_CODNUM, BEPTIT_CODNUM)
VALUES (84,2);
INSERT INTO TBEP_TIT_PREFERENTES_AREA (BEPARE_CODNUM, BEPTIT_CODNUM)
VALUES (84,3);
INSERT INTO TBEP_TIT_PREFERENTES_AREA (BEPARE_CODNUM, BEPTIT_CODNUM)
VALUES (84,4);
INSERT INTO TBEP_TIT_PREFERENTES_AREA (BEPARE_CODNUM, BEPTIT_CODNUM)
VALUES (84,5);
INSERT INTO TBEP_TIT_PREFERENTES_AREA (BEPARE_CODNUM, BEPTIT_CODNUM)
VALUES (85,1);
INSERT INTO TBEP_TIT_PREFERENTES_AREA (BEPARE_CODNUM, BEPTIT_CODNUM)
VALUES (85,2);
INSERT INTO TBEP_TIT_PREFERENTES_AREA (BEPARE_CODNUM, BEPTIT_CODNUM)
VALUES (85,3);
INSERT INTO TBEP_TIT_PREFERENTES_AREA (BEPARE_CODNUM, BEPTIT_CODNUM)
VALUES (85,4);
INSERT INTO TBEP_TIT_PREFERENTES_AREA (BEPARE_CODNUM, BEPTIT_CODNUM)
VALUES (85,5);
INSERT INTO TBEP_TIT_PREFERENTES_AREA (BEPARE_CODNUM, BEPTIT_CODNUM)
VALUES (87,127);
INSERT INTO TBEP_TIT_PREFERENTES_AREA (BEPARE_CODNUM, BEPTIT_CODNUM)
VALUES (87,4);
INSERT INTO TBEP_TIT_PREFERENTES_AREA (BEPARE_CODNUM, BEPTIT_CODNUM)
VALUES (87,53);
INSERT INTO TBEP_TIT_PREFERENTES_AREA (BEPARE_CODNUM, BEPTIT_CODNUM)
VALUES (87,5);
INSERT INTO TBEP_TIT_PREFERENTES_AREA (BEPARE_CODNUM, BEPTIT_CODNUM)
VALUES (88,1);
INSERT INTO TBEP_TIT_PREFERENTES_AREA (BEPARE_CODNUM, BEPTIT_CODNUM)
VALUES (88,4);
INSERT INTO TBEP_TIT_PREFERENTES_AREA (BEPARE_CODNUM, BEPTIT_CODNUM)
VALUES (88,5);
INSERT INTO TBEP_TIT_PREFERENTES_AREA (BEPARE_CODNUM, BEPTIT_CODNUM)
VALUES (88,53);
INSERT INTO TBEP_TIT_PREFERENTES_AREA (BEPARE_CODNUM, BEPTIT_CODNUM)
VALUES (88,127);
INSERT INTO TBEP_TIT_PREFERENTES_AREA (BEPARE_CODNUM, BEPTIT_CODNUM)
VALUES (89,51);
INSERT INTO TBEP_TIT_PREFERENTES_AREA (BEPARE_CODNUM, BEPTIT_CODNUM)
VALUES (89,128);
INSERT INTO TBEP_TIT_PREFERENTES_AREA (BEPARE_CODNUM, BEPTIT_CODNUM)
VALUES (89,54);
INSERT INTO TBEP_TIT_PREFERENTES_AREA (BEPARE_CODNUM, BEPTIT_CODNUM)
VALUES (89,129);
INSERT INTO TBEP_TIT_PREFERENTES_AREA (BEPARE_CODNUM, BEPTIT_CODNUM)
VALUES (90,17);
INSERT INTO TBEP_TIT_PREFERENTES_AREA (BEPARE_CODNUM, BEPTIT_CODNUM)
VALUES (90,18);
INSERT INTO TBEP_TIT_PREFERENTES_AREA (BEPARE_CODNUM, BEPTIT_CODNUM)
VALUES (90,19);
INSERT INTO TBEP_TIT_PREFERENTES_AREA (BEPARE_CODNUM, BEPTIT_CODNUM)
VALUES (90,20);
INSERT INTO TBEP_TIT_PREFERENTES_AREA (BEPARE_CODNUM, BEPTIT_CODNUM)
VALUES (91,63);
INSERT INTO TBEP_TIT_PREFERENTES_AREA (BEPARE_CODNUM, BEPTIT_CODNUM)
VALUES (91,64);
INSERT INTO TBEP_TIT_PREFERENTES_AREA (BEPARE_CODNUM, BEPTIT_CODNUM)
VALUES (91,65);
INSERT INTO TBEP_TIT_PREFERENTES_AREA (BEPARE_CODNUM, BEPTIT_CODNUM)
VALUES (91,66);
INSERT INTO TBEP_TIT_PREFERENTES_AREA (BEPARE_CODNUM, BEPTIT_CODNUM)
VALUES (91,67);
INSERT INTO TBEP_TIT_PREFERENTES_AREA (BEPARE_CODNUM, BEPTIT_CODNUM)
VALUES (91,68);
INSERT INTO TBEP_TIT_PREFERENTES_AREA (BEPARE_CODNUM, BEPTIT_CODNUM)
VALUES (91,174);
INSERT INTO TBEP_TIT_PREFERENTES_AREA (BEPARE_CODNUM, BEPTIT_CODNUM)
VALUES (92,1);
INSERT INTO TBEP_TIT_PREFERENTES_AREA (BEPARE_CODNUM, BEPTIT_CODNUM)
VALUES (92,98);
INSERT INTO TBEP_TIT_PREFERENTES_AREA (BEPARE_CODNUM, BEPTIT_CODNUM)
VALUES (92,99);
INSERT INTO TBEP_TIT_PREFERENTES_AREA (BEPARE_CODNUM, BEPTIT_CODNUM)
VALUES (92,50);
INSERT INTO TBEP_TIT_PREFERENTES_AREA (BEPARE_CODNUM, BEPTIT_CODNUM)
VALUES (92,51);
INSERT INTO TBEP_TIT_PREFERENTES_AREA (BEPARE_CODNUM, BEPTIT_CODNUM)
VALUES (92,101);
INSERT INTO TBEP_TIT_PREFERENTES_AREA (BEPARE_CODNUM, BEPTIT_CODNUM)
VALUES (92,4);
INSERT INTO TBEP_TIT_PREFERENTES_AREA (BEPARE_CODNUM, BEPTIT_CODNUM)
VALUES (93,1);
INSERT INTO TBEP_TIT_PREFERENTES_AREA (BEPARE_CODNUM, BEPTIT_CODNUM)
VALUES (93,49);
INSERT INTO TBEP_TIT_PREFERENTES_AREA (BEPARE_CODNUM, BEPTIT_CODNUM)
VALUES (93,50);
INSERT INTO TBEP_TIT_PREFERENTES_AREA (BEPARE_CODNUM, BEPTIT_CODNUM)
VALUES (93,127);
INSERT INTO TBEP_TIT_PREFERENTES_AREA (BEPARE_CODNUM, BEPTIT_CODNUM)
VALUES (93,4);
INSERT INTO TBEP_TIT_PREFERENTES_AREA (BEPARE_CODNUM, BEPTIT_CODNUM)
VALUES (93,53);
INSERT INTO TBEP_TIT_PREFERENTES_AREA (BEPARE_CODNUM, BEPTIT_CODNUM)
VALUES (93,5);
INSERT INTO TBEP_TIT_PREFERENTES_AREA (BEPARE_CODNUM, BEPTIT_CODNUM)
VALUES (20,125);
INSERT INTO TBEP_TIT_PREFERENTES_AREA (BEPARE_CODNUM, BEPTIT_CODNUM)
VALUES (20,45);
INSERT INTO TBEP_TIT_PREFERENTES_AREA (BEPARE_CODNUM, BEPTIT_CODNUM)
VALUES (20,46);
INSERT INTO TBEP_TIT_PREFERENTES_AREA (BEPARE_CODNUM, BEPTIT_CODNUM)
VALUES (20,120);
INSERT INTO TBEP_TIT_PREFERENTES_AREA (BEPARE_CODNUM, BEPTIT_CODNUM)
VALUES (20,130);
INSERT INTO TBEP_TIT_PREFERENTES_AREA (BEPARE_CODNUM, BEPTIT_CODNUM)
VALUES (20,126);
INSERT INTO TBEP_TIT_PREFERENTES_AREA (BEPARE_CODNUM, BEPTIT_CODNUM)
VALUES (20,123);
INSERT INTO TBEP_TIT_PREFERENTES_AREA (BEPARE_CODNUM, BEPTIT_CODNUM)
VALUES (95,131);
INSERT INTO TBEP_TIT_PREFERENTES_AREA (BEPARE_CODNUM, BEPTIT_CODNUM)
VALUES (95,132);
INSERT INTO TBEP_TIT_PREFERENTES_AREA (BEPARE_CODNUM, BEPTIT_CODNUM)
VALUES (95,133);
INSERT INTO TBEP_TIT_PREFERENTES_AREA (BEPARE_CODNUM, BEPTIT_CODNUM)
VALUES (95,96);
INSERT INTO TBEP_TIT_PREFERENTES_AREA (BEPARE_CODNUM, BEPTIT_CODNUM)
VALUES (96,97);
INSERT INTO TBEP_TIT_PREFERENTES_AREA (BEPARE_CODNUM, BEPTIT_CODNUM)
VALUES (96,134);
INSERT INTO TBEP_TIT_PREFERENTES_AREA (BEPARE_CODNUM, BEPTIT_CODNUM)
VALUES (97,135);
INSERT INTO TBEP_TIT_PREFERENTES_AREA (BEPARE_CODNUM, BEPTIT_CODNUM)
VALUES (97,136);
INSERT INTO TBEP_TIT_PREFERENTES_AREA (BEPARE_CODNUM, BEPTIT_CODNUM)
VALUES (97,137);
INSERT INTO TBEP_TIT_PREFERENTES_AREA (BEPARE_CODNUM, BEPTIT_CODNUM)
VALUES (97,138);
INSERT INTO TBEP_TIT_PREFERENTES_AREA (BEPARE_CODNUM, BEPTIT_CODNUM)
VALUES (97,97);
INSERT INTO TBEP_TIT_PREFERENTES_AREA (BEPARE_CODNUM, BEPTIT_CODNUM)
VALUES (97,134);
INSERT INTO TBEP_TIT_PREFERENTES_AREA (BEPARE_CODNUM, BEPTIT_CODNUM)
VALUES (98,97);
INSERT INTO TBEP_TIT_PREFERENTES_AREA (BEPARE_CODNUM, BEPTIT_CODNUM)
VALUES (98,134);
INSERT INTO TBEP_TIT_PREFERENTES_AREA (BEPARE_CODNUM, BEPTIT_CODNUM)
VALUES (99,97);
INSERT INTO TBEP_TIT_PREFERENTES_AREA (BEPARE_CODNUM, BEPTIT_CODNUM)
VALUES (99,134);
INSERT INTO TBEP_TIT_PREFERENTES_AREA (BEPARE_CODNUM, BEPTIT_CODNUM)
VALUES (100,139);
INSERT INTO TBEP_TIT_PREFERENTES_AREA (BEPARE_CODNUM, BEPTIT_CODNUM)
VALUES (100,6);
INSERT INTO TBEP_TIT_PREFERENTES_AREA (BEPARE_CODNUM, BEPTIT_CODNUM)
VALUES (100,140);
INSERT INTO TBEP_TIT_PREFERENTES_AREA (BEPARE_CODNUM, BEPTIT_CODNUM)
VALUES (100,7);
INSERT INTO TBEP_TIT_PREFERENTES_AREA (BEPARE_CODNUM, BEPTIT_CODNUM)
VALUES (100,11);
INSERT INTO TBEP_TIT_PREFERENTES_AREA (BEPARE_CODNUM, BEPTIT_CODNUM)
VALUES (100,141);
INSERT INTO TBEP_TIT_PREFERENTES_AREA (BEPARE_CODNUM, BEPTIT_CODNUM)
VALUES (101,138);
INSERT INTO TBEP_TIT_PREFERENTES_AREA (BEPARE_CODNUM, BEPTIT_CODNUM)
VALUES (101,135);
INSERT INTO TBEP_TIT_PREFERENTES_AREA (BEPARE_CODNUM, BEPTIT_CODNUM)
VALUES (102,46);
INSERT INTO TBEP_TIT_PREFERENTES_AREA (BEPARE_CODNUM, BEPTIT_CODNUM)
VALUES (102,122);
INSERT INTO TBEP_TIT_PREFERENTES_AREA (BEPARE_CODNUM, BEPTIT_CODNUM)
VALUES (102,80);
INSERT INTO TBEP_TIT_PREFERENTES_AREA (BEPARE_CODNUM, BEPTIT_CODNUM)
VALUES (103,40);
INSERT INTO TBEP_TIT_PREFERENTES_AREA (BEPARE_CODNUM, BEPTIT_CODNUM)
VALUES (103,41);
INSERT INTO TBEP_TIT_PREFERENTES_AREA (BEPARE_CODNUM, BEPTIT_CODNUM)
VALUES (103,42);
INSERT INTO TBEP_TIT_PREFERENTES_AREA (BEPARE_CODNUM, BEPTIT_CODNUM)
VALUES (103,142);
INSERT INTO TBEP_TIT_PREFERENTES_AREA (BEPARE_CODNUM, BEPTIT_CODNUM)
VALUES (103,143);
INSERT INTO TBEP_TIT_PREFERENTES_AREA (BEPARE_CODNUM, BEPTIT_CODNUM)
VALUES (104,112);
INSERT INTO TBEP_TIT_PREFERENTES_AREA (BEPARE_CODNUM, BEPTIT_CODNUM)
VALUES (104,113);
INSERT INTO TBEP_TIT_PREFERENTES_AREA (BEPARE_CODNUM, BEPTIT_CODNUM)
VALUES (105,40);
INSERT INTO TBEP_TIT_PREFERENTES_AREA (BEPARE_CODNUM, BEPTIT_CODNUM)
VALUES (105,41);
INSERT INTO TBEP_TIT_PREFERENTES_AREA (BEPARE_CODNUM, BEPTIT_CODNUM)
VALUES (105,42);
INSERT INTO TBEP_TIT_PREFERENTES_AREA (BEPARE_CODNUM, BEPTIT_CODNUM)
VALUES (105,142);
INSERT INTO TBEP_TIT_PREFERENTES_AREA (BEPARE_CODNUM, BEPTIT_CODNUM)
VALUES (105,143);
INSERT INTO TBEP_TIT_PREFERENTES_AREA (BEPARE_CODNUM, BEPTIT_CODNUM)
VALUES (106,40);
INSERT INTO TBEP_TIT_PREFERENTES_AREA (BEPARE_CODNUM, BEPTIT_CODNUM)
VALUES (106,41);
INSERT INTO TBEP_TIT_PREFERENTES_AREA (BEPARE_CODNUM, BEPTIT_CODNUM)
VALUES (106,42);
INSERT INTO TBEP_TIT_PREFERENTES_AREA (BEPARE_CODNUM, BEPTIT_CODNUM)
VALUES (106,144);
INSERT INTO TBEP_TIT_PREFERENTES_AREA (BEPARE_CODNUM, BEPTIT_CODNUM)
VALUES (106,145);
INSERT INTO TBEP_TIT_PREFERENTES_AREA (BEPARE_CODNUM, BEPTIT_CODNUM)
VALUES (106,146);
INSERT INTO TBEP_TIT_PREFERENTES_AREA (BEPARE_CODNUM, BEPTIT_CODNUM)
VALUES (106,147);
INSERT INTO TBEP_TIT_PREFERENTES_AREA (BEPARE_CODNUM, BEPTIT_CODNUM)
VALUES (107,97);
INSERT INTO TBEP_TIT_PREFERENTES_AREA (BEPARE_CODNUM, BEPTIT_CODNUM)
VALUES (107,134);
INSERT INTO TBEP_TIT_PREFERENTES_AREA (BEPARE_CODNUM, BEPTIT_CODNUM)
VALUES (108,148);
INSERT INTO TBEP_TIT_PREFERENTES_AREA (BEPARE_CODNUM, BEPTIT_CODNUM)
VALUES (108,43);
INSERT INTO TBEP_TIT_PREFERENTES_AREA (BEPARE_CODNUM, BEPTIT_CODNUM)
VALUES (108,44);
INSERT INTO TBEP_TIT_PREFERENTES_AREA (BEPARE_CODNUM, BEPTIT_CODNUM)
VALUES (22,139);
INSERT INTO TBEP_TIT_PREFERENTES_AREA (BEPARE_CODNUM, BEPTIT_CODNUM)
VALUES (22,125);
INSERT INTO TBEP_TIT_PREFERENTES_AREA (BEPARE_CODNUM, BEPTIT_CODNUM)
VALUES (22,45);
INSERT INTO TBEP_TIT_PREFERENTES_AREA (BEPARE_CODNUM, BEPTIT_CODNUM)
VALUES (22,46);
INSERT INTO TBEP_TIT_PREFERENTES_AREA (BEPARE_CODNUM, BEPTIT_CODNUM)
VALUES (22,119);
INSERT INTO TBEP_TIT_PREFERENTES_AREA (BEPARE_CODNUM, BEPTIT_CODNUM)
VALUES (22,120);
INSERT INTO TBEP_TIT_PREFERENTES_AREA (BEPARE_CODNUM, BEPTIT_CODNUM)
VALUES (22,121);
INSERT INTO TBEP_TIT_PREFERENTES_AREA (BEPARE_CODNUM, BEPTIT_CODNUM)
VALUES (22,149);
INSERT INTO TBEP_TIT_PREFERENTES_AREA (BEPARE_CODNUM, BEPTIT_CODNUM)
VALUES (22,130);
INSERT INTO TBEP_TIT_PREFERENTES_AREA (BEPARE_CODNUM, BEPTIT_CODNUM)
VALUES (22,122);
INSERT INTO TBEP_TIT_PREFERENTES_AREA (BEPARE_CODNUM, BEPTIT_CODNUM)
VALUES (22,126);
INSERT INTO TBEP_TIT_PREFERENTES_AREA (BEPARE_CODNUM, BEPTIT_CODNUM)
VALUES (22,150);
INSERT INTO TBEP_TIT_PREFERENTES_AREA (BEPARE_CODNUM, BEPTIT_CODNUM)
VALUES (22,123);
INSERT INTO TBEP_TIT_PREFERENTES_AREA (BEPARE_CODNUM, BEPTIT_CODNUM)
VALUES (22,124);
INSERT INTO TBEP_TIT_PREFERENTES_AREA (BEPARE_CODNUM, BEPTIT_CODNUM)
VALUES (109,151);
INSERT INTO TBEP_TIT_PREFERENTES_AREA (BEPARE_CODNUM, BEPTIT_CODNUM)
VALUES (109,152);
INSERT INTO TBEP_TIT_PREFERENTES_AREA (BEPARE_CODNUM, BEPTIT_CODNUM)
VALUES (109,97);
INSERT INTO TBEP_TIT_PREFERENTES_AREA (BEPARE_CODNUM, BEPTIT_CODNUM)
VALUES (109,134);
INSERT INTO TBEP_TIT_PREFERENTES_AREA (BEPARE_CODNUM, BEPTIT_CODNUM)
VALUES (110,97);
INSERT INTO TBEP_TIT_PREFERENTES_AREA (BEPARE_CODNUM, BEPTIT_CODNUM)
VALUES (110,134);
INSERT INTO TBEP_TIT_PREFERENTES_AREA (BEPARE_CODNUM, BEPTIT_CODNUM)
VALUES (112,71);
INSERT INTO TBEP_TIT_PREFERENTES_AREA (BEPARE_CODNUM, BEPTIT_CODNUM)
VALUES (112,72);
INSERT INTO TBEP_TIT_PREFERENTES_AREA (BEPARE_CODNUM, BEPTIT_CODNUM)
VALUES (112,120);
INSERT INTO TBEP_TIT_PREFERENTES_AREA (BEPARE_CODNUM, BEPTIT_CODNUM)
VALUES (112,79);
INSERT INTO TBEP_TIT_PREFERENTES_AREA (BEPARE_CODNUM, BEPTIT_CODNUM)
VALUES (112,122);
INSERT INTO TBEP_TIT_PREFERENTES_AREA (BEPARE_CODNUM, BEPTIT_CODNUM)
VALUES (112,80);
INSERT INTO TBEP_TIT_PREFERENTES_AREA (BEPARE_CODNUM, BEPTIT_CODNUM)
VALUES (112,123);
INSERT INTO TBEP_TIT_PREFERENTES_AREA (BEPARE_CODNUM, BEPTIT_CODNUM)
VALUES (112,124);
INSERT INTO TBEP_TIT_PREFERENTES_AREA (BEPARE_CODNUM, BEPTIT_CODNUM)
VALUES (113,153);
INSERT INTO TBEP_TIT_PREFERENTES_AREA (BEPARE_CODNUM, BEPTIT_CODNUM)
VALUES (113,154);
INSERT INTO TBEP_TIT_PREFERENTES_AREA (BEPARE_CODNUM, BEPTIT_CODNUM)
VALUES (113,155);
INSERT INTO TBEP_TIT_PREFERENTES_AREA (BEPARE_CODNUM, BEPTIT_CODNUM)
VALUES (114,55);
INSERT INTO TBEP_TIT_PREFERENTES_AREA (BEPARE_CODNUM, BEPTIT_CODNUM)
VALUES (114,56);
INSERT INTO TBEP_TIT_PREFERENTES_AREA (BEPARE_CODNUM, BEPTIT_CODNUM)
VALUES (114,57);
INSERT INTO TBEP_TIT_PREFERENTES_AREA (BEPARE_CODNUM, BEPTIT_CODNUM)
VALUES (114,58);
INSERT INTO TBEP_TIT_PREFERENTES_AREA (BEPARE_CODNUM, BEPTIT_CODNUM)
VALUES (114,59);
INSERT INTO TBEP_TIT_PREFERENTES_AREA (BEPARE_CODNUM, BEPTIT_CODNUM)
VALUES (114,60);
INSERT INTO TBEP_TIT_PREFERENTES_AREA (BEPARE_CODNUM, BEPTIT_CODNUM)
VALUES (114,61);
INSERT INTO TBEP_TIT_PREFERENTES_AREA (BEPARE_CODNUM, BEPTIT_CODNUM)
VALUES (114,62);
INSERT INTO TBEP_TIT_PREFERENTES_AREA (BEPARE_CODNUM, BEPTIT_CODNUM)
VALUES (115,45);
INSERT INTO TBEP_TIT_PREFERENTES_AREA (BEPARE_CODNUM, BEPTIT_CODNUM)
VALUES (115,46);
INSERT INTO TBEP_TIT_PREFERENTES_AREA (BEPARE_CODNUM, BEPTIT_CODNUM)
VALUES (115,122);
INSERT INTO TBEP_TIT_PREFERENTES_AREA (BEPARE_CODNUM, BEPTIT_CODNUM)
VALUES (115,124);
INSERT INTO TBEP_TIT_PREFERENTES_AREA (BEPARE_CODNUM, BEPTIT_CODNUM)
VALUES (116,32);
INSERT INTO TBEP_TIT_PREFERENTES_AREA (BEPARE_CODNUM, BEPTIT_CODNUM)
VALUES (116,33);
INSERT INTO TBEP_TIT_PREFERENTES_AREA (BEPARE_CODNUM, BEPTIT_CODNUM)
VALUES (116,34);
INSERT INTO TBEP_TIT_PREFERENTES_AREA (BEPARE_CODNUM, BEPTIT_CODNUM)
VALUES (116,35);
INSERT INTO TBEP_TIT_PREFERENTES_AREA (BEPARE_CODNUM, BEPTIT_CODNUM)
VALUES (24,139);
INSERT INTO TBEP_TIT_PREFERENTES_AREA (BEPARE_CODNUM, BEPTIT_CODNUM)
VALUES (24,6);
INSERT INTO TBEP_TIT_PREFERENTES_AREA (BEPARE_CODNUM, BEPTIT_CODNUM)
VALUES (24,140);
INSERT INTO TBEP_TIT_PREFERENTES_AREA (BEPARE_CODNUM, BEPTIT_CODNUM)
VALUES (24,156);
INSERT INTO TBEP_TIT_PREFERENTES_AREA (BEPARE_CODNUM, BEPTIT_CODNUM)
VALUES (24,91);
INSERT INTO TBEP_TIT_PREFERENTES_AREA (BEPARE_CODNUM, BEPTIT_CODNUM)
VALUES (24,92);
INSERT INTO TBEP_TIT_PREFERENTES_AREA (BEPARE_CODNUM, BEPTIT_CODNUM)
VALUES (24,141);
INSERT INTO TBEP_TIT_PREFERENTES_AREA (BEPARE_CODNUM, BEPTIT_CODNUM)
VALUES (24,96);
INSERT INTO TBEP_TIT_PREFERENTES_AREA (BEPARE_CODNUM, BEPTIT_CODNUM)
VALUES (24,97);
INSERT INTO TBEP_TIT_PREFERENTES_AREA (BEPARE_CODNUM, BEPTIT_CODNUM)
VALUES (117,64);
INSERT INTO TBEP_TIT_PREFERENTES_AREA (BEPARE_CODNUM, BEPTIT_CODNUM)
VALUES (117,65);
INSERT INTO TBEP_TIT_PREFERENTES_AREA (BEPARE_CODNUM, BEPTIT_CODNUM)
VALUES (117,174);
INSERT INTO TBEP_TIT_PREFERENTES_AREA (BEPARE_CODNUM, BEPTIT_CODNUM)
VALUES (117,67);
INSERT INTO TBEP_TIT_PREFERENTES_AREA (BEPARE_CODNUM, BEPTIT_CODNUM)
VALUES (117,68);
INSERT INTO TBEP_TIT_PREFERENTES_AREA (BEPARE_CODNUM, BEPTIT_CODNUM)
VALUES (118,153);
INSERT INTO TBEP_TIT_PREFERENTES_AREA (BEPARE_CODNUM, BEPTIT_CODNUM)
VALUES (118,154);
INSERT INTO TBEP_TIT_PREFERENTES_AREA (BEPARE_CODNUM, BEPTIT_CODNUM)
VALUES (118,155);
INSERT INTO TBEP_TIT_PREFERENTES_AREA (BEPARE_CODNUM, BEPTIT_CODNUM)
VALUES (119,1);
INSERT INTO TBEP_TIT_PREFERENTES_AREA (BEPARE_CODNUM, BEPTIT_CODNUM)
VALUES (119,98);
INSERT INTO TBEP_TIT_PREFERENTES_AREA (BEPARE_CODNUM, BEPTIT_CODNUM)
VALUES (119,99);
INSERT INTO TBEP_TIT_PREFERENTES_AREA (BEPARE_CODNUM, BEPTIT_CODNUM)
VALUES (119,50);
INSERT INTO TBEP_TIT_PREFERENTES_AREA (BEPARE_CODNUM, BEPTIT_CODNUM)
VALUES (119,100);
INSERT INTO TBEP_TIT_PREFERENTES_AREA (BEPARE_CODNUM, BEPTIT_CODNUM)
VALUES (119,101);
INSERT INTO TBEP_TIT_PREFERENTES_AREA (BEPARE_CODNUM, BEPTIT_CODNUM)
VALUES (119,4);
INSERT INTO TBEP_TIT_PREFERENTES_AREA (BEPARE_CODNUM, BEPTIT_CODNUM)
VALUES (25,16);
INSERT INTO TBEP_TIT_PREFERENTES_AREA (BEPARE_CODNUM, BEPTIT_CODNUM)
VALUES (25,114);
INSERT INTO TBEP_TIT_PREFERENTES_AREA (BEPARE_CODNUM, BEPTIT_CODNUM)
VALUES (25,157);
INSERT INTO TBEP_TIT_PREFERENTES_AREA (BEPARE_CODNUM, BEPTIT_CODNUM)
VALUES (25,115);
INSERT INTO TBEP_TIT_PREFERENTES_AREA (BEPARE_CODNUM, BEPTIT_CODNUM)
VALUES (25,116);
INSERT INTO TBEP_TIT_PREFERENTES_AREA (BEPARE_CODNUM, BEPTIT_CODNUM)
VALUES (25,158);
INSERT INTO TBEP_TIT_PREFERENTES_AREA (BEPARE_CODNUM, BEPTIT_CODNUM)
VALUES (25,159);
INSERT INTO TBEP_TIT_PREFERENTES_AREA (BEPARE_CODNUM, BEPTIT_CODNUM)
VALUES (25,160);
INSERT INTO TBEP_TIT_PREFERENTES_AREA (BEPARE_CODNUM, BEPTIT_CODNUM)
VALUES (120,13);
INSERT INTO TBEP_TIT_PREFERENTES_AREA (BEPARE_CODNUM, BEPTIT_CODNUM)
VALUES (120,88);
INSERT INTO TBEP_TIT_PREFERENTES_AREA (BEPARE_CODNUM, BEPTIT_CODNUM)
VALUES (121,91);
INSERT INTO TBEP_TIT_PREFERENTES_AREA (BEPARE_CODNUM, BEPTIT_CODNUM)
VALUES (121,92);
INSERT INTO TBEP_TIT_PREFERENTES_AREA (BEPARE_CODNUM, BEPTIT_CODNUM)
VALUES (121,10);
INSERT INTO TBEP_TIT_PREFERENTES_AREA (BEPARE_CODNUM, BEPTIT_CODNUM)
VALUES (121,93);
INSERT INTO TBEP_TIT_PREFERENTES_AREA (BEPARE_CODNUM, BEPTIT_CODNUM)
VALUES (121,94);
INSERT INTO TBEP_TIT_PREFERENTES_AREA (BEPARE_CODNUM, BEPTIT_CODNUM)
VALUES (121,95);
INSERT INTO TBEP_TIT_PREFERENTES_AREA (BEPARE_CODNUM, BEPTIT_CODNUM)
VALUES (121,96);
INSERT INTO TBEP_TIT_PREFERENTES_AREA (BEPARE_CODNUM, BEPTIT_CODNUM)
VALUES (121,97);
INSERT INTO TBEP_TIT_PREFERENTES_AREA (BEPARE_CODNUM, BEPTIT_CODNUM)
VALUES (121,13);
INSERT INTO TBEP_TIT_PREFERENTES_AREA (BEPARE_CODNUM, BEPTIT_CODNUM)
VALUES (122,153);
INSERT INTO TBEP_TIT_PREFERENTES_AREA (BEPARE_CODNUM, BEPTIT_CODNUM)
VALUES (122,154);
INSERT INTO TBEP_TIT_PREFERENTES_AREA (BEPARE_CODNUM, BEPTIT_CODNUM)
VALUES (122,155);
INSERT INTO TBEP_TIT_PREFERENTES_AREA (BEPARE_CODNUM, BEPTIT_CODNUM)
VALUES (123,153);
INSERT INTO TBEP_TIT_PREFERENTES_AREA (BEPARE_CODNUM, BEPTIT_CODNUM)
VALUES (123,154);
INSERT INTO TBEP_TIT_PREFERENTES_AREA (BEPARE_CODNUM, BEPTIT_CODNUM)
VALUES (123,155);
INSERT INTO TBEP_TIT_PREFERENTES_AREA (BEPARE_CODNUM, BEPTIT_CODNUM)
VALUES (124,153);
INSERT INTO TBEP_TIT_PREFERENTES_AREA (BEPARE_CODNUM, BEPTIT_CODNUM)
VALUES (124,154);
INSERT INTO TBEP_TIT_PREFERENTES_AREA (BEPARE_CODNUM, BEPTIT_CODNUM)
VALUES (124,155);
INSERT INTO TBEP_TIT_PREFERENTES_AREA (BEPARE_CODNUM, BEPTIT_CODNUM)
VALUES (125,153);
INSERT INTO TBEP_TIT_PREFERENTES_AREA (BEPARE_CODNUM, BEPTIT_CODNUM)
VALUES (125,154);
INSERT INTO TBEP_TIT_PREFERENTES_AREA (BEPARE_CODNUM, BEPTIT_CODNUM)
VALUES (125,155);
INSERT INTO TBEP_TIT_PREFERENTES_AREA (BEPARE_CODNUM, BEPTIT_CODNUM)
VALUES (26,112);
INSERT INTO TBEP_TIT_PREFERENTES_AREA (BEPARE_CODNUM, BEPTIT_CODNUM)
VALUES (26,113);
INSERT INTO TBEP_TIT_PREFERENTES_AREA (BEPARE_CODNUM, BEPTIT_CODNUM)
VALUES (126,139);
INSERT INTO TBEP_TIT_PREFERENTES_AREA (BEPARE_CODNUM, BEPTIT_CODNUM)
VALUES (126,6);
INSERT INTO TBEP_TIT_PREFERENTES_AREA (BEPARE_CODNUM, BEPTIT_CODNUM)
VALUES (126,161);
INSERT INTO TBEP_TIT_PREFERENTES_AREA (BEPARE_CODNUM, BEPTIT_CODNUM)
VALUES (126,122);
INSERT INTO TBEP_TIT_PREFERENTES_AREA (BEPARE_CODNUM, BEPTIT_CODNUM)
VALUES (126,15);
INSERT INTO TBEP_TIT_PREFERENTES_AREA (BEPARE_CODNUM, BEPTIT_CODNUM)
VALUES (126,124);
INSERT INTO TBEP_TIT_PREFERENTES_AREA (BEPARE_CODNUM, BEPTIT_CODNUM)
VALUES (127,139);
INSERT INTO TBEP_TIT_PREFERENTES_AREA (BEPARE_CODNUM, BEPTIT_CODNUM)
VALUES (127,6);
INSERT INTO TBEP_TIT_PREFERENTES_AREA (BEPARE_CODNUM, BEPTIT_CODNUM)
VALUES (127,161);
INSERT INTO TBEP_TIT_PREFERENTES_AREA (BEPARE_CODNUM, BEPTIT_CODNUM)
VALUES (127,122);
INSERT INTO TBEP_TIT_PREFERENTES_AREA (BEPARE_CODNUM, BEPTIT_CODNUM)
VALUES (127,47);
INSERT INTO TBEP_TIT_PREFERENTES_AREA (BEPARE_CODNUM, BEPTIT_CODNUM)
VALUES (127,15);
INSERT INTO TBEP_TIT_PREFERENTES_AREA (BEPARE_CODNUM, BEPTIT_CODNUM)
VALUES (127,48);
INSERT INTO TBEP_TIT_PREFERENTES_AREA (BEPARE_CODNUM, BEPTIT_CODNUM)
VALUES (127,124);
INSERT INTO TBEP_TIT_PREFERENTES_AREA (BEPARE_CODNUM, BEPTIT_CODNUM)
VALUES (128,6);
INSERT INTO TBEP_TIT_PREFERENTES_AREA (BEPARE_CODNUM, BEPTIT_CODNUM)
VALUES (128,122);
INSERT INTO TBEP_TIT_PREFERENTES_AREA (BEPARE_CODNUM, BEPTIT_CODNUM)
VALUES (128,15);
INSERT INTO TBEP_TIT_PREFERENTES_AREA (BEPARE_CODNUM, BEPTIT_CODNUM)
VALUES (128,124);
INSERT INTO TBEP_TIT_PREFERENTES_AREA (BEPARE_CODNUM, BEPTIT_CODNUM)
VALUES (130,160);
INSERT INTO TBEP_TIT_PREFERENTES_AREA (BEPARE_CODNUM, BEPTIT_CODNUM)
VALUES (130,162);
INSERT INTO TBEP_TIT_PREFERENTES_AREA (BEPARE_CODNUM, BEPTIT_CODNUM)
VALUES (130,163);
INSERT INTO TBEP_TIT_PREFERENTES_AREA (BEPARE_CODNUM, BEPTIT_CODNUM)
VALUES (131,135);
INSERT INTO TBEP_TIT_PREFERENTES_AREA (BEPARE_CODNUM, BEPTIT_CODNUM)
VALUES (131,164);
INSERT INTO TBEP_TIT_PREFERENTES_AREA (BEPARE_CODNUM, BEPTIT_CODNUM)
VALUES (131,137);
INSERT INTO TBEP_TIT_PREFERENTES_AREA (BEPARE_CODNUM, BEPTIT_CODNUM)
VALUES (131,165);
INSERT INTO TBEP_TIT_PREFERENTES_AREA (BEPARE_CODNUM, BEPTIT_CODNUM)
VALUES (131,166);
INSERT INTO TBEP_TIT_PREFERENTES_AREA (BEPARE_CODNUM, BEPTIT_CODNUM)
VALUES (131,167);
INSERT INTO TBEP_TIT_PREFERENTES_AREA (BEPARE_CODNUM, BEPTIT_CODNUM)
VALUES (131,47);
INSERT INTO TBEP_TIT_PREFERENTES_AREA (BEPARE_CODNUM, BEPTIT_CODNUM)
VALUES (131,138);
INSERT INTO TBEP_TIT_PREFERENTES_AREA (BEPARE_CODNUM, BEPTIT_CODNUM)
VALUES (131,97);
INSERT INTO TBEP_TIT_PREFERENTES_AREA (BEPARE_CODNUM, BEPTIT_CODNUM)
VALUES (131,134);
INSERT INTO TBEP_TIT_PREFERENTES_AREA (BEPARE_CODNUM, BEPTIT_CODNUM)
VALUES (132,139);
INSERT INTO TBEP_TIT_PREFERENTES_AREA (BEPARE_CODNUM, BEPTIT_CODNUM)
VALUES (132,6);
INSERT INTO TBEP_TIT_PREFERENTES_AREA (BEPARE_CODNUM, BEPTIT_CODNUM)
VALUES (132,140);
INSERT INTO TBEP_TIT_PREFERENTES_AREA (BEPARE_CODNUM, BEPTIT_CODNUM)
VALUES (132,7);
INSERT INTO TBEP_TIT_PREFERENTES_AREA (BEPARE_CODNUM, BEPTIT_CODNUM)
VALUES (132,11);
INSERT INTO TBEP_TIT_PREFERENTES_AREA (BEPARE_CODNUM, BEPTIT_CODNUM)
VALUES (132,141);
INSERT INTO TBEP_TIT_PREFERENTES_AREA (BEPARE_CODNUM, BEPTIT_CODNUM)
VALUES (134,40);
INSERT INTO TBEP_TIT_PREFERENTES_AREA (BEPARE_CODNUM, BEPTIT_CODNUM)
VALUES (134,41);
INSERT INTO TBEP_TIT_PREFERENTES_AREA (BEPARE_CODNUM, BEPTIT_CODNUM)
VALUES (134,145);
INSERT INTO TBEP_TIT_PREFERENTES_AREA (BEPARE_CODNUM, BEPTIT_CODNUM)
VALUES (134,146);
INSERT INTO TBEP_TIT_PREFERENTES_AREA (BEPARE_CODNUM, BEPTIT_CODNUM)
VALUES (134,168);
INSERT INTO TBEP_TIT_PREFERENTES_AREA (BEPARE_CODNUM, BEPTIT_CODNUM)
VALUES (134,169);
INSERT INTO TBEP_TIT_PREFERENTES_AREA (BEPARE_CODNUM, BEPTIT_CODNUM)
VALUES (135,112);
INSERT INTO TBEP_TIT_PREFERENTES_AREA (BEPARE_CODNUM, BEPTIT_CODNUM)
VALUES (135,135);
INSERT INTO TBEP_TIT_PREFERENTES_AREA (BEPARE_CODNUM, BEPTIT_CODNUM)
VALUES (135,113);
INSERT INTO TBEP_TIT_PREFERENTES_AREA (BEPARE_CODNUM, BEPTIT_CODNUM)
VALUES (135,138);
INSERT INTO TBEP_TIT_PREFERENTES_AREA (BEPARE_CODNUM, BEPTIT_CODNUM)
VALUES (136,55);
INSERT INTO TBEP_TIT_PREFERENTES_AREA (BEPARE_CODNUM, BEPTIT_CODNUM)
VALUES (136,56);
INSERT INTO TBEP_TIT_PREFERENTES_AREA (BEPARE_CODNUM, BEPTIT_CODNUM)
VALUES (136,57);
INSERT INTO TBEP_TIT_PREFERENTES_AREA (BEPARE_CODNUM, BEPTIT_CODNUM)
VALUES (136,58);
INSERT INTO TBEP_TIT_PREFERENTES_AREA (BEPARE_CODNUM, BEPTIT_CODNUM)
VALUES (136,59);
INSERT INTO TBEP_TIT_PREFERENTES_AREA (BEPARE_CODNUM, BEPTIT_CODNUM)
VALUES (136,60);
INSERT INTO TBEP_TIT_PREFERENTES_AREA (BEPARE_CODNUM, BEPTIT_CODNUM)
VALUES (136,61);
INSERT INTO TBEP_TIT_PREFERENTES_AREA (BEPARE_CODNUM, BEPTIT_CODNUM)
VALUES (136,62);
INSERT INTO TBEP_TIT_PREFERENTES_AREA (BEPARE_CODNUM, BEPTIT_CODNUM)
VALUES (137,170);
INSERT INTO TBEP_TIT_PREFERENTES_AREA (BEPARE_CODNUM, BEPTIT_CODNUM)
VALUES (137,171);
INSERT INTO TBEP_TIT_PREFERENTES_AREA (BEPARE_CODNUM, BEPTIT_CODNUM)
VALUES (28,79);
INSERT INTO TBEP_TIT_PREFERENTES_AREA (BEPARE_CODNUM, BEPTIT_CODNUM)
VALUES (28,80);
INSERT INTO TBEP_TIT_PREFERENTES_AREA (BEPARE_CODNUM, BEPTIT_CODNUM)
VALUES (29,64);
INSERT INTO TBEP_TIT_PREFERENTES_AREA (BEPARE_CODNUM, BEPTIT_CODNUM)
VALUES (29,172);
INSERT INTO TBEP_TIT_PREFERENTES_AREA (BEPARE_CODNUM, BEPTIT_CODNUM)
VALUES (29,173);
INSERT INTO TBEP_TIT_PREFERENTES_AREA (BEPARE_CODNUM, BEPTIT_CODNUM)
VALUES (29,67);