INSERT INTO TBEP_TIT_PREFERENTES_AREA (BEPARE_CODNUM, BEPTIT_CODNUM, UID_USUARIO)
VALUES (12,1,'CARGA_INICIAL');
INSERT INTO TBEP_TIT_PREFERENTES_AREA (BEPARE_CODNUM, BEPTIT_CODNUM, UID_USUARIO)
VALUES (12,2,'CARGA_INICIAL');
INSERT INTO TBEP_TIT_PREFERENTES_AREA (BEPARE_CODNUM, BEPTIT_CODNUM, UID_USUARIO)
VALUES (12,3,'CARGA_INICIAL');
INSERT INTO TBEP_TIT_PREFERENTES_AREA (BEPARE_CODNUM, BEPTIT_CODNUM, UID_USUARIO)
VALUES (12,4,'CARGA_INICIAL');
INSERT INTO TBEP_TIT_PREFERENTES_AREA (BEPARE_CODNUM, BEPTIT_CODNUM, UID_USUARIO)
VALUES (12,5,'CARGA_INICIAL');
INSERT INTO TBEP_TIT_PREFERENTES_AREA (BEPARE_CODNUM, BEPTIT_CODNUM, UID_USUARIO)
VALUES (30,6,'CARGA_INICIAL');
INSERT INTO TBEP_TIT_PREFERENTES_AREA (BEPARE_CODNUM, BEPTIT_CODNUM, UID_USUARIO)
VALUES (30,7,'CARGA_INICIAL');
INSERT INTO TBEP_TIT_PREFERENTES_AREA (BEPARE_CODNUM, BEPTIT_CODNUM, UID_USUARIO)
VALUES (30,8,'CARGA_INICIAL');
INSERT INTO TBEP_TIT_PREFERENTES_AREA (BEPARE_CODNUM, BEPTIT_CODNUM, UID_USUARIO)
VALUES (30,9,'CARGA_INICIAL');
INSERT INTO TBEP_TIT_PREFERENTES_AREA (BEPARE_CODNUM, BEPTIT_CODNUM, UID_USUARIO)
VALUES (30,10,'CARGA_INICIAL');
INSERT INTO TBEP_TIT_PREFERENTES_AREA (BEPARE_CODNUM, BEPTIT_CODNUM, UID_USUARIO)
VALUES (30,11,'CARGA_INICIAL');
INSERT INTO TBEP_TIT_PREFERENTES_AREA (BEPARE_CODNUM, BEPTIT_CODNUM, UID_USUARIO)
VALUES (30,12,'CARGA_INICIAL');
INSERT INTO TBEP_TIT_PREFERENTES_AREA (BEPARE_CODNUM, BEPTIT_CODNUM, UID_USUARIO)
VALUES (30,13,'CARGA_INICIAL');
INSERT INTO TBEP_TIT_PREFERENTES_AREA (BEPARE_CODNUM, BEPTIT_CODNUM, UID_USUARIO)
VALUES (30,14,'CARGA_INICIAL');
INSERT INTO TBEP_TIT_PREFERENTES_AREA (BEPARE_CODNUM, BEPTIT_CODNUM, UID_USUARIO)
VALUES (30,15,'CARGA_INICIAL');
INSERT INTO TBEP_TIT_PREFERENTES_AREA (BEPARE_CODNUM, BEPTIT_CODNUM, UID_USUARIO)
VALUES (31,16,'CARGA_INICIAL');
INSERT INTO TBEP_TIT_PREFERENTES_AREA (BEPARE_CODNUM, BEPTIT_CODNUM, UID_USUARIO)
VALUES (31,17,'CARGA_INICIAL');
INSERT INTO TBEP_TIT_PREFERENTES_AREA (BEPARE_CODNUM, BEPTIT_CODNUM, UID_USUARIO)
VALUES (31,18,'CARGA_INICIAL');
INSERT INTO TBEP_TIT_PREFERENTES_AREA (BEPARE_CODNUM, BEPTIT_CODNUM, UID_USUARIO)
VALUES (31,19,'CARGA_INICIAL');
INSERT INTO TBEP_TIT_PREFERENTES_AREA (BEPARE_CODNUM, BEPTIT_CODNUM, UID_USUARIO)
VALUES (31,20,'CARGA_INICIAL');
INSERT INTO TBEP_TIT_PREFERENTES_AREA (BEPARE_CODNUM, BEPTIT_CODNUM, UID_USUARIO)
VALUES (32,19,'CARGA_INICIAL');
INSERT INTO TBEP_TIT_PREFERENTES_AREA (BEPARE_CODNUM, BEPTIT_CODNUM, UID_USUARIO)
VALUES (32,20,'CARGA_INICIAL');
INSERT INTO TBEP_TIT_PREFERENTES_AREA (BEPARE_CODNUM, BEPTIT_CODNUM, UID_USUARIO)
VALUES (33,19,'CARGA_INICIAL');
INSERT INTO TBEP_TIT_PREFERENTES_AREA (BEPARE_CODNUM, BEPTIT_CODNUM, UID_USUARIO)
VALUES (33,20,'CARGA_INICIAL');
INSERT INTO TBEP_TIT_PREFERENTES_AREA (BEPARE_CODNUM, BEPTIT_CODNUM, UID_USUARIO)
VALUES (34,21,'CARGA_INICIAL');
INSERT INTO TBEP_TIT_PREFERENTES_AREA (BEPARE_CODNUM, BEPTIT_CODNUM, UID_USUARIO)
VALUES (34,22,'CARGA_INICIAL');
INSERT INTO TBEP_TIT_PREFERENTES_AREA (BEPARE_CODNUM, BEPTIT_CODNUM, UID_USUARIO)
VALUES (34,23,'CARGA_INICIAL');
INSERT INTO TBEP_TIT_PREFERENTES_AREA (BEPARE_CODNUM, BEPTIT_CODNUM, UID_USUARIO)
VALUES (34,19,'CARGA_INICIAL');
INSERT INTO TBEP_TIT_PREFERENTES_AREA (BEPARE_CODNUM, BEPTIT_CODNUM, UID_USUARIO)
VALUES (34,20,'CARGA_INICIAL');
INSERT INTO TBEP_TIT_PREFERENTES_AREA (BEPARE_CODNUM, BEPTIT_CODNUM, UID_USUARIO)
VALUES (34,24,'CARGA_INICIAL');
INSERT INTO TBEP_TIT_PREFERENTES_AREA (BEPARE_CODNUM, BEPTIT_CODNUM, UID_USUARIO)
VALUES (35,19,'CARGA_INICIAL');
INSERT INTO TBEP_TIT_PREFERENTES_AREA (BEPARE_CODNUM, BEPTIT_CODNUM, UID_USUARIO)
VALUES (35,20,'CARGA_INICIAL');
INSERT INTO TBEP_TIT_PREFERENTES_AREA (BEPARE_CODNUM, BEPTIT_CODNUM, UID_USUARIO)
VALUES (36,19,'CARGA_INICIAL');
INSERT INTO TBEP_TIT_PREFERENTES_AREA (BEPARE_CODNUM, BEPTIT_CODNUM, UID_USUARIO)
VALUES (36,20,'CARGA_INICIAL');
INSERT INTO TBEP_TIT_PREFERENTES_AREA (BEPARE_CODNUM, BEPTIT_CODNUM, UID_USUARIO)
VALUES (37,19,'CARGA_INICIAL');
INSERT INTO TBEP_TIT_PREFERENTES_AREA (BEPARE_CODNUM, BEPTIT_CODNUM, UID_USUARIO)
VALUES (37,20,'CARGA_INICIAL');
INSERT INTO TBEP_TIT_PREFERENTES_AREA (BEPARE_CODNUM, BEPTIT_CODNUM, UID_USUARIO)
VALUES (38,19,'CARGA_INICIAL');
INSERT INTO TBEP_TIT_PREFERENTES_AREA (BEPARE_CODNUM, BEPTIT_CODNUM, UID_USUARIO)
VALUES (38,20,'CARGA_INICIAL');
INSERT INTO TBEP_TIT_PREFERENTES_AREA (BEPARE_CODNUM, BEPTIT_CODNUM, UID_USUARIO)
VALUES (39,19,'CARGA_INICIAL');
INSERT INTO TBEP_TIT_PREFERENTES_AREA (BEPARE_CODNUM, BEPTIT_CODNUM, UID_USUARIO)
VALUES (39,20,'CARGA_INICIAL');
INSERT INTO TBEP_TIT_PREFERENTES_AREA (BEPARE_CODNUM, BEPTIT_CODNUM, UID_USUARIO)
VALUES (40,19,'CARGA_INICIAL');
INSERT INTO TBEP_TIT_PREFERENTES_AREA (BEPARE_CODNUM, BEPTIT_CODNUM, UID_USUARIO)
VALUES (40,20,'CARGA_INICIAL');
INSERT INTO TBEP_TIT_PREFERENTES_AREA (BEPARE_CODNUM, BEPTIT_CODNUM, UID_USUARIO)
VALUES (41,19,'CARGA_INICIAL');
INSERT INTO TBEP_TIT_PREFERENTES_AREA (BEPARE_CODNUM, BEPTIT_CODNUM, UID_USUARIO)
VALUES (41,20,'CARGA_INICIAL');
INSERT INTO TBEP_TIT_PREFERENTES_AREA (BEPARE_CODNUM, BEPTIT_CODNUM, UID_USUARIO)
VALUES (42,19,'CARGA_INICIAL');
INSERT INTO TBEP_TIT_PREFERENTES_AREA (BEPARE_CODNUM, BEPTIT_CODNUM, UID_USUARIO)
VALUES (42,20,'CARGA_INICIAL');
INSERT INTO TBEP_TIT_PREFERENTES_AREA (BEPARE_CODNUM, BEPTIT_CODNUM, UID_USUARIO)
VALUES (43,25,'CARGA_INICIAL');
INSERT INTO TBEP_TIT_PREFERENTES_AREA (BEPARE_CODNUM, BEPTIT_CODNUM, UID_USUARIO)
VALUES (43,26,'CARGA_INICIAL');
INSERT INTO TBEP_TIT_PREFERENTES_AREA (BEPARE_CODNUM, BEPTIT_CODNUM, UID_USUARIO)
VALUES (44,27,'CARGA_INICIAL');
INSERT INTO TBEP_TIT_PREFERENTES_AREA (BEPARE_CODNUM, BEPTIT_CODNUM, UID_USUARIO)
VALUES (44,28,'CARGA_INICIAL');
INSERT INTO TBEP_TIT_PREFERENTES_AREA (BEPARE_CODNUM, BEPTIT_CODNUM, UID_USUARIO)
VALUES (44,29,'CARGA_INICIAL');
INSERT INTO TBEP_TIT_PREFERENTES_AREA (BEPARE_CODNUM, BEPTIT_CODNUM, UID_USUARIO)
VALUES (44,30,'CARGA_INICIAL');
INSERT INTO TBEP_TIT_PREFERENTES_AREA (BEPARE_CODNUM, BEPTIT_CODNUM, UID_USUARIO)
VALUES (44,31,'CARGA_INICIAL');
INSERT INTO TBEP_TIT_PREFERENTES_AREA (BEPARE_CODNUM, BEPTIT_CODNUM, UID_USUARIO)
VALUES (45,32,'CARGA_INICIAL');
INSERT INTO TBEP_TIT_PREFERENTES_AREA (BEPARE_CODNUM, BEPTIT_CODNUM, UID_USUARIO)
VALUES (45,33,'CARGA_INICIAL');
INSERT INTO TBEP_TIT_PREFERENTES_AREA (BEPARE_CODNUM, BEPTIT_CODNUM, UID_USUARIO)
VALUES (45,34,'CARGA_INICIAL');
INSERT INTO TBEP_TIT_PREFERENTES_AREA (BEPARE_CODNUM, BEPTIT_CODNUM, UID_USUARIO)
VALUES (45,35,'CARGA_INICIAL');
INSERT INTO TBEP_TIT_PREFERENTES_AREA (BEPARE_CODNUM, BEPTIT_CODNUM, UID_USUARIO)
VALUES (46,25,'CARGA_INICIAL');
INSERT INTO TBEP_TIT_PREFERENTES_AREA (BEPARE_CODNUM, BEPTIT_CODNUM, UID_USUARIO)
VALUES (46,36,'CARGA_INICIAL');
INSERT INTO TBEP_TIT_PREFERENTES_AREA (BEPARE_CODNUM, BEPTIT_CODNUM, UID_USUARIO)
VALUES (46,26,'CARGA_INICIAL');
INSERT INTO TBEP_TIT_PREFERENTES_AREA (BEPARE_CODNUM, BEPTIT_CODNUM, UID_USUARIO)
VALUES (46,37,'CARGA_INICIAL');
INSERT INTO TBEP_TIT_PREFERENTES_AREA (BEPARE_CODNUM, BEPTIT_CODNUM, UID_USUARIO)
VALUES (46,38,'CARGA_INICIAL');
INSERT INTO TBEP_TIT_PREFERENTES_AREA (BEPARE_CODNUM, BEPTIT_CODNUM, UID_USUARIO)
VALUES (46,39,'CARGA_INICIAL');
INSERT INTO TBEP_TIT_PREFERENTES_AREA (BEPARE_CODNUM, BEPTIT_CODNUM, UID_USUARIO)
VALUES (47,40,'CARGA_INICIAL');
INSERT INTO TBEP_TIT_PREFERENTES_AREA (BEPARE_CODNUM, BEPTIT_CODNUM, UID_USUARIO)
VALUES (47,41,'CARGA_INICIAL');
INSERT INTO TBEP_TIT_PREFERENTES_AREA (BEPARE_CODNUM, BEPTIT_CODNUM, UID_USUARIO)
VALUES (47,42,'CARGA_INICIAL');
INSERT INTO TBEP_TIT_PREFERENTES_AREA (BEPARE_CODNUM, BEPTIT_CODNUM, UID_USUARIO)
VALUES (48,43,'CARGA_INICIAL');
INSERT INTO TBEP_TIT_PREFERENTES_AREA (BEPARE_CODNUM, BEPTIT_CODNUM, UID_USUARIO)
VALUES (48,44,'CARGA_INICIAL');
INSERT INTO TBEP_TIT_PREFERENTES_AREA (BEPARE_CODNUM, BEPTIT_CODNUM, UID_USUARIO)
VALUES (49,45,'CARGA_INICIAL');
INSERT INTO TBEP_TIT_PREFERENTES_AREA (BEPARE_CODNUM, BEPTIT_CODNUM, UID_USUARIO)
VALUES (49,46,'CARGA_INICIAL');
INSERT INTO TBEP_TIT_PREFERENTES_AREA (BEPARE_CODNUM, BEPTIT_CODNUM, UID_USUARIO)
VALUES (49,47,'CARGA_INICIAL');
INSERT INTO TBEP_TIT_PREFERENTES_AREA (BEPARE_CODNUM, BEPTIT_CODNUM, UID_USUARIO)
VALUES (49,48,'CARGA_INICIAL');
INSERT INTO TBEP_TIT_PREFERENTES_AREA (BEPARE_CODNUM, BEPTIT_CODNUM, UID_USUARIO)
VALUES (49,6,'CARGA_INICIAL');
INSERT INTO TBEP_TIT_PREFERENTES_AREA (BEPARE_CODNUM, BEPTIT_CODNUM, UID_USUARIO)
VALUES (49,7,'CARGA_INICIAL');
INSERT INTO TBEP_TIT_PREFERENTES_AREA (BEPARE_CODNUM, BEPTIT_CODNUM, UID_USUARIO)
VALUES (49,8,'CARGA_INICIAL');
INSERT INTO TBEP_TIT_PREFERENTES_AREA (BEPARE_CODNUM, BEPTIT_CODNUM, UID_USUARIO)
VALUES (49,11,'CARGA_INICIAL');
INSERT INTO TBEP_TIT_PREFERENTES_AREA (BEPARE_CODNUM, BEPTIT_CODNUM, UID_USUARIO)
VALUES (49,12,'CARGA_INICIAL');
INSERT INTO TBEP_TIT_PREFERENTES_AREA (BEPARE_CODNUM, BEPTIT_CODNUM, UID_USUARIO)
VALUES (49,15,'CARGA_INICIAL');
INSERT INTO TBEP_TIT_PREFERENTES_AREA (BEPARE_CODNUM, BEPTIT_CODNUM, UID_USUARIO)
VALUES (50,49,'CARGA_INICIAL');
INSERT INTO TBEP_TIT_PREFERENTES_AREA (BEPARE_CODNUM, BEPTIT_CODNUM, UID_USUARIO)
VALUES (50,50,'CARGA_INICIAL');
INSERT INTO TBEP_TIT_PREFERENTES_AREA (BEPARE_CODNUM, BEPTIT_CODNUM, UID_USUARIO)
VALUES (50,51,'CARGA_INICIAL');
INSERT INTO TBEP_TIT_PREFERENTES_AREA (BEPARE_CODNUM, BEPTIT_CODNUM, UID_USUARIO)
VALUES (50,52,'CARGA_INICIAL');
INSERT INTO TBEP_TIT_PREFERENTES_AREA (BEPARE_CODNUM, BEPTIT_CODNUM, UID_USUARIO)
VALUES (50,53,'CARGA_INICIAL');
INSERT INTO TBEP_TIT_PREFERENTES_AREA (BEPARE_CODNUM, BEPTIT_CODNUM, UID_USUARIO)
VALUES (50,54,'CARGA_INICIAL');
INSERT INTO TBEP_TIT_PREFERENTES_AREA (BEPARE_CODNUM, BEPTIT_CODNUM, UID_USUARIO)
VALUES (50,5,'CARGA_INICIAL');
INSERT INTO TBEP_TIT_PREFERENTES_AREA (BEPARE_CODNUM, BEPTIT_CODNUM, UID_USUARIO)
VALUES (50,3,'CARGA_INICIAL');
INSERT INTO TBEP_TIT_PREFERENTES_AREA (BEPARE_CODNUM, BEPTIT_CODNUM, UID_USUARIO)
VALUES (51,55,'CARGA_INICIAL');
INSERT INTO TBEP_TIT_PREFERENTES_AREA (BEPARE_CODNUM, BEPTIT_CODNUM, UID_USUARIO)
VALUES (51,56,'CARGA_INICIAL');
INSERT INTO TBEP_TIT_PREFERENTES_AREA (BEPARE_CODNUM, BEPTIT_CODNUM, UID_USUARIO)
VALUES (51,57,'CARGA_INICIAL');
INSERT INTO TBEP_TIT_PREFERENTES_AREA (BEPARE_CODNUM, BEPTIT_CODNUM, UID_USUARIO)
VALUES (51,58,'CARGA_INICIAL');
INSERT INTO TBEP_TIT_PREFERENTES_AREA (BEPARE_CODNUM, BEPTIT_CODNUM, UID_USUARIO)
VALUES (51,59,'CARGA_INICIAL');
INSERT INTO TBEP_TIT_PREFERENTES_AREA (BEPARE_CODNUM, BEPTIT_CODNUM, UID_USUARIO)
VALUES (51,60,'CARGA_INICIAL');
INSERT INTO TBEP_TIT_PREFERENTES_AREA (BEPARE_CODNUM, BEPTIT_CODNUM, UID_USUARIO)
VALUES (51,61,'CARGA_INICIAL');
INSERT INTO TBEP_TIT_PREFERENTES_AREA (BEPARE_CODNUM, BEPTIT_CODNUM, UID_USUARIO)
VALUES (51,62,'CARGA_INICIAL');
INSERT INTO TBEP_TIT_PREFERENTES_AREA (BEPARE_CODNUM, BEPTIT_CODNUM, UID_USUARIO)
VALUES (53,63,'CARGA_INICIAL');
INSERT INTO TBEP_TIT_PREFERENTES_AREA (BEPARE_CODNUM, BEPTIT_CODNUM, UID_USUARIO)
VALUES (53,64,'CARGA_INICIAL');
INSERT INTO TBEP_TIT_PREFERENTES_AREA (BEPARE_CODNUM, BEPTIT_CODNUM, UID_USUARIO)
VALUES (53,65,'CARGA_INICIAL');
INSERT INTO TBEP_TIT_PREFERENTES_AREA (BEPARE_CODNUM, BEPTIT_CODNUM, UID_USUARIO)
VALUES (53,66,'CARGA_INICIAL');
INSERT INTO TBEP_TIT_PREFERENTES_AREA (BEPARE_CODNUM, BEPTIT_CODNUM, UID_USUARIO)
VALUES (53,67,'CARGA_INICIAL');
INSERT INTO TBEP_TIT_PREFERENTES_AREA (BEPARE_CODNUM, BEPTIT_CODNUM, UID_USUARIO)
VALUES (53,68,'CARGA_INICIAL');
INSERT INTO TBEP_TIT_PREFERENTES_AREA (BEPARE_CODNUM, BEPTIT_CODNUM, UID_USUARIO)
VALUES (53,174,'CARGA_INICIAL');
INSERT INTO TBEP_TIT_PREFERENTES_AREA (BEPARE_CODNUM, BEPTIT_CODNUM, UID_USUARIO)
VALUES (54,63,'CARGA_INICIAL');
INSERT INTO TBEP_TIT_PREFERENTES_AREA (BEPARE_CODNUM, BEPTIT_CODNUM, UID_USUARIO)
VALUES (54,64,'CARGA_INICIAL');
INSERT INTO TBEP_TIT_PREFERENTES_AREA (BEPARE_CODNUM, BEPTIT_CODNUM, UID_USUARIO)
VALUES (54,65,'CARGA_INICIAL');
INSERT INTO TBEP_TIT_PREFERENTES_AREA (BEPARE_CODNUM, BEPTIT_CODNUM, UID_USUARIO)
VALUES (54,67,'CARGA_INICIAL');
INSERT INTO TBEP_TIT_PREFERENTES_AREA (BEPARE_CODNUM, BEPTIT_CODNUM, UID_USUARIO)
VALUES (54,68,'CARGA_INICIAL');
INSERT INTO TBEP_TIT_PREFERENTES_AREA (BEPARE_CODNUM, BEPTIT_CODNUM, UID_USUARIO)
VALUES (54,174,'CARGA_INICIAL');
INSERT INTO TBEP_TIT_PREFERENTES_AREA (BEPARE_CODNUM, BEPTIT_CODNUM, UID_USUARIO)
VALUES (55,7,'CARGA_INICIAL');
INSERT INTO TBEP_TIT_PREFERENTES_AREA (BEPARE_CODNUM, BEPTIT_CODNUM, UID_USUARIO)
VALUES (55,8,'CARGA_INICIAL');
INSERT INTO TBEP_TIT_PREFERENTES_AREA (BEPARE_CODNUM, BEPTIT_CODNUM, UID_USUARIO)
VALUES (55,9,'CARGA_INICIAL');
INSERT INTO TBEP_TIT_PREFERENTES_AREA (BEPARE_CODNUM, BEPTIT_CODNUM, UID_USUARIO)
VALUES (55,11,'CARGA_INICIAL');
INSERT INTO TBEP_TIT_PREFERENTES_AREA (BEPARE_CODNUM, BEPTIT_CODNUM, UID_USUARIO)
VALUES (55,12,'CARGA_INICIAL');
INSERT INTO TBEP_TIT_PREFERENTES_AREA (BEPARE_CODNUM, BEPTIT_CODNUM, UID_USUARIO)
VALUES (55,14,'CARGA_INICIAL');
INSERT INTO TBEP_TIT_PREFERENTES_AREA (BEPARE_CODNUM, BEPTIT_CODNUM, UID_USUARIO)
VALUES (56,69,'CARGA_INICIAL');
INSERT INTO TBEP_TIT_PREFERENTES_AREA (BEPARE_CODNUM, BEPTIT_CODNUM, UID_USUARIO)
VALUES (56,70,'CARGA_INICIAL');
INSERT INTO TBEP_TIT_PREFERENTES_AREA (BEPARE_CODNUM, BEPTIT_CODNUM, UID_USUARIO)
VALUES (57,71,'CARGA_INICIAL');
INSERT INTO TBEP_TIT_PREFERENTES_AREA (BEPARE_CODNUM, BEPTIT_CODNUM, UID_USUARIO)
VALUES (57,72,'CARGA_INICIAL');
INSERT INTO TBEP_TIT_PREFERENTES_AREA (BEPARE_CODNUM, BEPTIT_CODNUM, UID_USUARIO)
VALUES (58,73,'CARGA_INICIAL');
INSERT INTO TBEP_TIT_PREFERENTES_AREA (BEPARE_CODNUM, BEPTIT_CODNUM, UID_USUARIO)
VALUES (58,74,'CARGA_INICIAL');
INSERT INTO TBEP_TIT_PREFERENTES_AREA (BEPARE_CODNUM, BEPTIT_CODNUM, UID_USUARIO)
VALUES (58,75,'CARGA_INICIAL');
INSERT INTO TBEP_TIT_PREFERENTES_AREA (BEPARE_CODNUM, BEPTIT_CODNUM, UID_USUARIO)
VALUES (58,76,'CARGA_INICIAL');
INSERT INTO TBEP_TIT_PREFERENTES_AREA (BEPARE_CODNUM, BEPTIT_CODNUM, UID_USUARIO)
VALUES (58,77,'CARGA_INICIAL');
INSERT INTO TBEP_TIT_PREFERENTES_AREA (BEPARE_CODNUM, BEPTIT_CODNUM, UID_USUARIO)
VALUES (58,78,'CARGA_INICIAL');
INSERT INTO TBEP_TIT_PREFERENTES_AREA (BEPARE_CODNUM, BEPTIT_CODNUM, UID_USUARIO)
VALUES (14,45,'CARGA_INICIAL');
INSERT INTO TBEP_TIT_PREFERENTES_AREA (BEPARE_CODNUM, BEPTIT_CODNUM, UID_USUARIO)
VALUES (14,46,'CARGA_INICIAL');
INSERT INTO TBEP_TIT_PREFERENTES_AREA (BEPARE_CODNUM, BEPTIT_CODNUM, UID_USUARIO)
VALUES (14,70,'CARGA_INICIAL');
INSERT INTO TBEP_TIT_PREFERENTES_AREA (BEPARE_CODNUM, BEPTIT_CODNUM, UID_USUARIO)
VALUES (14,28,'CARGA_INICIAL');
INSERT INTO TBEP_TIT_PREFERENTES_AREA (BEPARE_CODNUM, BEPTIT_CODNUM, UID_USUARIO)
VALUES (14,79,'CARGA_INICIAL');
INSERT INTO TBEP_TIT_PREFERENTES_AREA (BEPARE_CODNUM, BEPTIT_CODNUM, UID_USUARIO)
VALUES (14,80,'CARGA_INICIAL');
INSERT INTO TBEP_TIT_PREFERENTES_AREA (BEPARE_CODNUM, BEPTIT_CODNUM, UID_USUARIO)
VALUES (14,81,'CARGA_INICIAL');
INSERT INTO TBEP_TIT_PREFERENTES_AREA (BEPARE_CODNUM, BEPTIT_CODNUM, UID_USUARIO)
VALUES (14,82,'CARGA_INICIAL');
INSERT INTO TBEP_TIT_PREFERENTES_AREA (BEPARE_CODNUM, BEPTIT_CODNUM, UID_USUARIO)
VALUES (59,7,'CARGA_INICIAL');
INSERT INTO TBEP_TIT_PREFERENTES_AREA (BEPARE_CODNUM, BEPTIT_CODNUM, UID_USUARIO)
VALUES (59,8,'CARGA_INICIAL');
INSERT INTO TBEP_TIT_PREFERENTES_AREA (BEPARE_CODNUM, BEPTIT_CODNUM, UID_USUARIO)
VALUES (59,9,'CARGA_INICIAL');
INSERT INTO TBEP_TIT_PREFERENTES_AREA (BEPARE_CODNUM, BEPTIT_CODNUM, UID_USUARIO)
VALUES (59,10,'CARGA_INICIAL');
INSERT INTO TBEP_TIT_PREFERENTES_AREA (BEPARE_CODNUM, BEPTIT_CODNUM, UID_USUARIO)
VALUES (59,11,'CARGA_INICIAL');
INSERT INTO TBEP_TIT_PREFERENTES_AREA (BEPARE_CODNUM, BEPTIT_CODNUM, UID_USUARIO)
VALUES (59,12,'CARGA_INICIAL');
INSERT INTO TBEP_TIT_PREFERENTES_AREA (BEPARE_CODNUM, BEPTIT_CODNUM, UID_USUARIO)
VALUES (59,13,'CARGA_INICIAL');
INSERT INTO TBEP_TIT_PREFERENTES_AREA (BEPARE_CODNUM, BEPTIT_CODNUM, UID_USUARIO)
VALUES (59,14,'CARGA_INICIAL');
INSERT INTO TBEP_TIT_PREFERENTES_AREA (BEPARE_CODNUM, BEPTIT_CODNUM, UID_USUARIO)
VALUES (60,83,'CARGA_INICIAL');
INSERT INTO TBEP_TIT_PREFERENTES_AREA (BEPARE_CODNUM, BEPTIT_CODNUM, UID_USUARIO)
VALUES (60,84,'CARGA_INICIAL');
INSERT INTO TBEP_TIT_PREFERENTES_AREA (BEPARE_CODNUM, BEPTIT_CODNUM, UID_USUARIO)
VALUES (60,85,'CARGA_INICIAL');
INSERT INTO TBEP_TIT_PREFERENTES_AREA (BEPARE_CODNUM, BEPTIT_CODNUM, UID_USUARIO)
VALUES (60,86,'CARGA_INICIAL');
INSERT INTO TBEP_TIT_PREFERENTES_AREA (BEPARE_CODNUM, BEPTIT_CODNUM, UID_USUARIO)
VALUES (60,87,'CARGA_INICIAL');
INSERT INTO TBEP_TIT_PREFERENTES_AREA (BEPARE_CODNUM, BEPTIT_CODNUM, UID_USUARIO)
VALUES (61,88,'CARGA_INICIAL');
INSERT INTO TBEP_TIT_PREFERENTES_AREA (BEPARE_CODNUM, BEPTIT_CODNUM, UID_USUARIO)
VALUES (61,13,'CARGA_INICIAL');
INSERT INTO TBEP_TIT_PREFERENTES_AREA (BEPARE_CODNUM, BEPTIT_CODNUM, UID_USUARIO)
VALUES (15,89,'CARGA_INICIAL');
INSERT INTO TBEP_TIT_PREFERENTES_AREA (BEPARE_CODNUM, BEPTIT_CODNUM, UID_USUARIO)
VALUES (15,90,'CARGA_INICIAL');
INSERT INTO TBEP_TIT_PREFERENTES_AREA (BEPARE_CODNUM, BEPTIT_CODNUM, UID_USUARIO)
VALUES (63,91,'CARGA_INICIAL');
INSERT INTO TBEP_TIT_PREFERENTES_AREA (BEPARE_CODNUM, BEPTIT_CODNUM, UID_USUARIO)
VALUES (63,92,'CARGA_INICIAL');
INSERT INTO TBEP_TIT_PREFERENTES_AREA (BEPARE_CODNUM, BEPTIT_CODNUM, UID_USUARIO)
VALUES (63,93,'CARGA_INICIAL');
INSERT INTO TBEP_TIT_PREFERENTES_AREA (BEPARE_CODNUM, BEPTIT_CODNUM, UID_USUARIO)
VALUES (63,94,'CARGA_INICIAL');
INSERT INTO TBEP_TIT_PREFERENTES_AREA (BEPARE_CODNUM, BEPTIT_CODNUM, UID_USUARIO)
VALUES (63,95,'CARGA_INICIAL');
INSERT INTO TBEP_TIT_PREFERENTES_AREA (BEPARE_CODNUM, BEPTIT_CODNUM, UID_USUARIO)
VALUES (63,96,'CARGA_INICIAL');
INSERT INTO TBEP_TIT_PREFERENTES_AREA (BEPARE_CODNUM, BEPTIT_CODNUM, UID_USUARIO)
VALUES (63,97,'CARGA_INICIAL');
INSERT INTO TBEP_TIT_PREFERENTES_AREA (BEPARE_CODNUM, BEPTIT_CODNUM, UID_USUARIO)
VALUES (63,13,'CARGA_INICIAL');
INSERT INTO TBEP_TIT_PREFERENTES_AREA (BEPARE_CODNUM, BEPTIT_CODNUM, UID_USUARIO)
VALUES (63,10,'CARGA_INICIAL');
INSERT INTO TBEP_TIT_PREFERENTES_AREA (BEPARE_CODNUM, BEPTIT_CODNUM, UID_USUARIO)
VALUES (16,1,'CARGA_INICIAL');
INSERT INTO TBEP_TIT_PREFERENTES_AREA (BEPARE_CODNUM, BEPTIT_CODNUM, UID_USUARIO)
VALUES (16,98,'CARGA_INICIAL');
INSERT INTO TBEP_TIT_PREFERENTES_AREA (BEPARE_CODNUM, BEPTIT_CODNUM, UID_USUARIO)
VALUES (16,99,'CARGA_INICIAL');
INSERT INTO TBEP_TIT_PREFERENTES_AREA (BEPARE_CODNUM, BEPTIT_CODNUM, UID_USUARIO)
VALUES (16,50,'CARGA_INICIAL');
INSERT INTO TBEP_TIT_PREFERENTES_AREA (BEPARE_CODNUM, BEPTIT_CODNUM, UID_USUARIO)
VALUES (16,100,'CARGA_INICIAL');
INSERT INTO TBEP_TIT_PREFERENTES_AREA (BEPARE_CODNUM, BEPTIT_CODNUM, UID_USUARIO)
VALUES (16,101,'CARGA_INICIAL');
INSERT INTO TBEP_TIT_PREFERENTES_AREA (BEPARE_CODNUM, BEPTIT_CODNUM, UID_USUARIO)
VALUES (16,4,'CARGA_INICIAL');
INSERT INTO TBEP_TIT_PREFERENTES_AREA (BEPARE_CODNUM, BEPTIT_CODNUM, UID_USUARIO)
VALUES (64,102,'CARGA_INICIAL');
INSERT INTO TBEP_TIT_PREFERENTES_AREA (BEPARE_CODNUM, BEPTIT_CODNUM, UID_USUARIO)
VALUES (64,103,'CARGA_INICIAL');
INSERT INTO TBEP_TIT_PREFERENTES_AREA (BEPARE_CODNUM, BEPTIT_CODNUM, UID_USUARIO)
VALUES (65,104,'CARGA_INICIAL');
INSERT INTO TBEP_TIT_PREFERENTES_AREA (BEPARE_CODNUM, BEPTIT_CODNUM, UID_USUARIO)
VALUES (65,105,'CARGA_INICIAL');
INSERT INTO TBEP_TIT_PREFERENTES_AREA (BEPARE_CODNUM, BEPTIT_CODNUM, UID_USUARIO)
VALUES (65,106,'CARGA_INICIAL');
INSERT INTO TBEP_TIT_PREFERENTES_AREA (BEPARE_CODNUM, BEPTIT_CODNUM, UID_USUARIO)
VALUES (65,107,'CARGA_INICIAL');
INSERT INTO TBEP_TIT_PREFERENTES_AREA (BEPARE_CODNUM, BEPTIT_CODNUM, UID_USUARIO)
VALUES (66,108,'CARGA_INICIAL');
INSERT INTO TBEP_TIT_PREFERENTES_AREA (BEPARE_CODNUM, BEPTIT_CODNUM, UID_USUARIO)
VALUES (66,109,'CARGA_INICIAL');
INSERT INTO TBEP_TIT_PREFERENTES_AREA (BEPARE_CODNUM, BEPTIT_CODNUM, UID_USUARIO)
VALUES (67,110,'CARGA_INICIAL');
INSERT INTO TBEP_TIT_PREFERENTES_AREA (BEPARE_CODNUM, BEPTIT_CODNUM, UID_USUARIO)
VALUES (67,111,'CARGA_INICIAL');
INSERT INTO TBEP_TIT_PREFERENTES_AREA (BEPARE_CODNUM, BEPTIT_CODNUM, UID_USUARIO)
VALUES (17,112,'CARGA_INICIAL');
INSERT INTO TBEP_TIT_PREFERENTES_AREA (BEPARE_CODNUM, BEPTIT_CODNUM, UID_USUARIO)
VALUES (17,113,'CARGA_INICIAL');
INSERT INTO TBEP_TIT_PREFERENTES_AREA (BEPARE_CODNUM, BEPTIT_CODNUM, UID_USUARIO)
VALUES (68,108,'CARGA_INICIAL');
INSERT INTO TBEP_TIT_PREFERENTES_AREA (BEPARE_CODNUM, BEPTIT_CODNUM, UID_USUARIO)
VALUES (68,109,'CARGA_INICIAL');
INSERT INTO TBEP_TIT_PREFERENTES_AREA (BEPARE_CODNUM, BEPTIT_CODNUM, UID_USUARIO)
VALUES (18,47,'CARGA_INICIAL');
INSERT INTO TBEP_TIT_PREFERENTES_AREA (BEPARE_CODNUM, BEPTIT_CODNUM, UID_USUARIO)
VALUES (18,48,'CARGA_INICIAL');
INSERT INTO TBEP_TIT_PREFERENTES_AREA (BEPARE_CODNUM, BEPTIT_CODNUM, UID_USUARIO)
VALUES (71,114,'CARGA_INICIAL');
INSERT INTO TBEP_TIT_PREFERENTES_AREA (BEPARE_CODNUM, BEPTIT_CODNUM, UID_USUARIO)
VALUES (71,115,'CARGA_INICIAL');
INSERT INTO TBEP_TIT_PREFERENTES_AREA (BEPARE_CODNUM, BEPTIT_CODNUM, UID_USUARIO)
VALUES (71,116,'CARGA_INICIAL');
INSERT INTO TBEP_TIT_PREFERENTES_AREA (BEPARE_CODNUM, BEPTIT_CODNUM, UID_USUARIO)
VALUES (71,19,'CARGA_INICIAL');
INSERT INTO TBEP_TIT_PREFERENTES_AREA (BEPARE_CODNUM, BEPTIT_CODNUM, UID_USUARIO)
VALUES (71,20,'CARGA_INICIAL');
INSERT INTO TBEP_TIT_PREFERENTES_AREA (BEPARE_CODNUM, BEPTIT_CODNUM, UID_USUARIO)
VALUES (72,117,'CARGA_INICIAL');
INSERT INTO TBEP_TIT_PREFERENTES_AREA (BEPARE_CODNUM, BEPTIT_CODNUM, UID_USUARIO)
VALUES (72,118,'CARGA_INICIAL');
INSERT INTO TBEP_TIT_PREFERENTES_AREA (BEPARE_CODNUM, BEPTIT_CODNUM, UID_USUARIO)
VALUES (73,47,'CARGA_INICIAL');
INSERT INTO TBEP_TIT_PREFERENTES_AREA (BEPARE_CODNUM, BEPTIT_CODNUM, UID_USUARIO)
VALUES (73,48,'CARGA_INICIAL');
INSERT INTO TBEP_TIT_PREFERENTES_AREA (BEPARE_CODNUM, BEPTIT_CODNUM, UID_USUARIO)
VALUES (74,47,'CARGA_INICIAL');
INSERT INTO TBEP_TIT_PREFERENTES_AREA (BEPARE_CODNUM, BEPTIT_CODNUM, UID_USUARIO)
VALUES (74,48,'CARGA_INICIAL');
INSERT INTO TBEP_TIT_PREFERENTES_AREA (BEPARE_CODNUM, BEPTIT_CODNUM, UID_USUARIO)
VALUES (76,45,'CARGA_INICIAL');
INSERT INTO TBEP_TIT_PREFERENTES_AREA (BEPARE_CODNUM, BEPTIT_CODNUM, UID_USUARIO)
VALUES (76,46,'CARGA_INICIAL');
INSERT INTO TBEP_TIT_PREFERENTES_AREA (BEPARE_CODNUM, BEPTIT_CODNUM, UID_USUARIO)
VALUES (76,119,'CARGA_INICIAL');
INSERT INTO TBEP_TIT_PREFERENTES_AREA (BEPARE_CODNUM, BEPTIT_CODNUM, UID_USUARIO)
VALUES (76,27,'CARGA_INICIAL');
INSERT INTO TBEP_TIT_PREFERENTES_AREA (BEPARE_CODNUM, BEPTIT_CODNUM, UID_USUARIO)
VALUES (76,28,'CARGA_INICIAL');
INSERT INTO TBEP_TIT_PREFERENTES_AREA (BEPARE_CODNUM, BEPTIT_CODNUM, UID_USUARIO)
VALUES (76,120,'CARGA_INICIAL');
INSERT INTO TBEP_TIT_PREFERENTES_AREA (BEPARE_CODNUM, BEPTIT_CODNUM, UID_USUARIO)
VALUES (76,121,'CARGA_INICIAL');
INSERT INTO TBEP_TIT_PREFERENTES_AREA (BEPARE_CODNUM, BEPTIT_CODNUM, UID_USUARIO)
VALUES (76,79,'CARGA_INICIAL');
INSERT INTO TBEP_TIT_PREFERENTES_AREA (BEPARE_CODNUM, BEPTIT_CODNUM, UID_USUARIO)
VALUES (76,122,'CARGA_INICIAL');
INSERT INTO TBEP_TIT_PREFERENTES_AREA (BEPARE_CODNUM, BEPTIT_CODNUM, UID_USUARIO)
VALUES (76,80,'CARGA_INICIAL');
INSERT INTO TBEP_TIT_PREFERENTES_AREA (BEPARE_CODNUM, BEPTIT_CODNUM, UID_USUARIO)
VALUES (76,123,'CARGA_INICIAL');
INSERT INTO TBEP_TIT_PREFERENTES_AREA (BEPARE_CODNUM, BEPTIT_CODNUM, UID_USUARIO)
VALUES (76,124,'CARGA_INICIAL');
INSERT INTO TBEP_TIT_PREFERENTES_AREA (BEPARE_CODNUM, BEPTIT_CODNUM, UID_USUARIO)
VALUES (78,81,'CARGA_INICIAL');
INSERT INTO TBEP_TIT_PREFERENTES_AREA (BEPARE_CODNUM, BEPTIT_CODNUM, UID_USUARIO)
VALUES (78,82,'CARGA_INICIAL');
INSERT INTO TBEP_TIT_PREFERENTES_AREA (BEPARE_CODNUM, BEPTIT_CODNUM, UID_USUARIO)
VALUES (79,63,'CARGA_INICIAL');
INSERT INTO TBEP_TIT_PREFERENTES_AREA (BEPARE_CODNUM, BEPTIT_CODNUM, UID_USUARIO)
VALUES (79,64,'CARGA_INICIAL');
INSERT INTO TBEP_TIT_PREFERENTES_AREA (BEPARE_CODNUM, BEPTIT_CODNUM, UID_USUARIO)
VALUES (79,65,'CARGA_INICIAL');
INSERT INTO TBEP_TIT_PREFERENTES_AREA (BEPARE_CODNUM, BEPTIT_CODNUM, UID_USUARIO)
VALUES (79,66,'CARGA_INICIAL');
INSERT INTO TBEP_TIT_PREFERENTES_AREA (BEPARE_CODNUM, BEPTIT_CODNUM, UID_USUARIO)
VALUES (79,67,'CARGA_INICIAL');
INSERT INTO TBEP_TIT_PREFERENTES_AREA (BEPARE_CODNUM, BEPTIT_CODNUM, UID_USUARIO)
VALUES (79,68,'CARGA_INICIAL');
INSERT INTO TBEP_TIT_PREFERENTES_AREA (BEPARE_CODNUM, BEPTIT_CODNUM, UID_USUARIO)
VALUES (79,174,'CARGA_INICIAL');
INSERT INTO TBEP_TIT_PREFERENTES_AREA (BEPARE_CODNUM, BEPTIT_CODNUM, UID_USUARIO)
VALUES (80,125,'CARGA_INICIAL');
INSERT INTO TBEP_TIT_PREFERENTES_AREA (BEPARE_CODNUM, BEPTIT_CODNUM, UID_USUARIO)
VALUES (80,46,'CARGA_INICIAL');
INSERT INTO TBEP_TIT_PREFERENTES_AREA (BEPARE_CODNUM, BEPTIT_CODNUM, UID_USUARIO)
VALUES (80,119,'CARGA_INICIAL');
INSERT INTO TBEP_TIT_PREFERENTES_AREA (BEPARE_CODNUM, BEPTIT_CODNUM, UID_USUARIO)
VALUES (80,126,'CARGA_INICIAL');
INSERT INTO TBEP_TIT_PREFERENTES_AREA (BEPARE_CODNUM, BEPTIT_CODNUM, UID_USUARIO)
VALUES (82,7,'CARGA_INICIAL');
INSERT INTO TBEP_TIT_PREFERENTES_AREA (BEPARE_CODNUM, BEPTIT_CODNUM, UID_USUARIO)
VALUES (82,8,'CARGA_INICIAL');
INSERT INTO TBEP_TIT_PREFERENTES_AREA (BEPARE_CODNUM, BEPTIT_CODNUM, UID_USUARIO)
VALUES (82,9,'CARGA_INICIAL');
INSERT INTO TBEP_TIT_PREFERENTES_AREA (BEPARE_CODNUM, BEPTIT_CODNUM, UID_USUARIO)
VALUES (82,10,'CARGA_INICIAL');
INSERT INTO TBEP_TIT_PREFERENTES_AREA (BEPARE_CODNUM, BEPTIT_CODNUM, UID_USUARIO)
VALUES (82,11,'CARGA_INICIAL');
INSERT INTO TBEP_TIT_PREFERENTES_AREA (BEPARE_CODNUM, BEPTIT_CODNUM, UID_USUARIO)
VALUES (82,12,'CARGA_INICIAL');
INSERT INTO TBEP_TIT_PREFERENTES_AREA (BEPARE_CODNUM, BEPTIT_CODNUM, UID_USUARIO)
VALUES (82,13,'CARGA_INICIAL');
INSERT INTO TBEP_TIT_PREFERENTES_AREA (BEPARE_CODNUM, BEPTIT_CODNUM, UID_USUARIO)
VALUES (82,14,'CARGA_INICIAL');
INSERT INTO TBEP_TIT_PREFERENTES_AREA (BEPARE_CODNUM, BEPTIT_CODNUM, UID_USUARIO)
VALUES (83,7,'CARGA_INICIAL');
INSERT INTO TBEP_TIT_PREFERENTES_AREA (BEPARE_CODNUM, BEPTIT_CODNUM, UID_USUARIO)
VALUES (83,8,'CARGA_INICIAL');
INSERT INTO TBEP_TIT_PREFERENTES_AREA (BEPARE_CODNUM, BEPTIT_CODNUM, UID_USUARIO)
VALUES (83,9,'CARGA_INICIAL');
INSERT INTO TBEP_TIT_PREFERENTES_AREA (BEPARE_CODNUM, BEPTIT_CODNUM, UID_USUARIO)
VALUES (83,10,'CARGA_INICIAL');
INSERT INTO TBEP_TIT_PREFERENTES_AREA (BEPARE_CODNUM, BEPTIT_CODNUM, UID_USUARIO)
VALUES (83,11,'CARGA_INICIAL');
INSERT INTO TBEP_TIT_PREFERENTES_AREA (BEPARE_CODNUM, BEPTIT_CODNUM, UID_USUARIO)
VALUES (83,12,'CARGA_INICIAL');
INSERT INTO TBEP_TIT_PREFERENTES_AREA (BEPARE_CODNUM, BEPTIT_CODNUM, UID_USUARIO)
VALUES (83,13,'CARGA_INICIAL');
INSERT INTO TBEP_TIT_PREFERENTES_AREA (BEPARE_CODNUM, BEPTIT_CODNUM, UID_USUARIO)
VALUES (83,14,'CARGA_INICIAL');
INSERT INTO TBEP_TIT_PREFERENTES_AREA (BEPARE_CODNUM, BEPTIT_CODNUM, UID_USUARIO)
VALUES (84,1,'CARGA_INICIAL');
INSERT INTO TBEP_TIT_PREFERENTES_AREA (BEPARE_CODNUM, BEPTIT_CODNUM, UID_USUARIO)
VALUES (84,2,'CARGA_INICIAL');
INSERT INTO TBEP_TIT_PREFERENTES_AREA (BEPARE_CODNUM, BEPTIT_CODNUM, UID_USUARIO)
VALUES (84,3,'CARGA_INICIAL');
INSERT INTO TBEP_TIT_PREFERENTES_AREA (BEPARE_CODNUM, BEPTIT_CODNUM, UID_USUARIO)
VALUES (84,4,'CARGA_INICIAL');
INSERT INTO TBEP_TIT_PREFERENTES_AREA (BEPARE_CODNUM, BEPTIT_CODNUM, UID_USUARIO)
VALUES (84,5,'CARGA_INICIAL');
INSERT INTO TBEP_TIT_PREFERENTES_AREA (BEPARE_CODNUM, BEPTIT_CODNUM, UID_USUARIO)
VALUES (85,1,'CARGA_INICIAL');
INSERT INTO TBEP_TIT_PREFERENTES_AREA (BEPARE_CODNUM, BEPTIT_CODNUM, UID_USUARIO)
VALUES (85,2,'CARGA_INICIAL');
INSERT INTO TBEP_TIT_PREFERENTES_AREA (BEPARE_CODNUM, BEPTIT_CODNUM, UID_USUARIO)
VALUES (85,3,'CARGA_INICIAL');
INSERT INTO TBEP_TIT_PREFERENTES_AREA (BEPARE_CODNUM, BEPTIT_CODNUM, UID_USUARIO)
VALUES (85,4,'CARGA_INICIAL');
INSERT INTO TBEP_TIT_PREFERENTES_AREA (BEPARE_CODNUM, BEPTIT_CODNUM, UID_USUARIO)
VALUES (85,5,'CARGA_INICIAL');
INSERT INTO TBEP_TIT_PREFERENTES_AREA (BEPARE_CODNUM, BEPTIT_CODNUM, UID_USUARIO)
VALUES (87,127,'CARGA_INICIAL');
INSERT INTO TBEP_TIT_PREFERENTES_AREA (BEPARE_CODNUM, BEPTIT_CODNUM, UID_USUARIO)
VALUES (87,4,'CARGA_INICIAL');
INSERT INTO TBEP_TIT_PREFERENTES_AREA (BEPARE_CODNUM, BEPTIT_CODNUM, UID_USUARIO)
VALUES (87,53,'CARGA_INICIAL');
INSERT INTO TBEP_TIT_PREFERENTES_AREA (BEPARE_CODNUM, BEPTIT_CODNUM, UID_USUARIO)
VALUES (87,5,'CARGA_INICIAL');
INSERT INTO TBEP_TIT_PREFERENTES_AREA (BEPARE_CODNUM, BEPTIT_CODNUM, UID_USUARIO)
VALUES (88,1,'CARGA_INICIAL');
INSERT INTO TBEP_TIT_PREFERENTES_AREA (BEPARE_CODNUM, BEPTIT_CODNUM, UID_USUARIO)
VALUES (88,4,'CARGA_INICIAL');
INSERT INTO TBEP_TIT_PREFERENTES_AREA (BEPARE_CODNUM, BEPTIT_CODNUM, UID_USUARIO)
VALUES (88,5,'CARGA_INICIAL');
INSERT INTO TBEP_TIT_PREFERENTES_AREA (BEPARE_CODNUM, BEPTIT_CODNUM, UID_USUARIO)
VALUES (88,53,'CARGA_INICIAL');
INSERT INTO TBEP_TIT_PREFERENTES_AREA (BEPARE_CODNUM, BEPTIT_CODNUM, UID_USUARIO)
VALUES (88,127,'CARGA_INICIAL');
INSERT INTO TBEP_TIT_PREFERENTES_AREA (BEPARE_CODNUM, BEPTIT_CODNUM, UID_USUARIO)
VALUES (89,51,'CARGA_INICIAL');
INSERT INTO TBEP_TIT_PREFERENTES_AREA (BEPARE_CODNUM, BEPTIT_CODNUM, UID_USUARIO)
VALUES (89,128,'CARGA_INICIAL');
INSERT INTO TBEP_TIT_PREFERENTES_AREA (BEPARE_CODNUM, BEPTIT_CODNUM, UID_USUARIO)
VALUES (89,54,'CARGA_INICIAL');
INSERT INTO TBEP_TIT_PREFERENTES_AREA (BEPARE_CODNUM, BEPTIT_CODNUM, UID_USUARIO)
VALUES (89,129,'CARGA_INICIAL');
INSERT INTO TBEP_TIT_PREFERENTES_AREA (BEPARE_CODNUM, BEPTIT_CODNUM, UID_USUARIO)
VALUES (90,17,'CARGA_INICIAL');
INSERT INTO TBEP_TIT_PREFERENTES_AREA (BEPARE_CODNUM, BEPTIT_CODNUM, UID_USUARIO)
VALUES (90,18,'CARGA_INICIAL');
INSERT INTO TBEP_TIT_PREFERENTES_AREA (BEPARE_CODNUM, BEPTIT_CODNUM, UID_USUARIO)
VALUES (90,19,'CARGA_INICIAL');
INSERT INTO TBEP_TIT_PREFERENTES_AREA (BEPARE_CODNUM, BEPTIT_CODNUM, UID_USUARIO)
VALUES (90,20,'CARGA_INICIAL');
INSERT INTO TBEP_TIT_PREFERENTES_AREA (BEPARE_CODNUM, BEPTIT_CODNUM, UID_USUARIO)
VALUES (91,63,'CARGA_INICIAL');
INSERT INTO TBEP_TIT_PREFERENTES_AREA (BEPARE_CODNUM, BEPTIT_CODNUM, UID_USUARIO)
VALUES (91,64,'CARGA_INICIAL');
INSERT INTO TBEP_TIT_PREFERENTES_AREA (BEPARE_CODNUM, BEPTIT_CODNUM, UID_USUARIO)
VALUES (91,65,'CARGA_INICIAL');
INSERT INTO TBEP_TIT_PREFERENTES_AREA (BEPARE_CODNUM, BEPTIT_CODNUM, UID_USUARIO)
VALUES (91,66,'CARGA_INICIAL');
INSERT INTO TBEP_TIT_PREFERENTES_AREA (BEPARE_CODNUM, BEPTIT_CODNUM, UID_USUARIO)
VALUES (91,67,'CARGA_INICIAL');
INSERT INTO TBEP_TIT_PREFERENTES_AREA (BEPARE_CODNUM, BEPTIT_CODNUM, UID_USUARIO)
VALUES (91,68,'CARGA_INICIAL');
INSERT INTO TBEP_TIT_PREFERENTES_AREA (BEPARE_CODNUM, BEPTIT_CODNUM, UID_USUARIO)
VALUES (91,174,'CARGA_INICIAL');
INSERT INTO TBEP_TIT_PREFERENTES_AREA (BEPARE_CODNUM, BEPTIT_CODNUM, UID_USUARIO)
VALUES (92,1,'CARGA_INICIAL');
INSERT INTO TBEP_TIT_PREFERENTES_AREA (BEPARE_CODNUM, BEPTIT_CODNUM, UID_USUARIO)
VALUES (92,98,'CARGA_INICIAL');
INSERT INTO TBEP_TIT_PREFERENTES_AREA (BEPARE_CODNUM, BEPTIT_CODNUM, UID_USUARIO)
VALUES (92,99,'CARGA_INICIAL');
INSERT INTO TBEP_TIT_PREFERENTES_AREA (BEPARE_CODNUM, BEPTIT_CODNUM, UID_USUARIO)
VALUES (92,50,'CARGA_INICIAL');
INSERT INTO TBEP_TIT_PREFERENTES_AREA (BEPARE_CODNUM, BEPTIT_CODNUM, UID_USUARIO)
VALUES (92,51,'CARGA_INICIAL');
INSERT INTO TBEP_TIT_PREFERENTES_AREA (BEPARE_CODNUM, BEPTIT_CODNUM, UID_USUARIO)
VALUES (92,101,'CARGA_INICIAL');
INSERT INTO TBEP_TIT_PREFERENTES_AREA (BEPARE_CODNUM, BEPTIT_CODNUM, UID_USUARIO)
VALUES (92,4,'CARGA_INICIAL');
INSERT INTO TBEP_TIT_PREFERENTES_AREA (BEPARE_CODNUM, BEPTIT_CODNUM, UID_USUARIO)
VALUES (93,1,'CARGA_INICIAL');
INSERT INTO TBEP_TIT_PREFERENTES_AREA (BEPARE_CODNUM, BEPTIT_CODNUM, UID_USUARIO)
VALUES (93,49,'CARGA_INICIAL');
INSERT INTO TBEP_TIT_PREFERENTES_AREA (BEPARE_CODNUM, BEPTIT_CODNUM, UID_USUARIO)
VALUES (93,50,'CARGA_INICIAL');
INSERT INTO TBEP_TIT_PREFERENTES_AREA (BEPARE_CODNUM, BEPTIT_CODNUM, UID_USUARIO)
VALUES (93,127,'CARGA_INICIAL');
INSERT INTO TBEP_TIT_PREFERENTES_AREA (BEPARE_CODNUM, BEPTIT_CODNUM, UID_USUARIO)
VALUES (93,4,'CARGA_INICIAL');
INSERT INTO TBEP_TIT_PREFERENTES_AREA (BEPARE_CODNUM, BEPTIT_CODNUM, UID_USUARIO)
VALUES (93,53,'CARGA_INICIAL');
INSERT INTO TBEP_TIT_PREFERENTES_AREA (BEPARE_CODNUM, BEPTIT_CODNUM, UID_USUARIO)
VALUES (93,5,'CARGA_INICIAL');
INSERT INTO TBEP_TIT_PREFERENTES_AREA (BEPARE_CODNUM, BEPTIT_CODNUM, UID_USUARIO)
VALUES (20,125,'CARGA_INICIAL');
INSERT INTO TBEP_TIT_PREFERENTES_AREA (BEPARE_CODNUM, BEPTIT_CODNUM, UID_USUARIO)
VALUES (20,45,'CARGA_INICIAL');
INSERT INTO TBEP_TIT_PREFERENTES_AREA (BEPARE_CODNUM, BEPTIT_CODNUM, UID_USUARIO)
VALUES (20,46,'CARGA_INICIAL');
INSERT INTO TBEP_TIT_PREFERENTES_AREA (BEPARE_CODNUM, BEPTIT_CODNUM, UID_USUARIO)
VALUES (20,120,'CARGA_INICIAL');
INSERT INTO TBEP_TIT_PREFERENTES_AREA (BEPARE_CODNUM, BEPTIT_CODNUM, UID_USUARIO)
VALUES (20,130,'CARGA_INICIAL');
INSERT INTO TBEP_TIT_PREFERENTES_AREA (BEPARE_CODNUM, BEPTIT_CODNUM, UID_USUARIO)
VALUES (20,126,'CARGA_INICIAL');
INSERT INTO TBEP_TIT_PREFERENTES_AREA (BEPARE_CODNUM, BEPTIT_CODNUM, UID_USUARIO)
VALUES (20,123,'CARGA_INICIAL');
INSERT INTO TBEP_TIT_PREFERENTES_AREA (BEPARE_CODNUM, BEPTIT_CODNUM, UID_USUARIO)
VALUES (95,131,'CARGA_INICIAL');
INSERT INTO TBEP_TIT_PREFERENTES_AREA (BEPARE_CODNUM, BEPTIT_CODNUM, UID_USUARIO)
VALUES (95,132,'CARGA_INICIAL');
INSERT INTO TBEP_TIT_PREFERENTES_AREA (BEPARE_CODNUM, BEPTIT_CODNUM, UID_USUARIO)
VALUES (95,133,'CARGA_INICIAL');
INSERT INTO TBEP_TIT_PREFERENTES_AREA (BEPARE_CODNUM, BEPTIT_CODNUM, UID_USUARIO)
VALUES (95,96,'CARGA_INICIAL');
INSERT INTO TBEP_TIT_PREFERENTES_AREA (BEPARE_CODNUM, BEPTIT_CODNUM, UID_USUARIO)
VALUES (96,97,'CARGA_INICIAL');
INSERT INTO TBEP_TIT_PREFERENTES_AREA (BEPARE_CODNUM, BEPTIT_CODNUM, UID_USUARIO)
VALUES (96,134,'CARGA_INICIAL');
INSERT INTO TBEP_TIT_PREFERENTES_AREA (BEPARE_CODNUM, BEPTIT_CODNUM, UID_USUARIO)
VALUES (97,135,'CARGA_INICIAL');
INSERT INTO TBEP_TIT_PREFERENTES_AREA (BEPARE_CODNUM, BEPTIT_CODNUM, UID_USUARIO)
VALUES (97,136,'CARGA_INICIAL');
INSERT INTO TBEP_TIT_PREFERENTES_AREA (BEPARE_CODNUM, BEPTIT_CODNUM, UID_USUARIO)
VALUES (97,137,'CARGA_INICIAL');
INSERT INTO TBEP_TIT_PREFERENTES_AREA (BEPARE_CODNUM, BEPTIT_CODNUM, UID_USUARIO)
VALUES (97,138,'CARGA_INICIAL');
INSERT INTO TBEP_TIT_PREFERENTES_AREA (BEPARE_CODNUM, BEPTIT_CODNUM, UID_USUARIO)
VALUES (97,97,'CARGA_INICIAL');
INSERT INTO TBEP_TIT_PREFERENTES_AREA (BEPARE_CODNUM, BEPTIT_CODNUM, UID_USUARIO)
VALUES (97,134,'CARGA_INICIAL');
INSERT INTO TBEP_TIT_PREFERENTES_AREA (BEPARE_CODNUM, BEPTIT_CODNUM, UID_USUARIO)
VALUES (98,97,'CARGA_INICIAL');
INSERT INTO TBEP_TIT_PREFERENTES_AREA (BEPARE_CODNUM, BEPTIT_CODNUM, UID_USUARIO)
VALUES (98,134,'CARGA_INICIAL');
INSERT INTO TBEP_TIT_PREFERENTES_AREA (BEPARE_CODNUM, BEPTIT_CODNUM, UID_USUARIO)
VALUES (99,97,'CARGA_INICIAL');
INSERT INTO TBEP_TIT_PREFERENTES_AREA (BEPARE_CODNUM, BEPTIT_CODNUM, UID_USUARIO)
VALUES (99,134,'CARGA_INICIAL');
INSERT INTO TBEP_TIT_PREFERENTES_AREA (BEPARE_CODNUM, BEPTIT_CODNUM, UID_USUARIO)
VALUES (100,139,'CARGA_INICIAL');
INSERT INTO TBEP_TIT_PREFERENTES_AREA (BEPARE_CODNUM, BEPTIT_CODNUM, UID_USUARIO)
VALUES (100,6,'CARGA_INICIAL');
INSERT INTO TBEP_TIT_PREFERENTES_AREA (BEPARE_CODNUM, BEPTIT_CODNUM, UID_USUARIO)
VALUES (100,140,'CARGA_INICIAL');
INSERT INTO TBEP_TIT_PREFERENTES_AREA (BEPARE_CODNUM, BEPTIT_CODNUM, UID_USUARIO)
VALUES (100,7,'CARGA_INICIAL');
INSERT INTO TBEP_TIT_PREFERENTES_AREA (BEPARE_CODNUM, BEPTIT_CODNUM, UID_USUARIO)
VALUES (100,11,'CARGA_INICIAL');
INSERT INTO TBEP_TIT_PREFERENTES_AREA (BEPARE_CODNUM, BEPTIT_CODNUM, UID_USUARIO)
VALUES (100,141,'CARGA_INICIAL');
INSERT INTO TBEP_TIT_PREFERENTES_AREA (BEPARE_CODNUM, BEPTIT_CODNUM, UID_USUARIO)
VALUES (101,138,'CARGA_INICIAL');
INSERT INTO TBEP_TIT_PREFERENTES_AREA (BEPARE_CODNUM, BEPTIT_CODNUM, UID_USUARIO)
VALUES (101,135,'CARGA_INICIAL');
INSERT INTO TBEP_TIT_PREFERENTES_AREA (BEPARE_CODNUM, BEPTIT_CODNUM, UID_USUARIO)
VALUES (102,46,'CARGA_INICIAL');
INSERT INTO TBEP_TIT_PREFERENTES_AREA (BEPARE_CODNUM, BEPTIT_CODNUM, UID_USUARIO)
VALUES (102,122,'CARGA_INICIAL');
INSERT INTO TBEP_TIT_PREFERENTES_AREA (BEPARE_CODNUM, BEPTIT_CODNUM, UID_USUARIO)
VALUES (102,80,'CARGA_INICIAL');
INSERT INTO TBEP_TIT_PREFERENTES_AREA (BEPARE_CODNUM, BEPTIT_CODNUM, UID_USUARIO)
VALUES (103,40,'CARGA_INICIAL');
INSERT INTO TBEP_TIT_PREFERENTES_AREA (BEPARE_CODNUM, BEPTIT_CODNUM, UID_USUARIO)
VALUES (103,41,'CARGA_INICIAL');
INSERT INTO TBEP_TIT_PREFERENTES_AREA (BEPARE_CODNUM, BEPTIT_CODNUM, UID_USUARIO)
VALUES (103,42,'CARGA_INICIAL');
INSERT INTO TBEP_TIT_PREFERENTES_AREA (BEPARE_CODNUM, BEPTIT_CODNUM, UID_USUARIO)
VALUES (103,142,'CARGA_INICIAL');
INSERT INTO TBEP_TIT_PREFERENTES_AREA (BEPARE_CODNUM, BEPTIT_CODNUM, UID_USUARIO)
VALUES (103,143,'CARGA_INICIAL');
INSERT INTO TBEP_TIT_PREFERENTES_AREA (BEPARE_CODNUM, BEPTIT_CODNUM, UID_USUARIO)
VALUES (104,112,'CARGA_INICIAL');
INSERT INTO TBEP_TIT_PREFERENTES_AREA (BEPARE_CODNUM, BEPTIT_CODNUM, UID_USUARIO)
VALUES (104,113,'CARGA_INICIAL');
INSERT INTO TBEP_TIT_PREFERENTES_AREA (BEPARE_CODNUM, BEPTIT_CODNUM, UID_USUARIO)
VALUES (105,40,'CARGA_INICIAL');
INSERT INTO TBEP_TIT_PREFERENTES_AREA (BEPARE_CODNUM, BEPTIT_CODNUM, UID_USUARIO)
VALUES (105,41,'CARGA_INICIAL');
INSERT INTO TBEP_TIT_PREFERENTES_AREA (BEPARE_CODNUM, BEPTIT_CODNUM, UID_USUARIO)
VALUES (105,42,'CARGA_INICIAL');
INSERT INTO TBEP_TIT_PREFERENTES_AREA (BEPARE_CODNUM, BEPTIT_CODNUM, UID_USUARIO)
VALUES (105,142,'CARGA_INICIAL');
INSERT INTO TBEP_TIT_PREFERENTES_AREA (BEPARE_CODNUM, BEPTIT_CODNUM, UID_USUARIO)
VALUES (105,143,'CARGA_INICIAL');
INSERT INTO TBEP_TIT_PREFERENTES_AREA (BEPARE_CODNUM, BEPTIT_CODNUM, UID_USUARIO)
VALUES (106,40,'CARGA_INICIAL');
INSERT INTO TBEP_TIT_PREFERENTES_AREA (BEPARE_CODNUM, BEPTIT_CODNUM, UID_USUARIO)
VALUES (106,41,'CARGA_INICIAL');
INSERT INTO TBEP_TIT_PREFERENTES_AREA (BEPARE_CODNUM, BEPTIT_CODNUM, UID_USUARIO)
VALUES (106,42,'CARGA_INICIAL');
INSERT INTO TBEP_TIT_PREFERENTES_AREA (BEPARE_CODNUM, BEPTIT_CODNUM, UID_USUARIO)
VALUES (106,144,'CARGA_INICIAL');
INSERT INTO TBEP_TIT_PREFERENTES_AREA (BEPARE_CODNUM, BEPTIT_CODNUM, UID_USUARIO)
VALUES (106,145,'CARGA_INICIAL');
INSERT INTO TBEP_TIT_PREFERENTES_AREA (BEPARE_CODNUM, BEPTIT_CODNUM, UID_USUARIO)
VALUES (106,146,'CARGA_INICIAL');
INSERT INTO TBEP_TIT_PREFERENTES_AREA (BEPARE_CODNUM, BEPTIT_CODNUM, UID_USUARIO)
VALUES (106,147,'CARGA_INICIAL');
INSERT INTO TBEP_TIT_PREFERENTES_AREA (BEPARE_CODNUM, BEPTIT_CODNUM, UID_USUARIO)
VALUES (107,97,'CARGA_INICIAL');
INSERT INTO TBEP_TIT_PREFERENTES_AREA (BEPARE_CODNUM, BEPTIT_CODNUM, UID_USUARIO)
VALUES (107,134,'CARGA_INICIAL');
INSERT INTO TBEP_TIT_PREFERENTES_AREA (BEPARE_CODNUM, BEPTIT_CODNUM, UID_USUARIO)
VALUES (108,148,'CARGA_INICIAL');
INSERT INTO TBEP_TIT_PREFERENTES_AREA (BEPARE_CODNUM, BEPTIT_CODNUM, UID_USUARIO)
VALUES (108,43,'CARGA_INICIAL');
INSERT INTO TBEP_TIT_PREFERENTES_AREA (BEPARE_CODNUM, BEPTIT_CODNUM, UID_USUARIO)
VALUES (108,44,'CARGA_INICIAL');
INSERT INTO TBEP_TIT_PREFERENTES_AREA (BEPARE_CODNUM, BEPTIT_CODNUM, UID_USUARIO)
VALUES (22,139,'CARGA_INICIAL');
INSERT INTO TBEP_TIT_PREFERENTES_AREA (BEPARE_CODNUM, BEPTIT_CODNUM, UID_USUARIO)
VALUES (22,125,'CARGA_INICIAL');
INSERT INTO TBEP_TIT_PREFERENTES_AREA (BEPARE_CODNUM, BEPTIT_CODNUM, UID_USUARIO)
VALUES (22,45,'CARGA_INICIAL');
INSERT INTO TBEP_TIT_PREFERENTES_AREA (BEPARE_CODNUM, BEPTIT_CODNUM, UID_USUARIO)
VALUES (22,46,'CARGA_INICIAL');
INSERT INTO TBEP_TIT_PREFERENTES_AREA (BEPARE_CODNUM, BEPTIT_CODNUM, UID_USUARIO)
VALUES (22,119,'CARGA_INICIAL');
INSERT INTO TBEP_TIT_PREFERENTES_AREA (BEPARE_CODNUM, BEPTIT_CODNUM, UID_USUARIO)
VALUES (22,120,'CARGA_INICIAL');
INSERT INTO TBEP_TIT_PREFERENTES_AREA (BEPARE_CODNUM, BEPTIT_CODNUM, UID_USUARIO)
VALUES (22,121,'CARGA_INICIAL');
INSERT INTO TBEP_TIT_PREFERENTES_AREA (BEPARE_CODNUM, BEPTIT_CODNUM, UID_USUARIO)
VALUES (22,149,'CARGA_INICIAL');
INSERT INTO TBEP_TIT_PREFERENTES_AREA (BEPARE_CODNUM, BEPTIT_CODNUM, UID_USUARIO)
VALUES (22,130,'CARGA_INICIAL');
INSERT INTO TBEP_TIT_PREFERENTES_AREA (BEPARE_CODNUM, BEPTIT_CODNUM, UID_USUARIO)
VALUES (22,122,'CARGA_INICIAL');
INSERT INTO TBEP_TIT_PREFERENTES_AREA (BEPARE_CODNUM, BEPTIT_CODNUM, UID_USUARIO)
VALUES (22,126,'CARGA_INICIAL');
INSERT INTO TBEP_TIT_PREFERENTES_AREA (BEPARE_CODNUM, BEPTIT_CODNUM, UID_USUARIO)
VALUES (22,150,'CARGA_INICIAL');
INSERT INTO TBEP_TIT_PREFERENTES_AREA (BEPARE_CODNUM, BEPTIT_CODNUM, UID_USUARIO)
VALUES (22,123,'CARGA_INICIAL');
INSERT INTO TBEP_TIT_PREFERENTES_AREA (BEPARE_CODNUM, BEPTIT_CODNUM, UID_USUARIO)
VALUES (22,124,'CARGA_INICIAL');
INSERT INTO TBEP_TIT_PREFERENTES_AREA (BEPARE_CODNUM, BEPTIT_CODNUM, UID_USUARIO)
VALUES (109,151,'CARGA_INICIAL');
INSERT INTO TBEP_TIT_PREFERENTES_AREA (BEPARE_CODNUM, BEPTIT_CODNUM, UID_USUARIO)
VALUES (109,152,'CARGA_INICIAL');
INSERT INTO TBEP_TIT_PREFERENTES_AREA (BEPARE_CODNUM, BEPTIT_CODNUM, UID_USUARIO)
VALUES (109,97,'CARGA_INICIAL');
INSERT INTO TBEP_TIT_PREFERENTES_AREA (BEPARE_CODNUM, BEPTIT_CODNUM, UID_USUARIO)
VALUES (109,134,'CARGA_INICIAL');
INSERT INTO TBEP_TIT_PREFERENTES_AREA (BEPARE_CODNUM, BEPTIT_CODNUM, UID_USUARIO)
VALUES (110,97,'CARGA_INICIAL');
INSERT INTO TBEP_TIT_PREFERENTES_AREA (BEPARE_CODNUM, BEPTIT_CODNUM, UID_USUARIO)
VALUES (110,134,'CARGA_INICIAL');
INSERT INTO TBEP_TIT_PREFERENTES_AREA (BEPARE_CODNUM, BEPTIT_CODNUM, UID_USUARIO)
VALUES (112,71,'CARGA_INICIAL');
INSERT INTO TBEP_TIT_PREFERENTES_AREA (BEPARE_CODNUM, BEPTIT_CODNUM, UID_USUARIO)
VALUES (112,72,'CARGA_INICIAL');
INSERT INTO TBEP_TIT_PREFERENTES_AREA (BEPARE_CODNUM, BEPTIT_CODNUM, UID_USUARIO)
VALUES (112,120,'CARGA_INICIAL');
INSERT INTO TBEP_TIT_PREFERENTES_AREA (BEPARE_CODNUM, BEPTIT_CODNUM, UID_USUARIO)
VALUES (112,79,'CARGA_INICIAL');
INSERT INTO TBEP_TIT_PREFERENTES_AREA (BEPARE_CODNUM, BEPTIT_CODNUM, UID_USUARIO)
VALUES (112,122,'CARGA_INICIAL');
INSERT INTO TBEP_TIT_PREFERENTES_AREA (BEPARE_CODNUM, BEPTIT_CODNUM, UID_USUARIO)
VALUES (112,80,'CARGA_INICIAL');
INSERT INTO TBEP_TIT_PREFERENTES_AREA (BEPARE_CODNUM, BEPTIT_CODNUM, UID_USUARIO)
VALUES (112,123,'CARGA_INICIAL');
INSERT INTO TBEP_TIT_PREFERENTES_AREA (BEPARE_CODNUM, BEPTIT_CODNUM, UID_USUARIO)
VALUES (112,124,'CARGA_INICIAL');
INSERT INTO TBEP_TIT_PREFERENTES_AREA (BEPARE_CODNUM, BEPTIT_CODNUM, UID_USUARIO)
VALUES (113,153,'CARGA_INICIAL');
INSERT INTO TBEP_TIT_PREFERENTES_AREA (BEPARE_CODNUM, BEPTIT_CODNUM, UID_USUARIO)
VALUES (113,154,'CARGA_INICIAL');
INSERT INTO TBEP_TIT_PREFERENTES_AREA (BEPARE_CODNUM, BEPTIT_CODNUM, UID_USUARIO)
VALUES (113,155,'CARGA_INICIAL');
INSERT INTO TBEP_TIT_PREFERENTES_AREA (BEPARE_CODNUM, BEPTIT_CODNUM, UID_USUARIO)
VALUES (114,55,'CARGA_INICIAL');
INSERT INTO TBEP_TIT_PREFERENTES_AREA (BEPARE_CODNUM, BEPTIT_CODNUM, UID_USUARIO)
VALUES (114,56,'CARGA_INICIAL');
INSERT INTO TBEP_TIT_PREFERENTES_AREA (BEPARE_CODNUM, BEPTIT_CODNUM, UID_USUARIO)
VALUES (114,57,'CARGA_INICIAL');
INSERT INTO TBEP_TIT_PREFERENTES_AREA (BEPARE_CODNUM, BEPTIT_CODNUM, UID_USUARIO)
VALUES (114,58,'CARGA_INICIAL');
INSERT INTO TBEP_TIT_PREFERENTES_AREA (BEPARE_CODNUM, BEPTIT_CODNUM, UID_USUARIO)
VALUES (114,59,'CARGA_INICIAL');
INSERT INTO TBEP_TIT_PREFERENTES_AREA (BEPARE_CODNUM, BEPTIT_CODNUM, UID_USUARIO)
VALUES (114,60,'CARGA_INICIAL');
INSERT INTO TBEP_TIT_PREFERENTES_AREA (BEPARE_CODNUM, BEPTIT_CODNUM, UID_USUARIO)
VALUES (114,61,'CARGA_INICIAL');
INSERT INTO TBEP_TIT_PREFERENTES_AREA (BEPARE_CODNUM, BEPTIT_CODNUM, UID_USUARIO)
VALUES (114,62,'CARGA_INICIAL');
INSERT INTO TBEP_TIT_PREFERENTES_AREA (BEPARE_CODNUM, BEPTIT_CODNUM, UID_USUARIO)
VALUES (115,45,'CARGA_INICIAL');
INSERT INTO TBEP_TIT_PREFERENTES_AREA (BEPARE_CODNUM, BEPTIT_CODNUM, UID_USUARIO)
VALUES (115,46,'CARGA_INICIAL');
INSERT INTO TBEP_TIT_PREFERENTES_AREA (BEPARE_CODNUM, BEPTIT_CODNUM, UID_USUARIO)
VALUES (115,122,'CARGA_INICIAL');
INSERT INTO TBEP_TIT_PREFERENTES_AREA (BEPARE_CODNUM, BEPTIT_CODNUM, UID_USUARIO)
VALUES (115,124,'CARGA_INICIAL');
INSERT INTO TBEP_TIT_PREFERENTES_AREA (BEPARE_CODNUM, BEPTIT_CODNUM, UID_USUARIO)
VALUES (116,32,'CARGA_INICIAL');
INSERT INTO TBEP_TIT_PREFERENTES_AREA (BEPARE_CODNUM, BEPTIT_CODNUM, UID_USUARIO)
VALUES (116,33,'CARGA_INICIAL');
INSERT INTO TBEP_TIT_PREFERENTES_AREA (BEPARE_CODNUM, BEPTIT_CODNUM, UID_USUARIO)
VALUES (116,34,'CARGA_INICIAL');
INSERT INTO TBEP_TIT_PREFERENTES_AREA (BEPARE_CODNUM, BEPTIT_CODNUM, UID_USUARIO)
VALUES (116,35,'CARGA_INICIAL');
INSERT INTO TBEP_TIT_PREFERENTES_AREA (BEPARE_CODNUM, BEPTIT_CODNUM, UID_USUARIO)
VALUES (24,139,'CARGA_INICIAL');
INSERT INTO TBEP_TIT_PREFERENTES_AREA (BEPARE_CODNUM, BEPTIT_CODNUM, UID_USUARIO)
VALUES (24,6,'CARGA_INICIAL');
INSERT INTO TBEP_TIT_PREFERENTES_AREA (BEPARE_CODNUM, BEPTIT_CODNUM, UID_USUARIO)
VALUES (24,140,'CARGA_INICIAL');
INSERT INTO TBEP_TIT_PREFERENTES_AREA (BEPARE_CODNUM, BEPTIT_CODNUM, UID_USUARIO)
VALUES (24,156,'CARGA_INICIAL');
INSERT INTO TBEP_TIT_PREFERENTES_AREA (BEPARE_CODNUM, BEPTIT_CODNUM, UID_USUARIO)
VALUES (24,91,'CARGA_INICIAL');
INSERT INTO TBEP_TIT_PREFERENTES_AREA (BEPARE_CODNUM, BEPTIT_CODNUM, UID_USUARIO)
VALUES (24,92,'CARGA_INICIAL');
INSERT INTO TBEP_TIT_PREFERENTES_AREA (BEPARE_CODNUM, BEPTIT_CODNUM, UID_USUARIO)
VALUES (24,141,'CARGA_INICIAL');
INSERT INTO TBEP_TIT_PREFERENTES_AREA (BEPARE_CODNUM, BEPTIT_CODNUM, UID_USUARIO)
VALUES (24,96,'CARGA_INICIAL');
INSERT INTO TBEP_TIT_PREFERENTES_AREA (BEPARE_CODNUM, BEPTIT_CODNUM, UID_USUARIO)
VALUES (24,97,'CARGA_INICIAL');
INSERT INTO TBEP_TIT_PREFERENTES_AREA (BEPARE_CODNUM, BEPTIT_CODNUM, UID_USUARIO)
VALUES (117,64,'CARGA_INICIAL');
INSERT INTO TBEP_TIT_PREFERENTES_AREA (BEPARE_CODNUM, BEPTIT_CODNUM, UID_USUARIO)
VALUES (117,65,'CARGA_INICIAL');
INSERT INTO TBEP_TIT_PREFERENTES_AREA (BEPARE_CODNUM, BEPTIT_CODNUM, UID_USUARIO)
VALUES (117,174,'CARGA_INICIAL');
INSERT INTO TBEP_TIT_PREFERENTES_AREA (BEPARE_CODNUM, BEPTIT_CODNUM, UID_USUARIO)
VALUES (117,67,'CARGA_INICIAL');
INSERT INTO TBEP_TIT_PREFERENTES_AREA (BEPARE_CODNUM, BEPTIT_CODNUM, UID_USUARIO)
VALUES (117,68,'CARGA_INICIAL');
INSERT INTO TBEP_TIT_PREFERENTES_AREA (BEPARE_CODNUM, BEPTIT_CODNUM, UID_USUARIO)
VALUES (118,153,'CARGA_INICIAL');
INSERT INTO TBEP_TIT_PREFERENTES_AREA (BEPARE_CODNUM, BEPTIT_CODNUM, UID_USUARIO)
VALUES (118,154,'CARGA_INICIAL');
INSERT INTO TBEP_TIT_PREFERENTES_AREA (BEPARE_CODNUM, BEPTIT_CODNUM, UID_USUARIO)
VALUES (118,155,'CARGA_INICIAL');
INSERT INTO TBEP_TIT_PREFERENTES_AREA (BEPARE_CODNUM, BEPTIT_CODNUM, UID_USUARIO)
VALUES (119,1,'CARGA_INICIAL');
INSERT INTO TBEP_TIT_PREFERENTES_AREA (BEPARE_CODNUM, BEPTIT_CODNUM, UID_USUARIO)
VALUES (119,98,'CARGA_INICIAL');
INSERT INTO TBEP_TIT_PREFERENTES_AREA (BEPARE_CODNUM, BEPTIT_CODNUM, UID_USUARIO)
VALUES (119,99,'CARGA_INICIAL');
INSERT INTO TBEP_TIT_PREFERENTES_AREA (BEPARE_CODNUM, BEPTIT_CODNUM, UID_USUARIO)
VALUES (119,50,'CARGA_INICIAL');
INSERT INTO TBEP_TIT_PREFERENTES_AREA (BEPARE_CODNUM, BEPTIT_CODNUM, UID_USUARIO)
VALUES (119,100,'CARGA_INICIAL');
INSERT INTO TBEP_TIT_PREFERENTES_AREA (BEPARE_CODNUM, BEPTIT_CODNUM, UID_USUARIO)
VALUES (119,101,'CARGA_INICIAL');
INSERT INTO TBEP_TIT_PREFERENTES_AREA (BEPARE_CODNUM, BEPTIT_CODNUM, UID_USUARIO)
VALUES (119,4,'CARGA_INICIAL');
INSERT INTO TBEP_TIT_PREFERENTES_AREA (BEPARE_CODNUM, BEPTIT_CODNUM, UID_USUARIO)
VALUES (25,16,'CARGA_INICIAL');
INSERT INTO TBEP_TIT_PREFERENTES_AREA (BEPARE_CODNUM, BEPTIT_CODNUM, UID_USUARIO)
VALUES (25,114,'CARGA_INICIAL');
INSERT INTO TBEP_TIT_PREFERENTES_AREA (BEPARE_CODNUM, BEPTIT_CODNUM, UID_USUARIO)
VALUES (25,157,'CARGA_INICIAL');
INSERT INTO TBEP_TIT_PREFERENTES_AREA (BEPARE_CODNUM, BEPTIT_CODNUM, UID_USUARIO)
VALUES (25,115,'CARGA_INICIAL');
INSERT INTO TBEP_TIT_PREFERENTES_AREA (BEPARE_CODNUM, BEPTIT_CODNUM, UID_USUARIO)
VALUES (25,116,'CARGA_INICIAL');
INSERT INTO TBEP_TIT_PREFERENTES_AREA (BEPARE_CODNUM, BEPTIT_CODNUM, UID_USUARIO)
VALUES (25,158,'CARGA_INICIAL');
INSERT INTO TBEP_TIT_PREFERENTES_AREA (BEPARE_CODNUM, BEPTIT_CODNUM, UID_USUARIO)
VALUES (25,159,'CARGA_INICIAL');
INSERT INTO TBEP_TIT_PREFERENTES_AREA (BEPARE_CODNUM, BEPTIT_CODNUM, UID_USUARIO)
VALUES (25,160,'CARGA_INICIAL');
INSERT INTO TBEP_TIT_PREFERENTES_AREA (BEPARE_CODNUM, BEPTIT_CODNUM, UID_USUARIO)
VALUES (120,13,'CARGA_INICIAL');
INSERT INTO TBEP_TIT_PREFERENTES_AREA (BEPARE_CODNUM, BEPTIT_CODNUM, UID_USUARIO)
VALUES (120,88,'CARGA_INICIAL');
INSERT INTO TBEP_TIT_PREFERENTES_AREA (BEPARE_CODNUM, BEPTIT_CODNUM, UID_USUARIO)
VALUES (121,91,'CARGA_INICIAL');
INSERT INTO TBEP_TIT_PREFERENTES_AREA (BEPARE_CODNUM, BEPTIT_CODNUM, UID_USUARIO)
VALUES (121,92,'CARGA_INICIAL');
INSERT INTO TBEP_TIT_PREFERENTES_AREA (BEPARE_CODNUM, BEPTIT_CODNUM, UID_USUARIO)
VALUES (121,10,'CARGA_INICIAL');
INSERT INTO TBEP_TIT_PREFERENTES_AREA (BEPARE_CODNUM, BEPTIT_CODNUM, UID_USUARIO)
VALUES (121,93,'CARGA_INICIAL');
INSERT INTO TBEP_TIT_PREFERENTES_AREA (BEPARE_CODNUM, BEPTIT_CODNUM, UID_USUARIO)
VALUES (121,94,'CARGA_INICIAL');
INSERT INTO TBEP_TIT_PREFERENTES_AREA (BEPARE_CODNUM, BEPTIT_CODNUM, UID_USUARIO)
VALUES (121,95,'CARGA_INICIAL');
INSERT INTO TBEP_TIT_PREFERENTES_AREA (BEPARE_CODNUM, BEPTIT_CODNUM, UID_USUARIO)
VALUES (121,96,'CARGA_INICIAL');
INSERT INTO TBEP_TIT_PREFERENTES_AREA (BEPARE_CODNUM, BEPTIT_CODNUM, UID_USUARIO)
VALUES (121,97,'CARGA_INICIAL');
INSERT INTO TBEP_TIT_PREFERENTES_AREA (BEPARE_CODNUM, BEPTIT_CODNUM, UID_USUARIO)
VALUES (121,13,'CARGA_INICIAL');
INSERT INTO TBEP_TIT_PREFERENTES_AREA (BEPARE_CODNUM, BEPTIT_CODNUM, UID_USUARIO)
VALUES (122,153,'CARGA_INICIAL');
INSERT INTO TBEP_TIT_PREFERENTES_AREA (BEPARE_CODNUM, BEPTIT_CODNUM, UID_USUARIO)
VALUES (122,154,'CARGA_INICIAL');
INSERT INTO TBEP_TIT_PREFERENTES_AREA (BEPARE_CODNUM, BEPTIT_CODNUM, UID_USUARIO)
VALUES (122,155,'CARGA_INICIAL');
INSERT INTO TBEP_TIT_PREFERENTES_AREA (BEPARE_CODNUM, BEPTIT_CODNUM, UID_USUARIO)
VALUES (123,153,'CARGA_INICIAL');
INSERT INTO TBEP_TIT_PREFERENTES_AREA (BEPARE_CODNUM, BEPTIT_CODNUM, UID_USUARIO)
VALUES (123,154,'CARGA_INICIAL');
INSERT INTO TBEP_TIT_PREFERENTES_AREA (BEPARE_CODNUM, BEPTIT_CODNUM, UID_USUARIO)
VALUES (123,155,'CARGA_INICIAL');
INSERT INTO TBEP_TIT_PREFERENTES_AREA (BEPARE_CODNUM, BEPTIT_CODNUM, UID_USUARIO)
VALUES (124,153,'CARGA_INICIAL');
INSERT INTO TBEP_TIT_PREFERENTES_AREA (BEPARE_CODNUM, BEPTIT_CODNUM, UID_USUARIO)
VALUES (124,154,'CARGA_INICIAL');
INSERT INTO TBEP_TIT_PREFERENTES_AREA (BEPARE_CODNUM, BEPTIT_CODNUM, UID_USUARIO)
VALUES (124,155,'CARGA_INICIAL');
INSERT INTO TBEP_TIT_PREFERENTES_AREA (BEPARE_CODNUM, BEPTIT_CODNUM, UID_USUARIO)
VALUES (125,153,'CARGA_INICIAL');
INSERT INTO TBEP_TIT_PREFERENTES_AREA (BEPARE_CODNUM, BEPTIT_CODNUM, UID_USUARIO)
VALUES (125,154,'CARGA_INICIAL');
INSERT INTO TBEP_TIT_PREFERENTES_AREA (BEPARE_CODNUM, BEPTIT_CODNUM, UID_USUARIO)
VALUES (125,155,'CARGA_INICIAL');
INSERT INTO TBEP_TIT_PREFERENTES_AREA (BEPARE_CODNUM, BEPTIT_CODNUM, UID_USUARIO)
VALUES (26,112,'CARGA_INICIAL');
INSERT INTO TBEP_TIT_PREFERENTES_AREA (BEPARE_CODNUM, BEPTIT_CODNUM, UID_USUARIO)
VALUES (26,113,'CARGA_INICIAL');
INSERT INTO TBEP_TIT_PREFERENTES_AREA (BEPARE_CODNUM, BEPTIT_CODNUM, UID_USUARIO)
VALUES (126,139,'CARGA_INICIAL');
INSERT INTO TBEP_TIT_PREFERENTES_AREA (BEPARE_CODNUM, BEPTIT_CODNUM, UID_USUARIO)
VALUES (126,6,'CARGA_INICIAL');
INSERT INTO TBEP_TIT_PREFERENTES_AREA (BEPARE_CODNUM, BEPTIT_CODNUM, UID_USUARIO)
VALUES (126,161,'CARGA_INICIAL');
INSERT INTO TBEP_TIT_PREFERENTES_AREA (BEPARE_CODNUM, BEPTIT_CODNUM, UID_USUARIO)
VALUES (126,122,'CARGA_INICIAL');
INSERT INTO TBEP_TIT_PREFERENTES_AREA (BEPARE_CODNUM, BEPTIT_CODNUM, UID_USUARIO)
VALUES (126,15,'CARGA_INICIAL');
INSERT INTO TBEP_TIT_PREFERENTES_AREA (BEPARE_CODNUM, BEPTIT_CODNUM, UID_USUARIO)
VALUES (126,124,'CARGA_INICIAL');
INSERT INTO TBEP_TIT_PREFERENTES_AREA (BEPARE_CODNUM, BEPTIT_CODNUM, UID_USUARIO)
VALUES (127,139,'CARGA_INICIAL');
INSERT INTO TBEP_TIT_PREFERENTES_AREA (BEPARE_CODNUM, BEPTIT_CODNUM, UID_USUARIO)
VALUES (127,6,'CARGA_INICIAL');
INSERT INTO TBEP_TIT_PREFERENTES_AREA (BEPARE_CODNUM, BEPTIT_CODNUM, UID_USUARIO)
VALUES (127,161,'CARGA_INICIAL');
INSERT INTO TBEP_TIT_PREFERENTES_AREA (BEPARE_CODNUM, BEPTIT_CODNUM, UID_USUARIO)
VALUES (127,122,'CARGA_INICIAL');
INSERT INTO TBEP_TIT_PREFERENTES_AREA (BEPARE_CODNUM, BEPTIT_CODNUM, UID_USUARIO)
VALUES (127,47,'CARGA_INICIAL');
INSERT INTO TBEP_TIT_PREFERENTES_AREA (BEPARE_CODNUM, BEPTIT_CODNUM, UID_USUARIO)
VALUES (127,15,'CARGA_INICIAL');
INSERT INTO TBEP_TIT_PREFERENTES_AREA (BEPARE_CODNUM, BEPTIT_CODNUM, UID_USUARIO)
VALUES (127,48,'CARGA_INICIAL');
INSERT INTO TBEP_TIT_PREFERENTES_AREA (BEPARE_CODNUM, BEPTIT_CODNUM, UID_USUARIO)
VALUES (127,124,'CARGA_INICIAL');
INSERT INTO TBEP_TIT_PREFERENTES_AREA (BEPARE_CODNUM, BEPTIT_CODNUM, UID_USUARIO)
VALUES (128,6,'CARGA_INICIAL');
INSERT INTO TBEP_TIT_PREFERENTES_AREA (BEPARE_CODNUM, BEPTIT_CODNUM, UID_USUARIO)
VALUES (128,122,'CARGA_INICIAL');
INSERT INTO TBEP_TIT_PREFERENTES_AREA (BEPARE_CODNUM, BEPTIT_CODNUM, UID_USUARIO)
VALUES (128,15,'CARGA_INICIAL');
INSERT INTO TBEP_TIT_PREFERENTES_AREA (BEPARE_CODNUM, BEPTIT_CODNUM, UID_USUARIO)
VALUES (128,124,'CARGA_INICIAL');
INSERT INTO TBEP_TIT_PREFERENTES_AREA (BEPARE_CODNUM, BEPTIT_CODNUM, UID_USUARIO)
VALUES (130,160,'CARGA_INICIAL');
INSERT INTO TBEP_TIT_PREFERENTES_AREA (BEPARE_CODNUM, BEPTIT_CODNUM, UID_USUARIO)
VALUES (130,162,'CARGA_INICIAL');
INSERT INTO TBEP_TIT_PREFERENTES_AREA (BEPARE_CODNUM, BEPTIT_CODNUM, UID_USUARIO)
VALUES (130,163,'CARGA_INICIAL');
INSERT INTO TBEP_TIT_PREFERENTES_AREA (BEPARE_CODNUM, BEPTIT_CODNUM, UID_USUARIO)
VALUES (131,135,'CARGA_INICIAL');
INSERT INTO TBEP_TIT_PREFERENTES_AREA (BEPARE_CODNUM, BEPTIT_CODNUM, UID_USUARIO)
VALUES (131,164,'CARGA_INICIAL');
INSERT INTO TBEP_TIT_PREFERENTES_AREA (BEPARE_CODNUM, BEPTIT_CODNUM, UID_USUARIO)
VALUES (131,137,'CARGA_INICIAL');
INSERT INTO TBEP_TIT_PREFERENTES_AREA (BEPARE_CODNUM, BEPTIT_CODNUM, UID_USUARIO)
VALUES (131,165,'CARGA_INICIAL');
INSERT INTO TBEP_TIT_PREFERENTES_AREA (BEPARE_CODNUM, BEPTIT_CODNUM, UID_USUARIO)
VALUES (131,166,'CARGA_INICIAL');
INSERT INTO TBEP_TIT_PREFERENTES_AREA (BEPARE_CODNUM, BEPTIT_CODNUM, UID_USUARIO)
VALUES (131,167,'CARGA_INICIAL');
INSERT INTO TBEP_TIT_PREFERENTES_AREA (BEPARE_CODNUM, BEPTIT_CODNUM, UID_USUARIO)
VALUES (131,47,'CARGA_INICIAL');
INSERT INTO TBEP_TIT_PREFERENTES_AREA (BEPARE_CODNUM, BEPTIT_CODNUM, UID_USUARIO)
VALUES (131,138,'CARGA_INICIAL');
INSERT INTO TBEP_TIT_PREFERENTES_AREA (BEPARE_CODNUM, BEPTIT_CODNUM, UID_USUARIO)
VALUES (131,97,'CARGA_INICIAL');
INSERT INTO TBEP_TIT_PREFERENTES_AREA (BEPARE_CODNUM, BEPTIT_CODNUM, UID_USUARIO)
VALUES (131,134,'CARGA_INICIAL');
INSERT INTO TBEP_TIT_PREFERENTES_AREA (BEPARE_CODNUM, BEPTIT_CODNUM, UID_USUARIO)
VALUES (132,139,'CARGA_INICIAL');
INSERT INTO TBEP_TIT_PREFERENTES_AREA (BEPARE_CODNUM, BEPTIT_CODNUM, UID_USUARIO)
VALUES (132,6,'CARGA_INICIAL');
INSERT INTO TBEP_TIT_PREFERENTES_AREA (BEPARE_CODNUM, BEPTIT_CODNUM, UID_USUARIO)
VALUES (132,140,'CARGA_INICIAL');
INSERT INTO TBEP_TIT_PREFERENTES_AREA (BEPARE_CODNUM, BEPTIT_CODNUM, UID_USUARIO)
VALUES (132,7,'CARGA_INICIAL');
INSERT INTO TBEP_TIT_PREFERENTES_AREA (BEPARE_CODNUM, BEPTIT_CODNUM, UID_USUARIO)
VALUES (132,11,'CARGA_INICIAL');
INSERT INTO TBEP_TIT_PREFERENTES_AREA (BEPARE_CODNUM, BEPTIT_CODNUM, UID_USUARIO)
VALUES (132,141,'CARGA_INICIAL');
INSERT INTO TBEP_TIT_PREFERENTES_AREA (BEPARE_CODNUM, BEPTIT_CODNUM, UID_USUARIO)
VALUES (134,40,'CARGA_INICIAL');
INSERT INTO TBEP_TIT_PREFERENTES_AREA (BEPARE_CODNUM, BEPTIT_CODNUM, UID_USUARIO)
VALUES (134,41,'CARGA_INICIAL');
INSERT INTO TBEP_TIT_PREFERENTES_AREA (BEPARE_CODNUM, BEPTIT_CODNUM, UID_USUARIO)
VALUES (134,145,'CARGA_INICIAL');
INSERT INTO TBEP_TIT_PREFERENTES_AREA (BEPARE_CODNUM, BEPTIT_CODNUM, UID_USUARIO)
VALUES (134,146,'CARGA_INICIAL');
INSERT INTO TBEP_TIT_PREFERENTES_AREA (BEPARE_CODNUM, BEPTIT_CODNUM, UID_USUARIO)
VALUES (134,168,'CARGA_INICIAL');
INSERT INTO TBEP_TIT_PREFERENTES_AREA (BEPARE_CODNUM, BEPTIT_CODNUM, UID_USUARIO)
VALUES (134,169,'CARGA_INICIAL');
INSERT INTO TBEP_TIT_PREFERENTES_AREA (BEPARE_CODNUM, BEPTIT_CODNUM, UID_USUARIO)
VALUES (135,112,'CARGA_INICIAL');
INSERT INTO TBEP_TIT_PREFERENTES_AREA (BEPARE_CODNUM, BEPTIT_CODNUM, UID_USUARIO)
VALUES (135,135,'CARGA_INICIAL');
INSERT INTO TBEP_TIT_PREFERENTES_AREA (BEPARE_CODNUM, BEPTIT_CODNUM, UID_USUARIO)
VALUES (135,113,'CARGA_INICIAL');
INSERT INTO TBEP_TIT_PREFERENTES_AREA (BEPARE_CODNUM, BEPTIT_CODNUM, UID_USUARIO)
VALUES (135,138,'CARGA_INICIAL');
INSERT INTO TBEP_TIT_PREFERENTES_AREA (BEPARE_CODNUM, BEPTIT_CODNUM, UID_USUARIO)
VALUES (136,55,'CARGA_INICIAL');
INSERT INTO TBEP_TIT_PREFERENTES_AREA (BEPARE_CODNUM, BEPTIT_CODNUM, UID_USUARIO)
VALUES (136,56,'CARGA_INICIAL');
INSERT INTO TBEP_TIT_PREFERENTES_AREA (BEPARE_CODNUM, BEPTIT_CODNUM, UID_USUARIO)
VALUES (136,57,'CARGA_INICIAL');
INSERT INTO TBEP_TIT_PREFERENTES_AREA (BEPARE_CODNUM, BEPTIT_CODNUM, UID_USUARIO)
VALUES (136,58,'CARGA_INICIAL');
INSERT INTO TBEP_TIT_PREFERENTES_AREA (BEPARE_CODNUM, BEPTIT_CODNUM, UID_USUARIO)
VALUES (136,59,'CARGA_INICIAL');
INSERT INTO TBEP_TIT_PREFERENTES_AREA (BEPARE_CODNUM, BEPTIT_CODNUM, UID_USUARIO)
VALUES (136,60,'CARGA_INICIAL');
INSERT INTO TBEP_TIT_PREFERENTES_AREA (BEPARE_CODNUM, BEPTIT_CODNUM, UID_USUARIO)
VALUES (136,61,'CARGA_INICIAL');
INSERT INTO TBEP_TIT_PREFERENTES_AREA (BEPARE_CODNUM, BEPTIT_CODNUM, UID_USUARIO)
VALUES (136,62,'CARGA_INICIAL');
INSERT INTO TBEP_TIT_PREFERENTES_AREA (BEPARE_CODNUM, BEPTIT_CODNUM, UID_USUARIO)
VALUES (137,170,'CARGA_INICIAL');
INSERT INTO TBEP_TIT_PREFERENTES_AREA (BEPARE_CODNUM, BEPTIT_CODNUM, UID_USUARIO)
VALUES (137,171,'CARGA_INICIAL');
INSERT INTO TBEP_TIT_PREFERENTES_AREA (BEPARE_CODNUM, BEPTIT_CODNUM, UID_USUARIO)
VALUES (28,79,'CARGA_INICIAL');
INSERT INTO TBEP_TIT_PREFERENTES_AREA (BEPARE_CODNUM, BEPTIT_CODNUM, UID_USUARIO)
VALUES (28,80,'CARGA_INICIAL');
INSERT INTO TBEP_TIT_PREFERENTES_AREA (BEPARE_CODNUM, BEPTIT_CODNUM, UID_USUARIO)
VALUES (29,64,'CARGA_INICIAL');
INSERT INTO TBEP_TIT_PREFERENTES_AREA (BEPARE_CODNUM, BEPTIT_CODNUM, UID_USUARIO)
VALUES (29,172,'CARGA_INICIAL');
INSERT INTO TBEP_TIT_PREFERENTES_AREA (BEPARE_CODNUM, BEPTIT_CODNUM, UID_USUARIO)
VALUES (29,173,'CARGA_INICIAL');
INSERT INTO TBEP_TIT_PREFERENTES_AREA (BEPARE_CODNUM, BEPTIT_CODNUM, UID_USUARIO)
VALUES (29,67,'CARGA_INICIAL');