INSERT INTO TBEP_APARTADOSBAREMACION (CODIGO,NOMBRE,PORCENTAJEMAXIMO,UID_USUARIO)
VALUES ('I','Formación académica',0.5,'CARGA_INICIAL');
INSERT INTO TBEP_APARTADOSBAREMACION (CODIGO,NOMBRE,PORCENTAJEMAXIMO,UID_USUARIO)
VALUES ('II','Actividad docente',0.2,'CARGA_INICIAL');
INSERT INTO TBEP_APARTADOSBAREMACION (CODIGO,NOMBRE,PORCENTAJEMAXIMO,UID_USUARIO)
VALUES ('III','Actividad investigadora',0.3,'CARGA_INICIAL');