INSERT INTO TBEP_APARTADOSBAREMACION (CODIGO,NOMBRE,PORCENTAJEMAXIMO,UID_USUARIO)
VALUES ('I','Formación académica',50,'CARGA_INICIAL');
INSERT INTO TBEP_APARTADOSBAREMACION (CODIGO,NOMBRE,PORCENTAJEMAXIMO,UID_USUARIO)
VALUES ('II','Actividad docente',20,'CARGA_INICIAL');
INSERT INTO TBEP_APARTADOSBAREMACION (CODIGO,NOMBRE,PORCENTAJEMAXIMO,UID_USUARIO)
VALUES ('III','Actividad investigadora',30,'CARGA_INICIAL');