INSERT INTO TBEP_AFINIDADES (CODNUM,CODIGO,DESCRIPCION,MODULACION,UID_USUARIO)
VALUES (1,'AA','Contribuciones propias del área de la plaza.',100,'CARGA_INICIAL');
INSERT INTO TBEP_AFINIDADES (CODNUM,CODIGO,DESCRIPCION,MODULACION,UID_USUARIO)
VALUES (2,'AA','Contribuciones afines a la área de la plaza.',50,'CARGA_INICIAL');
INSERT INTO TBEP_AFINIDADES (CODNUM,CODIGO,DESCRIPCION,MODULACION,UID_USUARIO)
VALUES (3,'AA','Sin afinidad a la área de la plaza.',0,'CARGA_INICIAL');
INSERT INTO TBEP_AFINIDADES (CODNUM,CODIGO,DESCRIPCION,MODULACION,UID_USUARIO)
VALUES (4,'AI','Contribuciones de investigación propias del área de la plaza.',100,'CARGA_INICIAL');
INSERT INTO TBEP_AFINIDADES (CODNUM,CODIGO,DESCRIPCION,MODULACION,UID_USUARIO)
VALUES (5,'AI','Contribuciones de investigación afines del área de la plaza.',50,'CARGA_INICIAL');
INSERT INTO TBEP_AFINIDADES (CODNUM,CODIGO,DESCRIPCION,MODULACION,UID_USUARIO)
VALUES (6,'AI','Sin afinidad a la área de la plaza.',0,'CARGA_INICIAL');