INSERT INTO TBEP_BLOQUESBAREMACION (BEPAPA_CODNUM,CODIGO,NOMBRE,UID_USUARIO)
SELECT
	bepapa.CODNUM AS BEPAPA_CODNUM,
	'1' AS CODIGO,
	'Titulación' AS NOMBRE,
	'CARGA_INICIAL' AS UID_USUARIO
FROM TBEP_APARTADOSBAREMACION bepapa WHERE bepapa.CODIGO = 'I' FETCH FIRST 1 ROWS ONLY;
INSERT INTO TBEP_BLOQUESBAREMACION (BEPAPA_CODNUM,CODIGO,NOMBRE,UID_USUARIO)
SELECT
	bepapa.CODNUM AS BEPAPA_CODNUM,
	'2' AS CODIGO,
	'Premios fin de carrera' AS NOMBRE,
	'CARGA_INICIAL' AS UID_USUARIO
FROM TBEP_APARTADOSBAREMACION bepapa WHERE bepapa.CODIGO = 'I' FETCH FIRST 1 ROWS ONLY;
INSERT INTO TBEP_BLOQUESBAREMACION (BEPAPA_CODNUM,CODIGO,NOMBRE,UID_USUARIO)
SELECT
	bepapa.CODNUM AS BEPAPA_CODNUM,
	'3' AS CODIGO,
	'Alumno colaborador del Departamento al que pertenezca el área convocante, becario Erasmus, Intercampus, ...' AS NOMBRE,
	'CARGA_INICIAL' AS UID_USUARIO
FROM TBEP_APARTADOSBAREMACION bepapa WHERE bepapa.CODIGO = 'I' FETCH FIRST 1 ROWS ONLY;
INSERT INTO TBEP_BLOQUESBAREMACION (BEPAPA_CODNUM,CODIGO,NOMBRE,UID_USUARIO)
SELECT
	bepapa.CODNUM AS BEPAPA_CODNUM,
	'4' AS CODIGO,
	'Otras titulaciones universitarias distintas a la exigída en la convocatoria' AS NOMBRE,
	'CARGA_INICIAL' AS UID_USUARIO
FROM TBEP_APARTADOSBAREMACION bepapa WHERE bepapa.CODIGO = 'I' FETCH FIRST 1 ROWS ONLY;
INSERT INTO TBEP_BLOQUESBAREMACION (BEPAPA_CODNUM,CODIGO,NOMBRE,UID_USUARIO)
SELECT
	bepapa.CODNUM AS BEPAPA_CODNUM,
	'5' AS CODIGO,
	'Doctorado [1]' AS NOMBRE,
	'CARGA_INICIAL' AS UID_USUARIO
FROM TBEP_APARTADOSBAREMACION bepapa WHERE bepapa.CODIGO = 'I' FETCH FIRST 1 ROWS ONLY;
INSERT INTO TBEP_BLOQUESBAREMACION (BEPAPA_CODNUM,CODIGO,NOMBRE,UID_USUARIO)
SELECT
	bepapa.CODNUM AS BEPAPA_CODNUM,
	'6' AS CODIGO,
	'Becas de investigación en concurrencia competitiva' AS NOMBRE,
	'CARGA_INICIAL' AS UID_USUARIO
FROM TBEP_APARTADOSBAREMACION bepapa WHERE bepapa.CODIGO = 'I' FETCH FIRST 1 ROWS ONLY;
INSERT INTO TBEP_BLOQUESBAREMACION (BEPAPA_CODNUM,CODIGO,NOMBRE,UID_USUARIO)
SELECT
	bepapa.CODNUM AS BEPAPA_CODNUM,
	'7' AS CODIGO,
	'Cursos de postgrado relevantes para la plaza' AS NOMBRE,
	'CARGA_INICIAL' AS UID_USUARIO
FROM TBEP_APARTADOSBAREMACION bepapa WHERE bepapa.CODIGO = 'I' FETCH FIRST 1 ROWS ONLY;
INSERT INTO TBEP_BLOQUESBAREMACION (BEPAPA_CODNUM,CODIGO,NOMBRE,UID_USUARIO)
SELECT
	bepapa.CODNUM AS BEPAPA_CODNUM,
	'8' AS CODIGO,
	'Otras acciones de formación' AS NOMBRE,
	'CARGA_INICIAL' AS UID_USUARIO
FROM TBEP_APARTADOSBAREMACION bepapa WHERE bepapa.CODIGO = 'I' FETCH FIRST 1 ROWS ONLY;
INSERT INTO TBEP_BLOQUESBAREMACION (BEPAPA_CODNUM,CODIGO,NOMBRE,UID_USUARIO)
SELECT
	bepapa.CODNUM AS BEPAPA_CODNUM,
	'1' AS CODIGO,
	'Docencia universitaria en títulos oficiales' AS NOMBRE,
	'CARGA_INICIAL' AS UID_USUARIO
FROM TBEP_APARTADOSBAREMACION bepapa WHERE bepapa.CODIGO = 'II' FETCH FIRST 1 ROWS ONLY;
INSERT INTO TBEP_BLOQUESBAREMACION (BEPAPA_CODNUM,CODIGO,NOMBRE,UID_USUARIO)
SELECT
	bepapa.CODNUM AS BEPAPA_CODNUM,
	'2' AS CODIGO,
	'Docencia universitaria no oficial (Másteres propios de la Universidad, Cursos de Experto de la Universidad y Cursos de Extensión Universitaria)' AS NOMBRE,
	'CARGA_INICIAL' AS UID_USUARIO
FROM TBEP_APARTADOSBAREMACION bepapa WHERE bepapa.CODIGO = 'II' FETCH FIRST 1 ROWS ONLY;
INSERT INTO TBEP_BLOQUESBAREMACION (BEPAPA_CODNUM,CODIGO,NOMBRE,UID_USUARIO)
SELECT
	bepapa.CODNUM AS BEPAPA_CODNUM,
	'3' AS CODIGO,
	'Docencia no universitaria' AS NOMBRE,
	'CARGA_INICIAL' AS UID_USUARIO
FROM TBEP_APARTADOSBAREMACION bepapa WHERE bepapa.CODIGO = 'II' FETCH FIRST 1 ROWS ONLY;
INSERT INTO TBEP_BLOQUESBAREMACION (BEPAPA_CODNUM,CODIGO,NOMBRE,UID_USUARIO)
SELECT
	bepapa.CODNUM AS BEPAPA_CODNUM,
	'4' AS CODIGO,
	'Creación de material docente' AS NOMBRE,
	'CARGA_INICIAL' AS UID_USUARIO
FROM TBEP_APARTADOSBAREMACION bepapa WHERE bepapa.CODIGO = 'II' FETCH FIRST 1 ROWS ONLY;
INSERT INTO TBEP_BLOQUESBAREMACION (BEPAPA_CODNUM,CODIGO,NOMBRE,UID_USUARIO)
SELECT
	bepapa.CODNUM AS BEPAPA_CODNUM,
	'5' AS CODIGO,
	'Proyectos de innovación y mejora de la calidad docente a través de convocatorias competitivas oficiales [4]' AS NOMBRE,
	'CARGA_INICIAL' AS UID_USUARIO
FROM TBEP_APARTADOSBAREMACION bepapa WHERE bepapa.CODIGO = 'II' FETCH FIRST 1 ROWS ONLY;
INSERT INTO TBEP_BLOQUESBAREMACION (BEPAPA_CODNUM,CODIGO,NOMBRE,UID_USUARIO)
SELECT
	bepapa.CODNUM AS BEPAPA_CODNUM,
	'6' AS CODIGO,
	'Participación en Congresos de Innovación Docente, no relacionados con la investigación [5]' AS NOMBRE,
	'CARGA_INICIAL' AS UID_USUARIO
FROM TBEP_APARTADOSBAREMACION bepapa WHERE bepapa.CODIGO = 'II' FETCH FIRST 1 ROWS ONLY;
INSERT INTO TBEP_BLOQUESBAREMACION (BEPAPA_CODNUM,CODIGO,NOMBRE,UID_USUARIO)
SELECT
	bepapa.CODNUM AS BEPAPA_CODNUM,
	'7' AS CODIGO,
	'Docencia en la modalidad de bilingüismo' AS NOMBRE,
	'CARGA_INICIAL' AS UID_USUARIO
FROM TBEP_APARTADOSBAREMACION bepapa WHERE bepapa.CODIGO = 'II' FETCH FIRST 1 ROWS ONLY;
INSERT INTO TBEP_BLOQUESBAREMACION (BEPAPA_CODNUM,CODIGO,NOMBRE,UID_USUARIO)
SELECT
	bepapa.CODNUM AS BEPAPA_CODNUM,
	'1' AS CODIGO,
	'Publicaciones científicas' AS NOMBRE,
	'CARGA_INICIAL' AS UID_USUARIO
FROM TBEP_APARTADOSBAREMACION bepapa WHERE bepapa.CODIGO = 'III' FETCH FIRST 1 ROWS ONLY;
INSERT INTO TBEP_BLOQUESBAREMACION (BEPAPA_CODNUM,CODIGO,NOMBRE,UID_USUARIO)
SELECT
	bepapa.CODNUM AS BEPAPA_CODNUM,
	'2' AS CODIGO,
	'Editor de revistas científicas' AS NOMBRE,
	'CARGA_INICIAL' AS UID_USUARIO
FROM TBEP_APARTADOSBAREMACION bepapa WHERE bepapa.CODIGO = 'III' FETCH FIRST 1 ROWS ONLY;
INSERT INTO TBEP_BLOQUESBAREMACION (BEPAPA_CODNUM,CODIGO,NOMBRE,UID_USUARIO)
SELECT
	bepapa.CODNUM AS BEPAPA_CODNUM,
	'3' AS CODIGO,
	'Libros o monografías' AS NOMBRE,
	'CARGA_INICIAL' AS UID_USUARIO
FROM TBEP_APARTADOSBAREMACION bepapa WHERE bepapa.CODIGO = 'III' FETCH FIRST 1 ROWS ONLY;
INSERT INTO TBEP_BLOQUESBAREMACION (BEPAPA_CODNUM,CODIGO,NOMBRE,UID_USUARIO)
SELECT
	bepapa.CODNUM AS BEPAPA_CODNUM,
	'4' AS CODIGO,
	'Contribuciones a congresos, conferencias, seminarios y reuniones científicas' AS NOMBRE,
	'CARGA_INICIAL' AS UID_USUARIO
FROM TBEP_APARTADOSBAREMACION bepapa WHERE bepapa.CODIGO = 'III' FETCH FIRST 1 ROWS ONLY;
INSERT INTO TBEP_BLOQUESBAREMACION (BEPAPA_CODNUM,CODIGO,NOMBRE,UID_USUARIO)
SELECT
	bepapa.CODNUM AS BEPAPA_CODNUM,
	'5' AS CODIGO,
	'Proyectos de investigación obtenidos en convocatorias públicas y competitivas y contratos con empresas o con la administración' AS NOMBRE,
	'CARGA_INICIAL' AS UID_USUARIO
FROM TBEP_APARTADOSBAREMACION bepapa WHERE bepapa.CODIGO = 'III' FETCH FIRST 1 ROWS ONLY;
INSERT INTO TBEP_BLOQUESBAREMACION (BEPAPA_CODNUM,CODIGO,NOMBRE,UID_USUARIO)
SELECT
	bepapa.CODNUM AS BEPAPA_CODNUM,
	'6' AS CODIGO,
	'Patentes' AS NOMBRE,
	'CARGA_INICIAL' AS UID_USUARIO
FROM TBEP_APARTADOSBAREMACION bepapa WHERE bepapa.CODIGO = 'III' FETCH FIRST 1 ROWS ONLY;
INSERT INTO TBEP_BLOQUESBAREMACION (BEPAPA_CODNUM,CODIGO,NOMBRE,UID_USUARIO)
SELECT
	bepapa.CODNUM AS BEPAPA_CODNUM,
	'7' AS CODIGO,
	'Estancias predoctorales' AS NOMBRE,
	'CARGA_INICIAL' AS UID_USUARIO
FROM TBEP_APARTADOSBAREMACION bepapa WHERE bepapa.CODIGO = 'III' FETCH FIRST 1 ROWS ONLY;
INSERT INTO TBEP_BLOQUESBAREMACION (BEPAPA_CODNUM,CODIGO,NOMBRE,UID_USUARIO)
SELECT
	bepapa.CODNUM AS BEPAPA_CODNUM,
	'8' AS CODIGO,
	'Estancias postdoctorales en otras universidades o centros de investigación' AS NOMBRE,
	'CARGA_INICIAL' AS UID_USUARIO
FROM TBEP_APARTADOSBAREMACION bepapa WHERE bepapa.CODIGO = 'III' FETCH FIRST 1 ROWS ONLY;
INSERT INTO TBEP_BLOQUESBAREMACION (BEPAPA_CODNUM,CODIGO,NOMBRE,UID_USUARIO)
SELECT
	bepapa.CODNUM AS BEPAPA_CODNUM,
	'9' AS CODIGO,
	'Dirección de tesis doctorales y trabajos de iniciación a la investigación' AS NOMBRE,
	'CARGA_INICIAL' AS UID_USUARIO
FROM TBEP_APARTADOSBAREMACION bepapa WHERE bepapa.CODIGO = 'III' FETCH FIRST 1 ROWS ONLY;
INSERT INTO TBEP_BLOQUESBAREMACION (BEPAPA_CODNUM,CODIGO,NOMBRE,UID_USUARIO)
SELECT
	bepapa.CODNUM AS BEPAPA_CODNUM,
	'10' AS CODIGO,
	'Premios en concurrencia competitiva' AS NOMBRE,
	'CARGA_INICIAL' AS UID_USUARIO
FROM TBEP_APARTADOSBAREMACION bepapa WHERE bepapa.CODIGO = 'III' FETCH FIRST 1 ROWS ONLY;
INSERT INTO TBEP_BLOQUESBAREMACION (BEPAPA_CODNUM,CODIGO,NOMBRE,UID_USUARIO)
SELECT
	bepapa.CODNUM AS BEPAPA_CODNUM,
	'11' AS CODIGO,
	'Otros méritos de investigación' AS NOMBRE,
	'CARGA_INICIAL' AS UID_USUARIO
FROM TBEP_APARTADOSBAREMACION bepapa WHERE bepapa.CODIGO = 'III' FETCH FIRST 1 ROWS ONLY;