Insert into TBEP_ITEMSBAREMACION (CODNUM, BEPBLO_CODNUM, CODIGO, NOMBRE, DESCRIPCION, FLGACTIVO, UNIDADES, VALOR, VALOR_MINIMO, VALOR_MAXIMO, AFINIDAD, INDIVIDUALIZADO, UID_USUARIO) Values
   (58, 19, '1', 'Ponencias invitadas a congresos internacionales', 'Mérito individualizado. Una sola contribucion por mérito.La puntuación asignada, 1, en contribuciones de más de cuatro autores se multiplicará por 4 y se dividirá por el número de autores.Se recomienda que la documentación acreditativa del mérito contenga los elementos esenciales que permitan conocer los aspectos formales y el contenido de las publicaciones: : Autor/a, ISBN, editorial, año de publicación, índice completo', 'S', 'DECIMAL', 1.6, 0.1, 1, 'AI', 'S', 'pmperez');
Insert into TBEP_ITEMSBAREMACION (CODNUM, BEPBLO_CODNUM, CODIGO, NOMBRE, DESCRIPCION, FLGACTIVO, UNIDADES, VALOR, VALOR_MINIMO, VALOR_MAXIMO, AFINIDAD, INDIVIDUALIZADO, UID_USUARIO) Values
   (59, 19, '2', 'Ponencias invitadas a congresos nacionales', 'Mérito individualizado. Una sola contribucion por mérito.La puntuación asignada, 1, en contribuciones de más de cuatro autores se multiplicará por 4 y se dividirá por el número de autores.Se recomienda que la documentación acreditativa del mérito contenga los elementos esenciales que permitan conocer los aspectos formales y el contenido de las publicaciones: : Autor/a, ISBN, editorial, año de publicación, índice comple', 'S', 'DECIMAL', 0.9, 0.1, 1, 'AI', 'S', 'pmperez');
Insert into TBEP_ITEMSBAREMACION (CODNUM, BEPBLO_CODNUM, CODIGO, NOMBRE, DESCRIPCION, FLGACTIVO, UNIDADES, VALOR, VALOR_MINIMO, VALOR_MAXIMO, AFINIDAD, INDIVIDUALIZADO, UID_USUARIO) Values
   (60, 19, '3', 'Comunicaciones a congresos internacionales', 'Mérito individualizado. Una sola contribucion por mérito.La puntuación asignada, 1, en contribuciones de más de cuatro autores se multiplicará por 4 y se dividirá por el número de autores.Se recomienda que la documentación acreditativa del mérito contenga los elementos esenciales que permitan conocer los aspectos formales y el contenido de las publicaciones: : Autor/a, ISBN, editorial, año de publicación, índice comple', 'S', 'DECIMAL', 0.9, 0.1, 1, 'AI', 'S', 'pmperez');
Insert into TBEP_ITEMSBAREMACION (CODNUM, BEPBLO_CODNUM, CODIGO, NOMBRE, DESCRIPCION, FLGACTIVO, UNIDADES, VALOR, VALOR_MINIMO, VALOR_MAXIMO, AFINIDAD, INDIVIDUALIZADO, UID_USUARIO) Values
   (63, 19, '6', 'Pósteres a congresos nacionales', 'Mérito individualizado. Una sola contribucion por mérito.La puntuación asignada, 1, en contribuciones de más de cuatro autores se multiplicará por 4 y se dividirá por el número de autores.Se recomienda que la documentación acreditativa del mérito contenga los elementos esenciales que permitan conocer los aspectos formales y el contenido de las publicaciones: : Autor/a, ISBN, editorial, año de publicación, índice comple', 'S', 'DECIMAL', 0.3, 0.1, 1, 'AI', 'S', 'pmperez');
Insert into TBEP_ITEMSBAREMACION (CODNUM, BEPBLO_CODNUM, CODIGO, NOMBRE, DESCRIPCION, FLGACTIVO, UNIDADES, VALOR, VALOR_MINIMO, VALOR_MAXIMO, AFINIDAD, INDIVIDUALIZADO, UID_USUARIO) Values
   (67, 20, '2', 'Proyectos nacionales', 'érito individualizado.  Un sólo proyecto por mérito.Para  investigador  principal introducir valor 1. Para el resto de personal introducir valor 0.5.En los proyectos con duración inferior a 3 años se multiplicará  la puntuación anterior por el número  de años o fracción y se dividirá por 3', 'S', 'DECIMAL', 1.5, 0.1, 1, 'AI', 'S', 'pmperez');
Insert into TBEP_ITEMSBAREMACION (CODNUM, BEPBLO_CODNUM, CODIGO, NOMBRE, DESCRIPCION, FLGACTIVO, UNIDADES, VALOR, VALOR_MINIMO, VALOR_MAXIMO, AFINIDAD, INDIVIDUALIZADO, UID_USUARIO) Values
   (71, 21, '1', 'Patentes en explotación', 'Mérito  individualizado. Una sola patente por  mérito', 'S', 'ENTERO', 2, 1, 1, 'AI', 'S', 'pmperez');
Insert into TBEP_ITEMSBAREMACION (CODNUM, BEPBLO_CODNUM, CODIGO, NOMBRE, DESCRIPCION, FLGACTIVO, UNIDADES, VALOR, VALOR_MINIMO, VALOR_MAXIMO, AFINIDAD, INDIVIDUALIZADO, UID_USUARIO) Values
   (72, 21, '2', 'Patentes restringidas o modelos de explotación', 'Mérito  individualizado. Una sola patente por  mérito', 'S', 'ENTERO', 1.5, 1, 1, 'AI', 'S', 'pmperez');
Insert into TBEP_ITEMSBAREMACION (CODNUM, BEPBLO_CODNUM, CODIGO, NOMBRE, DESCRIPCION, FLGACTIVO, UNIDADES, VALOR, VALOR_MINIMO, VALOR_MAXIMO, AFINIDAD, INDIVIDUALIZADO, UID_USUARIO) Values
   (74, 22, '2', 'Meses de estancia en centro nacional con financiación ajena', 'Mérito  individualizado. Una sola estancia por  mérito.Las estancias en un mismo centro, pero en distintos períodos temporales, podrán acumularse en un solo pdf.', 'S', 'DECIMAL', 0.1, 0.1, 100, 'AI', 'S', 'pmperez');
Insert into TBEP_ITEMSBAREMACION (CODNUM, BEPBLO_CODNUM, CODIGO, NOMBRE, DESCRIPCION, FLGACTIVO, UNIDADES, VALOR, VALOR_MINIMO, VALOR_MAXIMO, AFINIDAD, INDIVIDUALIZADO, UID_USUARIO) Values
   (75, 23, '1', 'Meses de estancia en centro extranjero con financiación ajena', 'En este apartado se incluyen las becas postdoctorales', 'S', 'DECIMAL', 0.4, 0.1, 100, 'AI', 'N', 'pmperez');
Insert into TBEP_ITEMSBAREMACION (CODNUM, BEPBLO_CODNUM, CODIGO, NOMBRE, DESCRIPCION, FLGACTIVO, UNIDADES, VALOR, VALOR_MINIMO, VALOR_MAXIMO, AFINIDAD, INDIVIDUALIZADO, UID_USUARIO) Values
   (77, 24, '1', 'Tesis doctorales dirigidas y defendidas', 'Mérito individualizado. Una sola tesis por mérito', 'S', 'ENTERO', 1.5, 1, 1, 'AI', 'S', 'pmperez');
Insert into TBEP_ITEMSBAREMACION (CODNUM, BEPBLO_CODNUM, CODIGO, NOMBRE, DESCRIPCION, FLGACTIVO, UNIDADES, VALOR, VALOR_MINIMO, VALOR_MAXIMO, AFINIDAD, INDIVIDUALIZADO, UID_USUARIO) Values
   (79, 25, '1', 'Premios de investigación internacionales', 'Mérito  individualizado. Un solo premio por mérito', 'S', 'ENTERO', 1.5, 1, 1, 'AI', 'S', 'pmperez');
Insert into TBEP_ITEMSBAREMACION (CODNUM, BEPBLO_CODNUM, CODIGO, NOMBRE, DESCRIPCION, FLGACTIVO, UNIDADES, VALOR, VALOR_MINIMO, VALOR_MAXIMO, AFINIDAD, INDIVIDUALIZADO, UID_USUARIO) Values
   (80, 25, '2', 'Premios de investigación nacionales', 'Mérito  individualizado. Un solo premio por mérito', 'S', 'ENTERO', 1, 1, 1, 'AI', 'S', 'pmperez');
Insert into TBEP_ITEMSBAREMACION (CODNUM, BEPBLO_CODNUM, CODIGO, NOMBRE, DESCRIPCION, FLGACTIVO, UNIDADES, VALOR, VALOR_MINIMO, VALOR_MAXIMO, AFINIDAD, INDIVIDUALIZADO, UID_USUARIO) Values
   (81, 25, '3', 'Premios de investigación autonómicos', 'Mérito  individualizado. Un solo premio por mérito', 'S', 'ENTERO', 0.6, 1, 1, 'AI', 'S', 'pmperez');
Insert into TBEP_ITEMSBAREMACION (CODNUM, BEPBLO_CODNUM, CODIGO, NOMBRE, FLGACTIVO, UNIDADES, VALOR, VALOR_MINIMO, VALOR_MAXIMO, AFINIDAD, INDIVIDUALIZADO, UID_USUARIO) Values
   (83, 26, '1', 'Meses en programas de incorporación de doctores', 'S', 'ENTERO', 0.3, 1, 100, 'AI', 'N', 'pmperez');
Insert into TBEP_ITEMSBAREMACION (CODNUM, BEPBLO_CODNUM, CODIGO, NOMBRE, DESCRIPCION, FLGACTIVO, UNIDADES, VALOR, VALOR_MINIMO, VALOR_MAXIMO, AFINIDAD, INDIVIDUALIZADO, UID_USUARIO) Values
   (84, 26, '2', 'Pertenencia activa a grupos de investigación PAIDI evaluados en la última convocatoria', 'Mérito  individualizado. Solo un grupo por mérito', 'S', 'ENTERO', 0.3, 1, 1, 'AI', 'S', 'pmperez');
Insert into TBEP_ITEMSBAREMACION (CODNUM, BEPBLO_CODNUM, CODIGO, NOMBRE, DESCRIPCION, FLGACTIVO, UNIDADES, VALOR, VALOR_MINIMO, VALOR_MAXIMO, INDIVIDUALIZADO, UID_USUARIO) Values
   (2, 2, '1', 'Premios nacionales', 'Se pondera en función del nivel del mérito aportado. Primer premio fin de carrera(Grado, Licenciatura, Diplomatura, Ingeniería o Arquitectura):  Introducir valor 1.Segundo premio fin de carrera, segundo premio fin de máster, primer premio proyecto fin  de carrera, primer premio fin de grado o   primer premio fin de máster. Introducir valor 0.6. Tercer premio y siguientes o accésist. Introducir valor 0.3. * No se tendrán en cuenta en este apartado premios de actividad investigadora, innovación, transferencia del  conocimiento, cursos académicos, así como menciones especiales. Sólo un premio por mérito.', 'S', 'DECIMAL', 3, 0.33, 1, 'S', 'pmperez');
Insert into TBEP_ITEMSBAREMACION (CODNUM, BEPBLO_CODNUM, CODIGO, NOMBRE, DESCRIPCION, FLGACTIVO, UNIDADES, VALOR, VALOR_MINIMO, VALOR_MAXIMO, INDIVIDUALIZADO, UID_USUARIO) Values
   (3, 2, '2', 'Premios de la Universidad', 'Se pondera en función del nivel del mérito aportado.Primer premio fin de carrera(Grado, Licenciatura, Diplomatura, Ingeniería o Arquitectura):  Introducir valor 1.Segundo premio fin de carrera, segundo premio fin de máster, primer premio proyecto fin  de carrera, primer premio fin de grado o   primer premio fin de máster. Introducir valor 0.6. Tercer premio y siguientes o accésist. Introducir valor 0.3. * No se tendrán en cuenta en este apartado premios de actividad investigadora, innovación, transferencia del  conocimiento, cursos académicos, así como menciones especiales. Sólo un premio por mérito.', 'S', 'DECIMAL', 1.5, 0.33, 1, 'S', 'pmperez');
Insert into TBEP_ITEMSBAREMACION (CODNUM, BEPBLO_CODNUM, CODIGO, NOMBRE, DESCRIPCION, FLGACTIVO, UNIDADES, VALOR, VALOR_MINIMO, VALOR_MAXIMO, AFINIDAD, INDIVIDUALIZADO, UID_USUARIO) Values
   (4, 3, '1', 'Meses de Becario de alumno colaborador de Departamento', 'Se justificarán los méritos en un solo PDF que incluirá la credencial de becario y un certificado oficial del período de beca disfrutado. Se valoraran exclusivamente becas de colaboración convocadas por el Ministerio de Educación, no becas convocadas por las universidades, becas Ícaro,... Si los méritos se contabilizan en cursos académicos hay que hacer la siguiente equivalencia: 1 curso académico = 10 meses.', 'S', 'DECIMAL', 0.05, 0.1, 100, 'AA', 'S', 'pmperez');
Insert into TBEP_ITEMSBAREMACION (CODNUM, BEPBLO_CODNUM, CODIGO, NOMBRE, DESCRIPCION, FLGACTIVO, UNIDADES, VALOR, VALOR_MINIMO, VALOR_MAXIMO, INDIVIDUALIZADO, UID_USUARIO) Values
   (6, 4, '1', 'Titulaciones universitarias superiores distintas a la exigida  para acceder a la convocatoria', 'NO se valoran títulos propios de master, especialista o experto que son valorados en el apartado 1.8.1. En caso de ser doctor, la posesión del DEA tendrá la misma consideración que un Máster Oficial conducente al Doctorado y será valorado como mérito en este apartado (Aprobado en comisión de seguimiento 7/5/2018). Las especialidades  sanitarias tienen, a estos meros efectos, consideración de Máster Oficial.No se incluye el  CAP, no pueden considerarse títulos universitarios de carácter oficial y con validez en todo el territorio nacional, ni tan siquiera títulos propios universitarios, regidos por normativa distinta a la señalada orden ministerial. Sólo un  título  por mérito', 'S', 'ENTERO', 1.2, 1, 1, 'S', 'pmperez');
Insert into TBEP_ITEMSBAREMACION (CODNUM, BEPBLO_CODNUM, CODIGO, NOMBRE, DESCRIPCION, FLGACTIVO, UNIDADES, VALOR, VALOR_MINIMO, VALOR_MAXIMO, INDIVIDUALIZADO, UID_USUARIO) Values
   (7, 4, '2', 'Titulaciones universitarias de grado medio y/o titulaciones de Grado distinta a la exigida para acceder a  la conv.', 'NO se valoran títulos propios de master, especialista o experto porque son valorados en el apartado 1.8.1. En caso de ser doctor, la posesión del DEA tendrá la misma consideración que un Máster Oficial conducente al Doctorado y será valorado como mérito en este apartado (Aprobado en comisión de seguimiento 7/5/2018). Las especialidades  sanitarias tienen, a estos meros efectos, consideración de Máster Oficial.No se incluye el  CAP, no pueden considerarse títulos universitarios de carácter oficial y con validez en todo el territorio nacional, ni tan siquiera títulos propios universitarios, regidos por normativa distinta a la señalada orden ministerial. Sólo un  título  por mérito', 'S', 'ENTERO', 0.8, 1, 1, 'S', 'pmperez');
Insert into TBEP_ITEMSBAREMACION (CODNUM, BEPBLO_CODNUM, CODIGO, NOMBRE, DESCRIPCION, FLGACTIVO, UNIDADES, VALOR, VALOR_MINIMO, VALOR_MAXIMO, AFINIDAD, INDIVIDUALIZADO, UID_USUARIO) Values
   (25, 10, '1', 'Créditos impartidos en docencia universitaria no oficial', 'Mérito individualizado. Una sola actividad por mérito ', 'S', 'DECIMAL', 0.08, 0.1, 100, 'AA', 'S', 'pmperez');
Insert into TBEP_ITEMSBAREMACION (CODNUM, BEPBLO_CODNUM, CODIGO, NOMBRE, DESCRIPCION, FLGACTIVO, UNIDADES, VALOR, VALOR_MINIMO, VALOR_MAXIMO, AFINIDAD, INDIVIDUALIZADO, UID_USUARIO) Values
   (28, 12, '1', 'Libros o monografías internacionales', 'Mérito  individualizado. Sólo un libro por mérito.La consideración de internacionalidad o nacionalidad es criterio de la comisión.', 'S', 'ENTERO', 3, 1, 1, 'AA', 'S', 'pmperez');
Insert into TBEP_ITEMSBAREMACION (CODNUM, BEPBLO_CODNUM, CODIGO, NOMBRE, DESCRIPCION, FLGACTIVO, UNIDADES, VALOR, VALOR_MINIMO, VALOR_MAXIMO, AFINIDAD, INDIVIDUALIZADO, UID_USUARIO) Values
   (31, 12, '4', 'Capítulos de libros nacionales', 'Mérito  individualizado. Sólo un libro por mérito. Máximo 2 capítulos por cada libro', 'S', 'ENTERO', 1.5, 1, 2, 'AA', 'S', 'pmperez');
Insert into TBEP_ITEMSBAREMACION (CODNUM, BEPBLO_CODNUM, CODIGO, NOMBRE, DESCRIPCION, FLGACTIVO, UNIDADES, VALOR, VALOR_MINIMO, VALOR_MAXIMO, AFINIDAD, INDIVIDUALIZADO, UID_USUARIO) Values
   (30, 12, '3', 'Libros o monografías nacionales', 'Mérito  individualizado. Sólo un libro por mérito.En este apartado no se consideran publicaciones de actas de congresos, aunque tengan ISBN. ', 'S', 'ENTERO', 2, 1, 1, 'AA', 'S', 'pmperez');
Insert into TBEP_ITEMSBAREMACION (CODNUM, BEPBLO_CODNUM, CODIGO, NOMBRE, DESCRIPCION, FLGACTIVO, UNIDADES, VALOR, VALOR_MINIMO, VALOR_MAXIMO, AFINIDAD, INDIVIDUALIZADO, UID_USUARIO) Values
   (34, 13, '1', 'Participación en proyectos de formación e innovación docente con una duración de al menos un año o un curso académico', 'Mérito individualizado. Sólo un proyecto por mérito.Introducir valor 1 si es coordinador/a.Introducir valor o.5 si es participante', 'S', 'DECIMAL', 1, 0.5, 1, 'AA', 'S', 'pmperez');
Insert into TBEP_ITEMSBAREMACION (CODNUM, BEPBLO_CODNUM, CODIGO, NOMBRE, DESCRIPCION, FLGACTIVO, UNIDADES, VALOR, VALOR_MINIMO, VALOR_MAXIMO, AFINIDAD, INDIVIDUALIZADO, UID_USUARIO) Values
   (35, 14, '1', 'Ponencias invitadas a congresos internacionales de innovación docente, no  relacionados con la investigación.', 'Mérito individualizado. Una ponencia por mérito.La puntuación asignada, 1, en contribuciones de más de cuatro autores se multiplicará por 4 y se dividirá por el número de autores', 'S', 'DECIMAL', 1.6, 0.1, 1, 'AA', 'S', 'pmperez');
Insert into TBEP_ITEMSBAREMACION (CODNUM, BEPBLO_CODNUM, CODIGO, NOMBRE, DESCRIPCION, FLGACTIVO, UNIDADES, VALOR, VALOR_MINIMO, VALOR_MAXIMO, AFINIDAD, INDIVIDUALIZADO, UID_USUARIO) Values
   (37, 14, '3', 'Comunicaciones a congresos internacionales de innovación docente, no relacionados con investigación', 'Mérito individualizado. Una sola comunicación con méritoLa puntuación asignada, 1, en contribuciones de más de cuatro autores se multiplicará por 4 y se dividirá por el número de autores', 'S', 'DECIMAL', 0.4, 0.1, 1, 'AA', 'S', 'pmperez');
Insert into TBEP_ITEMSBAREMACION (CODNUM, BEPBLO_CODNUM, CODIGO, NOMBRE, DESCRIPCION, FLGACTIVO, UNIDADES, VALOR, VALOR_MINIMO, VALOR_MAXIMO, AFINIDAD, INDIVIDUALIZADO, UID_USUARIO) Values
   (38, 14, '4', 'Comunicaciones a congresos nacionales de innovación docente, no relacionados con la investigación', 'Mérito  individualizado. Una sola comunicación por méritoLa puntuación asignada, 1, en contribuciones de más de cuatro autores se multiplicará por 4 y se dividirá por el número de autores', 'S', 'DECIMAL', 0.2, 0.1, 1, 'AA', 'S', 'pmperez');
Insert into TBEP_ITEMSBAREMACION (CODNUM, BEPBLO_CODNUM, CODIGO, NOMBRE, DESCRIPCION, FLGACTIVO, UNIDADES, VALOR, VALOR_MINIMO, VALOR_MAXIMO, AFINIDAD, INDIVIDUALIZADO, UID_USUARIO) Values
   (40, 16, '1', 'Artículos en revistas situadas en el 1er cuartil del Journal Citation Report', 'Mérito individualizado. Un solo artículo por mérito.La puntuación asignada, 1, en contribuciones de más de cuatro autores se multiplicará por 4 y se dividirá por el número de autores.NO se tendrán en cuenta las publicaciones aceptadas pero sin publicar a fecha de cierre de la bolsa ("Estar en prensa").Se recomienda que la documentación acreditativa del mérito contenga los elementos esenciales que permitan conocer los aspectos formales y el contenido de las publicaciones: : Autor/a, ISBN, editorial, año de publicación, índice completo..', 'S', 'DECIMAL', 3.6, 0.1, 1, 'AI', 'S', 'pmperez');
Insert into TBEP_ITEMSBAREMACION (CODNUM, BEPBLO_CODNUM, CODIGO, NOMBRE, DESCRIPCION, FLGACTIVO, UNIDADES, VALOR, VALOR_MINIMO, VALOR_MAXIMO, AFINIDAD, INDIVIDUALIZADO, UID_USUARIO) Values
   (41, 16, '2', 'Artículos en revistas situadas en el 2º cuartil del Journal Citation Report', 'Mérito individualizado. Un solo artículo por mérito.La puntuación asignada, 1, en contribuciones de más de cuatro autores se multiplicará por 4 y se dividirá por el número de autores.NO se tendrán en cuenta las publicaciones aceptadas pero sin publicar a fecha de cierre de la bolsa ("Estar en prensa").Se recomienda que la documentación acreditativa del mérito contenga los elementos esenciales que permitan conocer los aspectos formales y el contenido de las publicaciones: : Autor/a, ISBN, editorial, año de publicación, índice completo', 'S', 'DECIMAL', 3.4, 0.1, 1, 'AI', 'S', 'pmperez');
Insert into TBEP_ITEMSBAREMACION (CODNUM, BEPBLO_CODNUM, CODIGO, NOMBRE, DESCRIPCION, FLGACTIVO, UNIDADES, VALOR, VALOR_MINIMO, VALOR_MAXIMO, AFINIDAD, INDIVIDUALIZADO, UID_USUARIO) Values
   (42, 16, '3', 'Artículos en revistas situadas en el 3er cuartil del Journal Citation Report o en primer cuartil de los indices de referencia utilizados para la evaluación de la actividad', 'Mérito individualizado. Un solo artículo por mérito.La puntuación asignada, 1, en contribuciones de más de cuatro autores se multiplicará por 4 y se dividirá por el número de autores.NO se tendrán en cuenta las publicaciones aceptadas pero sin publicar a fecha de cierre de la bolsa ("Estar en prensa").Se recomienda que la documentación acreditativa del mérito contenga los elementos esenciales que permitan conocer los aspectos formales y el contenido de las publicaciones: : Autor/a, ISBN, editorial, año de publicación, índice completo', 'S', 'DECIMAL', 3, 0.1, 1, 'AI', 'S', 'pmperez');
Insert into TBEP_ITEMSBAREMACION (CODNUM, BEPBLO_CODNUM, CODIGO, NOMBRE, DESCRIPCION, FLGACTIVO, UNIDADES, VALOR, VALOR_MINIMO, VALOR_MAXIMO, AFINIDAD, INDIVIDUALIZADO, UID_USUARIO) Values
   (44, 16, '5', 'Artículos en otras revistas en tercer o cuarto de los indices de referencia utilizados para la evaluación de la actividad investigadora por CNEAI, en caso de no usarse JCR', 'Mérito individualizado. Un solo artículo por mérito.La puntuación asignada, 1, en contribuciones de más de cuatro autores se multiplicará por 4 y se dividirá por el número de autores.NO se tendrán en cuenta las publicaciones aceptadas pero sin publicar a fecha de cierre de la bolsa ("Estar en prensa").Se recomienda que la documentación acreditativa del mérito contenga los elementos esenciales que permitan conocer los aspectos formales y el contenido de las publicaciones: : Autor/a, ISBN, editorial, año de publicación, índice completo', 'S', 'DECIMAL', 1.5, 0.1, 1, 'AI', 'S', 'pmperez');
Insert into TBEP_ITEMSBAREMACION (CODNUM, BEPBLO_CODNUM, CODIGO, NOMBRE, DESCRIPCION, FLGACTIVO, UNIDADES, VALOR, VALOR_MINIMO, VALOR_MAXIMO, AFINIDAD, INDIVIDUALIZADO, UID_USUARIO) Values
   (45, 16, '6', 'Artículos en otras revistas con proceso anónimo de revisión por pares y referenciadas en SCOPUS', 'Mérito individualizado. Un solo artículo por mérito.La puntuación asignada, 1, en contribuciones de más de cuatro autores se multiplicará por 4 y se dividirá por el número de autores.NO se tendrán en cuenta las publicaciones aceptadas pero sin publicar a fecha de cierre de la bolsa ("Estar en prensa").Se recomienda que la documentación acreditativa del mérito contenga los elementos esenciales que permitan conocer los aspectos formales y el contenido de las publicaciones: : Autor/a, ISBN, editorial, año de publicación, índice completo', 'S', 'DECIMAL', 0.5, 0.1, 1, 'AI', 'S', 'pmperez');
Insert into TBEP_ITEMSBAREMACION (CODNUM, BEPBLO_CODNUM, CODIGO, NOMBRE, DESCRIPCION, FLGACTIVO, UNIDADES, VALOR, VALOR_MINIMO, VALOR_MAXIMO, AFINIDAD, INDIVIDUALIZADO, UID_USUARIO) Values
   (47, 17, '2', 'Editor jefe de revista nacional', 'Mérito individualizado. Una sola participación por mérito.La puntuación a asignar, 1, se dividirá por 1,2,3,4 o 5  de acuerdo con el apartado III.1.1-III.1.5  en que esté  situada la  revista. No se considerará como  mérito la participación en cómites  editoriales de revistas no  contenidas en ninguno de esos apartados.', 'S', 'DECIMAL', 1.5, 0.1, 1, 'AI', 'S', 'pmperez');
Insert into TBEP_ITEMSBAREMACION (CODNUM, BEPBLO_CODNUM, CODIGO, NOMBRE, DESCRIPCION, FLGACTIVO, UNIDADES, VALOR, VALOR_MINIMO, VALOR_MAXIMO, AFINIDAD, INDIVIDUALIZADO, UID_USUARIO) Values
   (48, 17, '3', 'Miembro del comité editorial/evaluador de revista internacional', 'Mérito individualizado. Una sola participación por mérito.La puntuación a asignar, 1, se dividirá por 1,2,3,4 o 5  de acuerdo con el apartado III.1.1-III.1.5  en que esté  situada la  revista. No se considerará como  mérito la participación en cómites  editoriales de revistas no  contenidas en ninguno de esos apartados.', 'S', 'DECIMAL', 1.5, 0.1, 1, 'AI', 'S', 'pmperez');
Insert into TBEP_ITEMSBAREMACION (CODNUM, BEPBLO_CODNUM, CODIGO, NOMBRE, DESCRIPCION, FLGACTIVO, UNIDADES, VALOR, VALOR_MINIMO, VALOR_MAXIMO, AFINIDAD, INDIVIDUALIZADO, UID_USUARIO) Values
   (49, 17, '4', 'Miembro del comité editorial/evaluador de revista nacional', 'Mérito individualizado. Una sola participación por mérito.La puntuación a asignar, 1, se dividirá por 1,2,3,4 o 5  de acuerdo con el apartado III.1.1-III.1.5  en que esté  situada la  revista. No se considerará como  mérito la participación en cómites  editoriales de revistas no  contenidas en ninguno de esos apartados.', 'S', 'DECIMAL', 0.7, 0.1, 1, 'AI', 'S', 'pmperez');
Insert into TBEP_ITEMSBAREMACION (CODNUM, BEPBLO_CODNUM, CODIGO, NOMBRE, DESCRIPCION, FLGACTIVO, UNIDADES, VALOR, VALOR_MINIMO, VALOR_MAXIMO, INDIVIDUALIZADO, UID_USUARIO) Values
   (15, 6, '1', 'Años de disfrute de beca FPI, FPDI o FPU del Plan Nacional análogas de Comunidades Autónomas y Universidades Públicas', 'Hace referencia  a becas predoctorales, no a becas posdoctarales. Como justificante de la credencial de becario se admite el certificado del Vicerrectorado correspondiente.', 'S', 'DECIMAL', 1, 0.1, 30, 'S', 'pmperez');
Insert into TBEP_ITEMSBAREMACION (CODNUM, BEPBLO_CODNUM, CODIGO, NOMBRE, DESCRIPCION, FLGACTIVO, UNIDADES, VALOR, VALOR_MINIMO, VALOR_MAXIMO, AFINIDAD, INDIVIDUALIZADO, UID_USUARIO) Values
   (17, 7, '1', 'Créditos en Títulos Propios, ya sean de máster, especialista o experto universitario', 'No se considera en este apartado el CAP. No confundir con los títulos de Máster Oficial que se valoran en el apartado 1.4.1. No se baremarán los certificados de los cursos que aparezcan en días debiendo figurar en CRÉDITOS reconocidos.Para los certificados en horas se realiza la siguiente equivalencia: 10 horas = 1 crédito Máximo 60 créditos por título Sólo un  título por mérito', 'S', 'DECIMAL', 0.02, 0.1, 1000, 'AA', 'N', 'pmperez');
Insert into TBEP_ITEMSBAREMACION (CODNUM, BEPBLO_CODNUM, CODIGO, NOMBRE, DESCRIPCION, FLGACTIVO, UNIDADES, VALOR, VALOR_MINIMO, VALOR_MAXIMO, AFINIDAD, INDIVIDUALIZADO, UID_USUARIO) Values
   (50, 18, '1', 'Libros o monografías internacionales', 'Mérito individualizado. Un solo libro por mérito.La puntuación asignada, 1, en contribuciones de más de cuatro autores se multiplicará por 4 y se dividirá por el número de autores.NO se tendrán en cuenta las publicaciones aceptadas pero sin publicar a fecha de cierre de la bolsa ("Estar en prensa").Se recomienda que la documentación acreditativa del mérito contenga los elementos esenciales que permitan conocer los aspectos formales y el contenido de las publicaciones: Autor/a, ISBN, editorial, año de publicación, índice completo..', 'S', 'DECIMAL', 3, 0.1, 1, 'AI', 'S', 'pmperez');
Insert into TBEP_ITEMSBAREMACION (CODNUM, BEPBLO_CODNUM, CODIGO, NOMBRE, DESCRIPCION, FLGACTIVO, UNIDADES, VALOR, VALOR_MINIMO, VALOR_MAXIMO, AFINIDAD, INDIVIDUALIZADO, UID_USUARIO) Values
   (52, 18, '3', 'Capítulos de libro internacional', 'Mérito individualizado. Un solo libro por mérito.Máximo 2 capítulos por libro, hasta un máximo de 3 puntos por libro.La puntuación asignada, 1, en contribuciones de más de cuatro autores se multiplicará por 4 y se dividirá por el número de autores.NO se tendrán en cuenta las publicaciones aceptadas pero sin publicar a fecha de cierre de la bolsa ("Estar en prensa").Se recomienda que la documentación acreditativa del mérito contenga los elementos esenciales que permitan conocer los aspectos formales y el contenido de las publicaciones: : Autor/a, ISBN, editorial, año de publicación, índice completoMáximo 2 capítulos por libro, hasta un máximo de 3 puntos por libro', 'S', 'DECIMAL', 1.5, 0.1, 3, 'AI', 'S', 'pmperez');
Insert into TBEP_ITEMSBAREMACION (CODNUM, BEPBLO_CODNUM, CODIGO, NOMBRE, DESCRIPCION, FLGACTIVO, UNIDADES, VALOR, VALOR_MINIMO, VALOR_MAXIMO, AFINIDAD, INDIVIDUALIZADO, UID_USUARIO) Values
   (53, 18, '4', 'Capítulos de libro nacional', 'Mérito individualizado. Un solo libro por mérito.Máximo 2 capítulos por libro, hasta un máximo de 2 puntos por libro.La puntuación asignada, 1, en contribuciones de más de cuatro autores se multiplicará por 4 y se dividirá por el número de autores.NO se tendrán en cuenta las publicaciones aceptadas pero sin publicar a fecha de cierre de la bolsa ("Estar en prensa").Se recomienda que la documentación acreditativa del mérito contenga los elementos esenciales que permitan conocer los aspectos formales y el contenido de las publicaciones: : Autor/a, ISBN, editorial, año de publicación, índice completo', 'S', 'DECIMAL', 1, 0.1, 2, 'AI', 'S', 'pmperez');
Insert into TBEP_ITEMSBAREMACION (CODNUM, BEPBLO_CODNUM, CODIGO, NOMBRE, DESCRIPCION, FLGACTIVO, UNIDADES, VALOR, VALOR_MINIMO, VALOR_MAXIMO, AFINIDAD, INDIVIDUALIZADO, UID_USUARIO) Values
   (55, 18, '6', 'Editor de libro nacional. Podrá sumarse puntuación adicional por capítulos propios hasta un máximo de 2 puntos en total por libro', 'Mérito individualizado. Un sólo libro por mérito.Podrá sumarse puntuación adicional por capítulos propios hasta un máximo de 2 puntos en total por libro.No se considerarán proceedingsNo se considerarán proceedings', 'S', 'ENTERO', 1, 1, 2, 'AI', 'S', 'pmperez');
Insert into TBEP_ITEMSBAREMACION (CODNUM, BEPBLO_CODNUM, CODIGO, NOMBRE, DESCRIPCION, FLGACTIVO, UNIDADES, VALOR, VALOR_MINIMO, VALOR_MAXIMO, AFINIDAD, INDIVIDUALIZADO, UID_USUARIO) Values
   (61, 19, '4', 'Comunicaciones a congresos nacionales', 'Mérito individualizado. Una sola contribucion por mérito.La puntuación asignada, 1, en contribuciones de más de cuatro autores se multiplicará por 4 y se dividirá por el número de autores.Se recomienda que la documentación acreditativa del mérito contenga los elementos esenciales que permitan conocer los aspectos formales y el contenido de las publicaciones: : Autor/a, ISBN, editorial, año de publicación, índice comple', 'S', 'DECIMAL', 0.5, 0.1, 1, 'AI', 'S', 'pmperez');
Insert into TBEP_ITEMSBAREMACION (CODNUM, BEPBLO_CODNUM, CODIGO, NOMBRE, DESCRIPCION, FLGACTIVO, UNIDADES, VALOR, VALOR_MINIMO, VALOR_MAXIMO, AFINIDAD, INDIVIDUALIZADO, UID_USUARIO) Values
   (62, 19, '5', 'Pósteres a congresos internacionales', 'Mérito individualizado. Una sola contribucion por mérito.La puntuación asignada, 1, en contribuciones de más de cuatro autores se multiplicará por 4 y se dividirá por el número de autores.Se recomienda que la documentación acreditativa del mérito contenga los elementos esenciales que permitan conocer los aspectos formales y el contenido de las publicaciones: : Autor/a, ISBN, editorial, año de publicación, índice comple', 'S', 'DECIMAL', 0.5, 0.1, 1, 'AI', 'S', 'pmperez');
Insert into TBEP_ITEMSBAREMACION (CODNUM, BEPBLO_CODNUM, CODIGO, NOMBRE, DESCRIPCION, FLGACTIVO, UNIDADES, VALOR, VALOR_MINIMO, VALOR_MAXIMO, AFINIDAD, INDIVIDUALIZADO, UID_USUARIO) Values
   (64, 19, '7', 'Resúmenes a congresos internacionales', 'Mérito individualizado. Una sola contribucion por mérito.La puntuación asignada, 1, en contribuciones de más de cuatro autores se multiplicará por 4 y se dividirá por el número de autores.Se recomienda que la documentación acreditativa del mérito contenga los elementos esenciales que permitan conocer los aspectos formales y el contenido de las publicaciones: : Autor/a, ISBN, editorial, año de publicación, índice comple', 'S', 'DECIMAL', 0.3, 0.1, 1, 'AI', 'S', 'pmperez');
Insert into TBEP_ITEMSBAREMACION (CODNUM, BEPBLO_CODNUM, CODIGO, NOMBRE, DESCRIPCION, FLGACTIVO, UNIDADES, VALOR, VALOR_MINIMO, VALOR_MAXIMO, AFINIDAD, INDIVIDUALIZADO, UID_USUARIO) Values
   (65, 19, '8', 'Resúmenes a congresos nacionales', 'Mérito individualizado. Una sola contribucion por mérito.La puntuación asignada, 1, en contribuciones de más de cuatro autores se multiplicará por 4 y se dividirá por el número de autores.Se recomienda que la documentación acreditativa del mérito contenga los elementos esenciales que permitan conocer los aspectos formales y el contenido de las publicaciones: : Autor/a, ISBN, editorial, año de publicación, índice comple', 'S', 'DECIMAL', 0.2, 0.1, 1, 'AI', 'S', 'pmperez');
Insert into TBEP_ITEMSBAREMACION (CODNUM, BEPBLO_CODNUM, CODIGO, NOMBRE, DESCRIPCION, FLGACTIVO, UNIDADES, VALOR, VALOR_MINIMO, VALOR_MAXIMO, AFINIDAD, INDIVIDUALIZADO, UID_USUARIO) Values
   (66, 20, '1', 'Proyectos internacionales', 'Mérito individualizado.  Un sólo proyecto por mérito.Para  investigador  principal introducir valor 1. Para el resto de personal introducir valor 0.5.En los proyectos con duración inferior a 3 años se multiplicará  la puntuación anterior por el número  de años o fracción y se dividirá por 3', 'S', 'DECIMAL', 2.5, 0.1, 1, 'AI', 'S', 'pmperez');
Insert into TBEP_ITEMSBAREMACION (CODNUM, BEPBLO_CODNUM, CODIGO, NOMBRE, DESCRIPCION, FLGACTIVO, UNIDADES, VALOR, VALOR_MINIMO, VALOR_MAXIMO, AFINIDAD, INDIVIDUALIZADO, UID_USUARIO) Values
   (68, 20, '3', 'Proyectos autonómicos', 'érito individualizado.  Un sólo proyecto por mérito.Para  investigador  principal introducir valor 1. Para el resto de personal introducir valor 0.5.En los proyectos con duración inferior a 3 años se multiplicará  la puntuación anterior por el número  de años o fracción y se dividirá por 3', 'S', 'DECIMAL', 1, 0.1, 1, 'AI', 'S', 'pmperez');
Insert into TBEP_ITEMSBAREMACION (CODNUM, BEPBLO_CODNUM, CODIGO, NOMBRE, DESCRIPCION, FLGACTIVO, UNIDADES, VALOR, VALOR_MINIMO, VALOR_MAXIMO, AFINIDAD, INDIVIDUALIZADO, UID_USUARIO) Values
   (69, 20, '4', 'Proyectos locales', 'érito individualizado.  Un sólo proyecto por mérito.Para  investigador  principal introducir valor 1. Para el resto de personal introducir valor 0.5.En los proyectos con duración inferior a 3 años se multiplicará  la puntuación anterior por el número  de años o fracción y se dividirá por 3', 'S', 'DECIMAL', 0.7, 0.1, 1, 'AI', 'S', 'pmperez');
Insert into TBEP_ITEMSBAREMACION (CODNUM, BEPBLO_CODNUM, CODIGO, NOMBRE, DESCRIPCION, FLGACTIVO, UNIDADES, VALOR, VALOR_MINIMO, VALOR_MAXIMO, AFINIDAD, INDIVIDUALIZADO, UID_USUARIO) Values
   (19, 8, '2', 'Créditos en cursos relevantes para la plaza', 'La relevancia o no de la actividad formativa la determina discrecionalmente la comisión. En este apartado se podrían valorar congresos que otorgan créditos, sin embargo, no se consideran jornadas.  No se baremarán los certificados de los cursos que aparezcan en días debiendo figurar en CRÉDITOS reconocidos.Para los certificados en horas se realiza la siguiente equivalencia: 10 horas = 1 crédito. Sólo un curso  por mérito', 'S', 'DECIMAL', 0.02, 0.1, 1, 'AA', 'N', 'pmperez');
Insert into TBEP_ITEMSBAREMACION (CODNUM, BEPBLO_CODNUM, CODIGO, NOMBRE, DESCRIPCION, FLGACTIVO, UNIDADES, VALOR, VALOR_MINIMO, VALOR_MAXIMO, INDIVIDUALIZADO, UID_USUARIO) Values
   (20, 8, '3', 'Diploma o certificación oficiales de acreditación de idioma extranjero', 'Acreditación de nivel, de conformidad con las tablas de certificados oficiales aceptados por las universidades andaluzas para la acreditación de lenguas extranjeras y su correspondencia con el Marco Común Europeo de Referencia para las lenguas. Nivel A1 y A2  Marco Europeo de Referencia debe introducir el valor 0.25 Nivel B1 Marco Europeo de Referencia debe introducir el valor 0.50Nivel B2 Marco Europeo de Referencia debe introducir el valor 0.75Nivel C1 y C2 Marco Europeo de Referencia debe introducir el valor 1.00 Sólo se valora el nivel más alto de idioma. No confundir certificado de acreditación de nivel con certificado de superación de cursos de formación de idiomas.', 'S', 'DECIMAL', 0.3, 0.25, 1, 'S', 'pmperez');
Insert into TBEP_ITEMSBAREMACION (CODNUM, BEPBLO_CODNUM, CODIGO, NOMBRE, DESCRIPCION, FLGACTIVO, UNIDADES, VALOR, VALOR_MINIMO, VALOR_MAXIMO, AFINIDAD, INDIVIDUALIZADO, UID_USUARIO) Values
   (70, 20, '5', 'Contratos', 'Mérito  individualizado. Un solo contrato por mérito.La puntuación asignada al contrato,1,cuando  el importe del mismo sea inferior a 60.000 euros se multiplicará  por el importe (en euros) y se  dividirá por 60.000.Este apartado hace referencia a contratos OTRI, no a contratos laborales con la universidad u otra institución. ', 'S', 'DECIMAL', 1, 0.1, 1, 'AI', 'S', 'pmperez');
Insert into TBEP_ITEMSBAREMACION (CODNUM, BEPBLO_CODNUM, CODIGO, NOMBRE, DESCRIPCION, FLGACTIVO, UNIDADES, VALOR, VALOR_MINIMO, VALOR_MAXIMO, AFINIDAD, INDIVIDUALIZADO, UID_USUARIO) Values
   (73, 22, '1', 'Meses de estancia en centro extranjero con financiación ajena', 'Mérito  individualizado. Una sola estancia por  mérito.Las estancias en un mismo centro, pero en distintos períodos temporales, podrán acumularse en un solo pdf.', 'S', 'DECIMAL', 0.2, 0.1, 100, 'AI', 'S', 'pmperez');
Insert into TBEP_ITEMSBAREMACION (CODNUM, BEPBLO_CODNUM, CODIGO, NOMBRE, DESCRIPCION, FLGACTIVO, UNIDADES, VALOR, VALOR_MINIMO, VALOR_MAXIMO, AFINIDAD, INDIVIDUALIZADO, UID_USUARIO) Values
   (76, 23, '2', 'Meses de estancia en centro nacional con financiación ajena', 'En este apartado se incluyen las becas postdoctorales', 'S', 'DECIMAL', 0.2, 0.1, 100, 'AI', 'N', 'pmperez');
Insert into TBEP_ITEMSBAREMACION (CODNUM, BEPBLO_CODNUM, CODIGO, NOMBRE, DESCRIPCION, FLGACTIVO, UNIDADES, VALOR, VALOR_MINIMO, VALOR_MAXIMO, AFINIDAD, INDIVIDUALIZADO, UID_USUARIO) Values
   (78, 24, '2', 'Trabajos de iniciación a la investigación dirigidos', 'Mérito individualizado. Un solo trabajo por mérito.Este apartado hace referencia a la dirección de trabajos de iniciación a la investigación, en el marco de los estudios de doctorado vinculados a la vigencia del  Real Decreto 56/2005, de 21 de enero, por el que se regulan los estudios universitarios oficiales de Posgrado. Los TFM (Trabajo Fin Máster) no son trabajos equiparables a éstos, no obstante, las comisiones de contratación, dentro del ámbito de la discrecionalidad técnica, pueden tener otro criterio siempre y cuando lo justifiquen adecuadamente.   ', 'S', 'ENTERO', 0.2, 1, 1, 'AI', 'S', 'pmperez');
Insert into TBEP_ITEMSBAREMACION (CODNUM, BEPBLO_CODNUM, CODIGO, NOMBRE, DESCRIPCION, FLGACTIVO, UNIDADES, VALOR, VALOR_MINIMO, VALOR_MAXIMO, AFINIDAD, INDIVIDUALIZADO, UID_USUARIO) Values
   (82, 25, '4', 'Premios de investigación locales', 'Mérito  individualizado. Un solo premio por mérito', 'S', 'ENTERO', 0.5, 1, 1, 'AI', 'S', 'pmperez');
Insert into TBEP_ITEMSBAREMACION (CODNUM, BEPBLO_CODNUM, CODIGO, NOMBRE, DESCRIPCION, FLGACTIVO, UNIDADES, VALOR, VALOR_MINIMO, VALOR_MAXIMO, INDIVIDUALIZADO, UID_USUARIO) Values
   (1, 1, '1', 'Nota media de las asignaturas cursadas en la titulación exigida para la plaza', 'La nota que hay introducir obligatoriamente debe estar en la escala de 1 a 4. Se debe introducir nota exacta con decimales. (Tabla de conversión escala 1-10: https://sede.csic.gob.es/tabla_conversion) No se valorará expediente académico de doctorado o máster.  En el caso de titulaciones obtenidas en el extranjero, se deberá estar en posesión de de la correspondiente credencial de homologación o en su caso del correspondientecertificado de equivalencia,salvo  en los  supuestos de los aspirantes que hubieran obtenido el reconocimiento de su cualificación profesional.', 'S', 'DECIMAL', 1, 1, 4, 'S', 'pmperez');
Insert into TBEP_ITEMSBAREMACION (CODNUM, BEPBLO_CODNUM, CODIGO, NOMBRE, DESCRIPCION, FLGACTIVO, UNIDADES, VALOR, VALOR_MINIMO, VALOR_MAXIMO, INDIVIDUALIZADO, UID_USUARIO) Values
   (5, 3, '2', 'Meses de Becario Erasmus, Intercampus, ...', 'Se justificarán los méritos en un solo PDF que incluirá la credencial de becario y un certificado oficial del período de beca disfrutado.', 'S', 'DECIMAL', 0.06, 0.1, 100, 'S', 'pmperez');
Insert into TBEP_ITEMSBAREMACION (CODNUM, BEPBLO_CODNUM, CODIGO, NOMBRE, DESCRIPCION, FLGACTIVO, UNIDADES, VALOR, VALOR_MINIMO, VALOR_MAXIMO, AFINIDAD, INDIVIDUALIZADO, UID_USUARIO) Values
   (8, 5, '1', 'Créditos superados en programas de doctorado', 'Excluyente con los siguientes del apartado  1.5', 'S', 'DECIMAL', 0.1, 0.1, 1000, 'AI', 'N', 'pmperez');
Insert into TBEP_ITEMSBAREMACION (CODNUM, BEPBLO_CODNUM, CODIGO, NOMBRE, DESCRIPCION, FLGACTIVO, UNIDADES, VALOR, VALOR_MINIMO, VALOR_MAXIMO, AFINIDAD, INDIVIDUALIZADO, UID_USUARIO) Values
   (9, 5, '2', 'Por estar matriculado en un programa de doctorado y tener aprobado el proyecto de tesis', 'El plan de investigación se asimila al proyecto de tesis y se acredita con el justificante de tenerlo aprobado parte de la Comisión Académica del programa de doctorado, el cual se puede sustituir por la evaluación anual positiva por parte de dicha Comisión.  Excluyente con 1.5.1, 1.5.3 y 1.5.4, 1.55, 1.5.6 y 1.5.7', 'S', 'SI/NO', 2, 1, 1, 'AI', 'S', 'pmperez');
Insert into TBEP_ITEMSBAREMACION (CODNUM, BEPBLO_CODNUM, CODIGO, NOMBRE, DESCRIPCION, FLGACTIVO, UNIDADES, VALOR, VALOR_MINIMO, VALOR_MAXIMO, AFINIDAD, INDIVIDUALIZADO, UID_USUARIO) Values
   (10, 5, '3', 'Por tener la suficiencia investigadora/DEA/Trabajo Tutelado de INiciación a la Investigación', 'Excluyente con 1.5.1, 1.5.2, 1.5.4, 1.5.5, 1.5.6 y 1.5.7', 'S', 'SI/NO', 3, 1, 1, 'AI', 'S', 'pmperez');
Insert into TBEP_ITEMSBAREMACION (CODNUM, BEPBLO_CODNUM, CODIGO, NOMBRE, DESCRIPCION, FLGACTIVO, UNIDADES, VALOR, VALOR_MINIMO, VALOR_MAXIMO, AFINIDAD, INDIVIDUALIZADO, UID_USUARIO) Values
   (11, 5, '4', 'Por ser doctor', 'Excluyente con 1.5.1, 1.5.2, 1.5.3.Solamente se  valora tener la condición  de doctor, por lo  que no  puntúa tener más de un título de doctorado. Los títulos extranjeros deben estar homologados por una universidad española.', 'S', 'SI/NO', 6, 1, 1, 'AI', 'S', 'pmperez');
Insert into TBEP_ITEMSBAREMACION (CODNUM, BEPBLO_CODNUM, CODIGO, NOMBRE, FLGACTIVO, UNIDADES, VALOR, VALOR_MINIMO, VALOR_MAXIMO, AFINIDAD, INDIVIDUALIZADO, UID_USUARIO) Values
   (12, 5, '5', 'Por doctorado Cum Laude', 'S', 'SI/NO', 3, 1, 1, 'AI', 'S', 'pmperez');
Insert into TBEP_ITEMSBAREMACION (CODNUM, BEPBLO_CODNUM, CODIGO, NOMBRE, FLGACTIVO, UNIDADES, VALOR, VALOR_MINIMO, VALOR_MAXIMO, AFINIDAD, INDIVIDUALIZADO, UID_USUARIO) Values
   (13, 5, '6', 'Premio extraordinario de doctorado', 'S', 'SI/NO', 3, 1, 1, 'AI', 'S', 'pmperez');
Insert into TBEP_ITEMSBAREMACION (CODNUM, BEPBLO_CODNUM, CODIGO, NOMBRE, FLGACTIVO, UNIDADES, VALOR, VALOR_MINIMO, VALOR_MAXIMO, AFINIDAD, INDIVIDUALIZADO, UID_USUARIO) Values
   (14, 5, '7', 'Por doctorado europeo o internacional', 'S', 'SI/NO', 3, 1, 1, 'AI', 'S', 'pmperez');
Insert into TBEP_ITEMSBAREMACION (CODNUM, BEPBLO_CODNUM, CODIGO, NOMBRE, DESCRIPCION, FLGACTIVO, UNIDADES, VALOR, VALOR_MINIMO, VALOR_MAXIMO, INDIVIDUALIZADO, UID_USUARIO) Values
   (16, 6, '2', 'Años de disfrute de beca de investigación no homologada por la Universidad de Jaén', 'No se consideran las becas de tecnólogos o técnicos', 'S', 'DECIMAL', 0.5, 0.1, 30, 'S', 'pmperez');
Insert into TBEP_ITEMSBAREMACION (CODNUM, BEPBLO_CODNUM, CODIGO, NOMBRE, DESCRIPCION, FLGACTIVO, UNIDADES, VALOR, VALOR_MINIMO, VALOR_MAXIMO, INDIVIDUALIZADO, UID_USUARIO) Values
   (18, 8, '1', 'Créditos en cursos de formación en materia de innovación docente universitaria', 'No se considera en este apartado el CAP Sólo un curso por mérito', 'S', 'DECIMAL', 0.06, 0.1, 1, 'S', 'pmperez');
Insert into TBEP_ITEMSBAREMACION (CODNUM, BEPBLO_CODNUM, CODIGO, NOMBRE, DESCRIPCION, FLGACTIVO, UNIDADES, VALOR, VALOR_MINIMO, VALOR_MAXIMO, AFINIDAD, INDIVIDUALIZADO, UID_USUARIO) Values
   (21, 9, '1', 'Créditos impartidos en docencia universitaria reglada de primer y segundo ciclo y grado', '1 crédito equivale a 10 h. Se debe introducir valor en número de créditos. En  certificaciones  realizadas por cursos académicos,  un  curso a tiempo completo equivale a 24 créditos o parte proporcional en supuesto de tiempo  parcial. No computan como créditos docentes las horas de atención tutorial.  ', 'S', 'DECIMAL', 0.13, 0.1, 1000, 'AA', 'N', 'pmperez');
Insert into TBEP_ITEMSBAREMACION (CODNUM, BEPBLO_CODNUM, CODIGO, NOMBRE, DESCRIPCION, FLGACTIVO, UNIDADES, VALOR, VALOR_MINIMO, VALOR_MAXIMO, AFINIDAD, INDIVIDUALIZADO, UID_USUARIO) Values
   (22, 9, '2', 'Créditos impartidos en programas de doctorado o máster oficiales', '1 crédito equivale a 10 h.', 'S', 'DECIMAL', 0.15, 0.1, 1000, 'AA', 'N', 'pmperez');
Insert into TBEP_ITEMSBAREMACION (CODNUM, BEPBLO_CODNUM, CODIGO, NOMBRE, DESCRIPCION, FLGACTIVO, UNIDADES, VALOR, VALOR_MINIMO, VALOR_MAXIMO, AFINIDAD, INDIVIDUALIZADO, UID_USUARIO) Values
   (23, 9, '3', 'Cursos académicos como tutor de prácticas externas regladas', 'Un máximo de tres curso académicos', 'S', 'DECIMAL', 0.25, 0.1, 3, 'AA', 'N', 'pmperez');
Insert into TBEP_ITEMSBAREMACION (CODNUM, BEPBLO_CODNUM, CODIGO, NOMBRE, DESCRIPCION, FLGACTIVO, UNIDADES, VALOR, VALOR_MINIMO, VALOR_MAXIMO, AFINIDAD, INDIVIDUALIZADO, UID_USUARIO) Values
   (24, 9, '4', 'Dirección de Proyectos fin de carrera / fin de grado / fin de máster', 'Sólo se valoran la  dirección de proyectos terminados, no en proceso de dirección. Se acredita con certificado del director o decano del centro. Sólo una dirección por mérito', 'S', 'ENTERO', 0.05, 1, 1, 'AA', 'S', 'pmperez');
Insert into TBEP_ITEMSBAREMACION (CODNUM, BEPBLO_CODNUM, CODIGO, NOMBRE, DESCRIPCION, FLGACTIVO, UNIDADES, VALOR, VALOR_MINIMO, VALOR_MAXIMO, AFINIDAD, INDIVIDUALIZADO, UID_USUARIO) Values
   (26, 11, '1', 'Años de docencia de enseñanza secundaria en centros oficiales', 'A tiempo completo o parte proporcional si es a tiempo parcial', 'S', 'DECIMAL', 0.3, 0.1, 50, 'AA', 'N', 'pmperez');
Insert into TBEP_ITEMSBAREMACION (CODNUM, BEPBLO_CODNUM, CODIGO, NOMBRE, DESCRIPCION, FLGACTIVO, UNIDADES, VALOR, VALOR_MINIMO, VALOR_MAXIMO, AFINIDAD, INDIVIDUALIZADO, UID_USUARIO) Values
   (27, 11, '2', 'Créditos impartidos en cursos de formación', 'Mérito individualizado. Sólo un curso por mérito', 'S', 'DECIMAL', 0.04, 0.1, 1000, 'AA', 'N', 'pmperez');
Insert into TBEP_ITEMSBAREMACION (CODNUM, BEPBLO_CODNUM, CODIGO, NOMBRE, DESCRIPCION, FLGACTIVO, UNIDADES, VALOR, VALOR_MINIMO, VALOR_MAXIMO, AFINIDAD, INDIVIDUALIZADO, UID_USUARIO) Values
   (29, 12, '2', 'Capítulos de libros internacionales', 'Mérito  individualizado. Sólo un libro por mérito. Máximo 2 capítulos por cada libro.La consideración de internacionalidad o nacionalidad es criterio de la comisión. ', 'S', 'ENTERO', 1.5, 1, 2, 'AA', 'S', 'pmperez');
Insert into TBEP_ITEMSBAREMACION (CODNUM, BEPBLO_CODNUM, CODIGO, NOMBRE, DESCRIPCION, FLGACTIVO, UNIDADES, VALOR, VALOR_MINIMO, VALOR_MAXIMO, AFINIDAD, INDIVIDUALIZADO, UID_USUARIO) Values
   (32, 12, '5', 'Manuales, libros de prácticas o similares', 'Mérito  individualizado. Sólo un manual por mérito', 'S', 'ENTERO', 0.7, 1, 1, 'AA', 'S', 'pmperez');
Insert into TBEP_ITEMSBAREMACION (CODNUM, BEPBLO_CODNUM, CODIGO, NOMBRE, DESCRIPCION, FLGACTIVO, UNIDADES, VALOR, VALOR_MINIMO, VALOR_MAXIMO, AFINIDAD, INDIVIDUALIZADO, UID_USUARIO) Values
   (33, 12, '6', 'Tutoriales para docencia en red', 'Mérito  individualizado. Sólo un tutorial por mérito', 'S', 'ENTERO', 0.5, 1, 1, 'AA', 'S', 'pmperez');
Insert into TBEP_ITEMSBAREMACION (CODNUM, BEPBLO_CODNUM, CODIGO, NOMBRE, DESCRIPCION, FLGACTIVO, UNIDADES, VALOR, VALOR_MINIMO, VALOR_MAXIMO, AFINIDAD, INDIVIDUALIZADO, UID_USUARIO) Values
   (36, 14, '2', 'Ponencias invitadas a congresos nacionales de innovación docente, no  relacionados con la investigación.', 'Mérito individualizado. Una sola ponencia por mérito. La puntuación asignada, 1, en contribuciones de más de cuatro autores se multiplicará por 4 y se dividirá por el número de autores', 'S', 'DECIMAL', 0.8, 0.1, 1, 'AA', 'S', 'pmperez');
Insert into TBEP_ITEMSBAREMACION (CODNUM, BEPBLO_CODNUM, CODIGO, NOMBRE, FLGACTIVO, UNIDADES, VALOR, VALOR_MINIMO, VALOR_MAXIMO, AFINIDAD, INDIVIDUALIZADO, UID_USUARIO) Values
   (39, 15, '1', 'Créditos de asignatura impartida en idioma extranjero en títulos oficiales', 'S', 'DECIMAL', 0.05, 0.01, 1000, 'AA', 'N', 'pmperez');
Insert into TBEP_ITEMSBAREMACION (CODNUM, BEPBLO_CODNUM, CODIGO, NOMBRE, DESCRIPCION, FLGACTIVO, UNIDADES, VALOR, VALOR_MINIMO, VALOR_MAXIMO, AFINIDAD, INDIVIDUALIZADO, UID_USUARIO) Values
   (43, 16, '4', 'Artículos en revistas situadas en el 4º cuartil del Journal Citation Report o en segundo cuartil los indices de referencia utilizados para la evaluación de la actividad investigadora por CNEAI, en caso de no usarse JCR', 'Mérito individualizado. Un solo artículo por mérito.La puntuación asignada, 1, en contribuciones de más de cuatro autores se multiplicará por 4 y se dividirá por el número de autores.NO se tendrán en cuenta las publicaciones aceptadas pero sin publicar a fecha de cierre de la bolsa ("Estar en prensa").Se recomienda que la documentación acreditativa del mérito contenga los elementos esenciales que permitan conocer los aspectos formales y el contenido de las publicaciones: : Autor/a, ISBN, editorial, año de publicación, índice completo', 'S', 'DECIMAL', 2.8, 0.1, 1, 'AI', 'S', 'pmperez');
Insert into TBEP_ITEMSBAREMACION (CODNUM, BEPBLO_CODNUM, CODIGO, NOMBRE, DESCRIPCION, FLGACTIVO, UNIDADES, VALOR, VALOR_MINIMO, VALOR_MAXIMO, AFINIDAD, INDIVIDUALIZADO, UID_USUARIO) Values
   (46, 17, '1', 'Editor jefe de revista internacional', 'Mérito individualizado. Una sola participación por mérito.La puntuación a asignar, 1, se dividirá por 1,2,3,4 o 5  de acuerdo con el apartado III.1.1-III.1.5  en que esté  situada la  revista. No se considerará como  mérito la participación en cómites  editoriales de revistas no  contenidas en ninguno de esos apartados.', 'S', 'DECIMAL', 3, 0.1, 1, 'AI', 'S', 'pmperez');
Insert into TBEP_ITEMSBAREMACION (CODNUM, BEPBLO_CODNUM, CODIGO, NOMBRE, DESCRIPCION, FLGACTIVO, UNIDADES, VALOR, VALOR_MINIMO, VALOR_MAXIMO, AFINIDAD, INDIVIDUALIZADO, UID_USUARIO) Values
   (51, 18, '2', 'Libros o monografías nacionales', 'Mérito individualizado. Un solo libro por mérito.La puntuación asignada, 1, en contribuciones de más de cuatro autores se multiplicará por 4 y se dividirá por el número de autores.NO se tendrán en cuenta las publicaciones aceptadas pero sin publicar a fecha de cierre de la bolsa ("Estar en prensa").Se recomienda que la documentación acreditativa del mérito contenga los elementos esenciales que permitan conocer los aspectos formales y el contenido de las publicaciones: : Autor/a, ISBN, editorial, año de publicación, índice completo.No se consideran actas ', 'S', 'DECIMAL', 2, 0.1, 1, 'AI', 'S', 'pmperez');
Insert into TBEP_ITEMSBAREMACION (CODNUM, BEPBLO_CODNUM, CODIGO, NOMBRE, DESCRIPCION, FLGACTIVO, UNIDADES, VALOR, VALOR_MINIMO, VALOR_MAXIMO, AFINIDAD, INDIVIDUALIZADO, UID_USUARIO) Values
   (54, 18, '5', 'Editor de libro internacional. Podrá sumarse puntuación adicional por capítulos propios hasta un máximo de 3 puntos en total por libro', 'Mérito individualizado. Un sólo libro por méritoPodrá sumarse puntuación adicional por capítulos propios hasta un máximo de 3 puntos en total por libroNo se considerarán proceedings', 'S', 'ENTERO', 1.5, 1, 3, 'AI', 'S', 'pmperez');
Insert into TBEP_ITEMSBAREMACION (CODNUM, BEPBLO_CODNUM, CODIGO, NOMBRE, DESCRIPCION, FLGACTIVO, UNIDADES, VALOR, VALOR_MINIMO, VALOR_MAXIMO, AFINIDAD, INDIVIDUALIZADO, UID_USUARIO) Values
   (56, 18, '7', 'Recensiones de libros', 'Mérito individualizado. Una sola  recensión por mérito.', 'S', 'ENTERO', 0.5, 1, 1, 'AI', 'S', 'pmperez');
Insert into TBEP_ITEMSBAREMACION (CODNUM, BEPBLO_CODNUM, CODIGO, NOMBRE, DESCRIPCION, FLGACTIVO, UNIDADES, VALOR, VALOR_MINIMO, VALOR_MAXIMO, AFINIDAD, INDIVIDUALIZADO, UID_USUARIO) Values
   (57, 18, '8', 'Traducciones de libros', 'Mérito individualizado. Una sola traducción por mérito', 'S', 'ENTERO', 0.5, 1, 1, 'AI', 'S', 'pmperez');