INSERT INTO TBEP_MERITOS_PREFERENTES (CODIGO, NOMBRE, OBSERVACIONES, TIPO, TIPO_CALCULO, APLICABLE, BASE, FACTOR, VALOR_MAXIMO, BEPITE_TIPO_CODNUM, BEPBLO_APLICABLE_CODNUM, BEPAPA_APLICABLE_CODNUM, BEPITE_APLICABLE_CODNUM, FLGACTIVO, UID_USUARIO)
VALUES('1', 'Estar en posesión de alguna de las titulaciones preferentes de acceso a la plaza.', NULL, 'TITULACION_PREFERENTE', 'FACTOR', 'APARTADO', NULL, 1.5, NULL, NULL, NULL, 1, NULL, 'S', 'CARGA_INICIAL');
INSERT INTO TBEP_MERITOS_PREFERENTES (CODIGO, NOMBRE, OBSERVACIONES, TIPO, TIPO_CALCULO, APLICABLE, BASE, FACTOR, VALOR_MAXIMO, BEPITE_TIPO_CODNUM, BEPBLO_APLICABLE_CODNUM, BEPAPA_APLICABLE_CODNUM, BEPITE_APLICABLE_CODNUM, FLGACTIVO, UID_USUARIO)
VALUES('2', 'Haber cumplido el período de cuatro años de formación de personal investigador a que se refiere el art. 64 de la LAU', '(solo para las plazas de ayudante)', 'MERITO', 'FACTOR', 'APARTADO', NULL, 1.1, NULL, 15, NULL, 3, NULL, 'S', 'CARGA_INICIAL');
INSERT INTO TBEP_MERITOS_PREFERENTES (CODIGO, NOMBRE, OBSERVACIONES, TIPO, TIPO_CALCULO, APLICABLE, BASE, FACTOR, VALOR_MAXIMO, BEPITE_TIPO_CODNUM, BEPBLO_APLICABLE_CODNUM, BEPAPA_APLICABLE_CODNUM, BEPITE_APLICABLE_CODNUM, FLGACTIVO, UID_USUARIO)
VALUES('3', 'Estar acreditado como...', NULL, 'POSESION', 'OPCIONES', 'TOTAL', NULL, 0, NULL, NULL, NULL, NULL, NULL, 'S', 'CARGA_INICIAL');
INSERT INTO TBEP_MER_PRE_OPCIONES (BEPMEP_CODNUM, NOMBRE, FACTOR, FLGBORRADO, FECHA_BORRADO, UID_USUARIO)
VALUES((SELECT CODNUM FROM TBEP_MERITOS_PREFERENTES WHERE CODIGO = '3'), 'Profesor Colaborador', 1.1, 'N', NULL, 'CARGA_INICIAL');
INSERT INTO TBEP_MER_PRE_OPCIONES (BEPMEP_CODNUM, NOMBRE, FACTOR, FLGBORRADO, FECHA_BORRADO, UID_USUARIO)
VALUES((SELECT CODNUM FROM TBEP_MERITOS_PREFERENTES WHERE CODIGO = '3'), 'Ayudante Doctor', 1.2, 'N', NULL, 'CARGA_INICIAL');
INSERT INTO TBEP_MER_PRE_OPCIONES (BEPMEP_CODNUM, NOMBRE, FACTOR, FLGBORRADO, FECHA_BORRADO, UID_USUARIO)
VALUES((SELECT CODNUM FROM TBEP_MERITOS_PREFERENTES WHERE CODIGO = '3'), 'Contratado Doctor', 1.3, 'N', NULL, 'CARGA_INICIAL');
INSERT INTO TBEP_MER_PRE_OPCIONES (BEPMEP_CODNUM, NOMBRE, FACTOR, FLGBORRADO, FECHA_BORRADO, UID_USUARIO)
VALUES((SELECT CODNUM FROM TBEP_MERITOS_PREFERENTES WHERE CODIGO = '3'), 'Titular de Universidad', 1.4, 'N', NULL, 'CARGA_INICIAL');