INSERT INTO TBEP_USUARIOS (PRSNIF,CODCUENTA,ROL,DIRECCION,CODIGOPOSTAL,LOCALIDAD,PROVINCIA,NACIONALIDAD,FLGLISTADISTRIBUCION,FLGEXCLUIDO,FLGBORRADO,UID_USUARIO)
VALUES ('B18865253', 'atisoluciones', 1050, 'C. Cordoba Nº2', '18210', 'Peligros', 'Granada', 'Español', 'S', 'N', 'N', 'CARGA_INICIAL');
