Insert into TBEP_MERITOS_EXCLUYENTES
   (CODNUM, BEPITE_CODNUM_PADRE, BEPITE_CODNUM_HIJO, UID_USUARIO)
 Values
   (17, 10, 8, 'pmperez');
Insert into TBEP_MERITOS_EXCLUYENTES
   (CODNUM, BEPITE_CODNUM_PADRE, BEPITE_CODNUM_HIJO, UID_USUARIO)
 Values
   (18, 10, 9, 'pmperez');
Insert into TBEP_MERITOS_EXCLUYENTES
   (CODNUM, BEPITE_CODNUM_PADRE, BEPITE_CODNUM_HIJO, UID_USUARIO)
 Values
   (19, 10, 11, 'pmperez');
Insert into TBEP_MERITOS_EXCLUYENTES
   (CODNUM, BEPITE_CODNUM_PADRE, BEPITE_CODNUM_HIJO, UID_USUARIO)
 Values
   (20, 10, 12, 'pmperez');
Insert into TBEP_MERITOS_EXCLUYENTES
   (CODNUM, BEPITE_CODNUM_PADRE, BEPITE_CODNUM_HIJO, UID_USUARIO)
 Values
   (21, 10, 13, 'pmperez');
Insert into TBEP_MERITOS_EXCLUYENTES
   (CODNUM, BEPITE_CODNUM_PADRE, BEPITE_CODNUM_HIJO, UID_USUARIO)
 Values
   (22, 10, 14, 'pmperez');
Insert into TBEP_MERITOS_EXCLUYENTES
   (CODNUM, BEPITE_CODNUM_PADRE, BEPITE_CODNUM_HIJO, UID_USUARIO)
 Values
   (23, 9, 8, 'pmperez');
Insert into TBEP_MERITOS_EXCLUYENTES
   (CODNUM, BEPITE_CODNUM_PADRE, BEPITE_CODNUM_HIJO, UID_USUARIO)
 Values
   (24, 9, 10, 'pmperez');
Insert into TBEP_MERITOS_EXCLUYENTES
   (CODNUM, BEPITE_CODNUM_PADRE, BEPITE_CODNUM_HIJO, UID_USUARIO)
 Values
   (25, 9, 11, 'pmperez');
Insert into TBEP_MERITOS_EXCLUYENTES
   (CODNUM, BEPITE_CODNUM_PADRE, BEPITE_CODNUM_HIJO, UID_USUARIO)
 Values
   (26, 9, 12, 'pmperez');
Insert into TBEP_MERITOS_EXCLUYENTES
   (CODNUM, BEPITE_CODNUM_PADRE, BEPITE_CODNUM_HIJO, UID_USUARIO)
 Values
   (27, 9, 13, 'pmperez');
Insert into TBEP_MERITOS_EXCLUYENTES
   (CODNUM, BEPITE_CODNUM_PADRE, BEPITE_CODNUM_HIJO, UID_USUARIO)
 Values
   (28, 9, 14, 'pmperez');
Insert into TBEP_MERITOS_EXCLUYENTES
   (CODNUM, BEPITE_CODNUM_PADRE, BEPITE_CODNUM_HIJO, UID_USUARIO)
 Values
   (29, 11, 8, 'pmperez');
Insert into TBEP_MERITOS_EXCLUYENTES
   (CODNUM, BEPITE_CODNUM_PADRE, BEPITE_CODNUM_HIJO, UID_USUARIO)
 Values
   (30, 11, 9, 'pmperez');
Insert into TBEP_MERITOS_EXCLUYENTES
   (CODNUM, BEPITE_CODNUM_PADRE, BEPITE_CODNUM_HIJO, UID_USUARIO)
 Values
   (31, 11, 10, 'pmperez');
Insert into TBEP_MERITOS_EXCLUYENTES
   (CODNUM, BEPITE_CODNUM_PADRE, BEPITE_CODNUM_HIJO, UID_USUARIO)
 Values
   (13, 8, 9, 'pmperez');
Insert into TBEP_MERITOS_EXCLUYENTES
   (CODNUM, BEPITE_CODNUM_PADRE, BEPITE_CODNUM_HIJO, UID_USUARIO)
 Values
   (14, 8, 10, 'pmperez');
Insert into TBEP_MERITOS_EXCLUYENTES
   (CODNUM, BEPITE_CODNUM_PADRE, BEPITE_CODNUM_HIJO, UID_USUARIO)
 Values
   (15, 8, 11, 'pmperez');
Insert into TBEP_MERITOS_EXCLUYENTES
   (CODNUM, BEPITE_CODNUM_PADRE, BEPITE_CODNUM_HIJO, UID_USUARIO)
 Values
   (16, 8, 12, 'pmperez');