-- creación registros pruebas;
Insert into UVIRTUAL.DCT_CONVOCATORIAS (IDCONVOCATORIA,NOMBRECONVOCATORIA,ESTADO,OBSERVACIONES,FECHALIMITE,FECHACOMISION) 
values (1,'convocatoria abierta','ABIERTA','observaciones 1',to_date('31-08-52','DD-MM-RR'), to_date('31-08-52','DD-MM-RR'));
Insert into UVIRTUAL.DCT_CONVOCATORIAS (IDCONVOCATORIA,NOMBRECONVOCATORIA,ESTADO,OBSERVACIONES,FECHALIMITE,FECHACOMISION) 
values (2,'convocatoria cerrada','CERRADA','observaciones 2',to_date('31-08-52','DD-MM-RR'),to_date('31-08-52','DD-MM-RR'));
Insert into UVIRTUAL.DCT_CONVOCATORIAS (IDCONVOCATORIA,NOMBRECONVOCATORIA,ESTADO,OBSERVACIONES,FECHALIMITE,FECHACOMISION) 
values (3,'convocatoria abierta pasada','ABIERTA','observaciones 3',to_date('31-08-22','DD-MM-RR'),to_date('31-08-52','DD-MM-RR'));
Insert into UVIRTUAL.DCT_CONVOCATORIAS (IDCONVOCATORIA,NOMBRECONVOCATORIA,ESTADO,OBSERVACIONES,FECHALIMITE,FECHACOMISION) 
values (4,'convocatoria creada','CREADA','observaciones',to_date('31-08-58','DD-MM-RR'),to_date('31-08-52','DD-MM-RR'));
Insert into UVIRTUAL.DCT_CONVOCATORIAS (IDCONVOCATORIA,NOMBRECONVOCATORIA,ESTADO,OBSERVACIONES,FECHALIMITE,FECHACOMISION) 
values (5,'convocatoria para borrar','CREADA','observaciones',to_date('31-08-58','DD-MM-RR'),to_date('31-08-52','DD-MM-RR'));