INSERT INTO UVIRTUAL.TBEP_USUARIOS (PRSNIF,CODCUENTA,ROL,DIRECCION,CODIGOPOSTAL,LOCALIDAD,PROVINCIA,NACIONALIDAD,FLGLISTADISTRIBUCION,FLGEXCLUIDO,FLGBORRADO)
VALUES ('62607992Z','personal1', 1050, 'Calle Ejemplo Personal1', '11111', 'GRANADA', 'GRANADA', 'ESPAÑOL',
		'S', 'N', 'N');
INSERT INTO UVIRTUAL.TBEP_USUARIOS (PRSNIF,CODCUENTA,ROL,DIRECCION,CODIGOPOSTAL,LOCALIDAD,PROVINCIA,NACIONALIDAD,FLGLISTADISTRIBUCION,FLGEXCLUIDO,FLGBORRADO)
VALUES ('36393760D','comision1', 1051, 'Calle Ejemplo Personal1', '11111', 'GRANADA', 'GRANADA', 'ESPAÑOL',
		'S', 'N', 'N');
INSERT INTO UVIRTUAL.TBEP_USUARIOS (PRSNIF,CODCUENTA,ROL,DIRECCION,CODIGOPOSTAL,LOCALIDAD,PROVINCIA,NACIONALIDAD,FLGLISTADISTRIBUCION,FLGEXCLUIDO,FLGBORRADO)
VALUES ('03465896A','director1', 1053, 'Calle Ejemplo Personal1', '11111', 'GRANADA', 'GRANADA', 'ESPAÑOL',
		'S', 'N', 'N');
INSERT INTO UVIRTUAL.TBEP_USUARIOS (PRSNIF,CODCUENTA,ROL,DIRECCION,CODIGOPOSTAL,LOCALIDAD,PROVINCIA,NACIONALIDAD,FLGLISTADISTRIBUCION,FLGEXCLUIDO,FLGBORRADO)
VALUES ('43396488L','candidato1', 1052, 'Calle Ejemplo Candidato1', '11111', 'GRANADA', 'GRANADA', 'ESPAÑOL',
		'S', 'N', 'N');
		INSERT INTO UVIRTUAL.TBEP_USUARIOS (PRSNIF,CODCUENTA,ROL,DIRECCION,CODIGOPOSTAL,LOCALIDAD,PROVINCIA,NACIONALIDAD,FLGLISTADISTRIBUCION,FLGEXCLUIDO,FLGBORRADO)
VALUES ('91606989J','candidato2', 1052, 'Calle Ejemplo Candidato2', '11111', 'GRANADA', 'GRANADA', 'ESPAÑOL',
		'S', 'N', 'N');
		INSERT INTO UVIRTUAL.TBEP_USUARIOS (PRSNIF,CODCUENTA,ROL,DIRECCION,CODIGOPOSTAL,LOCALIDAD,PROVINCIA,NACIONALIDAD,FLGLISTADISTRIBUCION,FLGEXCLUIDO,FLGBORRADO,FECHA_BORRADO)
VALUES ('12312312Z','testusuarioborrado', 1052, 'Calle borrado', '11111', 'GRANADA', 'GRANADA', 'ESPAÑOL',
		'S', 'N', 'S', TO_DATE('2021-06-29', 'yyyy-mm-dd'));
		INSERT INTO UVIRTUAL.TBEP_USUARIOS (PRSNIF,CODCUENTA,ROL,DIRECCION,CODIGOPOSTAL,LOCALIDAD,PROVINCIA,NACIONALIDAD,FLGLISTADISTRIBUCION,FLGEXCLUIDO,FLGEXCLUIDOTIPO,FECHA_EXCLUSION,FECHA_EXCLUSION_INICIO,FECHA_EXCLUSION_FIN,FLGBORRADO)
VALUES ('32132121Z','testusuarioexcluido', 1052, 'Calle borrado', '11111', 'GRANADA', 'GRANADA', 'ESPAÑOL',
		'S', 'S','T',TO_DATE('2021-06-29', 'yyyy-mm-dd'),TO_DATE('2021-06-29', 'yyyy-mm-dd'),TO_DATE('2021-07-29', 'yyyy-mm-dd'), 'N');
		
		INSERT INTO UVIRTUAL.TBEP_USUARIOS (PRSNIF,CODCUENTA,ROL,DIRECCION,CODIGOPOSTAL,LOCALIDAD,PROVINCIA,NACIONALIDAD,FLGLISTADISTRIBUCION,FLGEXCLUIDO,FLGBORRADO)
VALUES ('11111222Z','tesTitulaciones', 1050, 'Calle Ejemplo tesTitulaciones', '11111', 'GRANADA', 'GRANADA', 'ESPAÑOL',
		'S', 'N', 'N');
		