INSERT INTO TBEP_FICHEROS (NOMBRE,TITULO,ARCHIVO,FLGPUBLICO,UID_USUARIO)
VALUES ('archivo1.pdf', 'titulo1', hextoraw('4041424344'), 'S', 'CARGA_INICIAL');
INSERT INTO TBEP_FICHEROS (NOMBRE,TITULO,ARCHIVO,FLGPUBLICO,UID_USUARIO)
VALUES ('archivo2.pdf', 'titulo2', hextoraw('4041424344'), 'N', 'CARGA_INICIAL');
INSERT INTO TBEP_FICHEROS (NOMBRE,TITULO,ARCHIVO,FLGPUBLICO,UID_USUARIO)
VALUES ('archivo3.pdf', 'titulo3', hextoraw('4041424344'), 'N', 'CARGA_INICIAL');
INSERT INTO TBEP_FICHEROS (NOMBRE,TITULO,ARCHIVO,FLGPUBLICO,UID_USUARIO)
VALUES ('archivo4.test', 'titulo4', hextoraw('4041424344'), 'S', 'CARGA_INICIAL');