INSERT INTO TBEP_DEPARTAMENTOS (ID_DEPARTAMENTO, DES_DEPARTAMENTO)
SELECT DISTINCT uvnbrdsa.ID_DEPARTAMENTO AS ID_DEPARTAMENTO, uvnbrdsa.DES_DEPARTAMENTO 
FROM UXXIRRHH_VUJA_NET_BEP_RH_DEPTO_SECC_AREA uvnbrdsa;
--/////////////////////
INSERT INTO TBEP_AREAS (ID_AREA_CONOCIMIENTO, ID_SECCION, DES_AREA_CONOCIMIENTO, BEPDEP_CODNUM)
SELECT
	uvnbrdsa.ID_AREA_CONOCIMIENTO,
	MIN(uvnbrdsa.ID_SECCION) AS ID_SECCION,
	MIN(uvnbrdsa.DES_AREA_CONOCIMIENTO) AS DES_AREA_CONOCIMIENTO,
	MIN(td.CODNUM) AS BEPDEP_CODNUM
FROM UXXIRRHH_VUJA_NET_BEP_RH_DEPTO_SECC_AREA uvnbrdsa
INNER JOIN TBEP_DEPARTAMENTOS td ON TD.ID_DEPARTAMENTO = uvnbrdsa.ID_DEPARTAMENTO
GROUP BY uvnbrdsa.ID_AREA_CONOCIMIENTO;