INSERT INTO TBEP_EVALUADORES (BEPARE_CODNUM, BEPUSU_CODNUM, UID_USUARIO)
SELECT
	bepade.BEPARE_CODNUM AS BEPARE_CODNUM,
	3 AS BEPUSU_CODNUM,
	'CARGA_INICIAL' AS UID_USUARIO
FROM TBEP_AREAS_DEPARTAMENTOS bepade
INNER JOIN TBEP_DEPARTAMENTOS bepdep ON bepdep.CODNUM = bepade.BEPDEP_CODNUM 
WHERE bepdep.DES_DEPARTAMENTO LIKE '%MATEMÁTICAS%' FETCH FIRST 3 ROWS ONLY;