INSERT INTO TBEP_TITULACIONESAREA (BEPARE_CODNUM, BEPTIT_CODNUM)
SELECT
	bepare.CODNUM AS BEPARE_CODNUM,
	beptit.CODNUM AS BEPTIT_CODNUM
FROM TBEP_TITULACIONES beptit, TBEP_AREAS bepare ORDER BY bepare.DES_AREA_CONOCIMIENTO FETCH FIRST 1 ROWS ONLY;