INSERT INTO TBEP_EVALUADORES (BEPARE_CODNUM, BEPUSU_CODNUM)
SELECT
	bepare.CODNUM AS BEPARE_CODNUM,
	bepusu.CODNUM AS BEPUSU_CODNUM
FROM TBEP_USUARIOS bepusu, TBEP_AREAS bepare WHERE bepusu.ROL = 1051 AND bepusu.FLGBORRADO!='S' AND bepusu.FLGEXCLUIDO!='S' ORDER BY bepare.DES_AREA_CONOCIMIENTO FETCH FIRST 2 ROWS ONLY;