INSERT INTO VUJA_NET_BEP_AR_PERSONA (CODINT,STRTIPODOCUMENTO,IDNIF,LETRANIF,STRNOMBRE,STRAPELLIDO1,STRAPELLIDO2,EMAIL_ALTA)
VALUES (1,'DNI','12345678','A','ATIS','ATISAPELLIDO1','ATISAPELLIDO2','atis@atis.com');
INSERT INTO VUJA_NET_BEP_AR_PERSONA (CODINT,STRTIPODOCUMENTO,IDNIF,LETRANIF,STRNOMBRE,STRAPELLIDO1,STRAPELLIDO2,EMAIL_ALTA)
VALUES (2,'DNI','87654321','B','ESTUDIANTE1','ESTUDIANTE1APELLIDO1','ESTUDIANTE1APELLIDO2','estudiante1@estudiante1.com');
INSERT INTO VUJA_NET_BEP_AR_PERSONA (CODINT,STRTIPODOCUMENTO,IDNIF,LETRANIF,STRNOMBRE,STRAPELLIDO1,STRAPELLIDO2,EMAIL_ALTA)
VALUES (3,'DNI','87654321','B','USIG','USIGAPELLIDO1','USIGAPELLIDO2','usig@usig.com');
INSERT INTO VUJA_NET_BEP_AR_PERSONA (CODINT,STRTIPODOCUMENTO,IDNIF,LETRANIF,STRNOMBRE,STRAPELLIDO1,STRAPELLIDO2,EMAIL_ALTA)
VALUES (4,'NIF','99988877','C','EJEMPLO','EJEMPLOAPELLIDO1','EJEMPLOAPELLIDO2','ejemplo@ejemplo.com');
INSERT INTO VUJA_NET_BEP_AR_PERSONA (CODINT,STRTIPODOCUMENTO,IDNIF,LETRANIF,STRNOMBRE,STRAPELLIDO1,STRAPELLIDO2,EMAIL_ALTA)
VALUES (5,'NIF','99988877','C','PRUEBA','PRUEBAAPELLIDO1','PRUEBAAPELLIDO2','prueba@prueba.com');
INSERT INTO VUJA_NET_BEP_AR_PERSONA (CODINT,STRTIPODOCUMENTO,IDNIF,LETRANIF,STRNOMBRE,STRAPELLIDO1,STRAPELLIDO2,EMAIL_ALTA)
VALUES (6,'NIF','99988874','C','DOCENTE','DOCENTEAPELLIDO1','DOCENTEAPELLIDO2','docente@usig.com');

INSERT INTO UVIRTUAL.TBEP_USUARIOS (CODPERSONA,CODCUENTA,ROL,EMAIL,FLGLISTADISTRIBUCION,FLGEXCLUIDO,RAZON_EXCLUSION,FECHA_EXCLUSION,FLGBORRADO,FECHA_BORRADO)
SELECT
	uvpersona.CODINT AS CODPERSONA,
	'atis' AS CODCUENTA,
	1050 AS ROL,
	'atis@atis.com' AS EMAIL,
	'S' AS FLGLISTADISTRIBUCION,
	'S' AS FLGEXCLUIDO,
	'EJEMPLO' AS RAZON_EXCLUSION,
	TO_DATE('05/04/2021', 'DD/MM/YYYY') AS FECHA_EXCLUSION,
	'N' AS FLGBORRADO,
	NULL AS FECHA_BORRADO
FROM UVIRTUAL.VUJA_NET_BEP_AR_PERSONA uvpersona WHERE uvpersona.CODINT=1;

INSERT INTO UVIRTUAL.TBEP_USUARIOS (CODPERSONA,CODCUENTA,ROL,EMAIL,FLGLISTADISTRIBUCION,FLGEXCLUIDO,RAZON_EXCLUSION,FECHA_EXCLUSION,FLGBORRADO,FECHA_BORRADO)
SELECT
	uvpersona.CODINT AS CODPERSONA,
	'estudiante1' AS CODCUENTA,
	1051 AS ROL,
	'estudiante1@estudiante1.com' AS EMAIL,
	'S' AS FLGLISTADISTRIBUCION,
	'N' AS FLGEXCLUIDO,
	NULL AS RAZON_EXCLUSION,
	NULL AS FECHA_EXCLUSION,
	'N' AS FLGBORRADO,
	NULL AS FECHA_BORRADO
FROM UVIRTUAL.VUJA_NET_BEP_AR_PERSONA uvpersona WHERE uvpersona.CODINT=2;

INSERT INTO UVIRTUAL.TBEP_USUARIOS (CODPERSONA,CODCUENTA,ROL,EMAIL,FLGLISTADISTRIBUCION,FLGEXCLUIDO,RAZON_EXCLUSION,FECHA_EXCLUSION,FLGBORRADO,FECHA_BORRADO)
SELECT
	uvpersona.CODINT AS CODPERSONA,
	'usig' AS CODCUENTA,
	1052 AS ROL,
	'usig@usig.com' AS EMAIL,
	'N' AS FLGLISTADISTRIBUCION,
	'N' AS FLGEXCLUIDO,
	NULL AS RAZON_EXCLUSION,
	NULL AS FECHA_EXCLUSION,
	'S' AS FLGBORRADO,
	TO_DATE('05/04/2021', 'DD/MM/YYYY') AS FECHA_BORRADO
FROM UVIRTUAL.VUJA_NET_BEP_AR_PERSONA uvpersona WHERE uvpersona.CODINT=3;

INSERT INTO UVIRTUAL.TBEP_USUARIOS (CODPERSONA,CODCUENTA,ROL,EMAIL,FLGLISTADISTRIBUCION,FLGEXCLUIDO,RAZON_EXCLUSION,FECHA_EXCLUSION,FLGBORRADO,FECHA_BORRADO)
SELECT
	uvpersona.CODINT AS CODPERSONA,
	'ejemplo' AS CODCUENTA,
	1052 AS ROL,
	'evaluador1@usig.com' AS EMAIL,
	'N' AS FLGLISTADISTRIBUCION,
	'N' AS FLGEXCLUIDO,
	NULL AS RAZON_EXCLUSION,
	NULL AS FECHA_EXCLUSION,
	'N' AS FLGBORRADO,
	NULL AS FECHA_BORRADO
FROM UVIRTUAL.VUJA_NET_BEP_AR_PERSONA uvpersona WHERE uvpersona.CODINT=4;

INSERT INTO UVIRTUAL.TBEP_USUARIOS (CODPERSONA,CODCUENTA,ROL,EMAIL,FLGLISTADISTRIBUCION,FLGEXCLUIDO,RAZON_EXCLUSION,FECHA_EXCLUSION,FLGBORRADO,FECHA_BORRADO)
SELECT
	uvpersona.CODINT AS CODPERSONA,
	'prueba' AS CODCUENTA,
	1052 AS ROL,
	'evaluador2@usig.com' AS EMAIL,
	'N' AS FLGLISTADISTRIBUCION,
	'N' AS FLGEXCLUIDO,
	NULL AS RAZON_EXCLUSION,
	NULL AS FECHA_EXCLUSION,
	'N' AS FLGBORRADO,
	NULL AS FECHA_BORRADO
FROM UVIRTUAL.VUJA_NET_BEP_AR_PERSONA uvpersona WHERE uvpersona.CODINT=5;

INSERT INTO UVIRTUAL.TBEP_USUARIOS (CODPERSONA,CODCUENTA,ROL,EMAIL,FLGLISTADISTRIBUCION,FLGEXCLUIDO,RAZON_EXCLUSION,FECHA_EXCLUSION,FLGBORRADO,FECHA_BORRADO)
SELECT
	uvpersona.CODINT AS CODPERSONA,
	'docente' AS CODCUENTA,
	1052 AS ROL,
	'docente@usig.com' AS EMAIL,
	'N' AS FLGLISTADISTRIBUCION,
	'N' AS FLGEXCLUIDO,
	NULL AS RAZON_EXCLUSION,
	NULL AS FECHA_EXCLUSION,
	'N' AS FLGBORRADO,
	NULL AS FECHA_BORRADO
FROM UVIRTUAL.VUJA_NET_BEP_AR_PERSONA uvpersona WHERE uvpersona.CODINT=6;