INSERT INTO TBEP_USUARIOS (CODNUM,ADM_USU_IDENTIFICADOR,ROL,FLGLISTADISTRIBUCION,FLGEXCLUIDO,RAZON_EXCLUSION,FECHA_EXCLUSION,FLGBORRADO,FECHA_BORRADO)
VALUES (1,'atis',1050,'S','S','EJEMPLO',TO_DATE('05/04/2021', 'DD/MM/YYYY'),'N',NULL);

INSERT INTO TBEP_USUARIOS (CODNUM,ADM_USU_IDENTIFICADOR,ROL,FLGLISTADISTRIBUCION,FLGEXCLUIDO,RAZON_EXCLUSION,FECHA_EXCLUSION,FLGBORRADO,FECHA_BORRADO)
VALUES (2,'estudiante1',1051,'S','N','EJEMPLO',NULL,'S',TO_DATE('05/04/2021', 'DD/MM/YYYY'));

INSERT INTO TBEP_USUARIOS (CODNUM,ADM_USU_IDENTIFICADOR,ROL,FLGLISTADISTRIBUCION,FLGEXCLUIDO,RAZON_EXCLUSION,FECHA_EXCLUSION,FLGBORRADO,FECHA_BORRADO)
VALUES (3,'usig',1052,'N','N','EJEMPLO',NULL,'N',NULL);