INSERT INTO TBEP_USUARIOS (CODNUM,ADM_USU_CODNUM,UJAENDNI,NUMDOCUMENTO,TIPO_DOCUMENTO,NOMBRE,APELLIDO1,APELLIDO2,SEXO,EMAIL,ROL,FLGLISTADISTRIBUCION,FLGEXCLUIDO,RAZON_EXCLUSION,FECHA_EXCLUSION,FLGBORRADO,FECHA_BORRADO)
VALUES (1,1,'12345678A','98765432G','DNI','EJEMPLO1','EJEMPLO_APELLIDO11','EJEMPLO_APELLIDO21','V','EJEMPLO1@EJEMPLO1.COM',1050,'S','S','EJEMPLO',TO_DATE('05/04/2021', 'DD/MM/YYYY'),'N',NULL);

INSERT INTO TBEP_USUARIOS (CODNUM,ADM_USU_CODNUM,UJAENDNI,NUMDOCUMENTO,TIPO_DOCUMENTO,NOMBRE,APELLIDO1,APELLIDO2,SEXO,EMAIL,ROL,FLGLISTADISTRIBUCION,FLGEXCLUIDO,RAZON_EXCLUSION,FECHA_EXCLUSION,FLGBORRADO,FECHA_BORRADO)
VALUES (2,2,'12345678B','98765432F','DNI','EJEMPLO2','EJEMPLO_APELLIDO12','EJEMPLO_APELLIDO22','V','EJEMPLO2@EJEMPLO1.COM',1050,'S','S','EJEMPLO',TO_DATE('05/04/2021', 'DD/MM/YYYY'),'N',NULL);

INSERT INTO TBEP_USUARIOS (CODNUM,ADM_USU_CODNUM,UJAENDNI,NUMDOCUMENTO,TIPO_DOCUMENTO,NOMBRE,APELLIDO1,APELLIDO2,SEXO,EMAIL,ROL,FLGLISTADISTRIBUCION,FLGEXCLUIDO,RAZON_EXCLUSION,FECHA_EXCLUSION,FLGBORRADO,FECHA_BORRADO)
VALUES (3,3,'12345678C','98765432E','DNI','EJEMPLO3','EJEMPLO_APELLIDO13','EJEMPLO_APELLIDO23','V','EJEMPLO3@EJEMPLO1.COM',1050,'N','N','EJEMPLO',NULL,'N',NULL);

INSERT INTO TBEP_USUARIOS (CODNUM,ADM_USU_CODNUM,UJAENDNI,NUMDOCUMENTO,TIPO_DOCUMENTO,NOMBRE,APELLIDO1,APELLIDO2,SEXO,EMAIL,ROL,FLGLISTADISTRIBUCION,FLGEXCLUIDO,RAZON_EXCLUSION,FECHA_EXCLUSION,FLGBORRADO,FECHA_BORRADO)
VALUES (4,4,'12345678D','98765432D','DNI','EJEMPLO4','EJEMPLO_APELLIDO14','EJEMPLO_APELLIDO24','M','EJEMPLO4@EJEMPLO1.COM',1050,'N','N','EJEMPLO',NULL,'N',NULL);

INSERT INTO TBEP_USUARIOS (CODNUM,ADM_USU_CODNUM,UJAENDNI,NUMDOCUMENTO,TIPO_DOCUMENTO,NOMBRE,APELLIDO1,APELLIDO2,SEXO,EMAIL,ROL,FLGLISTADISTRIBUCION,FLGEXCLUIDO,RAZON_EXCLUSION,FECHA_EXCLUSION,FLGBORRADO,FECHA_BORRADO)
VALUES (5,5,'12345678E','98765432C','DNI','EJEMPLO5','EJEMPLO_APELLIDO15','EJEMPLO_APELLIDO25','M','EJEMPLO5@EJEMPLO1.COM',1050,'N','N','EJEMPLO',NULL,'S',TO_DATE('05/04/2021', 'DD/MM/YYYY'));

INSERT INTO TBEP_USUARIOS (CODNUM,ADM_USU_CODNUM,UJAENDNI,NUMDOCUMENTO,TIPO_DOCUMENTO,NOMBRE,APELLIDO1,APELLIDO2,SEXO,EMAIL,ROL,FLGLISTADISTRIBUCION,FLGEXCLUIDO,RAZON_EXCLUSION,FECHA_EXCLUSION,FLGBORRADO,FECHA_BORRADO)
VALUES (6,6,'12345678F','98765432B','DNI','EJEMPLO6','EJEMPLO_APELLIDO16','EJEMPLO_APELLIDO26','M','EJEMPLO6@EJEMPLO1.COM',1050,'N','N','EJEMPLO',NULL,'S',TO_DATE('05/04/2021', 'DD/MM/YYYY'));

INSERT INTO TBEP_USUARIOS (CODNUM,ADM_USU_CODNUM,UJAENDNI,NUMDOCUMENTO,TIPO_DOCUMENTO,NOMBRE,APELLIDO1,APELLIDO2,SEXO,EMAIL,ROL,FLGLISTADISTRIBUCION,FLGEXCLUIDO,RAZON_EXCLUSION,FECHA_EXCLUSION,FLGBORRADO,FECHA_BORRADO)
VALUES (7,7,'12345678G','98765432A','DNI','EJEMPLO7','EJEMPLO_APELLIDO17','EJEMPLO_APELLIDO27','M','EJEMPLO7@EJEMPLO1.COM',1050,'N','N','EJEMPLO',NULL,'S',TO_DATE('05/04/2021', 'DD/MM/YYYY'));