INSERT INTO ARCOS.V_PERSONA_INTRANET (CODINT, UJAENDNI, NUMDOCUMENTO, STRTIPODOCUMENTO, STRNOMBRE, STRAPELLIDO1, STRAPELLIDO2, SEXO, COD_PERSONA_AC, COD_PERSONA_RH, BLNMANUAL) 
Values (3, '12345678', '98765432A', 'DNI', 'ATIS', 'Usuario de', 'pruebas', 'V', 3, 3, 'S');

INSERT INTO ARCOS.V_CUENTAS_INTRANET (IDCUENTA, IDIDENTIFICADOR, STRDN, CODINT, IDDOMINIO, BLNBLOQUEADA, BLNCTAGGL, BLNCTAGGLSUSP, BLNINSTITUCIONAL, STRDESCRIPCION, STRCORREORUTA)
Values (3, 'atis', 'uid=atis,cn=users,dc=ujaen,dc=es', 3, 'ujaen.es',  'N', 'N', 'N', 'N', 'Usuario de pruebas, ATIS', 'atis@xxx');

INSERT INTO ARCOS.V_PERSONA_INTRANET (CODINT, UJAENDNI, NUMDOCUMENTO, STRTIPODOCUMENTO, STRNOMBRE, STRAPELLIDO1, STRAPELLIDO2, SEXO, COD_PERSONA_AC, COD_PERSONA_RH, BLNMANUAL) 
Values (4, '87654321', '23456789A', 'DNI', 'EJEMPLO', 'Usuario de', 'pruebas', 'V', 4, 4, 'S');

INSERT INTO ARCOS.V_CUENTAS_INTRANET (IDCUENTA, IDIDENTIFICADOR, STRDN, CODINT, IDDOMINIO, BLNBLOQUEADA, BLNCTAGGL, BLNCTAGGLSUSP, BLNINSTITUCIONAL, STRDESCRIPCION, STRCORREORUTA)
Values (4, 'ejemplo', 'uid=atis,cn=users,dc=ujaen,dc=es', 4, 'ujaen.es',  'N', 'N', 'N', 'N', 'Usuario de pruebas, EJEMPLO', 'ejemplo@xxx');

INSERT INTO ARCOS.V_PERSONA_INTRANET (CODINT, UJAENDNI, NUMDOCUMENTO, STRTIPODOCUMENTO, STRNOMBRE, STRAPELLIDO1, STRAPELLIDO2, SEXO, COD_PERSONA_AC, COD_PERSONA_RH, BLNMANUAL) 
Values (5, '76543219', '123987456C', 'DNI', 'PRUEBA', 'Usuario de', 'pruebas', 'V', 5, 5, 'S');

INSERT INTO ARCOS.V_CUENTAS_INTRANET (IDCUENTA, IDIDENTIFICADOR, STRDN, CODINT, IDDOMINIO, BLNBLOQUEADA, BLNCTAGGL, BLNCTAGGLSUSP, BLNINSTITUCIONAL, STRDESCRIPCION, STRCORREORUTA)
Values (5, 'prueba', 'uid=atis,cn=users,dc=ujaen,dc=es', 5, 'ujaen.es',  'N', 'N', 'N', 'N', 'Usuario de pruebas, PRUEBA', 'prueba@xxx');