INSERT INTO ARCOS.V_PERSONA_INTRANET (CODINT, UJAENDNI, NUMDOCUMENTO, STRTIPODOCUMENTO, STRNOMBRE, STRAPELLIDO1, STRAPELLIDO2, SEXO, COD_PERSONA_AC, COD_PERSONA_RH, BLNMANUAL) 
Values (3, '12345678', '98765432A', 'DNI', 'ATIS', 'Usuario de', 'pruebas', 'V', 3, 3, 'S');

INSERT INTO ARCOS.V_CUENTAS_INTRANET (IDCUENTA, IDIDENTIFICADOR, STRDN, CODINT, IDDOMINIO, BLNBLOQUEADA, BLNCTAGGL, BLNCTAGGLSUSP, BLNINSTITUCIONAL, STRDESCRIPCION, STRCORREORUTA)
Values (3, 'atis', 'uid=atis,cn=users,dc=ujaen,dc=es', 3, 'ujaen.es',  'N', 'N', 'N', 'N', 'Usuario de pruebas, ATIS', 'atis@xxx');