INSERT INTO VUJA_NET_BEP_AR_PERSONA (CODINT,STRTIPODOCUMENTO,IDNIF,LETRANIF,STRNOMBRE,STRAPELLIDO1,STRAPELLIDO2,EMAIL_ALTA)
VALUES (1,'DNI','12345678','A','USIG','USIGAPELLIDO1','USIGAPELLIDO2','usig@usig.com');
INSERT INTO VUJA_NET_BEP_AR_PERSONA (CODINT,STRTIPODOCUMENTO,IDNIF,LETRANIF,STRNOMBRE,STRAPELLIDO1,STRAPELLIDO2,EMAIL_ALTA)
VALUES (3,'DNI','12345678','P','Personal1','Personal1APELLIDO1','Personal1APELLIDO2','Personal1@Personal1.com');
INSERT INTO VUJA_NET_BEP_AR_PERSONA (CODINT,STRTIPODOCUMENTO,IDNIF,LETRANIF,STRNOMBRE,STRAPELLIDO1,STRAPELLIDO2,EMAIL_ALTA)
VALUES (4,'DNI','22345678','P','Personal2','Personal2APELLIDO1','Personal2APELLIDO2','Personal2@Personal1.com');
INSERT INTO VUJA_NET_BEP_AR_PERSONA (CODINT,STRTIPODOCUMENTO,IDNIF,LETRANIF,STRNOMBRE,STRAPELLIDO1,STRAPELLIDO2,EMAIL_ALTA)
VALUES (5,'DNI','32345678','P','Personal3','Personal3APELLIDO1','Personal3APELLIDO2','Personal3@Personal1.com');
INSERT INTO VUJA_NET_BEP_AR_PERSONA (CODINT,STRTIPODOCUMENTO,IDNIF,LETRANIF,STRNOMBRE,STRAPELLIDO1,STRAPELLIDO2,EMAIL_ALTA)
VALUES (6,'DNI','42345678','P','Personal4','Personal4APELLIDO1','Personal4APELLIDO2','Personal4@Personal1.com');
INSERT INTO VUJA_NET_BEP_AR_PERSONA (CODINT,STRTIPODOCUMENTO,IDNIF,LETRANIF,STRNOMBRE,STRAPELLIDO1,STRAPELLIDO2,EMAIL_ALTA)
VALUES (7,'DNI','52345678','P','Personal5','Personal5APELLIDO1','Personal5APELLIDO2','Personal5@Personal1.com');


INSERT INTO VUJA_NET_BEP_AR_PERSONA (CODINT,STRTIPODOCUMENTO,IDNIF,LETRANIF,STRNOMBRE,STRAPELLIDO1,STRAPELLIDO2,EMAIL_ALTA)
VALUES (8,'DNI','12345678','B','Comision1','Comision1APELLIDO1','Comision1APELLIDO2','Comision1@Comision1.com');
INSERT INTO VUJA_NET_BEP_AR_PERSONA (CODINT,STRTIPODOCUMENTO,IDNIF,LETRANIF,STRNOMBRE,STRAPELLIDO1,STRAPELLIDO2,EMAIL_ALTA)
VALUES (9,'DNI','22345678','B','Comision2','Comision2APELLIDO1','Comision2APELLIDO2','Comision2@Comision1.com');
INSERT INTO VUJA_NET_BEP_AR_PERSONA (CODINT,STRTIPODOCUMENTO,IDNIF,LETRANIF,STRNOMBRE,STRAPELLIDO1,STRAPELLIDO2,EMAIL_ALTA)
VALUES (10,'DNI','32345678','B','Comision3','Comision3APELLIDO1','Comision3APELLIDO2','Comision3@Comision1.com');
INSERT INTO VUJA_NET_BEP_AR_PERSONA (CODINT,STRTIPODOCUMENTO,IDNIF,LETRANIF,STRNOMBRE,STRAPELLIDO1,STRAPELLIDO2,EMAIL_ALTA)
VALUES (11,'DNI','42345678','B','Comision4','Comision4APELLIDO1','Comision4APELLIDO2','Comision4@Comision1.com');
INSERT INTO VUJA_NET_BEP_AR_PERSONA (CODINT,STRTIPODOCUMENTO,IDNIF,LETRANIF,STRNOMBRE,STRAPELLIDO1,STRAPELLIDO2,EMAIL_ALTA)
VALUES (12,'DNI','52345678','B','Comision5','Comision5APELLIDO1','Comision5APELLIDO2','Comision5@Comision1.com');


INSERT INTO VUJA_NET_BEP_AR_PERSONA (CODINT,STRTIPODOCUMENTO,IDNIF,LETRANIF,STRNOMBRE,STRAPELLIDO1,STRAPELLIDO2,EMAIL_ALTA)
VALUES (13,'DNI','52345678','C','Candidato1','Candidato1APELLIDO1','Candidato1APELLIDO2','Candidato1@Comision1.com');
INSERT INTO VUJA_NET_BEP_AR_PERSONA (CODINT,STRTIPODOCUMENTO,IDNIF,LETRANIF,STRNOMBRE,STRAPELLIDO1,STRAPELLIDO2,EMAIL_ALTA)
VALUES (14,'DNI','52345678','C','Candidato2','Candidato2APELLIDO1','Candidato2APELLIDO2','Candidato2@Comision1.com');
INSERT INTO VUJA_NET_BEP_AR_PERSONA (CODINT,STRTIPODOCUMENTO,IDNIF,LETRANIF,STRNOMBRE,STRAPELLIDO1,STRAPELLIDO2,EMAIL_ALTA)
VALUES (15,'DNI','52345678','C','Candidato3','Candidato3APELLIDO1','Candidato3APELLIDO2','Candidato3@Comision1.com');
INSERT INTO VUJA_NET_BEP_AR_PERSONA (CODINT,STRTIPODOCUMENTO,IDNIF,LETRANIF,STRNOMBRE,STRAPELLIDO1,STRAPELLIDO2,EMAIL_ALTA)
VALUES (16,'DNI','52345678','C','Candidato4','Candidato4APELLIDO1','Candidato4APELLIDO2','Candidato4@Comision1.com');
INSERT INTO VUJA_NET_BEP_AR_PERSONA (CODINT,STRTIPODOCUMENTO,IDNIF,LETRANIF,STRNOMBRE,STRAPELLIDO1,STRAPELLIDO2,EMAIL_ALTA)
VALUES (17,'DNI','52345678','C','Candidato5','Candidato5APELLIDO1','Candidato5APELLIDO2','Candidato5@Comision1.com');
INSERT INTO VUJA_NET_BEP_AR_PERSONA (CODINT,STRTIPODOCUMENTO,IDNIF,LETRANIF,STRNOMBRE,STRAPELLIDO1,STRAPELLIDO2,EMAIL_ALTA)
VALUES (18,'DNI','52345678','C','Candidato6','Candidato6APELLIDO1','Candidato6APELLIDO2','Candidato6@Comision1.com');
INSERT INTO VUJA_NET_BEP_AR_PERSONA (CODINT,STRTIPODOCUMENTO,IDNIF,LETRANIF,STRNOMBRE,STRAPELLIDO1,STRAPELLIDO2,EMAIL_ALTA)
VALUES (19,'DNI','52345678','C','Candidato7','Candidato7APELLIDO1','Candidato7APELLIDO2','Candidato7@Comision1.com');
INSERT INTO VUJA_NET_BEP_AR_PERSONA (CODINT,STRTIPODOCUMENTO,IDNIF,LETRANIF,STRNOMBRE,STRAPELLIDO1,STRAPELLIDO2,EMAIL_ALTA)
VALUES (20,'DNI','52345678','C','Candidato8','Candidato8APELLIDO1','Candidato8APELLIDO2','Candidato8@Comision1.com');
INSERT INTO VUJA_NET_BEP_AR_PERSONA (CODINT,STRTIPODOCUMENTO,IDNIF,LETRANIF,STRNOMBRE,STRAPELLIDO1,STRAPELLIDO2,EMAIL_ALTA)
VALUES (21,'DNI','52345678','C','Candidato9','Candidato9APELLIDO1','Candidato9APELLIDO2','Candidato9@Comision1.com');
INSERT INTO VUJA_NET_BEP_AR_PERSONA (CODINT,STRTIPODOCUMENTO,IDNIF,LETRANIF,STRNOMBRE,STRAPELLIDO1,STRAPELLIDO2,EMAIL_ALTA)
VALUES (22,'DNI','52345678','C','Candidato10','Candidato10APELLIDO1','Candidato10APELLIDO2','Candidato10@Comision1.com');

INSERT INTO VUJA_NET_BEP_AR_PERSONA (CODINT,STRTIPODOCUMENTO,IDNIF,LETRANIF,STRNOMBRE,STRAPELLIDO1,STRAPELLIDO2,EMAIL_ALTA)
VALUES (23,'DNI','52345678','C','Pruebas1','Pruebas1APELLIDO1','Pruebas1APELLIDO2','Pruebas1@Pruebas1.com');
INSERT INTO VUJA_NET_BEP_AR_PERSONA (CODINT,STRTIPODOCUMENTO,IDNIF,LETRANIF,STRNOMBRE,STRAPELLIDO1,STRAPELLIDO2,EMAIL_ALTA)
VALUES (24,'DNI','52345678','C','Pruebas2','Pruebas2APELLIDO1','Pruebas2APELLIDO2','Pruebas1@Pruebas1.com');

/*NO TOCAR NI ASOCIAR*/
INSERT INTO VUJA_NET_BEP_AR_PERSONA (CODINT,STRTIPODOCUMENTO,IDNIF,LETRANIF,STRNOMBRE,STRAPELLIDO1,STRAPELLIDO2,EMAIL_ALTA)
VALUES (100,'NIF','11111111','C','TEST','TESTAPELLIDO1','TESTAPELLIDO2','test@test.com');
/**/

INSERT INTO UVIRTUAL.TBEP_USUARIOS (CODPERSONA,CODCUENTA,ROL,EMAIL,FLGLISTADISTRIBUCION,FLGEXCLUIDO,RAZON_EXCLUSION,FECHA_EXCLUSION,FLGBORRADO,FECHA_BORRADO)
SELECT
	uvpersona.CODINT AS CODPERSONA,
	'usig' AS CODCUENTA,
	1050 AS ROL,
	'usig@usig.com' AS EMAIL,
	'S' AS FLGLISTADISTRIBUCION,
	'S' AS FLGEXCLUIDO,
	'EJEMPLO' AS RAZON_EXCLUSION,
	TO_DATE('05/04/2021', 'DD/MM/YYYY') AS FECHA_EXCLUSION,
	'N' AS FLGBORRADO,
	NULL AS FECHA_BORRADO
FROM UVIRTUAL.VUJA_NET_BEP_AR_PERSONA uvpersona WHERE uvpersona.CODINT=1;

INSERT INTO UVIRTUAL.TBEP_USUARIOS (CODPERSONA,CODCUENTA,ROL,EMAIL,DIRECCION,CODIGOPOSTAL,LOCALIDAD,PROVINCIA,MOVIL,TELEFONO,NACIONALIDAD,SEXO,FLGLISTADISTRIBUCION,FLGEXCLUIDO,RAZON_EXCLUSION,FECHA_EXCLUSION,FLGBORRADO,FECHA_BORRADO)
SELECT
	uvpersona.CODINT AS CODPERSONA,
	'personal1' AS CODCUENTA,
	1050 AS ROL,
	'Personal1@Personal1.com' AS EMAIL,
	'Calle Ejemplo Personal1' AS DIRECCION,
	'11111' AS CODIGOPOSTAL,
	'GRANADA' AS LOCALIDAD,
	'GRANADA' AS PROVINCIA,
	'666777888' AS MOVIL,
	'999888777' AS TELEFONO,
	'ESPAÑOL' AS NACIONALIDAD,
	'M' AS SEXO,
	'S' AS FLGLISTADISTRIBUCION,
	'S' AS FLGEXCLUIDO,
	'Personal1 EJEMPLO' AS RAZON_EXCLUSION,
	TO_DATE('05/04/2021', 'DD/MM/YYYY') AS FECHA_EXCLUSION,
	'N' AS FLGBORRADO,
	NULL AS FECHA_BORRADO
FROM UVIRTUAL.VUJA_NET_BEP_AR_PERSONA uvpersona WHERE uvpersona.CODINT=3;

INSERT INTO UVIRTUAL.TBEP_USUARIOS (CODPERSONA,CODCUENTA,ROL,EMAIL,DIRECCION,CODIGOPOSTAL,LOCALIDAD,PROVINCIA,MOVIL,TELEFONO,NACIONALIDAD,SEXO,FLGLISTADISTRIBUCION,FLGEXCLUIDO,RAZON_EXCLUSION,FECHA_EXCLUSION,FLGBORRADO,FECHA_BORRADO)
SELECT
	uvpersona.CODINT AS CODPERSONA,
	'personal2' AS CODCUENTA,
	1050 AS ROL,
	'Personal2@Personal2.com' AS EMAIL,
	'Calle Ejemplo Personal2' AS DIRECCION,
	'22222' AS CODIGOPOSTAL,
	'GRANADA' AS LOCALIDAD,
	'GRANADA' AS PROVINCIA,
	'666777888' AS MOVIL,
	'999888777' AS TELEFONO,
	'ESPAÑOL' AS NACIONALIDAD,
	'F' AS SEXO,
	'S' AS FLGLISTADISTRIBUCION,
	'S' AS FLGEXCLUIDO,
	'Personal2 EJEMPLO' AS RAZON_EXCLUSION,
	TO_DATE('15/04/2021', 'DD/MM/YYYY') AS FECHA_EXCLUSION,
	'N' AS FLGBORRADO,
	NULL AS FECHA_BORRADO
FROM UVIRTUAL.VUJA_NET_BEP_AR_PERSONA uvpersona WHERE uvpersona.CODINT=4;

INSERT INTO UVIRTUAL.TBEP_USUARIOS (CODPERSONA,CODCUENTA,ROL,EMAIL,DIRECCION,CODIGOPOSTAL,LOCALIDAD,PROVINCIA,MOVIL,TELEFONO,NACIONALIDAD,SEXO,FLGLISTADISTRIBUCION,FLGEXCLUIDO,RAZON_EXCLUSION,FECHA_EXCLUSION,FLGBORRADO,FECHA_BORRADO)
SELECT
	uvpersona.CODINT AS CODPERSONA,
	'personal3' AS CODCUENTA,
	1050 AS ROL,
	'Personal3@Personal3.com' AS EMAIL,
	'Calle Ejemplo Personal3' AS DIRECCION,
	'33333' AS CODIGOPOSTAL,
	'GRANADA' AS LOCALIDAD,
	'GRANADA' AS PROVINCIA,
	'666777888' AS MOVIL,
	'999888777' AS TELEFONO,
	'ESPAÑOL' AS NACIONALIDAD,
	'F' AS SEXO,
	'S' AS FLGLISTADISTRIBUCION,
	'N' AS FLGEXCLUIDO,
	NULL AS RAZON_EXCLUSION,
	NULL AS FECHA_EXCLUSION,
	'N' AS FLGBORRADO,
	NULL AS FECHA_BORRADO
FROM UVIRTUAL.VUJA_NET_BEP_AR_PERSONA uvpersona WHERE uvpersona.CODINT=5;

INSERT INTO UVIRTUAL.TBEP_USUARIOS (CODPERSONA,CODCUENTA,ROL,EMAIL,DIRECCION,CODIGOPOSTAL,LOCALIDAD,PROVINCIA,MOVIL,TELEFONO,NACIONALIDAD,SEXO,FLGLISTADISTRIBUCION,FLGEXCLUIDO,RAZON_EXCLUSION,FECHA_EXCLUSION,FLGBORRADO,FECHA_BORRADO)
SELECT
	uvpersona.CODINT AS CODPERSONA,
	'personal4' AS CODCUENTA,
	1050 AS ROL,
	'Personal4@Personal4.com' AS EMAIL,
	'Calle Ejemplo Personal4' AS DIRECCION,
	'44444' AS CODIGOPOSTAL,
	'GRANADA' AS LOCALIDAD,
	'GRANADA' AS PROVINCIA,
	'666777888' AS MOVIL,
	'999888777' AS TELEFONO,
	'ESPAÑOL' AS NACIONALIDAD,
	'M' AS SEXO,
	'S' AS FLGLISTADISTRIBUCION,
	'N' AS FLGEXCLUIDO,
	NULL AS RAZON_EXCLUSION,
	NULL AS FECHA_EXCLUSION,
	'N' AS FLGBORRADO,
	NULL AS FECHA_BORRADO
FROM UVIRTUAL.VUJA_NET_BEP_AR_PERSONA uvpersona WHERE uvpersona.CODINT=6;

INSERT INTO UVIRTUAL.TBEP_USUARIOS (CODPERSONA,CODCUENTA,ROL,EMAIL,DIRECCION,CODIGOPOSTAL,LOCALIDAD,PROVINCIA,MOVIL,TELEFONO,NACIONALIDAD,SEXO,FLGLISTADISTRIBUCION,FLGEXCLUIDO,RAZON_EXCLUSION,FECHA_EXCLUSION,FLGBORRADO,FECHA_BORRADO)
SELECT
	uvpersona.CODINT AS CODPERSONA,
	'personal5' AS CODCUENTA,
	1050 AS ROL,
	'Personal5@Personal5.com' AS EMAIL,
	'Calle Ejemplo Personal5' AS DIRECCION,
	'55555' AS CODIGOPOSTAL,
	'GRANADA' AS LOCALIDAD,
	'GRANADA' AS PROVINCIA,
	'666777888' AS MOVIL,
	'999888777' AS TELEFONO,
	'ESPAÑOL' AS NACIONALIDAD,
	'M' AS SEXO,
	'S' AS FLGLISTADISTRIBUCION,
	'N' AS FLGEXCLUIDO,
	NULL AS RAZON_EXCLUSION,
	NULL AS FECHA_EXCLUSION,
	'N' AS FLGBORRADO,
	NULL AS FECHA_BORRADO
FROM UVIRTUAL.VUJA_NET_BEP_AR_PERSONA uvpersona WHERE uvpersona.CODINT=7;



INSERT INTO UVIRTUAL.TBEP_USUARIOS (CODPERSONA,CODCUENTA,ROL,EMAIL,DIRECCION,CODIGOPOSTAL,LOCALIDAD,PROVINCIA,MOVIL,TELEFONO,NACIONALIDAD,SEXO,FLGLISTADISTRIBUCION,FLGEXCLUIDO,RAZON_EXCLUSION,FECHA_EXCLUSION,FLGBORRADO,FECHA_BORRADO)
SELECT
	uvpersona.CODINT AS CODPERSONA,
	'comision1' AS CODCUENTA,
	1051 AS ROL,
	'Comision1@Comision1.com' AS EMAIL,
	'Calle Ejemplo Comision1' AS DIRECCION,
	'66666' AS CODIGOPOSTAL,
	'GRANADA' AS LOCALIDAD,
	'GRANADA' AS PROVINCIA,
	'666777888' AS MOVIL,
	'999888777' AS TELEFONO,
	'ESPAÑOL' AS NACIONALIDAD,
	'M' AS SEXO,
	'S' AS FLGLISTADISTRIBUCION,
	'N' AS FLGEXCLUIDO,
	NULL AS RAZON_EXCLUSION,
	NULL AS FECHA_EXCLUSION,
	'N' AS FLGBORRADO,
	NULL AS FECHA_BORRADO
FROM UVIRTUAL.VUJA_NET_BEP_AR_PERSONA uvpersona WHERE uvpersona.CODINT=8;

INSERT INTO UVIRTUAL.TBEP_USUARIOS (CODPERSONA,CODCUENTA,ROL,EMAIL,DIRECCION,CODIGOPOSTAL,LOCALIDAD,PROVINCIA,MOVIL,TELEFONO,NACIONALIDAD,SEXO,FLGLISTADISTRIBUCION,FLGEXCLUIDO,RAZON_EXCLUSION,FECHA_EXCLUSION,FLGBORRADO,FECHA_BORRADO)
SELECT
	uvpersona.CODINT AS CODPERSONA,
	'comision2' AS CODCUENTA,
	1051 AS ROL,
	'Comision2@Comision2.com' AS EMAIL,
	'Calle Ejemplo Comision2' AS DIRECCION,
	'77777' AS CODIGOPOSTAL,
	'GRANADA' AS LOCALIDAD,
	'GRANADA' AS PROVINCIA,
	'666777888' AS MOVIL,
	'999888777' AS TELEFONO,
	'ESPAÑOL' AS NACIONALIDAD,
	'M' AS SEXO,
	'S' AS FLGLISTADISTRIBUCION,
	'N' AS FLGEXCLUIDO,
	NULL AS RAZON_EXCLUSION,
	NULL AS FECHA_EXCLUSION,
	'N' AS FLGBORRADO,
	NULL AS FECHA_BORRADO
FROM UVIRTUAL.VUJA_NET_BEP_AR_PERSONA uvpersona WHERE uvpersona.CODINT=9;

INSERT INTO UVIRTUAL.TBEP_USUARIOS (CODPERSONA,CODCUENTA,ROL,EMAIL,DIRECCION,CODIGOPOSTAL,LOCALIDAD,PROVINCIA,MOVIL,TELEFONO,NACIONALIDAD,SEXO,FLGLISTADISTRIBUCION,FLGEXCLUIDO,RAZON_EXCLUSION,FECHA_EXCLUSION,FLGBORRADO,FECHA_BORRADO)
SELECT
	uvpersona.CODINT AS CODPERSONA,
	'comision3' AS CODCUENTA,
	1051 AS ROL,
	'Comision3@Comision3.com' AS EMAIL,
	'Calle Ejemplo Comision3' AS DIRECCION,
	'88888' AS CODIGOPOSTAL,
	'GRANADA' AS LOCALIDAD,
	'GRANADA' AS PROVINCIA,
	'666777888' AS MOVIL,
	'999888777' AS TELEFONO,
	'ESPAÑOL' AS NACIONALIDAD,
	'F' AS SEXO,
	'S' AS FLGLISTADISTRIBUCION,
	'S' AS FLGEXCLUIDO,
	'Comision3 EJEMPLO' AS RAZON_EXCLUSION,
	TO_DATE('15/04/2021', 'DD/MM/YYYY') AS FECHA_EXCLUSION,
	'N' AS FLGBORRADO,
	NULL AS FECHA_BORRADO
FROM UVIRTUAL.VUJA_NET_BEP_AR_PERSONA uvpersona WHERE uvpersona.CODINT=10;

INSERT INTO UVIRTUAL.TBEP_USUARIOS (CODPERSONA,CODCUENTA,ROL,EMAIL,DIRECCION,CODIGOPOSTAL,LOCALIDAD,PROVINCIA,MOVIL,TELEFONO,NACIONALIDAD,SEXO,FLGLISTADISTRIBUCION,FLGEXCLUIDO,RAZON_EXCLUSION,FECHA_EXCLUSION,FLGBORRADO,FECHA_BORRADO)
SELECT
	uvpersona.CODINT AS CODPERSONA,
	'comision4' AS CODCUENTA,
	1051 AS ROL,
	'Comision4@Comision4.com' AS EMAIL,
	'Calle Ejemplo Comision4' AS DIRECCION,
	'99999' AS CODIGOPOSTAL,
	'GRANADA' AS LOCALIDAD,
	'GRANADA' AS PROVINCIA,
	'666777888' AS MOVIL,
	'999888777' AS TELEFONO,
	'ESPAÑOL' AS NACIONALIDAD,
	'F' AS SEXO,
	'S' AS FLGLISTADISTRIBUCION,
	'N' AS FLGEXCLUIDO,
	NULL AS RAZON_EXCLUSION,
	NULL AS FECHA_EXCLUSION,
	'N' AS FLGBORRADO,
	NULL AS FECHA_BORRADO
FROM UVIRTUAL.VUJA_NET_BEP_AR_PERSONA uvpersona WHERE uvpersona.CODINT=11;

INSERT INTO UVIRTUAL.TBEP_USUARIOS (CODPERSONA,CODCUENTA,ROL,EMAIL,DIRECCION,CODIGOPOSTAL,LOCALIDAD,PROVINCIA,MOVIL,TELEFONO,NACIONALIDAD,SEXO,FLGLISTADISTRIBUCION,FLGEXCLUIDO,RAZON_EXCLUSION,FECHA_EXCLUSION,FLGBORRADO,FECHA_BORRADO)
SELECT
	uvpersona.CODINT AS CODPERSONA,
	'comision5' AS CODCUENTA,
	1051 AS ROL,
	'Comision5@Comision5.com' AS EMAIL,
	'Calle Ejemplo Comision5' AS DIRECCION,
	'10101' AS CODIGOPOSTAL,
	'GRANADA' AS LOCALIDAD,
	'GRANADA' AS PROVINCIA,
	'666777888' AS MOVIL,
	'999888777' AS TELEFONO,
	'ESPAÑOL' AS NACIONALIDAD,
	'F' AS SEXO,
	'S' AS FLGLISTADISTRIBUCION,
	'N' AS FLGEXCLUIDO,
	NULL AS RAZON_EXCLUSION,
	NULL AS FECHA_EXCLUSION,
	'N' AS FLGBORRADO,
	NULL AS FECHA_BORRADO
FROM UVIRTUAL.VUJA_NET_BEP_AR_PERSONA uvpersona WHERE uvpersona.CODINT=12;

INSERT INTO UVIRTUAL.TBEP_USUARIOS (CODPERSONA,CODCUENTA,ROL,EMAIL,DIRECCION,CODIGOPOSTAL,LOCALIDAD,PROVINCIA,MOVIL,TELEFONO,NACIONALIDAD,SEXO,FLGLISTADISTRIBUCION,FLGEXCLUIDO,RAZON_EXCLUSION,FECHA_EXCLUSION,FLGBORRADO,FECHA_BORRADO)
SELECT
	uvpersona.CODINT AS CODPERSONA,
	'candidato1' AS CODCUENTA,
	1052 AS ROL,
	'Candidato1@Candidato1.com' AS EMAIL,
	'Calle Ejemplo Candidato1' AS DIRECCION,
	'10101' AS CODIGOPOSTAL,
	'GRANADA' AS LOCALIDAD,
	'GRANADA' AS PROVINCIA,
	'666777888' AS MOVIL,
	'999888777' AS TELEFONO,
	'ESPAÑOL' AS NACIONALIDAD,
	'F' AS SEXO,
	'S' AS FLGLISTADISTRIBUCION,
	'N' AS FLGEXCLUIDO,
	NULL AS RAZON_EXCLUSION,
	NULL AS FECHA_EXCLUSION,
	'N' AS FLGBORRADO,
	NULL AS FECHA_BORRADO
FROM UVIRTUAL.VUJA_NET_BEP_AR_PERSONA uvpersona WHERE uvpersona.CODINT=13;

INSERT INTO UVIRTUAL.TBEP_USUARIOS (CODPERSONA,CODCUENTA,ROL,EMAIL,DIRECCION,CODIGOPOSTAL,LOCALIDAD,PROVINCIA,MOVIL,TELEFONO,NACIONALIDAD,SEXO,FLGLISTADISTRIBUCION,FLGEXCLUIDO,RAZON_EXCLUSION,FECHA_EXCLUSION,FLGBORRADO,FECHA_BORRADO)
SELECT
	uvpersona.CODINT AS CODPERSONA,
	'candidato2' AS CODCUENTA,
	1052 AS ROL,
	'Candidato2@Candidato2.com' AS EMAIL,
	'Calle Ejemplo Candidato2' AS DIRECCION,
	'10101' AS CODIGOPOSTAL,
	'GRANADA' AS LOCALIDAD,
	'GRANADA' AS PROVINCIA,
	'666777888' AS MOVIL,
	'999888777' AS TELEFONO,
	'ESPAÑOL' AS NACIONALIDAD,
	'F' AS SEXO,
	'S' AS FLGLISTADISTRIBUCION,
	'N' AS FLGEXCLUIDO,
	NULL AS RAZON_EXCLUSION,
	NULL AS FECHA_EXCLUSION,
	'N' AS FLGBORRADO,
	NULL AS FECHA_BORRADO
FROM UVIRTUAL.VUJA_NET_BEP_AR_PERSONA uvpersona WHERE uvpersona.CODINT=14;

INSERT INTO UVIRTUAL.TBEP_USUARIOS (CODPERSONA,CODCUENTA,ROL,EMAIL,DIRECCION,CODIGOPOSTAL,LOCALIDAD,PROVINCIA,MOVIL,TELEFONO,NACIONALIDAD,SEXO,FLGLISTADISTRIBUCION,FLGEXCLUIDO,RAZON_EXCLUSION,FECHA_EXCLUSION,FLGBORRADO,FECHA_BORRADO)
SELECT
	uvpersona.CODINT AS CODPERSONA,
	'candidato3' AS CODCUENTA,
	1052 AS ROL,
	'Candidato3@Candidato3.com' AS EMAIL,
	'Calle Ejemplo Candidato3' AS DIRECCION,
	'10101' AS CODIGOPOSTAL,
	'GRANADA' AS LOCALIDAD,
	'GRANADA' AS PROVINCIA,
	'666777888' AS MOVIL,
	'999888777' AS TELEFONO,
	'ESPAÑOL' AS NACIONALIDAD,
	'F' AS SEXO,
	'S' AS FLGLISTADISTRIBUCION,
	'N' AS FLGEXCLUIDO,
	NULL AS RAZON_EXCLUSION,
	NULL AS FECHA_EXCLUSION,
	'N' AS FLGBORRADO,
	NULL AS FECHA_BORRADO
FROM UVIRTUAL.VUJA_NET_BEP_AR_PERSONA uvpersona WHERE uvpersona.CODINT=15;

INSERT INTO UVIRTUAL.TBEP_USUARIOS (CODPERSONA,CODCUENTA,ROL,EMAIL,DIRECCION,CODIGOPOSTAL,LOCALIDAD,PROVINCIA,MOVIL,TELEFONO,NACIONALIDAD,SEXO,FLGLISTADISTRIBUCION,FLGEXCLUIDO,RAZON_EXCLUSION,FECHA_EXCLUSION,FLGBORRADO,FECHA_BORRADO)
SELECT
	uvpersona.CODINT AS CODPERSONA,
	'candidato4' AS CODCUENTA,
	1052 AS ROL,
	'Candidato4@Candidato4.com' AS EMAIL,
	'Calle Ejemplo Candidato4' AS DIRECCION,
	'10101' AS CODIGOPOSTAL,
	'GRANADA' AS LOCALIDAD,
	'GRANADA' AS PROVINCIA,
	'666777888' AS MOVIL,
	'999888777' AS TELEFONO,
	'ESPAÑOL' AS NACIONALIDAD,
	'F' AS SEXO,
	'S' AS FLGLISTADISTRIBUCION,
	'N' AS FLGEXCLUIDO,
	NULL AS RAZON_EXCLUSION,
	NULL AS FECHA_EXCLUSION,
	'S' AS FLGBORRADO,
	TO_DATE('15/04/2021', 'DD/MM/YYYY') AS FECHA_BORRADO
FROM UVIRTUAL.VUJA_NET_BEP_AR_PERSONA uvpersona WHERE uvpersona.CODINT=16;

INSERT INTO UVIRTUAL.TBEP_USUARIOS (CODPERSONA,CODCUENTA,ROL,EMAIL,DIRECCION,CODIGOPOSTAL,LOCALIDAD,PROVINCIA,MOVIL,TELEFONO,NACIONALIDAD,SEXO,FLGLISTADISTRIBUCION,FLGEXCLUIDO,RAZON_EXCLUSION,FECHA_EXCLUSION,FLGBORRADO,FECHA_BORRADO)
SELECT
	uvpersona.CODINT AS CODPERSONA,
	'candidato5' AS CODCUENTA,
	1052 AS ROL,
	'Candidato5@Candidato5.com' AS EMAIL,
	'Calle Ejemplo Candidato5' AS DIRECCION,
	'10101' AS CODIGOPOSTAL,
	'GRANADA' AS LOCALIDAD,
	'GRANADA' AS PROVINCIA,
	'666777888' AS MOVIL,
	'999888777' AS TELEFONO,
	'ESPAÑOL' AS NACIONALIDAD,
	'F' AS SEXO,
	'S' AS FLGLISTADISTRIBUCION,
	'N' AS FLGEXCLUIDO,
	NULL AS RAZON_EXCLUSION,
	NULL AS FECHA_EXCLUSION,
	'N' AS FLGBORRADO,
	NULL AS FECHA_BORRADO
FROM UVIRTUAL.VUJA_NET_BEP_AR_PERSONA uvpersona WHERE uvpersona.CODINT=17;


INSERT INTO UVIRTUAL.TBEP_USUARIOS (CODPERSONA,CODCUENTA,ROL,EMAIL,DIRECCION,CODIGOPOSTAL,LOCALIDAD,PROVINCIA,MOVIL,TELEFONO,NACIONALIDAD,SEXO,FLGLISTADISTRIBUCION,FLGEXCLUIDO,RAZON_EXCLUSION,FECHA_EXCLUSION,FLGBORRADO,FECHA_BORRADO)
SELECT
	uvpersona.CODINT AS CODPERSONA,
	'candidato6' AS CODCUENTA,
	1052 AS ROL,
	'Candidato6@Candidato6.com' AS EMAIL,
	'Calle Ejemplo Candidato6' AS DIRECCION,
	'10101' AS CODIGOPOSTAL,
	'GRANADA' AS LOCALIDAD,
	'GRANADA' AS PROVINCIA,
	'666777888' AS MOVIL,
	'999888777' AS TELEFONO,
	'ESPAÑOL' AS NACIONALIDAD,
	'F' AS SEXO,
	'S' AS FLGLISTADISTRIBUCION,
	'S' AS FLGEXCLUIDO,
	'Candidato6 EJEMPLO' AS RAZON_EXCLUSION,
	TO_DATE('15/04/2021', 'DD/MM/YYYY') AS FECHA_EXCLUSION,
	'N' AS FLGBORRADO,
	NULL AS FECHA_BORRADO
FROM UVIRTUAL.VUJA_NET_BEP_AR_PERSONA uvpersona WHERE uvpersona.CODINT=18;


INSERT INTO UVIRTUAL.TBEP_USUARIOS (CODPERSONA,CODCUENTA,ROL,EMAIL,DIRECCION,CODIGOPOSTAL,LOCALIDAD,PROVINCIA,MOVIL,TELEFONO,NACIONALIDAD,SEXO,FLGLISTADISTRIBUCION,FLGEXCLUIDO,RAZON_EXCLUSION,FECHA_EXCLUSION,FLGBORRADO,FECHA_BORRADO)
SELECT
	uvpersona.CODINT AS CODPERSONA,
	'candidato7' AS CODCUENTA,
	1052 AS ROL,
	'Candidato7@Candidato7.com' AS EMAIL,
	'Calle Ejemplo Candidato7' AS DIRECCION,
	'10101' AS CODIGOPOSTAL,
	'GRANADA' AS LOCALIDAD,
	'GRANADA' AS PROVINCIA,
	'666777888' AS MOVIL,
	'999888777' AS TELEFONO,
	'ESPAÑOL' AS NACIONALIDAD,
	'F' AS SEXO,
	'S' AS FLGLISTADISTRIBUCION,
	'S' AS FLGEXCLUIDO,
	'Candidato7 EJEMPLO' AS RAZON_EXCLUSION,
	TO_DATE('15/04/2021', 'DD/MM/YYYY') AS FECHA_EXCLUSION,
	'N' AS FLGBORRADO,
	NULL AS FECHA_BORRADO
FROM UVIRTUAL.VUJA_NET_BEP_AR_PERSONA uvpersona WHERE uvpersona.CODINT=19;

INSERT INTO UVIRTUAL.TBEP_USUARIOS (CODPERSONA,CODCUENTA,ROL,EMAIL,DIRECCION,CODIGOPOSTAL,LOCALIDAD,PROVINCIA,MOVIL,TELEFONO,NACIONALIDAD,SEXO,FLGLISTADISTRIBUCION,FLGEXCLUIDO,RAZON_EXCLUSION,FECHA_EXCLUSION,FLGBORRADO,FECHA_BORRADO)
SELECT
	uvpersona.CODINT AS CODPERSONA,
	'candidato8' AS CODCUENTA,
	1052 AS ROL,
	'Candidato8@Candidato8.com' AS EMAIL,
	'Calle Ejemplo Candidato8' AS DIRECCION,
	'10101' AS CODIGOPOSTAL,
	'GRANADA' AS LOCALIDAD,
	'GRANADA' AS PROVINCIA,
	'666777888' AS MOVIL,
	'999888777' AS TELEFONO,
	'ESPAÑOL' AS NACIONALIDAD,
	'F' AS SEXO,
	'S' AS FLGLISTADISTRIBUCION,
	'S' AS FLGEXCLUIDO,
	'Candidato8 EJEMPLO' AS RAZON_EXCLUSION,
	TO_DATE('15/04/2021', 'DD/MM/YYYY') AS FECHA_EXCLUSION,
	'N' AS FLGBORRADO,
	NULL AS FECHA_BORRADO
FROM UVIRTUAL.VUJA_NET_BEP_AR_PERSONA uvpersona WHERE uvpersona.CODINT=20;

INSERT INTO UVIRTUAL.TBEP_USUARIOS (CODPERSONA,CODCUENTA,ROL,EMAIL,DIRECCION,CODIGOPOSTAL,LOCALIDAD,PROVINCIA,MOVIL,TELEFONO,NACIONALIDAD,SEXO,FLGLISTADISTRIBUCION,FLGEXCLUIDO,RAZON_EXCLUSION,FECHA_EXCLUSION,FLGBORRADO,FECHA_BORRADO)
SELECT
	uvpersona.CODINT AS CODPERSONA,
	'candidato9' AS CODCUENTA,
	1052 AS ROL,
	'Candidato9@Candidato9.com' AS EMAIL,
	'Calle Ejemplo Candidato9' AS DIRECCION,
	'10101' AS CODIGOPOSTAL,
	'GRANADA' AS LOCALIDAD,
	'GRANADA' AS PROVINCIA,
	'666777888' AS MOVIL,
	'999888777' AS TELEFONO,
	'ESPAÑOL' AS NACIONALIDAD,
	'F' AS SEXO,
	'S' AS FLGLISTADISTRIBUCION,
	'S' AS FLGEXCLUIDO,
	'Candidato9 EJEMPLO' AS RAZON_EXCLUSION,
	TO_DATE('15/04/2021', 'DD/MM/YYYY') AS FECHA_EXCLUSION,
	'N' AS FLGBORRADO,
	NULL AS FECHA_BORRADO
FROM UVIRTUAL.VUJA_NET_BEP_AR_PERSONA uvpersona WHERE uvpersona.CODINT=21;

INSERT INTO UVIRTUAL.TBEP_USUARIOS (CODPERSONA,CODCUENTA,ROL,EMAIL,DIRECCION,CODIGOPOSTAL,LOCALIDAD,PROVINCIA,MOVIL,TELEFONO,NACIONALIDAD,SEXO,FLGLISTADISTRIBUCION,FLGEXCLUIDO,RAZON_EXCLUSION,FECHA_EXCLUSION,FLGBORRADO,FECHA_BORRADO)
SELECT
	uvpersona.CODINT AS CODPERSONA,
	'candidato10' AS CODCUENTA,
	1052 AS ROL,
	'Candidato10@Candidato10.com' AS EMAIL,
	'Calle Ejemplo Candidato10' AS DIRECCION,
	'10101' AS CODIGOPOSTAL,
	'GRANADA' AS LOCALIDAD,
	'GRANADA' AS PROVINCIA,
	'666777888' AS MOVIL,
	'999888777' AS TELEFONO,
	'ESPAÑOL' AS NACIONALIDAD,
	'F' AS SEXO,
	'S' AS FLGLISTADISTRIBUCION,
	'S' AS FLGEXCLUIDO,
	'Candidato10 EJEMPLO' AS RAZON_EXCLUSION,
	TO_DATE('15/04/2021', 'DD/MM/YYYY') AS FECHA_EXCLUSION,
	'S' AS FLGBORRADO,
	TO_DATE('15/04/2021', 'DD/MM/YYYY') AS FECHA_BORRADO
FROM UVIRTUAL.VUJA_NET_BEP_AR_PERSONA uvpersona WHERE uvpersona.CODINT=22;