-- creación registros de prueba apartados de baremación;
INSERT INTO TBEP_APARTADOSBAREMACION (CODIGO,NOMBRE)
VALUES ('1','Formacion');
INSERT INTO TBEP_APARTADOSBAREMACION (CODIGO,NOMBRE)
VALUES ('2','ACTIVIDAD DOCENTE [2]');
INSERT INTO TBEP_APARTADOSBAREMACION (CODIGO,NOMBRE)
VALUES ('3','ACTIVIDAD INVESTIGADORA');
INSERT INTO TBEP_APARTADOSBAREMACION (CODIGO,NOMBRE)
VALUES ('4','EXPERIENCIA PROFESIONAL DE LOS');
INSERT INTO TBEP_APARTADOSBAREMACION (CODIGO,NOMBRE)
VALUES ('5','Representacion, gobierno y gestion universitaria');
INSERT INTO TBEP_APARTADOSBAREMACION (CODIGO,NOMBRE)
VALUES ('6','Informe del departamento');
INSERT INTO TBEP_APARTADOSBAREMACION (CODIGO,NOMBRE)
VALUES ('7','Prueba');
INSERT INTO TBEP_APARTADOSBAREMACION (CODIGO,NOMBRE)
VALUES ('8','Prueba');
INSERT INTO TBEP_APARTADOSBAREMACION (CODIGO,NOMBRE)
VALUES ('9','Prueba');
INSERT INTO TBEP_APARTADOSBAREMACION (CODIGO,NOMBRE)
VALUES ('10','Prueba');