-- creación registros de prueba apartados de baremación;
INSERT INTO TBEP_APARTADOSBAREMACION (CODIGO,NOMBRE)
VALUES ('1','Formación académica');
INSERT INTO TBEP_APARTADOSBAREMACION (CODIGO,NOMBRE)
VALUES ('2','Actividad docente');
INSERT INTO TBEP_APARTADOSBAREMACION (CODIGO,NOMBRE)
VALUES ('3','Actividad investigadora');
INSERT INTO TBEP_APARTADOSBAREMACION (CODIGO,NOMBRE)
VALUES ('4','Méritos preferentes');