-- creación registros de prueba apartados de baremación;
INSERT INTO TBEP_APARTADOSBAREMACION (CODIGO,NOMBRE,PORCENTAJEMAXIMO)
VALUES ('1','Formación académica',30);
INSERT INTO TBEP_APARTADOSBAREMACION (CODIGO,NOMBRE,PORCENTAJEMAXIMO)
VALUES ('2','Actividad docente',40);
INSERT INTO TBEP_APARTADOSBAREMACION (CODIGO,NOMBRE,PORCENTAJEMAXIMO)
VALUES ('3','Actividad investigadora',20);