INSERT INTO TBEP_SOLICITUD_BOLSAS (BEPBOL_CODNUM, BEPSOL_CODNUM, UID_USUARIO)
	VALUES (2,1,'CARGA_INICIAL');
INSERT INTO TBEP_SOLICITUD_BOLSAS (BEPBOL_CODNUM, BEPSOL_CODNUM, UID_USUARIO)
	VALUES (4,1,'CARGA_INICIAL');
INSERT INTO TBEP_SOLICITUD_BOLSAS (BEPBOL_CODNUM, BEPSOL_CODNUM, UID_USUARIO)
	VALUES (8,1,'CARGA_INICIAL');
INSERT INTO TBEP_SOLICITUD_BOLSAS (BEPBOL_CODNUM, BEPSOL_CODNUM, UID_USUARIO)
	VALUES (9,1,'CARGA_INICIAL');