-- creación registros de prueba apartados de baremación;
INSERT INTO TBEP_APARTADOSBAREMACION (CODIGO,NOMBRE,PORCENTAJEMAXIMO)
VALUES ('I','Formación académica',50);
INSERT INTO TBEP_APARTADOSBAREMACION (CODIGO,NOMBRE,PORCENTAJEMAXIMO)
VALUES ('II','Actividad docente',20);
INSERT INTO TBEP_APARTADOSBAREMACION (CODIGO,NOMBRE,PORCENTAJEMAXIMO)
VALUES ('III','Actividad investigadora',30);