-- creación registros de prueba ítems de baremación;
INSERT INTO TBEP_ITEMSBAREMACION (BEPBLO_CODNUM,CODIGO,NOMBRE)
SELECT
	bepblo.CODNUM AS BEPBLO_CODNUM,
	'1' AS CODIGO,
	'Nota media de las asignaturas cursadas en la titulación exigida para la plaza' AS NOMBRE
FROM TBEP_BLOQUESBAREMACION bepblo ORDER BY bepblo.CODIGO FETCH FIRST 1 ROWS ONLY;
INSERT INTO TBEP_ITEMSBAREMACION (BEPBLO_CODNUM,CODIGO,NOMBRE)
SELECT
	bepblo.CODNUM AS BEPBLO_CODNUM,
	'2' AS CODIGO,
	'Ítem 2' AS NOMBRE
FROM TBEP_BLOQUESBAREMACION bepblo ORDER BY bepblo.CODIGO FETCH FIRST 1 ROWS ONLY;
INSERT INTO TBEP_ITEMSBAREMACION (BEPBLO_CODNUM,CODIGO,NOMBRE)
SELECT
	bepblo.CODNUM AS BEPBLO_CODNUM,
	'3' AS CODIGO,
	'Ítem 3' AS NOMBRE
FROM TBEP_BLOQUESBAREMACION bepblo ORDER BY bepblo.CODIGO FETCH FIRST 1 ROWS ONLY;
INSERT INTO TBEP_ITEMSBAREMACION (BEPBLO_CODNUM,CODIGO,NOMBRE)
SELECT
	bepblo.CODNUM AS BEPBLO_CODNUM,
	'4' AS CODIGO,
	'Ítem 4' AS NOMBRE
FROM TBEP_BLOQUESBAREMACION bepblo ORDER BY bepblo.CODIGO FETCH FIRST 1 ROWS ONLY;
INSERT INTO TBEP_ITEMSBAREMACION (BEPBLO_CODNUM,CODIGO,NOMBRE)
SELECT
	bepblo.CODNUM AS BEPBLO_CODNUM,
	'5' AS CODIGO,
	'Ítem 5' AS NOMBRE
FROM TBEP_BLOQUESBAREMACION bepblo ORDER BY bepblo.CODIGO FETCH FIRST 1 ROWS ONLY;
INSERT INTO TBEP_ITEMSBAREMACION (BEPBLO_CODNUM,CODIGO,NOMBRE)
SELECT
	bepblo.CODNUM AS BEPBLO_CODNUM,
	'6' AS CODIGO,
	'Ítem 6' AS NOMBRE
FROM TBEP_BLOQUESBAREMACION bepblo ORDER BY bepblo.CODIGO FETCH FIRST 1 ROWS ONLY;