INSERT INTO TBEP_SOL_BOL_MERITOS (BEPSBO_CODNUM, BEPMER_CODNUM,UID_USUARIO)
	VALUES (1,1,'CARGA_INICIAL');
INSERT INTO TBEP_SOL_BOL_MERITOS (BEPSBO_CODNUM, BEPMER_CODNUM,UID_USUARIO)
	VALUES (1,2,'CARGA_INICIAL');
INSERT INTO TBEP_SOL_BOL_MERITOS (BEPSBO_CODNUM, BEPMER_CODNUM,UID_USUARIO)
	VALUES (1,3,'CARGA_INICIAL');
INSERT INTO TBEP_SOL_BOL_MERITOS (BEPSBO_CODNUM, BEPMER_CODNUM,UID_USUARIO)
	VALUES (2,2,'CARGA_INICIAL');
INSERT INTO TBEP_SOL_BOL_MERITOS (BEPSBO_CODNUM, BEPMER_CODNUM,UID_USUARIO)
	VALUES (2,4,'CARGA_INICIAL');
INSERT INTO TBEP_SOL_BOL_MERITOS (BEPSBO_CODNUM, BEPMER_CODNUM,UID_USUARIO)
	VALUES (3,1,'CARGA_INICIAL');
INSERT INTO TBEP_SOL_BOL_MERITOS (BEPSBO_CODNUM, BEPMER_CODNUM,UID_USUARIO)
	VALUES (3,5,'CARGA_INICIAL');
INSERT INTO TBEP_SOL_BOL_MERITOS (BEPSBO_CODNUM, BEPMER_CODNUM,UID_USUARIO)
	VALUES (3,3,'CARGA_INICIAL');
INSERT INTO TBEP_SOL_BOL_MERITOS (BEPSBO_CODNUM, BEPMER_CODNUM,UID_USUARIO)
	VALUES (1,9,'CARGA_INICIAL');
INSERT INTO TBEP_SOL_BOL_MERITOS (BEPSBO_CODNUM, BEPMER_CODNUM,UID_USUARIO)
	VALUES (2,9,'CARGA_INICIAL');
