INSERT INTO TBEP_TITULACIONES_USUARIO (BEPTUS_TIT_CODNUM, BEPTUS_USU_CODNUM,DESCRIPCION,ARCHIVO,FLGVALIDADA,UID_USUARIO)
SELECT
(SELECT beptit.CODNUM AS BEPTUS_TIT_CODNUM FROM TBEP_TITULACIONES beptit FETCH FIRST 1 ROWS ONLY),
bepusu.CODNUM AS BEPTUS_USU_CODNUM,
'descripcion titulación 1' AS DESCRIPCION,
hextoraw('453d7a34') AS ARCHIVO,
'N' AS FLGVALIDADA,
'CARGA_INICIAL' AS UID_USUARIO
FROM TBEP_USUARIOS bepusu WHERE bepusu.CODCUENTA = 'candidato1' FETCH FIRST 1 ROWS ONLY;
INSERT INTO TBEP_TITULACIONES_USUARIO (BEPTUS_TIT_CODNUM, BEPTUS_USU_CODNUM,DESCRIPCION,ARCHIVO,FLGVALIDADA,UID_USUARIO)
SELECT
(SELECT beptit.CODNUM AS BEPTUS_TIT_CODNUM FROM TBEP_TITULACIONES beptit WHERE beptit.CODNUM = 2),
bepusu.CODNUM AS BEPTUS_USU_CODNUM,
'descripcion titulación 2' AS DESCRIPCION,
hextoraw('453d7a34') AS ARCHIVO,
'S' AS FLGVALIDADA,
'CARGA_INICIAL' AS UID_USUARIO
FROM TBEP_USUARIOS bepusu WHERE bepusu.CODCUENTA = 'candidato1' FETCH FIRST 1 ROWS ONLY;
INSERT INTO TBEP_TITULACIONES_USUARIO (BEPTUS_TIT_CODNUM, BEPTUS_USU_CODNUM,DESCRIPCION,ARCHIVO,FLGVALIDADA,UID_USUARIO)
SELECT
(SELECT beptit.CODNUM AS BEPTUS_TIT_CODNUM FROM TBEP_TITULACIONES beptit WHERE beptit.CODNUM = 3),
bepusu.CODNUM AS BEPTUS_USU_CODNUM,
'descripcion titulación 3' AS DESCRIPCION,
hextoraw('453d7a34') AS ARCHIVO,
'N' AS FLGVALIDADA,
'CARGA_INICIAL' AS UID_USUARIO
FROM TBEP_USUARIOS bepusu WHERE bepusu.CODCUENTA = 'candidato1' FETCH FIRST 1 ROWS ONLY;
INSERT INTO TBEP_TITULACIONES_USUARIO (BEPTUS_TIT_CODNUM, BEPTUS_USU_CODNUM,DESCRIPCION,ARCHIVO,FLGVALIDADA,UID_USUARIO)
SELECT
(SELECT beptit.CODNUM AS BEPTUS_TIT_CODNUM FROM TBEP_TITULACIONES beptit WHERE beptit.NOMBRE LIKE '%Matemáticas%' FETCH FIRST 1 ROWS ONLY),
bepusu.CODNUM AS BEPTUS_USU_CODNUM,
'descripcion titulación 4' AS DESCRIPCION,
hextoraw('453d7a34') AS ARCHIVO,
'S' AS FLGVALIDADA,
'CARGA_INICIAL' AS UID_USUARIO
FROM TBEP_USUARIOS bepusu WHERE bepusu.CODCUENTA = 'candidato3' FETCH FIRST 1 ROWS ONLY;