INSERT INTO UVIRTUAL.TBEP_USUARIOS (PRSNIF,CODCUENTA,ROL,DIRECCION,CODIGOPOSTAL,LOCALIDAD,PROVINCIA,NACIONALIDAD,FLGLISTADISTRIBUCION,FLGEXCLUIDO,FLGBORRADO)
VALUES ('62607992Z','personal1', 1050, 'Calle Ejemplo Personal1', '11111', 'GRANADA', 'GRANADA', 'ESPAÑOL',
		'S', 'N', 'N');
INSERT INTO UVIRTUAL.TBEP_USUARIOS (PRSNIF,CODCUENTA,ROL,DIRECCION,CODIGOPOSTAL,LOCALIDAD,PROVINCIA,NACIONALIDAD,FLGLISTADISTRIBUCION,FLGEXCLUIDO,FLGBORRADO)
VALUES ('36393760D','comision1', 1051, 'Calle Ejemplo Personal1', '11111', 'GRANADA', 'GRANADA', 'ESPAÑOL',
		'S', 'N', 'N');
INSERT INTO UVIRTUAL.TBEP_USUARIOS (PRSNIF,CODCUENTA,ROL,DIRECCION,CODIGOPOSTAL,LOCALIDAD,PROVINCIA,NACIONALIDAD,FLGLISTADISTRIBUCION,FLGEXCLUIDO,FLGBORRADO)
VALUES ('03465896A','director1', 1053, 'Calle Ejemplo Personal1', '11111', 'GRANADA', 'GRANADA', 'ESPAÑOL',
		'S', 'N', 'N');
INSERT INTO UVIRTUAL.TBEP_USUARIOS (PRSNIF,CODCUENTA,ROL,DIRECCION,CODIGOPOSTAL,LOCALIDAD,PROVINCIA,NACIONALIDAD,FLGLISTADISTRIBUCION,FLGEXCLUIDO,FLGBORRADO)
VALUES ('43396488L','candidato1', 1052, 'Calle Ejemplo Candidato1', '11111', 'GRANADA', 'GRANADA', 'ESPAÑOL',
		'S', 'N', 'N');
		INSERT INTO UVIRTUAL.TBEP_USUARIOS (PRSNIF,CODCUENTA,ROL,DIRECCION,CODIGOPOSTAL,LOCALIDAD,PROVINCIA,NACIONALIDAD,FLGLISTADISTRIBUCION,FLGEXCLUIDO,FLGBORRADO)
VALUES ('91606989J','candidato2', 1052, 'Calle Ejemplo Candidato2', '11111', 'GRANADA', 'GRANADA', 'ESPAÑOL',
		'S', 'N', 'N');