-- creación registros de prueba bloques de baremación;
INSERT INTO TBEP_BLOQUESBAREMACION (BEPAPA_CODNUM,CODIGO,NOMBRE)
SELECT
	bepapa.CODNUM AS BEPAPA_CODNUM,
	'1' AS CODIGO,
	'Titulacion' AS NOMBRE
FROM TBEP_APARTADOSBAREMACION bepapa ORDER BY bepapa.CODIGO FETCH FIRST 1 ROWS ONLY;
INSERT INTO TBEP_BLOQUESBAREMACION (BEPAPA_CODNUM,CODIGO,NOMBRE)
SELECT
	bepapa.CODNUM AS BEPAPA_CODNUM,
	'2' AS CODIGO,
	'Premios fin de carrera' AS NOMBRE
FROM TBEP_APARTADOSBAREMACION bepapa ORDER BY bepapa.CODIGO FETCH FIRST 1 ROWS ONLY;
INSERT INTO TBEP_BLOQUESBAREMACION (BEPAPA_CODNUM,CODIGO,NOMBRE)
SELECT
	bepapa.CODNUM AS BEPAPA_CODNUM,
	'3' AS CODIGO,
	'Alumno colab. Dep. incluy. el' AS NOMBRE
FROM TBEP_APARTADOSBAREMACION bepapa ORDER BY bepapa.CODIGO FETCH FIRST 1 ROWS ONLY;
INSERT INTO TBEP_BLOQUESBAREMACION (BEPAPA_CODNUM,CODIGO,NOMBRE)
SELECT
	bepapa.CODNUM AS BEPAPA_CODNUM,
	'4' AS CODIGO,
	'Otras titulaciones universitarias afines distintas a la exigida' AS NOMBRE
FROM TBEP_APARTADOSBAREMACION bepapa ORDER BY bepapa.CODIGO FETCH FIRST 1 ROWS ONLY;
INSERT INTO TBEP_BLOQUESBAREMACION (BEPAPA_CODNUM,CODIGO,NOMBRE)
SELECT
	bepapa.CODNUM AS BEPAPA_CODNUM,
	'5' AS CODIGO,
	'Doctorado' AS NOMBRE
FROM TBEP_APARTADOSBAREMACION bepapa ORDER BY bepapa.CODIGO FETCH FIRST 1 ROWS ONLY;
INSERT INTO TBEP_BLOQUESBAREMACION (BEPAPA_CODNUM,CODIGO,NOMBRE)
SELECT
	bepapa.CODNUM AS BEPAPA_CODNUM,
	'6' AS CODIGO,
	'Becas de investigación' AS NOMBRE
FROM TBEP_APARTADOSBAREMACION bepapa ORDER BY bepapa.CODIGO FETCH FIRST 1 ROWS ONLY;