INSERT INTO TBEP_MER_PRE_USUARIO (BEPMEP_CODNUM,BEPUSU_CODNUM,BEPMPO_CODNUM,DESCRIPCION,ARCHIVO)
VALUES (
    (SELECT CODNUM FROM TBEP_MERITOS_PREFERENTES WHERE TIPO = 'POSESION' FETCH FIRST 1 ROWS ONLY),
    (SELECT CODNUM FROM TBEP_USUARIOS WHERE CODCUENTA = 'candidato1'),
    (SELECT CODNUM FROM TBEP_MER_PRE_OPCIONES WHERE CODNUM = 3),
    'descripción acreditación 1',
    hextoraw('453d7a34')
);
INSERT INTO TBEP_MER_PRE_USUARIO (BEPMEP_CODNUM,BEPUSU_CODNUM,BEPMPO_CODNUM,DESCRIPCION,ARCHIVO)
VALUES (
    (SELECT CODNUM FROM TBEP_MERITOS_PREFERENTES WHERE TIPO = 'POSESION' FETCH FIRST 1 ROWS ONLY),
    (SELECT CODNUM FROM TBEP_USUARIOS WHERE CODCUENTA = 'candidato1'),
    (SELECT CODNUM FROM TBEP_MER_PRE_OPCIONES WHERE CODNUM = 3),
    'descripción acreditación 2',
    hextoraw('453d7a34')
);
INSERT INTO TBEP_MER_PRE_USUARIO (BEPMEP_CODNUM,BEPUSU_CODNUM,BEPMPO_CODNUM,DESCRIPCION,ARCHIVO)
VALUES (
    (SELECT CODNUM FROM TBEP_MERITOS_PREFERENTES WHERE TIPO = 'POSESION' FETCH FIRST 1 ROWS ONLY),
    (SELECT CODNUM FROM TBEP_USUARIOS WHERE CODCUENTA = 'candidato1'),
    (SELECT CODNUM FROM TBEP_MER_PRE_OPCIONES WHERE CODNUM = 3),
    'descripción acreditación 3',
    hextoraw('453d7a34')
);