-- bloque I;
INSERT INTO TBEP_BLOQUESBAREMACION (BEPAPA_CODNUM,CODIGO,NOMBRE)
SELECT
	bepapa.CODNUM AS BEPAPA_CODNUM,
	'1' AS CODIGO,
	'Titulación' AS NOMBRE
FROM TBEP_APARTADOSBAREMACION bepapa WHERE bepapa.CODIGO = 'I' FETCH FIRST 1 ROWS ONLY;
INSERT INTO TBEP_BLOQUESBAREMACION (BEPAPA_CODNUM,CODIGO,NOMBRE)
SELECT
	bepapa.CODNUM AS BEPAPA_CODNUM,
	'2' AS CODIGO,
	'Premios fin de carrera' AS NOMBRE
FROM TBEP_APARTADOSBAREMACION bepapa WHERE bepapa.CODIGO = 'I' FETCH FIRST 1 ROWS ONLY;
INSERT INTO TBEP_BLOQUESBAREMACION (BEPAPA_CODNUM,CODIGO,NOMBRE)
SELECT
	bepapa.CODNUM AS BEPAPA_CODNUM,
	'3' AS CODIGO,
	'Alumno colaborador del Departamento al que pertenezca el área convocante, becario Erasmus, Intercampus, ...' AS NOMBRE
FROM TBEP_APARTADOSBAREMACION bepapa WHERE bepapa.CODIGO = 'I' FETCH FIRST 1 ROWS ONLY;
-- bloque II;
INSERT INTO TBEP_BLOQUESBAREMACION (BEPAPA_CODNUM,CODIGO,NOMBRE)
SELECT
	bepapa.CODNUM AS BEPAPA_CODNUM,
	'1' AS CODIGO,
	'Docencia universitaria en títulos oficiales' AS NOMBRE
FROM TBEP_APARTADOSBAREMACION bepapa WHERE bepapa.CODIGO = 'II' FETCH FIRST 1 ROWS ONLY;
INSERT INTO TBEP_BLOQUESBAREMACION (BEPAPA_CODNUM,CODIGO,NOMBRE)
SELECT
	bepapa.CODNUM AS BEPAPA_CODNUM,
	'2' AS CODIGO,
	'Docencia universitaria no oficial (Másteres propios de la Universidad, Cursos de Experto de la Universidad y Cursos de Extensión Universitaria)' AS NOMBRE
FROM TBEP_APARTADOSBAREMACION bepapa WHERE bepapa.CODIGO = 'II' FETCH FIRST 1 ROWS ONLY;
-- bloque III;
INSERT INTO TBEP_BLOQUESBAREMACION (BEPAPA_CODNUM,CODIGO,NOMBRE)
SELECT
	bepapa.CODNUM AS BEPAPA_CODNUM,
	'1' AS CODIGO,
	'Publicaciones científicas' AS NOMBRE
FROM TBEP_APARTADOSBAREMACION bepapa WHERE bepapa.CODIGO = 'III' FETCH FIRST 1 ROWS ONLY;
INSERT INTO TBEP_BLOQUESBAREMACION (BEPAPA_CODNUM,CODIGO,NOMBRE)
SELECT
	bepapa.CODNUM AS BEPAPA_CODNUM,
	'2' AS CODIGO,
	'Editor de revistas científicas' AS NOMBRE
FROM TBEP_APARTADOSBAREMACION bepapa WHERE bepapa.CODIGO = 'III' FETCH FIRST 1 ROWS ONLY;