INSERT INTO TBEP_SOL_BOL_MER_VALORACION (BEPSBM_CODNUM,BEPAFI_CODNUM,VALOR,UID_USUARIO)
SELECT bepsbm.CODNUM AS BEPSBM_CODNUM, 
	(SELECT CODNUM FROM TBEP_AFINIDADES bepafi WHERE bepafi.CODIGO = bepite.AFINIDAD FETCH FIRST 1 ROWS ONLY) AS BEPAFI_CODNUM,
	NULL AS VALOR, 'CARGA_INICIAL' AS UID_USUARIO FROM TBEP_SOL_BOL_MERITOS bepsbm 
	INNER JOIN TBEP_MERITOS bepmer ON bepmer.CODNUM = bepsbm.BEPMER_CODNUM
	INNER JOIN TBEP_ITEMSBAREMACION bepite ON bepite.CODNUM = bepmer.BEPITE_CODNUM 
	WHERE bepite.AFINIDAD IS NOT NULL AND bepite.INDIVIDUALIZADO = 'S';