INSERT INTO TBEP_SOL_BOL_MER_VALORACION (BEPSBM_CODNUM,BEPAFI_CODNUM,VALOR,UID_USUARIO)
SELECT bepsbm.CODNUM AS BEPSBM_CODNUM, 1, NULL AS VALOR, 'CARGA_INICIAL' AS UID_USUARIO FROM TBEP_SOL_BOL_MERITOS bepsbm 
	INNER JOIN TBEP_MERITOS bepmer ON bepmer.CODNUM = bepsbm.BEPMER_CODNUM
	INNER JOIN TBEP_ITEMSBAREMACION bepite ON bepite.CODNUM = bepmer.BEPITE_CODNUM 
	WHERE bepite.AFINIDAD IS NOT NULL AND bepite.INDIVIDUALIZADO = 'S';