-- items bloque I.1;
INSERT INTO TBEP_ITEMSBAREMACION (BEPBLO_CODNUM,CODIGO,NOMBRE,DESCRIPCION,UNIDADES,VALOR,VALOR_MINIMO,VALOR_MAXIMO,AFINIDAD,INDIVIDUALIZADO)
SELECT
    bepblo.CODNUM AS BEPBLO_CODNUM,
    '1' AS CODIGO,
    'Nota media de las asignaturas cursadas en la titulación exigida para la plaza' AS NOMBRE,
    '(A:1, N:2, SB:3 y MH:4)' AS DESCRIPCION,
    'DECIMAL' AS UNIDADES,
    1 AS VALOR,
    1 AS VALOR_MINIMO,
    4 AS VALOR_MAXIMO,
    'N' AS AFINIDAD,
    'N' AS INDIVIDUALIZADO
FROM TBEP_BLOQUESBAREMACION bepblo 
WHERE bepblo.BEPAPA_CODNUM = (SELECT bepapa.CODNUM FROM TBEP_APARTADOSBAREMACION bepapa WHERE bepapa.CODIGO = 'I' FETCH FIRST 1 ROWS ONLY) 
AND bepblo.CODIGO = '1' FETCH FIRST 1 ROWS ONLY;
-- items bloque I.2.1;
INSERT INTO TBEP_ITEMSBAREMACION (BEPBLO_CODNUM,CODIGO,NOMBRE,DESCRIPCION,UNIDADES,VALOR,VALOR_MINIMO,VALOR_MAXIMO,AFINIDAD,INDIVIDUALIZADO)
SELECT
    bepblo.CODNUM AS BEPBLO_CODNUM,
    '1' AS CODIGO,
    'Premios nacionales' AS NOMBRE,
    NULL AS DESCRIPCION,
    'ENTERO' AS UNIDADES,
    3 AS VALOR,
    1 AS VALOR_MINIMO,
    1000 AS VALOR_MAXIMO,
    'N' AS AFINIDAD,
    'S' AS INDIVIDUALIZADO
FROM TBEP_BLOQUESBAREMACION bepblo 
WHERE bepblo.BEPAPA_CODNUM = (SELECT bepapa.CODNUM FROM TBEP_APARTADOSBAREMACION bepapa WHERE bepapa.CODIGO = 'I' FETCH FIRST 1 ROWS ONLY) 
AND bepblo.CODIGO = '2' FETCH FIRST 1 ROWS ONLY;
-- items bloque I.2.2;
INSERT INTO TBEP_ITEMSBAREMACION (BEPBLO_CODNUM,CODIGO,NOMBRE,DESCRIPCION,UNIDADES,VALOR,VALOR_MINIMO,VALOR_MAXIMO,AFINIDAD,INDIVIDUALIZADO)
SELECT
    bepblo.CODNUM AS BEPBLO_CODNUM,
    '2' AS CODIGO,
    'Premios de la Universidad' AS NOMBRE,
    NULL AS DESCRIPCION,
    'DECIMAL' AS UNIDADES,
    1.5 AS VALOR,
    1 AS VALOR_MINIMO,
    1000 AS VALOR_MAXIMO,
    'N' AS AFINIDAD,
    'S' AS INDIVIDUALIZADO
FROM TBEP_BLOQUESBAREMACION bepblo 
WHERE bepblo.BEPAPA_CODNUM = (SELECT bepapa.CODNUM FROM TBEP_APARTADOSBAREMACION bepapa WHERE bepapa.CODIGO = 'I' FETCH FIRST 1 ROWS ONLY) 
AND bepblo.CODIGO = '2' FETCH FIRST 1 ROWS ONLY;
-- items bloque I.3.1;
INSERT INTO TBEP_ITEMSBAREMACION (BEPBLO_CODNUM,CODIGO,NOMBRE,DESCRIPCION,UNIDADES,VALOR,VALOR_MINIMO,VALOR_MAXIMO,AFINIDAD,INDIVIDUALIZADO)
SELECT
    bepblo.CODNUM AS BEPBLO_CODNUM,
    '1' AS CODIGO,
    'Meses de Becario de alumno colaborador de Departamento' AS NOMBRE,
    NULL AS DESCRIPCION,
    'DECIMAL' AS UNIDADES,
    0.05 AS VALOR,
    1 AS VALOR_MINIMO,
    100 AS VALOR_MAXIMO,
    'AA' AS AFINIDAD,
    'N' AS INDIVIDUALIZADO
FROM TBEP_BLOQUESBAREMACION bepblo 
WHERE bepblo.BEPAPA_CODNUM = (SELECT bepapa.CODNUM FROM TBEP_APARTADOSBAREMACION bepapa WHERE bepapa.CODIGO = 'I' FETCH FIRST 1 ROWS ONLY) 
AND bepblo.CODIGO = '3' FETCH FIRST 1 ROWS ONLY;
-- items bloque I.3.2;
INSERT INTO TBEP_ITEMSBAREMACION (BEPBLO_CODNUM,CODIGO,NOMBRE,DESCRIPCION,UNIDADES,VALOR,VALOR_MINIMO,VALOR_MAXIMO,AFINIDAD,INDIVIDUALIZADO)
SELECT
    bepblo.CODNUM AS BEPBLO_CODNUM,
    '2' AS CODIGO,
    'Meses de Becario Erasmus, Intercampus, ...' AS NOMBRE,
    NULL AS DESCRIPCION,
    'DECIMAL' AS UNIDADES,
    0.06 AS VALOR,
    1 AS VALOR_MINIMO,
    100 AS VALOR_MAXIMO,
    'N' AS AFINIDAD,
    'N' AS INDIVIDUALIZADO
FROM TBEP_BLOQUESBAREMACION bepblo 
WHERE bepblo.BEPAPA_CODNUM = (SELECT bepapa.CODNUM FROM TBEP_APARTADOSBAREMACION bepapa WHERE bepapa.CODIGO = 'I' FETCH FIRST 1 ROWS ONLY) 
AND bepblo.CODIGO = '3' FETCH FIRST 1 ROWS ONLY;
-- items bloque I.4.1;
INSERT INTO TBEP_ITEMSBAREMACION (BEPBLO_CODNUM,CODIGO,NOMBRE,DESCRIPCION,UNIDADES,VALOR,VALOR_MINIMO,VALOR_MAXIMO,AFINIDAD,INDIVIDUALIZADO)
SELECT
    bepblo.CODNUM AS BEPBLO_CODNUM,
    '1' AS CODIGO,
    'Titulaciones universitarias superiores' AS NOMBRE,
    'Ingenierias, Licenciaturas, Arquitectura y/o Máster Oficial' AS DESCRIPCION,
    'DECIMAL' AS UNIDADES,
    1.2 AS VALOR,
    1 AS VALOR_MINIMO,
    100 AS VALOR_MAXIMO,
    'N' AS AFINIDAD,
    'S' AS INDIVIDUALIZADO
FROM TBEP_BLOQUESBAREMACION bepblo 
WHERE bepblo.BEPAPA_CODNUM = (SELECT bepapa.CODNUM FROM TBEP_APARTADOSBAREMACION bepapa WHERE bepapa.CODIGO = 'I' FETCH FIRST 1 ROWS ONLY) 
AND bepblo.CODIGO = '4' FETCH FIRST 1 ROWS ONLY;
-- items bloque I.4.2;
INSERT INTO TBEP_ITEMSBAREMACION (BEPBLO_CODNUM,CODIGO,NOMBRE,DESCRIPCION,UNIDADES,VALOR,VALOR_MINIMO,VALOR_MAXIMO,AFINIDAD,INDIVIDUALIZADO)
SELECT
    bepblo.CODNUM AS BEPBLO_CODNUM,
    '2' AS CODIGO,
    'Titulaciones universitarias de grado medio y/o titulaciones de Grado' AS NOMBRE,
    NULL AS DESCRIPCION,
    'DECIMAL' AS UNIDADES,
    0.8 AS VALOR,
    1 AS VALOR_MINIMO,
    10 AS VALOR_MAXIMO,
    'N' AS AFINIDAD,
    'S' AS INDIVIDUALIZADO
FROM TBEP_BLOQUESBAREMACION bepblo 
WHERE bepblo.BEPAPA_CODNUM = (SELECT bepapa.CODNUM FROM TBEP_APARTADOSBAREMACION bepapa WHERE bepapa.CODIGO = 'I' FETCH FIRST 1 ROWS ONLY) 
AND bepblo.CODIGO = '4' FETCH FIRST 1 ROWS ONLY;
-- items bloque I.5.1;
INSERT INTO TBEP_ITEMSBAREMACION (BEPBLO_CODNUM,CODIGO,NOMBRE,DESCRIPCION,UNIDADES,VALOR,VALOR_MINIMO,VALOR_MAXIMO,AFINIDAD,INDIVIDUALIZADO)
SELECT
    bepblo.CODNUM AS BEPBLO_CODNUM,
    '1' AS CODIGO,
    'Créditos superados en programas de doctorado' AS NOMBRE,
    'Excluyente con los siguientes' AS DESCRIPCION,
    'DECIMAL' AS UNIDADES,
    0.1 AS VALOR,
    1 AS VALOR_MINIMO,
    1000 AS VALOR_MAXIMO,
    'AI' AS AFINIDAD,
    'N' AS INDIVIDUALIZADO
FROM TBEP_BLOQUESBAREMACION bepblo 
WHERE bepblo.BEPAPA_CODNUM = (SELECT bepapa.CODNUM FROM TBEP_APARTADOSBAREMACION bepapa WHERE bepapa.CODIGO = 'I' FETCH FIRST 1 ROWS ONLY) 
AND bepblo.CODIGO = '5' FETCH FIRST 1 ROWS ONLY;
-- items bloque I.5.2;
INSERT INTO TBEP_ITEMSBAREMACION (BEPBLO_CODNUM,CODIGO,NOMBRE,DESCRIPCION,UNIDADES,VALOR,VALOR_MINIMO,VALOR_MAXIMO,AFINIDAD,INDIVIDUALIZADO)
SELECT
    bepblo.CODNUM AS BEPBLO_CODNUM,
    '2' AS CODIGO,
    'Por estar matriculado en un programa de doctorado y tener aprobado el proyecto de tesis' AS NOMBRE,
    'Excluyente con 1.5.3 y 1.5.4' AS DESCRIPCION,
    'ENTERO' AS UNIDADES,
    2 AS VALOR,
    1 AS VALOR_MINIMO,
    5 AS VALOR_MAXIMO,
    'AI' AS AFINIDAD,
    'N' AS INDIVIDUALIZADO
FROM TBEP_BLOQUESBAREMACION bepblo 
WHERE bepblo.BEPAPA_CODNUM = (SELECT bepapa.CODNUM FROM TBEP_APARTADOSBAREMACION bepapa WHERE bepapa.CODIGO = 'I' FETCH FIRST 1 ROWS ONLY) 
AND bepblo.CODIGO = '5' FETCH FIRST 1 ROWS ONLY;
-- items bloque I.5.3;
INSERT INTO TBEP_ITEMSBAREMACION (BEPBLO_CODNUM,CODIGO,NOMBRE,DESCRIPCION,UNIDADES,VALOR,VALOR_MINIMO,VALOR_MAXIMO,AFINIDAD,INDIVIDUALIZADO)
SELECT
    bepblo.CODNUM AS BEPBLO_CODNUM,
    '3' AS CODIGO,
    'Por tener la suficiencia investigadora/DEA/Trabajo Tutelado de INiciación a la Investigación' AS NOMBRE,
    'Excluyente con 1.5.4, 1.5.5, 1.5.6 y 1.5.7' AS DESCRIPCION,
    'ENTERO' AS UNIDADES,
    3 AS VALOR,
    1 AS VALOR_MINIMO,
    3 AS VALOR_MAXIMO,
    'AI' AS AFINIDAD,
    'N' AS INDIVIDUALIZADO
FROM TBEP_BLOQUESBAREMACION bepblo 
WHERE bepblo.BEPAPA_CODNUM = (SELECT bepapa.CODNUM FROM TBEP_APARTADOSBAREMACION bepapa WHERE bepapa.CODIGO = 'I' FETCH FIRST 1 ROWS ONLY) 
AND bepblo.CODIGO = '5' FETCH FIRST 1 ROWS ONLY;
-- items bloque I.5.4;
INSERT INTO TBEP_ITEMSBAREMACION (BEPBLO_CODNUM,CODIGO,NOMBRE,DESCRIPCION,UNIDADES,VALOR,VALOR_MINIMO,VALOR_MAXIMO,AFINIDAD,INDIVIDUALIZADO)
SELECT
    bepblo.CODNUM AS BEPBLO_CODNUM,
    '4' AS CODIGO,
    'Por ser doctor' AS NOMBRE,
    NULL AS DESCRIPCION,
    'SI/NO' AS UNIDADES,
    6 AS VALOR,
    1 AS VALOR_MINIMO,
    2 AS VALOR_MAXIMO,
    'AI' AS AFINIDAD,
    'N' AS INDIVIDUALIZADO
FROM TBEP_BLOQUESBAREMACION bepblo 
WHERE bepblo.BEPAPA_CODNUM = (SELECT bepapa.CODNUM FROM TBEP_APARTADOSBAREMACION bepapa WHERE bepapa.CODIGO = 'I' FETCH FIRST 1 ROWS ONLY) 
AND bepblo.CODIGO = '5' FETCH FIRST 1 ROWS ONLY;
-- items bloque I.5.5;
INSERT INTO TBEP_ITEMSBAREMACION (BEPBLO_CODNUM,CODIGO,NOMBRE,DESCRIPCION,UNIDADES,VALOR,VALOR_MINIMO,VALOR_MAXIMO,AFINIDAD,INDIVIDUALIZADO)
SELECT
    bepblo.CODNUM AS BEPBLO_CODNUM,
    '5' AS CODIGO,
    'Por doctorado Cum Laude' AS NOMBRE,
    NULL AS DESCRIPCION,
    'SI/NO' AS UNIDADES,
    3 AS VALOR,
    1 AS VALOR_MINIMO,
    2 AS VALOR_MAXIMO,
    'AI' AS AFINIDAD,
    'N' AS INDIVIDUALIZADO
FROM TBEP_BLOQUESBAREMACION bepblo 
WHERE bepblo.BEPAPA_CODNUM = (SELECT bepapa.CODNUM FROM TBEP_APARTADOSBAREMACION bepapa WHERE bepapa.CODIGO = 'I' FETCH FIRST 1 ROWS ONLY) 
AND bepblo.CODIGO = '5' FETCH FIRST 1 ROWS ONLY;
-- items bloque I.5.6;
INSERT INTO TBEP_ITEMSBAREMACION (BEPBLO_CODNUM,CODIGO,NOMBRE,DESCRIPCION,UNIDADES,VALOR,VALOR_MINIMO,VALOR_MAXIMO,AFINIDAD,INDIVIDUALIZADO)
SELECT
    bepblo.CODNUM AS BEPBLO_CODNUM,
    '6' AS CODIGO,
    'Premio extraordinario de doctorado' AS NOMBRE,
    NULL AS DESCRIPCION,
    'SI/NO' AS UNIDADES,
    3 AS VALOR,
    1 AS VALOR_MINIMO,
    2 AS VALOR_MAXIMO,
    'AI' AS AFINIDAD,
    'N' AS INDIVIDUALIZADO
FROM TBEP_BLOQUESBAREMACION bepblo 
WHERE bepblo.BEPAPA_CODNUM = (SELECT bepapa.CODNUM FROM TBEP_APARTADOSBAREMACION bepapa WHERE bepapa.CODIGO = 'I' FETCH FIRST 1 ROWS ONLY) 
AND bepblo.CODIGO = '5' FETCH FIRST 1 ROWS ONLY;
-- items bloque I.5.7;
INSERT INTO TBEP_ITEMSBAREMACION (BEPBLO_CODNUM,CODIGO,NOMBRE,DESCRIPCION,UNIDADES,VALOR,VALOR_MINIMO,VALOR_MAXIMO,AFINIDAD,INDIVIDUALIZADO)
SELECT
    bepblo.CODNUM AS BEPBLO_CODNUM,
    '7' AS CODIGO,
    'Por doctorado europeo o internacional' AS NOMBRE,
    NULL AS DESCRIPCION,
    'SI/NO' AS UNIDADES,
    3 AS VALOR,
    1 AS VALOR_MINIMO,
    2 AS VALOR_MAXIMO,
    'AI' AS AFINIDAD,
    'N' AS INDIVIDUALIZADO
FROM TBEP_BLOQUESBAREMACION bepblo 
WHERE bepblo.BEPAPA_CODNUM = (SELECT bepapa.CODNUM FROM TBEP_APARTADOSBAREMACION bepapa WHERE bepapa.CODIGO = 'I' FETCH FIRST 1 ROWS ONLY) 
AND bepblo.CODIGO = '5' FETCH FIRST 1 ROWS ONLY;
-- items bloque I.6.1;
INSERT INTO TBEP_ITEMSBAREMACION (BEPBLO_CODNUM,CODIGO,NOMBRE,DESCRIPCION,UNIDADES,VALOR,VALOR_MINIMO,VALOR_MAXIMO,AFINIDAD,INDIVIDUALIZADO)
SELECT
    bepblo.CODNUM AS BEPBLO_CODNUM,
    '1' AS CODIGO,
    'Años de disfrute de beca FPI, FPDI o FPU del Plan Nacional análogas de Comunidades Autónomas y Universidades Públicas' AS NOMBRE,
    'Se consideran los años totales por cada beca' AS DESCRIPCION,
    'ENTERO' AS UNIDADES,
    1 AS VALOR,
    1 AS VALOR_MINIMO,
    30 AS VALOR_MAXIMO,
    'N' AS AFINIDAD,
    'N' AS INDIVIDUALIZADO
FROM TBEP_BLOQUESBAREMACION bepblo 
WHERE bepblo.BEPAPA_CODNUM = (SELECT bepapa.CODNUM FROM TBEP_APARTADOSBAREMACION bepapa WHERE bepapa.CODIGO = 'I' FETCH FIRST 1 ROWS ONLY) 
AND bepblo.CODIGO = '6' FETCH FIRST 1 ROWS ONLY;
-- items bloque I.6.2;
INSERT INTO TBEP_ITEMSBAREMACION (BEPBLO_CODNUM,CODIGO,NOMBRE,DESCRIPCION,UNIDADES,VALOR,VALOR_MINIMO,VALOR_MAXIMO,AFINIDAD,INDIVIDUALIZADO)
SELECT
    bepblo.CODNUM AS BEPBLO_CODNUM,
    '2' AS CODIGO,
    'Años de disfrute de beca de investigación no homologada por la Universidad de Jaén' AS NOMBRE,
    NULL AS DESCRIPCION,
    'ENTERO' AS UNIDADES,
    0.5 AS VALOR,
    1 AS VALOR_MINIMO,
    30 AS VALOR_MAXIMO,
    'N' AS AFINIDAD,
    'N' AS INDIVIDUALIZADO
FROM TBEP_BLOQUESBAREMACION bepblo 
WHERE bepblo.BEPAPA_CODNUM = (SELECT bepapa.CODNUM FROM TBEP_APARTADOSBAREMACION bepapa WHERE bepapa.CODIGO = 'I' FETCH FIRST 1 ROWS ONLY) 
AND bepblo.CODIGO = '6' FETCH FIRST 1 ROWS ONLY;
-- items bloque I.7.1;
INSERT INTO TBEP_ITEMSBAREMACION (BEPBLO_CODNUM,CODIGO,NOMBRE,DESCRIPCION,UNIDADES,VALOR,VALOR_MINIMO,VALOR_MAXIMO,AFINIDAD,INDIVIDUALIZADO)
SELECT
    bepblo.CODNUM AS BEPBLO_CODNUM,
    '1' AS CODIGO,
    'Créditos en Títulos Propios, ya sean de máster, especialista o experto universitario' AS NOMBRE,
    'Máximo 60 créditos por título' AS DESCRIPCION,
    'ENTERO' AS UNIDADES,
    0.02 AS VALOR,
    1 AS VALOR_MINIMO,
    1000 AS VALOR_MAXIMO,
    'AA' AS AFINIDAD,
    'S' AS INDIVIDUALIZADO
FROM TBEP_BLOQUESBAREMACION bepblo 
WHERE bepblo.BEPAPA_CODNUM = (SELECT bepapa.CODNUM FROM TBEP_APARTADOSBAREMACION bepapa WHERE bepapa.CODIGO = 'I' FETCH FIRST 1 ROWS ONLY) 
AND bepblo.CODIGO = '7' FETCH FIRST 1 ROWS ONLY;
-- items bloque I.8.1;
INSERT INTO TBEP_ITEMSBAREMACION (BEPBLO_CODNUM,CODIGO,NOMBRE,DESCRIPCION,UNIDADES,VALOR,VALOR_MINIMO,VALOR_MAXIMO,AFINIDAD,INDIVIDUALIZADO)
SELECT
    bepblo.CODNUM AS BEPBLO_CODNUM,
    '1' AS CODIGO,
    'Créditos en cursos de formación en materia de innovación docente universitaria' AS NOMBRE,
    NULL AS DESCRIPCION,
    'ENTERO' AS UNIDADES,
    0.06 AS VALOR,
    1 AS VALOR_MINIMO,
    1000 AS VALOR_MAXIMO,
    'N' AS AFINIDAD,
    'S' AS INDIVIDUALIZADO
FROM TBEP_BLOQUESBAREMACION bepblo 
WHERE bepblo.BEPAPA_CODNUM = (SELECT bepapa.CODNUM FROM TBEP_APARTADOSBAREMACION bepapa WHERE bepapa.CODIGO = 'I' FETCH FIRST 1 ROWS ONLY) 
AND bepblo.CODIGO = '8' FETCH FIRST 1 ROWS ONLY;
-- items bloque I.8.2;
INSERT INTO TBEP_ITEMSBAREMACION (BEPBLO_CODNUM,CODIGO,NOMBRE,DESCRIPCION,UNIDADES,VALOR,VALOR_MINIMO,VALOR_MAXIMO,AFINIDAD,INDIVIDUALIZADO)
SELECT
    bepblo.CODNUM AS BEPBLO_CODNUM,
    '2' AS CODIGO,
    'Créditos en cursos relevantes para la plaza' AS NOMBRE,
    NULL AS DESCRIPCION,
    'ENTERO' AS UNIDADES,
    0.02 AS VALOR,
    1 AS VALOR_MINIMO,
    1000 AS VALOR_MAXIMO,
    'AA' AS AFINIDAD,
    'S' AS INDIVIDUALIZADO
FROM TBEP_BLOQUESBAREMACION bepblo 
WHERE bepblo.BEPAPA_CODNUM = (SELECT bepapa.CODNUM FROM TBEP_APARTADOSBAREMACION bepapa WHERE bepapa.CODIGO = 'I' FETCH FIRST 1 ROWS ONLY) 
AND bepblo.CODIGO = '8' FETCH FIRST 1 ROWS ONLY;
-- items bloque I.8.3;
INSERT INTO TBEP_ITEMSBAREMACION (BEPBLO_CODNUM,CODIGO,NOMBRE,DESCRIPCION,UNIDADES,VALOR,VALOR_MINIMO,VALOR_MAXIMO,AFINIDAD,INDIVIDUALIZADO)
SELECT
    bepblo.CODNUM AS BEPBLO_CODNUM,
    '3' AS CODIGO,
    'Diploma o certificación oficiales de acreditación de idioma extranjero' AS NOMBRE,
    NULL AS DESCRIPCION,
    'ENTERO' AS UNIDADES,
    0.3 AS VALOR,
    1 AS VALOR_MINIMO,
    100 AS VALOR_MAXIMO,
    'N' AS AFINIDAD,
    'S' AS INDIVIDUALIZADO
FROM TBEP_BLOQUESBAREMACION bepblo 
WHERE bepblo.BEPAPA_CODNUM = (SELECT bepapa.CODNUM FROM TBEP_APARTADOSBAREMACION bepapa WHERE bepapa.CODIGO = 'I' FETCH FIRST 1 ROWS ONLY) 
AND bepblo.CODIGO = '8' FETCH FIRST 1 ROWS ONLY;
-- items bloque II.1.1;
INSERT INTO TBEP_ITEMSBAREMACION (BEPBLO_CODNUM,CODIGO,NOMBRE,DESCRIPCION,UNIDADES,VALOR,VALOR_MINIMO,VALOR_MAXIMO,AFINIDAD,INDIVIDUALIZADO)
SELECT
    bepblo.CODNUM AS BEPBLO_CODNUM,
    '1' AS CODIGO,
    'Créditos impartidos en docencia reglada de primer y segundo ciclo y grado' AS NOMBRE,
    '1 crédito equivale a 10 h.' AS DESCRIPCION,
    'DECIMAL' AS UNIDADES,
    0.125 AS VALOR,
    1 AS VALOR_MINIMO,
    1000 AS VALOR_MAXIMO,
    'AA' AS AFINIDAD,
    'N' AS INDIVIDUALIZADO
FROM TBEP_BLOQUESBAREMACION bepblo 
WHERE bepblo.BEPAPA_CODNUM = (SELECT bepapa.CODNUM FROM TBEP_APARTADOSBAREMACION bepapa WHERE bepapa.CODIGO = 'II' FETCH FIRST 1 ROWS ONLY) 
AND bepblo.CODIGO = '1' FETCH FIRST 1 ROWS ONLY;
-- items bloque II.1.2;
INSERT INTO TBEP_ITEMSBAREMACION (BEPBLO_CODNUM,CODIGO,NOMBRE,DESCRIPCION,UNIDADES,VALOR,VALOR_MINIMO,VALOR_MAXIMO,AFINIDAD,INDIVIDUALIZADO)
SELECT
    bepblo.CODNUM AS BEPBLO_CODNUM,
    '2' AS CODIGO,
    'Créditos impartidos en programas de doctorado o máster' AS NOMBRE,
    '1 crédito equivale a 10 h.' AS DESCRIPCION,
    'DECIMAL' AS UNIDADES,
    0.15 AS VALOR,
    1 AS VALOR_MINIMO,
    1000 AS VALOR_MAXIMO,
    'AA' AS AFINIDAD,
    'N' AS INDIVIDUALIZADO
FROM TBEP_BLOQUESBAREMACION bepblo 
WHERE bepblo.BEPAPA_CODNUM = (SELECT bepapa.CODNUM FROM TBEP_APARTADOSBAREMACION bepapa WHERE bepapa.CODIGO = 'II' FETCH FIRST 1 ROWS ONLY) 
AND bepblo.CODIGO = '1' FETCH FIRST 1 ROWS ONLY;
-- items bloque II.1.3;
INSERT INTO TBEP_ITEMSBAREMACION (BEPBLO_CODNUM,CODIGO,NOMBRE,DESCRIPCION,UNIDADES,VALOR,VALOR_MINIMO,VALOR_MAXIMO,AFINIDAD,INDIVIDUALIZADO)
SELECT
    bepblo.CODNUM AS BEPBLO_CODNUM,
    '3' AS CODIGO,
    'Cursos académicos como tutor de prácticas externas regladas' AS NOMBRE,
    'Hasta un máximo de tres cursos académicos' AS DESCRIPCION,
    'DECIMAL' AS UNIDADES,
    0.25 AS VALOR,
    1 AS VALOR_MINIMO,
    100 AS VALOR_MAXIMO,
    'AA' AS AFINIDAD,
    'N' AS INDIVIDUALIZADO
FROM TBEP_BLOQUESBAREMACION bepblo 
WHERE bepblo.BEPAPA_CODNUM = (SELECT bepapa.CODNUM FROM TBEP_APARTADOSBAREMACION bepapa WHERE bepapa.CODIGO = 'II' FETCH FIRST 1 ROWS ONLY) 
AND bepblo.CODIGO = '1' FETCH FIRST 1 ROWS ONLY;
-- items bloque II.1.4;
INSERT INTO TBEP_ITEMSBAREMACION (BEPBLO_CODNUM,CODIGO,NOMBRE,DESCRIPCION,UNIDADES,VALOR,VALOR_MINIMO,VALOR_MAXIMO,AFINIDAD,INDIVIDUALIZADO)
SELECT
    bepblo.CODNUM AS BEPBLO_CODNUM,
    '4' AS CODIGO,
    'Dirección de Proyectos fin de carrera / fin de grado / fin de máster' AS NOMBRE,
    NULL AS DESCRIPCION,
    'DECIMAL' AS UNIDADES,
    0.05 AS VALOR,
    1 AS VALOR_MINIMO,
    100 AS VALOR_MAXIMO,
    'AA' AS AFINIDAD,
    'S' AS INDIVIDUALIZADO
FROM TBEP_BLOQUESBAREMACION bepblo 
WHERE bepblo.BEPAPA_CODNUM = (SELECT bepapa.CODNUM FROM TBEP_APARTADOSBAREMACION bepapa WHERE bepapa.CODIGO = 'II' FETCH FIRST 1 ROWS ONLY) 
AND bepblo.CODIGO = '1' FETCH FIRST 1 ROWS ONLY;
-- items bloque II.2.1;
INSERT INTO TBEP_ITEMSBAREMACION (BEPBLO_CODNUM,CODIGO,NOMBRE,DESCRIPCION,UNIDADES,VALOR,VALOR_MINIMO,VALOR_MAXIMO,AFINIDAD,INDIVIDUALIZADO)
SELECT
    bepblo.CODNUM AS BEPBLO_CODNUM,
    '1' AS CODIGO,
    'Créditos impartidos' AS NOMBRE,
    NULL AS DESCRIPCION,
    'DECIMAL' AS UNIDADES,
    0.08 AS VALOR,
    1 AS VALOR_MINIMO,
    100 AS VALOR_MAXIMO,
    'AA' AS AFINIDAD,
    'S' AS INDIVIDUALIZADO
FROM TBEP_BLOQUESBAREMACION bepblo 
WHERE bepblo.BEPAPA_CODNUM = (SELECT bepapa.CODNUM FROM TBEP_APARTADOSBAREMACION bepapa WHERE bepapa.CODIGO = 'II' FETCH FIRST 1 ROWS ONLY) 
AND bepblo.CODIGO = '2' FETCH FIRST 1 ROWS ONLY;
-- items bloque II.3.1;
INSERT INTO TBEP_ITEMSBAREMACION (BEPBLO_CODNUM,CODIGO,NOMBRE,DESCRIPCION,UNIDADES,VALOR,VALOR_MINIMO,VALOR_MAXIMO,AFINIDAD,INDIVIDUALIZADO)
SELECT
    bepblo.CODNUM AS BEPBLO_CODNUM,
    '1' AS CODIGO,
    'Años de docencia de enseñanza secundaria en centros oficiales' AS NOMBRE,
    'A tiempo completo o parte proporcional si a tiempo parcial' AS DESCRIPCION,
    'DECIMAL' AS UNIDADES,
    0.3 AS VALOR,
    1 AS VALOR_MINIMO,
    50 AS VALOR_MAXIMO,
    'AA' AS AFINIDAD,
    'N' AS INDIVIDUALIZADO
FROM TBEP_BLOQUESBAREMACION bepblo 
WHERE bepblo.BEPAPA_CODNUM = (SELECT bepapa.CODNUM FROM TBEP_APARTADOSBAREMACION bepapa WHERE bepapa.CODIGO = 'II' FETCH FIRST 1 ROWS ONLY) 
AND bepblo.CODIGO = '3' FETCH FIRST 1 ROWS ONLY;
-- items bloque II.3.2;
INSERT INTO TBEP_ITEMSBAREMACION (BEPBLO_CODNUM,CODIGO,NOMBRE,DESCRIPCION,UNIDADES,VALOR,VALOR_MINIMO,VALOR_MAXIMO,AFINIDAD,INDIVIDUALIZADO)
SELECT
    bepblo.CODNUM AS BEPBLO_CODNUM,
    '2' AS CODIGO,
    'Créditos impartidos en cursos de formación' AS NOMBRE,
    NULL AS DESCRIPCION,
    'ENTERO' AS UNIDADES,
    0.04 AS VALOR,
    1 AS VALOR_MINIMO,
    1000 AS VALOR_MAXIMO,
    'AA' AS AFINIDAD,
    'S' AS INDIVIDUALIZADO
FROM TBEP_BLOQUESBAREMACION bepblo 
WHERE bepblo.BEPAPA_CODNUM = (SELECT bepapa.CODNUM FROM TBEP_APARTADOSBAREMACION bepapa WHERE bepapa.CODIGO = 'II' FETCH FIRST 1 ROWS ONLY) 
AND bepblo.CODIGO = '3' FETCH FIRST 1 ROWS ONLY;
-- items bloque II.4.1;
INSERT INTO TBEP_ITEMSBAREMACION (BEPBLO_CODNUM,CODIGO,NOMBRE,DESCRIPCION,UNIDADES,VALOR,VALOR_MINIMO,VALOR_MAXIMO,AFINIDAD,INDIVIDUALIZADO)
SELECT
    bepblo.CODNUM AS BEPBLO_CODNUM,
    '1' AS CODIGO,
    'Libros o monografías internacionales' AS NOMBRE,
    NULL AS DESCRIPCION,
    'ENTERO' AS UNIDADES,
    3 AS VALOR,
    1 AS VALOR_MINIMO,
    50 AS VALOR_MAXIMO,
    'AA' AS AFINIDAD,
    'S' AS INDIVIDUALIZADO
FROM TBEP_BLOQUESBAREMACION bepblo 
WHERE bepblo.BEPAPA_CODNUM = (SELECT bepapa.CODNUM FROM TBEP_APARTADOSBAREMACION bepapa WHERE bepapa.CODIGO = 'II' FETCH FIRST 1 ROWS ONLY) 
AND bepblo.CODIGO = '4' FETCH FIRST 1 ROWS ONLY;
-- items bloque II.4.2;
INSERT INTO TBEP_ITEMSBAREMACION (BEPBLO_CODNUM,CODIGO,NOMBRE,DESCRIPCION,UNIDADES,VALOR,VALOR_MINIMO,VALOR_MAXIMO,AFINIDAD,INDIVIDUALIZADO)
SELECT
    bepblo.CODNUM AS BEPBLO_CODNUM,
    '2' AS CODIGO,
    'Capítulos de libros internacionales' AS NOMBRE,
    'Máxmo 2 capítulos por libro' AS DESCRIPCION,
    'ENTERO' AS UNIDADES,
    1.5 AS VALOR,
    1 AS VALOR_MINIMO,
    50 AS VALOR_MAXIMO,
    'AA' AS AFINIDAD,
    'S' AS INDIVIDUALIZADO
FROM TBEP_BLOQUESBAREMACION bepblo 
WHERE bepblo.BEPAPA_CODNUM = (SELECT bepapa.CODNUM FROM TBEP_APARTADOSBAREMACION bepapa WHERE bepapa.CODIGO = 'II' FETCH FIRST 1 ROWS ONLY) 
AND bepblo.CODIGO = '4' FETCH FIRST 1 ROWS ONLY;
-- items bloque II.4.3;
INSERT INTO TBEP_ITEMSBAREMACION (BEPBLO_CODNUM,CODIGO,NOMBRE,DESCRIPCION,UNIDADES,VALOR,VALOR_MINIMO,VALOR_MAXIMO,AFINIDAD,INDIVIDUALIZADO)
SELECT
    bepblo.CODNUM AS BEPBLO_CODNUM,
    '3' AS CODIGO,
    'Libros o monografías nacionales' AS NOMBRE,
    NULL AS DESCRIPCION,
    'ENTERO' AS UNIDADES,
    2 AS VALOR,
    1 AS VALOR_MINIMO,
    50 AS VALOR_MAXIMO,
    'AA' AS AFINIDAD,
    'S' AS INDIVIDUALIZADO
FROM TBEP_BLOQUESBAREMACION bepblo 
WHERE bepblo.BEPAPA_CODNUM = (SELECT bepapa.CODNUM FROM TBEP_APARTADOSBAREMACION bepapa WHERE bepapa.CODIGO = 'II' FETCH FIRST 1 ROWS ONLY) 
AND bepblo.CODIGO = '4' FETCH FIRST 1 ROWS ONLY;
-- items bloque II.4.4;
INSERT INTO TBEP_ITEMSBAREMACION (BEPBLO_CODNUM,CODIGO,NOMBRE,DESCRIPCION,UNIDADES,VALOR,VALOR_MINIMO,VALOR_MAXIMO,AFINIDAD,INDIVIDUALIZADO)
SELECT
    bepblo.CODNUM AS BEPBLO_CODNUM,
    '4' AS CODIGO,
    'Capítulos de libros nacionales' AS NOMBRE,
    'Máximo 2 capítulos por libro' AS DESCRIPCION,
    'ENTERO' AS UNIDADES,
    1.5 AS VALOR,
    1 AS VALOR_MINIMO,
    50 AS VALOR_MAXIMO,
    'AA' AS AFINIDAD,
    'S' AS INDIVIDUALIZADO
FROM TBEP_BLOQUESBAREMACION bepblo 
WHERE bepblo.BEPAPA_CODNUM = (SELECT bepapa.CODNUM FROM TBEP_APARTADOSBAREMACION bepapa WHERE bepapa.CODIGO = 'II' FETCH FIRST 1 ROWS ONLY) 
AND bepblo.CODIGO = '4' FETCH FIRST 1 ROWS ONLY;
-- items bloque II.4.5;
INSERT INTO TBEP_ITEMSBAREMACION (BEPBLO_CODNUM,CODIGO,NOMBRE,DESCRIPCION,UNIDADES,VALOR,VALOR_MINIMO,VALOR_MAXIMO,AFINIDAD,INDIVIDUALIZADO)
SELECT
    bepblo.CODNUM AS BEPBLO_CODNUM,
    '5' AS CODIGO,
    'Manuales, libros de prácticas o similares' AS NOMBRE,
    NULL AS DESCRIPCION,
    'ENTERO' AS UNIDADES,
    0.7 AS VALOR,
    1 AS VALOR_MINIMO,
    50 AS VALOR_MAXIMO,
    'AA' AS AFINIDAD,
    'S' AS INDIVIDUALIZADO
FROM TBEP_BLOQUESBAREMACION bepblo 
WHERE bepblo.BEPAPA_CODNUM = (SELECT bepapa.CODNUM FROM TBEP_APARTADOSBAREMACION bepapa WHERE bepapa.CODIGO = 'II' FETCH FIRST 1 ROWS ONLY) 
AND bepblo.CODIGO = '4' FETCH FIRST 1 ROWS ONLY;
-- items bloque II.4.6;
INSERT INTO TBEP_ITEMSBAREMACION (BEPBLO_CODNUM,CODIGO,NOMBRE,DESCRIPCION,UNIDADES,VALOR,VALOR_MINIMO,VALOR_MAXIMO,AFINIDAD,INDIVIDUALIZADO)
SELECT
    bepblo.CODNUM AS BEPBLO_CODNUM,
    '6' AS CODIGO,
    'Tutoriales para docencia en red' AS NOMBRE,
    NULL AS DESCRIPCION,
    'ENTERO' AS UNIDADES,
    0.5 AS VALOR,
    1 AS VALOR_MINIMO,
    50 AS VALOR_MAXIMO,
    'AA' AS AFINIDAD,
    'S' AS INDIVIDUALIZADO
FROM TBEP_BLOQUESBAREMACION bepblo 
WHERE bepblo.BEPAPA_CODNUM = (SELECT bepapa.CODNUM FROM TBEP_APARTADOSBAREMACION bepapa WHERE bepapa.CODIGO = 'II' FETCH FIRST 1 ROWS ONLY) 
AND bepblo.CODIGO = '4' FETCH FIRST 1 ROWS ONLY;
-- items bloque II.5.1;
INSERT INTO TBEP_ITEMSBAREMACION (BEPBLO_CODNUM,CODIGO,NOMBRE,DESCRIPCION,UNIDADES,VALOR,VALOR_MINIMO,VALOR_MAXIMO,AFINIDAD,INDIVIDUALIZADO)
SELECT
    bepblo.CODNUM AS BEPBLO_CODNUM,
    '1' AS CODIGO,
    'Participación en proyectos de formación e innovación docente con una duración de al menos un año o un curso académico' AS NOMBRE,
    NULL AS DESCRIPCION,
    'ENTERO' AS UNIDADES,
    1 AS VALOR,
    1 AS VALOR_MINIMO,
    4 AS VALOR_MAXIMO,
    'AA' AS AFINIDAD,
    'S' AS INDIVIDUALIZADO
FROM TBEP_BLOQUESBAREMACION bepblo 
WHERE bepblo.BEPAPA_CODNUM = (SELECT bepapa.CODNUM FROM TBEP_APARTADOSBAREMACION bepapa WHERE bepapa.CODIGO = 'II' FETCH FIRST 1 ROWS ONLY) 
AND bepblo.CODIGO = '5' FETCH FIRST 1 ROWS ONLY;
-- items bloque II.6.1;
INSERT INTO TBEP_ITEMSBAREMACION (BEPBLO_CODNUM,CODIGO,NOMBRE,DESCRIPCION,UNIDADES,VALOR,VALOR_MINIMO,VALOR_MAXIMO,AFINIDAD,INDIVIDUALIZADO)
SELECT
    bepblo.CODNUM AS BEPBLO_CODNUM,
    '1' AS CODIGO,
    'Ponencias invitadas a congresos internacionales' AS NOMBRE,
    NULL AS DESCRIPCION,
    'ENTERO' AS UNIDADES,
    1.6 AS VALOR,
    1 AS VALOR_MINIMO,
    10 AS VALOR_MAXIMO,
    'AA' AS AFINIDAD,
    'S' AS INDIVIDUALIZADO
FROM TBEP_BLOQUESBAREMACION bepblo 
WHERE bepblo.BEPAPA_CODNUM = (SELECT bepapa.CODNUM FROM TBEP_APARTADOSBAREMACION bepapa WHERE bepapa.CODIGO = 'II' FETCH FIRST 1 ROWS ONLY) 
AND bepblo.CODIGO = '6' FETCH FIRST 1 ROWS ONLY;
-- items bloque II.6.2;
INSERT INTO TBEP_ITEMSBAREMACION (BEPBLO_CODNUM,CODIGO,NOMBRE,DESCRIPCION,UNIDADES,VALOR,VALOR_MINIMO,VALOR_MAXIMO,AFINIDAD,INDIVIDUALIZADO)
SELECT
    bepblo.CODNUM AS BEPBLO_CODNUM,
    '2' AS CODIGO,
    'Ponencias invitadas a congresos nacionales' AS NOMBRE,
    NULL AS DESCRIPCION,
    'ENTERO' AS UNIDADES,
    0.8 AS VALOR,
    1 AS VALOR_MINIMO,
    10 AS VALOR_MAXIMO,
    'AA' AS AFINIDAD,
    'S' AS INDIVIDUALIZADO
FROM TBEP_BLOQUESBAREMACION bepblo 
WHERE bepblo.BEPAPA_CODNUM = (SELECT bepapa.CODNUM FROM TBEP_APARTADOSBAREMACION bepapa WHERE bepapa.CODIGO = 'II' FETCH FIRST 1 ROWS ONLY) 
AND bepblo.CODIGO = '6' FETCH FIRST 1 ROWS ONLY;
-- items bloque II.6.3;
INSERT INTO TBEP_ITEMSBAREMACION (BEPBLO_CODNUM,CODIGO,NOMBRE,DESCRIPCION,UNIDADES,VALOR,VALOR_MINIMO,VALOR_MAXIMO,AFINIDAD,INDIVIDUALIZADO)
SELECT
    bepblo.CODNUM AS BEPBLO_CODNUM,
    '3' AS CODIGO,
    'Comunicaciones a congresos internacionales' AS NOMBRE,
    NULL AS DESCRIPCION,
    'ENTERO' AS UNIDADES,
    0.4 AS VALOR,
    1 AS VALOR_MINIMO,
    10 AS VALOR_MAXIMO,
    'AA' AS AFINIDAD,
    'S' AS INDIVIDUALIZADO
FROM TBEP_BLOQUESBAREMACION bepblo 
WHERE bepblo.BEPAPA_CODNUM = (SELECT bepapa.CODNUM FROM TBEP_APARTADOSBAREMACION bepapa WHERE bepapa.CODIGO = 'II' FETCH FIRST 1 ROWS ONLY) 
AND bepblo.CODIGO = '6' FETCH FIRST 1 ROWS ONLY;
-- items bloque II.6.4;
INSERT INTO TBEP_ITEMSBAREMACION (BEPBLO_CODNUM,CODIGO,NOMBRE,DESCRIPCION,UNIDADES,VALOR,VALOR_MINIMO,VALOR_MAXIMO,AFINIDAD,INDIVIDUALIZADO)
SELECT
    bepblo.CODNUM AS BEPBLO_CODNUM,
    '4' AS CODIGO,
    'Comunicaciones a congresos nacionales' AS NOMBRE,
    NULL AS DESCRIPCION,
    'ENTERO' AS UNIDADES,
    0.2 AS VALOR,
    1 AS VALOR_MINIMO,
    10 AS VALOR_MAXIMO,
    'AA' AS AFINIDAD,
    'S' AS INDIVIDUALIZADO
FROM TBEP_BLOQUESBAREMACION bepblo 
WHERE bepblo.BEPAPA_CODNUM = (SELECT bepapa.CODNUM FROM TBEP_APARTADOSBAREMACION bepapa WHERE bepapa.CODIGO = 'II' FETCH FIRST 1 ROWS ONLY) 
AND bepblo.CODIGO = '6' FETCH FIRST 1 ROWS ONLY;
-- items bloque II.7.1;
INSERT INTO TBEP_ITEMSBAREMACION (BEPBLO_CODNUM,CODIGO,NOMBRE,DESCRIPCION,UNIDADES,VALOR,VALOR_MINIMO,VALOR_MAXIMO,AFINIDAD,INDIVIDUALIZADO)
SELECT
    bepblo.CODNUM AS BEPBLO_CODNUM,
    '1' AS CODIGO,
    'Créditos de asignatura impartida en idioma extranjero en títulos oficiales' AS NOMBRE,
    NULL AS DESCRIPCION,
    'ENTERO' AS UNIDADES,
    0.05 AS VALOR,
    1 AS VALOR_MINIMO,
    1000 AS VALOR_MAXIMO,
    'AA' AS AFINIDAD,
    'S' AS INDIVIDUALIZADO
FROM TBEP_BLOQUESBAREMACION bepblo 
WHERE bepblo.BEPAPA_CODNUM = (SELECT bepapa.CODNUM FROM TBEP_APARTADOSBAREMACION bepapa WHERE bepapa.CODIGO = 'II' FETCH FIRST 1 ROWS ONLY) 
AND bepblo.CODIGO = '7' FETCH FIRST 1 ROWS ONLY;
-- items bloque III.1.1;
INSERT INTO TBEP_ITEMSBAREMACION (BEPBLO_CODNUM,CODIGO,NOMBRE,DESCRIPCION,UNIDADES,VALOR,VALOR_MINIMO,VALOR_MAXIMO,AFINIDAD,INDIVIDUALIZADO)
SELECT
    bepblo.CODNUM AS BEPBLO_CODNUM,
    '1' AS CODIGO,
    'Artículos en revistas situadas en el 1er cuartil del Journal Citation Report' AS NOMBRE,
    NULL AS DESCRIPCION,
    'ENTERO' AS UNIDADES,
    3.6 AS VALOR,
    1 AS VALOR_MINIMO,
    1000 AS VALOR_MAXIMO,
    'AI' AS AFINIDAD,
    'S' AS INDIVIDUALIZADO
FROM TBEP_BLOQUESBAREMACION bepblo 
WHERE bepblo.BEPAPA_CODNUM = (SELECT bepapa.CODNUM FROM TBEP_APARTADOSBAREMACION bepapa WHERE bepapa.CODIGO = 'III' FETCH FIRST 1 ROWS ONLY) 
AND bepblo.CODIGO = '1' FETCH FIRST 1 ROWS ONLY;
-- items bloque III.1.2;
INSERT INTO TBEP_ITEMSBAREMACION (BEPBLO_CODNUM,CODIGO,NOMBRE,DESCRIPCION,UNIDADES,VALOR,VALOR_MINIMO,VALOR_MAXIMO,AFINIDAD,INDIVIDUALIZADO)
SELECT
    bepblo.CODNUM AS BEPBLO_CODNUM,
    '2' AS CODIGO,
    'Artículos en revistas situadas en el 2º cuartil del Journal Citation Report' AS NOMBRE,
    NULL AS DESCRIPCION,
    'ENTERO' AS UNIDADES,
    3.4 AS VALOR,
    1 AS VALOR_MINIMO,
    1000 AS VALOR_MAXIMO,
    'AI' AS AFINIDAD,
    'S' AS INDIVIDUALIZADO
FROM TBEP_BLOQUESBAREMACION bepblo 
WHERE bepblo.BEPAPA_CODNUM = (SELECT bepapa.CODNUM FROM TBEP_APARTADOSBAREMACION bepapa WHERE bepapa.CODIGO = 'III' FETCH FIRST 1 ROWS ONLY) 
AND bepblo.CODIGO = '1' FETCH FIRST 1 ROWS ONLY;
-- items bloque III.1.3;
INSERT INTO TBEP_ITEMSBAREMACION (BEPBLO_CODNUM,CODIGO,NOMBRE,DESCRIPCION,UNIDADES,VALOR,VALOR_MINIMO,VALOR_MAXIMO,AFINIDAD,INDIVIDUALIZADO)
SELECT
    bepblo.CODNUM AS BEPBLO_CODNUM,
    '3' AS CODIGO,
    'Artículos en revistas situadas en el 3er cuartil del Journal Citation Report o en primer cuartil de los indices de referencia utilizados para la evaluación de la actividad' AS NOMBRE,
    NULL AS DESCRIPCION,
    'ENTERO' AS UNIDADES,
    3 AS VALOR,
    1 AS VALOR_MINIMO,
    1000 AS VALOR_MAXIMO,
    'AI' AS AFINIDAD,
    'S' AS INDIVIDUALIZADO
FROM TBEP_BLOQUESBAREMACION bepblo 
WHERE bepblo.BEPAPA_CODNUM = (SELECT bepapa.CODNUM FROM TBEP_APARTADOSBAREMACION bepapa WHERE bepapa.CODIGO = 'III' FETCH FIRST 1 ROWS ONLY) 
AND bepblo.CODIGO = '1' FETCH FIRST 1 ROWS ONLY;
-- items bloque III.1.4;
INSERT INTO TBEP_ITEMSBAREMACION (BEPBLO_CODNUM,CODIGO,NOMBRE,DESCRIPCION,UNIDADES,VALOR,VALOR_MINIMO,VALOR_MAXIMO,AFINIDAD,INDIVIDUALIZADO)
SELECT
    bepblo.CODNUM AS BEPBLO_CODNUM,
    '4' AS CODIGO,
    'Artículos en revistas situadas en el 4º cuartil del Journal Citation Report o en segundo cuartil los indices de referencia utilizados para la evaluación de la actividad investigadora por CNEAI, en caso de no usarse JCR' AS NOMBRE,
    NULL AS DESCRIPCION,
    'ENTERO' AS UNIDADES,
    2.8 AS VALOR,
    1 AS VALOR_MINIMO,
    1000 AS VALOR_MAXIMO,
    'AI' AS AFINIDAD,
    'S' AS INDIVIDUALIZADO
FROM TBEP_BLOQUESBAREMACION bepblo 
WHERE bepblo.BEPAPA_CODNUM = (SELECT bepapa.CODNUM FROM TBEP_APARTADOSBAREMACION bepapa WHERE bepapa.CODIGO = 'III' FETCH FIRST 1 ROWS ONLY) 
AND bepblo.CODIGO = '1' FETCH FIRST 1 ROWS ONLY;
-- items bloque III.1.5;
INSERT INTO TBEP_ITEMSBAREMACION (BEPBLO_CODNUM,CODIGO,NOMBRE,DESCRIPCION,UNIDADES,VALOR,VALOR_MINIMO,VALOR_MAXIMO,AFINIDAD,INDIVIDUALIZADO)
SELECT
    bepblo.CODNUM AS BEPBLO_CODNUM,
    '5' AS CODIGO,
    'Artículos en otras revistas en tercer o cuarto de los indices de referencia utilizados para la evaluación de la actividad investigadora por CNEAI, en caso de no usarse JCR' AS NOMBRE,
    NULL AS DESCRIPCION,
    'ENTERO' AS UNIDADES,
    1.5 AS VALOR,
    1 AS VALOR_MINIMO,
    1000 AS VALOR_MAXIMO,
    'AI' AS AFINIDAD,
    'S' AS INDIVIDUALIZADO
FROM TBEP_BLOQUESBAREMACION bepblo 
WHERE bepblo.BEPAPA_CODNUM = (SELECT bepapa.CODNUM FROM TBEP_APARTADOSBAREMACION bepapa WHERE bepapa.CODIGO = 'III' FETCH FIRST 1 ROWS ONLY) 
AND bepblo.CODIGO = '1' FETCH FIRST 1 ROWS ONLY;
-- items bloque III.1.6;
INSERT INTO TBEP_ITEMSBAREMACION (BEPBLO_CODNUM,CODIGO,NOMBRE,DESCRIPCION,UNIDADES,VALOR,VALOR_MINIMO,VALOR_MAXIMO,AFINIDAD,INDIVIDUALIZADO)
SELECT
    bepblo.CODNUM AS BEPBLO_CODNUM,
    '6' AS CODIGO,
    'Artículos en otras revistas con proceso anónimo de revisión por pares y referenciadas en SCOPUS' AS NOMBRE,
    NULL AS DESCRIPCION,
    'ENTERO' AS UNIDADES,
    0.5 AS VALOR,
    1 AS VALOR_MINIMO,
    1000 AS VALOR_MAXIMO,
    'AI' AS AFINIDAD,
    'S' AS INDIVIDUALIZADO
FROM TBEP_BLOQUESBAREMACION bepblo 
WHERE bepblo.BEPAPA_CODNUM = (SELECT bepapa.CODNUM FROM TBEP_APARTADOSBAREMACION bepapa WHERE bepapa.CODIGO = 'III' FETCH FIRST 1 ROWS ONLY) 
AND bepblo.CODIGO = '1' FETCH FIRST 1 ROWS ONLY;
-- items bloque III.2.1;
INSERT INTO TBEP_ITEMSBAREMACION (BEPBLO_CODNUM,CODIGO,NOMBRE,DESCRIPCION,UNIDADES,VALOR,VALOR_MINIMO,VALOR_MAXIMO,AFINIDAD,INDIVIDUALIZADO)
SELECT
    bepblo.CODNUM AS BEPBLO_CODNUM,
    '1' AS CODIGO,
    'Editor jefe de revista internacional' AS NOMBRE,
    NULL AS DESCRIPCION,
    'SI/NO' AS UNIDADES,
    3 AS VALOR,
    1 AS VALOR_MINIMO,
    2 AS VALOR_MAXIMO,
    'AI' AS AFINIDAD,
    'S' AS INDIVIDUALIZADO
FROM TBEP_BLOQUESBAREMACION bepblo 
WHERE bepblo.BEPAPA_CODNUM = (SELECT bepapa.CODNUM FROM TBEP_APARTADOSBAREMACION bepapa WHERE bepapa.CODIGO = 'III' FETCH FIRST 1 ROWS ONLY) 
AND bepblo.CODIGO = '2' FETCH FIRST 1 ROWS ONLY;
-- items bloque III.2.2;
INSERT INTO TBEP_ITEMSBAREMACION (BEPBLO_CODNUM,CODIGO,NOMBRE,DESCRIPCION,UNIDADES,VALOR,VALOR_MINIMO,VALOR_MAXIMO,AFINIDAD,INDIVIDUALIZADO)
SELECT
    bepblo.CODNUM AS BEPBLO_CODNUM,
    '2' AS CODIGO,
    'Editor jefe de revista nacional' AS NOMBRE,
    NULL AS DESCRIPCION,
    'SI/NO' AS UNIDADES,
    1.5 AS VALOR,
    1 AS VALOR_MINIMO,
    2 AS VALOR_MAXIMO,
    'AI' AS AFINIDAD,
    'S' AS INDIVIDUALIZADO
FROM TBEP_BLOQUESBAREMACION bepblo 
WHERE bepblo.BEPAPA_CODNUM = (SELECT bepapa.CODNUM FROM TBEP_APARTADOSBAREMACION bepapa WHERE bepapa.CODIGO = 'III' FETCH FIRST 1 ROWS ONLY) 
AND bepblo.CODIGO = '2' FETCH FIRST 1 ROWS ONLY;
-- items bloque III.2.3;
INSERT INTO TBEP_ITEMSBAREMACION (BEPBLO_CODNUM,CODIGO,NOMBRE,DESCRIPCION,UNIDADES,VALOR,VALOR_MINIMO,VALOR_MAXIMO,AFINIDAD,INDIVIDUALIZADO)
SELECT
    bepblo.CODNUM AS BEPBLO_CODNUM,
    '3' AS CODIGO,
    'Miembro del comité editorial/evaluador de revista internacional' AS NOMBRE,
    NULL AS DESCRIPCION,
    'SI/NO' AS UNIDADES,
    1.5 AS VALOR,
    1 AS VALOR_MINIMO,
    2 AS VALOR_MAXIMO,
    'AI' AS AFINIDAD,
    'S' AS INDIVIDUALIZADO
FROM TBEP_BLOQUESBAREMACION bepblo 
WHERE bepblo.BEPAPA_CODNUM = (SELECT bepapa.CODNUM FROM TBEP_APARTADOSBAREMACION bepapa WHERE bepapa.CODIGO = 'III' FETCH FIRST 1 ROWS ONLY) 
AND bepblo.CODIGO = '2' FETCH FIRST 1 ROWS ONLY;
-- items bloque III.2.4;
INSERT INTO TBEP_ITEMSBAREMACION (BEPBLO_CODNUM,CODIGO,NOMBRE,DESCRIPCION,UNIDADES,VALOR,VALOR_MINIMO,VALOR_MAXIMO,AFINIDAD,INDIVIDUALIZADO)
SELECT
    bepblo.CODNUM AS BEPBLO_CODNUM,
    '4' AS CODIGO,
    'Miembro del comité editorial/evaluador de revista nacional' AS NOMBRE,
    NULL AS DESCRIPCION,
    'SI/NO' AS UNIDADES,
    0.7 AS VALOR,
    1 AS VALOR_MINIMO,
    2 AS VALOR_MAXIMO,
    'AI' AS AFINIDAD,
    'S' AS INDIVIDUALIZADO
FROM TBEP_BLOQUESBAREMACION bepblo 
WHERE bepblo.BEPAPA_CODNUM = (SELECT bepapa.CODNUM FROM TBEP_APARTADOSBAREMACION bepapa WHERE bepapa.CODIGO = 'III' FETCH FIRST 1 ROWS ONLY) 
AND bepblo.CODIGO = '2' FETCH FIRST 1 ROWS ONLY;
-- items bloque III.3.1;
INSERT INTO TBEP_ITEMSBAREMACION (BEPBLO_CODNUM,CODIGO,NOMBRE,DESCRIPCION,UNIDADES,VALOR,VALOR_MINIMO,VALOR_MAXIMO,AFINIDAD,INDIVIDUALIZADO)
SELECT
    bepblo.CODNUM AS BEPBLO_CODNUM,
    '1' AS CODIGO,
    'Libros o monografías internacionales' AS NOMBRE,
    'No se consideran proceedings' AS DESCRIPCION,
    'ENTERO' AS UNIDADES,
    3 AS VALOR,
    1 AS VALOR_MINIMO,
    100 AS VALOR_MAXIMO,
    'AI' AS AFINIDAD,
    'S' AS INDIVIDUALIZADO
FROM TBEP_BLOQUESBAREMACION bepblo 
WHERE bepblo.BEPAPA_CODNUM = (SELECT bepapa.CODNUM FROM TBEP_APARTADOSBAREMACION bepapa WHERE bepapa.CODIGO = 'III' FETCH FIRST 1 ROWS ONLY) 
AND bepblo.CODIGO = '3' FETCH FIRST 1 ROWS ONLY;
-- items bloque III.3.2;
INSERT INTO TBEP_ITEMSBAREMACION (BEPBLO_CODNUM,CODIGO,NOMBRE,DESCRIPCION,UNIDADES,VALOR,VALOR_MINIMO,VALOR_MAXIMO,AFINIDAD,INDIVIDUALIZADO)
SELECT
    bepblo.CODNUM AS BEPBLO_CODNUM,
    '2' AS CODIGO,
    'Libros o monografías nacionales' AS NOMBRE,
    'No se consideran actas que serán valoradas en el apartado III.4' AS DESCRIPCION,
    'ENTERO' AS UNIDADES,
    2 AS VALOR,
    1 AS VALOR_MINIMO,
    100 AS VALOR_MAXIMO,
    'AI' AS AFINIDAD,
    'S' AS INDIVIDUALIZADO
FROM TBEP_BLOQUESBAREMACION bepblo 
WHERE bepblo.BEPAPA_CODNUM = (SELECT bepapa.CODNUM FROM TBEP_APARTADOSBAREMACION bepapa WHERE bepapa.CODIGO = 'III' FETCH FIRST 1 ROWS ONLY) 
AND bepblo.CODIGO = '3' FETCH FIRST 1 ROWS ONLY;
-- items bloque III.3.3;
INSERT INTO TBEP_ITEMSBAREMACION (BEPBLO_CODNUM,CODIGO,NOMBRE,DESCRIPCION,UNIDADES,VALOR,VALOR_MINIMO,VALOR_MAXIMO,AFINIDAD,INDIVIDUALIZADO)
SELECT
    bepblo.CODNUM AS BEPBLO_CODNUM,
    '3' AS CODIGO,
    'Capítulos de libro internacional' AS NOMBRE,
    'Máximo 2 capítulos por libro, hasta un máximo de 3 puntos por libro' AS DESCRIPCION,
    'ENTERO' AS UNIDADES,
    1.5 AS VALOR,
    1 AS VALOR_MINIMO,
    100 AS VALOR_MAXIMO,
    'AI' AS AFINIDAD,
    'S' AS INDIVIDUALIZADO
FROM TBEP_BLOQUESBAREMACION bepblo 
WHERE bepblo.BEPAPA_CODNUM = (SELECT bepapa.CODNUM FROM TBEP_APARTADOSBAREMACION bepapa WHERE bepapa.CODIGO = 'III' FETCH FIRST 1 ROWS ONLY) 
AND bepblo.CODIGO = '3' FETCH FIRST 1 ROWS ONLY;
-- items bloque III.3.4;
INSERT INTO TBEP_ITEMSBAREMACION (BEPBLO_CODNUM,CODIGO,NOMBRE,DESCRIPCION,UNIDADES,VALOR,VALOR_MINIMO,VALOR_MAXIMO,AFINIDAD,INDIVIDUALIZADO)
SELECT
    bepblo.CODNUM AS BEPBLO_CODNUM,
    '4' AS CODIGO,
    'Capítulos de libro nacional' AS NOMBRE,
    'Máximo 2 capítulos por libro, hasta un máximo de 2 puntos por libro' AS DESCRIPCION,
    'ENTERO' AS UNIDADES,
    1 AS VALOR,
    1 AS VALOR_MINIMO,
    100 AS VALOR_MAXIMO,
    'AI' AS AFINIDAD,
    'S' AS INDIVIDUALIZADO
FROM TBEP_BLOQUESBAREMACION bepblo 
WHERE bepblo.BEPAPA_CODNUM = (SELECT bepapa.CODNUM FROM TBEP_APARTADOSBAREMACION bepapa WHERE bepapa.CODIGO = 'III' FETCH FIRST 1 ROWS ONLY) 
AND bepblo.CODIGO = '3' FETCH FIRST 1 ROWS ONLY;
-- items bloque III.3.5;
INSERT INTO TBEP_ITEMSBAREMACION (BEPBLO_CODNUM,CODIGO,NOMBRE,DESCRIPCION,UNIDADES,VALOR,VALOR_MINIMO,VALOR_MAXIMO,AFINIDAD,INDIVIDUALIZADO)
SELECT
    bepblo.CODNUM AS BEPBLO_CODNUM,
    '5' AS CODIGO,
    'Editor de libro internacional. Podrá sumarse puntuación adicional por capítulos propios hasta un máximo de 3 puntos en total por libro' AS NOMBRE,
    'No se considerarán proceedings' AS DESCRIPCION,
    'ENTERO' AS UNIDADES,
    1.5 AS VALOR,
    1 AS VALOR_MINIMO,
    100 AS VALOR_MAXIMO,
    'AI' AS AFINIDAD,
    'S' AS INDIVIDUALIZADO
FROM TBEP_BLOQUESBAREMACION bepblo 
WHERE bepblo.BEPAPA_CODNUM = (SELECT bepapa.CODNUM FROM TBEP_APARTADOSBAREMACION bepapa WHERE bepapa.CODIGO = 'III' FETCH FIRST 1 ROWS ONLY) 
AND bepblo.CODIGO = '3' FETCH FIRST 1 ROWS ONLY;
-- items bloque III.3.6;
INSERT INTO TBEP_ITEMSBAREMACION (BEPBLO_CODNUM,CODIGO,NOMBRE,DESCRIPCION,UNIDADES,VALOR,VALOR_MINIMO,VALOR_MAXIMO,AFINIDAD,INDIVIDUALIZADO)
SELECT
    bepblo.CODNUM AS BEPBLO_CODNUM,
    '6' AS CODIGO,
    'Editor de libro nacional. Podrá sumarse puntuación adicional por capítulos propios hasta un máximo de 2 puntos en total por libro' AS NOMBRE,
    'No se considerarán proceedings' AS DESCRIPCION,
    'ENTERO' AS UNIDADES,
    1 AS VALOR,
    1 AS VALOR_MINIMO,
    100 AS VALOR_MAXIMO,
    'AI' AS AFINIDAD,
    'S' AS INDIVIDUALIZADO
FROM TBEP_BLOQUESBAREMACION bepblo 
WHERE bepblo.BEPAPA_CODNUM = (SELECT bepapa.CODNUM FROM TBEP_APARTADOSBAREMACION bepapa WHERE bepapa.CODIGO = 'III' FETCH FIRST 1 ROWS ONLY) 
AND bepblo.CODIGO = '3' FETCH FIRST 1 ROWS ONLY;
-- items bloque III.3.7;
INSERT INTO TBEP_ITEMSBAREMACION (BEPBLO_CODNUM,CODIGO,NOMBRE,DESCRIPCION,UNIDADES,VALOR,VALOR_MINIMO,VALOR_MAXIMO,AFINIDAD,INDIVIDUALIZADO)
SELECT
    bepblo.CODNUM AS BEPBLO_CODNUM,
    '7' AS CODIGO,
    'Recensiones de libros' AS NOMBRE,
    'Hasta un máximo de 20 recensiones' AS DESCRIPCION,
    'ENTERO' AS UNIDADES,
    0.5 AS VALOR,
    1 AS VALOR_MINIMO,
    100 AS VALOR_MAXIMO,
    'AI' AS AFINIDAD,
    'S' AS INDIVIDUALIZADO
FROM TBEP_BLOQUESBAREMACION bepblo 
WHERE bepblo.BEPAPA_CODNUM = (SELECT bepapa.CODNUM FROM TBEP_APARTADOSBAREMACION bepapa WHERE bepapa.CODIGO = 'III' FETCH FIRST 1 ROWS ONLY) 
AND bepblo.CODIGO = '3' FETCH FIRST 1 ROWS ONLY;
-- items bloque III.3.8;
INSERT INTO TBEP_ITEMSBAREMACION (BEPBLO_CODNUM,CODIGO,NOMBRE,DESCRIPCION,UNIDADES,VALOR,VALOR_MINIMO,VALOR_MAXIMO,AFINIDAD,INDIVIDUALIZADO)
SELECT
    bepblo.CODNUM AS BEPBLO_CODNUM,
    '8' AS CODIGO,
    'Traducciones de libros' AS NOMBRE,
    NULL AS DESCRIPCION,
    'ENTERO' AS UNIDADES,
    0.5 AS VALOR,
    1 AS VALOR_MINIMO,
    1000 AS VALOR_MAXIMO,
    'AI' AS AFINIDAD,
    'S' AS INDIVIDUALIZADO
FROM TBEP_BLOQUESBAREMACION bepblo 
WHERE bepblo.BEPAPA_CODNUM = (SELECT bepapa.CODNUM FROM TBEP_APARTADOSBAREMACION bepapa WHERE bepapa.CODIGO = 'III' FETCH FIRST 1 ROWS ONLY) 
AND bepblo.CODIGO = '3' FETCH FIRST 1 ROWS ONLY;
-- items bloque III.4.1;
INSERT INTO TBEP_ITEMSBAREMACION (BEPBLO_CODNUM,CODIGO,NOMBRE,DESCRIPCION,UNIDADES,VALOR,VALOR_MINIMO,VALOR_MAXIMO,AFINIDAD,INDIVIDUALIZADO)
SELECT
    bepblo.CODNUM AS BEPBLO_CODNUM,
    '1' AS CODIGO,
    'Ponencias invitadas a congresos internacionales' AS NOMBRE,
    NULL AS DESCRIPCION,
    'ENTERO' AS UNIDADES,
    1.6 AS VALOR,
    1 AS VALOR_MINIMO,
    10 AS VALOR_MAXIMO,
    'AI' AS AFINIDAD,
    'S' AS INDIVIDUALIZADO
FROM TBEP_BLOQUESBAREMACION bepblo 
WHERE bepblo.BEPAPA_CODNUM = (SELECT bepapa.CODNUM FROM TBEP_APARTADOSBAREMACION bepapa WHERE bepapa.CODIGO = 'III' FETCH FIRST 1 ROWS ONLY) 
AND bepblo.CODIGO = '4' FETCH FIRST 1 ROWS ONLY;
-- items bloque III.4.2;
INSERT INTO TBEP_ITEMSBAREMACION (BEPBLO_CODNUM,CODIGO,NOMBRE,DESCRIPCION,UNIDADES,VALOR,VALOR_MINIMO,VALOR_MAXIMO,AFINIDAD,INDIVIDUALIZADO)
SELECT
    bepblo.CODNUM AS BEPBLO_CODNUM,
    '2' AS CODIGO,
    'Ponencias invitadas a congresos nacionales' AS NOMBRE,
    NULL AS DESCRIPCION,
    'ENTERO' AS UNIDADES,
    0.9 AS VALOR,
    1 AS VALOR_MINIMO,
    10 AS VALOR_MAXIMO,
    'AI' AS AFINIDAD,
    'S' AS INDIVIDUALIZADO
FROM TBEP_BLOQUESBAREMACION bepblo 
WHERE bepblo.BEPAPA_CODNUM = (SELECT bepapa.CODNUM FROM TBEP_APARTADOSBAREMACION bepapa WHERE bepapa.CODIGO = 'III' FETCH FIRST 1 ROWS ONLY) 
AND bepblo.CODIGO = '4' FETCH FIRST 1 ROWS ONLY;
-- items bloque III.4.3;
INSERT INTO TBEP_ITEMSBAREMACION (BEPBLO_CODNUM,CODIGO,NOMBRE,DESCRIPCION,UNIDADES,VALOR,VALOR_MINIMO,VALOR_MAXIMO,AFINIDAD,INDIVIDUALIZADO)
SELECT
    bepblo.CODNUM AS BEPBLO_CODNUM,
    '3' AS CODIGO,
    'Comunicaciones a congresos internacionales' AS NOMBRE,
    NULL AS DESCRIPCION,
    'ENTERO' AS UNIDADES,
    0.9 AS VALOR,
    1 AS VALOR_MINIMO,
    10 AS VALOR_MAXIMO,
    'AI' AS AFINIDAD,
    'S' AS INDIVIDUALIZADO
FROM TBEP_BLOQUESBAREMACION bepblo 
WHERE bepblo.BEPAPA_CODNUM = (SELECT bepapa.CODNUM FROM TBEP_APARTADOSBAREMACION bepapa WHERE bepapa.CODIGO = 'III' FETCH FIRST 1 ROWS ONLY) 
AND bepblo.CODIGO = '4' FETCH FIRST 1 ROWS ONLY;
-- items bloque III.4.4;
INSERT INTO TBEP_ITEMSBAREMACION (BEPBLO_CODNUM,CODIGO,NOMBRE,DESCRIPCION,UNIDADES,VALOR,VALOR_MINIMO,VALOR_MAXIMO,AFINIDAD,INDIVIDUALIZADO)
SELECT
    bepblo.CODNUM AS BEPBLO_CODNUM,
    '4' AS CODIGO,
    'Comunicaciones a congresos nacionales' AS NOMBRE,
    NULL AS DESCRIPCION,
    'ENTERO' AS UNIDADES,
    0.5 AS VALOR,
    1 AS VALOR_MINIMO,
    10 AS VALOR_MAXIMO,
    'AI' AS AFINIDAD,
    'S' AS INDIVIDUALIZADO
FROM TBEP_BLOQUESBAREMACION bepblo 
WHERE bepblo.BEPAPA_CODNUM = (SELECT bepapa.CODNUM FROM TBEP_APARTADOSBAREMACION bepapa WHERE bepapa.CODIGO = 'III' FETCH FIRST 1 ROWS ONLY) 
AND bepblo.CODIGO = '4' FETCH FIRST 1 ROWS ONLY;
-- items bloque III.4.5;
INSERT INTO TBEP_ITEMSBAREMACION (BEPBLO_CODNUM,CODIGO,NOMBRE,DESCRIPCION,UNIDADES,VALOR,VALOR_MINIMO,VALOR_MAXIMO,AFINIDAD,INDIVIDUALIZADO)
SELECT
    bepblo.CODNUM AS BEPBLO_CODNUM,
    '5' AS CODIGO,
    'Pósteres a congresos internacionales' AS NOMBRE,
    NULL AS DESCRIPCION,
    'ENTERO' AS UNIDADES,
    0.5 AS VALOR,
    1 AS VALOR_MINIMO,
    10 AS VALOR_MAXIMO,
    'AI' AS AFINIDAD,
    'S' AS INDIVIDUALIZADO
FROM TBEP_BLOQUESBAREMACION bepblo 
WHERE bepblo.BEPAPA_CODNUM = (SELECT bepapa.CODNUM FROM TBEP_APARTADOSBAREMACION bepapa WHERE bepapa.CODIGO = 'III' FETCH FIRST 1 ROWS ONLY) 
AND bepblo.CODIGO = '4' FETCH FIRST 1 ROWS ONLY;
-- items bloque III.4.6;
INSERT INTO TBEP_ITEMSBAREMACION (BEPBLO_CODNUM,CODIGO,NOMBRE,DESCRIPCION,UNIDADES,VALOR,VALOR_MINIMO,VALOR_MAXIMO,AFINIDAD,INDIVIDUALIZADO)
SELECT
    bepblo.CODNUM AS BEPBLO_CODNUM,
    '6' AS CODIGO,
    'Pósteres a congresos nacionales' AS NOMBRE,
    NULL AS DESCRIPCION,
    'ENTERO' AS UNIDADES,
    0.3 AS VALOR,
    1 AS VALOR_MINIMO,
    10 AS VALOR_MAXIMO,
    'AI' AS AFINIDAD,
    'S' AS INDIVIDUALIZADO
FROM TBEP_BLOQUESBAREMACION bepblo 
WHERE bepblo.BEPAPA_CODNUM = (SELECT bepapa.CODNUM FROM TBEP_APARTADOSBAREMACION bepapa WHERE bepapa.CODIGO = 'III' FETCH FIRST 1 ROWS ONLY) 
AND bepblo.CODIGO = '4' FETCH FIRST 1 ROWS ONLY;
-- items bloque III.4.7;
INSERT INTO TBEP_ITEMSBAREMACION (BEPBLO_CODNUM,CODIGO,NOMBRE,DESCRIPCION,UNIDADES,VALOR,VALOR_MINIMO,VALOR_MAXIMO,AFINIDAD,INDIVIDUALIZADO)
SELECT
    bepblo.CODNUM AS BEPBLO_CODNUM,
    '7' AS CODIGO,
    'Resúmenes a congresos internacionales' AS NOMBRE,
    NULL AS DESCRIPCION,
    'ENTERO' AS UNIDADES,
    0.3 AS VALOR,
    1 AS VALOR_MINIMO,
    10 AS VALOR_MAXIMO,
    'AI' AS AFINIDAD,
    'S' AS INDIVIDUALIZADO
FROM TBEP_BLOQUESBAREMACION bepblo 
WHERE bepblo.BEPAPA_CODNUM = (SELECT bepapa.CODNUM FROM TBEP_APARTADOSBAREMACION bepapa WHERE bepapa.CODIGO = 'III' FETCH FIRST 1 ROWS ONLY) 
AND bepblo.CODIGO = '4' FETCH FIRST 1 ROWS ONLY;
-- items bloque III.4.8;
INSERT INTO TBEP_ITEMSBAREMACION (BEPBLO_CODNUM,CODIGO,NOMBRE,DESCRIPCION,UNIDADES,VALOR,VALOR_MINIMO,VALOR_MAXIMO,AFINIDAD,INDIVIDUALIZADO)
SELECT
    bepblo.CODNUM AS BEPBLO_CODNUM,
    '8' AS CODIGO,
    'Resúmenes a congresos nacionales' AS NOMBRE,
    NULL AS DESCRIPCION,
    'ENTERO' AS UNIDADES,
    0.2 AS VALOR,
    1 AS VALOR_MINIMO,
    10 AS VALOR_MAXIMO,
    'AI' AS AFINIDAD,
    'S' AS INDIVIDUALIZADO
FROM TBEP_BLOQUESBAREMACION bepblo 
WHERE bepblo.BEPAPA_CODNUM = (SELECT bepapa.CODNUM FROM TBEP_APARTADOSBAREMACION bepapa WHERE bepapa.CODIGO = 'III' FETCH FIRST 1 ROWS ONLY) 
AND bepblo.CODIGO = '4' FETCH FIRST 1 ROWS ONLY;
-- items bloque III.5.1;
INSERT INTO TBEP_ITEMSBAREMACION (BEPBLO_CODNUM,CODIGO,NOMBRE,DESCRIPCION,UNIDADES,VALOR,VALOR_MINIMO,VALOR_MAXIMO,AFINIDAD,INDIVIDUALIZADO)
SELECT
    bepblo.CODNUM AS BEPBLO_CODNUM,
    '1' AS CODIGO,
    'Proyectos internacionales' AS NOMBRE,
    NULL AS DESCRIPCION,
    'ENTERO' AS UNIDADES,
    2.5 AS VALOR,
    1 AS VALOR_MINIMO,
    100 AS VALOR_MAXIMO,
    'AI' AS AFINIDAD,
    'S' AS INDIVIDUALIZADO
FROM TBEP_BLOQUESBAREMACION bepblo 
WHERE bepblo.BEPAPA_CODNUM = (SELECT bepapa.CODNUM FROM TBEP_APARTADOSBAREMACION bepapa WHERE bepapa.CODIGO = 'III' FETCH FIRST 1 ROWS ONLY) 
AND bepblo.CODIGO = '5' FETCH FIRST 1 ROWS ONLY;
-- items bloque III.5.2;
INSERT INTO TBEP_ITEMSBAREMACION (BEPBLO_CODNUM,CODIGO,NOMBRE,DESCRIPCION,UNIDADES,VALOR,VALOR_MINIMO,VALOR_MAXIMO,AFINIDAD,INDIVIDUALIZADO)
SELECT
    bepblo.CODNUM AS BEPBLO_CODNUM,
    '2' AS CODIGO,
    'Proyectos nacionales' AS NOMBRE,
    NULL AS DESCRIPCION,
    'ENTERO' AS UNIDADES,
    1.5 AS VALOR,
    1 AS VALOR_MINIMO,
    100 AS VALOR_MAXIMO,
    'AI' AS AFINIDAD,
    'S' AS INDIVIDUALIZADO
FROM TBEP_BLOQUESBAREMACION bepblo 
WHERE bepblo.BEPAPA_CODNUM = (SELECT bepapa.CODNUM FROM TBEP_APARTADOSBAREMACION bepapa WHERE bepapa.CODIGO = 'III' FETCH FIRST 1 ROWS ONLY) 
AND bepblo.CODIGO = '5' FETCH FIRST 1 ROWS ONLY;
-- items bloque III.5.3;
INSERT INTO TBEP_ITEMSBAREMACION (BEPBLO_CODNUM,CODIGO,NOMBRE,DESCRIPCION,UNIDADES,VALOR,VALOR_MINIMO,VALOR_MAXIMO,AFINIDAD,INDIVIDUALIZADO)
SELECT
    bepblo.CODNUM AS BEPBLO_CODNUM,
    '3' AS CODIGO,
    'Proyectos autonómicos' AS NOMBRE,
    NULL AS DESCRIPCION,
    'ENTERO' AS UNIDADES,
    1 AS VALOR,
    1 AS VALOR_MINIMO,
    100 AS VALOR_MAXIMO,
    'AI' AS AFINIDAD,
    'S' AS INDIVIDUALIZADO
FROM TBEP_BLOQUESBAREMACION bepblo 
WHERE bepblo.BEPAPA_CODNUM = (SELECT bepapa.CODNUM FROM TBEP_APARTADOSBAREMACION bepapa WHERE bepapa.CODIGO = 'III' FETCH FIRST 1 ROWS ONLY) 
AND bepblo.CODIGO = '5' FETCH FIRST 1 ROWS ONLY;
-- items bloque III.5.4;
INSERT INTO TBEP_ITEMSBAREMACION (BEPBLO_CODNUM,CODIGO,NOMBRE,DESCRIPCION,UNIDADES,VALOR,VALOR_MINIMO,VALOR_MAXIMO,AFINIDAD,INDIVIDUALIZADO)
SELECT
    bepblo.CODNUM AS BEPBLO_CODNUM,
    '4' AS CODIGO,
    'Proyectos locales' AS NOMBRE,
    NULL AS DESCRIPCION,
    'ENTERO' AS UNIDADES,
    0.7 AS VALOR,
    1 AS VALOR_MINIMO,
    100 AS VALOR_MAXIMO,
    'AI' AS AFINIDAD,
    'S' AS INDIVIDUALIZADO
FROM TBEP_BLOQUESBAREMACION bepblo 
WHERE bepblo.BEPAPA_CODNUM = (SELECT bepapa.CODNUM FROM TBEP_APARTADOSBAREMACION bepapa WHERE bepapa.CODIGO = 'III' FETCH FIRST 1 ROWS ONLY) 
AND bepblo.CODIGO = '5' FETCH FIRST 1 ROWS ONLY;
-- items bloque III.5.5;
INSERT INTO TBEP_ITEMSBAREMACION (BEPBLO_CODNUM,CODIGO,NOMBRE,DESCRIPCION,UNIDADES,VALOR,VALOR_MINIMO,VALOR_MAXIMO,AFINIDAD,INDIVIDUALIZADO)
SELECT
    bepblo.CODNUM AS BEPBLO_CODNUM,
    '5' AS CODIGO,
    'Contratos' AS NOMBRE,
    NULL AS DESCRIPCION,
    'ENTERO' AS UNIDADES,
    1 AS VALOR,
    1 AS VALOR_MINIMO,
    100 AS VALOR_MAXIMO,
    'AI' AS AFINIDAD,
    'S' AS INDIVIDUALIZADO
FROM TBEP_BLOQUESBAREMACION bepblo 
WHERE bepblo.BEPAPA_CODNUM = (SELECT bepapa.CODNUM FROM TBEP_APARTADOSBAREMACION bepapa WHERE bepapa.CODIGO = 'III' FETCH FIRST 1 ROWS ONLY) 
AND bepblo.CODIGO = '5' FETCH FIRST 1 ROWS ONLY;
-- items bloque III.6.1;
INSERT INTO TBEP_ITEMSBAREMACION (BEPBLO_CODNUM,CODIGO,NOMBRE,DESCRIPCION,UNIDADES,VALOR,VALOR_MINIMO,VALOR_MAXIMO,AFINIDAD,INDIVIDUALIZADO)
SELECT
    bepblo.CODNUM AS BEPBLO_CODNUM,
    '1' AS CODIGO,
    'Patentes en explotación' AS NOMBRE,
    NULL AS DESCRIPCION,
    'ENTERO' AS UNIDADES,
    2 AS VALOR,
    1 AS VALOR_MINIMO,
    100 AS VALOR_MAXIMO,
    'AI' AS AFINIDAD,
    'S' AS INDIVIDUALIZADO
FROM TBEP_BLOQUESBAREMACION bepblo 
WHERE bepblo.BEPAPA_CODNUM = (SELECT bepapa.CODNUM FROM TBEP_APARTADOSBAREMACION bepapa WHERE bepapa.CODIGO = 'III' FETCH FIRST 1 ROWS ONLY) 
AND bepblo.CODIGO = '6' FETCH FIRST 1 ROWS ONLY;
-- items bloque III.6.2;
INSERT INTO TBEP_ITEMSBAREMACION (BEPBLO_CODNUM,CODIGO,NOMBRE,DESCRIPCION,UNIDADES,VALOR,VALOR_MINIMO,VALOR_MAXIMO,AFINIDAD,INDIVIDUALIZADO)
SELECT
    bepblo.CODNUM AS BEPBLO_CODNUM,
    '2' AS CODIGO,
    'Patentes restringidas o moelos de explotación' AS NOMBRE,
    NULL AS DESCRIPCION,
    'ENTERO' AS UNIDADES,
    1.5 AS VALOR,
    1 AS VALOR_MINIMO,
    100 AS VALOR_MAXIMO,
    'AI' AS AFINIDAD,
    'S' AS INDIVIDUALIZADO
FROM TBEP_BLOQUESBAREMACION bepblo 
WHERE bepblo.BEPAPA_CODNUM = (SELECT bepapa.CODNUM FROM TBEP_APARTADOSBAREMACION bepapa WHERE bepapa.CODIGO = 'III' FETCH FIRST 1 ROWS ONLY) 
AND bepblo.CODIGO = '6' FETCH FIRST 1 ROWS ONLY;
-- items bloque III.7.1;
INSERT INTO TBEP_ITEMSBAREMACION (BEPBLO_CODNUM,CODIGO,NOMBRE,DESCRIPCION,UNIDADES,VALOR,VALOR_MINIMO,VALOR_MAXIMO,AFINIDAD,INDIVIDUALIZADO)
SELECT
    bepblo.CODNUM AS BEPBLO_CODNUM,
    '1' AS CODIGO,
    'Meses de estancia en centro extranjero con financiación ajena' AS NOMBRE,
    NULL AS DESCRIPCION,
    'DECIMAL' AS UNIDADES,
    0.2 AS VALOR,
    1 AS VALOR_MINIMO,
    100 AS VALOR_MAXIMO,
    'AI' AS AFINIDAD,
    'S' AS INDIVIDUALIZADO
FROM TBEP_BLOQUESBAREMACION bepblo 
WHERE bepblo.BEPAPA_CODNUM = (SELECT bepapa.CODNUM FROM TBEP_APARTADOSBAREMACION bepapa WHERE bepapa.CODIGO = 'III' FETCH FIRST 1 ROWS ONLY) 
AND bepblo.CODIGO = '7' FETCH FIRST 1 ROWS ONLY;
-- items bloque III.7.2;
INSERT INTO TBEP_ITEMSBAREMACION (BEPBLO_CODNUM,CODIGO,NOMBRE,DESCRIPCION,UNIDADES,VALOR,VALOR_MINIMO,VALOR_MAXIMO,AFINIDAD,INDIVIDUALIZADO)
SELECT
    bepblo.CODNUM AS BEPBLO_CODNUM,
    '2' AS CODIGO,
    'Meses de estancia en centro nacional con financiación ajena' AS NOMBRE,
    NULL AS DESCRIPCION,
    'DECIMAL' AS UNIDADES,
    0.1 AS VALOR,
    1 AS VALOR_MINIMO,
    100 AS VALOR_MAXIMO,
    'AI' AS AFINIDAD,
    'S' AS INDIVIDUALIZADO
FROM TBEP_BLOQUESBAREMACION bepblo 
WHERE bepblo.BEPAPA_CODNUM = (SELECT bepapa.CODNUM FROM TBEP_APARTADOSBAREMACION bepapa WHERE bepapa.CODIGO = 'III' FETCH FIRST 1 ROWS ONLY) 
AND bepblo.CODIGO = '7' FETCH FIRST 1 ROWS ONLY;
-- items bloque III.8.1;
INSERT INTO TBEP_ITEMSBAREMACION (BEPBLO_CODNUM,CODIGO,NOMBRE,DESCRIPCION,UNIDADES,VALOR,VALOR_MINIMO,VALOR_MAXIMO,AFINIDAD,INDIVIDUALIZADO)
SELECT
    bepblo.CODNUM AS BEPBLO_CODNUM,
    '1' AS CODIGO,
    'Meses de estancia en centro extranjero con financiación ajena' AS NOMBRE,
    NULL AS DESCRIPCION,
    'DECIMAL' AS UNIDADES,
    0.4 AS VALOR,
    1 AS VALOR_MINIMO,
    100 AS VALOR_MAXIMO,
    'AI' AS AFINIDAD,
    'N' AS INDIVIDUALIZADO
FROM TBEP_BLOQUESBAREMACION bepblo 
WHERE bepblo.BEPAPA_CODNUM = (SELECT bepapa.CODNUM FROM TBEP_APARTADOSBAREMACION bepapa WHERE bepapa.CODIGO = 'III' FETCH FIRST 1 ROWS ONLY) 
AND bepblo.CODIGO = '8' FETCH FIRST 1 ROWS ONLY;
-- items bloque III.8.2;
INSERT INTO TBEP_ITEMSBAREMACION (BEPBLO_CODNUM,CODIGO,NOMBRE,DESCRIPCION,UNIDADES,VALOR,VALOR_MINIMO,VALOR_MAXIMO,AFINIDAD,INDIVIDUALIZADO)
SELECT
    bepblo.CODNUM AS BEPBLO_CODNUM,
    '2' AS CODIGO,
    'Meses de estancia en centro nacional con financiación ajena' AS NOMBRE,
    NULL AS DESCRIPCION,
    'DECIMAL' AS UNIDADES,
    0.2 AS VALOR,
    1 AS VALOR_MINIMO,
    100 AS VALOR_MAXIMO,
    'AI' AS AFINIDAD,
    'N' AS INDIVIDUALIZADO
FROM TBEP_BLOQUESBAREMACION bepblo 
WHERE bepblo.BEPAPA_CODNUM = (SELECT bepapa.CODNUM FROM TBEP_APARTADOSBAREMACION bepapa WHERE bepapa.CODIGO = 'III' FETCH FIRST 1 ROWS ONLY) 
AND bepblo.CODIGO = '8' FETCH FIRST 1 ROWS ONLY;
-- items bloque III.9.1;
INSERT INTO TBEP_ITEMSBAREMACION (BEPBLO_CODNUM,CODIGO,NOMBRE,DESCRIPCION,UNIDADES,VALOR,VALOR_MINIMO,VALOR_MAXIMO,AFINIDAD,INDIVIDUALIZADO)
SELECT
    bepblo.CODNUM AS BEPBLO_CODNUM,
    '1' AS CODIGO,
    'Tésis doctorales dirigidas y defendidas' AS NOMBRE,
    NULL AS DESCRIPCION,
    'ENTERO' AS UNIDADES,
    1.5 AS VALOR,
    1 AS VALOR_MINIMO,
    100 AS VALOR_MAXIMO,
    'AI' AS AFINIDAD,
    'S' AS INDIVIDUALIZADO
FROM TBEP_BLOQUESBAREMACION bepblo 
WHERE bepblo.BEPAPA_CODNUM = (SELECT bepapa.CODNUM FROM TBEP_APARTADOSBAREMACION bepapa WHERE bepapa.CODIGO = 'III' FETCH FIRST 1 ROWS ONLY) 
AND bepblo.CODIGO = '9' FETCH FIRST 1 ROWS ONLY;
-- items bloque III.9.2;
INSERT INTO TBEP_ITEMSBAREMACION (BEPBLO_CODNUM,CODIGO,NOMBRE,DESCRIPCION,UNIDADES,VALOR,VALOR_MINIMO,VALOR_MAXIMO,AFINIDAD,INDIVIDUALIZADO)
SELECT
    bepblo.CODNUM AS BEPBLO_CODNUM,
    '2' AS CODIGO,
    'Trabajos de iniciación a la investigación dirigidos' AS NOMBRE,
    NULL AS DESCRIPCION,
    'ENTERO' AS UNIDADES,
    0.2 AS VALOR,
    1 AS VALOR_MINIMO,
    100 AS VALOR_MAXIMO,
    'AI' AS AFINIDAD,
    'S' AS INDIVIDUALIZADO
FROM TBEP_BLOQUESBAREMACION bepblo 
WHERE bepblo.BEPAPA_CODNUM = (SELECT bepapa.CODNUM FROM TBEP_APARTADOSBAREMACION bepapa WHERE bepapa.CODIGO = 'III' FETCH FIRST 1 ROWS ONLY) 
AND bepblo.CODIGO = '9' FETCH FIRST 1 ROWS ONLY;
-- items bloque III.10.1;
INSERT INTO TBEP_ITEMSBAREMACION (BEPBLO_CODNUM,CODIGO,NOMBRE,DESCRIPCION,UNIDADES,VALOR,VALOR_MINIMO,VALOR_MAXIMO,AFINIDAD,INDIVIDUALIZADO)
SELECT
    bepblo.CODNUM AS BEPBLO_CODNUM,
    '1' AS CODIGO,
    'Premios de investigación internacionales' AS NOMBRE,
    NULL AS DESCRIPCION,
    'ENTERO' AS UNIDADES,
    1.5 AS VALOR,
    1 AS VALOR_MINIMO,
    100 AS VALOR_MAXIMO,
    'AI' AS AFINIDAD,
    'S' AS INDIVIDUALIZADO
FROM TBEP_BLOQUESBAREMACION bepblo 
WHERE bepblo.BEPAPA_CODNUM = (SELECT bepapa.CODNUM FROM TBEP_APARTADOSBAREMACION bepapa WHERE bepapa.CODIGO = 'III' FETCH FIRST 1 ROWS ONLY) 
AND bepblo.CODIGO = '10' FETCH FIRST 1 ROWS ONLY;
-- items bloque III.10.2;
INSERT INTO TBEP_ITEMSBAREMACION (BEPBLO_CODNUM,CODIGO,NOMBRE,DESCRIPCION,UNIDADES,VALOR,VALOR_MINIMO,VALOR_MAXIMO,AFINIDAD,INDIVIDUALIZADO)
SELECT
    bepblo.CODNUM AS BEPBLO_CODNUM,
    '2' AS CODIGO,
    'Premios de investigación nacionales' AS NOMBRE,
    NULL AS DESCRIPCION,
    'ENTERO' AS UNIDADES,
    1 AS VALOR,
    1 AS VALOR_MINIMO,
    100 AS VALOR_MAXIMO,
    'AI' AS AFINIDAD,
    'S' AS INDIVIDUALIZADO
FROM TBEP_BLOQUESBAREMACION bepblo 
WHERE bepblo.BEPAPA_CODNUM = (SELECT bepapa.CODNUM FROM TBEP_APARTADOSBAREMACION bepapa WHERE bepapa.CODIGO = 'III' FETCH FIRST 1 ROWS ONLY) 
AND bepblo.CODIGO = '10' FETCH FIRST 1 ROWS ONLY;
-- items bloque III.10.3;
INSERT INTO TBEP_ITEMSBAREMACION (BEPBLO_CODNUM,CODIGO,NOMBRE,DESCRIPCION,UNIDADES,VALOR,VALOR_MINIMO,VALOR_MAXIMO,AFINIDAD,INDIVIDUALIZADO)
SELECT
    bepblo.CODNUM AS BEPBLO_CODNUM,
    '3' AS CODIGO,
    'Premios de investigación autonómicos' AS NOMBRE,
    NULL AS DESCRIPCION,
    'ENTERO' AS UNIDADES,
    0.6 AS VALOR,
    1 AS VALOR_MINIMO,
    100 AS VALOR_MAXIMO,
    'AI' AS AFINIDAD,
    'S' AS INDIVIDUALIZADO
FROM TBEP_BLOQUESBAREMACION bepblo 
WHERE bepblo.BEPAPA_CODNUM = (SELECT bepapa.CODNUM FROM TBEP_APARTADOSBAREMACION bepapa WHERE bepapa.CODIGO = 'III' FETCH FIRST 1 ROWS ONLY) 
AND bepblo.CODIGO = '10' FETCH FIRST 1 ROWS ONLY;
-- items bloque III.10.4;
INSERT INTO TBEP_ITEMSBAREMACION (BEPBLO_CODNUM,CODIGO,NOMBRE,DESCRIPCION,UNIDADES,VALOR,VALOR_MINIMO,VALOR_MAXIMO,AFINIDAD,INDIVIDUALIZADO)
SELECT
    bepblo.CODNUM AS BEPBLO_CODNUM,
    '4' AS CODIGO,
    'Premios de investigación locales' AS NOMBRE,
    NULL AS DESCRIPCION,
    'ENTERO' AS UNIDADES,
    0.5 AS VALOR,
    1 AS VALOR_MINIMO,
    100 AS VALOR_MAXIMO,
    'AI' AS AFINIDAD,
    'S' AS INDIVIDUALIZADO
FROM TBEP_BLOQUESBAREMACION bepblo 
WHERE bepblo.BEPAPA_CODNUM = (SELECT bepapa.CODNUM FROM TBEP_APARTADOSBAREMACION bepapa WHERE bepapa.CODIGO = 'III' FETCH FIRST 1 ROWS ONLY) 
AND bepblo.CODIGO = '10' FETCH FIRST 1 ROWS ONLY;
-- items bloque III.11.1;
INSERT INTO TBEP_ITEMSBAREMACION (BEPBLO_CODNUM,CODIGO,NOMBRE,DESCRIPCION,UNIDADES,VALOR,VALOR_MINIMO,VALOR_MAXIMO,AFINIDAD,INDIVIDUALIZADO)
SELECT
    bepblo.CODNUM AS BEPBLO_CODNUM,
    '1' AS CODIGO,
    'Meses en programas de incorporación de doctores' AS NOMBRE,
    NULL AS DESCRIPCION,
    'ENTERO' AS UNIDADES,
    0.3 AS VALOR,
    1 AS VALOR_MINIMO,
    100 AS VALOR_MAXIMO,
    'AI' AS AFINIDAD,
    'N' AS INDIVIDUALIZADO
FROM TBEP_BLOQUESBAREMACION bepblo 
WHERE bepblo.BEPAPA_CODNUM = (SELECT bepapa.CODNUM FROM TBEP_APARTADOSBAREMACION bepapa WHERE bepapa.CODIGO = 'III' FETCH FIRST 1 ROWS ONLY) 
AND bepblo.CODIGO = '11' FETCH FIRST 1 ROWS ONLY;
-- items bloque III.11.2;
INSERT INTO TBEP_ITEMSBAREMACION (BEPBLO_CODNUM,CODIGO,NOMBRE,DESCRIPCION,UNIDADES,VALOR,VALOR_MINIMO,VALOR_MAXIMO,AFINIDAD,INDIVIDUALIZADO)
SELECT
    bepblo.CODNUM AS BEPBLO_CODNUM,
    '2' AS CODIGO,
    'Pertenencia activa a grupos de investigación PAIDI evaluados en la última convocatoria' AS NOMBRE,
    NULL AS DESCRIPCION,
    'ENTERO' AS UNIDADES,
    0.3 AS VALOR,
    1 AS VALOR_MINIMO,
    100 AS VALOR_MAXIMO,
    'AI' AS AFINIDAD,
    'S' AS INDIVIDUALIZADO
FROM TBEP_BLOQUESBAREMACION bepblo 
WHERE bepblo.BEPAPA_CODNUM = (SELECT bepapa.CODNUM FROM TBEP_APARTADOSBAREMACION bepapa WHERE bepapa.CODIGO = 'III' FETCH FIRST 1 ROWS ONLY) 
AND bepblo.CODIGO = '11' FETCH FIRST 1 ROWS ONLY;