INSERT INTO UVIRTUAL.TBEP_SOL_BOL_MER_VALORACION (BEPSBM_CODNUM,BEPAFI_CODNUM,VALOR)
VALUES (
    (SELECT bepsbm.CODNUM AS BEPSBM_CODNUM FROM UVIRTUAL.TBEP_SOL_BOL_MERITOS bepsbm 
    	INNER JOIN UVIRTUAL.TBEP_MERITOS bepmer ON bepmer.CODNUM = bepsbm.BEPMER_CODNUM
    	WHERE bepmer.BEPITE_CODNUM = 8 AND bepmer.BEPUSU_CODNUM = 5 AND bepsbm.BEPSBO_CODNUM = 3 FETCH FIRST 1 ROWS ONLY),
    (SELECT CODNUM FROM UVIRTUAL.TBEP_AFINIDADES WHERE CODNUM = 1),
    1
);
INSERT INTO UVIRTUAL.TBEP_SOL_BOL_MER_VALORACION (BEPSBM_CODNUM,BEPAFI_CODNUM,VALOR)
VALUES (
    (SELECT bepsbm.CODNUM AS BEPSBM_CODNUM FROM UVIRTUAL.TBEP_SOL_BOL_MERITOS bepsbm 
    	INNER JOIN UVIRTUAL.TBEP_MERITOS bepmer ON bepmer.CODNUM = bepsbm.BEPMER_CODNUM
    	WHERE bepmer.BEPITE_CODNUM = 8 AND bepmer.BEPUSU_CODNUM = 5 AND bepsbm.BEPSBO_CODNUM = 3 FETCH FIRST 1 ROWS ONLY),
    (SELECT CODNUM FROM UVIRTUAL.TBEP_AFINIDADES WHERE CODNUM = 2),
    1
);
INSERT INTO UVIRTUAL.TBEP_SOL_BOL_MER_VALORACION (BEPSBM_CODNUM,BEPAFI_CODNUM,VALOR)
VALUES (
    (SELECT bepsbm.CODNUM AS BEPSBM_CODNUM FROM UVIRTUAL.TBEP_SOL_BOL_MERITOS bepsbm 
    	INNER JOIN UVIRTUAL.TBEP_MERITOS bepmer ON bepmer.CODNUM = bepsbm.BEPMER_CODNUM
    	WHERE bepmer.BEPITE_CODNUM = 8 AND bepmer.BEPUSU_CODNUM = 5 AND bepsbm.BEPSBO_CODNUM = 3 FETCH FIRST 1 ROWS ONLY),
    (SELECT CODNUM FROM UVIRTUAL.TBEP_AFINIDADES WHERE CODNUM = 3),
    2
);
INSERT INTO UVIRTUAL.TBEP_SOL_BOL_MER_VALORACION (BEPSBM_CODNUM,BEPAFI_CODNUM,VALOR)
VALUES (
    (SELECT bepsbm.CODNUM AS BEPSBM_CODNUM FROM UVIRTUAL.TBEP_SOL_BOL_MERITOS bepsbm 
    	INNER JOIN UVIRTUAL.TBEP_MERITOS bepmer ON bepmer.CODNUM = bepsbm.BEPMER_CODNUM
    	WHERE bepmer.BEPITE_CODNUM = 4 AND bepmer.BEPUSU_CODNUM = 5 AND bepsbm.BEPSBO_CODNUM = 1 FETCH FIRST 1 ROWS ONLY),
    (SELECT CODNUM FROM UVIRTUAL.TBEP_AFINIDADES WHERE CODNUM = 1),
    1
);
INSERT INTO UVIRTUAL.TBEP_SOL_BOL_MER_VALORACION (BEPSBM_CODNUM,BEPAFI_CODNUM,VALOR)
VALUES (
    (SELECT bepsbm.CODNUM AS BEPSBM_CODNUM FROM UVIRTUAL.TBEP_SOL_BOL_MERITOS bepsbm 
    	INNER JOIN UVIRTUAL.TBEP_MERITOS bepmer ON bepmer.CODNUM = bepsbm.BEPMER_CODNUM
    	WHERE bepmer.BEPITE_CODNUM = 4 AND bepmer.BEPUSU_CODNUM = 5 AND bepsbm.BEPSBO_CODNUM = 1 FETCH FIRST 1 ROWS ONLY),
    (SELECT CODNUM FROM UVIRTUAL.TBEP_AFINIDADES WHERE CODNUM = 2),
    1
);
INSERT INTO UVIRTUAL.TBEP_SOL_BOL_MER_VALORACION (BEPSBM_CODNUM,BEPAFI_CODNUM,VALOR)
VALUES (
    (SELECT bepsbm.CODNUM AS BEPSBM_CODNUM FROM UVIRTUAL.TBEP_SOL_BOL_MERITOS bepsbm 
    	INNER JOIN UVIRTUAL.TBEP_MERITOS bepmer ON bepmer.CODNUM = bepsbm.BEPMER_CODNUM
    	WHERE bepmer.BEPITE_CODNUM = 4 AND bepmer.BEPUSU_CODNUM = 5 AND bepsbm.BEPSBO_CODNUM = 1 FETCH FIRST 1 ROWS ONLY),
    (SELECT CODNUM FROM UVIRTUAL.TBEP_AFINIDADES WHERE CODNUM = 3),
    2
);
INSERT INTO UVIRTUAL.TBEP_SOL_BOL_MER_VALORACION (BEPSBM_CODNUM,BEPAFI_CODNUM,VALOR)
VALUES (
    (SELECT bepsbm.CODNUM AS BEPSBM_CODNUM FROM UVIRTUAL.TBEP_SOL_BOL_MERITOS bepsbm 
    	INNER JOIN UVIRTUAL.TBEP_MERITOS bepmer ON bepmer.CODNUM = bepsbm.BEPMER_CODNUM
    	WHERE bepmer.BEPITE_CODNUM = 4 AND bepmer.BEPUSU_CODNUM = 5 AND bepsbm.BEPSBO_CODNUM = 2 FETCH FIRST 1 ROWS ONLY),
    (SELECT CODNUM FROM UVIRTUAL.TBEP_AFINIDADES WHERE CODNUM = 1),
    1
);
INSERT INTO UVIRTUAL.TBEP_SOL_BOL_MER_VALORACION (BEPSBM_CODNUM,BEPAFI_CODNUM,VALOR)
VALUES (
    (SELECT bepsbm.CODNUM AS BEPSBM_CODNUM FROM UVIRTUAL.TBEP_SOL_BOL_MERITOS bepsbm 
    	INNER JOIN UVIRTUAL.TBEP_MERITOS bepmer ON bepmer.CODNUM = bepsbm.BEPMER_CODNUM
    	WHERE bepmer.BEPITE_CODNUM = 4 AND bepmer.BEPUSU_CODNUM = 5 AND bepsbm.BEPSBO_CODNUM = 2 FETCH FIRST 1 ROWS ONLY),
    (SELECT CODNUM FROM UVIRTUAL.TBEP_AFINIDADES WHERE CODNUM = 2),
    1
);
INSERT INTO UVIRTUAL.TBEP_SOL_BOL_MER_VALORACION (BEPSBM_CODNUM,BEPAFI_CODNUM,VALOR)
VALUES (
    (SELECT bepsbm.CODNUM AS BEPSBM_CODNUM FROM UVIRTUAL.TBEP_SOL_BOL_MERITOS bepsbm 
    	INNER JOIN UVIRTUAL.TBEP_MERITOS bepmer ON bepmer.CODNUM = bepsbm.BEPMER_CODNUM
    	WHERE bepmer.BEPITE_CODNUM = 4 AND bepmer.BEPUSU_CODNUM = 5 AND bepsbm.BEPSBO_CODNUM = 2 FETCH FIRST 1 ROWS ONLY),
    (SELECT CODNUM FROM UVIRTUAL.TBEP_AFINIDADES WHERE CODNUM = 3),
    2
);
INSERT INTO UVIRTUAL.TBEP_SOL_BOL_MER_VALORACION (BEPSBM_CODNUM,BEPAFI_CODNUM,VALOR)
VALUES (
    (SELECT bepsbm.CODNUM AS BEPSBM_CODNUM FROM UVIRTUAL.TBEP_SOL_BOL_MERITOS bepsbm 
    	INNER JOIN UVIRTUAL.TBEP_MERITOS bepmer ON bepmer.CODNUM = bepsbm.BEPMER_CODNUM
    	WHERE bepmer.BEPITE_CODNUM = 17 AND bepmer.BEPUSU_CODNUM = 5 AND bepsbm.BEPSBO_CODNUM = 1 FETCH FIRST 2 ROWS ONLY),
    (SELECT CODNUM FROM UVIRTUAL.TBEP_AFINIDADES WHERE CODNUM = 1),
    NULL
);
INSERT INTO UVIRTUAL.TBEP_SOL_BOL_MER_VALORACION (BEPSBM_CODNUM,BEPAFI_CODNUM,VALOR)
VALUES (
    (SELECT bepsbm.CODNUM AS BEPSBM_CODNUM FROM UVIRTUAL.TBEP_SOL_BOL_MERITOS bepsbm 
    	INNER JOIN UVIRTUAL.TBEP_MERITOS bepmer ON bepmer.CODNUM = bepsbm.BEPMER_CODNUM
    	WHERE bepmer.BEPITE_CODNUM = 17 AND bepmer.BEPUSU_CODNUM = 5 AND bepsbm.BEPSBO_CODNUM = 2 FETCH FIRST 2 ROWS ONLY),
    (SELECT CODNUM FROM UVIRTUAL.TBEP_AFINIDADES WHERE CODNUM = 1),
    NULL
);