-- items bloque I.1;
INSERT INTO TBEP_ITEMSBAREMACION (BEPBLO_CODNUM,CODIGO,NOMBRE,DESCRIPCION,UNIDADES,VALOR,VALOR_MINIMO,VALOR_MAXIMO,AFINIDAD,INDIVIDUALIZADO)
SELECT
    bepblo.CODNUM AS BEPBLO_CODNUM,
    '1' AS CODIGO,
    'Nota media de las asignaturas cursadas en la titulación exigida para la plaza' AS NOMBRE,
    '(A:1, N:2, SB:3 y MH:4)' AS DESCRIPCION,
    'DECIMAL' AS UNIDADES,
    1 AS VALOR,
    1 AS VALOR_MINIMO,
    4 AS VALOR_MAXIMO,
    NULL AS AFINIDAD,
    'N' AS INDIVIDUALIZADO
FROM TBEP_BLOQUESBAREMACION bepblo 
WHERE bepblo.BEPAPA_CODNUM = (SELECT bepapa.CODNUM FROM TBEP_APARTADOSBAREMACION bepapa WHERE bepapa.CODIGO = 'I' FETCH FIRST 1 ROWS ONLY) 
AND bepblo.CODIGO = '1' FETCH FIRST 1 ROWS ONLY;
-- items bloque I.2;
INSERT INTO TBEP_ITEMSBAREMACION (BEPBLO_CODNUM,CODIGO,NOMBRE,DESCRIPCION,UNIDADES,VALOR,VALOR_MINIMO,VALOR_MAXIMO,AFINIDAD,INDIVIDUALIZADO)
SELECT
    bepblo.CODNUM AS BEPBLO_CODNUM,
    '2' AS CODIGO,
    'Premios nacionales' AS NOMBRE,
    NULL AS DESCRIPCION,
    'ENTERO' AS UNIDADES,
    3 AS VALOR,
    1 AS VALOR_MINIMO,
    1000 AS VALOR_MAXIMO,
    NULL AS AFINIDAD,
    'S' AS INDIVIDUALIZADO
FROM TBEP_BLOQUESBAREMACION bepblo 
WHERE bepblo.BEPAPA_CODNUM = (SELECT bepapa.CODNUM FROM TBEP_APARTADOSBAREMACION bepapa WHERE bepapa.CODIGO = 'I' FETCH FIRST 1 ROWS ONLY) 
AND bepblo.CODIGO = '1' FETCH FIRST 1 ROWS ONLY;
-- items bloque II.1;
INSERT INTO TBEP_ITEMSBAREMACION (BEPBLO_CODNUM,CODIGO,NOMBRE,DESCRIPCION,UNIDADES,VALOR,VALOR_MINIMO,VALOR_MAXIMO,AFINIDAD,INDIVIDUALIZADO)
SELECT
    bepblo.CODNUM AS BEPBLO_CODNUM,
    '1' AS CODIGO,
    'Créditos impartidos en docencia reglada de primer y segundo ciclo y grado' AS NOMBRE,
    '1 crédito equivale a 10 h.' AS DESCRIPCION,
    'DECIMAL' AS UNIDADES,
    0.125 AS VALOR,
    0.1 AS VALOR_MINIMO,
    1000 AS VALOR_MAXIMO,
    'AA' AS AFINIDAD,
    'N' AS INDIVIDUALIZADO
FROM TBEP_BLOQUESBAREMACION bepblo 
WHERE bepblo.BEPAPA_CODNUM = (SELECT bepapa.CODNUM FROM TBEP_APARTADOSBAREMACION bepapa WHERE bepapa.CODIGO = 'II' FETCH FIRST 1 ROWS ONLY) 
AND bepblo.CODIGO = '1' FETCH FIRST 1 ROWS ONLY;
-- items bloque III.1;
INSERT INTO TBEP_ITEMSBAREMACION (BEPBLO_CODNUM,CODIGO,NOMBRE,DESCRIPCION,UNIDADES,VALOR,VALOR_MINIMO,VALOR_MAXIMO,AFINIDAD,INDIVIDUALIZADO)
SELECT
    bepblo.CODNUM AS BEPBLO_CODNUM,
    '1' AS CODIGO,
    'Artículos en revistas situadas en el 1er cuartil del Journal Citation Report' AS NOMBRE,
    NULL AS DESCRIPCION,
    'ENTERO' AS UNIDADES,
    3.6 AS VALOR,
    1 AS VALOR_MINIMO,
    1000 AS VALOR_MAXIMO,
    'AI' AS AFINIDAD,
    'S' AS INDIVIDUALIZADO
FROM TBEP_BLOQUESBAREMACION bepblo 
WHERE bepblo.BEPAPA_CODNUM = (SELECT bepapa.CODNUM FROM TBEP_APARTADOSBAREMACION bepapa WHERE bepapa.CODIGO = 'III' FETCH FIRST 1 ROWS ONLY) 
AND bepblo.CODIGO = '1' FETCH FIRST 1 ROWS ONLY;