-- creación registros de prueba para méritos;
INSERT INTO TBEP_MERITOS (BEPITE_CODNUM,BEPUSU_CODNUM,VALOR,DESCRIPCION,OBSERVACION,ARCHIVO)
SELECT
(SELECT bepite.CODNUM AS BEPITE_CODNUM FROM TBEP_ITEMSBAREMACION bepite FETCH FIRST 1 ROWS ONLY),
bepusu.CODNUM AS BEPUSU_CODNUM,
2.4 AS VALOR,
'descripcion mérito 1' AS DESCRIPCION,
'observacion mérito 1' AS OBSERVACION,
hextoraw('453d7a34') AS ARCHIVO
FROM TBEP_USUARIOS bepusu WHERE bepusu.CODNUM = 12 FETCH FIRST 1 ROWS ONLY;
INSERT INTO TBEP_MERITOS (BEPITE_CODNUM,BEPUSU_CODNUM,VALOR,DESCRIPCION,OBSERVACION,ARCHIVO)
SELECT
(SELECT bepite.CODNUM AS BEPITE_CODNUM FROM TBEP_ITEMSBAREMACION bepite WHERE bepite.CODNUM = 2),
bepusu.CODNUM AS BEPUSU_CODNUM,
4 AS VALOR,
'descripcion mérito 2' AS DESCRIPCION,
'observacion mérito 2' AS OBSERVACION,
hextoraw('453d7a34') AS ARCHIVO
FROM TBEP_USUARIOS bepusu WHERE bepusu.CODNUM = 12 FETCH FIRST 1 ROWS ONLY;
INSERT INTO TBEP_MERITOS (BEPITE_CODNUM,BEPUSU_CODNUM,VALOR,DESCRIPCION,OBSERVACION,ARCHIVO)
SELECT
(SELECT bepite.CODNUM AS BEPITE_CODNUM FROM TBEP_ITEMSBAREMACION bepite WHERE bepite.CODNUM = 3),
bepusu.CODNUM AS BEPUSU_CODNUM,
3 AS VALOR,
'descripcion mérito 3' AS DESCRIPCION,
'observacion mérito 3' AS OBSERVACION,
hextoraw('453d7a34') AS ARCHIVO
FROM TBEP_USUARIOS bepusu WHERE bepusu.CODNUM = 12 FETCH FIRST 1 ROWS ONLY;