-- creación registros de prueba para titulaciones del usuario;
INSERT INTO TBEP_TITULACIONES_USUARIO (BEPTUS_TIT_CODNUM, BEPTUS_USU_CODNUM,DESCRIPCION,ARCHIVO)
SELECT
(SELECT beptit.CODNUM AS BEPTUS_TIT_CODNUM FROM TBEP_TITULACIONES beptit FETCH FIRST 1 ROWS ONLY),
bepusu.CODNUM AS BEPTUS_USU_CODNUM,
'descripcion titulación 1' AS DESCRIPCION,
hextoraw('453d7a34') AS ARCHIVO
FROM TBEP_USUARIOS bepusu WHERE bepusu.CODNUM = 12 FETCH FIRST 1 ROWS ONLY;
INSERT INTO TBEP_TITULACIONES_USUARIO (BEPTUS_TIT_CODNUM, BEPTUS_USU_CODNUM,DESCRIPCION,ARCHIVO,FLGVALIDADA)
SELECT
(SELECT beptit.CODNUM AS BEPTUS_TIT_CODNUM FROM TBEP_TITULACIONES beptit WHERE beptit.CODNUM = 2),
bepusu.CODNUM AS BEPTUS_USU_CODNUM,
'descripcion titulación 1' AS DESCRIPCION,
hextoraw('453d7a34') AS ARCHIVO,
'S' AS FLGVALIDADA
FROM TBEP_USUARIOS bepusu WHERE bepusu.CODNUM = 12 FETCH FIRST 1 ROWS ONLY;
INSERT INTO TBEP_TITULACIONES_USUARIO (BEPTUS_TIT_CODNUM, BEPTUS_USU_CODNUM,DESCRIPCION,ARCHIVO)
SELECT
(SELECT beptit.CODNUM AS BEPTUS_TIT_CODNUM FROM TBEP_TITULACIONES beptit WHERE beptit.CODNUM = 3),
bepusu.CODNUM AS BEPTUS_USU_CODNUM,
'descripcion titulación 1' AS DESCRIPCION,
hextoraw('453d7a34') AS ARCHIVO
FROM TBEP_USUARIOS bepusu WHERE bepusu.CODNUM = 12 FETCH FIRST 1 ROWS ONLY;