CREATE TRIGGER DARG_USUARIO_BRI
BEFORE INSERT
ON ARG_USUARIO 
FOR EACH ROW
DECLARE
BEGIN
    INSERT INTO ARG_HTO_CAMBIOS (CODCAMBIO,	DATCAMBIO, USUARIO,	CORREO,	ATRIBUTO, OPERACION, VALORANTERIOR, VALORNUEVO)
    VALUES (sec_arg_cambio_hto.nextval, sysdate, :New.USUARIO, null, 'usuario', 'A', null, :New.USUARIO);
END DARG_USUARIO_BRI;
--/////////////////////
CREATE TRIGGER DARG_USUARIO_BRU
BEFORE UPDATE
ON ARG_USUARIO 
FOR EACH ROW
DECLARE
BEGIN
	IF UPDATING ('USUARIO') THEN
	    INSERT INTO ARG_HTO_CAMBIOS (CODCAMBIO,	DATCAMBIO, USUARIO,	CORREO,	ATRIBUTO, OPERACION, VALORANTERIOR, VALORNUEVO)
	    VALUES (sec_arg_cambio_hto.nextval, sysdate, :New.USUARIO, null, 'usuario', 'C', :old.USUARIO, :New.USUARIO);
    END IF;
	IF UPDATING ('NOMBRE') THEN
	    INSERT INTO ARG_HTO_CAMBIOS (CODCAMBIO,	DATCAMBIO, USUARIO,	CORREO,	ATRIBUTO, OPERACION, VALORANTERIOR, VALORNUEVO)
	    VALUES (sec_arg_cambio_hto.nextval, sysdate, :New.USUARIO, null, 'NOMBRE', 'C', :old.NOMBRE, :New.NOMBRE);
    END IF;
	IF UPDATING ('APELLIDO1') THEN
	    INSERT INTO ARG_HTO_CAMBIOS (CODCAMBIO,	DATCAMBIO, USUARIO,	CORREO,	ATRIBUTO, OPERACION, VALORANTERIOR, VALORNUEVO)
	    VALUES (sec_arg_cambio_hto.nextval, sysdate, :New.USUARIO, null, 'APELLIDO1', 'C', :old.APELLIDO1, :New.APELLIDO1);
    END IF;
	IF UPDATING ('APELLIDO2') THEN
	    INSERT INTO ARG_HTO_CAMBIOS (CODCAMBIO,	DATCAMBIO, USUARIO,	CORREO,	ATRIBUTO, OPERACION, VALORANTERIOR, VALORNUEVO)
	    VALUES (sec_arg_cambio_hto.nextval, sysdate, :New.USUARIO, null, 'APELLIDO2', 'C', :old.APELLIDO2, :New.APELLIDO2);
    END IF;
	IF UPDATING ('DOCUMENTO') THEN
	    INSERT INTO ARG_HTO_CAMBIOS (CODCAMBIO,	DATCAMBIO, USUARIO,	CORREO,	ATRIBUTO, OPERACION, VALORANTERIOR, VALORNUEVO)
	    VALUES (sec_arg_cambio_hto.nextval, sysdate, :New.USUARIO, null, 'DOCUMENTO', 'C', :old.DOCUMENTO, :New.DOCUMENTO);
    END IF;
	IF UPDATING ('TIPODOCUMENTO') THEN
	    INSERT INTO ARG_HTO_CAMBIOS (CODCAMBIO,	DATCAMBIO, USUARIO,	CORREO,	ATRIBUTO, OPERACION, VALORANTERIOR, VALORNUEVO)
	    VALUES (sec_arg_cambio_hto.nextval, sysdate, :New.USUARIO, null, 'TIPODOCUMENTO', 'C', :old.TIPODOCUMENTO, :New.TIPODOCUMENTO);
    END IF;
END DARG_USUARIO_BRU;
--/////////////////////
CREATE TRIGGER DARG_USUARIO_BRD
BEFORE DELETE
ON ARG_USUARIO
FOR EACH ROW
DECLARE
BEGIN
    INSERT INTO ARG_HTO_CAMBIOS (CODCAMBIO,	DATCAMBIO, USUARIO,	CORREO,	ATRIBUTO, OPERACION, VALORANTERIOR, VALORNUEVO)
    VALUES (sec_arg_cambio_hto.nextval, sysdate, :Old.USUARIO, null, 'usuario', 'B', :old.USUARIO, null);
END DARG_USUARIO_BRD;
--/////////////////////
--/////////////////////
CREATE TRIGGER DARG_CUENTA_BRI
BEFORE INSERT
ON ARG_CUENTA 
FOR EACH ROW
DECLARE
BEGIN
    INSERT INTO ARG_HTO_CAMBIOS (CODCAMBIO,	DATCAMBIO, USUARIO,	CORREO,	ATRIBUTO, OPERACION, VALORANTERIOR, VALORNUEVO)
    VALUES (sec_arg_cambio_hto.nextval, sysdate, :New.USUARIO, :new.CORREO, 'cuenta', 'A', null, :New.USUARIO);
END DARG_CUENTA_BRI;
--/////////////////////
CREATE TRIGGER DARG_CUENTA_BRU
BEFORE UPDATE
ON ARG_CUENTA 
FOR EACH ROW
DECLARE
BEGIN
	IF UPDATING ('CORREO') THEN
	    INSERT INTO ARG_HTO_CAMBIOS (CODCAMBIO,	DATCAMBIO, USUARIO,	CORREO,	ATRIBUTO, OPERACION, VALORANTERIOR, VALORNUEVO)
	    VALUES (sec_arg_cambio_hto.nextval, sysdate, :New.USUARIO, :new.correo, 'CORREO', 'C', :old.CORREO, :New.CORREO);
	END IF;
	IF UPDATING ('CLAVE') THEN
	    INSERT INTO ARG_HTO_CAMBIOS (CODCAMBIO,	DATCAMBIO, USUARIO,	CORREO,	ATRIBUTO, OPERACION, VALORANTERIOR, VALORNUEVO)
	    VALUES (sec_arg_cambio_hto.nextval, sysdate, :New.USUARIO, :new.correo, 'CLAVE', 'C', :old.CLAVE, :New.CLAVE);
	END IF;
END DARG_CUENTA_BRU;
--/////////////////////
CREATE TRIGGER DARG_CUENTA_BRD
BEFORE DELETE
ON ARG_CUENTA
FOR EACH ROW
DECLARE
BEGIN
    INSERT INTO ARG_HTO_CAMBIOS (CODCAMBIO,	DATCAMBIO, USUARIO,	CORREO,	ATRIBUTO, OPERACION, VALORANTERIOR, VALORNUEVO)
    VALUES (sec_arg_cambio_hto.nextval, sysdate, :Old.USUARIO, :old.correo, 'cuenta', 'B', :old.USUARIO, null);
END DARG_CUENTA_BRD;
